### ISSUE TITLE
Dynamic layernorm test fails on Pixel 6

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#10024]
https://github.com/iree-org/iree/pull/10011 enabled more layernorm tests. It is failing on Pixel 6 right now:

https://buildkite.com/iree/iree-test-android/builds/6859
https://buildkite.com/iree/iree-test-android/builds

**Comment by antiagainst** [comment]
There are 4 dispatches for the test case. In dispatch#2, we are computing (5 - 1920 * 0.00260417). NVIDIA GPU gives 0 as the result, but for some reason on Pixel 6 Mail GPUs gives -1.49012E-07 as the result..

**Comment by benvanik** [comment]
Mali seems more right there - very small negative number :P Can we almost-equals compare instead? (e-6/e-7 is pretty tiny)

**Comment by okkwon** [comment]
1e-07 is not really very small in fp32 while it is very small for fp16. The normal (not subnormal) min is 1.175494350822287508e-38 for fp32. The test uses `check.expect_almost_eq` currently. We should investigate more to check where to diverge.

**Comment by okkwon** [comment]
There might be a fused instruction which affect the accuracy. For example, x*x might produce a different value from pow(x, 2). There are several cases, which can affect the accuracy, e.g., fma, recip, and ... along with the rounding mode.

**Comment by antiagainst** [comment]
Closing as obsolete -- no plans of action on this right now
