### ISSUE TITLE
Performance issue with `torch.linear` op

### ISSUE THREAD

**Issue by ramiro050** [iree-org/iree#10038]
### Request description

I am currently benchmarking a Bert model, and I noticed that the time it takes for the model to run the PyTorch op [`torch.linear`](https://pytorch.org/docs/stable/generated/torch.nn.functional.linear.html?highlight=linear#torch.nn.functional.linear) with IREE+CUDA is at least 40x slower than with PyTorch+CUDA using eager mode.

The MLIR for the op is:

```mlir
#map0 = affine_map<(d0, d1, d2) -> (d2)>
#map1 = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
#map2 = affine_map<(d0, d1, d2) -> (d2, d1)>
module attributes {torch.debug_module_name = "MyModule"} {
  func.func @forward(%arg0: tensor<1x512x768xf32>, %arg1: tensor<30522x768xf32>, %arg2: tensor<30522xf32>) -> tensor<1x512x30522xf32> {
    %0 = linalg.init_tensor [1, 512, 30522] : tensor<1x512x30522xf32>
    %1 = linalg.init_tensor [1, 768, 30522] : tensor<1x768x30522xf32>
    %2 = linalg.generic {indexing_maps = [#map0, #map1], iterator_types = ["parallel", "parallel", "parallel"]} ins(%arg2 : tensor<30522xf32>) outs(%0 : tensor<1x512x30522xf32>) {
    ^bb0(%arg3: f32, %arg4: f32):
      linalg.yield %arg3 : f32
    } -> tensor<1x512x30522xf32>
    %3 = linalg.generic {indexing_maps = [#map2, #map1], iterator_types = ["parallel", "parallel", "parallel"]} ins(%arg1 : tensor<30522x768xf32>) outs(%1 : tensor<1x768x30522xf32>) {
    ^bb0(%arg3: f32, %arg4: f32):
      linalg.yield %arg3 : f32
    } -> tensor<1x768x30522xf32>
    %4 = linalg.batch_matmul ins(%arg0, %3 : tensor<1x512x768xf32>, tensor<1x768x30522xf32>) outs(%2 : tensor<1x512x30522xf32>) -> tensor<1x512x30522xf32>
    return %4 : tensor<1x512x30522xf32>
  }
}
```

Generated from the module

```python
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, result0, var0, var1):
        var8 = torch.ops.aten.linear(result0, var0, var1)
        return var8
```

When I compile it using

```python
ireec.compile_str(str(linalg_module), target_backends=['cuda'], input_type=ireec.InputType.TM_TENSOR, output_file="compiled-module.vmfb", enable_benchmark=True)
```

and benchmark it using `~/iree-build-release/tools/iree-benchmark-module --module_file=compiled-module.vmfb --device=cuda://GPU...` I get:

```
022-08-09T16:44:06+00:00
Running /home/ramiroleal/iree-build-release/tools/iree-benchmark-module
Run on (12 X 2200.2 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x6)
  L1 Instruction 32 KiB (x6)
  L2 Unified 1024 KiB (x6)
  L3 Unified 39424 KiB (x1)
Load Average: 0.13, 0.15, 0.16
--------------------------------------------------------------------------------------
Benchmark                                            Time             CPU   Iterations
--------------------------------------------------------------------------------------
BM_forward_benchmark/process_time/real_time       36.0 ms         36.0 ms           18
```

On the other hand, when I time the PyTorch+CUDA execution, I get a total time of around 0.1 ms. If I instead use the NVIDIA tool `ncu` to get the duration of each dispatch, I get that the IREE version takes around 40 ms to run and the PyTorch version takes around 1 ms to run.

### What component(s) does this issue relate to?

Compiler

**Comment by ThomasRaoux** [comment]
There is a non-aligned matmul (30522 is only aligned on 2) that causes matmul codegen to fall through the slow path. We have plans to address unaligned matmul codegen this quarter which should take care of this.

**Comment by ThomasRaoux** [comment]
@ramiro050, is this a blocking perf problem? What is the impact on your work?

**Comment by ramiro050** [comment]
> @ramiro050, is this a blocking perf problem? What is the impact on your work?

It is not blocking. Having this fixed this quarter works!

> There is a non-aligned matmul

What properties should the dimensions satisfy to be aligned? I think for now I can change some hyperparameters in my model to make sure the matmuls get the fast codegen

**Comment by antiagainst** [comment]
closing as obsolete--no plan of actions
