### ISSUE TITLE
TFL/test/flex_ops.mlir using outdated opaque attribute

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#10091]
Disabling test as part of integrate. It should be relatively easy to regenerate from the source once new binaries are available. Should also evaluate whether this test is needed anymore.

**Comment by jpienaar** [comment]
https://github.com/tensorflow/tensorflow/commit/dd5f285c13b2bed2c7db78f521d7a760dbf43ec5 may be of use.

**Comment by alliemartens** [comment]
Adding @NatashaKnk to take a look while on frontend rotation this week.

**Comment by alliemartens** [comment]
@rsuderman @NatashaKnk Can you help triage this with a priority and some labels?

**Comment by rsuderman** [comment]
Should be a pretty easy fix, we will just need to see what changed for TFLite's flex ops.
