### ISSUE TITLE
Run on a Bare-Metal Platform (static_library)

### ISSUE THREAD

**Issue by Theoo1997** [iree-org/iree#10108]
Hi,
I am trying to build and run [IREE "Static Library" sample](https://github.com/iree-org/iree/tree/main/samples/static_library) without building IREE from scratch. I've noticed that the IREE "Static Library" sample has its own [CMake](https://github.com/iree-org/iree/blob/main/samples/static_library/CMakeLists.txt) so I've used this cmake (cmake , cmake --build) to create the executables (static_library_demo_test, static_library_demo_c_test). The problem is that after I've used this cmake file no executables were created.

**Comment by marbre** [comment]
I think you want to look into https://iree-org.github.io/iree/deployment-configurations/bare-metal/. Further, https://github.com/iml130/iree-bare-metal-arm is doing what you want: We use a snapshot and only cross-compile the runtime for the bare-metal target.

**Comment by Theoo1997** [comment]
> I think you want to look into https://iree-org.github.io/iree/deployment-configurations/bare-metal/ and https://iree-org.github.io/iree/building-from-source/riscv/#bare-metal-execution-example (for RSIC-V). Further, https://github.com/iml130/iree-bare-metal-arm is doing what you want: We use a snapshot and only cross-compile the runtime for the bare-metal target.

Yes I've seen this links before. They are not related with my issue. Ι only need to a make a NN executable for x86. The above instructions build IREE from scratch and then generate static_library_demo executable. 
![image](https://user-images.githubusercontent.com/109102287/184897733-907e12f7-5d72-406e-a8c9-843a7634122b.png)
 I only wont to generate static_library_demo executable and not build IREE (takes time). So I've used this [CMake](https://github.com/iree-org/iree/blob/main/samples/static_library/CMakeLists.txt) without any success. Can I use the above cmake to create static_library_demo? And if I can what would be the steps to do it ?

**Comment by ScottTodd** [comment]
You might also want to take a look at https://github.com/iree-org/iree/tree/main/experimental/web/sample_static, particularly the [`CMakeLists.txt`](https://github.com/iree-org/iree/blob/main/experimental/web/sample_static/CMakeLists.txt) and [`build_sample.sh`](https://github.com/iree-org/iree/blob/main/experimental/web/sample_static/build_sample.sh) files. That uses a prebuilt `iree-compile` in the script and then links the output of that in via the CMake file.

**Comment by ScottTodd** [comment]
> > You might also want to take a look at https://github.com/iree-org/iree/tree/main/experimental/web/sample_static, particularly the [`CMakeLists.txt`](https://github.com/iree-org/iree/blob/main/experimental/web/sample_static/CMakeLists.txt) and [`build_sample.sh`](https://github.com/iree-org/iree/blob/main/experimental/web/sample_static/build_sample.sh) files. That uses a prebuilt `iree-compile` in the script and then links the output of that in via the CMake file.
> 
> So I can't use the cmake that I mentioned to generate an executable without compiling IREE from scratch?

You can start with that file, but you'll need to make edits if you want to avoid compiling IREE from scratch. The checks at the start depend on building the `iree-compile` compiler binary and a few CMake options being set: https://github.com/iree-org/iree/blob/99caaec7072c02997434e711edd6e722dfca8ff9/samples/static_library/CMakeLists.txt#L7-L14

Further down there are more checks for optional features in the build: https://github.com/iree-org/iree/blob/99caaec7072c02997434e711edd6e722dfca8ff9/samples/static_library/CMakeLists.txt#L97-L99

Some debugging with CMake's [`message()`](https://cmake.org/cmake/help/latest/command/message.html) and configuring should help you see what parts of the CMake file are running and which values they use.

**Comment by Theoo1997** [comment]
> > > You might also want to take a look at https://github.com/iree-org/iree/tree/main/experimental/web/sample_static, particularly the [`CMakeLists.txt`](https://github.com/iree-org/iree/blob/main/experimental/web/sample_static/CMakeLists.txt) and [`build_sample.sh`](https://github.com/iree-org/iree/blob/main/experimental/web/sample_static/build_sample.sh) files. That uses a prebuilt `iree-compile` in the script and then links the output of that in via the CMake file.
> > 
> > 
> > So I can't use the cmake that I mentioned to generate an executable without compiling IREE from scratch?
> 
> You can start with that file, but you'll need to make edits if you want to avoid compiling IREE from scratch. The checks at the start depend on building the `iree-compile` compiler binary and a few CMake options being set:
> 
> https://github.com/iree-org/iree/blob/99caaec7072c02997434e711edd6e722dfca8ff9/samples/static_library/CMakeLists.txt#L7-L14
> 
> Further down there are more checks for optional features in the build:
> 
> https://github.com/iree-org/iree/blob/99caaec7072c02997434e711edd6e722dfca8ff9/samples/static_library/CMakeLists.txt#L97-L99
> 
> Some debugging with CMake's [`message()`](https://cmake.org/cmake/help/latest/command/message.html) and configuring should help you see what parts of the CMake file are running and which values they use.

Thank you. I am closing this issue.
