### ISSUE TITLE
Fusing tensor.pad with consumer for LLVMCPU pipeline

### ISSUE THREAD

**Issue by harsh-nod** [iree-org/iree#10178]
### What happened?

In order to improve Resnet-50 performance on the CPU, the idea was to fuse the tensor.pad op with its consumers (following what is happening in the SPIR-V pipeline) in the LLVMCPU pipeline.

The first prototype of this is here -
https://github.com/harsh-nod/iree/commit/3250f9d0bfed511448a0015e70c684c51cd7ddea

This works for the following conv example
```
func.func @_main(%input: tensor<1x112x112x32xf32>, %filter: tensor<3x3x32x1xf32>, %bias: tensor<32xf32>) -> tensor<1x112x112x32xf32> attributes {iree.module.export} {
    %108 = "tosa.depthwise_conv2d"(%input, %filter, %bias) {dilation = [1, 1], pad = [1, 1, 1, 1], stride = [1, 1]} : (tensor<1x112x112x32xf32>, tensor<3x3x32x1xf32>, tensor<32xf32>) -> tensor<1x112x112x32xf32>
    return %108 : tensor<1x112x112x32xf32>
}
```

But doesn't work for the entire model.

Specifically, we run into an IREEBufferization error when compiling the following dispatch region.
```
func.func @predict_dispatch_1_pooling_nhwc_max_1x56x56x64x3x3(%0: tensor<1x112x112x64xf32>) -> tensor<1x56x56x64xf32> {
  %cst = arith.constant 0.000000e+00 : f32
  %cst_0 = arith.constant 0xFF800000 : f32
  %1 = linalg.init_tensor [3, 3] : tensor<3x3xf32>
  %2 = tensor.pad %0 low[0, 1, 1, 0] high[0, 1, 1, 0] {
  ^bb0(%arg2: index, %arg3: index, %arg4: index, %arg5: index):
    tensor.yield %cst : f32
  } : tensor<1x112x112x64xf32> to tensor<1x114x114x64xf32>
  %3 = linalg.init_tensor [1, 56, 56, 64] : tensor<1x56x56x64xf32>
  %4 = linalg.fill ins(%cst_0 : f32) outs(%3 : tensor<1x56x56x64xf32>) -> tensor<1x56x56x64xf32>
  %5 = linalg.pooling_nhwc_max {dilations = dense<1> : vector<2xi64>, strides = dense<2> : vector<2xi64>} ins(%2, %1 : tensor<1x114x114x64xf32>, tensor<3x3xf32>) outs(%4 : tensor<1x56x56x64xf32>) -> tensor<1x56x56x64xf32>
  return %5 : tensor<1x56x56x64xf32>
}
```

It seems like this dispatch region is being lowered using the CPU default pass pipeline which means
that apart from tiling and distributing to workgroups, no more tiling and vectorization is done. How does
the current bufferization pipeline handle tensor.pad ops that have not been vectorized? If the
bufferization does not handle tensor.pad ops or assumes that none are left prior to bufferization, then
that could be the problem.

In the case of the convolution where bufferization succeeds, we convert tensor.pad to its vector equivalent
and hence don't run into this problem.

### Steps to reproduce your issue

1. Save the above mlir file into pool.mlir
2. Run the following command ```iree-compile --iree-input-type=tosa --iree-hal-target-backends=vulkan-spirv --iree-vulkan-target-triple=valhall-unknown-android11 --iree-flow-enable-fuse-padding-into-consumer-ops -mlir-disable-threading -mlir-print-ir-after-all pool.mlir -o pool.vmfb```
3. Can run the same command with the LLVMCPU pipeline as well ```iree-compile --iree-input-type=tosa --iree-hal-target-backends=llvm-cpu --iree-flow-enable-fuse-padding-into-consumer-ops -mlir-disable-threading -mlir-print-ir-after-all pool.mlir -o pool.vmfb```
4. See the error ```pool.mlir:5:8: error: op was not bufferized
  %2 = tensor.pad %0 low[0, 1, 1, 0] high[0, 1, 1, 0] {
       ^
pool.mlir:1:1: note: called from
func.func @predict_dispatch_1_pooling_nhwc_max_1x56x56x64x3x3(%0: tensor<1x112x112x64xf32>) -> tensor<1x56x56x64xf32> {
^
pool.mlir:5:8: note: see current operation: %12 = "tensor.pad"(%9) ({
^bb0(%arg0: index, %arg1: index, %arg2: index, %arg3: index):
  "tensor.yield"(%3) : (f32) -> ()
}) {operand_segment_sizes = array<i32: 1, 0, 0>, static_high = [0, 1, 1, 0], static_low = [0, 1, 1, 0]} : (tensor<1x112x112x64xf32>) -> tensor<1x114x114x64xf32>
  %2 = tensor.pad %0 low[0, 1, 1, 0] high[0, 1, 1, 0] {
       ^
// -----// IR Dump After IREEComprehensiveBufferize Failed (iree-codegen-iree-comprehensive-bufferize) //----- //```

### What component(s) does this issue relate to?

Compiler

### Version information

e4dc88c3d1f6bd7d88cf418e775e549d4e8b6e37 + patch reference above (in harsh-nod fork)

**Comment by MaheshRavishankar** [comment]
@harsh-nod try patching this in https://reviews.llvm.org/D132355

**Comment by harsh-nod** [comment]
Thanks! That helps because now tensor.pad is getting bufferized. But we get a new error related to allocations
```
error: 'builtin.module' op expected total size of stack allocation is not greater than 32768 bytes, but got 215296 bytes
  %5 = linalg.pooling_nhwc_max {dilations = dense<1> : vector<2xi64>, strides = dense<2> : vector<2xi64>} ins(%2, %1 : tensor<1x114x114x64xf32>, tensor<3x3xf32>) outs(%4 : tensor<1x56x56x64xf32>) -> tensor<1x56x56x64xf32>
```

**Comment by MaheshRavishankar** [comment]
To unblock,you can increase the limit here https://github.com/iree-org/iree/blob/ae72b956ea0701482fb95d170b40ed82e0e4ef46/compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUCheckIRBeforeLLVMConversion.cpp#L19 . Eventually to land this we should just avoid fusion pad with pooling op consumers.

**Comment by alliemartens** [comment]
8/25 meeting: fixed, can close

**Comment by hanhanW** [comment]
This is done in https://github.com/iree-org/iree/pull/10458
