### ISSUE TITLE
Add metadata to models in Shark Tank

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#10200]
For all models in the Shark Tank, please add and log the metadata in [this sheet](https://docs.google.com/spreadsheets/d/1a78kfOcp4k9i7sUo-NB0CpsIWCJNL2dllDzB7VXo4YA/edit?resourcekey=0-7tAKlY3iDTG6Tc_u78-6BQ#gid=0). Specifically: data type, param count, tags and comments.

**Comment by powderluv** [comment]
@monorimet @dan-garvey

**Comment by monorimet** [comment]
Hi Marie,

We have sent up a patch to include this metadata in our benchmark results.
Please take a look.
https://github.com/nod-ai/SHARK/pull/297

**Comment by mariecwhite** [comment]
Thanks Ean, this looks great!

**Comment by erob710** [comment]
Confirmed. Can close.
