### ISSUE TITLE
iree-compile fails to compile TOSA MLIR (imported from some TFLite models) for VMVX backend

### ISSUE THREAD

**Issue by lundong** [iree-org/iree#10253]
### What happened?

After importing some TFLite models via TOSA, iree-compile cannot compile the imported TOSA MLIR into vmfb for the VMVX backend. It works fine for llvm-cpu backend though.

A failed tflite example is the person detection model: https://storage.googleapis.com/iree-model-artifacts/person_detect.tflite

### Steps to reproduce your issue

1. Build IREE
2. Import TFLite model (use person.detect.tflite as an example) 
path/to/iree/integrations/tensorflow/iree_tf_compiler/iree-import-tflite path/to/person_detect.tflite -o=/tmp/person_detect.mlir
3. Use iree-compile to compile TOSA MLIR
path/to/iree/tools/iree-compile -iree-input-type=tosa -iree-hal-target-backends=vmvx /tmp/person_detect.mlir -o /tmp/person_detect.vmfb
error: failed to legalize operation 'arith.extui' that was explicitly marked illegal ...

### What component(s) does this issue relate to?

Compiler

### Version information

IREE ToT

### Additional context

This issue could have been a known issue, but not been resolved for quite a while.

**Comment by hcindyl** [comment]
Correction: person_detection model can be found at https://storage.googleapis.com/iree-model-artifacts/person_detect.tflite

**Comment by ScottTodd** [comment]
The IR right before the error, as well as the full error message for `error: failed to legalize operation 'arith.extui' that was explicitly marked illegal` would be useful in triaging this. I suspect we're just missing some lowerings from `arith` to IREE's VM dialect. New ops get added periodically, and the VM lowerings aren't exhaustively tested.

**Comment by NatashaKnk** [comment]
Should be fixed with [10534](https://github.com/iree-org/iree/pull/10534), closing this.
