### ISSUE TITLE
Seeing duplicated benchmarks with large variance

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#10267]
Benchmark results show multiple runs with the same configuration but with a large difference in latency. For example:

resnet50,tensorflow,True,mhlo,cpu,17.004667025195612,58.807384967803955,100,2022-08-31 01:28:42.039942
resnet50,shark_python,True,mhlo,cpu,40.70748637358883,24.565505981445312,100,2022-08-31 01:28:44.619628
resnet50,shark_iree_c,True,mhlo,cpu,**40.65040650406504**,24.6,100,2022-08-31 01:28:45.714299
resnet50,tensorflow,False,mhlo,cpu,17.0901621626379,58.513195514678955,100,2022-08-31 01:30:11.689923
resnet50,shark_python,False,mhlo,cpu,39.74879520789748,25.157995223999023,100,2022-08-31 01:30:14.332538
resnet50,shark_iree_c,False,mhlo,cpu,**1.736111111111111**,576.0000000000001,100,2022-08-31 01:30:15.018194

**Comment by mariecwhite** [comment]
@monorimet @dan-garvey

**Comment by powderluv** [comment]
Can we please add @monorimet @dan-garvey to IREE project and assign directly to them ?

We should also run this on the new n2-highcpu instances for cpu numbers.

**Comment by monorimet** [comment]
Hey there -- 
The results posted above look correct. There are three cases with dynamic shapes (indicated by "True" here, but in ToM it should say dynamic/static) and three static cases. 

Was this the only case besides the ones we saw with Alexnet?

**Comment by mariecwhite** [comment]
Oh yes sorry about that, didn't realize one result was for dynamic shapes and the other for static shapes. It's just Alexnet from the last time I ran it.

**Comment by monorimet** [comment]
Ok cool! The duplicate alexnet results ended up being caused by a clerical error. It is resolved by this PR: https://github.com/nod-ai/SHARK/pull/322

**Comment by mariecwhite** [comment]
Thanks Ean. Closing issue.
