### ISSUE TITLE
Duplicate fuses in the fusion heuristic worklist 

### ISSUE THREAD

**Issue by pzread** [iree-org/iree#10296]
This is an issue on the WIP branch https://github.com/iree-org/iree/compare/fusion_heuristics and #10177

The worklist https://github.com/iree-org/iree/commit/714c3ca6215c4afdcdce3e7f435360ebad9e0c95#diff-c9f4338d6d7230f44399f248a85d6a631c264bf976c0c80a6d48eadcf442d7acR1073-R1090 will fuse and traverse the same producer multiple times (from its uses), which might require exponential time to finish the worklist. This causes that MiniLM compilation couldn't be finished.

Adding a visited producer set to avoid duplicate traversal can solve the issue.

**Comment by pzread** [comment]
Realized https://github.com/iree-org/iree/commit/714c3ca6215c4afdcdce3e7f435360ebad9e0c95#diff-c9f4338d6d7230f44399f248a85d6a631c264bf976c0c80a6d48eadcf442d7acR1078 should stop the duplicate fuse, not sure why it doesn't work. Need to dig in a little bit more.

**Comment by pzread** [comment]
I see. The real issue is we wrongly push the producer into the worklist even if it's not fusable, then the check on fusion group attr can't stop the exponential traversal.

https://github.com/iree-org/iree/commit/714c3ca6215c4afdcdce3e7f435360ebad9e0c95#diff-c9f4338d6d7230f44399f248a85d6a631c264bf976c0c80a6d48eadcf442d7acR1088

**Comment by MaheshRavishankar** [comment]
> I see. The real issue is we wrongly push the producer into the worklist even if it's not fusable, then the check on fusion group attr can't stop the exponential traversal.
> 
> [714c3ca#diff-c9f4338d6d7230f44399f248a85d6a631c264bf976c0c80a6d48eadcf442d7acR1088](https://github.com/iree-org/iree/commit/714c3ca6215c4afdcdce3e7f435360ebad9e0c95#diff-c9f4338d6d7230f44399f248a85d6a631c264bf976c0c80a6d48eadcf442d7acR1088)

yeah, thats true. Hopefully that is easier to fix.

**Comment by pzread** [comment]
Fixed by bb39517d85fa8306fad15a7d34beafe772cabbca

**Comment by MaheshRavishankar** [comment]
Ship  it. No need to send PR. Just push to branch
