### ISSUE TITLE
Mhlo ops are illegal when I try MobileNet v2 example in tutorial

### ISSUE THREAD

**Issue by MetaBoat** [iree-org/iree#10294]
I'm following the tutorial at [https://iree-org.github.io/iree/deployment-configurations/#compile-the-model](url) to compile the mobilenet_v2.mlir to CPU deployable format.
```
iree/build/tools/iree-compile \
    --iree-hal-target-backends=llvm-cpu \
    mobilenet_v2.mlir -o mobilenet_cpu.vmfb
```
Neither of pip-install or build-from-source iree-compile tools can compile the mlir to vmfb because of illegal mhlo ops: 
```
error: The following illegal operations still remain: 
        mhlo.reshape (count: 18)
        mhlo.batch_norm_inference (count: 52)
        mhlo.convolution (count: 53)
        mhlo.clamp (count: 35)
        mhlo.reduce_window (count: 1)
        mhlo.add (count: 2)
        mhlo.constant (count: 5)
        mhlo.return (count: 1)
```
Is the tutorial out of date? Or If I did't use the right commands to compile the program please tell me the right way to deploy the tf models. Thx alot.

**Comment by ScottTodd** [comment]
Those docs should be updated to include the `--iree-input-type=mhlo` flag, sorry about that. I also thought we had an error message that would hint about that (or ideas around auto-detecting the input type)... and there was a fairly recent discussion about that which I can't find right now.

**Comment by MetaBoat** [comment]
Thanks @ScottTodd  for fixing this.
