### ISSUE TITLE
Person Detect TFLite model has invalid quant params

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#10292]
### What happened?

Unable to benchmark person_detect.tflite with the TFLite benchmarking tool because of error:

```
Graph: [/data/local/tmp/benchmarks/models/tflite/person_detect.tflite]
#threads used for CPU inference: [1]
Loaded model /data/local/tmp/benchmarks/models/tflite/person_detect.tflite
INFO: Initialized TensorFlow Lite runtime.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 33 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 36 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 40 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 44 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 48 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 52 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 56 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 60 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 64 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 68 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 72 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 76 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 80 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 84 has invalid quantization parameters.
Failed to initialize the interpreter
Benchmarking failed.
```

It looks like we'll need to re-run post-quantization training to fix the quant params. Guide to retrain and re-quantize: https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/examples/person_detection/training_a_model.md

**Comment by hanhanW** [comment]
Thanks for filing the issue, I just hit the same issue when running benchmarks!

**Comment by mariecwhite** [comment]
No worries. I've started following the instructions. It's currently training on my workstation.

**Comment by hcindyl** [comment]
It is a known issue from TFLM (an internal bug has been filed to track this). The model was trained differently and can only be handled by TFLM interpreter, but not the TFLite interpreter. That's why a mock interpreter was put in https://github.com/iree-org/iree-samples/blob/main/tflitehub/person_detect_test.py#L20

I would recommend against not re-train this model since it is a direct copy from the TFLM codebase.

**Comment by allieculp** [comment]
@mariecwhite Is this still open?

**Comment by mariecwhite** [comment]
Still open but likely won't fix since this a model for micro use cases.

**Comment by allieculp** [comment]
Moving to backlog, please change if you have any concerns!

**Comment by ScottTodd** [comment]
Going to close this stale issue. There might still be issues with that particular tflite model, but we should file a more recent issue if so.
