### ISSUE TITLE
The upstream behavior of bitEnumContains changed which impacts ElideRedundantCommands

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#10329]
The behavior of bitEnumContains is changed by https://github.com/llvm/llvm-project/commit/839b436c93604e042f74050cf2adadd75f30e898

I have a workaround to make the test pass, and drop a comment in https://reviews.llvm.org/D133374.

File an issue for tracking the cleanup of workaround.

@benvanik do we intend to do `(static_cast<uint32_t>(bits) & static_cast<uint32_t>(bit)) != 0;` in this check? Should all the bits be included?

https://github.com/iree-org/iree/blob/ec970102aa469d1c30d91db6c025d500130154b3/compiler/src/iree/compiler/Dialect/HAL/Transforms/ElideRedundantCommands.cpp#L99-L112

**Comment by hanhanW** [comment]
https://github.com/iree-org/iree/pull/10322

**Comment by antiagainst** [comment]
Good catch Hanhan! Sorry I missed that during code reviews. I think we should fix the change upstream to avoid silently changing the behavior. Posted on the patch; if you can fix it that'd be awesome.
