### ISSUE TITLE
Convert 1x1 filter NCHW Conv2D to matmul

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#10323]
The pass only handles Conv2DNhwcHwcfOp case. We should generalize it to handle nchw cases. File an issue for tracking it.

**Comment by antiagainst** [comment]
https://github.com/iree-org/iree/pull/10616 lands support for NCHW. Now we just need to extend the pass to support non-1 batch dimensions. I've done something similar in img2col pass, see here: https://github.com/iree-org/iree/pull/10343.

**Comment by antiagainst** [comment]
Actually that is specified in this issue is done. Filing another one to track non-unit batch dim: https://github.com/iree-org/iree/issues/10768.
