### ISSUE TITLE
Unsupported fusion blocks tensorcore pipeline

### ISSUE THREAD

**Issue by yzhang93** [iree-org/iree#10342]
### What happened?

When we add lowering configs on the matmul op to use tensorcore pipeline, we see very bad performance of the model because of the unsupported fusion with some ops (e.g. math.erf).

I've attached some example model IR that have bad performances.
https://storage.googleapis.com/iree-shared-files/nod-perf/vivian/minilm.txt
https://storage.googleapis.com/iree-shared-files/nod-perf/vivian/albert.txt
https://storage.googleapis.com/iree-shared-files/nod-perf/vivian/funnel.txt

**Comment by MaheshRavishankar** [comment]
The title of the bug is misleading. Its not unsupported fusion, but unsupported vectorization?

**Comment by ThomasRaoux** [comment]
PR fix under review:
https://github.com/iree-org/iree/pull/10460
