### ISSUE TITLE
iree-compile crashes running OPT

### ISSUE THREAD

**Issue by gpetters94** [iree-org/iree#10345]
### What happened?

I've been working on [modifying OPT](https://github.com/gpetters94/mlir-npcomp/tree/opt) to get it to run through torch-mlir. It now [lowers to tm_tensor](https://gist.github.com/gpetters94/0400f6375ede845e0a226aa2e4fb6393), but running it through current iree-compile crashes, and old IREE produces inconsistent behavior.

Running the command `iree-run-module --device=local-task --module_file=tmp.vmfb --entry_function=forward --function_input="1x7xi64=0" --function_input="1x7xi64=1 1 1 1 1 1 1"` on the compiled vmfb produces no output, just `EXEC @forward`.

Running [this](https://github.com/gpetters94/SHARK/blob/opt/opt.py) downstream code produces an assertion error in IREE (the IREE_SAVE_TEMPS results are [here](https://gist.github.com/gpetters94/4ac7309215fe3121f10e617f5132b303)). It might be an issue on the downstream codebase, but I thought I'd include it here just in case.

### Steps to reproduce your issue

Command line

1. Execute `iree-compiler` on the given mlir file

2. Execute `iree-run-module --device=local-task --module_file=tmp.vmfb --entry_function=forward --function_input="1x7xi64=0" --function_input="1x7xi64=1 1 1 1 1 1 1"` on the produced vmfb

Python

1. Download [this mlir](https://gist.github.com/gpetters94/0c0d4ddc8b88440c9b5cbbc4a9ae6c10).

2. Run [the aforementioned Python file](https://github.com/gpetters94/SHARK/blob/opt/opt.py) with IREE compiled in debug mode

### What component(s) does this issue relate to?

Runtime

### Version information

d750badfdf0bc68db04776c8a042fe6afb37d70e

**Comment by gpetters94** [comment]
Small update: I've double checked and the second issue arises when compiling with the following command:

```
iree-compile --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvm-embedded-linker-path=/home/gap/git/SHARK/venv/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvm-target-cpu-features=host -iree-llvm-target-triple=x86_64-linux-gnu --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 opt.torch.mlir > opt.vmfb
```

**Comment by gpetters94** [comment]
[This backtrace](https://github.com/iree-org/iree/files/9531756/backtrace.txt) happens when running the latest iree-compile on the tm_tensor code.

**Comment by powderluv** [comment]
@MaheshRavishankar any thoughts on this crash

**Comment by rsuderman** [comment]
Hmmm, initial guess was this was related to dynamic shapes as it failed on trying to calculate a slice size however  the source IR does not appear to be dynamic . Whoever has time to look - it would be useful to see what the state is like before the failure, maybe some lowering is not computing it's intermediate size?

**Comment by benvanik** [comment]
This is https://github.com/google/iree/blob/main/compiler/src/iree/compiler/Dialect/Stream/Transforms/PackConstants.cpp#L54 - the input file has elided attributes (`%cst_61 = arith.constant dense_resource<__elided__> : tensor<768x768xf32> loc(#loc0)`) and we don't support that. We may be able to make this one place handle elided ones but there may be other places hiding. Best bet is to not try to compile modules with elided attributes.

**Comment by benvanik** [comment]
(supporting the new dense resource attr may solve this as well, I'll at least give that a try but at some point compilation will fail if you're using elided attrs)

**Comment by benvanik** [comment]
`tm_tensor.scan` needs to be converted prior to passing into IREE - I can now get past the point it was dying but eventually it fails on that unrecognized op.

**Comment by gpetters94** [comment]
> `tm_tensor.scan` needs to be converted prior to passing into IREE - I can now get past the point it was dying but eventually it fails on that unrecognized op.

What does it need to be converted to? I thought IREE supported tm_tensor.

**Comment by powderluv** [comment]
@silvasean @ramiro050 fyi

**Comment by benvanik** [comment]
I'm not familiar with it (someone else may know), but you'd need to pass `--iree-input-type=tm_tensor` to convert them. I don't see any tests checked in using that so I'm not sure of its status.

**Comment by gpetters94** [comment]
> I'm not familiar with it (someone else may know), but you'd need to pass `--iree-input-type=tm_tensor` to convert them. I don't see any tests checked in using that so I'm not sure of its status (or, I guess, _I_ would - sorry, am tired and just learned that we had code like this :).

Not a problem - I should've posted the compile command I used. The crash happens with using `--iree-input-type=tm_tensor`.

**Comment by benvanik** [comment]
With #10377 you can pass `--iree-util-zero-fill-elided-attrs` to the compiler to have your elided attrs written to the final output as zeros - at least with this sample that works but there may still be some places hiding in the code that need to be updated. If you don't pass that flag you'll get a nice error suggesting you use the flag or provide values.
