### ISSUE TITLE
iree-tools-tflite 20220913.265 creates mlir files with special characters and additional op/file list

### ISSUE THREAD

**Issue by hcindyl** [iree-org/iree#10405]
### What happened?

tosa MLIR generated with iree-tools-tflite 20220913.265 is not in a clean text format. It has a lot of special characters in the file. In addition, it printout an op list at the end, similar to issuing `--mlir-print-debuginfo` with iree-tools-tflite 20220912.264, and the original tflite file location is also embedded in the mlir file.

```
ML<EF>R^AMLIR16.0.0git^@^A7^G^A^C^E^A^C^G^C^E^C ^E^]^K^M^O^Q^S^U^W^YESC^]^_!#%^CV
<F2>^G<87>^A<FB>^S^K^O^S^O^O^K^K^K^K^K^K^K^K^K^K^K^_ESC^O^O^SESC^S^O^SESC^O^S^O^S^S^S ....
...
#^U^O^Q^M^O^O^K^K^Qbuiltin^@func^@tosa^@module^@return^@const^@rescale^@conv2d^@transpose^@depthwis
e_conv2d^@mul^@cast^@avg_pool2d^@reshape^@sub^@exp^@reduce_sum^@reciprocal^@add^@value^@shift^@double_round^@input_zp^@multiplier^@output_zp^@per_channel^@scale32^@pad^@quantization_info^@stride^@dilation^@iree.identifier^@MobilenetV1/Predictions/Reshape_1^@main^@ml/ml-models-public/quant_models/mobilenet_v1_0.25_224_quant.tflite^@arg_attrs
```

Attach the mobilenet_v1_0.25_224_quant.tflite rendering result with both 20220912.264 and 20220913.265, as well as the final llvm-cpu static library bytecode module result
[mobilenet_v1_0.25_224_quant.tar.gz](https://github.com/iree-org/iree/files/9565370/mobilenet_v1_0.25_224_quant.tar.gz)

### Steps to reproduce your issue

1. `pip install -f https://github.com/iree-org/iree/releases --upgrade iree-tools-tflite==20220913.265`
2.  Download [mobilenet_v1_0.25_224_quant.tflite](https://tfhub.dev/tensorflow/lite-model/mobilenet_v1_0.25_224_quantized/1/default/1?lite-format=tflite)
3. `iree-import-tflite <tflite file> -o tosa.mlir`
4. `less tosa.mlir`

### What component(s) does this issue relate to?

Frontends, MLIR, Compiler

### Version information

20220913.265

**Comment by ScottTodd** [comment]
> It has a lot of special characters in the file

It's no longer a text file, see https://github.com/iree-org/iree/pull/10375

**Comment by hcindyl** [comment]
Thanks! Copy my discord question here: The embedded input tflite file path in the mlir-bytecode format would trigger https://github.com/iree-org/iree/blob/9cdcc05/compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMCPUTarget.cpp#L60-L69 to use that location as the module name instead of the name of the file generated by `iree-import-tflite`. Should we incorporate the ByteReader somehow when `iree-compiler` processes the `tosa` input?

**Comment by rsuderman** [comment]
You won't need to make any changes to `iree-compile` as it already checks for the magic bits to identify bytecode vs mlir-ir. In the case you want to see the IR version including the flag `--output-format=mlir-ir` will output a more human readable version.

We are migrating to the bytecode format as it will soon halve the size of the exported files.

**Comment by jpienaar** [comment]
https://github.com/llvm/llvm-project/blob/e07d749e7df07381ed90d564020eda0c1c89d7e3/mlir/lib/Parser/Parser.cpp#L29 it is nested inside the parseSourceFile routine in MLIR. So this is something not visible in memory, the ModuleOp you get should not be affected by this. If you are piping the .mlir/.mlirbc file across tools, you'd want to enable location emission so that the .mlirbc retains the info of the origin (`--mlir-print-debuginfo` should do that).

**Comment by ScottTodd** [comment]
Is there anything still to do for this issue? I think we've been using the bytecode format for some time now?

We might still have some build system functions outputting bytecode into files named .mlir though (see https://github.com/iree-org/iree/pull/10375#discussion_r970850047 - we could change some paths to `.mlirbc`)

**Comment by hcindyl** [comment]
The library query symbol is sanitized properly at candidate-20221111.324, and we can use the default bytecode-mlir output format. I will close the issue. Thanks for the help!
