### ISSUE TITLE
Error compiling MobileBert with `--iree-vmvx-enable-microkernels`, "Unable to resolve all strided buffer descriptors"

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#10427]
Steps to reproduce:

1. Get MobileBert-quant downloaded and imported into MLIR/TOSA, easiest to do it as a byproduct of building the `iree-benchmark-suites` target: `cmake --build . --target iree-benchmark-suites`
2. This file should now be in the build dir: `benchmark_suites/TFLite/mobilebert-baseline-tf2-quant.tflite.mlir`
3. Try compiling that to VMVX + ukernels:

```
tools/iree-compile --output-format=vm-bytecode --iree-hal-target-backends=vmvx --iree-input-type=tosa --iree-vmvx-enable-microkernels ./benchmark_suites/TFLite/mobilebert-baseline-tf2-quant.tflite.mlir -o /tmp/mobilebert-quant-vmvx.vmfb
```

Result:
```
./benchmark_suites/TFLite/mobilebert-baseline-tf2-quant.tflite.mlir:5996:13: error: Unable to resolve all strided buffer descriptors:
    %5993 = "tosa.transpose"(%5992, %1005) : (tensor<1x384x2xi8>, tensor<3xi32>) -> tensor<2x1x384xi8>
```

Complete output: https://gist.github.com/bjacob/2cc0958191ebe61bc847347e0533983f

**Comment by bjacob** [comment]
@stellaraccident if you have cycles, otherwise i'll look next week.

**Comment by stellaraccident** [comment]
It was not particularly easy to extract this because whole model debugging is hard and the tools we have for debugging deep, nested pipelines need some work. But here is the isolated repro:

https://gist.github.com/stellaraccident/a5aa0b74130956515118ee79295a431b

```
./tools/iree-opt --iree-vmvx-resolve-buffer-descriptors bad_buffer.mlir
```
