### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement iree-compiler-snapshot

### ISSUE THREAD

**Issue by sergiuiacob1** [iree-org/iree#10479]
### What happened?

Until today, my `requirements.txt` file had no issues installing iree libraries: `pip3 install -r requirements.txt`

requirements.txt:
```
-f https://github.com/google/iree/releases/tag/snapshot-20210728.428
iree-compiler-snapshot
iree-runtime-snapshot
iree-tools-tf-snapshot
iree-tools-tflite-snapshot
iree-tools-xla-snapshot
```

As of today, the error I'm getting is:
```
sergiuiacob@Sergius-MacBook-Pro ~ % pip3 install -f https://github.com/google/iree/releases/tag/snapshot-20210728.428 iree-compiler-snapshot --no-cache-dir
Looking in links: https://github.com/google/iree/releases/tag/snapshot-20210728.428
ERROR: Could not find a version that satisfies the requirement iree-compiler-snapshot (from versions: none)
ERROR: No matching distribution found for iree-compiler-snapshot
WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the '/Users/sergiuiacob/.pyenv/versions/3.7.13/bin/python3.7 -m pip install --upgrade pip' command.
```

### Steps to reproduce your issue

`pip3 install -f https://github.com/google/iree/releases/tag/snapshot-20210728.428 iree-compiler-snapshot --no-cache-dir`

### Version information

python 3.7.13
pip3 22.0.4

**Comment by sergiuiacob1** [comment]
My constraints are that I have to use these jaxlib and jax versions:
```
jaxlib==0.1.61
https://github.com/google/jax/archive/refs/tags/jax-v0.2.9.tar.gz
```

**Comment by sergiuiacob1** [comment]
I've also had issues with `jaxlib` before – versions just not being available all of a sudden anymore.
What's a safe way to install these versions and just make sure CI/CD doesn't start failing all of a sudden?

**Comment by stellaraccident** [comment]
Not sure if related but suspicious timing: https://github.com/llvm/torch-mlir/issues/1374#issuecomment-1251692931

Basically, all of these are nightlies with no guarantees, although we do publish "stable" releases to pypi. I don't think we are extending any special care to jaxlib at the moment and would need to look into it. My best advice for now is that if you depend on pinned stable nightlies and minor versions over a long time (you are at a year+), your best bet is to mirror them somewhere if not getting them from pypi.

**Comment by sergiuiacob1** [comment]
> Not sure if related but suspicious timing: [llvm/torch-mlir#1374 (comment)](https://github.com/llvm/torch-mlir/issues/1374#issuecomment-1251692931)
> 
> Basically, all of these are nightlies with no guarantees, although we do publish "stable" releases to pypi. I don't think we are extending any special care to jaxlib at the moment and would need to look into it. My best advice for now is that if you depend on pinned stable nightlies and minor versions over a long time (you are at a year+), your best bet is to mirror them somewhere if not getting them from pypi.

The problem with pypi is that there's a storage limitation and I've seen jaxlib / iree versions just disappearing overnight from the pypi repository.
The reason I chose to install using github links if because I tought they have unlimited lifespan.

One thing I've noticed is `pip3 install -f https://github.com/google/iree/releases/tag/snapshot-20210728.428 iree-compiler-snapshot` used to work, now it does not.
But if I rename `iree-compiler-snapshot` to `iree-compiler`, then it is downloading a package, aka
`pip3 install -f https://github.com/google/iree/releases/tag/snapshot-20210728.428 iree-compiler`

Why is that?

**Comment by sergiuiacob1** [comment]
On a linux machine, the error I'm getting for the command in OP is

```
ERROR: Ignored the following versions that require a different python version: 1.22.0 Requires-Python >=3.8; 1.22.0rc1 Requires-Python >=3.8; 1.22.0rc2 Requires-Python >=3.8; 1.22.0rc3 Requires-Python >=3.8; 1.22.1 Requires-Python >=3.8; 1.22.2 Requires-Python >=3.8; 1.22.3 Requires-Python >=3.8; 1.22.4 Requires-Python >=3.8; 1.23.0 Requires-Python >=3.8; 1.23.0rc1 Requires-Python >=3.8; 1.23.0rc2 Requires-Python >=3.8; 1.23.0rc3 Requires-Python >=3.8; 1.23.1 Requires-Python >=3.8; 1.23.2 Requires-Python >=3.8; 1.23.3 Requires-Python >=3.8; 1.4.1 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement iree-compiler-snapshot (from versions: none)
ERROR: No matching distribution found for iree-compiler-snapshot
```

**Comment by silvasean** [comment]
This appears to be the same issue as https://github.com/llvm/torch-mlir/issues/1374 -- feels like GitHub is canarying the new releases page so it shows up irregularly across projects or even within the same project. We should be able to share a solution.

**Comment by stellaraccident** [comment]
I'm not sure yet this is the same issue. Is the issue that jaxlib won't install? The error you show signs to imply that, and it seems to indicate that they dropped support for python 3.7?

(We can pull a Jax dev in and ask but I'd like to know that is the problem -- I know what iree does for this stuff but not Jax)

**Comment by silvasean** [comment]
The `ERROR: Could not find a version that satisfies the requirement iree-compiler-snapshot (from versions: none)` is the telltale sign -- it parsed the HTML and didn't find any links ("none")

**Comment by sergiuiacob1** [comment]
I've fixed this by pointing pip to the assets' links directly

```
-f https://github.com/iree-org/iree/releases/expanded_assets/snapshot-20210728.428
--extra-index-url https://github.com/iree-org/iree/releases/expanded_assets/snapshot-20210728.428
iree-compiler-snapshot
iree-runtime-snapshot
iree-tools-tf-snapshot
iree-tools-tflite-snapshot
iree-tools-xla-snapshot
```

I think this can be considered a permanent fix, right?

**Comment by silvasean** [comment]
That hardcodes a specific version, so it is not a fully general fix.

**Comment by silvasean** [comment]
We should be able to do something like this: https://github.com/llvm/torch-mlir/pull/1389

**Comment by sergiuiacob1** [comment]
> That hardcodes a specific version, so it is not a fully general fix.

That's true, but for my specific use-case it gets the job done.

**Comment by dellis23** [comment]
The fix for `torch-mlir` has been merged in [this](https://github.com/llvm/torch-mlir/commit/1dfe5efe9ee8f58deabf9382b58894a00b2d440c) commit.  This generates a package index at https://llvm.github.io/torch-mlir/package-index/.  Feel free to grab inspiration from that commit if you'd like to do something similar in another repo.

It works via github actions.  I ended up creating a [separate branch](https://github.com/llvm/torch-mlir/tree/github-pages) solely for the github pages content, which that github action pushes to.

**Comment by aaron-schneider** [comment]
@GMNGeoffrey Can we remove the "awaiting-triage" label?

**Comment by GMNGeoffrey** [comment]
I think https://github.com/iree-org/iree/pull/10594 should fix this. I think at the point we're hosting our own thing, we should consider making it a [PEP 503](https://peps.python.org/pep-0503/) compliant index. I'm going to move that discussion to https://github.com/iree-org/iree/issues/9532
