### ISSUE TITLE
Add cmake option for additional runtime link libraries.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#10548]
`IREE_HAL_EXECUTABLE_IMPORT_PROVIDER_DEFAULT_FN` now allows for external import providers to be defined but when set requires that all binaries both runtime and compiler have the symbol defined due to ConstEval and other compiler->runtime deps.

To make out-of-tree import providers possible we also need to link in user-defined static libraries that contain the symbol. An `IREE_EXTERNAL_HAL_DEPS` cmake var that just added deps via `target_link_libraries` in a central place would let this happen.

Users could then implement their provider in some .c, wrap that in a cmake library, set the symbol name via `IREE_HAL_EXECUTABLE_IMPORT_PROVIDER_DEFAULT_FN`, and append the library to `IREE_EXTERNAL_HAL_DEPS`. The python bindings, compiler tools, and all runtime tools would consistently use the provider.

**Comment by nicolasvasilache** [comment]
Both the issue and the PR that fixes (#10551) commit message list a wrong flag name .. (resp. `IREE_EXTERNAL_HAL_DEPS ` and `IREE_HAL_EXECUTABLE_LOADER_DEPS`). The proper flag is `IREE_HAL_EXECUTABLE_LOADER_EXTRA_DEPS`, maybe surface it somewhere more visible?

Re:

> To make out-of-tree import providers possible we also need to link in user-defined static libraries that contain the symbol. 
> An IREE_EXTERNAL_HAL_DEPS cmake var that just added deps via target_link_libraries in a central place would let this 
> happen.

I am unclear from this issue description whether adopting `IREE_HAL_EXECUTABLE_LOADER_EXTRA_DEPS` is supposed to make the ConstEval issue go away (in my case it does not and I still need a hack into `Runtime.cpp`).

Additionally, this does not seem to propagate to the build rule of `iree-run-module` which complains that the dependence is missing. Locally I was successful when I added the dependence directly to the build rule.

I put my current stack in https://github.com/nicolasvasilache/iree/tree/tpp-dev, the commit of interest is https://github.com/nicolasvasilache/iree/commit/b235ba58f18d2f782b39013a86e62a11ea158243

**Comment by benvanik** [comment]
The issue was written before the PR + review feedback. It looks like the commit message was overwritten with the original PR message when squashed and that got the old name. 🤷 Did you look at the updated example? https://github.com/iree-org/iree/commit/a430a433b13559972c0217aca087a07650522864

Stepping back, it'll be useful if you understand the error you're getting (`undefined symbol iree_hal_test_import_provider`): that's saying that when linking there's no dependency (transitive or otherwise) providing that symbol. That's because in the original example and your code the symbol lives in `context_util.c` - only things depending on that will ever have the symbol. The compiler doesn't depend on that and as such the linker can't find it there when building it. In your change you've just mucked with the xsmm dependency and not resolved the actual missing symbol `iree_hal_test_import_provider`. It's useful to understand what linker errors indicate as they're usually pretty easy to track down in static builds (dynamic linkage is a lot more pain). It's just like if you wrote this and tried to link it:
```c
void some_extern_function();
void foo() {
  some_extern_function();
}
```
You'd get `undefined symbol some_extern_function` until you provided it. Same error you're getting now.

If you look at the updated example it moved the provider out to its own library to make it clearer that it's not related to context_utils and _that_ library is what's referenced in the extra deps var as that's what will provide the symbol. All binaries (compiler, runtime, bindings, etc) using IREE's HAL will pull in that dep and the symbol will be present. If you moved your code into someplace like that and used xsmm you'd add your xsmm dep to the `iree_samples_custom_cpu_imports` cmake `target_link_libraries` - it should then get pulled in to the final binaries automatically.

There's not really any magic here relative to normal C linkage:
- `IREE_HAL_EXECUTABLE_IMPORT_PROVIDER_DEFAULT_FN=iree_samples_custom_cpu_import_provider` says call function `iree_samples_custom_cpu_import_provider`
- the linker now needs some library to provide function `iree_samples_custom_cpu_import_provider`
- in the example that `iree_samples_custom_cpu_imports` library provides the symbol
- `IREE_HAL_EXECUTABLE_LOADER_EXTRA_DEPS=iree_samples_custom_cpu_imports` tells the linker to depend on that library
- linker can now find `iree_samples_custom_cpu_import_provider` and happily links

**Comment by nicolasvasilache** [comment]
The link I had was borked: https://github.com/iree-org/iree/compare/benvanik-loader-deps...benvanik-native-example?expand=1
![Screen Shot 2022-09-27 at 6 35 30 PM](https://user-images.githubusercontent.com/10148468/192585138-f7c329d3-a32d-4c5a-9bc4-92be3155a028.png)

https://github.com/iree-org/iree/commit/a430a433b13559972c0217aca087a07650522864 makes sense, thanks!
