### ISSUE TITLE
Crash in ASR decoders

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#10567]
It crashes in a gather op. There might be issues in codegen, which generates invalid inputs for gather op.

**Comment by hanhanW** [comment]
I finally get some clues... The issue is about generic ops that return both a reduced and unreduced value. I think the root cause is the change of fusion heuristic.

Let me write down how I bisect and reproduce the issue.

https://github.com/iree-org/iree/pull/10130 introduced new features that caused infinite loop, see https://github.com/iree-org/iree/issues/10300. The issue is fixed by https://github.com/iree-org/iree/pull/10487. So if we're checking out to a commit after device queue features, we'll have to cherry-pick three commits.

```
d07c2487b54d995d65d66080308fb845bd985a09
bb711ee1bfa3c4780910c2cbf33f857de09d18be
87522d1fa1983efcca137166e796400d995b3001
```

During the debug, I noticed that there is a bug in op.emitWarning, which is fixed by https://github.com/iree-org/iree/pull/10761

So the steps to check correctness is checkouting to the commit, and cherry-pick four commits before building IREE.

Later, I found that there are compilation errors after landing https://github.com/iree-org/iree/commit/c9e9482d8718d45312d6ba2ff03d52668eb8de3d. The commit enables the feature that handles multi-result operations in Elementwise op fusion. However, it created invalid generic ops. The verification failed:

```
error: 'linalg.generic' op unexpected output tensor expression in indexing map #0 a.k.a 'd0' is function of reduction iterator 'd0'
```

It's fixed by https://github.com/iree-org/iree/pull/10226 The commit drops a check for output indexing maps, and fixed a vectorization issue. Starting from this point, we run into segfault in ASR decoders.

The error was in a mhlo.reduce op which has two outputs.

```
%3:2 = mhlo.reduce(%arg0 init: %1), (%0 init: %2) across dimensions = [1] : (tensor<1x1024xf32>, tensor<1x1024xi32>, tensor<f32>, tensor<i32>) -> (tensor<1xf32>, tensor<1xi32>)
```

My guess is that it's come from ArgMin/Max like operation, and IREE does not handle it correctly at this moment. It still need some time to figure out what's happening because the model is big.

@MaheshRavishankar @pzread Is it fine to add a flag to undo https://github.com/iree-org/iree/commit/c9e9482d8718d45312d6ba2ff03d52668eb8de3d? Can you help look into the PR and provide a draft, so I can verify if this is the root cause?

**Comment by MaheshRavishankar** [comment]
Very strange. The commit you point to is an NFC change that just fixes the ABI. So might be something that I didn't anticipate. It will be hard to just add a flag for that commit. Where is the segfault coming from? What's the stack trace?

**Comment by hanhanW** [comment]
It's a runtime crash, not compilation error. I was thinking if the result of element-wise fusion is different. I can try to dump something and put more information here.

**Comment by MaheshRavishankar** [comment]
Ok. I can see tomorrow.

**Comment by hanhanW** [comment]
I think it's not a NFC because the result of fusion is different. It's allowed to generate a generic op that return multiple results. E.g.,

```
%3240:3 = "linalg.generic"(%3173, %3237, %3237, %3238, %3239) ({
^bb0(%arg2: i32, %arg3: f32, %arg4: f32, %arg5: f32, %arg6: i32):
  %3246 = "linalg.index"() {dim = 0 : i64} : () -> index
  %3247 = "arith.cmpi"(%3246, %436) {predicate = 0 : i64} : (index, index) -> i1
  %3248 = "arith.select"(%3247, %76, %arg4) : (i1, f32, f32) -> f32
  %3249 = "linalg.index"() {dim = 0 : i64} : () -> index
  %3250 = "arith.index_cast"(%3249) : (index) -> i32
  %3251 = "arith.cmpi"(%arg2, %467) {predicate = 4 : i64} : (i32, i32) -> i1
  %3252 = "arith.select"(%3251, %arg3, %3248) : (i1, f32, f32) -> f32
  %3253 = "arith.cmpf"(%arg5, %3252) {predicate = 2 : i64} : (f32, f32) -> i1
  %3254 = "arith.cmpf"(%arg5, %arg5) {predicate = 13 : i64} : (f32, f32) -> i1
  %3255 = "arith.ori"(%3253, %3254) : (i1, i1) -> i1
  %3256 = "arith.cmpf"(%arg5, %3252) {predicate = 1 : i64} : (f32, f32) -> i1
  %3257 = "arith.cmpi"(%arg6, %3250) {predicate = 2 : i64} : (i32, i32) -> i1
  %3258 = "arith.andi"(%3256, %3257) : (i1, i1) -> i1
  %3259 = "arith.ori"(%3255, %3258) : (i1, i1) -> i1
  %3260 = "arith.select"(%3255, %arg5, %3252) : (i1, f32, f32) -> f32
  %3261 = "arith.select"(%3259, %arg6, %3250) : (i1, i32, i32) -> i32
  "linalg.yield"(%3248, %3260, %3261) : (f32, f32, i32) -> ()
}) {indexing_maps = [affine_map<(d0) -> ()>, affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>, affine_map<(d0) -> ()>, affine_map<(d0) -> ()>], iterator_types = ["reduction"], operand_segment_sizes = array<i32: 2, 3>} : (tensor<i32>, tensor<1024xf32>, tensor<1024xf32>, tensor<f32>, tensor<i32>) -> (tensor<1024xf32>, tensor<f32>, tensor<i32>)
```

Before the commit, it's not allowed. I'd like to check if it's the root cause of the runtime crash, so I'm looking for a hack to disable such behavior.

**Comment by hanhanW** [comment]
The above IR was generated by iree-compile. I think it's changed in the commit, because the cherry-pick commit supports the feature, while the IREE control function does not explicitly disable it. It's not caught because our tests does not cover the case.

The commit after it (i.e., https://github.com/llvm/llvm-project/commit/7744253f12a84879aa58522346e919df8b65364e) fixed the compilation issue about generic ops that return both a reduced and unreduced value.

Yes, I need a flag or draft to disable creation of multi-result generic ops. I can help verify if it's the root cause, and try to provide smaller repro. Thanks for helping on it!

**Comment by hanhanW** [comment]
This is fixed by recent multi-result fusion work.
