### ISSUE TITLE
Link libraries

### ISSUE THREAD

**Issue by Theoo1997** [iree-org/iree#10574]
I wont to run a NN on bare metal on x86. I have an error when I try to locate the libraries needed to make the executable.  
```
/usr/bin/ld: cannot find -liree_runtime_runtime
/usr/bin/ld: cannot find -liree_hal_local_loaders_static_library_loader
/usr/bin/ld: cannot find -liree_hal_drivers_local_task_task_driver
/usr/bin/ld: cannot find -liree_task_api
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/lenet_exe.dir/build.make:131: lenet_exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/lenet_exe.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
Where can I find this libraries and add the to the include path?

**Comment by sergiuiacob1** [comment]
@Theoo1997 I am having a similar issue, how did you solve this?

**Comment by Theoo1997** [comment]
> @Theoo1997 I am having a similar issue, how did you solve this?

I never found the solution. The only trick that I did was to add "add_subdirectory(lenet) (lenet is the folder that has the C++ code to make the executable)" to iree's cmake file and recompile iree. I tried to include the libraries (.a files) but they where to many. If you find any solution to this problem please post it.
