### ISSUE TITLE
Failed to legalize operation 'arith.extui' 

### ISSUE THREAD

**Issue by not-jenni** [iree-org/iree#10604]
### What happened?

`error: failed to legalize operation 'arith.extui' that was explicitly marked illegal`

Running iree-compile on an internal google tflite model results in errors for the VMVX backend.  This is the MLIR snippet causing the error:

```
func.func @main(%arg0 : tensor<?x120x160x16xi32>) -> (tensor<?x120x160x16xi8>) {
    %0 = "tosa.rescale"(%arg0) {double_round = true, input_zp = 0 : i32, multiplier = [1124909143 : i32, 1463392758 : i32, 1243591614 : i32, 1521475634 : i32, 1117488603 : i32, 2033741321 : i32, 1415517171 : i32, 2019663567 : i32, 1730978840 : i32, 1489509255 : i32, 1551973637 : i32, 1161295759 : i32, 1596869545 : i32, 1386718964 : i32, 1947757139 : i32, 1162926849 : i32], output_zp = -128 : i32, per_channel = true, scale32 = true, shift = [39 : i32, 39 : i32, 39 : i32, 39 : i32, 39 : i32, 41 : i32, 39 : i32, 40 : i32, 40 : i32, 40 : i32, 40 : i32, 39 : i32, 34 : i32, 39 : i32, 40 : i32, 39 : i32]} : (tensor<?x120x160x16xi32>) -> tensor<?x120x160x16xi8>
    return %0 : tensor<?x120x160x16xi8>
}
```

Full error output:
https://gist.github.com/not-jenni/37bdaa993e97c395ec955a66ccfcf842

### Steps to reproduce your issue

1. Download https://github.com/iree-org/iree/releases/tag/candidate-20220902.254 and the MLIR sample
2. Run `./iree-compile sample.mlir --iree-input-type=tosa --iree-hal-target-backends=vmvx -o=sample.vmfb`

### What component(s) does this issue relate to?

Compiler

### Version information

iree stable stable-20220902.254

### Additional context

This model failure was pointed out by @lundong

**Comment by MaheshRavishankar** [comment]
@not-jenni does this happen on the LLVM CPU backend as well?

**Comment by ScottTodd** [comment]
I'd expect this conversion to cover this case: https://github.com/iree-org/iree/blob/0bca135fc03950c1b5e777f0f8127f97be41da8e/compiler/src/iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp#L790-L822 

I also doubt this reproduces on the LLVM CPU backend (there's a long tail of support for these math/bit logic/arithmetic ops that LLVM supports via upstream contributions while we add them to VMVX in IREE as needed).

**Comment by not-jenni** [comment]
@MaheshRavishankar No, this compiles successfully for the LLVM CPU backend

**Comment by not-jenni** [comment]
I just tested this again building from source, and the issue seems to be resolved by https://github.com/iree-org/iree/pull/10534
