### ISSUE TITLE
IREE-compile failing with f16 types for vulkan backend.

### ISSUE THREAD

**Issue by pashu123** [iree-org/iree#10718]
### What happened?

```
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
iree-compile: /home/prashant/iree/third_party/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:256: const T &llvm::ArrayRef<mlir::AffineExpr>::operator[](size_t) const [T = mlir::AffineExpr]: Assertion `Index < Length && "Invalid index!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
iree-compile: /home/prashant/iree/third_party/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:256: const T &llvm::ArrayRef<mlir::AffineExpr>::operator[](size_t) const [T = mlir::AffineExpr]: Assertion `Index < Length && "Invalid index!"' failed.
```

### Steps to reproduce your issue

The IR is present here: https://gist.github.com/pashu123/facec30e8f185795025c7ddcca5f21d9

Command: `iree-compile - --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan  --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false -iree-vulkan-target-triple=ampere-rtx3090-linux --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64`

### What component(s) does this issue relate to?

Compiler

**Comment by pashu123** [comment]
Example to reproduce the error: 
```
module {
  func.func @forward(%arg0: tensor<2x320xf16>, %arg1: tensor<320x1280xf16>) -> tensor<2x1280xf16> {
    %cst = arith.constant 0.000000e+00 : f16    %0 = tensor.empty() : tensor<2x1280xf16>    %1 = linalg.fill ins(%cst : f16) outs(%0 : tensor<2x1280xf16>) -> tensor<2x1280xf16>    %2 = linalg.matmul ins(%arg0, %arg1 : tensor<2x320xf16>, tensor<320x1280xf16>) outs(%1 : tensor<2x1280xf16>) -> tensor<2x1280xf16>
    return %2 : tensor<2x1280xf16>
  }
}
```

**Comment by pashu123** [comment]
@antiagainst The IR fails with the log ```
vector.transfer_write %47#8, %alloc[%42, %56] : vector<8xf16>, memref<32x64xvector<4xf16>, 3> loc(callsite("/home/prashant/xyz.mlir":6:10 at "/home/prashant/xyz.mlir":2:3))                         
iree-compile: /home/prashant/iree/third_party/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:256: const T &llvm::ArrayRef<mlir::AffineExpr>::operator[](size_t) const [T = mlir::AffineExpr]: Assertion `Index < Length && "Invalid index!"' failed.                                                    
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.                                                                                          
Stack dump:                                                                                                                                                                                          
0.      Program arguments: iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-llvm-embedded-linker-path=/home/prashant/iree-build/compiler/bindings/python/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvm-target-cpu-features=host -iree-vulkan-tar
get-triple=ampere-rtx3090-linux --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 /home/prashant/xyz.mlir --mlir-disable-threading -mlir-print-ir-after-all                        
 #0 0x000055f276aaee63 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/prashant/iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:569:13
 #1 0x000055f276aad250 llvm::sys::RunSignalHandlers() /home/prashant/iree/third_party/llvm-project/llvm/lib/Support/Signals.cpp:105:18                                                               
 #2 0x000055f276aaf1da SignalHandler(int) /home/prashant/iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1                                                                       
 #3 0x00007fc3a9470520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)                                                                                                                                     
 #4 0x00007fc3a94c4a7c pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x96a7c)                                                                                                                        
 #5 0x00007fc3a9470476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)                                                                                                                              #6 0x00007fc3a94567f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)                                                                                                                               
 #7 0x00007fc3a945671b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)                                                                                                                                     
 #8 0x00007fc3a9467e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)                                                                                                                                     
 #9 0x000055f2768c0917 mlir::AffineDimExpr mlir::AffineExpr::cast<mlir::AffineDimExpr>() const /home/prashant/iree/third_party/llvm-project/mlir/include/mlir/IR/AffineExpr.h:292:3                  #10 0x000055f2768c0917 mlir::AffineMap::getDimPosition(unsigned int) const /home/prashant/iree/third_party/llvm-project/mlir/lib/IR/AffineMap.cpp:328:25                                             
#11 0x000055f272ed9f0a mlir::iree_compiler::(anonymous namespace)::ScalarizeVectorTransferWrite::matchAndRewrite(mlir::vector::TransferWriteOp, mlir::PatternRewriter&) const /home/prashant/iree/com
piler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp:0:27  
```

**Comment by pashu123** [comment]
The map is `(d0, d1) -> ()` and it's indexing into 0th dim which I think doesn't exist. https://github.com/iree-org/iree/blob/300335a6fadcbc22c417575d7ed23ce61d5e56c4/compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp#L513

**Comment by antiagainst** [comment]
Okay, with #10791, #10792, #10793, and https://reviews.llvm.org/D135770, the fp16 model should compile.

**Comment by pashu123** [comment]
@antiagainst I tried running with the above patches it gives ```
stable_diff_f16_elided.mlir:1730:12: error: failed to legalize operation 'vector.transfer_read' that was explicitly marked illegal    %261 = linalg.generic {indexing_maps = [#map16, #map16, #map16], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded_770, %209 : tensor<2x4096x320xf16>, tensor<2x4096x320xf16>) outs(%156 : tensor<2x4096x320xf16>) {           ^stable_diff_f16_elided.mlir:25:3: note: called from
  func.func @forward(%arg0: tensor<2x4x64x64xf16>, %arg1: tensor<1xf16>, %arg2: tensor<2x77x768xf16>) -> tensor<2x4x64x64xf16> {  ^stable_diff_f16_elided.mlir:1730:12: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.6, [Shader, Float64, Float16, Int64, Int16, Int8, StorageBuffer16BitAccess, StorageUniform16, StoragePushConstant16, StorageBuffer8BitAccess, UniformAndStorageBuffer8BitAccess, StoragePushConstant8, GroupNonUniform, GroupNonUniformVote, GroupNonUniformArithmetic, GroupNonUniformBallot, GroupNonUniformShuffle, GroupNonUniformShuffleRelative, GroupNonUniformClustered, GroupNonUniformQuad, VariablePointers, VariablePointersStorageBuffer, CooperativeMatrixNV], [SPV_KHR_16bit_storage, SPV_KHR_8bit_storage, SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers, SPV_NV_cooperative_matrix]>, NVIDIA:DiscreteGPU, #spirv.resource_limits<max_compute_shared_memory_size = 49152, max_compute_workgroup_invocations = 1024, max_compute_workgroup_size = [1024, 1024, 64], cooperative_matrix_properties_nv = [#spirv.coop_matrix_props<m_size = 8, n_size = 8, k_size = 32, a_type = i8, b_type = i8, c_type = i32, result_type = i32, scope = <Subgroup>>, #spirv.coop_matrix_props<m_size = 16, n_size = 16, k_size = 16, a_type = f16, b_type = f16, c_type = f16, result_type = f16, scope = <Subgroup>>, #spirv.coop_matrix_props<m_size = 16, n_size = 16, k_size = 16, a_type = f16, b_type = f16, c_type = f32, result_type = f32, scope = <Subgroup>>]>>}>    %261 = linalg.generic {indexing_maps = [#map16, #map16, #map16], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded_770, %209 : tensor<2x4096x320xf16>, tensor<2x4096x320xf16>) outs(%156 : tensor<2x4096x320xf16>) {           ^stable_diff_f16_elided.mlir:25:3: note: called from  func.func @forward(%arg0: tensor<2x4x64x64xf16>, %arg1: tensor<1xf16>, %arg2: tensor<2x77x768xf16>) -> tensor<2x4x64x64xf16> {  ^stable_diff_f16_elided.mlir:1730:12: error: failed to serialize executables    %261 = linalg.generic {indexing_maps = [#map16, #map16, #map16], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded_770, %209 : tensor<2x4096x320xf16>, tensor<2x4096x320xf16>) outs(%156 : tensor<2x4096x320xf16>) {           ^stable_diff_f16_elided.mlir:25:3: note: called from  func.func @forward(%arg0: tensor<2x4x64x64xf16>, %arg1: tensor<1xf16>, %arg2: tensor<2x77x768xf16>) -> tensor<2x4x64x64xf16> {  ^compilation failed
```

To repro: stable_diff_f16_elided: https://gist.github.com/f7d4d2a2d2c91bd46423d0006d23c030

command: `iree-compile  --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-llvm-embedded-linker-path=/home/prashant/iree-build/compiler/bindings/python/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvm-target-cpu-features=host -iree-vulkan-target-triple=ampere-rtx3090-linux --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 stable_diff_f16_elided.mlir  --mlir-disable-threading
`

**Comment by pashu123** [comment]
```see current operation: %710 = "vector.transfer_read"(%58, %709, %45) {in_bounds = [true], operand_segment_sizes = array<i32: 1, 1, 1, 0>, permutation_map 
= affine_map<(d0) -> (d0)>} : (memref<320xf16>, index, f16) -> vector<16xf16> loc(callsite("stable_diff_f16_elided.mlir":1730:12 at "stable_diff_f16_elided.mlir":25:3))```

**Comment by pashu123** [comment]
@antiagainst The cooperative matrix kicks in, but if I change the target triple to `rdna2-unknown-linux` it passes.

**Comment by powderluv** [comment]
This fails for him on Nvidia hardware with cooperative matrix. Works on AMD hardware without cooperative matrix.
