### ISSUE TITLE
Re-enable CUDA transform dialect tests

### ISSUE THREAD

**Issue by okkwon** [iree-org/iree#10777]
### What happened?

During the recent LLVM integrate, the CUDA transform dialect test failed and were disabled. These need to be re-enabled again.

Here is the commit that disabled the tests.
https://github.com/iree-org/iree/pull/10740/commits/692eea09462a0f7c01546307d530e1779fdd9039

**Comment by aaron-schneider** [comment]
Hi @okkwon @nicolasvasilache  - can you assign a priority and remove the awaiting-triage label?

**Comment by nicolasvasilache** [comment]
Fixed a while ago
