### ISSUE TITLE
Large regressions across many models after adding (pad + consumer) to CPU pipeline

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#10820]
One of samples: https://perf.iree.dev/serie?IREE?MobileNetV3Small%20%5Bfp32%2Cimagenet%5D%20(TFLite)%20CPU-x86_64-CascadeLake%20full-inference%2Cdefault-flags%20%5Bcompilation%3Amodule%3Acompilation-time%5D

**Comment by hanhanW** [comment]
It seems that the (pad + consumer) is not the root cause. I disabled the feature in https://github.com/iree-org/iree/pull/10824, and there are no improvements.

**Comment by pzread** [comment]
Just want to note that the regression seems to be on compilation time not the latency.

**Comment by benvanik** [comment]
Oh, I didn't notice that... dana isn't great at making that clear x_x
Still, a big increase in compile time isn't good - was this from changing build machines or some other build configurations outside of source control?

**Comment by pzread** [comment]
The build machines provide much less stable performance, but 40% is a lot. I'll check if there is an issue or change on the machine.

**Comment by benvanik** [comment]
Given that our compile times are way too long today doubling them has to have a really good benefit to be worth it - if we didn't see major performance changes in runtime but do see nearly all models taking 2x longer to compile that's not good :)

**Comment by pzread** [comment]
As the result of the revert https://github.com/iree-org/iree/pull/10824, it looks like the improvement on the compilation time matched the regression. So it might be actually the root cause.

**Comment by benvanik** [comment]
Good catch! Would be good to dig into ways of making the pipeline more efficient - a 40% increases is *massive* and mobilenet is a tiny model - we don't want to death-by-a-thousand-papercuts our way to multi-day compile times.

**Comment by hanhanW** [comment]
Good point! I thought the new passes won't impact the compilation time for default path a lot, but it seems not. Definitely have to take some time on it!

**Comment by benvanik** [comment]
(ping on this - a 50% compile time reduction is pretty big)

**Comment by hanhanW** [comment]
I can't reproduce it on my workstation. They all takes 34 seconds on my machine with `--mlir-disable-threading` flag; 40 seconds w/o `--mlir-disable-threading`. I can try to reproduce it on a x86_64-CascadeLake VM.

(I know it's weird that multi-threaded is slower, but it's not the point for this issue. That should be a separate issue.)
