### ISSUE TITLE
Sequentially running an Iree model crashes

### ISSUE THREAD

**Issue by gsalexandru** [iree-org/iree#10830]
### What happened?

We can successfully run an Iree model using the C runtime API, but our problem is that running the same model many times (on different inputs or the same input) crashes. The dimensions are 1 row, 256 columns. We confirmed that the problem is not OOM or memory leaks. At some point it crashes without any error, it just stops. The process is still running, but it does not do anything. Debugger is not helpful as it does not provide a specific line of code when this issue occurs. The problem happens on different iterations, which vary 100x sometimes, around 5 million. All this is making us believe there is some unidentified behaviour. We are quite lost, debugging this for days. Could you pleas help us with some insight into what we could try or some good practices?

### Steps to reproduce your issue

1. Export a model using IREE
2. Build a session using the model path
3. Build Input
4. Run model using the inputs and session many times

### Version information

https://github.com/iree-org/iree/releases/expanded_assets/snapshot-20210728.428

**Comment by benvanik** [comment]
We're going to need more information - it's kind of like saying "a random program we compiled with LLVM crashes" :)
What's the error? "crash" could mean anything (assertion hit, segfault, sigill, hang, etc)
Have you run with ASAN? (pass `-DIREE_ENABLE_ASAN=ON` to cmake configure)
What are you trying to run? (link to source input IR)
What backends are you running on? (CPU, Vulkan, etc)
What platform are you running on? (Windows, Linux, etc)
You mention the API: are you 100% confident it's not the API usage? Can you share the code? Are you trying to invoke concurrently from multiple threads? etc?

To rule out your own usage you can use `iree-benchmark-module` to run the model for a large number of iterations by passing `--benchmark_min_time=100000` (or a similarly large number of seconds). If it fails there then with the source model we can dig into the compiler or runtime issue that may be causing it. If you can't share the model then you'll have to build a reproducer that does trigger in `iree-benchmark-module` you can share.

**Comment by jpienaar** [comment]
Closing given lack of activity, if you have more info here please and we can follow up again.
