### ISSUE TITLE
Stable diffusion Torch-Fp16 Vulkan giving invalid numbers

### ISSUE THREAD

**Issue by raikonenfnu** [iree-org/iree#10850]
### What happened?

Running iree-run-module on SD Torch Fp16 gives invalid Fp16 numbers:

<img width="833" alt="Screen Shot 2022-10-19 at 1 45 31 AM" src="https://user-images.githubusercontent.com/68087699/196785718-31bedb62-09de-4da9-a82a-17112b500aeb.png">

I have reduced the model to the smallest repro I can get: [link to reduced IR](https://storage.googleapis.com/iree-shared-files/nod-perf/stanley/StableDiffusion/sd_nan_repro.mlir) 

Interestingly, if we do `iree-trace-dispatch-tensor` it actually outputs the correct values.
<img width="833" alt="Screen Shot 2022-10-19 at 1 45 31 AM (1)" src="https://user-images.githubusercontent.com/68087699/196786188-fa47dc62-7871-43b2-b55d-c0e5d05eb855.png">

### Steps to reproduce your issue

Repro full model:
```bash
wget https://storage.googleapis.com/shark_tank/prashant_nod/stable_diff_f16_torch/stable_diff_f16_torch.mlir

iree-compile --iree-input-type=none --iree-hal-target-backends=vulkan --iree-flow-linalg-ops-padding-size=16 --iree-flow-enable-padding-linalg-ops --iree-vulkan-target-triple=rdna2-unknown-linux --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-flow-enable-conv-nchw-to-nhwc-transform ~/nod/mlir/stable_diff_f16_torch.mlir -o /tmp/stable_diff_f16.vmfb

iree-run-module --module_file=/tmp/stable_diff_f16.vmfb --device=vulkan --entry_function=forward --function_input="1x4x64x64xf16"  --function_input="1xf16" --function_input="1x77x768xf16"
```

Repro reduced IR:
```bash
wget https://storage.googleapis.com/iree-shared-files/nod-perf/stanley/StableDiffusion/sd_nan_repro.mlir

/iree-compile --iree-input-type=none --iree-hal-target-backends=vulkan --iree-flow-enable-conv-nchw-to-nhwc-transform --iree-flow-linalg-ops-padding-size=16 --iree-flow-enable-padding-linalg-ops --iree-vulkan-target-triple=rdna2-unknown-linux --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 /path/to/sd_nan_repro.mlir -o /tmp/ml.vmfb

iree-run-module --module_file=/tmp/ml.vmfb --device=vulkan --entry_function=forward --function_input="2x4x64x64xf16=4.0" --function_input="2x4x66x66xf16"
```

Note: 
-Tried removing all the optimization flags but issue persist
-I also have tried `-iree-stream-partitioning-favor=debug` + `packSlicesWithNoAliasing` instead of greedy in [here](https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Dialect/Stream/Transforms/LayoutSlices.cpp#L298)

### Additional context

Other interesting notes:
- it has 2 convs, tried with just the latest/last conv that caused the issue and fed it inputs from function argument, but that still worked.
- removing the earliest conv makes also removes the invalid number.
- If I removed the earliest conv it works, and if I set the output to the first/earliest conv as an func agument, the invalid numbers get removed.
- Non of the inputs to either of these convs are actually NaNs.

Task list to debug:

- [x] A.reduce the dispatch some more. (a bit hard, since now even replacing the earliest operation with a func argument, makes the error go away.), but if we can try to recreate the inputs to the latest/last conv, that can break that conv, we can try to set it as function argument and just analyze that conv. (maybe try reduce as much as possible in between two convs) ->([most reduced IR](https://storage.googleapis.com/iree-shared-files/nod-perf/stanley/StableDiffusion/conv_nan_repro.mlir))
- [x] B.Compile this reduced IR with --iree-flow-trace-dispatch-tensors and compare the difference between CUDA and Vulkan. (Need to check that cuda works first though) -> With trace-dispatch-tensors cuda/vulkan/cpu all match!
- [x] C.Google around for other people facing similar issues (i.e Fp16 and NaNs/or -98304 on vulkan) -> didn't find much.
- [x] D.Print out Vulkan/SPIRV code generated of the latest/last/most back conv, and analyze correctness. -> from Stanley's POV dispatch/spirv code seems OK, plus it can run on it's own in isolation. (even with two conv back to back it actually works).
- [x] E.Checkout tencent/ncnn issues related to fp16 and vulkan [link](https://www.google.com/search?q=Fp16+vulkan+site%3Agithub.com&rlz=1C5CHFA_enUS930US930&biw=1680&bih=882&sxsrf=ALiCzsYJF-E3GTB-NwJpV5gMgcSLk9J_tA%3A1666165829044&ei=RaxPY6uoAujfkPIPuLOh4Ao&ved=0ahUKEwjr3oGz5-v6AhXoL0QIHbhZCKwQ4dUDCA8&uact=5&oq=Fp16+vulkan+site%3Agithub.com&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQA0oECEEYAUoECEYYAFC2CVjfCmC4D2gCcAB4AIABP4gBdpIBATKYAQCgAQHAAQE&sclient=gws-wiz-serp) -> didn't find much.
- [ ] F. isolate the last conv from the reduced conv_nan_repro.mlir, do a dump after ConvertToSPIRV, compare the spirv dialect code for the last conv to see if there exist any difference when it's in isolation vs when it's part of the reduced dipatch mlir.
- [ ] G. Run tracy on it to check if there exist any dispatch region has suspiciously low runtime.(may mean it got skipped over somehow)
- [ ] H. Run tracy to see the graph if anything got called concurrently where it shouldn't have.

**Comment by raikonenfnu** [comment]
Reduced the IR some more, by trying to "fold" away operations that does not change the shape and retain the error. Sometimes it does make the error disappear (i.e replacing use of some generic ops with the fillOp)

Most reduced IR:(20 operations)
https://storage.googleapis.com/iree-shared-files/nod-perf/stanley/StableDiffusion/conv_nan_repro.mlir

**Comment by raikonenfnu** [comment]
Background:
We have this reduced IR, that seems to have a correctness issue.
This reduced IR is basically conv2d -> reduction -> elementwise add.
To repro, we can compare the output between CUDA and Vulkan output:
```bash
wget https://storage.googleapis.com/iree-shared-files/nod-perf/stanley/StableDiffusion/reduction/reduc_nan_repro.mlir

iree-compile --iree-input-type=none --iree-hal-target-backends=vulkan -iree-vulkan-target-triple=rdna2-unknown-linux --iree-flow-linalg-ops-padding-size=16 --iree-flow-enable-padding-linalg-ops --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 ~/nod/mlir_test/reduc_nan_repro.mlir -o /tmp/reduc_nan.vmfb

iree-run-module --module_file=/tmp/conv_nan.vmfb --device=vulkan --entry_function=forward --function_input="2x4x66x66xf16" --print_max_element_count=100000000 > ~/vulkan_reduc_f32.txt

iree-compile --iree-input-type=none --iree-hal-target-backends=cuda --iree-flow-linalg-ops-padding-size=16 --iree-flow-enable-padding-linalg-ops --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 ~/nod/mlir_test/reduc_nan_repro.mlir -o /tmp/reduc_nan.vmfb

iree-run-module --module_file=/tmp/conv_nan.vmfb --device=cuda --entry_function=forward --function_input="2x4x66x66xf16" --print_max_element_count=100000000 > ~/cuda_reduc_f32.txt

wget https://gist.githubusercontent.com/raikonenfnu/2c5bcc8b0d4d0783e8b21f3dd7492e33/raw/813d2f77832c313cf1a8ea93b204cb4c5d30e92b/run_module_result_check.py

python result_checker.py --cpu_backend_dispatch_path="/home/your_user_name/cuda_reduc_f32.txt" --target_backend_dispatch="/home/your_user_name/vulkan_reduc_f32.txt"
```

Interestingly, if we force the reduction and elementwise mulf to fuse using [this](https://github.com/nod-ai/SHARK-Runtime/commit/724e71426dab92c538b1615c7538dbf6af15a632), it works! Please check the difference of dispatches, especially dispatch_1 in vulkan_no_collapse, and disptach_1 and dispatch_2 in vulkan_collapse in the this [tarball](https://storage.googleapis.com/iree-shared-files/nod-perf/stanley/StableDiffusion/reduction/vulkan_collapse_vs_no_collapse.tar.gz)

**Comment by antiagainst** [comment]
It turns out this is due to the UnifyAliasedResourcePass. However the exact reason and thus fix would need more investigation. For now I'll just disable the pass for non-Apple platforms (given the pass is only necessary there): #10930.
