### ISSUE TITLE
[CI] setup script crashes on llvm-project cherry-pick 

### ISSUE THREAD

**Issue by kuhar** [iree-org/iree#10862]
### What happened?

The CI continues to crash for me when I try to cherry-pick an llvm-project commit. For example: https://github.com/iree-org/iree/actions/runs/3291795244/jobs/5426391256

It's not clear to me if I'm doing something wrong or if it's a bug in the script, but in either case, it'd be better for the script not to crash like that.

### Steps to reproduce your issue

My workflow was something like this:

1. Cherry-pick a future commit:
```shell
  cd third_party/llvm-project
  git switch -c my-branch
  git cherry-pick <SHA>
  git push upstream
```

2. Create an IREE commit updating the submodule, push to an iree fork, open a pull request.

**Comment by pzread** [comment]
It's a bug in `configure_ci.py`, working on the fix.
