### ISSUE TITLE
Add MemoryEffectOpInterface to vm.call and improve vm.import side-effect modeling

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#1088]
Right now vm.call ops cannot be CSEd as the nosideeffects attribute on vm.import ops is not visible to CSE (and even if it was it'd be incorrect in the case of allocations).

Adding the new MemoryEffectOpInterface to vm.call and then a way to express the attributes on vm.import ops and marshal it through the calls will let us get CSE/DCE automagically. The need for this is most noticeable near the end of lowering to the VM dialect where inlining or global initialization may combine functions and end up with redundant calls (to hal.ex.shared_device, for example).

```mlir
vm.import @ex.shared_device() -> !vm.ref<!hal.device>
attributes {nosideeffects}
```

```mlir
    vm.func @__init() {
      %ref = vm.call @hal.ex.shared_device() : () -> !vm.ref<!hal.device>
      %ref_1 = vm.call @hal.ex.shared_device() : () -> !vm.ref<!hal.device>
      ...
    }
```

**Comment by GMNGeoffrey** [comment]
I think related to https://github.com/google/iree/issues/1124

**Comment by benvanik** [comment]
Yep! I think #1124 can cover adding it to the dialects, where this covers adding it to vm.import/vm.call specifically (so that external/custom modules can declare side-effects). It may require some new vm attributes (like #vm.side_effect<"foo">) so that we can parse them.

**Comment by benvanik** [comment]
Here's an example of those shared_device calls:
https://gist.github.com/benvanik/cc49403752e2002b872b7d3a17df3cc0#file-5-vm-mlir-L153

**Comment by benvanik** [comment]
Duplicate of #1124.
