### ISSUE TITLE
Optimize transpose using shared memory in SPIRV backend

### ISSUE THREAD

**Issue by ThomasRaoux** [iree-org/iree#10932]
### What happened?

On targets supporting fast shared memory we can use it to optimize transposition and avoid bad memory access patterns in global memory.
The details are explained in this issue:
https://github.com/iree-org/iree/issues/10005
@KoolJBlack has implemented it for LLVMGPU path and most of the code can be re-used.
The change made were in those two commits:
https://github.com/iree-org/iree/commit/2829bcc10ee90b5a9d557b602c2dcaa43b5b5c2f
https://github.com/iree-org/iree/commit/6fa18e089ebb7570a3f4c61910f5a0b58957b55d

For SPIRV the kernelConfig needs to consider whether this is beneficial to the targets.

**Comment by aldesilv** [comment]
In SPIRV, how can we tell if using it is beneficial to the targets? Also, is there a heuristic for choosing the tile sizes and workgroup size?

**Comment by ThomasRaoux** [comment]
> In SPIRV, how can we tell if using it is beneficial to the targets? Also, is there a heuristic for choosing the tile sizes and workgroup size?

In general it should be beneficial if the target has an efficient native shared memory. 
Since there isn't an opportunity for re-use we most likely don't need an heuristic to pick the tile size and the workgroup size.
The tile size should be a square NxN where N is the number of element in a cacheline. This way a full cacheline can be read and a full cacheline can be written. Then the workgroup size should be something that allows efficient copy of the tile size so in general it would be something like (N, N/(16/sizeof(type)), 1) since we want to do copies where each thread copies 16bytes.

**Comment by antiagainst** [comment]
closing as obsolete -- no actions planned now
