### ISSUE TITLE
0d tensors being promoted to scalars with wrong dtype. (FusionOfTensorOps)

### ISSUE THREAD

**Issue by pashu123** [iree-org/iree#10959]
### What happened?

```
#map = affine_map<(d0, d1, d2) -> (d0, d1, 0)>
#map1 = affine_map<(d0, d1, d2) -> ()>
#map2 = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
module {
  func.func @forward(%arg0: tensor<2x4096x1xf16>) -> tensor<2x4096x1xf16> {
    %cst = arith.constant 1.000000e-05 : f64
    %0 = tensor.empty() : tensor<2x4096x1xf16>
    %1 = tensor.empty() : tensor<f16>
    %2 = linalg.fill ins(%cst : f64) outs(%1 : tensor<f16>) -> tensor<f16>
    %3 = linalg.generic {indexing_maps = [#map, #map1, #map2], iterator_types = ["parallel", "parallel", "parallel"]} ins(%arg0, %2 : tensor<2x4096x1xf16>, tensor<f16>) outs(%0 : tensor<2x4096x1xf16>) {
    ^bb0(%in: f16, %in_0: f16, %out: f16):
      %4 = arith.addf %in, %in_0 : f16
      linalg.yield %4 : f16
    } -> tensor<2x4096x1xf16>
    return %3 : tensor<2x4096x1xf16>
  }
}
```
Since the `linalg.fill` supports casting of the value operand, promoting it to the same data type as the output. This should be a legal IR.
Due to some optimization pass, I think the 0d tensor is somehow promoted to a scalar and this results in an error.
https://mlir.llvm.org/docs/Dialects/Linalg/#linalgfill-mlirlinalgfillop

More info: The fail is happening in the fusion of tensor ops pass.

```
// -----// IR Dump After FusionOfTensorOps Failed (iree-flow-fusion-of-tensor-ops) //----- //
"func.func"() ({
^bb0(%arg0: !hal.buffer_view):
  **%0 = "arith.constant"() {value = 9.99999974E-6 : f32} : () -> f32**
  %1 = "hal.tensor.import"(%arg0) {operand_segment_sizes = array<i32: 1, 0, 0>, target_encoding = tensor<2x4096x1xf16>} : (!hal.buffer_view) -> tensor<2x4096x1xf16>
  %2 = "tensor.empty"() : () -> tensor<2x4096x1xf16>
  %3 = "linalg.generic"(%1, %2) ({
  ^bb0(%arg1: f16, %arg2: f16):
    **%5 = "arith.addf"(%arg1, %0) : (f16, f32) -> f16**
    "linalg.yield"(%5) : (f16) -> ()
  }) {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel"], operand_segment_sizes = array<i32: 1, 1>} : (tensor<2x4096x1xf16>, tensor<2x4096x1xf16>) -> tensor<2x4096x1xf16>
  %4 = "hal.tensor.export"(%3) {operand_segment_sizes = array<i32: 1, 0, 0>, source_encoding = tensor<2x4096x1xf16>} : (tensor<2x4096x1xf16>) -> !hal.buffer_view
  "func.return"(%4) : (!hal.buffer_view) -> ()
}) {function_type = (!hal.buffer_view) -> !hal.buffer_view, iree.abi.stub, sym_name = "forward"} : () -> ()
```

### Steps to reproduce your issue

cuda-backend
`iree-compile  --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=cuda  --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvm-target-cpu-features=host --iree-hal-cuda-disable-loop-nounroll-wa --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs ~/test_cleaned.mlir`

vulkan-backend
` iree-compile   --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvm-target-cpu-features=host -iree-vulkan-target-triple=rdna2-unknown-linux --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs ~/test_cleaned.mlir`

This gives 
```
error: 'arith.addf' op requires the same type for all operands and results
      %4 = arith.addf %in, %in_0 : f16
           ^
```

**Comment by pashu123** [comment]
@ThomasRaoux Here's the diff https://reviews.llvm.org/D137447 Also, I have copied the cast function from https://github.com/llvm/llvm-project/blob/254bf678d49185026d1b17c6345106f9f3fe58b2/mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp#L423 . Do let me know if there's a better suggestion.

**Comment by ThomasRaoux** [comment]
> @ThomasRaoux Here's the diff https://reviews.llvm.org/D137447 Also, I have copied the cast function from https://github.com/llvm/llvm-project/blob/254bf678d49185026d1b17c6345106f9f3fe58b2/mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp#L423 . Do let me know if there's a better suggestion.

Thanks for fixing that! It would be great to not duplicate the function but to move it to a common place as you already did and re-use the existing function.
Let me know if you need help, I can also help merging the patch once this is done.

**Comment by pashu123** [comment]
@ThomasRaoux `for linalg ops the type would be signless, therefore this is probably not the right way to decide between signed and unsigned cast` Should I pass it as a function argument?

**Comment by ThomasRaoux** [comment]
> @ThomasRaoux `for linalg ops the type would be signless, therefore this is probably not the right way to decide between signed and unsigned cast` Should I pass it as a function argument?

Yes, the same way it was done in the existing linalg helper. This information should come the linalg op semantic, so you can just get this information out of the fillOp

**Comment by pashu123** [comment]
@ThomasRaoux Do you know how to extract the `TypeFn` from the fillOp. I didn't find any examples.

**Comment by pashu123** [comment]
This issue can be closed. Required changes have been merged https://reviews.llvm.org/D137447  @ThomasRaoux
