### ISSUE TITLE
Where IREE invokes llvm ?

### ISSUE THREAD

**Issue by Theoo1997** [iree-org/iree#10982]
### Request description

Hi,
I am working with IREE and I would like to know :

1. Where the compiler invokes llvm to compile the hal executables into the target platform.
2.  I also wont to see the llvm passes of the above step like "optimization_level = -O2", etc.
3. And print the llvm IR.

For example I've checked this steps here in the pictures and I didn't see any passes (like optimization_level = -O2 etc).:

Most probably because this steps translate the model to llvm IR?

![image](https://user-images.githubusercontent.com/109102287/199193844-556a92c6-6bcf-4581-b369-5ae814e5bbf1.png)

This step compiles the model to the target/targets platform using llvm? 

![image](https://user-images.githubusercontent.com/109102287/199193969-6a31bf4d-f54f-43b6-9b71-8a1bc2e21f0c.png)

**Comment by hanhanW** [comment]
> Where the compiler invokes llvm to compile the hal executables into the target platform.

This is the place that convert MLIR to LLVM module and invoke the LLVM passes: https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMCPUTarget.cpp#L160

> I also wont to see the llvm passes of the above step like "optimization_level = -O2", etc.

There are [LLVMTargetOptions](https://sourcegraph.com/github.com/iree-org/iree@7cd0a8cb6e1027188faa75b9361c4b10aab4707c/-/blob/compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp?L52) to set some options, and they are registered in https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMIRPasses.cpp

> And print the llvm IR.

You can dump whatever you want by adding some C++ codes, or use some flags like `--iree-llvm-keep-linker-artifacts`

https://sourcegraph.com/github.com/iree-org/iree@7cd0a8c/-/blob/compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp?L183-214&subtree=true

**Comment by Theoo1997** [comment]
> > Where the compiler invokes llvm to compile the hal executables into the target platform.
> 
> This is the place that convert MLIR to LLVM module and invoke the LLVM passes: https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMCPUTarget.cpp#L160
> 
> > I also wont to see the llvm passes of the above step like "optimization_level = -O2", etc.
> 
> There are [LLVMTargetOptions](https://sourcegraph.com/github.com/iree-org/iree@7cd0a8cb6e1027188faa75b9361c4b10aab4707c/-/blob/compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp?L52) to set some options, and they are registered in https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMIRPasses.cpp
> 
> > And print the llvm IR.
> 
> You can dump whatever you want by adding some C++ codes, or use some flags like `--iree-llvm-keep-linker-artifacts`
> 
> https://sourcegraph.com/github.com/iree-org/iree@7cd0a8c/-/blob/compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp?L183-214&subtree=true

Thank vary march for you answer!!
