### ISSUE TITLE
"requires-*" Bazel tags problematic for google-internal version

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#11000]
We introduced "requires-filesystem" and "requires-dtz" as tags to indicate tests that require certain features that may not be available on all platforms (e.g. baremetal). On importing this into Google's monorepo, I discovered that tags of the format "requires-*" have a special meaning that indicate what kind of executor they need to run on. You'll notice we also have CUDA tests tagged "requires-gpu-nvidia", which is for this reason. But filesystems are not one of the possible requirements and tl;dr it breaks the test. I think we have a couple options here:

1. Attempt to get the Google build infrastructure team to change how this works for unknown tags. Likely infeasible.
2. Strip/alter these flags as part of importing into google monorepo (what I did as a workaround for now).
3. Choose a different convention for our tags like this. This is kind of unfortunate because these really are analogous to requires-gpu-nvidia, so we end up with a state where people have to know which magic tags Google knows about. And "requires" does seem like kind of the logical name here.
4. Use Bazel platforms to encode this stuff. Likely technically feasible, but a ton of work.

I would vote for option 3 as my preference, but could also see the argument for option 2 (this is a weird Google-internal thing, so push it onto the Google integration). My argument for changing our convention is that it isn't really high cost for us at all and I don't think we need to deliberately make things harder for ourselves just to maintain purity around not letting weird Google-internal stuff influence us. I mean we basically have the whole Bazel build configuration because of weird Google-internal stuff.

Options for other names:
1. Suffix "required", e.g. "filesystem-required", "dtz-required". I think prefix is better here because it kind of "namespaces" all the tags like this, but probably not a big deal.
2. Prefix "needs", e.g. "needs-filesystem", "needs-dtz". Simple English Wikipedia approves :+1:
3. ...?

**Comment by GMNGeoffrey** [comment]
@ScottTodd any opinions? @hcindyl who added these (no good deed goes unpunished)

**Comment by hcindyl** [comment]
I vote for option 2.

**Comment by ScottTodd** [comment]
I'm fine with 1, 2, or 3. There aren't too many of these tags, so keep it simple until that changes.

**Comment by GMNGeoffrey** [comment]
Option 2 is more work for me, which is why I don't like it :-) It creates a maintenance burden and extra diffs between internal and open source. It's not *that* bad, but it is a headache. And if we add another "requires-*" tag, we have to edit the import scripting (we can't strip all requires tags because `requires-gpu-nvidia` is actually needed). We can use a regex to substitute and avoid the specific tag, but writing an RE2 regex that does that is actually really annoying (negating a whole word is super verbose). Anyway, all doable, but also annoying

**Comment by GMNGeoffrey** [comment]
It actually looks like we are maybe using this wrong. "requires" tags have a special meaning to Bazel as well: https://github.com/bazelbuild/bazel/blob/19b8d24531/src/main/java/com/google/devtools/build/lib/actions/ExecutionRequirements.java

**Comment by GMNGeoffrey** [comment]
I had some more discussion and think we're just going to go with option 2 for now. Maybe one day we'll figure out how Bazel platforms and toolchains work and set this all up properly here and then we'll see if there's a better way to map it internally, but for now doing the transformation of these few things is fine.
