### ISSUE TITLE
Upgrade GitHub Actions runner to at least 2.299.0 by 2022-12-01

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#11011]
https://github.com/actions/runner/releases/tag/v2.299.0

New release is out, which means we have [30 days to upgrade](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners#controlling-runner-software-updates-on-self-hosted-runners)

Same deal as https://github.com/iree-org/iree/issues/10546

**Comment by GMNGeoffrey** [comment]
As before, I'll wait at least a week or so for any patch versions

**Comment by GMNGeoffrey** [comment]
Ah but a few hours later https://github.com/actions/runner/releases/tag/v2.299.1. Seems GitHub's release validation for these may mostly be in prod...

**Comment by GMNGeoffrey** [comment]
Shouldn't have closed this as it needs to rollout. I pushed to canary yesterday

**Comment by GMNGeoffrey** [comment]
Did a full roll out

**Comment by pzread** [comment]
For some reasons we didn't see the rollout in the cluster. Re-rollout to canary, `version: 695985b58b-o8e`

**Comment by GMNGeoffrey** [comment]
Thank you!

**Comment by pzread** [comment]
Fully rolled out
