### ISSUE TITLE
Small numerical difference between Microkernel VMVX Output and LLVM reference

### ISSUE THREAD

**Issue by lundong** [iree-org/iree#11028]
### What happened?

An known issue is that output is incorrect (often completely off) when running TFLite imported and compiled target for VMVX backend (https://github.com/iree-org/iree/issues/10514).

Interestingly, when we enable microkernel, the outputs are almost correct, but are still of small numerical difference (up to 1 digit for all models we have tested), as compared with the reference output (LLVM backend).

### Steps to reproduce your issue

1. Build IREE
2. Download the sample person detection model from: https://storage.googleapis.com/iree-model-artifacts/person_detect.tflite 
3. Import the downloaded TFLite model
path/to/iree/integrations/tensorflow/iree_tf_compiler/iree-import-tflite path/to/person_detect.tflite -o=/tmp/person_detect.mlir
4. Use iree-compile to compile the MLIR
4.1 VMVX without microkernel
/path/to/iree-compile --iree-input-type=tosa --iree-hal-target-backends=vmvx /tmp/person_detect.mlir -o /tmp/person_detect_vmvx.vmfb
4.2 VMVX with microkernel
/path/to/iree-compile --iree-input-type=tosa --iree-hal-target-backends=vmvx --iree-vmvx-enable-microkernels /tmp/person_detect.mlir -o /tmp/person_detect_vmvx_ukernel.vmfb
4.3 LLVM (reference)
/path/to/iree-compile --iree-input-type=tosa --iree-hal-target-backends=llvm-cpu /tmp/person_detect.mlir -o /tmp/person_detect_llvm.vmfb
5. Run the model with all zero input and see different results
5.1 iree-run-module with VMVX without microkernel
/path/to/iree-run-module --module_file=/tmp/person_detect_vmvx.vmfb --entry_function=main --function_input="1x96x96x1xi8=0"
EXEC @main
result[0]: hal.buffer_view
1x2xi8=[-96 96]
5.2 iree-run-module with VMVX with microkernel
/path/to/iree_compiler/install/bin/iree-run-module --module_file=/tmp/person_detect_vmvx_ukernel.vmfb --entry_function=main --function_input="1x96x96x1xi8=0"
EXEC @main
result[0]: hal.buffer_view
1x2xi8=[73 -73]
5.3 iree-run-module with LLVM (reference output)
/path/to/iree-run-module --module_file=/tmp/person_detect_llvm.vmfb --entry_function=main --function_input="1x96x96x1xi8=0"
EXEC @main
result[0]: hal.buffer_view
1x2xi8=[72 -72]

### What component(s) does this issue relate to?

Compiler

### Version information

IREE ToT

### Additional context

As there is only 1-digit numerical difference, could this issue be relevant to how the rounding is done in microkernel?

**Comment by hcindyl** [comment]
@bjacob FYI

**Comment by bjacob** [comment]
The microkernel is a pure integer matmul, multiplying `i8` matrices into a `i32` result. Any rounding is done in other ops, which don't have microkernels at the moment.

**Comment by hcindyl** [comment]
Ahh, in that case, it is at the arith.trunci/arith.sitofp interaction as mentioned in https://github.com/iree-org/iree/issues/10514#issuecomment-1299138563

**Comment by aaron-schneider** [comment]
Has assignee and priority, so removing "awaiting-triage" label

**Comment by jpienaar** [comment]
Note, with the "workaround" mentioned in #10514 the non-microkernel produces same result as microkernel one ([73 -73]), comparing to LLVM the difference occurs due to small floating point difference that result in difference of 1:

```diff
diff /tmp/log.llvm /tmp/log2.vmvx
518c518
< 2xf32=1.91741 0.534759
---
> 2xf32=1.91741 0.53476
521c521
< 2xf32=1.91741 0.534759
---
> 2xf32=1.91741 0.53476
527c527
< 2xf32=1.91741 0.534759
---
> 2xf32=1.91741 0.53476
531c531
< 2xi8=72 -72
---
> 2xi8=73 -73
```

**Comment by lundong** [comment]
Close this issue, as it was confirmed that the small difference of 1 is an expected behavior (rather than bug) due to small floating point difference.
