### ISSUE TITLE
how to use --print-pipeline-passes flag

### ISSUE THREAD

**Issue by Theologis** [iree-org/iree#11095]
### What happened?

Hi, 
I would like to see all the passes for its pipeline step i.e :
                                      1. flow 
                                      2. stream
                                      3. Linalg/Vector
                                      4. llvm code gen
I've used --print-pipeline-passes flag into the compiler like that :
 `${BUILD_DIR}/tools/iree-compile \
                              ...........
    --print-pipeline-passes \ or --print-pipeline-passes=true
`
But nothing was displayed. Any ideas what I should do?

**Comment by ScottTodd** [comment]
That flag [comes from LLVM](https://github.com/llvm/llvm-project/blob/b1fdeeec1a5a570be57bca17fcc647892d2030ab/llvm/lib/Passes/PassBuilder.cpp#L261-L266), not MLIR. IREE is also just one user of MLIR/LLVM. You might get better support on one of MLIR's communication channels (MLIR Discourse forum, LLVM Discord server, LLVM issues, etc.).

For MLIR, https://mlir.llvm.org/docs/PassManagement/#ir-printing is a good reference. That explains flags like `--mlir-print-ir-after-all`

BTW, for the flag you asked about, if you search the source code for test files using it, you should find https://github.com/llvm/llvm-project/blob/main/llvm/test/Other/new-pm-print-pipeline.ll (but note again: that's for LLVM, not MLIR)

**Comment by Theologis** [comment]
HI [ScottTodd](https://github.com/ScottTodd)
Thank you for you answer. So there no way to print the passes from flow layer? For example for flow transformation I can see that this here are some passes:
   
![Screenshot from 2022-11-09 16-53-53](https://user-images.githubusercontent.com/36996704/201095526-90de219d-ae21-4f38-9ab7-2677bee35b24.png)

But are this the only ones ? Can I see it with a simple flag ?

**Comment by ScottTodd** [comment]
If you want a list of supported flags, run `iree-compile --help`. Here's a snippet of that output:
```
OVERVIEW: IREE compilation driver

USAGE: iree-compile.exe [options] <input file or '-' for stdin>

OPTIONS:

...

  --iree-flow-demote-f32-to-f16                                - Converts all f32 ops and values into f16 counterparts unconditionally before main flow conversions.
  --iree-flow-demote-f64-to-f32                                - Converts all f64 ops and values into f32 counterparts unconditionally before main flow conversions.
  --iree-flow-demote-i64-to-i32                                - Converts all i64 ops and values into i32 counterparts unconditionally before main flow conversions.
  --iree-flow-dispatch-use-transform-dialect=<string>          - mlir file containing a top-level module that specifies the transformations to apply to form dispatch regions.
  --iree-flow-dispatch-via-region-ops                          - Create dispatches via DispatchRegionOps
  --iree-flow-dispatch-via-region-ops-generate-workload-region - Generate the workload region when running with iree-flow-dispatch-via-region-ops
  --iree-flow-dump-dispatch-graph                              - Dump a dot graph for dispatches
  --iree-flow-dump-dispatch-graph-output-file=<string>         - Output file name for a dispatch graph dump
  --iree-flow-enable-aggressive-fusion                         - Enable the aggressive fusion heuristic to fuse multiuse ops and ops with reduction loops
  --iree-flow-enable-conv-img2col-transform                    - Enable converting convolution ops to img2col form.
  --iree-flow-enable-fuse-padding-into-linalg-consumer-ops     - Enable fusing tensor.pad ops into Linalg consumer ops
```

To see what passes run and what the effects those passes have during compilation, see the page I linked above (`--mlir-print-ir-after-all` is a good starting point)

**Comment by Theologis** [comment]
> 



> If you want a list of supported flags, run `iree-compile --help`. Here's a snippet of that output:
> 
> ```
> OVERVIEW: IREE compilation driver
> 
> USAGE: iree-compile.exe [options] <input file or '-' for stdin>
> 
> OPTIONS:
> 
> ...
> 
>   --iree-flow-demote-f32-to-f16                                - Converts all f32 ops and values into f16 counterparts unconditionally before main flow conversions.
>   --iree-flow-demote-f64-to-f32                                - Converts all f64 ops and values into f32 counterparts unconditionally before main flow conversions.
>   --iree-flow-demote-i64-to-i32                                - Converts all i64 ops and values into i32 counterparts unconditionally before main flow conversions.
>   --iree-flow-dispatch-use-transform-dialect=<string>          - mlir file containing a top-level module that specifies the transformations to apply to form dispatch regions.
>   --iree-flow-dispatch-via-region-ops                          - Create dispatches via DispatchRegionOps
>   --iree-flow-dispatch-via-region-ops-generate-workload-region - Generate the workload region when running with iree-flow-dispatch-via-region-ops
>   --iree-flow-dump-dispatch-graph                              - Dump a dot graph for dispatches
>   --iree-flow-dump-dispatch-graph-output-file=<string>         - Output file name for a dispatch graph dump
>   --iree-flow-enable-aggressive-fusion                         - Enable the aggressive fusion heuristic to fuse multiuse ops and ops with reduction loops
>   --iree-flow-enable-conv-img2col-transform                    - Enable converting convolution ops to img2col form.
>   --iree-flow-enable-fuse-padding-into-linalg-consumer-ops     - Enable fusing tensor.pad ops into Linalg consumer ops
> ```
> 
> To see what passes run and what the effects those passes have during compilation, see the page I linked above (`--mlir-print-ir-after-all` is a good starting point)

Thank you very much !!
