### ISSUE TITLE
CSE of single block ops creates correctness issues even when the generate IR is exactly the same.

### ISSUE THREAD

**Issue by MaheshRavishankar** [iree-org/iree#11101]
#10853 is the cherry pick of [D134306](https://reviews.llvm.org/D134306) to address failures in IREE with that patch. Summary of the patch upstream is that introduces CSE of operations with a single block. Just cherry picking it without any IREE changes causes failure in the [`bert_encoder_test`](https://github.com/iree-org/iree/blob/main/tests/e2e/models/bert_encoder_unrolled_fake_weights.mlir).

Interestingly the IR dumps with and without the cherry pick patch is identical. The gists are too big to paste here....  As a WAR I started adding a IREE local CSE pass that disables the CSE for single block ops, and used it in IREE. So it comes down to three uses of CSE passes
- 2 in https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Dialect/Stream/Transforms/Passes.cpp
- 1 in https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Dialect/HAL/Transforms/Passes.cpp

Using the CSE pass from upstream (with [D134306](https://reviews.llvm.org/D134306) ) causes the bert encoder to give garbage result. Using the IREE local CSE pass instead (added in #10853 ) which disables CSE of single block ops removes the failure.

For the time being, I am planning to submit #10853 but seems like this is exposing some weird behavior in IREE (I cant say if it is a compiler error since the generated IR is identical)

**Comment by benvanik** [comment]
I'm not sure I understand - is there any more context you can provide? I don't know what single block op CSE means :) Gists with elided constants?
I'm also not sure I follow what generated IR being exactly the same means - unless there's solar flares it should run the same if it's exactly the same?

**Comment by MaheshRavishankar** [comment]
Exact same in the sense, it is diff exact.

by single block op CSE, MLIR by default does not CSE ops which have regions. The patch adds CSE for ops with a single block.

**Comment by MaheshRavishankar** [comment]
Red herring I guess. Its not an issue any more.
