### ISSUE TITLE
Should `linalg_ext.pack` support computing sum-reductions for quantized matmuls with zero-points?

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#11146]
`linalg.quantized_matmul` supports arbitrary zero-points. `linalg.matmul` does not. We lower the former to the latter here: https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/InputConversion/Common/QuantizedMatmulToMatmul.cpp

This involves computing sums along rows/columns of the LHS/RHS matrices. The math is explained in comments in the above-linked file.

The ideal place to compute these sums is in the pack code, where the matrix data is being traversed anyway.

So I would like at least the pack ukernel to be able to compute sums.

This raises the question of whether `linalg_ext.pack` itself should have such support?

On the one hand, it would make it easy for the pass lowering `linalg_ext.pack` to pack ukernel.

On the other hand, it would not be directly usable by the above-linked `QuantizedMatmulToMatmul` pass, since at that early stage there isn't a `linalg_ext.pack` yet. So it seems that we will have some nontrivial graph transformation, one way or another?

@chelini

**Comment by MaheshRavishankar** [comment]
We should just rely on fusion for this to happen. Adding more semantics to pack operation is combining too many concepts.

**Comment by bjacob** [comment]
ok, thanks!
