### ISSUE TITLE
VM ops overuse `Pure` trait

### ISSUE THREAD

**Issue by kuhar** [iree-org/iree#11179]
VM ops seem to [overuse the `Pure` trait](https://github.com/iree-org/iree/blob/c1a2645da619fe517376617fcd3ec94c2624fd27/compiler/src/iree/compiler/Dialect/VM/IR/VMOps.td#L21). Any op that invokes UB on some inputs cannot be marked at `AlwaysSpeculatable` which is [implied by `Pure`](https://github.com/llvm/llvm-project/blob/cb33ef7ca71d864b5fb8efbe59d77e895ba6e9a0/mlir/include/mlir/Interfaces/SideEffectInterfaces.td#L133).

We recently fixed a similar issue in the arith dialect: https://github.com/llvm/llvm-project/issues/58700.

For vmvx, it seems to me like 'NoMemoryEffect' would be the safer default since these ops are implemented in C and inherit its immediate UB semantics (e.g., signed overflow, illegal shifts, etc). This would prevent them from being speculated or incorrectly hoisted.

Related/Parent issue: https://github.com/iree-org/iree/issues/10156

**Comment by kuhar** [comment]
cc: @benvanik @GMNGeoffrey @jpienaar

**Comment by GMNGeoffrey** [comment]
Yeah I think the origin of these long predates clear definitions of pure or even the `Pure` trait itself. We should clean these up
