### ISSUE TITLE
Uniform buffer descriptor type is not lowered to SPIR-V

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#11183]
### What happened?

This is blocking WebGPU push constant emulation (needed for real programs like posenet). cc @benvanik 

Original investigation [here on Discord](https://discord.com/channels/689900678990135345/867052513935753277/1042189916311928943)

When I tried to change https://github.com/iree-org/iree/blob/c1a2645da619fe517376617fcd3ec94c2624fd27/compiler/src/iree/compiler/Codegen/WGSL/WGSLReplacePushConstants.cpp#L138-L143 to `IREE::HAL::DescriptorType::UniformBuffer`, I'm still seeing spvasm like
```
%__resource_var_3_0_ = OpVariable %_ptr_StorageBuffer__struct_8 StorageBuffer
```
and WGSL like
```glsl
@binding(0) @group(3) var<storage, read_write> x__resource_var_3_0_ : S;
```

(we expect those to be 'uniform', not 'storage')

### Steps to reproduce your issue

1. Try to compile a program with `    %0 = hal.interface.binding.subspan set(3) binding(0) type(uniform_buffer) offset(%c1) : !flow.dispatch.tensor<readonly:tensor<2xi32>>` (e.g. a WebGPU program with push constants, and the change mentioned above)
2. Observe that the generated shaders are using StorageBuffer instead of UniformBuffer

### Version information

I'm working off of the `webgpu` branch (https://github.com/iree-org/iree/commit/94f71d54af847cd118911479dfe812560aac1f98), but I think this also happens at tip of tree (e.g. https://github.com/iree-org/iree/commit/a7140200ebd67e4d621f96b40253cd0dab9c454c)

### Additional context

This code doesn't appear to be using `subspanOp.getDescriptorType()`: https://github.com/iree-org/iree/blob/bdc6cf080b530f3ee65e46c5b9c383e747a4dd53/compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp#L114-L120

---

I traced through compilation to see where this information is lost:

Before `iree-codegen-iree-comprehensive-bufferize`:
```mlir
    %0 = hal.interface.binding.subspan set(3) binding(0) type(uniform_buffer) offset(%c1) : !flow.dispatch.tensor<readonly:tensor<2xi32>>
```
After `iree-codegen-iree-comprehensive-bufferize`:
```
    %0 = hal.interface.binding.subspan set(3) binding(0) type(uniform_buffer) offset(%c1) : memref<2xi32>
    %1 = hal.interface.binding.subspan set(3) binding(0) type(uniform_buffer) offset(%c1) : !flow.dispatch.tensor<readonly:tensor<2xi32>>
```
Before `map-memref-spirv-storage-class`:
```mlir
    %2 = hal.interface.binding.subspan set(3) binding(0) type(uniform_buffer) offset(%c0) : memref<?xi32>{%c2}
```
After `map-memref-spirv-storage-class`:
```mlir
    %2 = hal.interface.binding.subspan set(3) binding(0) type(uniform_buffer) offset(%c0) : memref<?xi32, #spirv.storage_class<StorageBuffer>>{%c2}
```

**Comment by antiagainst** [comment]
One more patch to upstream to enable SPIR-V side: https://reviews.llvm.org/D138257. Though there are more to do given this is touching MemRef memory space. Lots of upstream patterns assume numeric memory space, especially only 0. This includes bufferization and various conversions to LLVM. I might throw in a fallback for LLVM path for now given too many stuff to fix there. Will see whether I can get bufferization and SPIR-V flow working first..

**Comment by antiagainst** [comment]
https://reviews.llvm.org/D138330 addresses some bufferization issues.
