### ISSUE TITLE
Schedule release candidate CI workflow picks up commits with failed checks 

### ISSUE THREAD

**Issue by hcindyl** [iree-org/iree#11184]
### What happened?

https://github.com/iree-org/iree/actions/runs/3469376607/jobs/5796297215 
picked a failing commit (https://github.com/iree-org/iree/commit/3ff9d517054313a63d20012dcf9510e307915df1) as the "last green commit"

The code to pick up the commit is at https://github.com/talentpair/last-green-commit-action/blob/d95cfa836b22ef047dd0a8ddb1e6d9567982d702/src/main.ts#L34

GitHub REST api returns the `check_suites` via https://docs.github.com/en/rest/checks/suites#list-check-suites-for-a-git-reference

In the example above, it returns a list of check_suites with 13 checks, and some of them are with status `queued` and some of them are with the status `completed`

https://api.github.com/repos/iree-org/iree/check-suites/9307573321
https://api.github.com/repos/iree-org/iree/check-suites/9316620900

### What component(s) does this issue relate to?

Other

**Comment by hcindyl** [comment]
It could be more complicated than that.
If I query https://github.com/iree-org/iree/commit/3ff9d517054313a63d20012dcf9510e307915df1 with 
```
https://api.github.com/repos/iree-org/iree/commits/3ff9d517054313a63d20012dcf9510e307915df1/check-suites
```
And print out the name of the check_suite list and their status/conclusion
```
Google CLA
  status:queued
  conclusion:None
Dependabot
  status:queued
  conclusion:None
Buildkite
  status:queued
  conclusion:None
GitHub Pages
  status:queued
  conclusion:None
GitHub Actions
  status:completed
  conclusion:failure
GitHub Actions
  status:completed
  conclusion:success
GitHub Actions
  status:completed
  conclusion:success
GitHub Actions
  status:completed
  conclusion:success
GitHub Actions
  status:completed
  conclusion:success
GitHub Actions
  status:completed
  conclusion:success
GitHub Actions
  status:completed
  conclusion:success
GitHub Actions
  status:completed
  conclusion:success
GitHub Actions
  status:completed
  conclusion:success
```

If the flow changed from `Any` to `All` we may not find any usable commit if they are not the native GH actions.

**Comment by hcindyl** [comment]
If instead [check-runs](https://docs.github.com/en/rest/checks/runs#list-check-runs-for-a-git-reference) is called via REST API
```
https://api.github.com/repos/iree-org/iree/commits/3ff9d517054313a63d20012dcf9510e307915df1/check-runs
```
Then
```
publish_website
  status:completed
  conclusion:success
Publish release
  status:completed
  conclusion:success
Validate packages
  status:completed
  conclusion:success
Invoke workflow to validate and publish release
  status:completed
  conclusion:success
macos :: Build py-runtime-pkg Package
  status:completed
  conclusion:success
macos :: Build py-compiler-pkg Package
  status:completed
  conclusion:success
linux :: Build py-tf-compiler-tools-pkg Package
  status:completed
  conclusion:success
linux :: Build py-runtime-pkg Package
  status:completed
  conclusion:success
linux :: Build py-compiler-pkg Package
  status:completed
  conclusion:success
linux :: Build main-dist-linux Package
  status:completed
  conclusion:success
generate_report
  status:completed
  conclusion:success
Advance iree-mhlo-fork
  status:completed
  conclusion:success
Advance iree-llvm-fork
  status:completed
  conclusion:success
Advance iree-tf-fork
  status:completed
  conclusion:success
Advance iree-mhlo-fork
  status:completed
  conclusion:success
Advance iree-llvm-fork
  status:completed
  conclusion:success
Advance iree-tf-fork
  status:completed
  conclusion:success
benchmark_cuda
  status:completed
  conclusion:success
benchmark_cpu
  status:completed
  conclusion:success
setup
  status:completed
  conclusion:success
Advance iree-tf-fork
  status:completed
  conclusion:success
Advance iree-mhlo-fork
  status:completed
  conclusion:success
Advance iree-llvm-fork
  status:completed
  conclusion:success
summary
  status:completed
  conclusion:failure
test_benchmark_suites (host, x86_64, gcr.io/iree-oss/base@sha256:7c3027c48b94fc38e64488987fc7893c...
  status:completed
  conclusion:success
test_benchmark_suites (riscv, rv32-linux, gcr.io/iree-oss/riscv@sha256:cd2ee29950737f44b5ec54a32c...
  status:completed
  conclusion:success
test_benchmark_suites (riscv, rv64, gcr.io/iree-oss/riscv@sha256:cd2ee29950737f44b5ec54a32c37746e...
  status:completed
  conclusion:success
benchmarks / build_tools (riscv, rv64, gcr.io/iree-oss/riscv@sha256:cd2ee29950737f44b5ec54a32c37746e951fc74ef2...
  status:completed
  conclusion:success
benchmarks / build_suites
  status:completed
  conclusion:success
test_shark_model_suite
  status:completed
  conclusion:skipped
```

We may be able to distill the green commit with `check_runs["name"] == "summary" && check_runs["status"] == completed && check_runs["conclusion"] ==  "success"`

**Comment by GMNGeoffrey** [comment]
Oh God it's listing every possible check suite a commit could have 🤦

**Comment by hcindyl** [comment]
https://github.com/iree-org/iree/releases/tag/candidate-20221116.329 picked up a not-so-green https://github.com/iree-org/iree/commit/be18b66ea5d71dfed513cf98e5e52c5f09d7deaf again 😢

https://api.github.com/repos/iree-org/iree/commits/be18b66ea5d71dfed513cf98e5e52c5f09d7deaf/check-suites
https://api.github.com/repos/iree-org/iree/commits/be18b66ea5d71dfed513cf98e5e52c5f09d7deaf/check-runs?check_name=summary

**Comment by GMNGeoffrey** [comment]
Manually kicked off the workflow and it correctly picked the commit two behind head because the latest two were still running CI: https://github.com/iree-org/iree/actions/runs/3842646848/jobs/6544142849
