### ISSUE TITLE
[WebGPU] Missing BufferBlock decoration when using storage class Uniform

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#11229]
### What happened?

I'm continuing work to get real programs running on WebGPU, and this follows https://github.com/iree-org/iree/issues/11183.

Our push constant emulation code for WebGPU uses Uniform buffers, but up until now we've only supported Storage buffers. When trying to use uniform buffers I see this error from Tint:
```
Tint reported 1 error(s) for a SPIR-V program, see diagnostics:
error: line:38: For Vulkan, an OpTypeStruct variable containing an OpTypeRuntimeArray must be decorated with BufferBlock if it has storage class Uniform.
  %__resource_var_3_0_ = OpVariable %_ptr_Uniform__struct_8 Uniform
```

I see the same error for posenet and resnet50, in any executable (shader) that uses our push constant emulation.

### Steps to reproduce your issue

1. Use my [`webgpu-uniform-storage-debug` branch](https://github.com/ScottTodd/iree/tree/webgpu-uniform-storage-debug), or https://github.com/iree-org/iree/pull/11227 and this diff:
    ```diff
    --- a/compiler/src/iree/compiler/Codegen/WGSL/WGSLReplacePushConstants.cpp
    +++ b/compiler/src/iree/compiler/Codegen/WGSL/WGSLReplacePushConstants.cpp
    @@ -139,7 +139,7 @@ class WGSLReplacePushConstantsPass
             loc, dispatchTensorType,
             /*set=*/APInt(64, IREE_HAL_WEBGPU_PARAMS_BIND_GROUP_INDEX),
             /*binding=*/APInt(64, IREE_HAL_WEBGPU_PARAMS_BINDING_INDEX),
    -        IREE::HAL::DescriptorType::StorageBuffer, maxConstantValue, dynamicDims,
    +        IREE::HAL::DescriptorType::UniformBuffer, maxConstantValue, dynamicDims,
             alignmentAttr);
    ```
2. Compile a program that uses push constants for WebGPU, such as [`resnet50_fake_weights.mlir`](https://github.com/iree-org/iree/blob/main/tests/e2e/models/resnet50_fake_weights.mlir):
    ```
    iree-compile \
      --iree-hal-target-backends=webgpu \
      --iree-input-type=mhlo \
      tests/e2e/models/resnet50_fake_weights.mlir \
      -o /dev/null \
      --iree-hal-dump-executable-sources-to=/tmp/resnet50_webgpu/ \
      --iree-hal-dump-executable-intermediates-to=/tmp/resnet50_webgpu/ \
      --iree-hal-dump-executable-binaries-to=/tmp/resnet50_webgpu/
    ```
3. Observe the error:
    ```
    Tint reported 1 error(s) for a SPIR-V program, see diagnostics:
    error: line:38: For Vulkan, an OpTypeStruct variable containing an OpTypeRuntimeArray must be decorated with BufferBlock if it has storage class Uniform.
      %__resource_var_3_0_ = OpVariable %_ptr_Uniform__struct_8 Uniform
    ```   

Here's the .spvasm and .mlir for that resnet50 error: https://gist.github.com/ScottTodd/3308acaf7f54dd9bb0a56e633acb1099

### What component(s) does this issue relate to?

Compiler

### Version information

See above - https://github.com/iree-org/iree/pull/11227 and my one line change to `WGSLReplacePushConstants` are needed to get far enough to see this error. (Note: I'm assuming that both changes there are correct - we might be missing something else, but it's difficult to see more than one error ahead at a time)

### Additional context

Discussion [on Discord here](https://discord.com/channels/689900678990135345/867052513935753277/1043302547068297286). There might be some history here between older/newer versions of the SPIR-V spec and what Tint accepts and compiles to WGSL.

**Comment by antiagainst** [comment]
After a closer look, the reason is that we need to have static sizes for shader resources in uniform buffers. This should be easy to fix actually; here it is: https://github.com/iree-org/iree/pull/11248.

**Comment by ScottTodd** [comment]
Thanks for the patches, @antiagainst ! I see a different error now:

```
Tint reported 1 error(s) for a SPIR-V program, see diagnostics:
error: line:36: Structure id 8 decorated as Block for variable in Uniform storage class must follow relaxed uniform buffer layout rules: member 0 contains an array with stride 4 not satisfying alignment to 16
  %_struct_8 = OpTypeStruct %_arr_uint_uint_2

D:\dev\projects\iree/../iree-tmp/webgpu/posenet_2022_11_28/\module_main_dispatch_8.mlir:2:2: error: failed to compile SPIR-V to WGSL. Consider inspecting the shader program using -iree-hal-dump-executable-intermediates.
  hal.executable.variant public @webgpu_wgsl_fb, target = <"webgpu", "webgpu-wgsl-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.0, [Shader], [SPV_KHR_storage_buffer_storage_class]>, #spirv.resource_limits<>>}> {
 ^
```

.mlir/.spvasm: https://gist.github.com/ScottTodd/1534744f40053b34dc4671d445f974ce

Want to keep using this issue, or file a new one? I can also figure out a way to add a unit test that will show this on the `main` branch.

**Comment by ScottTodd** [comment]
Okay, I think the new error is different enough to keep this issue closed.
