### ISSUE TITLE
MaterializeEncodingConversionTarget + Debug + ASan = weird stack-buffer-overflow

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#11220]
STR:

Configure with `Debug` build type and enable ASan:

```
cmake -DCMAKE_BUILD_TYPE=Debug IREE_ENABLE_ASAN=ON
```

Rebuild `iree-compile`.

```
cmake --build . --target iree-compile
```

Run:

```
tools/iree-compile --iree-hal-target-backends=llvm-cpu $HOME/iree/runtime/src/iree/modules/check/test/success.mlir -o /tmp/a.vmfb
```

Result:

https://gist.github.com/bjacob/bd789d070aae45a6848887cef60fe064

I debugged this in GDB. The `op` here is a `arith.constant 0 : index` .   The `getOperands()` returns an empty range, which consists of a `nullptr` base pointer and a `0` length. Then as I step into the `llvm::any_of` at https://github.com/iree-org/iree/blob/1b95a2f285ac8d44e44f06de322abf5b315495bd/llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp#L413 , it immediately triggers the ASan error (above gist link).  Emphasis on *immediately*. So the code that's at fault here is part of the mechanics of the function call to `llvm::any_of`, before the actual start of `llvm::any_of`. Either that, or a miscompile.

**Comment by MaheshRavishankar** [comment]
Can you try dropping the `&` here https://github.com/iree-org/iree/blob/1b95a2f285ac8d44e44f06de322abf5b315495bd/llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp#LL417C6-L417C10

**Comment by bjacob** [comment]
Nice, it works with a `=` instead of the `&`.  (I need the `=` to be able to reference `hasOperandOrResultsWithEncoding`, unless i nested lambdas, which would look even hairier.

Can you make sense of the fact that changing the `&` into `=` makes it work? I can't.
