### ISSUE TITLE
[mhlo] error lowering mhlo.scatter to iree_linalg_ext.scatter: "op mismatch in shape of indices and update value at dim#0"

### ISSUE THREAD

**Issue by astrotuna201** [iree-org/iree#11234]
### What happened?

Follow-up from #11126 

The previous issue seems prematurely closed as current ToT still crashes after proposed fix.

The compilation fails 
```
<unknown>:0: error: 'iree_linalg_ext.scatter' op mismatch in shape of indices and update value at dim#0
<unknown>:0: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"llvm-cpu", "embedded-elf-arm_64", {cpu_features = "", data_layout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128", native_vector_size = 16 : index, target_triple = "arm64-unknown-unknown-eabi-elf"}>
<unknown>:0: error: failed to serialize executables
compilation failed
```

### Steps to reproduce your issue

Reproducer (shortened snippet from original mlir generated by jax:
```
#loc = loc(unknown)
module @jit_calc_grid_spacings_kernel {
  func.func public @main(%arg0: tensor<94xf32> loc(unknown)) -> (tensor<94xf32>) {
    %6 = mhlo.constant dense<2> : tensor<i32> loc(#loc)
    %7 = "mhlo.dynamic_slice"(%arg0, %6) {slice_sizes = dense<2> : tensor<1xi64>} : (tensor<94xf32>, tensor<i32>) -> tensor<2xf32> loc(#loc)
    %8 = mhlo.constant dense<92> : tensor<i32> loc(#loc)
    %9 = "mhlo.broadcast_in_dim"(%8) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<i32>) -> tensor<1xi32> loc(#loc)
    %10 = "mhlo.scatter"(%arg0, %9, %7) ({
    ^bb0(%arg12: tensor<f32> loc(unknown), %arg13: tensor<f32> loc(unknown)):
      mhlo.return %arg13 : tensor<f32> loc(#loc)
    }) {indices_are_sorted = true, scatter_dimension_numbers = #mhlo.scatter<update_window_dims = [0], scatter_dims_to_operand_dims = [0]>, unique_indices = true} : (tensor<94xf32>, tensor<1xi32>, tensor<2xf32>) -> tensor<94xf32> loc(#loc)
    return %10: tensor<94xf32>
  }
}
```

Compilation command:

```compiler/bindings/python/iree/compiler/tools/../_mlir_libs/iree-compile --iree-input-type=hlmo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvm-embedded-linker-path=iree-build/compiler/bindings/python/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false reproducer.mlir```

### What component(s) does this issue relate to?

Compiler

### Version information

[candidate-20221119.332](https://github.com/iree-org/iree/releases/tag/candidate-20221119.332)
jax, jaxlib 0.3.25

### Additional context

The full mlir was generated by jax from a [veros](https://veros.readthedocs.io/en/latest/) model.
When using the jax numpy backend, the model runs fine, switching to iree jax backend produces failure as above.

**Comment by jpienaar** [comment]
This seems to be working at head for me. Please reopen if this still fails for you

(Veros looks quite nice!)
