### ISSUE TITLE
TosaToLinalg lowering for tosa.convert clamps to int widths with truncating

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#11252]
`tosa.convert` for truncation operations clamps before truncating for integer operations (e.g. `i32` -> `i8`). These clamp operations should be removed from the TosaToLinalg lowerings.

https://www.mlplatform.org/tosa/tosa_spec.html#_cast

**Comment by jpienaar** [comment]
Should this one be tracked in LLVM github issues? (I think all the work will happen upstream)

**Comment by rsuderman** [comment]
Probably - I wasn't certain if LLVM was consistently using GitHub issues now. Fortunately Marie just landed the fix so we can just close now.

**Comment by jpienaar** [comment]
Yes :) (we could add the issue to the commit to have github close the issue for us, I think that works cross-repo, within repo more common).
