### ISSUE TITLE
Bufferize early pipelines fail with #10648

### ISSUE THREAD

**Issue by MaheshRavishankar** [iree-org/iree#11325]
#10648 changes the conversion to destination passing style to avoid the changing the `linalg.generic` fused with producer matmul/reduction ops, etc. to use the result of the producer as the `outs` operand. This was done as a hint to bufferization to avoid in-place allocation. This only works when the pipeline uses vectorization before bufferization. The SPIR-V/CUDA paths that bufferize early (the tensor matmul codegen paths) will result in intermediate allocations. For now there is a WAR flag added to the convert to destination passing style to keep the legacy behavior that can be dropped when these passes get modernized (i.e. use tensors -> vectors -> bufferize path instead of tensor -> bufferize -> vectors path).

**Comment by ThomasRaoux** [comment]
Do you have anytime timeline for this? Most of the stuff is ready to move but I have been trying to avoid interfering with the mma.sync work.

**Comment by MaheshRavishankar** [comment]
In the PR, I added a WAR flag so that this is decoupled from the work happening here... When it is landed you can just drop the WAR. In terms of landing the PR #10648 thats already ready to go...

**Comment by allieculp** [comment]
@ThomasRaoux Old issue here - any update?

**Comment by antiagainst** [comment]
closing as obsolete -- no actions planned now
