### ISSUE TITLE
iree-compile failures with -1 dim tensor shape mismatch (conv2d)

### ISSUE THREAD

**Issue by monorimet** [iree-org/iree#11328]
### What happened?

Many of our models in SHARK are encountering the following error:

```
E         iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
E         Diagnostics:
E         /data/anush/actions-runner/_work/SHARK/SHARK/shark.venv/lib/python3.10/site-packages/torch/nn/modules/conv.py:459:15: error: specified type 'tensor<-1x-1x-1x-1xf32>' does not match the inferred type 'tensor<-1x1x222x222xf32>'
E                 return F.conv2d(input, weight, bias, self.stride,
E                       ^
E         /data/anush/actions-runner/_work/SHARK/SHARK/tank/model_utils.py:138:15: note: called from
E                 return self.model.forward(input)
E                       ^
E         /data/anush/actions-runner/_work/SHARK/SHARK/shark.venv/lib/python3.10/site-packages/torch/nn/modules/conv.py:459:15: note: in bytecode version 0 produced by: MLIR16.0.0git
E                 return F.conv2d(input, weight, bias, self.stride,
E                       ^
E         
E         
E         Invoked with:
E          iree-compile /home/ean/SHARK/shark.venv/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-llvm-embedded-linker-path=/home/ean/SHARK/shark.venv/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --mlir-pass-pipeline-crash-reproducer=./shark_tmp/wide_resnet50_2_torch_False_vulkanim1uiycn/core-reproducer.mlir --iree-llvm-target-cpu-features=host -iree-vulkan-target-triple=ampere-rtx3080-linux --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs
E         
```

The models affected can be found listed in [this storage bucket](https://console.cloud.google.com/storage/browser/shark-public/builder/repro_artifacts/32a2) which also contains the reproducers for each failure.

### Steps to reproduce your issue

Issue can be reproduced as of ToM SHARK/IREE -> locally reproduced with SHARK pytest 

or

1. Download reproducers (linked above)
```shell
gsutil cp -r https://storage.cloud.google.com/shark-public/builder/repro_artifacts/32a2/alexnet_torch_False_cpu/
```

2. Run iree-compile:
```shell
iree-compile alexnet_torch_False_cpu/core-input.mlir --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --mlir-print-debuginfo --iree-llvm-target-cpu-features=host -iree-llvm-target-triple=x86_64-linux-gnu --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs
```

### What component(s) does this issue relate to?

Compiler

### Version information

ec8e830807dd3e54fd680dde79dfcf3807d7c90a

**Comment by monorimet** [comment]
This is also tracked on our side [here](https://github.com/nod-ai/SHARK/issues/511) for further reference.

**Comment by benvanik** [comment]
I think this is something coming from the frontend you'll need to check out there. The -1's are already present in the mlirbc you linked and a debug build of the compiler can't even load the file (asserts in the RankedTensorType builder when parsing the file).

Can you verify that the MLIR you are passing to iree-compile does not have an -1 dims in it?

**Comment by rsuderman** [comment]
I would guess this is due to the kDynamicSize change. If it is a bc serialized file I would expect it hardcodes the value into the binary.

**Comment by hanhanW** [comment]
We fixed couple places about using `-1` magic number in LLVM integrates.

+1 on @rsuderman , I would guess replacing these magic numbers with `ShapedType::kDynamic` could address the issue.

**Comment by monorimet** [comment]
Hey all, thanks for the input -- [this PR in torch-mlir](https://github.com/llvm/torch-mlir/pull/1654) should solve this issue.
