### ISSUE TITLE
Optimize "padding" operations created by im2col

### ISSUE THREAD

**Issue by ThomasRaoux** [iree-org/iree#11338]
### What happened?

Im2Col creates padding operations that have 6 parallel dimensions and that have non permutation maps. This result in poor code generation in iree.

Ex:
```
        %5 = tensor.empty() : tensor<2x1280x3x3x8x8xf16> 
        %6 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d4 + d2, d5 + d3)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4, d5)>], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel", "parallel"]} ins(%4 : tensor<2x1280x10x10xf16>) outs(%5 : tensor<2x1280x3x3x8x8xf16>) { 
        ^bb0(%in: f16, %out: f16):
          linalg.yield %in : f16
        } -> tensor<2x1280x3x3x8x8xf16>
```

To get good performance we need to:
1. Improve distribution, here the higher dims are not distributed creating large serialized loops
2. Get vectorization or better coalescing for the load and stores

**Comment by ThomasRaoux** [comment]
cc: @grypp as it is slightly related to things you are looking at.

**Comment by grypp** [comment]
Yes I've implemented #11295 that can collapse multiple scenarios but not this case. 

It is safe to collapse `d0-d1` dimensions, however, collapsing mechanism in MLIR have the following assert. So I left this as a future work. First we need to improve MLIR , then enable collapsing from iree. 
```
assert(indexingMap.isProjectedPermutation() && "expected indexing map to be projected permutation");
```

**Comment by ThomasRaoux** [comment]
> It is safe to collapse `d0-d1` dimensions, however, collapsing mechanism in MLIR have the following assert. So I left this as a future work. First we need to improve MLIR , then enable collapsing from iree.

That makes sense, this is already a nice improvements :)

**Comment by ThomasRaoux** [comment]
The performance for this ops are fixed and we are getting decent efficiency. We may want to add support for vectorization to improve things further but we would track this on a different issue.
