### ISSUE TITLE
FusionOfTensorOps pass silently failing when compiling random key generation

### ISSUE THREAD

**Issue by phoenix-meadowlark** [iree-org/iree#11333]
### What happened?

`iree-compile` exits without sending any text to stdout/stderr with a code of `1` when attempting to compile a Flax module that uses random key generation. Support for this is require for training.

This appears to be a regression and supersedes the error in https://github.com/iree-org/iree/issues/11201.

### Steps to reproduce your issue

Python to generate the module:

```python
import flax.linen as nn

class MakeRNG(nn.Module):
  pass

module = MakeRNG().bind({}, rngs={"random": jax.random.PRNGKey(0)})

def make_rng():
  return module.make_rng("random")

ir_module = jax.jit(make_rng, backend="iree").lower().compiler_ir()
with open("/tmp/make_rng.mlir", "wb") as f:
  ir_module.operation.print(file=f, binary=True, print_generic_op_form=True)
```

A MLIR reproducer can be found here: [`make_rng.mlir`](https://gist.github.com/phoenix-meadowlark/907d6c4edf65facc1461e5590a77ab8e)

The crash can be reproduced by running the following command:

```shell
iree-compile \
  --iree-hal-target-backends=llvm-cpu \
  --iree-input-type=mhlo \
  /tmp/make_rng.mlir \
  -o /tmp/make_rng.vmfb
```

### What component(s) does this issue relate to?

Compiler

### Version information

379d4a58f04bd4cd86e7d7b19aae85b2351b24d0

**Comment by benvanik** [comment]
Weird - I'm getting a failure in FusionOfTensorOps but it's not printing an error so it exits with 1 but doesn't print anything unless dumping ir after all. I'll see if I can find the exact source:
```
// -----// IR Dump After FusionOfTensorOps Failed (iree-flow-fusion-of-tensor-ops) //----- //
```

**Comment by benvanik** [comment]
The failure is coming from the `fusionPatterns` application. I'm guessing the IR chain here is deep enough to trigger the max iterations as setting it to 100 lets it pass. That's a bit scary from a algorithmic complexity standpoint but it wouldn't shock me if we're close to the limits elsewhere too :/

**Comment by MaheshRavishankar** [comment]
Thanks for triaging @benvanik (feel free to bump these to me)
