### ISSUE TITLE
[Build Error] Build is failing while linking LLVM

### ISSUE THREAD

**Issue by AhmadTameem** [iree-org/iree#11343]
I am getting this error while building IREE by using the guide given on official site (https://iree-org.github.io/iree/building-from-source/getting-started/). I already have LLVM and MLIR build in separate directories, but building with IREE is not working. 

Here are the terminal progress with error messages,
`$  cmake --build ../iree-build/
[0/2] Re-checking globbed directories...
[2192/4992] Linking CXX executable third_party/llvm-project/llvm/bin/lld

**FAILED: third_party/llvm-project/llvm/bin/lld** 

: && /usr/bin/clang++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -w -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -g -Wno-unused-command-line-argument -fuse-ld=lld -Wl,--color-diagnostics   -Wl,--export-dynamic third_party/llvm-project/llvm/tools/lld/tools/lld/CMakeFiles/lld.dir/lld.cpp.o third_party/llvm-project/llvm/tools/lld/tools/lld/CMakeFiles/lld.dir/lld-driver.cpp.o -o third_party/llvm-project/llvm/bin/lld  -Wl,-rpath,"\$ORIGIN/../lib"  third_party/llvm-project/llvm/lib/libLLVMSupport.a  -lpthread  third_party/llvm-project/llvm/lib/liblldCommon.a  third_party/llvm-project/llvm/lib/liblldCOFF.a  third_party/llvm-project/llvm/lib/liblldELF.a  third_party/llvm-project/llvm/lib/liblldMachO.a  third_party/llvm-project/llvm/lib/liblldMinGW.a  third_party/llvm-project/llvm/lib/liblldWasm.a  third_party/llvm-project/llvm/lib/liblldCOFF.a  third_party/llvm-project/llvm/lib/libLLVMLibDriver.a  third_party/llvm-project/llvm/lib/libLLVMWindowsDriver.a  third_party/llvm-project/llvm/lib/libLLVMWindowsManifest.a  third_party/llvm-project/llvm/lib/liblldCommon.a  third_party/llvm-project/llvm/lib/libLLVMOption.a  third_party/llvm-project/llvm/lib/libLLVMX86CodeGen.a  third_party/llvm-project/llvm/lib/libLLVMX86AsmParser.a  third_party/llvm-project/llvm/lib/libLLVMX86Desc.a  third_party/llvm-project/llvm/lib/libLLVMX86Disassembler.a  third_party/llvm-project/llvm/lib/libLLVMX86Info.a  third_party/llvm-project/llvm/lib/libLLVMARMCodeGen.a  third_party/llvm-project/llvm/lib/libLLVMARMAsmParser.a  third_party/llvm-project/llvm/lib/libLLVMARMDisassembler.a  third_party/llvm-project/llvm/lib/libLLVMARMDesc.a  third_party/llvm-project/llvm/lib/libLLVMARMInfo.a  third_party/llvm-project/llvm/lib/libLLVMARMUtils.a  third_party/llvm-project/llvm/lib/libLLVMAArch64CodeGen.a  third_party/llvm-project/llvm/lib/libLLVMCFGuard.a  third_party/llvm-project/llvm/lib/libLLVMAArch64AsmParser.a  third_party/llvm-project/llvm/lib/libLLVMAArch64Disassembler.a  third_party/llvm-project/llvm/lib/libLLVMAArch64Desc.a  third_party/llvm-project/llvm/lib/libLLVMAArch64Info.a  third_party/llvm-project/llvm/lib/libLLVMAArch64Utils.a  third_party/llvm-project/llvm/lib/libLLVMRISCVCodeGen.a  third_party/llvm-project/llvm/lib/libLLVMGlobalISel.a  third_party/llvm-project/llvm/lib/libLLVMRISCVAsmParser.a  third_party/llvm-project/llvm/lib/libLLVMRISCVDisassembler.a  third_party/llvm-project/llvm/lib/libLLVMRISCVDesc.a  third_party/llvm-project/llvm/lib/libLLVMRISCVInfo.a  third_party/llvm-project/llvm/lib/libLLVMWebAssemblyCodeGen.a  third_party/llvm-project/llvm/lib/libLLVMAsmPrinter.a  third_party/llvm-project/llvm/lib/libLLVMSelectionDAG.a  third_party/llvm-project/llvm/lib/libLLVMWebAssemblyAsmParser.a  third_party/llvm-project/llvm/lib/libLLVMWebAssemblyDisassembler.a  third_party/llvm-project/llvm/lib/libLLVMWebAssemblyDesc.a  third_party/llvm-project/llvm/lib/libLLVMMCDisassembler.a  third_party/llvm-project/llvm/lib/libLLVMWebAssemblyInfo.a  third_party/llvm-project/llvm/lib/libLLVMWebAssemblyUtils.a  third_party/llvm-project/llvm/lib/libLLVMLTO.a  third_party/llvm-project/llvm/lib/libLLVMCodeGen.a  third_party/llvm-project/llvm/lib/libLLVMExtensions.a  third_party/llvm-project/llvm/lib/libLLVMPasses.a  third_party/llvm-project/llvm/lib/libLLVMTarget.a  third_party/llvm-project/llvm/lib/libLLVMObjCARCOpts.a  third_party/llvm-project/llvm/lib/libLLVMCoroutines.a  third_party/llvm-project/llvm/lib/libLLVMipo.a  third_party/llvm-project/llvm/lib/libLLVMBitWriter.a  third_party/llvm-project/llvm/lib/libLLVMInstrumentation.a  third_party/llvm-project/llvm/lib/libLLVMLinker.a  third_party/llvm-project/llvm/lib/libLLVMFrontendOpenMP.a  third_party/llvm-project/llvm/lib/libLLVMScalarOpts.a  third_party/llvm-project/llvm/lib/libLLVMAggressiveInstCombine.a  third_party/llvm-project/llvm/lib/libLLVMInstCombine.a  third_party/llvm-project/llvm/lib/libLLVMIRPrinter.a  third_party/llvm-project/llvm/lib/libLLVMVectorize.a  third_party/llvm-project/llvm/lib/libLLVMTransformUtils.a  third_party/llvm-project/llvm/lib/libLLVMAnalysis.a  third_party/llvm-project/llvm/lib/libLLVMProfileData.a  third_party/llvm-project/llvm/lib/libLLVMSymbolize.a  third_party/llvm-project/llvm/lib/libLLVMDebugInfoDWARF.a  third_party/llvm-project/llvm/lib/libLLVMDebugInfoPDB.a  third_party/llvm-project/llvm/lib/libLLVMDebugInfoMSF.a  third_party/llvm-project/llvm/lib/libLLVMObject.a  third_party/llvm-project/llvm/lib/libLLVMTextAPI.a  third_party/llvm-project/llvm/lib/libLLVMMCParser.a  third_party/llvm-project/llvm/lib/libLLVMMC.a  third_party/llvm-project/llvm/lib/libLLVMDebugInfoCodeView.a  third_party/llvm-project/llvm/lib/libLLVMIRReader.a  third_party/llvm-project/llvm/lib/libLLVMBitReader.a  third_party/llvm-project/llvm/lib/libLLVMAsmParser.a  third_party/llvm-project/llvm/lib/libLLVMCore.a  third_party/llvm-project/llvm/lib/libLLVMRemarks.a  third_party/llvm-project/llvm/lib/libLLVMBitstreamReader.a  third_party/llvm-project/llvm/lib/libLLVMBinaryFormat.a  third_party/llvm-project/llvm/lib/libLLVMSupport.a  -lrt  -ldl  -lpthread  -lm  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libtinfo.so  third_party/llvm-project/llvm/lib/libLLVMDemangle.a && cd /home/oxe-lpt-50/iree-build/third_party/llvm-project/llvm/tools/lld/tools/lld && /home/oxe-lpt-50/temp/cmake-3.25.0/bin/cmake -E create_symlink lld /home/oxe-lpt-50/iree-build/third_party/llvm-project/llvm/./bin/lld-link && cd /home/oxe-lpt-50/iree-build/third_party/llvm-project/llvm/tools/lld/tools/lld && /home/oxe-lpt-50/temp/cmake-3.25.0/bin/cmake -E create_symlink lld /home/oxe-lpt-50/iree-build/third_party/llvm-project/llvm/./bin/ld.lld && cd /home/oxe-lpt-50/iree-build/third_party/llvm-project/llvm/tools/lld/tools/lld && /home/oxe-lpt-50/temp/cmake-3.25.0/bin/cmake -E create_symlink lld /home/oxe-lpt-50/iree-build/third_party/llvm-project/llvm/./bin/ld64.lld && cd /home/oxe-lpt-50/iree-build/third_party/llvm-project/llvm/tools/lld/tools/lld && /home/oxe-lpt-50/temp/cmake-3.25.0/bin/cmake -E create_symlink lld /home/oxe-lpt-50/iree-build/third_party/llvm-project/llvm/./bin/wasm-ld
**ld.lld: error: undefined hidden symbol: blake3_compress_in_place_avx512**
>>> referenced by blake3_dispatch.c:146 (/home/oxe-lpt-50/iree/third_party/llvm-project/llvm/lib/Support/BLAKE3/blake3_dispatch.c:146)
>>>               blake3_dispatch.c.o:(blake3_compress_in_place) in archive third_party/llvm-project/llvm/lib/libLLVMSupport.a

**ld.lld: error: undefined hidden symbol: blake3_compress_in_place_sse41**
>>> referenced by blake3_dispatch.c:152 (/home/oxe-lpt-50/iree/third_party/llvm-project/llvm/lib/Support/BLAKE3/blake3_dispatch.c:152)
>>>               blake3_dispatch.c.o:(blake3_compress_in_place) in archive third_party/llvm-project/llvm/lib/libLLVMSupport.a

**ld.lld: error: undefined hidden symbol: blake3_compress_in_place_sse2**
>>> referenced by blake3_dispatch.c:158 (/home/oxe-lpt-50/iree/third_party/llvm-project/llvm/lib/Support/BLAKE3/blake3_dispatch.c:158)
>>>               blake3_dispatch.c.o:(blake3_compress_in_place) in archive third_party/llvm-project/llvm/lib/libLLVMSupport.a

**ld.lld: error: undefined hidden symbol: blake3_compress_xof_avx512**
>>> referenced by blake3_dispatch.c:175 (/home/oxe-lpt-50/iree/third_party/llvm-project/llvm/lib/Support/BLAKE3/blake3_dispatch.c:175)
>>>               blake3_dispatch.c.o:(blake3_compress_xof) in archive third_party/llvm-project/llvm/lib/libLLVMSupport.a

**ld.lld: error: undefined hidden symbol: blake3_compress_xof_sse41**
>>> referenced by blake3_dispatch.c:181 (/home/oxe-lpt-50/iree/third_party/llvm-project/llvm/lib/Support/BLAKE3/blake3_dispatch.c:181)
>>>               blake3_dispatch.c.o:(blake3_compress_xof) in archive third_party/llvm-project/llvm/lib/libLLVMSupport.a

**ld.lld: error: undefined hidden symbol: blake3_compress_xof_sse2**
>>> referenced by blake3_dispatch.c:187 (/home/oxe-lpt-50/iree/third_party/llvm-project/llvm/lib/Support/BLAKE3/blake3_dispatch.c:187)
>>>               blake3_dispatch.c.o:(blake3_compress_xof) in archive third_party/llvm-project/llvm/lib/libLLVMSupport.a

**ld.lld: error**: undefined hidden symbol: blake3_hash_many_avx512
>>> referenced by blake3_dispatch.c:204 (/home/oxe-lpt-50/iree/third_party/llvm-project/llvm/lib/Support/BLAKE3/blake3_dispatch.c:204)
>>>               blake3_dispatch.c.o:(blake3_hash_many) in archive third_party/llvm-project/llvm/lib/libLLVMSupport.a

**ld.lld: error**: undefined hidden symbol: blake3_hash_many_avx2
>>> referenced by blake3_dispatch.c:212 (/home/oxe-lpt-50/iree/third_party/llvm-project/llvm/lib/Support/BLAKE3/blake3_dispatch.c:212)
>>>               blake3_dispatch.c.o:(blake3_hash_many) in archive third_party/llvm-project/llvm/lib/libLLVMSupport.a

ld.lld: **error**: undefined hidden symbol: blake3_hash_many_sse41
>>> referenced by blake3_dispatch.c:220 (/home/oxe-lpt-50/iree/third_party/llvm-project/llvm/lib/Support/BLAKE3/blake3_dispatch.c:220)
>>>               blake3_dispatch.c.o:(blake3_hash_many) in archive third_party/llvm-project/llvm/lib/libLLVMSupport.a

ld.lld: **error**: undefined hidden symbol: blake3_hash_many_sse2
>>> referenced by blake3_dispatch.c:228 (/home/oxe-lpt-50/iree/third_party/llvm-project/llvm/lib/Support/BLAKE3/blake3_dispatch.c:228)
>>>               blake3_dispatch.c.o:(blake3_hash_many) in archive third_party/llvm-project/llvm/lib/libLLVMSupport.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[9/2881] Building CXX object third_par...keFiles/MLIRTableGen.dir/Pattern.cpp.o

**ninja: build stopped: subcommand failed.**`

Thank you!

**Comment by stellaraccident** [comment]
I've never seen this issue before, and it is a quite basic failure in a very low level part of the llvm support library.

Can you share more information on the os and system you are on? I would usually categorize this as some kind of mis applied feature detect or ifdef in the build.

A couple of other things to try:

* Build with the "-k 100" flag and see if all exchanges are failing to link in this way or just lld.
* Try to build your other llvm tree with lld enabled and see if it again fails on building lld.
* try to build in Release mode (I found some suspect references to this making a difference when searching).

If it is system specific, we'll probably need to isolate a repro, so any more details you can provide may give the clue.

**Comment by AhmadTameem** [comment]
Thank you so much your reply!

My OS is Ubuntu 20.04.5 LTS and system is Lenovo v15-g2-itl. 

I think it could be an OS issue because earlier I tried building Polygeist (C++ MLIR Frontend) and it also failed with similar error. Although I rebuild MLIR-LLVM with lld enabled and it was successful.

I tried to search possible causes of error but found none. If you need any more information feel free to ask. Thanks again.

**Comment by stellaraccident** [comment]
This error is reminiscent to me of somehow having another llvm library on the system that is getting used for part of the build (and exports a slightly different API, resulting in inscrutable linking issues), but I don't have anything to base that on. May be a red herring.

Definitely sounds like something specific to your setup. One way that can help identify if an environmental issue is to build in a clean docker container.

Otherwise, I would go looking at the preprocessor macros in the falling file and connect them back to whatever feature detect code is deriving them. It seems like something is going wrong there. You may be able to make a local white to disable support for those vector extensions to see if that clears it. I'm not familiar with the code that is failing and would be debugging it fresh, same as you.

**Comment by AhmadTameem** [comment]
Okay, thank you for your reply. I will then try to build it with docker image.
