### ISSUE TITLE
CI job `build_test_all_windows` is failing to compile programs

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#11350]
First failing at https://github.com/iree-org/iree/commit/7efcd0aadc7c3d7e38ea7c7c465cd54bbb878911, sample logs: https://github.com/iree-org/iree/actions/runs/3576466891/jobs/6014311960.

I can't reproduce the failures locally. Some discussion about this failure [here on DIscord](https://discord.com/channels/689900678990135345/689957613152239638/1047218264222208010)

Possibly an infrastructure issue with the `managed-windows-cpu` runners - maybe we can restart them / check their disk space / etc.?

**Comment by ScottTodd** [comment]
Some ideas to debug this:
* Try re-enabling the job with no edits, maybe it fixed itself :crossed_fingers: 
* Try just building `iree-compile` and invoking that directly, rather than building `all` and having CMake invoke the tool for a bunch of generated targets
* Switch from `managed-windows-cpu` runners to the smaller Windows runners (will be much slower, but can help narrow down the issue(s))

**Comment by ScottTodd** [comment]
Huh, something strange is happening: https://github.com/iree-org/iree/actions/runs/3605109699/jobs/6075186286

Even with `-DIREE_LINK_COMPILER_SHARED_LIBRARY=OFF`, 

* This works: `./${BUILD_DIR}/tools/iree-tblgen.exe --help`
* This crashes with `Error: Process completed with exit code 127.`: `./${BUILD_DIR}/tools/iree-compile.exe --help`

I'm not seeing much in the logs that would explain why that is happening.

The next thing to try is probably reverting some changes / rolling back to a previously passing commit to see if something in the hosted runner environment itself changed.

**Comment by GMNGeoffrey** [comment]
> Possibly an infrastructure issue with the `managed-windows-cpu` runners - maybe we can restart them / check their disk space / etc.?

These are GitHub-managed ephemeral runners, so none of these really make sense as options. The environment changing is certainly a possibility though. Perhaps try dockerizing?
