### ISSUE TITLE
Add target environment for AMD RX 500 Series (GCN architectures)

### ISSUE THREAD

**Issue by averad** [iree-org/iree#11417]
### Request description

Please add the RX 500 Series of cards to IREE Target-Triple so they can be utilized without manually building IREE.

### Vulkan Info Output:
[vulkan_info_out.txt](https://github.com/nod-ai/SHARK/files/10136814/vulkan_info_out.txt)

[vulkan.gpuinfo.org](https://vulkan.gpuinfo.org/displayreport.php?id=17415)

### Untested Code Change
https://github.com/iree-org/iree/compare/main...averad:iree:rx500_series-TargetTripple

I am working on testing the above code using [SHARK](https://github.com/nod-ai/SHARK-Runtime/wiki/SHARK-Runtime-Windows-Build). 

### What component(s) does this issue relate to?

Compiler

### User Story

When attempting to run [SHARK Runtime Windows Build](https://github.com/nod-ai/SHARK-Runtime/wiki/SHARK-Runtime-Windows-Build) the error below occurs, which lead me to looking at adding the necessary  IREE Target-Triple.

```
Optimized kernel for your target device is not added yet.
            Contact SHARK Admin on discord[https://discord.com/invite/RUqY2h2s9u]
            or pull up an issue.
Target : deviceName        = Radeon RX 580 Series
```

**Comment by averad** [comment]
Opened upstream Enhancement Request [#11417](https://github.com/iree-org/iree/issues/11417)

**Comment by antiagainst** [comment]
Hi thanks for the feature request! Just wanted to say that those `--iree-vulkan-target-triple` is mainly meant to ease daily development---it takes quite a lot of information to specify the full Vulkan implementation (as you have dumped using vulkaninfo! we don't need all the details there as lots are for graphics, but still); we don't always want to specify those in full every time on command line. 

The proper way to support any kind of implementation is via the `--iree-vulkan-target-env` which accepts a `#vk.target_env` attribute to describe the characteristics of the target that are needed in IREE. Even longer term we expect IREE to grow capabilities to bucket implementations into different feature categories and ship flat binaries to support and dynamic select in runtime. 

With the above said, if you'd like to improve support for AMD GCN architectures, by all means feel free to send a pull request to add such a triple to make your life easier.

**Comment by antiagainst** [comment]
Closing as obsolete -- no plans of action on this right now
