### ISSUE TITLE
Implement flow/hal/vm.global store-load forwarding/store-store elimination

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#1145]
With variables/globals we can end up with some local silliness where some globals are stored and loaded back-to-back (instead of reusing the SSA value) or some globals are stored redundantly. Some of this may get better with more accurate side effect modeling (#1124), but I suspect we will need to have a few of our own canonicalizations.

Combined with better variable/global DCE this may turn many globals into locals as the inliner runs (for example, descriptor set layouts may go away in a lot of cases).

**Comment by benvanik** [comment]
Here's an example where we store and load:
https://gist.github.com/benvanik/cc49403752e2002b872b7d3a17df3cc0#file-5-vm-mlir-L151-L152

**Comment by benvanik** [comment]
Sadness, despair:

```mlir
hal.variable @_device_match_id_0 init(@_device_match_id_0_initializer) : i1 attributes {sym_visibility = "private"}
...
^bb3:	// 2 preds: ^bb1, ^bb2
    %6 = hal.variable.load @_device_match_id_0 : i1
    cond_br %6, ^bb4, ^bb5
  ^bb4:	// pred: ^bb3
    hal.command_buffer.dispatch %cmd, %4, entry_point = 0, workgroup_xyz = [%c16384, %c1, %c1]
    br ^bb6
  ^bb5:	// pred: ^bb3
    br ^bb6
  ^bb6:	// 2 preds: ^bb4, ^bb5
    %9 = hal.variable.load @_device_match_id_0 : i1
    cond_br %9, ^bb7, ^bb8
...
```

That immutable variable should have its loads CSEd. I suspect the current MemRead annotation on it is preventing that? Maybe we need more modeling in #1124, however it'd be nice if we could do this reliably when we know for a fact that nothing else can impact this op as it's effectively runtime constant.

**Comment by benvanik** [comment]
I've added a hack to flow/hal/vm load ops in #3498 that neuters their memory read side-effect when the source variable is immutable. This at least allows CSE/DCE to work for those, which are the common case in our current vision/BERT models. For any model actually using variables, though, we need the real thing.

**Comment by weimin** [comment]
Hi,
I am new to this repo and I found the good first issue tag for this. I sort of understand in the snippet above hal.variable.load @_device_match_id_0 : i1 in label ^bb6 is redundant in the second call since it was just loaded in label ^bb3 but what does current Memread annotation refer to. Thanks!

**Comment by benvanik** [comment]
`util.global` does a lot of this, though it could certainly be improved.
