### ISSUE TITLE
scf::tileConsumerAndFuseProducerGreedilyUsingSCFForOp does not work for unpack + generic case

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#11505]
We're able to use tiling interface for tile + fuse the ops, but not `scf::tileConsumerAndFuseProducerGreedilyUsingSCFForOp`.

There are no errors in the method, but it failed at the end of replacing ops.

```
mlir::detail::Interface<mlir::linalg::LinalgOp, m
lir::Operation *, mlir::linalg::detail::LinalgOpInterfaceTraits, mlir::Op<mlir::linalg::LinalgOp>, mlir::OpTrait::TraitBase>::Interface(ValueT) [ConcreteType = mlir::linalg::LinalgOp, ValueT = mlir::Operation *, Traits = mlir::linalg::detail::LinalgOpInterfaceTraits, BaseType = mlir::Op<mlir::linalg::LinalgOp>, BaseTrait = mlir::OpTrait::TraitBase]: Assertion `(!t || impl) && "expected value to provide interface instance"' failed.
```

To repro: `iree-opt --linalg-fuse="tile-sizes=16,16" ~/repro.mlir`

repro.mlir: https://gist.githubusercontent.com/hanhanW/9ba91d8fec99a15760ea32274fb951e4/raw

**Comment by hanhanW** [comment]
@MaheshRavishankar this is the issue that we've talked about.

**Comment by MaheshRavishankar** [comment]
I am guessing you mean there is still an issue?

**Comment by hanhanW** [comment]
I have to verify it.. My intention was "this is addressed by Mahesh". :p

**Comment by hanhanW** [comment]
verified that it's fixed.
