### ISSUE TITLE
Unable to run IREE on CUDA for some tensors

### ISSUE THREAD

**Issue by dellis23** [iree-org/iree#11556]
### What happened?

I tried to create a very basic program to add a tensor to itself and run it on IREE with CUDA.

### Steps to reproduce your issue

I've created [this repo](https://github.com/dellis23/iree-reproduce-cuda-issue) to reproduce the failure.

The error:

```
RuntimeError: Error invoking function: main_checkout/runtime/src/iree/hal/drivers/cuda/stream_command_buffer.c:370: INTERNAL; CUDA driver error 'CUDA_ERROR_INVALID_VALUE' (1): invalid argument; cuLaunchKernel; while invoking native function hal.device.queue.execute; while calling import;
[ 1]   native hal.device.queue.execute:0 -
```

### What component(s) does this issue relate to?

Runtime

### Version information

The repro script was run on a GCP n1-standard-4 Intel Haswell x86/64 instance with an NVIDIA T4 GPU on Ubuntu 22.04.  I'm installing IREE version `20221201.344`.

**Comment by dellis23** [comment]
Alright, I think I've gotten a bit further on this.  The example fails unless I lower the size of the tensor I'm passing in.  A `(100000, 1)` tensor works, but a `(100000, 10)` tensor doesn't.  It looks like a `(1000000, 1)` tensor works, however.  A `(1000000000, 1)` tensor fails with `Killed` (i.e. a 1GB tensor, if my math is correct), despite this being a 16GB GPU.

**Comment by dellis23** [comment]
The IR in question (this one works, since the second dimension is 1 and the tensor is small enough):

```mlir
#map = affine_map<(d0, d1) -> (d0, 0)>
#map1 = affine_map<(d0, d1) -> (d0, d1)>
module attributes {torch.debug_module_name = "TestModel"} {
  func.func @forward(%arg0: tensor<500000000x1xf32>) -> tensor<500000000x1xf32> {
    %0 = tensor.empty() : tensor<500000000x1xf32>
    %1 = linalg.generic {indexing_maps = [#map, #map, #map1], iterator_types = ["parallel", "parallel"]} ins(%arg0, %arg0 : tensor<500000000x1xf32>, tensor<500000000x1xf32>) outs(%0 : tensor<500000000x1xf32>) {
    ^bb0(%in: f32, %in_0: f32, %out: f32):
      %2 = arith.addf %in, %in_0 : f32
      linalg.yield %2 : f32
    } -> tensor<500000000x1xf32>
    return %1 : tensor<500000000x1xf32>
  }
}
```

**Comment by dellis23** [comment]
Non-working IR for a large tensor (1GB):

```mlir
#map = affine_map<(d0, d1) -> (d0, 0)>
#map1 = affine_map<(d0, d1) -> (d0, d1)>
module attributes {torch.debug_module_name = "TestModel"} {
  func.func @forward(%arg0: tensor<1000000000x1xf32>) -> tensor<1000000000x1xf32> {
    %0 = tensor.empty() : tensor<1000000000x1xf32>
    %1 = linalg.generic {indexing_maps = [#map, #map, #map1], iterator_types = ["parallel", "parallel"]} ins(%arg0, %arg0 : tensor<1000000000x1xf32>, tensor<1000000000x1xf32>) outs(%0 : tensor<1000000000x1xf32>) {
    ^bb0(%in: f32, %in_0: f32, %out: f32):
      %2 = arith.addf %in, %in_0 : f32
      linalg.yield %2 : f32
    } -> tensor<1000000000x1xf32>
    return %1 : tensor<1000000000x1xf32>
  }
}
```

This dies with:

```
Killed
```

Non-working IR for a small tensor with dimensions (m, n) where n > 1:

```mlir
#map = affine_map<(d0, d1) -> (d0, d1)>
module attributes {torch.debug_module_name = "TestModel"} {
  func.func @forward(%arg0: tensor<100000x10xf32>) -> tensor<100000x10xf32> {
    %0 = tensor.empty() : tensor<100000x10xf32>
    %1 = linalg.generic {indexing_maps = [#map, #map, #map], iterator_types = ["parallel", "parallel"]} ins(%arg0, %arg0 : tensor<100000x10xf32>, tensor<100000x10xf32>) outs(%0 : tensor<100000x10xf32>) {
    ^bb0(%in: f32, %in_0: f32, %out: f32):
      %2 = arith.addf %in, %in_0 : f32
      linalg.yield %2 : f32
    } -> tensor<100000x10xf32>
    return %1 : tensor<100000x10xf32>
  }
}
```


This dies with:

```shell
RuntimeError: Error invoking function: main_checkout/runtime/src/iree/hal/drivers/cuda/stream_command_buffer.c:370: INTERNAL; CUDA driver error 'CUDA_ERROR_INVALID_VALUE' (1): invalid argument; cuLaunchKernel; while invoking native function hal.device.queue.execute; while calling import;
[ 1]   native hal.device.queue.execute:0 -
```

Note that for the second example, if I lower `n` by enough, it _does_ end up working, so I'm not sure what the exact line is between working and not working (though it doesn't seem to be strictly overall tensor size, and the failure case is different).

**Comment by ThomasRaoux** [comment]
Those problems are fixed with https://github.com/iree-org/iree/pull/11295. 
Some more complex version of the same limitation may happen and for that we need to explicitly dispatch along X for large dimensions. Closing this for now as all the problems discussed are fixed.
