### ISSUE TITLE
VMVX compilation fails since iree candidate-20221214.358

### ISSUE THREAD

**Issue by lundong** [iree-org/iree#11558]
### What happened?

Since iree release candidate-20221214.358, iree-compile fails to compile the imported TOSA MLIR into vmfb for the VMVX backend. It worked okay for candidate-20221213.357.

A failed tflite example is the person detection model: https://storage.googleapis.com/iree-model-artifacts/person_detect.tflite

### Steps to reproduce your issue

1. Build IREE
2. Import TFLite model (use person.detect.tflite as an example)
path/to/iree-import-tflite path/to/person_detect.tflite -o=/tmp/person_detect.mlir
3. Use iree-compile to compile TOSA MLIR
path/to/iree-compile -iree-input-type=tosa -iree-hal-target-backends=vmvx /tmp/person_detect.mlir -o /tmp/person_detect.vmfb
error: failed to legalize operation 'arith.fptosi' that was explicitly marked illegal ...

### What component(s) does this issue relate to?

Compiler

### Version information

iree candidate-20221214.358

**Comment by lundong** [comment]
@jpienaar @hcindyl

**Comment by jpienaar** [comment]
PR to fix under review in https://github.com/iree-org/iree/pull/11553 - there are still issues here so I wouldn't use VMVX for anything below 32-bit yet.

**Comment by jpienaar** [comment]
Should be fixed and working in next nightly. Keeping it open until next nightly.

**Comment by lundong** [comment]
Confirmed it has been fixed. Thanks!
