### ISSUE TITLE
Would like "iree-compile -compile-mode=hal-executable" to compose with "iree-run-module"

### ISSUE THREAD

**Issue by nicolasvasilache** [iree-org/iree#11653]
### Request description

Using this IR: https://gist.github.com/nicolasvasilache/c4df13c22c2885dcc8ba9f48d582cf93

```
iree-compile -compile-mode=hal-executable ir.mlir
```
produces IR as I think I expect it.

Unfortunately, passing it through iree-run-module trying to execute it fails:
```
iree-compile -compile-mode=hal-executable /tmp/iree_transform_dialect_7a1eaa.mlir | iree-run-module --entry_function=reduction_2d_static --device=cuda --function_input="1234560x15xf32=1"

Reading module contents from stdin...
iree/runtime/src/iree/vm/bytecode_module.c:255: INVALID_ARGUMENT; FlatBuffer verification failed: identifier mismatch
```

Looking at the IR produced by iree-compile in this case vs other cases that run e2e suggests the stream part is ignored.
I conjecture this is intended behavior and not a bug.

I'd really like to run this end-to-end, if possible or understand what a workaround may be

**Comment by stellaraccident** [comment]
That is producing a raw device side cuda kernel. The rest of the pipeline is generating the host side code to mate with it. Having both is necessary to run but I think you are asking for something more stripped down than the default pipeline... Can you describe what that is?

**Comment by nicolasvasilache** [comment]
> That is producing a raw device side cuda kernel. The rest of the pipeline is generating the host side code to mate with it. Having both is necessary to run but I think you are asking for something more stripped down than the default pipeline... Can you describe what that is?

I am not sure I understand the question .. is there additional IR that is missing to generate the host here?
The TL;DR is I am trying to get #11654 to run e2e.

Running the first monstruous list of incantations gets me to the cuda kernel but I'd love to get the whole thing to run.

**Comment by benvanik** [comment]
Yes - the hal-executable mode is exclusively for producing HAL executables and does not produce any host code. In general the compiler allows for most of the input stages to be passed in normal flows. See the custom_dispatch samples that pass in flow-level host logic but hal.executable dispatch sources: https://github.com/iree-org/iree/blob/05f29e2cae7a6f06ab15ed94b195e5f4ff4277cf/samples/custom_dispatch/cuda/kernels/example.mlir

**Comment by nicolasvasilache** [comment]
@benvanik thanks for the link!

I have to drop until Tuesday, if you see a way to make #11654 run e2e all the way to iree-run-module, I'd love some more pointers.

Will pick it up when I come back!

**Comment by benvanik** [comment]
I have no clue what that PR is doing, but it looks shady (you cannot make assumptions about executables based on walking dispatch ops - nothing transform dialect related should ever touch the stream dialect host code like that) - you're going to need to need to explain when you get back :)

**Comment by nicolasvasilache** [comment]
Don't need this anymore.
