### ISSUE TITLE
Build IREE for an arm platform 

### ISSUE THREAD

**Issue by Theoo1997** [iree-org/iree#11704]
Hi,

I am trying to build IREE compiler into and aarch64 platform. When I compile it I faced the above error. Any ideas?

![Screenshot from 2023-01-04 13-14-59](https://user-images.githubusercontent.com/109102287/210543573-85f61eb1-3715-423a-8834-90ff18b67648.png)

**Comment by stellaraccident** [comment]
It looks like your sdcard is formatted in a way that doesn't support symlinks. Most likely fat i would guess. Under Linux, we assume that symlinks can be created.

You'll know if this is the issue if the following command from an sdcard directory fails:

`ln -s foobar .`

**Comment by stellaraccident** [comment]
(you will need to build on a native Linux filesystem like ext4)

**Comment by Theoo1997** [comment]
> It looks like your sdcard is formatted in a way that doesn't support symlinks. Most likely fat i would guess. Under Linux, we assume that symlinks can be created.
> 
> You'll know if this is the issue if the following command from an sdcard directory fails:
> 
> `ln -s foobar .`

Thanks for your answer. That is correct, the issue is the one you mentioned. But how I will solve this if I don't have enough space on a native Linux file system (only 32 gb)?

**Comment by stellaraccident** [comment]
A few other hints (but I don't know what you are trying to do so may not apply):

* Smaller platforms often just need the runtime and not the compiler (which is the most expensive part of the build). Disable it with -DIREE_BUILD_COMPILER=OFF
* Debug information bloats the build size. Building with -DCMAKE_BUILD_TYPE=Release should help.
* Enabling these two options in Linux can save a lot of disk space in the build directory for debug builds: https://github.com/iree-org/iree/blob/663b1a7b541e7d511675c45667cf39304e6b9eec/CMakeLists.txt#L269

**Comment by Theoo1997** [comment]
> A few other hints (but I don't know what you are trying to do so may not apply):
> 
> * Smaller platforms often just need the runtime and not the compiler (which is the most expensive part of the build). Disable it with -DIREE_BUILD_COMPILER=OFF
> * Debug information bloats the build size. Building with -DCMAKE_BUILD_TYPE=Release should help.
> * Enabling these two options in Linux can save a lot of disk space in the build directory for some builds: https://github.com/iree-org/iree/blob/663b1a7b541e7d511675c45667cf39304e6b9eec/CMakeLists.txt#L269

Yes that is a very good advice thanks !!
