### ISSUE TITLE
Build for host failed on macOS

### ISSUE THREAD

**Issue by wangkuiyi** [iree-org/iree#11722]
### What happened?

The command `cmake --build` failed on macOS.

```
/Users/y/w/iree/compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategiesGPU.cpp:93:18: error: conditional expression is ambiguous; 'pair<typename __unwrap_ref_decay<long>::type, [...]>' can be converted to 'pair<typename __unwrap_ref_decay<long long &>::type, [...]>' and vice versa
                 ? std::make_pair(0l, vectorSize)
                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Steps to reproduce your issue

I did the following steps.
1. Deleted my old local clone
2. Cloned IREE
   ```
   git clone --recursive https://github.com/iree-org/iree
   ```
4. Get into the local clone directory and configure the build
   ```
   cmake -S . -B build-release/ -GNinja \
     -DCMAKE_BUILD_TYPE=RelWithDebInfo \
     -DCMAKE_INSTALL_PREFIX=build-release/install
   ```
5. Build
   ```
   cmake --build build-release/ --target install
   ```

### What component(s) does this issue relate to?

Compiler

### Version information

33ace455f664e93654cd60646d106a35a195a54c

### Additional context

- Chip: Apple M1 max
- macOS: Ventura 13.1
- Xcode: Version 14.2 (14C18)
- Clang: Apple clang version 14.0.0 (clang-1400.0.29.202)
- SDK: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk

**Comment by antiagainst** [comment]
Thanks! Looks this is a new issue just introduced. I've created #11724 to fix it.
