### ISSUE TITLE
data tiling path crashes in mobile_ssd models on cascadelake target

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#11726]
To repro:

Download and import the model: https://storage.googleapis.com/iree-model-artifacts/mobile_ssd_v2_float_coco.tflite

Compile the model: `iree-compile --output-format=vm-bytecode --iree-hal-target-backends=llvm-cpu ~/mobile_ssd_v2_float_coco.mlir -o /tmp/a.vmfb --iree-input-type=tosa --iree-flow-enable-data-tiling --iree-llvm-target-cpu=cascadelake --iree-llvm-target-triple=x86_64-unknown-linux-gnu`

Run the model: `iree-benchmark-module --module_file=/tmp/a.vmfb --device=local-task --entry_function=main --function_input=1x320x320x3xf32`

**Comment by hanhanW** [comment]
I can not narrow the input down.... It won't crash if I add `--iree-flow-trace-dispatch-tensors` flag.

Also, it can only be reproduced with having `--iree-llvm-target-cpu=cascadelake --iree-llvm-target-triple=x86_64-unknown-linux-gnu` compilation flags.

**Comment by stellaraccident** [comment]
Probably need to dust off the asan support for generated code... (And would be good to document)

**Comment by hanhanW** [comment]
> Probably need to dust off the asan support for generated code... (And would be good to document)

Yes! I just finished the ASAN build (and can document how I do it somewhere).

**Comment by hanhanW** [comment]
I can compile simple input (like matmul) with ASAN, but not the mobile ssd model. I'm using the system linker; I get many  `relocation R_X86_64_PC32 cannot be used against symbol '__asan_option_detect_stack_use_after_return'; recompile with -fPIC` errors.

**Comment by hanhanW** [comment]
can't reproduce the issue on ToT, closing the issue
