### ISSUE TITLE
CMake build for iOS generates incomplete Info.plist files

### ISSUE THREAD

**Issue by wangkuiyi** [iree-org/iree#11733]
### What happened?

As detailed in the section "Step 1. Manually complete the Info.plist file" in this discussion post https://github.com/iree-org/iree/discussions/11732, the `xcrun simctl install` command cannot install the built iOS apps to iOS simulators. It complains that the `Info.plist` is lacking some fields.

After manually added a few fields, the `xcrun simctl install` command succeeded and I can run the installed app.

### Steps to reproduce your issue

There are pretty many steps to approach this problem, so I documented them in https://github.com/iree-org/iree/discussions/11732.

### What component(s) does this issue relate to?

Runtime

### Version information

23c8a44b0f76568d9932366a1e24024b87ee3557

**Comment by stellaraccident** [comment]
Great work all. Thanks for the detailed notes. I don't know much about that level of Mac development so hoping someone knows the answer.
