### ISSUE TITLE
Error when lowering tosa.logical_right_shift with i16 types in VMVX backend

### ISSUE THREAD

**Issue by c-rhodes** [iree-org/iree#11792]
### What happened?

Hi,

I'm hitting an error when compiling one of our pipelines with the VMVX backend:
```
tests/e2e/tosa_ops/logical_right_shift.mlir:4:13: note: see current operation: %22 = "vm.shr.i32.u"(%18, %21) : (i32, i32) -> i16
tests/e2e/tosa_ops/logical_right_shift.mlir:4:13: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vmvx", "vmvx-bytecode-fb", {ukernels = true}>
  %result = "tosa.logical_right_shift"(%0, %1) : (tensor<4xi16>, tensor<4xi16>) -> tensor<4xi16>
            ^
```

I created a small reproducer from `tests/e2e/tosa_ops/logical_right_shift.mlir` by changing the types to i16.

**INPUT MLIR**
```
func.func @tensor() {
  %0 = util.unfoldable_constant dense<[5, 8, 9, 256]> : tensor<4xi16>
  %1 = util.unfoldable_constant dense<[0, 1, 2, 8]> : tensor<4xi16>
  %result = "tosa.logical_right_shift"(%0, %1) : (tensor<4xi16>, tensor<4xi16>) -> tensor<4xi16>
  check.expect_eq_const(%result, dense<[5, 4, 2, 1]> : tensor<4xi16>) : tensor<4xi16>
  return
}
```

**TO REPRODUCE**

```
iree-compile --iree-hal-target-backends=vmvx --iree-input-type=tosa logical_right_shift_i16.mlir -o foo.vmfb
```

I see the op gets lowered to `arith.shrui` which then gets lowered to `vm.shr`, but the result type is taken from the src (i16) when it should be i32? I.e.
```
diff --git a/compiler/src/iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp b/compiler/src/iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp
index 0ebe8a838..3d09874d2 100644
--- a/compiler/src/iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp
+++ b/compiler/src/iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp
@@ -741,7 +741,7 @@ class ShiftArithmeticOpConversion : public OpConversionPattern<SrcOpTy> {
     }
     switch (adaptor.getLhs().getType().getIntOrFloatBitWidth()) {
       case 32:
-        rewriter.replaceOpWithNewOp<Dst32OpTy>(srcOp, srcOp.getType(),
+        rewriter.replaceOpWithNewOp<Dst32OpTy>(srcOp, rewriter.getI32Type(),
                                                adaptor.getLhs(), amount);
         break;
       case 64:
```

### What component(s) does this issue relate to?

Compiler

### Version information

d782f54f5

**Comment by bjacob** [comment]
`-mlir-print-ir-after-all` log: https://gist.github.com/bjacob/41ac384b7274a13d8cab4cfc0d06c194

**Comment by bjacob** [comment]
in GDB:

```
(gdb) frame
#0  mlir::iree_compiler::(anonymous namespace)::ShiftArithmeticOpConversion<mlir::arith::ShRUIOp, mlir::iree_compiler::IREE::VM::ShrI32UOp, mlir::iree_compiler::IREE::VM::ShrI64UOp>::matchAndRewrite (this=0x555557e65ca0, srcOp=..., adaptor=..., rewriter=...)
    at /usr/local/google/home/benoitjacob/iree/compiler/src/iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp:744
744             rewriter.replaceOpWithNewOp<Dst32OpTy>(srcOp, srcOp.getType(),
(gdb) l
739           amount = rewriter.createOrFold<arith::TruncIOp>(
740               srcOp.getLoc(), rewriter.getI32Type(), amount);
741         }
742         switch (adaptor.getLhs().getType().getIntOrFloatBitWidth()) {
743           case 32:
744             rewriter.replaceOpWithNewOp<Dst32OpTy>(srcOp, srcOp.getType(),
745                                                    adaptor.getLhs(), amount);
746             break;
747           case 64:
748             rewriter.replaceOpWithNewOp<Dst64OpTy>(srcOp, srcOp.getType(),
(gdb) call srcOp.dump()
%39 = "arith.shrui"(%34, %38) : (i16, i16) -> i16
```

**Comment by bjacob** [comment]
Thanks a lot for the report and the fix, which I believe is correct. I have applied the same fix to also the 64bit case and checked that no other place in this file seems to have the same issue. PR:
https://github.com/iree-org/iree/pull/11826

I wanted to add you as co-author but need an email address?

**Comment by c-rhodes** [comment]
@bjacob Thanks for taking a look, the email is cullen.rhodes@arm.com, cheers!

**Comment by bjacob** [comment]
Thanks! Now we get the error that there's a missing CLA for you. https://github.com/iree-org/iree/pull/11826/checks?check_run_id=10634152685 . It says you can follow the steps [here](https://cla.developers.google.com/github/rescan?pr=iree-org%2Firee%2Fpull%2F11826&key=%01%AB%94%01h%D8%19e%E9%D3%97%B0%1F%BB%9E%B5%AA%09%25E%DA&expiry=2023-02-27)

**Comment by banach-space** [comment]
That's something that we should be able to fix internally at Arm - I've reached out to relevant folks :)

Thank you both for resolving this so quickly!

**Comment by banach-space** [comment]
> Thanks! Now we get the error that there's a missing CLA for you. https://github.com/iree-org/iree/pull/11826/checks?check_run_id=10634152685 . It says you can follow the steps [here](https://cla.developers.google.com/github/rescan?pr=iree-org%2Firee%2Fpull%2F11826&key=%01%AB%94%01h%D8%19e%E9%D3%97%B0%1F%BB%9E%B5%AA%09%25E%DA&expiry=2023-02-27)

This should be sorted now. Does anything require re-triggering?

**Comment by bjacob** [comment]
possibly - we had a CI outage yesterday.  Thanks for getting the CLA, I will take care of the rest.

**Comment by bjacob** [comment]
retriggered but CI is still down.
