### ISSUE TITLE
Out of memory compile-time error with llvm-cpu and aggressive fusion 

### ISSUE THREAD

**Issue by aldesilv** [iree-org/iree#11798]
### What happened?

iree-compile runs out of memory

### Steps to reproduce your issue

[softmax.txt](https://github.com/iree-org/iree/files/10396156/softmax.txt)

1. tools/iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-flow-enable-aggressive-fusion --iree-llvmcpu-fail-on-out-of-bounds-stack-allocation=false softmax.txt -o test.vmfb

### What component(s) does this issue relate to?

Compiler

### Version information

iree main
533c2464dc0cc5429a57b3c22a69826007f91a08

**Comment by MaheshRavishankar** [comment]
Trying this on https://github.com/iree-org/iree/commit/56a873934c70a440e26f39ae14eb82ba0ed54897 doesnt seem to hit the issue. Can you please verify.

**Comment by aldesilv** [comment]
yeah, I don't run into the issue anymore.
