### ISSUE TITLE
TileAndDistributeToWorkgroups change introducing stack allocations and causing crashes/compile failures/etc

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#11830]
This integrate caused a regression in bufferization that leads to large stack allocations when none should be required:
https://github.com/iree-org/iree/commit/cc0c10cc67fe8b65aecdc0be7bdda61c79e4e219

This causes either compilation failures on certain targets (Windows) or crashes at runtime (Windows, OS X). It's also slow.

Testing before/after the integrate with `tests/e2e/models/resnet50_fake_weights.mlir` for x64 CPU on Windows I get this diff showing the additional allocations:
![image](https://user-images.githubusercontent.com/75337/212376572-46063f5e-5c6d-4e77-8215-1298a45206d0.png)

This seems to be the root cause (the first diff in the compilation):
![image](https://user-images.githubusercontent.com/75337/212379861-fd6cbad0-772c-4efd-b184-57d0920fdb8c.png)

Executable before TileAndDistributeToWorkgroups pass:
```mlir
#executable_target_embedded_elf_x86_64_ = #hal.executable.target<"llvm-cpu", "embedded-elf-x86_64", {cpu = "znver2", cpu_features = "-avx512pf,-tsxldtrk,+cx16,+sahf,-tbm,-avx512ifma,+sha,+crc32,-fma4,-vpclmulqdq,+prfchw,+bmi2,-cldemote,+fsgsbase,-avx512bf16,-amx-tile,-raoint,-uintr,-gfni,+popcnt,-ptwrite,+aes,-avx512bitalg,-movdiri,-widekl,+xsaves,-avx512er,-avxvnni,-avx512fp16,-avx512vnni,-amx-bf16,-avxvnniint8,-avx512vpopcntdq,-pconfig,+clwb,-cmpccxadd,-avx512f,+xsavec,+clzero,-pku,-amx-fp16,+mmx,-lwp,+rdpid,-xop,+rdseed,-waitpkg,-prefetchi,-kl,-movdir64b,+sse4a,-avx512bw,-avxneconvert,+clflushopt,+xsave,-avx512vbmi2,+64bit,-avx512vl,-serialize,-hreset,-invpcid,-avx512cd,+avx,-vaes,-amx-int8,+cx8,+fma,-rtm,+bmi,-enqcmd,+rdrnd,-mwaitx,+sse4.1,+sse4.2,+avx2,+fxsr,-wbnoinvd,+sse,+lzcnt,+pclmul,-rdpru,-avxifma,+f16c,+ssse3,-sgx,-prefetchwt1,+cmov,-avx512vbmi,-shstk,+movbe,-avx512vp2intersect,+xsaveopt,-avx512dq,+sse2,+adx,+sse3", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 32 : index, target_triple = "x86_64-unknown-unknown-eabi-elf"}>
#map = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#map1 = affine_map<(d0, d1, d2, d3) -> (d3)>
#map2 = affine_map<(d0, d1, d2, d3, d4) -> (d0 * 2 + d3, d1 * 2 + d4, d2)>
#map3 = affine_map<(d0, d1, d2, d3, d4) -> (d3, d4)>
#map4 = affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2)>
#map5 = affine_map<(d0, d1) -> (d0, d1)>
#map6 = affine_map<(d0, d1) -> (d1)>
#map7 = affine_map<(d0, d1) -> (d1, d0)>
#map8 = affine_map<(d0, d1) -> (d0)>
#map9 = affine_map<(d0) -> (d0)>
#map10 = affine_map<(d0) -> ()>
#map11 = affine_map<(d0, d1) -> ()>
#pipeline_layout = #hal.pipeline.layout<push_constants = 0, sets = [<0, bindings = [<0, storage_buffer, ReadOnly>, <1, storage_buffer>]>]>
#device_target_llvm_cpu = #hal.device.target<"llvm-cpu", {executable_targets = [#executable_target_embedded_elf_x86_64_]}>
module attributes {hal.device.targets = [#device_target_llvm_cpu]} {
  hal.executable private @predict_dispatch_3 {
    hal.executable.variant public @embedded_elf_x86_64, target = #executable_target_embedded_elf_x86_64_ {
      hal.executable.export public @predict_dispatch_3_generic_56x56x64x3x3 ordinal(0) layout(#pipeline_layout) {
      ^bb0(%arg0: !hal.device, %arg1: index, %arg2: index, %arg3: index, %arg4: index, %arg5: index):
        %x, %y, %z = flow.dispatch.workgroup_count_from_dag_root %arg1, %arg2, %arg3, %arg4, %arg5
        hal.return %x, %y, %z : index, index, index
      }
      builtin.module {
        func.func @predict_dispatch_3_generic_56x56x64x3x3() {
          %c3846080 = arith.constant 3846080 : index
          %c0 = arith.constant 0 : index
          %cst = arith.constant dense<0xFF800000> : tensor<56x56x64xf32>
          %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%c3846080) alignment(64) : !flow.dispatch.tensor<readonly:tensor<114x114x64xf32>>
          %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<writeonly:tensor<56x56x64xf32>>
          %2 = flow.dispatch.tensor.load %0, offsets = [0, 0, 0], sizes = [114, 114, 64], strides = [1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<114x114x64xf32>> -> tensor<114x114x64xf32>
          %3 = tensor.empty() : tensor<3x3xf32>
          %4 = linalg.generic {indexing_maps = [#map2, #map3, #map4], iterator_types = ["parallel", "parallel", "parallel", "reduction", "reduction"]} ins(%2, %3 : tensor<114x114x64xf32>, tensor<3x3xf32>) outs(%cst : tensor<56x56x64xf32>) {
          ^bb0(%in: f32, %in_0: f32, %out: f32):
            %5 = arith.maxf %out, %in : f32
            linalg.yield %5 : f32
          } -> tensor<56x56x64xf32>
          flow.dispatch.tensor.store %4, %1, offsets = [0, 0, 0], sizes = [56, 56, 64], strides = [1, 1, 1] : tensor<56x56x64xf32> -> !flow.dispatch.tensor<writeonly:tensor<56x56x64xf32>>
          return
        }
      }
    }
  }
}
```

And from flow:
```mlir
#map = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#map1 = affine_map<(d0, d1, d2, d3) -> (d3)>
#map2 = affine_map<(d0, d1, d2, d3, d4) -> (d0 * 2 + d3, d1 * 2 + d4, d2)>
#map3 = affine_map<(d0, d1, d2, d3, d4) -> (d3, d4)>
#map4 = affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2)>
#map5 = affine_map<(d0, d1) -> (d0, d1)>
#map6 = affine_map<(d0, d1) -> (d1)>
#map7 = affine_map<(d0, d1) -> (d1, d0)>
#map8 = affine_map<(d0, d1) -> (d0)>
#map9 = affine_map<(d0) -> (d0)>
#map10 = affine_map<(d0) -> ()>
#map11 = affine_map<(d0, d1) -> ()>
  flow.executable private @predict_dispatch_3 {
    flow.executable.export public @predict_dispatch_3_generic_56x56x64x3x3 workgroups(%arg0: index, %arg1: index, %arg2: index, %arg3: index, %arg4: index) -> (index, index, index) {
      %x, %y, %z = flow.dispatch.workgroup_count_from_dag_root %arg0, %arg1, %arg2, %arg3, %arg4
      flow.return %x, %y, %z : index, index, index
    }
    builtin.module {
      func.func @predict_dispatch_3_generic_56x56x64x3x3(%arg0: !flow.dispatch.tensor<readonly:tensor<114x114x64xf32>>, %arg1: !flow.dispatch.tensor<writeonly:tensor<56x56x64xf32>>) {
        %cst = arith.constant dense<0xFF800000> : tensor<56x56x64xf32>
        %0 = flow.dispatch.tensor.load %arg0, offsets = [0, 0, 0], sizes = [114, 114, 64], strides = [1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<114x114x64xf32>> -> tensor<114x114x64xf32>
        %1 = tensor.empty() : tensor<3x3xf32>
        %2 = linalg.generic {indexing_maps = [#map2, #map3, #map4], iterator_types = ["parallel", "parallel", "parallel", "reduction", "reduction"]} ins(%0, %1 : tensor<114x114x64xf32>, tensor<3x3xf32>) outs(%cst : tensor<56x56x64xf32>) {
        ^bb0(%in: f32, %in_0: f32, %out: f32):
          %3 = arith.maxf %out, %in : f32
          linalg.yield %3 : f32
        } -> tensor<56x56x64xf32>
        flow.dispatch.tensor.store %2, %arg1, offsets = [0, 0, 0], sizes = [56, 56, 64], strides = [1, 1, 1] : tensor<56x56x64xf32> -> !flow.dispatch.tensor<writeonly:tensor<56x56x64xf32>>
        return
      }
    }
  }
```

`predict_dispatch_1_conv_2d_nhwc_hwcf_1x112x112x64x7x7x3` (and many others) also exhibit similar changes, but dispatch_3 there is simpler.

**Comment by MaheshRavishankar** [comment]
Thanks Ben, Ill take a look.

**Comment by MaheshRavishankar** [comment]
Found the root cause. This op is a pooling op that has been generalized to a `linalg.generic`. This is going to cause all sort of badness (we wont vectorize this correctly cause we dont know that is a pooling op, etc.). So looks like something changed in MHLO for this. @jpienaar or @rsuderman any ideas? (cant see anything obvious from the commit list)

```
#map2 = affine_map<(d0, d1, d2, d3, d4) -> (d0 * 2 + d3, d1 * 2 + d4, d2)>
#map3 = affine_map<(d0, d1, d2, d3, d4) -> (d3, d4)>
#map4 = affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2)>
        %2 = linalg.generic {indexing_maps = [#map2, #map3, #map4], iterator_types = ["parallel", "parallel", "parallel", "reduction", "reduction"]} ins(%0, %1 : tensor<114x114x64xf32>, tensor<3x3xf32>) outs(%cst : tensor<56x56x64xf32>) {
        ^bb0(%in: f32, %in_0: f32, %out: f32):
          %3 = arith.maxf %out, %in : f32
          linalg.yield %3 : f32
        } -> tensor<56x56x64xf32>
```

Ill try to have a WAR for this that doesnt fail compilation (so good to have anyway), but that only helps compilation. This would cause regressions.

**Comment by MaheshRavishankar** [comment]
cc @dcaballe and @vmurali

**Comment by vmurali** [comment]
> Found the root cause. This op is a pooling op that has been generalized to a `linalg.generic`. This is going to cause all sort of badness (we wont vectorize this correctly cause we dont know that is a pooling op, etc.). So looks like something changed in MHLO for this. @jpienaar or @rsuderman any ideas? (cant see anything obvious from the commit list)
> 
> ```
> #map2 = affine_map<(d0, d1, d2, d3, d4) -> (d0 * 2 + d3, d1 * 2 + d4, d2)>
> #map3 = affine_map<(d0, d1, d2, d3, d4) -> (d3, d4)>
> #map4 = affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2)>
>         %2 = linalg.generic {indexing_maps = [#map2, #map3, #map4], iterator_types = ["parallel", "parallel", "parallel", "reduction", "reduction"]} ins(%0, %1 : tensor<114x114x64xf32>, tensor<3x3xf32>) outs(%cst : tensor<56x56x64xf32>) {
>         ^bb0(%in: f32, %in_0: f32, %out: f32):
>           %3 = arith.maxf %out, %in : f32
>           linalg.yield %3 : f32
>         } -> tensor<56x56x64xf32>
> ```
> 
> Ill try to have a WAR for this that doesnt fail compilation (so good to have anyway), but that only helps compilation. This would cause regressions.

Is it related to the pooling vectorization changes? Where exactly is this code snippet getting generated? The pooling transforms happen at linalg codegen strategy.

**Comment by MaheshRavishankar** [comment]
Nope it is not related to pooling vectorization itself.

I see this sort of IR from MHLO

```
#map2 = affine_map<(d0, d1, d2, d3, d4) -> (d0 * 2 + d3, d1 * 2 + d4, d2)>
#map3 = affine_map<(d0, d1, d2, d3, d4) -> (d3, d4)>
#map4 = affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2)>
func.func @test(%arg0 : tensor<114x114x64xf32>) -> tensor<56x56x64xf32> {
  %cst = arith.constant dense<0xFF800000> : tensor<56x56x64xf32>
  %1 = tensor.empty() : tensor<3x3xf32>
  %2 = linalg.generic {indexing_maps = [#map2, #map3, #map4], iterator_types = ["parallel", "parallel", "parallel", "reduction", "reduction"]} ins(%arg0, %1 : tensor<114x114x64xf32>, tensor<3x3xf32>) outs(%cst : tensor<56x56x64xf32>) {
  ^bb0(%in: f32, %in_0: f32, %out: f32):
    %3 = arith.maxf %out, %in : f32
    linalg.yield %3 : f32
  } -> tensor<56x56x64xf32>
  return %2 : tensor<56x56x64xf32>
}
```

This is not a generic op the front-end should be creating (see the indexing map `#map2`). This looks like a max-pooling op that is lowered to a generic op instead of the linalg pooling ops.

**Comment by jpienaar** [comment]
Is this directly from MHLO? (I don't see an obvious candidate either that side). Or is it an initial tensor op that got canonicalized?

**Comment by MaheshRavishankar** [comment]
I was thinking this is from MHLO... cause we have no place in IREE that should be doing this, but didnt check. Let me check resnet.

**Comment by jpienaar** [comment]
It seems likely due to changes to tensor dialect (at least it seems this was a tensor dialect op before linalg.generic but that was just via rough eyeballing) there seems to not be too many of those changes during integrate, some of which are (chosen based on tensor in name really): 

https://github.com/iree-org/iree-llvm-fork/commit/f6fb0a4f35d152d154aeb8a8e3d47ff1392c1bad

https://github.com/iree-org/iree-llvm-fork/commit/9cdf6b641da1a7ba0145b224460c64efd65017e0#diff-c4e46f5af529880be413de88bbb07439b3a93aa5f5fe4238373ca48f164aec12

e7d0cc76d7f03020429f4e15de79ddb6a3695aea

[83396d85495914e17746d0ea6daa56eb35de3b39](https://github.com/iree-org/iree-llvm-fork/commit/193cefd1b1f25eec3ea9e9ebd3faaa2e16caabc0)

I'm guessing no easy way to bisect here with this model unless we narrow down producer more first.

**Comment by MaheshRavishankar** [comment]
Its a pooling op. So it should always have been a linalg.pooling op. I tried lowering the resnet test and dumping the IR before Flow pipeline. I see this op 

```
  %21 = linalg.pooling_nhwc_max {dilations = dense<1> : vector<2xi64>, strides = dense<2> : vector<2xi64>} ins(%padded_17, %18 : tensor<1x114x114x64xf32>, tensor<3x3xf32>) outs(%20 : tensor<1x56x56x64xf32>) -> tensor<1x56x56x64xf32>
```

but I am on Linux. Can it be that on Windows it lowers differently? (@ScottTodd or @benvanik if you can check)
