### ISSUE TITLE
Build libIREERuntime

### ISSUE THREAD

**Issue by wangkuiyi** [iree-org/iree#11846]
### Request description

Neither the host compilation step, nor the Android/iOS cross-compilation step produces a runtime library. 

The [`CMakeLists.txt` file for the Runtime](https://github.com/iree-org/iree/blob/main/runtime/src/iree/CMakeLists.txt) doesn't seem to have much in it. The build of libIREECompiler is described in the [`CMakeList.txt` file of the Compiler](https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/API2/CMakeLists.txt).

Should we build the Runtime library as a static or a dynamic library so that iOS apps can link to it?

### What component(s) does this issue relate to?

Runtime

**Comment by benvanik** [comment]
You want to statically link the runtime.

**Comment by wangkuiyi** [comment]
Yes, I do.

Before I add the static library to my Xcode project, I use the following command line to build it.
```
libtool -static -o libIREERuntime.a $ALL_ARCHIVES
```
where `ALL_ARCHIVES` comes from
```
du -a ../iree-build-ios/runtime | grep '/lib.*a$' | cut -f 2 | grep -v testing | grep -v testdata
```

It would be easier if CMake's install target built it.

**Comment by stellaraccident** [comment]
I've recently been working on this: https://github.com/iree-org/iree-samples/tree/main/runtime-library

Let me know if that is relevant.

**Comment by GMNGeoffrey** [comment]
Is there further work required on this issue?

**Comment by stellaraccident** [comment]
I think it's as good as it is going to be for now. Could be better but that's future.
