### ISSUE TITLE
Link to IREE python documentation not returned in Google search query

### ISSUE THREAD

**Issue by silvasean** [iree-org/iree#11858]
### What happened?

When I do a web search on Google for `iree docs python bindings` I don't find this page: https://iree-org.github.io/iree/building-from-source/python-bindings-and-importers/

Bing does find it.

In general for some reason Google will never return a page from https://iree-org.github.io/iree/

### What component(s) does this issue relate to?

Other

**Comment by ScottTodd** [comment]
Weird... I'm pretty sure we were showing up higher in results for queries like that before. 

https://developers.google.com/search/docs/fundamentals/get-on-google
https://developers.google.com/search/help/crawling-index-faq

I see results for queries like `site:https://iree-org.github.io/ python`, so the website is indexed at least.

I see the sixth result for `iree python documentation` as https://iree-org.github.io/iree/getting-started/tensorflow/ and `iree building from source` has https://iree-org.github.io/iree/ as the top result.

https://stackoverflow.com/a/49073325 suggests we could create a Google Search Console account, and there might be other metadata / sitemaps we could generate (though I'm pretty sure mkdocs already does most of that for us).

**Comment by jpienaar** [comment]
From incognito mode (and slightly different query) I do see

![image](https://user-images.githubusercontent.com/706766/213575483-9541137e-f061-431f-8329-eff691057707.png)

But indeed its not top.

**Comment by ScottTodd** [comment]
Not sure we can do much here.
