### ISSUE TITLE
GPG key expired in runner image and block startup

### ISSUE THREAD

**Issue by pzread** [iree-org/iree#11852]
When creating an image, `build_tools/github_actions/runner/gcp/image_setup.sh` downloads the Google Cloud SDK gpg key and stores it in the image. This key never gets updated unless we push a new version of the runner image (our latest image was created in 2022/09).

This causes the problem if the gpg key expired and we run `apt-get update` later in the instances. The `apt-get update` will fail because the cloud sdk repo can't be verified by the expired gpg key.

In `build_tools/github_actions/runner/config/setup.sh`, `add-google-cloud-ops-agent-repo.sh` executes `apt-get update` and ran into this issue recently.

**Comment by GMNGeoffrey** [comment]
I was premature in closing this. This isn't fixed till it rolls out

**Comment by GMNGeoffrey** [comment]
New images have been fully pushed to prod
