### ISSUE TITLE
C++ syntax in string_view.h which might be included by .c files

### ISSUE THREAD

**Issue by wangkuiyi** [iree-org/iree#11865]
### What happened?

I failed to build the [IREE runtime library](https://github.com/iree-org/iree-samples/blob/main/runtime-library) because the C file https://github.com/iree-org/iree-samples/blob/main/runtime-library/test_api.c indirectly includes [`iree/base/string_view.h`](https://github.com/iree-org/iree/blob/main/runtime/src/iree/base/string_view.h), which use the C++ syntax of initializer list.

After changing [the line](https://github.com/iree-org/iree/blob/fca4102f97ba7e9795ff0dd1489653e2214867d6/runtime/src/iree/base/string_view.h#L67)

```
  iree_string_pair_t v = {iree_string_view_empty(), iree_string_view_empty()};
```
into
```
  iree_string_pair_t v;
  v.first = iree_string_view_empty(), v.second = iree_string_view_empty();
```

and [this line](https://github.com/iree-org/iree/blob/fca4102f97ba7e9795ff0dd1489653e2214867d6/runtime/src/iree/base/string_view.h#L74) as well as [this one](https://github.com/iree-org/iree/blob/fca4102f97ba7e9795ff0dd1489653e2214867d6/runtime/src/iree/base/string_view.h#L82-L85), the build succeeded.

### Steps to reproduce your issue

Please follow the steps in https://github.com/iree-org/iree-samples/issues/93

### What component(s) does this issue relate to?

Runtime

### Version information

d91712bf4d32c44f6075620293e638418a47d78f

### Additional context

Xcode Version 14.2 (14C18)
macOS 13.1 (22C65)

**Comment by benvanik** [comment]
Hmm C definitely has struct initializers, and we compile most of this code with C, so are you sure that's the issue?
We extensively use initializers in the code and this is likely a compiler version or configuration issue - have you made sure you're compiling in a modern C? (we generally require C11)

**Comment by wangkuiyi** [comment]
You are right. Using initializer list should not be the reason.

My setup works well building IREE compiler + runtime samples for macOS and iOS (simulator and devices).

Did we enable initializer list in the main repo but didn't in iree-sample/runtime-library?

**Comment by benvanik** [comment]
I'm not sure about the samples repo - but this line should be in the cmakelists:
`set(CMAKE_C_STANDARD 11)`

**Comment by wangkuiyi** [comment]
I was referring to this repo https://github.com/iree-org/iree-samples/tree/main/runtime-library

I added `set(CMAKE_C_STANDARD 11)` to [iree-samples/runtime-library/CMakeLists.txt](https://github.com/iree-org/iree-samples/tree/main/runtime-library/CMakeLists.txt) to make it looks similar to [that of the main repo](https://github.com/iree-org/iree/blob/main/CMakeLists.txt). And, I verified that the compilation flags recorded in `compile_commands.json` are the same.  However, `cmake --build build` still errors the use of struct initializer list.

```diff
12:37 $ git diff
diff --git a/runtime-library/CMakeLists.txt b/runtime-library/CMakeLists.txt
index 74fec9d..7ef209e 100644
--- a/runtime-library/CMakeLists.txt
+++ b/runtime-library/CMakeLists.txt
@@ -9,6 +9,10 @@ cmake_minimum_required(VERSION 3.21...3.24)
 project(IREE_RUNTIME_LIBRARY)
 cmake_policy(SET CMP0069 NEW)

+set(CMAKE_C_STANDARD 11)
+set(CMAKE_CXX_STANDARD 17)
+set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
+
 set(IREE_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../iree" CACHE STRING "Main IREE source")

 # Enable LTO if supported.
```

Then, I compared the compilations flags for my succeeded build of the main repo and the failed runtime-library for macOS (and then iOS).  The following opendiff command shows the flags are the same.

```
grep iree/runtime/src/iree/vm/module_impl_emitc.c ~/w/build-ios-sim/compile_commands.json  | grep '\"command\"' | tr ' ' '\n' > /tmp/iree
grep iree/runtime/src/iree/vm/module_impl_emitc.c build-ios-sim/compile_commands.json  | grep '\"command\"' | tr ' ' '\n' > /tmp/runtime
opendiff /tmp/iree /tmp/runtime
```

<img width="1605" alt="Screenshot 2023-01-17 at 12 49 25 PM" src="https://user-images.githubusercontent.com/1548775/213009308-30ad25fa-c9f3-4a21-a001-35acf87c7a6f.png">

I then disabled LTO from the runtime-library. Still `cmake --build` errors.

Very head scratching...

**Comment by wangkuiyi** [comment]
I got it -- we should have used nested initializer list for `iree_string_pair_t`.  Two clues:

1. The error message clearly told us to do so.
   ```
   /Users/y/w/iree-samples/runtime-library/build/include/iree/base/string_view.h:67:27: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
     iree_string_pair_t v = {iree_string_view_empty(), iree_string_view_empty()};
                             ^~~~~~~~~~~~~~~~~~~~~~~~
                             {                       }
   ```
1. There are three places in `string_view.h` that use initializer list when instantiating `iree_string_pair_t`. Two of them do not use nested initializer list and caused compilation errors, and the [last one](https://github.com/iree-org/iree/blob/343084fda533c48104aec0cf87e5ebacd1725122/runtime/src/iree/base/string_view.h#L82-L85) uses it and does not cause errors.
   ```
     iree_string_pair_t v = {
         {iree_make_cstring_view(first)},
         {iree_make_cstring_view(second)},
     };
   ```
The following change fixes the issue.

```diff
diff --git a/runtime/src/iree/base/string_view.h b/runtime/src/iree/base/string_view.h
index 6d26164d4..e8b74d867 100644
--- a/runtime/src/iree/base/string_view.h
+++ b/runtime/src/iree/base/string_view.h
@@ -64,14 +64,14 @@ typedef struct iree_string_pair_t {

 // Returns an empty string pair ("", "").
 static inline iree_string_pair_t iree_string_pair_empty(void) {
-  iree_string_pair_t v = {iree_string_view_empty(), iree_string_view_empty()};
+  iree_string_pair_t v = {{iree_string_view_empty()}, {iree_string_view_empty()}};
   return v;
 }

 // Returns a string pair with the given values.
 static inline iree_string_pair_t iree_make_string_pair(
     iree_string_view_t first, iree_string_view_t second) {
-  iree_string_pair_t v = {first, second};
+  iree_string_pair_t v = {{first}, {second}};
   return v;
 }
```
