### ISSUE TITLE
tosa.reshape -> linalg pattern incorrectly matching a reshape to a collapse

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#11874]
The `ReshapeConverterCollapse` pattern is incorrectly triggering on a reshape that is not a collapse and producing a `tensor.collapse_shape` op that does not pass verification:

```
Legalizing operation : 'tosa.reshape'(0x2cc2e6dc8e0) {
  %1996 = "tosa.reshape"(%1995) {new_shape = array<i64: 1, 17>} : (tensor<17x1xi32>) -> tensor<1x17xi32>

  * Fold {
  } -> FAILURE : unable to fold

  * Pattern : 'tosa.reshape -> ()' {
Trying to match "`anonymous-namespace'::ReshapeConverterExpand"
    ** Failure : tosa.reshape Attempting to expand into an incompatible shape
"`anonymous-namespace'::ReshapeConverterExpand" result 0
  } -> FAILURE : pattern failed to match

  * Pattern : 'tosa.reshape -> ()' {
Trying to match "`anonymous-namespace'::ReshapeConverterCollapse"
    ** Insert  : 'tensor.collapse_shape'(0x2cc2fb3c3a0)
    ** Replace : 'tosa.reshape'(0x2cc2e6dc8e0)
"`anonymous-namespace'::ReshapeConverterCollapse" result 1

    //===-------------------------------------------===//
    Legalizing operation : 'tensor.collapse_shape'(0x2cc2fb3c3a0) {
      %1996 = "tensor.collapse_shape"(%1994) {reassociation = [[], [0, 1]]} : (tensor<17x1xi32>) -> tensor<1x17xi32>

    } -> SUCCESS : operation marked legal by the target
    //===-------------------------------------------===//
  } -> SUCCESS : pattern applied successfully
```
->
```
D:\Dev\iree/../iree-tmp/models/posenet/posenet_i8.mlir:515:12: error: 'tensor.collapse_shape' op expected rank reduction, but found source rank 2 <= result rank 2
    %512 = "tosa.reshape"(%511) {new_shape = array<i64: 1, 17>} : (tensor<17x1xi32>) -> tensor<1x17xi32>
           ^
```

There's a few of these reshape patterns that seem to be doing ad-hoc matching without actually checking that they should be used - for example I'd expect to see something in ReshapeConverterCollapse that tests if the result rank is less than the input rank.

Reproduces on `iree-tools-tflite-20230117.400` with iree-compiler at head of 763485404b2eca11befe92bf6e45a860eefa1180 using source model https://storage.googleapis.com/iree-model-artifacts/tflite-integration-tests/posenet_i8.tflite.

If this doesn't reproduce then it's possible this is a pattern application registration order issue as I'm building iree-compile with MSVC and that can sometimes expose these issues (clang may deterministically apply patterns in a different order and mask that this is possible).

**Comment by rsuderman** [comment]
Landed in https://reviews.llvm.org/D141981
