### ISSUE TITLE
`IREE_ASSERT` evals its condition even with asserts disabled, unlike standard `assert`.

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#11918]
See [`IREE_ASSERT` code](https://sourcegraph.com/github.com/iree-org/iree@90187bd9b6b09b1236b0e5d26676e9973e5ed2ff/-/blob/runtime/src/iree/base/assert.h?L41-43&subtree=true). The current always-eval behavior is arguably saner and removes a traditional footgun with `assert`. But in rarer cases, such as when evaluating an expensive condition inside the `assert` condition, there can be an expectation that the evaluation vanishes when asserts are disabled, so the footgun can work both ways. Ultimately, I suspect that minimization of surprisal by making `IREE_ASSERT` functionally equivalent to `assert` may be the overriding factor. WDYT?

**Comment by bjacob** [comment]
Oh wait, `&&` is a sequence point so `false && (condition)` will not actually eval `condition` ... so wait, what is the point of writing it this way as opposed to just `false` ?

**Comment by ScottTodd** [comment]
> Oh wait, `&&` is a sequence point so `false && (condition)` will not actually eval `condition` ... so wait, what is the point of writing it this way as opposed to just `false` ?

Maybe some compilers complain about unused variables if you erase the condition entirely?

**Comment by benvanik** [comment]
IIRC to avoid compiler warnings, usually. Whether _that's_ a good idea or not is another thing - assuming no side-effects the used values in the condition should be DCE'd and the user then doesn't need to worry about wrapping their own stuff in preprocessor stuff. If there's side-effecting behavior it could still persist even with disabled assertions, though. We could add an `IREE_ASSERTION` macro like we have `IREE_TRACE` and `IREE_STATISTICS` that'd make it a bit cleaner, at least:
```c
IREE_ASSERTION({
  bool something_expensive = do_some_call();
  IREE_ASSERT(something_expensive);
});
```
