### ISSUE TITLE
Stablize compilation time measurement in benchmarks

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#11922]
Right now we measure the compilation time for compiling various models. Though the numbers reported can vary a lot. For example, [this one ranges from 60s to 140s](https://perf.iree.dev/serie?IREE?MobileBertSquad%20%5Bfp32%5D%20(TFLite)%20GPU-Mali-Valhall%20full-inference%2Cexperimental-flags%20%5Bcompilation%3Amodule%3Acompilation-time%5D); similarly for [CPU](https://perf.iree.dev/serie?IREE?MobileBertSquad%20%5Bfp32%5D%20(TFLite)%20CPU-ARM64-v8A%204-thread%2Cbig-core%2Cfull-inference%2Cdefault-flags%20%5Bcompilation%3Amodule%3Acompilation-time%5D). With such a level of noisiness we cannot draw any meaningful information out of it and it's actually a distraction. We'd need to figure out ways to make the numbers more stable.

**Comment by pzread** [comment]
Unassigned myself as I'm not working on this currently
