### ISSUE TITLE
Build failed for iOS

### ISSUE THREAD

**Issue by wangkuiyi** [iree-org/iree#11967]
### What happened?

```
[17/389] Generating llvm-cpu_command_buffer_dispatch_test.bin from command_buffer_dispatch_test.mlir
FAILED: runtime/src/iree/hal/drivers/local_task/cts/llvm-cpu_command_buffer_dispatch_test.bin /Users/y/w/iree-ios/iree-runtime-build/ios-sim/runtime/src/iree/hal/drivers/local_task/cts/llvm-cpu_command_buffer_dispatch_test.bin
cd /Users/y/w/iree-ios/iree-runtime-build/ios-sim/runtime/src/iree/hal/drivers/local_task/cts && /Users/y/w/iree-ios/iree-build/install/bin/iree-compile --output-format=vm-bytecode --compile-mode=hal-executable --iree-hal-target-backends=llvm-cpu /Users/y/w/iree-ios/iree/runtime/src/iree/hal/cts/testdata/command_buffer_dispatch_test.mlir -o llvm-cpu_command_buffer_dispatch_test.bin --iree-hal-executable-object-search-path=\"/Users/y/w/iree-ios/iree-runtime-build/ios-sim\"
/Users/y/w/iree-ios/iree/runtime/src/iree/hal/cts/testdata/command_buffer_dispatch_test.mlir:25:94: error: expected ':'
      %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(32) offset(%c0) : !flow.dispatch.tensor<readonly:f32>
                                                                                             ^
```

### Steps to reproduce your issue

1. `git pull upstream main && git submodule update`
1. Follow steps in https://iree-org.github.io/iree/building-from-source/ios

The above error appears at the building of the IREE runtime for the iOS Simulator.

### What component(s) does this issue relate to?

Runtime

### Version information

9242287e7cca1eab8ab08f4f9f9a52c4cbf91c66

### Additional context

macOS: 13.1 (22C65)
Xcode: Version 14.2 (14C18)

**Comment by wangkuiyi** [comment]
The errored code snippet is

https://github.com/iree-org/iree/blob/c170ca3d2396eaa7e68e5a8b7a0f33dbef37d21b/runtime/src/iree/hal/cts/testdata/command_buffer_dispatch_test.mlir#L25-L26

**Comment by ScottTodd** [comment]
Looks like you'll need to rebuild the compiler tools (in your host build). If you've already rebuilt the compiler tools and still see that error, clean your build directory (https://github.com/iree-org/iree/issues/11331 might be affecting you too)
