### ISSUE TITLE
SSA violation error in `iree-stream-emplace-allocations` pass

### ISSUE THREAD

**Issue by MaheshRavishankar** [iree-org/iree#11981]
This IR causes an SSA violation in the `EmplaceAllocations` pass in Stream

```
util.global private @_constant : !stream.resource<constant>
util.global private @_constant_0 : !stream.resource<constant>
func.func private @_rng_normal_2d() {
  %c0_i8 = arith.constant 0 : i8
  %c8 = arith.constant 8 : index
  %c60 = arith.constant 60 : index
  %c0 = arith.constant 0 : index
  %c64 = arith.constant 64 : index
  %c32 = arith.constant 32 : index
  %c1065353216_i32 = arith.constant 1065353216 : i32
  %c4 = arith.constant 4 : index
  %_constant = util.global.load @_constant : !stream.resource<constant>
  %_constant_0 = util.global.load @_constant_0 : !stream.resource<constant>
  %0 = stream.async.transfer %_constant : !stream.resource<constant>{%c60} -> !stream.resource<*>{%c60}
  %1 = stream.async.transfer %_constant_0 : !stream.resource<constant>{%c8} -> !stream.resource<*>{%c8}
  %2 = stream.async.splat %c0_i8 : i8 -> !stream.resource<*>{%c4}
  %3 = util.optimization_barrier %2 : !stream.resource<*>
  %4 = stream.async.splat %c1065353216_i32 : i32 -> !stream.resource<*>{%c4}
  %5 = util.optimization_barrier %4 : !stream.resource<*>
  %6 = util.optimization_barrier %1 : !stream.resource<*>
  %7 = stream.resource.size %5 : !stream.resource<*>
  %8 = stream.resource.size %3 : !stream.resource<*>
  %9:2 = stream.async.dispatch @_rng_normal_2d_dispatch_0::@_rng_normal_2d_dispatch_0_generic_8[%c8](%5[%c0 to %7 for %7], %3[%c0 to %8 for %8]) : (!stream.resource<*>{%7}, !stream.resource<*>{%8}) -> (!stream.resource<*>{%c32}, !stream.resource<*>{%c32})
  %10 = stream.async.alloca : !stream.resource<*>{%c64}
  %11 = stream.async.update %9#0, %10[%c0 to %c32] : !stream.resource<*>{%c32} -> %10 as !stream.resource<*>{%c64}
  %12 = stream.async.update %9#1, %11[%c32 to %c64] : !stream.resource<*>{%c32} -> %11 as !stream.resource<*>{%c64}
  %13 = stream.async.slice %12[%c0 to %c60] : !stream.resource<*>{%c64} -> !stream.resource<*>{%c60}
  %14 = stream.async.transfer %13 : !stream.resource<*>{%c60} -> !stream.resource<external>{%c60}
  %15 = stream.tensor.export %14 : tensor<3x5xf32> in !stream.resource<external>{%c60} -> tensor<3x5xf32>
  %16 = stream.async.transfer %0 : !stream.resource<*>{%c60} -> !stream.resource<external>{%c60}
  %17 = stream.tensor.export %16 : tensor<3x5xf32> in !stream.resource<external>{%c60} -> tensor<3x5xf32>
  check.expect_almost_eq(%15, %17) : tensor<3x5xf32>
  return
}
```

```
$ iree-opt  --iree-stream-emplace-allocations emplace_allocations_repro.mlir 
emplace_allocations_repro.mlir:23:10: error: operand #4 does not dominate this use
  %9:2 = stream.async.dispatch @_rng_normal_2d_dispatch_0::@_rng_normal_2d_dispatch_0_generic_8[%c8](%5[%c0 to %7 for %7], %3[%c0 to %8 for %8]) : (!stream.resource<*>{%7}, !stream.resource<*>{%8}) -> (!stream.resource<*>{%c32}, !stream.resource<*>{%c32})
         ^
emplace_allocations_repro.mlir:23:10: note: see current operation: %20:2 = "stream.async.dispatch"(%1, %15, %13, %19, %20#0, %17, %18, %4, %4, %3, %3, %3, %5, %17, %18, %5, %4, %17, %18, %5, %5, %4, %4) {entry_point = @_rng_normal_2d_dispatch_0::@_rng_normal_2d_dispatch_0_generic_8, operand_segment_sizes \
= array<i32: 1, 4, 4, 4, 4, 4, 2>, tied_operands = [2 : index, 3 : index]} : (index, !stream.resource<*>, !stream.resource<*>, !stream.resource<*>, !stream.resource<*>, index, index, index, index, index, index, index, index, index, index, index, index, index, index, index, index, index, index) -> (!stream\
.resource<*>, !stream.resource<*>)
emplace_allocations_repro.mlir:23:10: note: operand defined here (op in the same block)
```

**Comment by MaheshRavishankar** [comment]
Encountered with #11980

**Comment by MaheshRavishankar** [comment]
I havent traiged it, but @benvanik FYI...

**Comment by benvanik** [comment]
weiiird
`#20:2 = "stream.async.dispatch"(%1, %15, %13, %19, %20#0`
![image](https://user-images.githubusercontent.com/75337/215015610-1ff151bb-d548-43e9-92c8-bd6bb33b177c.png)

**Comment by benvanik** [comment]
(I can take a look at this in the morning - thanks for the reproducer!)

**Comment by benvanik** [comment]
Looks to be specific to multi-result stuff as the pass is not checking for that case - explains why we hadn't seen it yet! Will look into whether this is an easy fix or if I should just rewrite that pass.

**Comment by benvanik** [comment]
scratch that, I do have a test for that but this seems to trigger something else - will see if I can get the reproducer into a test case:
https://github.com/google/iree/blob/4fb9c4c4964cca34bf90a4c935ff8c1e1a0463cc/compiler/src/iree/compiler/Dialect/Stream/Transforms/test/emplace_allocations.mlir/#L88-L92

**Comment by benvanik** [comment]
There's a dispatch region optimization here where we can move the inserts into the dispatch and make it in-place avoiding the need to fix this up later - that'd avoid an additional binding. We still need to support this pattern, though.

**Comment by benvanik** [comment]
Minimal repro:
```mlir
func.func @emplaceMultiResultDispatchInto(
    %input: !stream.resource<*>, %input_size: index,
    %update_size: index, %target_size: index) -> !stream.resource<*> {
  %c0 = arith.constant 0 : index
  %c32 = arith.constant 32 : index
  %c64 = arith.constant 64 : index
  %update:2 = stream.async.dispatch @ex::@dispatch0(%input[%c0 to %input_size for %input_size]) : (!stream.resource<*>{%input_size}) -> (!stream.resource<*>{%update_size}, !stream.resource<*>{%update_size})
  %target = stream.async.alloca : !stream.resource<*>{%target_size}
  %target0 = stream.async.update %update#0, %target[%c0 to %c32] : !stream.resource<*>{%update_size} -> %target as !stream.resource<*>{%target_size}
  %target1 = stream.async.update %update#1, %target0[%c32 to %c64] : !stream.resource<*>{%update_size} -> %target0 as !stream.resource<*>{%target_size}
  return %target1 : !stream.resource<*>
}
```

Complication is that if we emplace both `%update:2` results as we should we end up with two dispatch results but only one user:
```mlir
func.func @emplaceMultiResultDispatchInto(
    %input: !stream.resource<*>, %input_size: index,
    %update_size: index, %target_size: index) -> !stream.resource<*> {
  %c0 = arith.constant 0 : index
  %c32 = arith.constant 32 : index
  %c64 = arith.constant 64 : index
  %target = stream.async.alloca : !stream.resource<*>{%target_size}
  %inplace_target:2 = stream.async.dispatch @ex::@dispatch0(%input[%c0 to %input_size for %input_size], %target[%c0 to %update_size for %update_size], %target[%update_size to %target_size for %update_size]) : (!stream.resource<*>{%input_size}, !stream.resource<*>{%target_size}, !stream.resource<*>{%target_size}) -> (%target{%target_size}, %target{%target_size})
  return %inplace_target#0 : !stream.resource<*>
}
```
^ how to decide between returning `%inplace_target#0` or `%inplace_target#1`?
They should be identical, but it's a bit ugly. Fine at this layer as we don't remove unused results but doing this kind of thing earlier on at the dispatch region level would make it much cleaner.

**Comment by benvanik** [comment]
I think I solved it for now! I'll leave it up to you @MaheshRavishankar if you want to file an issue for folding the updates into dispatch regions and avoiding this overhead (could make bufferization/aliasing easier and writes may be possible to combine when done).

**Comment by MaheshRavishankar** [comment]
I cant quite figure out what should happen at dispatch regions w.r.t to the inserts cause I am lost in the stream terminology. If you could give more info, I can look into it. Broadly, agreed that we want to move `tensor.insert_slice` into dispatches as well.... Once we handle `pad` the right way, we wont have spurious `tensor.insert_slice` that might make it easier...

**Comment by benvanik** [comment]
It really depends on what's happening, but I think it's specifically relevant in multi-result cases of which they are likely to originate from things like split/concats. Common patterns in ML for "cells" do things like this:
![image](https://user-images.githubusercontent.com/75337/216204300-94d6c5fa-19a8-4859-8a1a-bf98e32d5331.png)

This ends up as something like this today:
```
%0 = dispatch @a(%input[offset_a...])
%1 = dispatch @b(%input[offset_b...])
%2 = insert_slice %0, %target[offset_a...]
%3 = insert_slice %1, %2[offset_b...]
```
This is good as it allows us to concurrently schedule a and b. If we were to move the inserts into the dispatches we'd actually hurt things:
```
%0 = dispatch @a(%input[offset_a...], %target[offset_a...]) -> %target
%1 = dispatch @b(%input[offset_b...], %0[offset_b...]) -> %0
```
As now we can't concurrently issue the dispatches even though they don't overlap.

What's unique here is that with multi-result fusion it can end up like this (which would be good!):
```
%0, %1 = dispatch @ab(%input[offset_a...], %input[offset_b...])
%2 = insert_slice %0, %target[offset_a...]
%3 = insert_slice %1, %2[offset_b...]
```
We don't care about concurrency as we're dispatching the work together so we could fold the whole chain of inserts (that all have single users/etc) into the dispatch and avoid the overhead of tracking the unique values.

But it's a small amount of overhead (runtime/code size/etc) so if there's no other benefits from knowing inside of the combined dispatch that the two outputs are going to mutually exclusive parts of the same result then it's low priority - just polish stuff. Mostly just musing about new patterns we have now thanks to multi-result fusion :)

**Comment by benvanik** [comment]
(and sorry it took me 5 "in the mornings" to finally get this fixed - it's been a hectic week! :)
