### ISSUE TITLE
Padding and im2col don't work in preprocessing pass pipeline

### ISSUE THREAD

**Issue by ThomasRaoux** [iree-org/iree#12028]
### What happened?

Those 2 passes are silently ignored when used in preprocessing.

repro use iree-compile with:
--iree-preprocessing-pass-pipeline="builtin.module(func.func(iree-flow-convert-conv2d-to-img2col,iree-flow-pad-linalg-ops=pad-size=16))"

**Comment by stellaraccident** [comment]
By ignored, you mean not run?

**Comment by ThomasRaoux** [comment]
> By ignored, you mean not run?

yes, the argument is silently ignored and the passes don't run

**Comment by MaheshRavishankar** [comment]
well there were no tests for those specific passes. There were others that had tests, which did run....

**Comment by MaheshRavishankar** [comment]
I am looking into it..
