### ISSUE TITLE
Add Vulkan / CUDA A100 Stable Diffusion e2e to perf.iree.dev. 

### ISSUE THREAD

**Issue by powderluv** [iree-org/iree#12065]
### Request description

As we ship IREE to users who run Stable Diffusion would be good to catch performance regressions in perf.iree.dev. 

Can we please add Stable Diffusion from SHARK to perf.iree.dev. 

### What component(s) does this issue relate to?

Other

**Comment by mariecwhite** [comment]
Sure I can look into adding this. Can you point me to the model code? Currently perf.iree.dev supports TF and TFLite so those inputs are preferred.

**Comment by powderluv** [comment]
[This](https://github.com/nod-ai/SHARK/blob/main/apps/stable_diffusion/scripts/txt2img.py) is the main entry point for the CLI. Once you setup SHARK we just have to call that with flags like in the example. We can make the script better suited for perf.iree.dev. Currently it is via Torch. 

Adding @dan-garvey and @monorimet so we can add any flags required for you to use. We do plan to have a benchmark script ourselves for SD.

**Comment by mariecwhite** [comment]
Thanks. We'll need to add PyTorch support into perf.iree.dev to get this running. I'll work on this first.

**Comment by mariecwhite** [comment]
@pzread What is needed to get the Stable Diffusion model integrated? I see a couple of tasks here:

1. We are missing support for PyTorch models in perf.iree.dev. @powderluv if you can upload the nightly mlir file, similar to that SHARK is doing in gs://shark_tank/nightly, it would be more straightforward for the benchmarking infra to pull that down and compile that.
2. AMD runners. I believe our benchmarking runners are Intel-based. @powderluv what gc instance would we need to run these benchmarks?

**Comment by powderluv** [comment]
Latest "stable" nightly is here: https://storage.googleapis.com/shark_tank/latest/unet64_512_512_fp16_stabilityai_stable_diffusion_2_1_base/unet64_512_512_fp16_stabilityai_stable_diffusion_2_1_base_torch.mlir (there are 4 models total in the stable diffusion pipeline). 

If we run the default script for stable diffusion after setting up SHARK like https://github.com/nod-ai/SHARK/tree/main#linux--macos-users-2

```
python3.10 apps/stable_diffusion/scripts/txt2img.py --precision=fp16 --device=vulkan --prompt="tajmahal, oil on canvas, sunflowers, 4k, uhd"
```

It will import the MLIRs automatically (without a torch-mlir requirement). If you add the flag `--import_mlir` it will do a torch->torch-mlir conversion and then run the script. 

@dan-garvey has a golden image tester at the end of our CI that we can leverage to make sure the images are still good. 


We don't need AMD machines. This will run on the same A100 instance we have for SHARK tests but just use the vulkan path. We can enable the CUDA path too.

**Comment by allieculp** [comment]
@pzread @mariecwhite Any update on this?

**Comment by pzread** [comment]
I believe @antiagainst is working on this https://github.com/openxla/iree/pull/13107

**Comment by antiagainst** [comment]
[Clip](https://perf.iree.dev/serie?IREE?c80832d99fe0f7984c5e5b346336194772e0dd5dabe76fbe5fc930f214b59fd8) and [Unet](https://perf.iree.dev/serie?IREE?87e9645f8242ed27b624fee30e233a485c7f9dfed268f7a4d1872a327cb82d22) is added right now. Need to also add VAE, pending https://github.com/openxla/iree/pull/12767.

**Comment by antiagainst** [comment]
closing as obsolete -- no actions planned now
