### ISSUE TITLE
Fail to run MatMul CUDA TensorCore test.

### ISSUE THREAD

**Issue by JamesTheZ** [iree-org/iree#12123]
### What happened?

All the TensorCore test under `iree/tests/e2e/matmul/` fails in my environment. The SIMT tests have passed.

The environment is:
NVIDIA A10 GPU,
nvidia/cuda:11.6.2-cudnn8-devel-ubuntu18.04 docker image,
updated python 3.8, clang 11 in the docker.

### Steps to reproduce your issue

I follow the instructions in `https://iree-org.github.io/iree/building-from-source/getting-started/#clone-and-build` to build and run the tests.

### What component(s) does this issue relate to?

Compiler

### Version information

The IREE commit id is: 78940a262083d274575709e292c859cd5655adee

**Comment by ThomasRaoux** [comment]
Could you share a log of the error? I don't have an A10 GPU to test on. The code generated by those tests are targeting sm_80 architecture and I'm guessing there is an incompatibility.

**Comment by JamesTheZ** [comment]
The error log of `ctest` command is not rich:
```
Start testing: Feb 10 08:15 UTC
----------------------------------------------------------
17/23 Testing: iree/tests/e2e/matmul/e2e_matmul_direct_f16_gpu_large_mma_sync_LLVMGPUMatmulTensorCore_cuda_cuda
17/23 Test: iree/tests/e2e/matmul/e2e_matmul_direct_f16_gpu_large_mma_sync_LLVMGPUMatmulTensorCore_cuda_cuda
Command: "/home/xxxx/workspace/release/iree-build-old/tools/iree-e2e-matmul-test" "/home/xxxx/workspace/release/iree-build-old/tests/e2e/matmul/e2e_matmul_direct_f16_gpu_large_mma_sync_LLVMGPUMatmulTensorCore_cuda_cuda.yaml" "--device=cuda"
Directory: /home/xxxx/workspace/release/iree-build-old/tests/e2e/matmul
"iree/tests/e2e/matmul/e2e_matmul_direct_f16_gpu_large_mma_sync_LLVMGPUMatmulTensorCore_cuda_cuda" start time: Feb 10 08:15 UTC
Output:
----------------------------------------------------------
iree/runtime/src/iree/hal/drivers/cuda/native_executable.c:128: INTERNAL; CUDA driver error 'CUDA_ERROR_INVALID_VALUE' (1): invalid argument; while invoking native function hal.executable.create; while calling import; 
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module.__init:544 /home/xxxx/workspace/release/iree-build-old/tests/e2e/matmul/e2e_matmul_direct_f16_gpu_large_mma_sync_LLVMGPUMatmulTensorCore_cuda_cuda.mlir:37:13
      at /home/xxxx/workspace/release/iree-build-old/tests/e2e/matmul/e2e_matmul_direct_f16_gpu_large_mma_sync_LLVMGPUMatmulTensorCore_cuda_cuda.mlir:36:1; replaying trace file '/home/xxxx/workspace/release/iree-build-old/tests/e2e/matmul/e2e_matmul_direct_f16_gpu_large_mma_sync_LLVMGPUMatmulTensorCore_cuda_cuda.yaml'
<end of output>
Test time =   3.75 sec
----------------------------------------------------------
Test Failed.
"iree/tests/e2e/matmul/e2e_matmul_direct_f16_gpu_large_mma_sync_LLVMGPUMatmulTensorCore_cuda_cuda" end time: Feb 10 08:15 UTC
"iree/tests/e2e/matmul/e2e_matmul_direct_f16_gpu_large_mma_sync_LLVMGPUMatmulTensorCore_cuda_cuda" time elapsed: 00:00:03
----------------------------------------------------------

End testing: Feb 10 08:15 UTC

driver=cuda =   3.75 sec*proc

iree/tests/e2e/matmul =   3.75 sec*proc

noasan =   3.75 sec*proc

nomsan =   3.75 sec*proc

notsan =   3.75 sec*proc

noubsan =   3.75 sec*proc

requires-gpu-nvidia =   3.75 sec*proc
```

I also tested an MLIR input file with `iree-run-mlir` tool.
The command is:
```
../iree-build-old/tools/iree-run-mlir \
  --iree-hal-target-backends=cuda \
  --mlir-print-ir-after-all \
  matmul.mlir \
  --input=f32=-2
```
The content in `matmul.mlir` is:
```
#compilation0 = #iree_codegen.compilation_info<
  lowering_config = <tile_sizes = [[128, 128, 64]]>,
  translation_info = <LLVMGPUMatmulTensorCore
  pipeline_depth = 3>,
  workgroup_size = [64 : index, 2 : index, 1 : index]>
func.func @matmul_1024x256xf16_times_256x512xf16_into_1024x512xf16_for_LLVMGPUMatmulTensorCore_128_128_64_64_2_1(%lhs: tensor<1024x256xf16>, %rhs: tensor<256x512xf16>, %acc: tensor<1024x512xf16>) -> tensor<1024x512xf16> {
  %result = linalg.matmul {compilation_info = #compilation0} ins(%lhs, %rhs: tensor<1024x256xf16>, tensor<256x512xf16>) outs(%acc: tensor<1024x512xf16>) -> tensor<1024x512xf16>
  return %result: tensor<1024x512xf16>
}
```
The dumped MLIR pipeline is [iree-matmul-test.log](https://github.com/iree-org/iree/files/10705406/iree-matmul-test.log).
With the error of `LLVM ERROR: Cannot select: intrinsic %llvm.nvvm.cp.async.commit.group`.


The error log is different. I don't know whether they have the same problem.

**Comment by JamesTheZ** [comment]
By the way, how to dump the MLIR of each pass when running tests with `ctest`?

**Comment by ThomasRaoux** [comment]
> The dumped MLIR pipeline is [iree-matmul-test.log](https://github.com/iree-org/iree/files/10705406/iree-matmul-test.log). With the error of `LLVM ERROR: Cannot select: intrinsic %llvm.nvvm.cp.async.commit.group`.
> 
> The error log is different. I don't know whether they have the same problem.

This error is because you are forcing going through the `LLVMGPUMatmulTensorCore` codegen pipeline but since you are not using sm_8* kind of target we end up using features not available on the default shader model. To fix that you need to add `--iree-hal-cuda-llvm-target-arch=sm_86` to the command line. 
We need to add a verifier for that part, the annotations are meant for internal use mostly and not super robust.

The original error looks like we are running out of shared memory for your target. Those tests assume it is running on sm_80 kind of target. If you compile and run without using the attributes to force a configuration you shouldn't run into this problem. In the IR you pasted you need to remove `#compilation0` attribute.
```
iree/runtime/src/iree/hal/drivers/cuda/native_executable.c:128: INTERNAL; CUDA driver error 'CUDA_ERROR_INVALID_VALUE' (1): invalid argument; while invoking native function hal.executable.create; while calling import; 
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module.__init:544 /home/xxxx/workspace/release/iree-build-old/tests/e2e/matmul/e2e_matmul_direct_f16_gpu_large_mma_sync_LLVMGPUMatmulTensorCore_cuda_cuda.mlir:37:13
      at /home/xxxx/workspace/release/iree-build-old/tests/e2e/matmul/e2e_matmul_direct_f16_gpu_large_mma_sync_LLVMGPUMatmulTensorCore_cuda_cuda.mlir:36:1; replaying trace file '/home/xxxx/workspace/release/iree-build-old/tests/e2e/matmul/e2e_matmul_direct_f16_gpu_large_mma_sync_LLVMGPUMatmulTensorCore_cuda_cuda.yaml'
<end of output>
Test time =   3.75 sec
```

> By the way, how to dump the MLIR of each pass when running tests with ctest?

I believe it should dump out the command line, you can re-run it and add `-mlir-print-ir-after-all`

**Comment by JamesTheZ** [comment]
Thanks for your reply.

I modified the tiling size in the `#compilation0` attribute, and added `--iree-hal-cuda-llvm-target-arch=sm_86` to the command line of `iree-run-mlir`. It looks like the original problem of intrinsic and out-of-shared-mem are gone.

I assume `lowering_config = <tile_sizes = [[128, 128, 32]]>` means the thread-block level tiling is `[128, 128, 32]`. Am I right? How to specify more tiling configs like warp tiling size, warp layout (2x2 v.s. 4x1),  and MMA instruction type (e.g., 16-8-16 v.s. 16-8-8)?

Finally by running:
```bash
../iree-build/tools/iree-run-mlir \
  --iree-hal-target-backends=cuda \
  --iree-hal-cuda-llvm-target-arch=sm_86 \
  --mlir-print-ir-after-all \
  matmul.mlir \
  --input=f32=-2
```
I got the following error:
```
Failure for split at line #1: iree/runtime/src/iree/vm/invocation.c:95: INVALID_ARGUMENT; input list and function mismatch; expected 3 arguments but passed 1; evaluating export function 0; Evaluating functions
ERROR running file (matmul.mlir):
iree/runtime/src/iree/vm/invocation.c:95: INVALID_ARGUMENT; input list and function mismatch; expected 3 arguments but passed 1; evaluating export function 0; Evaluating functions
Compiling for target backend 'cuda*'...
EXEC @matmul_1024x256xf16_times_256x512xf16_into_1024x512xf16_for_LLVMGPUMatmulTensorCore_128_128_32_64_2_1
```
Does it mean that I need to give some input when running `iree-run-mlir` command? I did not find out how to specify the input for the given MLIR func.

**Comment by ThomasRaoux** [comment]
> Does it mean that I need to give some input when running `iree-run-mlir` command? I did not find out how to specify the input for the given MLIR func.

yes you need to pass inputs matching the type of the function arguments:
`—input=1024x256xf16 —input=256x512xf16`

**Comment by JamesTheZ** [comment]
It succeeds after specifying the inputs. Thank you a lot! @ThomasRaoux 

I will ask about the tiling problem in another issue.
