### ISSUE TITLE
Compare benchmarks checksum to reduce execution time and noise

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#12152]
Not sure if this has been tried already but would it make sense to compute some sort of checksum of the benchmark binaries in CI and compare them against the ones from the baseline? We could avoid running benchmarks when the checksum doesn't change. That should reduce the turnaround of the benchmark pipelines and help with the interpretation of noisy results.

**Comment by GMNGeoffrey** [comment]
Yes this is the high-level caching we'd want to do. Although note that we'd need to check both the compilation artifacts and the runtime ones. Bazel would give us the correct dependency analysis, but we'll need to hack something together ourselves for CMake :-/

**Comment by pzread** [comment]
Besides the checksums on compilation and runtime artifacts, we also need to consider the benchmark configuration (runtime flags, target devices).

**Comment by pzread** [comment]
Move the idea to #13923 to centralize the discussion
