### ISSUE TITLE
Softmax Kernel giving NaNs. 

### ISSUE THREAD

**Issue by pashu123** [iree-org/iree#12193]
### What happened?

The output from dispatch 43 is NaNs. The dispatch's mlir is https://gist.github.com/bcb869744964e72b19a68b1c24d28504 and the dispatch's Spirv is https://gist.github.com/4d32cf56fe1751de4a8170675fd23ec3. 

### Steps to reproduce your issue

First download `stable.mlir` from https://storage.googleapis.com/shark-public/prashant/stable.mlir .

Compilation command:
`iree-compile ~/stable.mlir --iree-llvm-target-cpu-features=host  --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-input-type=none --iree-hal-target-backends=vulkan --iree-preprocessing-pass-pipeline="iree-flow-detach-elementwise-from-named-ops,iree-flow-convert-1x1-filter-conv2d-to-matmul,iree-preprocessing-convert-conv2d-to-img2col,iree-preprocessing-pad-linalg-ops{pad-size=16}" --iree-flow-crop-at-index=43 --iree-hal-dump-executable-benchmarks-to=./dump/ --iree-spirv-index-bits=64 --iree-hal-dump-executable-binaries-to=./exec/ -iree-vulkan-target-triple=ampere-rtx3090-linux  -o unet.vmfb` 

Run with the below command: 
`iree-run-module --device=vulkan --function=forward --input=1x4x96x96xf32=0.5 --input=1xf32=2.0 --input=2x64x1024xf32=0.5 --input=xf32  --module=unet.vmfb --vulkan_debug_utils=true --vulkan_debug_verbosity=4 --vulkan_validation_layers=true > crop43.txt`

### What component(s) does this issue relate to?

Compiler

**Comment by antiagainst** [comment]
Looking into this now. What's `--iree-flow-crop-at-index=`? I didn't find that in IREE or SHARK fork. If you could provide the inputs to dispatch 43 that'd be helpful--I cannot repro the same dispatch region formation with upstream top of the tree right now.

**Comment by pashu123** [comment]
Oh! Sorry, this is the commit that I cherry-picked https://github.com/nod-ai/SHARK-Runtime/commit/9f0747b05 for the cropping pass.

**Comment by pashu123** [comment]
@antiagainst Let me know if you need inputs for the dispatch 43 or if you are okay with cherry-picking the pass.

**Comment by antiagainst** [comment]
I really struggle to reproduce this, after trying for quite some time. With f3ea9eef286bfb4ca58fed1f47eb034a7ce16a2a, using the following command-line:

tools/iree-compile --iree-input-type=none --iree-hal-target-backends=vulkan -iree-vulkan-target-triple=ampere-rtx3090-linux --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-preprocessing-pass-pipeline="builtin.module(iree-flow-detach-elementwise-from-named-ops,iree-flow-convert-1x1-filter-conv2d-to-matmul,iree-preprocessing-convert-conv2d-to-img2col,iree-preprocessing-pad-linalg-ops{pad-size=16})" --iree-spirv-index-bits=64 --iree-hal-dump-executable-sources-to=stable-sources ./stable.mlir -o stable.vmfb

I'm hitting issues on the local GPUs I have here: RTX 2070 Super OOM; RX 7900 XTX failed with "RESOURCE_EXHAUSTED; overflowed timeline semaphore max value; while invoking native function hal.fence.await". I don't have a RTX 3090 with me.. I guess maybe it can be reproduced on A100 in a VM? Could you maybe try that and let me know? 

Best would be to getthe tensor inputs to the faulty dispatch and being able to repro it just with the single dispatch.. Not sure how easy though given this seem to relate to index calculation so it would require the same buffer offset and such.

**Comment by benvanik** [comment]
(I'm getting together the instrumentation stuff now that could be used to trace out values (e.g. the indices being accessed) - may help in things like this - will see if I can get something together tomorrow in case you can't repro before then) nevermind I don't have vulkan wired up yet, but should be easy

**Comment by pashu123** [comment]
@antiagainst I am getting this 
```
[VULKAN] i linux_read_sorted_physical_devices:
[VULKAN] i      Original order:
[VULKAN] i            [0] NVIDIA GeForce RTX 3090
[VULKAN] i            [1] NVIDIA GeForce RTX 3090
[VULKAN] i      Sorted order:
[VULKAN] i            [0] NVIDIA GeForce RTX 3090
[VULKAN] i            [1] NVIDIA GeForce RTX 3090
[VULKAN] i linux_read_sorted_physical_devices:
[VULKAN] i      Original order:
[VULKAN] i            [0] NVIDIA GeForce RTX 3090
[VULKAN] i            [1] NVIDIA GeForce RTX 3090
[VULKAN] i      Sorted order:
[VULKAN] i            [0] NVIDIA GeForce RTX 3090
[VULKAN] i            [1] NVIDIA GeForce RTX 3090
[VULKAN] i Inserted device layer VK_LAYER_KHRONOS_validation (libVkLayer_khronos_validation.so)
[VULKAN] i        Using "NVIDIA GeForce RTX 3090" with driver: "libGLX_nvidia.so.0"

[VULKAN] ! Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x55aa75eec0f0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-LocalInvocationId-LocalInvocationId-04283] According to the Vulkan spec BuiltIn LocalInvocationId variable needs to be a 3-component 32-bit int vector. ID <4> (OpVariable) has components with bit width 64.
  %__builtin_var_LocalInvocationId__ = OpVariable %_ptr_Input_v3ulong Input

[1]    90356 IOT instruction (core dumped)  iree-run-module --device=vulkan --function=forward --input=1x4x96x96xf32=0.5
``` While running the above command.

**Comment by antiagainst** [comment]
> (I'm getting together the instrumentation stuff now that could be used to trace out values (e.g. the indices being accessed) - may help in things like this - will see if I can get something together tomorrow in case you can't repro before then) nevermind I don't have vulkan wired up yet, but should be easy

That would be great to try out once we have it! :D

**Comment by antiagainst** [comment]
> [VULKAN] ! Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x55aa75eec0f0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-LocalInvocationId-LocalInvocationId-04283] According to the Vulkan spec BuiltIn LocalInvocationId variable needs to be a 3-component 32-bit int vector. ID <4> (OpVariable) has components with bit width 64.
>   %__builtin_var_LocalInvocationId__ = OpVariable %_ptr_Input_v3ulong Input

That's a bug to fix. Let me handle it quickly.

**Comment by antiagainst** [comment]
https://reviews.llvm.org/D144819 should fix the validation error.

Again, on A100, with 289b9a1ebf954be3995cc1895254d09f2623341f and command-line in the previous  https://github.com/openxla/iree/issues/12193#issuecomment-1442822668, I'm still not able to repro the NaN issue. The full model runs successfully and the result are just normal float numbers.

**Comment by powderluv** [comment]
@pashu123  do you still see the error on rdna3 ?

**Comment by antiagainst** [comment]
FYI https://reviews.llvm.org/D144819 landed. Thought it would take some time to get incorporated into IREE.

**Comment by pashu123** [comment]
Yes, the NaNs issue is gone. Thanks, @antiagainst

**Comment by powderluv** [comment]
@antiagainst would it be possible to cherry-pick the patch into iree-fork so we can test end to end downstream while we wait for the next integrate ?

**Comment by antiagainst** [comment]
Here it is: https://github.com/iree-org/iree-llvm-fork/tree/spirv-64bit-processor-intrinsics.

**Comment by powderluv** [comment]
thank you.
