### ISSUE TITLE
Simple `tosa.conv2d` testcase fails to compile to VMVX+ukernel+data-tiling

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#12190]
Testcase (minimized from the one in #12189, coming from @lundong):

```
module {
  func.func @main(%arg0: tensor<1x112x112x8xi8>) -> tensor<1x112x112x16xi32> {
    %0 = "tosa.const"() {value = dense<[-918, -4433, 87, -234, -21393, 7738, 529, -8835, -16817, -375, -199, 572, 5082, 15569, -186, 4955]> : tensor<16xi32>} : () -> tensor<16xi32>
    %1 = "tosa.const"() {value = dense<"0xE2E2E2E2E2EBF6E206E2E2E8EBE6DEE2E0E2E2FDDCE7E1E2E2E2E2FDDFE6E0E3EBE2E2DCEFAC213DE2E2E2E3E2D3C9E4E2E2E2E2E3E1E1FA3EE2E2E9E9E5E3E47FE2E2E4EDE2E2E3E0E2E2E4DFE9DCFEE3E2E2E2E2E2E2E2F9E2E2E6EBEADCE4E2E2E2CEE5E1E0E181E2E2D9D3DEE1DDE2E2E2E2E2E2E2E2C5E2E2E2DBE1E3E1"> : tensor<16x1x1x8xi8>} : () -> tensor<16x1x1x8xi8>
    %2 = "tosa.conv2d"(%arg0, %1, %0) {dilation = array<i64: 1, 1>, pad = array<i64: 0, 0, 0, 0>, quantization_info = #tosa.conv_quant<input_zp = -128, weight_zp = -30>, stride = array<i64: 1, 1>} : (tensor<1x112x112x8xi8>, tensor<16x1x1x8xi8>, tensor<16xi32>) -> tensor<1x112x112x16xi32>
    return %2 : tensor<1x112x112x16xi32>
  }
}
```

Repro command line:

```
tools/iree-compile --iree-input-type=tosa --iree-hal-target-backends=vmvx --iree-vmvx-enable-microkernels --iree-flow-enable-data-tiling /tmp/conv1x1_test2.mlir
```

With the fix from #12189 avoiding the crash, this now results in the error message

```
/tmp/conv1x1_test2.mlir:5:10: error: 'func.func' op Tile+Distribute failed
    %2 = "tosa.conv2d"(%arg0, %1, %0) {dilation = array<i64: 1, 1>, pad = array<i64: 0, 0, 0, 0>, quantization_info = #tosa.conv_quant<input_zp = -128, weight_zp = -30>, stride = array<i64: 1, 1>} : (tensor<1x112x112x8xi8>, tensor<16x1x1x8xi8>, tensor<16xi32>) -> tensor<1x112x112x16xi32>
         ^
```

We are hitting the `notifyMatchFailure` here: https://github.com/iree-org/iree/blob/3c754f8e1c922429289250af22936a9bd556faec/compiler/src/iree/compiler/Codegen/Common/TileDispatchUsingInterface.cpp#L505-L509

Calling `tiledProducer->dump()` here, to see what isn't a `TilingInterface` as was expected, shows:

```
%extracted_slice_8 = tensor.extract_slice %52[%34, %43] [%20, %23] [1, 1] : tensor<?x?xi32> to tensor<?x?xi32>
```

Full `mlir-print-ir-after-all`:
https://gist.github.com/bjacob/cd6c4c471bbb6952dd63c4de8346b960

This only repros if with the conjunction of all these flags: `--iree-hal-target-backends=vmvx --iree-vmvx-enable-microkernels --iree-flow-enable-data-tiling`.

**Comment by bjacob** [comment]
FYI @hanhanW

**Comment by lundong** [comment]
A suggestion: after this issue is resolved, we may add the flag -iree-flow-enable-data-tiling in the e2e ukernel test at:
https://github.com/iree-org/iree/blob/main/tests/e2e/tosa_ops/CMakeLists.txt#L169

**Comment by hanhanW** [comment]
The issue happens in TileAndDistribute pass. The pass does not handle the case of `tiling an op could generate multiple ops`. In ukernel path, the unpack op has dynamic inner tiling sizes. In the context, tiling unpack op generates `unpack + extract_slice` ops. However, there are no tiling implementation of extract_slice op. Thus, it gets failed.

We don't need to cast the tiledProducer to TilingInterface. We can drop the casting to fix the issue. Here is the prototype: https://github.com/iree-org/iree/pull/12203/commits/b30b4f04b7917b65e80119318af86838ae531380

note that it's based on https://github.com/iree-org/iree/pull/12179

**Comment by bjacob** [comment]
Great, thanks for jumping on this @hanhanW !

> However, there are no tiling implementation of extract_slice op. 

So is that what needs to be fixed? Implement TilingInterface for extract_slice? Will that be enough, or were you suggesting that there was another separate issue above when you say "The issue happens in TileAndDistribute pass. The pass does not handle the case of tiling an op could generate multiple ops." ?

> We don't need to cast the tiledProducer to TilingInterface. We can drop the casting to fix the issue. Here is the prototype: https://github.com/iree-org/iree/commit/b30b4f04b7917b65e80119318af86838ae531380

Great, are you sending this as a PR?

**Comment by hanhanW** [comment]
Yes, there is a draft PR: https://github.com/iree-org/iree/pull/12203

I have to discuss with @MaheshRavishankar how to land the stuff properly. I'm also wondering if there are tiling implementation for extract_slice op. I haven't found the implementation. @MaheshRavishankar do you know anything about it?

**Comment by MaheshRavishankar** [comment]
We shouldnt implement the `TilingInterface` for `extract_slice` op. This creates a circular logic. The tile + fuse uses `extract_slice` as the anchor to find what to fuse. Implement the `TilingInterface` for that op itself would make things really hairy. You cant distinguish between what is a compute op to be tiled + fused, vs. what is a slice operation. Lets look a bit deeper. It might need some fixes to the interface API to fix this.

**Comment by hanhanW** [comment]
SG! In this case, I think my prototype makes sense. I'll clean it up after landing its parent PR.
