### ISSUE TITLE
collapsing reduction crashes when an input has a broadcast

### ISSUE THREAD

**Issue by okkwon** [iree-org/iree#12211]
### What happened?

```mlir
// RUN: iree-opt --split-input-file -iree-flow-collapse-dims %s | FileCheck %s

// Collapsing is not supported when an input is broadcasted; we can't collapse
// the input from tensor<4xf32> to tensor<32xf32> for example.

func.func @input_broadcast(%arg0: tensor<4x8xf32>, %arg1: tensor<4xf32>) -> tensor<f32> {
  %empty = tensor.empty() : tensor<f32>
  %reduce = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0)>, affine_map<(d0, d1) -> ()>], iterator_types = ["reduction", "reduction"]} ins(%arg0, %arg1 : tensor<4x8xf32>, tensor<4xf32>) outs(%empty : tensor<f32>) {
  ^bb0(%arg2: f32, %arg3: f32, %out: f32):
    %div = arith.divf %arg2, %arg3 : f32
    %add = arith.addf %out, %div : f32
    linalg.yield %add : f32
  } -> tensor<f32>
  return %reduce : tensor<f32>
}
// CHECK: @input_broadcast
// CHECK-NOT: tensor.collapse_shape
```

**Comment by MaheshRavishankar** [comment]
I don't think this is a bug. Collapsing such ops leads to indexing maps that are not projected permutations. What's the issue with the non-collapsed dims?

**Comment by okkwon** [comment]
Please refer to the related bug. I have a fix there, but you asked me to file a bug to assign it to Guray.

**Comment by MaheshRavishankar** [comment]
Understood, but linearizing this at the level at Linalg is not the prefered way forward.. Definitely shouldnt crash if it is crashing!

**Comment by grypp** [comment]
Thanks for letting me know about this bug. 

In fact this is not failing the pass that implemented. It crashes in collapse reduction pass https://github.com/iree-org/iree/blob/956a373b5274fc6741480309e5540210d427360d/compiler/src/iree/compiler/Dialect/Flow/Transforms/CollapseReductionDims.cpp#L33-L35

I agree we cannot collapse here. I just created a fix. Let me know what do you think

**Comment by allieculp** [comment]
@grypp @MaheshRavishankar Bumping this up to see if the fix was reviewed?

**Comment by MaheshRavishankar** [comment]
@grypp could you please verify if this is still and issue and close if it isnt.

**Comment by grypp** [comment]
yes, it works @okkwon submitted a fix that.
