### ISSUE TITLE
Improve support for executable experimentation.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#12222]
Based on #12126 from @qcolombet.

We've identified a laundry list of things to make a few workflows nice:
* replace an executable with different MLIR
* replace an executable with LLVM bitcode
* replace an executable with PTX source

Changing "replace" to "link" would also let us handle microkernels and is something we can fix at the same time.

Common tasks (useful for end-users and microkernels too):
* [x] support standardized MLIR executable merging early in the HAL pipeline (not per-backend)
* [x] support linking bitcode in the CUDA backend (instead of just replacement, ala CPU)
* [x] support linking bitcode in the CPU backend (in addition to .o as today)
* [x] implement `--iree-hal-dump-executable-intermediates-to=` flag in CUDA backend (instead of the stdout dump ptx flag)
* [x] improve CUDA linking support for fully external bitcode replacement

The unique work for #12126's workflow would be to add a new pass before/around `--iree-hal-dump-executable-sources-to=` that would swap out the contents of an executable with the contents of another _or_ replace the inner module with references to external object files.

One workflow is that one could dump-executable-sources-to=, modify them or lower them through iree-opt/etc, and then bring them back in and resume model compilation. This would allow for lightweight iteration of "what if this dispatch region was written like this" without needing to change the compiler to actually produce a dispatch region like that. For example, "what this didn't have the fused bias add" or "what if this called a microkernel instead."

A workflow matching #12126 would be to drop the inner module of an executable and add a set of objects to link instead - those objects could be mlir post-translation (LLVM/SPIR-V dialect, etc), bitcode, .o's in CPU, and PTX in CUDA.

The common tasks above work for all backends and should be fairly robust to things like multi-targeting, while the replacement workflow may need to be more specialized. An entire MLIR replacement could still support some of these by letting the user write something like https://github.com/iree-org/iree/blob/13a4a145b4892f8c146734f5d60afa4ca48ff104/samples/custom_dispatch/cuda/kernels/example.mlir#L43-L70 but it gets more complicated to specify otherwise without just allowing an array of object attributes to be specified. Since this is just a debugging feature for devs it's ok to be a bit rough, though, and require that users pass in the right files in the right formats with the right configuration.

The common features would combine with existing workflows around things like `--iree-hal-dump-executable-benchmarks-to=` and such as passing those results back to iree-compile would then support all the same linking/substitution behavior. A user could dump benchmarks and intermediates (PTX/etc), tweak the intermediates of the dispatch they want, and then use iree-compile to produce a microbenchmark with that modified PTX linked in.

If I had to order things I'd say getting executable replacement with MLIR->MLIR would be the first thing as it'd allow for PTX replacement via the same mechanism as custom_dispatch (dump executable sources, copy paste out, delete module, add object references to PTX) - from there we can add additional support for automatic substitution ("use the hal.executable you made but then delete the inner module and add these object files from this flag") - and finally we can flesh out the linking in the backends to handle more types (bitcode/etc). Orthogonal work would be to get the dump-intermediates flag working in CUDA to dump out bitcode and PTX files to make it easier to get those.

I'll take a look at that initial pass and then we can figure out next steps from there.

**Comment by benvanik** [comment]
First pass is going to support adding repeated flags like this:
```
iree-compile \
  --iree-hal-substitute-executable=some_executable_a=some/file_a.mlir \
  --iree-hal-substitute-executable=some_executable_b=some/file_b.ptx
```

If a .mlir/.mlirbc file is provided we'll just swap the whole executable out. This will allow for the custom_dispatch-like behavior of supporting multiple variants, target specialization, etc. If any other file is provided (ptx, spv, etc) we'll use the executable we created but drop its implementation and reference the provided file instead ala the `#hal.executable.object` attribute in custom_dispatch.

Since LLVM is parsing the flags it's possible to use response files to effectively have the mapping files as in #12126:
```
iree-compile @mappings.txt
```
mappings.txt:
```
--iree-hal-substitute-executable=some_executable_a=some/file_a.mlir
--iree-hal-substitute-executable=some_executable_b=some/file_b.ptx
```

Because it all bottoms out on the same flags this will also allow substitution from python/compiler C API/etc without needing extra files on disk (tricky in complex workflows).

**Comment by qcolombet** [comment]
Thanks @benvanik for filing and working on this!

**Comment by kuhar** [comment]
> --iree-hal-substitute-executable=some_executable_a=some/file_a.mlir
> --iree-hal-substitute-executable=some_executable_b=some/file_b.ptx

@benvanik @qcolombet  What do you think about substitution based on everything in a directory (instead of individual files), provided that the filenames match the names produced by `--iree-hal-dump--...`? This would seem more ergonomic to me, given that a dump would be your source of original substitution files for modification in nearly all cases that come to my mind.

I guess that alternatively, what I described above could be layered on top of repeated repeated substitution mappings.

**Comment by benvanik** [comment]
I thought about that too - could have `--iree-hal-substitute-executables-from=path/` that scans the dir to build the listing with the executable name inferred from the file names. I'll add that now, actually, as it's pretty easy :) Since we allow subsetting it'd let you do all executables if you did a dump with dump-sources-to= or a subset if you have a handful you want to swap out.

**Comment by benvanik** [comment]
Darn, the outputs to the various dump-to dirs have the module name in them which makes it harder to round-trip just on paths - could remove the module name I guess, but the binaries (like ptx) need target disambiguators in them. Still useful as a way to avoid needing to pass a bunch of flags but that use case is probably not going to be possible in this first version (dump to dir, change one or two file, and pass the dir right back in).

**Comment by benvanik** [comment]
nevermind, was able to make it work with round-tripping! 🎉
now silly things like `iree-compile --iree-hal-dump-executable-sources-to=foo/ --iree-hal-substitute-executables-from=foo/` work as a no-op :P

**Comment by benvanik** [comment]
#12240 added the path for substituting both executable MLIR and externalizing executables to reference ptx/spv, and #12265 adds support for dumping CUDA bitcode and linking bitcode on both CPU/CUDA paths sufficient for microkernels. There's one more cleanup needed to make full externalized CUDA bitcode workflows that I'll do next and add a custom_dispatch sample demonstrating that. Microkernels needs Mahesh's stuff and probably some additional CUDA specific LLVM lowering work but almost everything else should now be plumbed through.

**Comment by benvanik** [comment]
Sample landed showing .cu -> dispatch usage and ukernels on the GPU side are now possible (but not fully plumbed). Calling this done.
