### ISSUE TITLE
RV32 code size regression from #11576 LLVM integrate on 2022-12-16

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#12239]
Suspected LLVM integration: #11576

https://perf.iree.dev/serie?IREE?PersonDetect%20%5Bint8%5D%20(TFLite)%20CPU-RV32-Generic%20full-inference%2Cdefault-flags%20%5Bcompilation%3Amodule%3Acomponent-size%3Atotal-dispatch-size%5D

Direct local repro is nontrivial due to MLIR IR format change since that time, requires an `iree-import-tflite` from that timeframe. To make it easier, attaching here the already imported file. 
[person_detect.zip](https://github.com/iree-org/iree/files/10758622/person_detect.zip)

```
cmake --build . --target iree-compile && tools/iree-compile --iree-hal-target-backends=llvm-cpu --iree-input-type=tosa --iree-llvm-target-abi=ilp32 --iree-llvm-target-cpu-features=+m,+a,+f,+zvl512b,+zve32x --iree-llvm-target-cpu=generic-rv32 --iree-llvm-target-triple=riscv32-pc-linux-elf --riscv-v-fixed-length-vector-lmul-max=8 --riscv-v-vector-bits-min=512 benchmark_suites/TFLite/person_detect.tflite.mlir -o /tmp/a.vmfb --iree-llvm-keep-linker-artifacts 2>&1 | grep -o '/.*\.so' | xargs size -A | grep '^\.text' | awk '{print $2}'
```

Prints:

at IREE commit (and `git submodule update`) | value
--- | ---
[79b90d32d1723b0650b33bc5584dccb4828e5421](https://github.com/iree-org/iree/commit/79b90d32d1723b0650b33bc5584dccb4828e5421) | 871912
[7b4688272e40e939dc02053c7178b111a21eadd5](https://github.com/iree-org/iree/commit/7b4688272e40e939dc02053c7178b111a21eadd5) | 180752

**Comment by bjacob** [comment]
@hcindyl @pzread @julianwa

**Comment by dcaballe** [comment]
Could you try replacing `+zve32x` with `+zve32f` and see if the problem is still there

**Comment by bjacob** [comment]
That doesn't make a significant difference (`872080` vs `871912`).

**Comment by bjacob** [comment]
Bisect results coming soon (~ 5 bisection steps remaining)

**Comment by bjacob** [comment]
Bisection points to this commit (and I have verified that's indeed the case):
https://github.com/llvm/llvm-project/commit/f39b47264edda30b90ea9cc435fc1434a2e06edc

```
$ git bisect bad
f39b47264edda30b90ea9cc435fc1434a2e06edc is the first bad commit
commit f39b47264edda30b90ea9cc435fc1434a2e06edc
Author: Jakub Kuderski <kubak@google.com>
Date:   Mon Dec 12 14:39:57 2022 -0500

    [mlir][arith][tosa] Use extended mul in 32-bit `tosa.apply_scale`
    
    To not introduce 64-bit types that may be difficult to handle for some
    targets.
    
    Reviewed By: rsuderman, antiagainst
    
    Differential Revision: https://reviews.llvm.org/D139777

 mlir/lib/Conversion/TosaToArith/TosaToArith.cpp     | 16 ++++------------
 mlir/test/Conversion/TosaToArith/tosa-to-arith.mlir |  8 +-------
 2 files changed, 5 insertions(+), 19 deletions(-)
```

**Comment by benvanik** [comment]
paging @kuhar / @rsuderman / @antiagainst

**Comment by benvanik** [comment]
Maybe the arith.mulsi_extended lowering doesn't exist (emulated/decomposed)/is silly for all these backends?

**Comment by antiagainst** [comment]
@kuhar actually added lowering patterns for `arith.mulsi_extended` for LLVM: https://github.com/llvm/llvm-project/commit/285d321a855efb9415d0dcfa92141ae725dc7339#diff-04e8290220df887ebaa6c4bf8ba9d121af3df7536732e447029b6f342b5aaa62. The generated op sequence looks similar enough to me.. I'm not an expert on how LLVM would under the hood do the magic though.

**Comment by benvanik** [comment]
Are we sure it survives vectorization and such?

**Comment by bjacob** [comment]
@hcindyl would it be good enough as a short-term work-around if a new non-default flag restored the older TosaToArith lowering?

**Comment by dcaballe** [comment]
This seems to be bringing back the 64-bit vector issue that we fixed for zve32x some time ago. If a 64-bit vector instruction reaches the LLVM backend with zve32x, the whole operation will be scalarized. The LLVM lowering of `arith.mulsi_extended` seems to be generating 64-bit instructions, right?

**Comment by kuhar** [comment]
> The LLVM lowering of `arith.mulsi_extended` seems to be generating 64-bit instructions, right?

Yes, which should be identical to the original expansion in `tosa.apply_scale` before the change to `arith.mulsi_extended`

**Comment by kuhar** [comment]
@dcaballe Do you know if the riscv path has some dedicated pattern matching for i64 `arith.muli` and/or related ops?

**Comment by dcaballe** [comment]
The original IR generates two mul ops: from the first one, only the high part is used, from the second one, only the low part is used. The backend is able to match these patterns and generate the corresponding hi/lo muls included in zve32x. If we generate a single mul and extract the hi/low parts from it, the backend will try to generate a single mul and will end up scalarizing it.

**Comment by dcaballe** [comment]
I can't think of a robust solution for this problem since there is no generic mulhi mullo or mul extended representation in LLVM, right?

**Comment by bjacob** [comment]
Expecting that this problem might not have a very easy+robust solution, I asked above https://github.com/iree-org/iree/issues/12239#issuecomment-1433526034 if we might temporarily address this with a flag, if that would be acceptable to @hcindyl ?

**Comment by kuhar** [comment]
> I can't think of a robust solution for this problem since there is no generic mulhi mullo or mul extended representation in LLVM, right?

Correct, there are no dedicated intrinsics for those yet and it's generally onto each backend to pattern-match wide multiplication of sign/zero-extended inputs.



> Expecting that this problem might not have a very easy+robust solution, I asked above [#12239 (comment)](https://github.com/iree-org/iree/issues/12239#issuecomment-1433526034) if we might temporarily address this with a flag, if that would be acceptable to @hcindyl ?

The most straightforward solution that comes to my mind would be to add an option to the tosa to arith pass and conditionally used the old lowering without mulsi_extended.

**Comment by kuhar** [comment]
Repro with a single dispatch:

https://gist.github.com/kuhar/6e319a0a2b9af642cbcb54e9e10edc5b

Command:
```
iree-opt --iree-hal-translate-executables --iree-hal-serialize-executables --iree-llvm-keep-linker-artifacts repro.mlir
```

With full debug output:
```
iree-opt --iree-hal-translate-executables --iree-hal-serialize-executables --iree-llvm-keep-linker-artifacts repro.mlir --mlir-disable-threading --mlir-print-ir-after-all --print-after-all
```

The size is 5440 (`vector<5440xi8>, format = "embedded-elf-riscv_32", mime_type = "application/x-elf"`) with https://github.com/iree-org/iree/commit/79b90d32d1723b0650b33bc5584dccb4828e5421 and 3200 with just the llvm commit reverted: `git revert f39b47264edda30b90ea9cc435fc1434a2e06edc`.

**Comment by dcaballe** [comment]
> The most straightforward solution that comes to my mind would be to add an option to the tosa to arith pass and conditionally used the old lowering without mulsi_extended.

Would it make sense to have an optional arith->arith lowering for mulsi_exended that can generate the original code in tosa?

**Comment by kuhar** [comment]
I tried changing the arith-to-llvm lowering to match exactly what the old tosa-to-arith did so that
```
mlir-opt third_party/llvm-project/mlir/test/Conversion/TosaToArith/tosa-to-arith.mlir --split-input-file --tosa-to-arith="include-apply-rescale=true use-32-bit=true" --convert-arith-to-llvm
```

but despite this being identical, it still diverges in IREE's `LLVMCPU/ConvertToLLVM.cpp`. This seems brittle.

**Comment by kuhar** [comment]
> > The most straightforward solution that comes to my mind would be to add an option to the tosa to arith pass and conditionally used the old lowering without mulsi_extended.
> 
> Would it make sense to have an optional arith->arith lowering for mulsi_exended that can generate the original code in tosa?

both tosa.apply_scale and arith. lowering happens in `ConvertToLLVM.cpp`, so I assumed this would have the same effect to changing the lowering in ArithToLLVM, but I guess different folds (on the level or arith vs. llvm) may change the outcome. I'll give it a try too -- we could have it as a local pattern in IREE.

**Comment by kuhar** [comment]
An arith -> arith rewrite worked in my local setup: https://github.com/iree-org/iree/pull/12241

Do we want to fix this against the main branch or some release? @bjacob @dcaballe @antiagainst?

**Comment by hcindyl** [comment]
If possible, I would really appreciate this to be included in `main`, as our project pulls IREE's release candidate for `iree-compile` instead of building from source. I am okay with hiding this behind a compile flag if we don't want the behavior to be default.

**Comment by bjacob** [comment]
I confirm that #12241 fixes the testcase here.  Using the test in this Issue description (and using current `iree-import-tflite` to generate `person_detect.tflite.mlir`):

commit | .text size
--- | ---
Current `main` | 905036
With #12241 | 185720

Thanks a lot @kuhar for the effective fix!

**Comment by kuhar** [comment]
@hcindyl The fix has just been merged into `main`. It doesn't require any flags.

**Comment by hcindyl** [comment]
Thanks. However, I don't see a size drop in https://perf.iree.dev/serie?IREE?d967e293594998e48355d30d900dbdf77dbd6eedbff768112dbe8e7ec332b9eb-9e15f7e6-383c-47ec-bd38-ecba55a5f10a
![4436RykrEpPCcy8](https://user-images.githubusercontent.com/19485875/219780528-5b3835f1-a824-4400-88be-b249dfcaa1e0.png)

Is this because of the zve32x -> zve32f in https://github.com/iree-org/iree/commit/3a91bd8f9ba6049dfe93ea796a50f5112c2c3283? @dcaballe

**Comment by dcaballe** [comment]
Yes, 1 sec...

**Comment by dcaballe** [comment]
https://github.com/iree-org/iree/pull/12266
