### ISSUE TITLE
Allow IREE to be built with installed LLVM

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#12231]
### Request description

Customers frequently request to be able to build IREE against installed LLVM libraries. This issue tracks the work.

### What component(s) does this issue relate to?

Other

**Comment by stellaraccident** [comment]
This should be functionally complete now. A couple of follow-ons to finish off:

* Something is wrong with installed MLIR. find_package from the MLIR build tree gets everything (otherwise, missing tools like mlir-tblgen).
* Should add a CI job (can be post-submit) to run the byo script.

**Comment by allieculp** [comment]
@stellaraccident Setting this to 'in progress' - Is this work completed or leaving open for someone to finish?

**Comment by allieculp** [comment]
@stellaraccident checking on this one - leaving open for someone to finish? or closed?

**Comment by stellaraccident** [comment]
Last I heard, the customer was using this as-is, so will close.
