### ISSUE TITLE
Always run benchmarks on PRs modifying `third_party/llvm-project/`

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#12268]
We've had a few large performance regressions triggered by changes to MLIR/LLVM ("from LLVM integrates"). There are frequently too many commits and changes in each rollup to review in detail and determine whether or not to run benchmarks, so I propose we just always run benchmarks on presubmit whenever a PR modifies `third_party/llvm-project/`.

I'd probably implement this in https://github.com/iree-org/iree/blob/main/build_tools/github_actions/configure_ci.py with a `ALWAYS_RUN_BENCHMARKS_PATH_PATTERNS` like how we have `SKIP_PATH_PATTERNS`, and then have the check bypass git trailers / PR labels / etc.

(Some discussion about this [on Discord here](https://discord.com/channels/689900678990135345/760577505840463893/1076178445706477628))

**Comment by dcaballe** [comment]
How could we make this trigger only for integrates? When we are experimenting with LLVM changes, let's say on x86 only, we shouldn't have to run (and wait for) android and GPU benchmarks, for example. Could we enable this only for PRs that are not in Draft mode, for example? That would work...

**Comment by ScottTodd** [comment]
Good question. I think we can check for draft status. Here are some other ideas:

* Check for branch names matching a regex like `llvm-integrate-*` instead of checking file paths
* Check for the `llvm-integrate` label (https://github.com/openxla/iree/issues?q=label%3Allvm-integrate+)

**Comment by allieculp** [comment]
@pzread are you working on this?

**Comment by pzread** [comment]
Not working on this right now, but still on my task list

**Comment by pzread** [comment]
Looking at the history of LLVm integration and it seems like people used a variety of branch names and didn't use the integration label. But the PR title seems to mostly follow the pattern `Integrate.+(LLVM|llvm-project).*`.

Running benchmarks when the title/branch name is matched means every commit push will trigger a run, which can be very wasteful on the benchmark resources. Especially integration PRs usually have many commits. Nevertheless, most of the commits usually failed early in the CI pipeline, so it probably won't trigger too many benchmark runs.

**Comment by pzread** [comment]
> Could we enable this only for PRs that are not in Draft mode

Ah, now I saw this idea. It could work, but there is a corner case when someone converts an integration PR into `ready_for_review`. We don't trigger the CI workflow on this event. So benchmarks won't run unless there is another push after. We can trigger workflow on "ready_for_review" event, but either we always re-run the workflow for "all PRs" when they are flagged as ready for review, or some non-trivial logic needs to be implemented in a separate workflow (similar to our tricky benchmark triggering mechanism).

Let's see if some pattern matchings on PR's title and branch name will work first?
