### ISSUE TITLE
Constructs for better connecting micro kernel

### ISSUE THREAD

**Issue by MaheshRavishankar** [iree-org/iree#12276]
In course of connecting tensor-based micro kernel to replace the existing micro kernels path (#12157 ) a few constructs would make the connection cleaner. These could be built upstream and would make it easier to connect the codegen paths

1) There needs to be a way to lower a `memref` to a `void *`. Currently either `memref`s lower to a `struct {base_ptr, ptr, offset, sizes[], strides[]}`. There is also an option to lower a static `memref` to just a `void *`. Ideally upstream default lowering should lower `memref<elem-type>` (i.e 0D `memref` with no offset) to just a `void *`. Even if this is hard-coded that seems worth it as a way to lower to `void *`. That with `memref.extract_strided_metadata` can allow downstream users manage the ABI by themselves, without being tied into the ABI that the upstream MLIR prescribes that might not be suitable for all downstream users (at least is not suitable for IREE). 

1) The lowering uses `memref.extract_strided_metadata` as a means to get the base pointer, offsets, and strides when needed. This operation bundles together all the pieces. During the lowering it would be very convenient to have `memref.get_base_pointer` (and maybe other operations like `memref.get_offset`, `memref.get_sizes`, `memref.get_strides`, etc.) that can make it easier to manage. There are points in the lowering where the offsets, sizes and strides can be resolved, but base pointer can be resolved later. This will remove one specific "hack" that is done today as part of #12157 .  Starting with something like this

```
%0 = hal.interface.binding.subspan ... : memref<?x?xf32>{.., ..}
%base, %offset, %sizes:2, %strides:2 = memref.extract_strided_metadata %0 : memref<f32>, ...
...
func.call ... (... %base ...)
```

when resolving the `memref.extract_strided_metadata` (in the `ResolveBufferDescriptors` pass) the `%offset` , `%sizes:2` and `%strides:2` can be resolve based on the information from the `hal.interface.binding.subspan`. Ideally this IR is transformed into

```
%0 = hal.interface.binding.subspan ... : memref<?xf32>{..}
%base = memref.get_base_ptr %0 : memref<?xf32> -> memref<f32>
...
func.call ... (... %base ...)
```
 since at this stage we already have the information to resolve `%offset` , `%sizes:2` and `%strides:2` right here, and carrying it further is unnecessary.

**Comment by MaheshRavishankar** [comment]
@qcolombet since you have been working in this area, wondering if this is something you could help with (especially upstream). Happy to chat on GVC.

**Comment by qcolombet** [comment]
Hi @MaheshRavishankar,

Sure thing, now that I'm back from vacation, I can help!

**Comment by qcolombet** [comment]
What does it buy us to get from:
```
%0 = hal.interface.binding.subspan ... : memref<?x?xf32>{.., ..}
%base, %offset, %sizes:2, %strides:2 = memref.extract_strided_metadata %0 : memref<f32>, ...
...
func.call ... (... %base ...)
```
To
```
%0 = hal.interface.binding.subspan ... : memref<?xf32>{..}
%base = memref.get_base_ptr %0 : memref<?xf32> -> memref<f32>
...
func.call ... (... %base ...)
```

If we directly replace `%offset`, `%sizes:2`, and `%strides:2` produced by `memref.extract_strided_metadata` with what we know from `hal.interface.binding.subspan`, these values would effectively be dead and get cleared during lowering.

I like the conciseness of `memref.get_base_ptr` but I'm not sure it is worth adding a new operation just for that.
Essentially it looks to me like a pretty printer for `%base, %offset<dead>, %sizes:2<dead>, %strides:2<dead> = memref.extract_strided_metadata %0 : memref<f32>, ...`

**Comment by allieculp** [comment]
@MaheshRavishankar Looking for follow up here - if this is still relevant?

**Comment by MaheshRavishankar** [comment]
the `memref.reinterpret_cast` gives what I need here. Closing this bug.
