### ISSUE TITLE
Support a plugin mechanism in IREE codegen and use it to implement cutlass micro-kernels

### ISSUE THREAD

**Issue by ThomasRaoux** [iree-org/iree#12292]
### Request description

Even though IREE supports efficient code generations on most common ops we want to be able to leverage existing device side libraries when they exist and give an advantage. 
Libraries like cutlass provide different levels of hand-written libraries including block level and warp level libraries. Using those libraries allows to mix fusion and codegen startegy with hand tuned libraries. Being able to leverage this library would give IREE a way to collaborate efficiently with library writers and de-risk the codegen path by giving an alternative solution until full codegen solution gives performance parity on all targets.

cutlass is a large project specific to a single target therefore taking a dependency on cutlass in IREE build system is not desirable.

In order to solve this problem we will introduce a plugin mechanism in IREE that will allow IREE users to intercept operations and replace ops at different level of the codegenerations.

https://github.com/iree-org/iree/issues/12222 introduces a mechanism to intercept and replace executables at different levels. We will use this to prototype the plugin mechanism and refine the requirements needed. 

Here is what we want to prototype:
1) Use the current debug mechanism to replace linalg.matmul ops with existing micro-kernel ops pointing to the right file and get IREE codegen to consume this op without any knowledge of the micr-kernel
2) Improve the prototype by making the replace a pass called on the fly during compilation
3) Design a plugin interface so that IREE users can insert passes into code generation to replace some ops with device side library calls.
4) Use the plugin interface to make a module leverage cutlass kernels on top of IREE

### What component(s) does this issue relate to?

Compiler

**Comment by benvanik** [comment]
#12313 adds the plumbing required to invoke a tool or pass pipeline for each executable. The idea is that a user can either add passes to the IREE compiler when building it (via some IREE_BLAH_BLAH_EXTRA_LIBRARIES cmake thing?) and run those inline or build their own opt tool (mlir-opt-like, or in python, etc) to do the preprocessing. In the future when we get dynamically loadable compiler plugins (ala [clang plugins](https://clang.llvm.org/docs/ClangPlugins.html)) we can continue using this to route to pass pipelines registered by them.

I wanted to create something similar to https://github.com/benvanik/iree-template-runtime-cmake like `iree-template-compiler-cmake` that would show how to build a custom opt tool that used IREE and adjacent dialects (linalg, HAL, etc) and declared some passes/pipelines. Unfortunately I can't pick apart how our releases work - maybe it can already do this - but I think there's some intersection with the work to externalize LLVM. Someone who understands and wants to drive adoption of plugins should take this on and ensure the ergonomics are good and satisfy the user needs. There's now at least enough infrastructure in the compiler that all that work can happen mechanically and unrelated to the actual lowering pipelines.

**Comment by hwu36** [comment]
Happy to answer questions related to cutlass

**Comment by ThomasRaoux** [comment]
> Happy to answer questions related to cutlass

Thanks @hwu36! I'll take you up on that :)
1) One discussion that came up was whether cutlass is a good project to use as "threadblock level" library. (meaning a library called and inlined within a kernel that compose with other operations). 
From looking at the design of cutlass it seems like a perfect fit as cutlass exposes the knobs we need and hides things we don't need to know when using a threadblock level library like how we walk the data within a tile and how the compute/memory traffic is scheduled. 
Do you have any opinion and advice/warning of things to do or avoid here?

2) @grypp has tried compiling those block level kernels using open source clang and the performance were really poor. Is this something you have on your radar and do you know if someone on the clang/llvm side has plans to fix improve it. This is not a deal breaker for us but it would make our infrastructure simpler.  

If you think a more interactive conversation could be useful I would be happy to setup a video chat to discuss those as well.

**Comment by hwu36** [comment]
My understanding is that you want cutlass for performance.  In general, your ptx needs to be very close to cutlass to get the best perf.  It is especially true on hopper.  cutlass 2 for pre-hopper and cutlass 3 for hopper is a little different in usage.

First cutlass 2 and ampere. cutlass is modularized into hierarchy of device/kernel/threadblock/warp/thread.  The modules a typical kernel have are 1) gmem->smem iterator (threadblock level) 2) smem->rf iterator (warp level) 3) warp mma (warp level) 4) epilogue (which itself has several iterators to move data around).  We put 1-3 in a threadblock level mainloop.  mainloop and epilogue are connected in the kernel level.  In addition to these, we also have several functors (e.g. epilogue elementwise) to fill the customization needs.   Every modules are not really independent for the sake of the performance.  Shared memory layout is the handshake between different iterators.  If you want the good performance, you need to store the data in the shared memory as cutlass does, then you can use different cutlass modules with your own things to do what you want.  cutlass 2 code is still part of of cutlass even the version number is 3.0 now.

cutlass 3 is mainly for hopper (It can work on ampere, but it is not tuned).  hopper makes several big changes in the hardware and low level programming models.  cutlass 3 makes change to the modules accordingly.  cutlass 3 has cute as the low level layout algebra handler to make address computation much easier.  cutlass 3 also stops using iterators, but uses atoms.  If you want to know more about hopper, @thakkarV can explain in more details.

@manishucsd can also help you in using cutlass 2 and 3, too.

**Comment by hwu36** [comment]
As to clang, we don't build with it ourselves regularly though some cutlass community members use clang.

I am also happy to talk in person.

**Comment by ThomasRaoux** [comment]
Thanks for the detailed response (and sorry for the slow response on my side). 

> My understanding is that you want cutlass for performance. In general, your ptx needs to be very close to cutlass to get the best perf. It is especially true on hopper. cutlass 2 for pre-hopper and cutlass 3 for hopper is a little different in usage.
> 
> First cutlass 2 and ampere. cutlass is modularized into hierarchy of device/kernel/threadblock/warp/thread. The modules a typical kernel have are 1) gmem->smem iterator (threadblock level) 2) smem->rf iterator (warp level) 3) warp mma (warp level) 4) epilogue (which itself has several iterators to move data around). We put 1-3 in a threadblock level mainloop. 

This sounds great, 1-3 is exactly what we want to use and hook into the code generation.

> mainloop and epilogue are connected in the kernel level. In addition to these, we also have several functors (e.g. epilogue elementwise) to fill the customization needs. Every modules are not really independent for the sake of the performance. Shared memory layout is the handshake between different iterators. If you want the good performance, you need to store the data in the shared memory as cutlass does, then you can use different cutlass modules with your own things to do what you want. cutlass 2 code is still part of of cutlass even the version number is 3.0 now.

That makes sense. This mostly applies to inputs? We might have to make sure we use the right layout for matmul output but it looks simple from what I can see.

> 
> cutlass 3 is mainly for hopper (It can work on ampere, but it is not tuned). hopper makes several big changes in the hardware and low level programming models. cutlass 3 makes change to the modules accordingly. cutlass 3 has cute as the low level layout algebra handler to make address computation much easier. cutlass 3 also stops using iterators, but uses atoms. If you want to know more about hopper, @thakkarV can explain in more details.
> 
> @manishucsd can also help you in using cutlass 2 and 3, too.

We haven't looked in details at Hopper but this is something we are very interested in. It would be interesting to discuss what would be the equivalent level to intercept for hopper (threadblock level might not be the right level anymore?)

> As to clang, we don't build with it ourselves regularly though some cutlass community members use clang.

That's good to know. @grypp measured huge slow down when using clang, is this something you expect?

> 
> I am also happy to talk in person.

Thank you :) I'll send you an invite offline to discuss those in details when you are available.

**Comment by hwu36** [comment]
> This mostly applies to inputs?

Yes, the input operands should stored as cutlass does.

> is this something you expect?

I guess clang somehow spills.  `cuobjdump --dump-resource-usage xxx.o` could report STACK usage.  It should be zero.  If not, it spills either because the compiler cannot allocate registers within the giving register budget or the compiler fails to figure out some values are compile time constants.

**Comment by allieculp** [comment]
@grypp @ThomasRaoux Setting as P2 - please bump up if needed.

**Comment by ScottTodd** [comment]
@benvanik I think you have the most context on this type of issue these days. Is there still work we plan on doing in this area, or could we close this issue?

**Comment by benvanik** [comment]
Dead! The plumbing I added may still be useful - there's now executable objects for linking in the compiler/hal.dispatch.extern and stream.async.call for runtime command buffer operations and I think that covers all the bases for things like this.
