### ISSUE TITLE
RFC: Move public compiler headers and stubs to bindings/c

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#12326]
Currently, the public compiler headers and stub libraries are intermingled in the compiler implementation directory. This makes it hard/awkward to depend on the API without actually building the compiler (which is a use-case that we have in Google).

I'm planning to relocate the public, standalone parts of the compiler API to `compiler/bindings/c` and name them accordingly for public consumption.

This presently includes the following files under `compiler/src/iree/compiler/API2`:

* `Embed.h` (will rename to `iree/compiler/embed.h` or equiv)
* `Stub` (library which allows dynamic loading of an implementation)

As part of this, I will also rename `API2` -> `APIImpl` to distinguish it as the implementation of the API, and I will relocate the present contents of `API` to `bindings/python` (all that is left in the original `API` directory is the Python bindings).

This should be a pretty stable configuration that I don't anticipate changing once complete.

**Comment by benvanik** [comment]
sgtm - would make installs much easier
