### ISSUE TITLE
LLVM Integration causes mobilebert arm64 latency regression

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#12324]
LLVM integration https://github.com/openxla/iree/commit/d93c2634cb03a61e831cf78988174f123cdfe2b6 (2022-11-22) causes a few latency benchmark series to regress:

* https://perf.iree.dev/serie?IREE?MobileBertSquad%20%5Bfp32%5D%20(TFLite)%20big-core%2Cfull-inference%2Cdefault-flags%20with%20IREE-LLVM-CPU-Sync%20%40%20Pixel-6-Pro%20(CPU-ARMv8.2-A) 18%+
* https://perf.iree.dev/serie?IREE?MobileBertSquad%20%5Bfp32%5D%20(TFLite)%201-thread%2Cbig-core%2Cfull-inference%2Cdefault-flags%20with%20IREE-LLVM-CPU%20%40%20Pixel-6-Pro%20(CPU-ARMv8.2-A) 15%+
* https://perf.iree.dev/serie?IREE?MobileBertSquad%20%5Bfp32%5D%20(TFLite)%204-thread%2Cbig-core%2Cfull-inference%2Cdefault-flags%20with%20IREE-LLVM-CPU%20%40%20Pixel-6-Pro%20(CPU-ARMv8.2-A) 12%+
* https://perf.iree.dev/serie?IREE?MobileBertSquad%20%5Bint8%5D%20(TFLite)%20little-core%2Cfull-inference%2Cexperimental-flags%20with%20IREE-LLVM-CPU-Sync%20%40%20Pixel-4%20(CPU-ARMv8.2-A)
* ...

![image](https://user-images.githubusercontent.com/75337/220769395-8d197b3b-3a7e-4ea5-b159-9cd6db082fbd.png)

**Comment by antiagainst** [comment]
@dcaballe @bjacob or @hanhanW would somebody look into this and advise how to treat it? It has been there for a long while.

**Comment by bjacob** [comment]
i can take a look tomorrow, but a bisecting a really large llvm-project integrate + mhlo integrate + 43 files changed on IREE side + testcase involving an android benchmark means it's likely to take a whole day. FYI @julianwa

**Comment by hanhanW** [comment]
I think this is a dup of https://github.com/openxla/iree/issues/11357

I was distracted from other things. The conclusion was it's because of LLVM backend changes. The IRs before converting to LLVM module are same. The data in hal.executable.binary public @embedded_elf_arm_64 is different.

Closing the issue and moving to https://github.com/openxla/iree/issues/11357
