### ISSUE TITLE
Data layout tiling enablement caused latency regression

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#12322]
52c2e354f6c04b5aa45fb1e51f6599b1ea714e83 enables data layout tiling for latency benchmarks. It causes regression on several benchmark series:

* https://perf.iree.dev/serie?IREE?MobileNetV3Small%20%5Bfp32%2Cimagenet%5D%20(TFLite)%20little-core%2Cfull-inference%2Cexperimental-flags%20with%20IREE-LLVM-CPU-Sync%20%40%20Pixel-6-Pro%20(CPU-ARMv8.2-A)  25%+
* https://perf.iree.dev/serie?IREE?MobileNetV3Small%20%5Bfp32%2Cimagenet%5D%20(TFLite)%20little-core%2Cfull-inference%2Cexperimental-flags%20with%20IREE-LLVM-CPU-Sync%20%40%20Pixel-4%20(CPU-ARMv8.2-A) 23%+
* https://perf.iree.dev/serie?IREE?MobileBertSquad%20%5Bfp32%5D%20(TFLite)%20little-core%2Cfull-inference%2Cexperimental-flags%20with%20IREE-LLVM-CPU-Sync%20%40%20Pixel-6-Pro%20(CPU-ARMv8.2-A) 17%+
* https://perf.iree.dev/serie?IREE?MobileNetV2%20%5Bfp32%2Cimagenet%5D%20(TFLite)%20little-core%2Cfull-inference%2Cexperimental-flags%20with%20IREE-LLVM-CPU-Sync%20%40%20Pixel-6-Pro%20(CPU-ARMv8.2-A) 11%+
* ...

This is likely intended behavior though? @hanhanW please advise. We should mark those as intended behavior if so.

**Comment by hanhanW** [comment]
Based on the discussion in the PR, we can mark them as intended behavior.

https://github.com/openxla/iree/pull/11411#issuecomment-1338001806

**Comment by benvanik** [comment]
I wasn't expecting such large regressions to last until march - what's the ETA? (fix forward only works if you fix :)

**Comment by benvanik** [comment]
oh, are these just the experimental flags ones? that's ok then - and ugh we should bucket those separately - the names on those benchmarks are extremely unergonomic ;(

**Comment by antiagainst** [comment]
> oh, are these just the experimental flags ones? that's ok then - and ugh we should bucket those separately - the names on those benchmarks are extremely unergonomic ;(

Complaints heard! Let's at least have separate entry points in the sidebar for deafult/experiemental ones then. :)

**Comment by antiagainst** [comment]
The Web UI is now splitting default flagged ones vs experimental ones.

**Comment by antiagainst** [comment]
I've marked those series as intended. So closing this one.
