### ISSUE TITLE
LLVM integration causes x86_64 latency regressions

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#12329]
LLVM integration https://github.com/openxla/iree/commit/1290401bd7c02c4ac35d5689c278d9c32665e6a0 (2023-02-16) causes latency regression on 

* EfficientNetV2STF https://perf.iree.dev/serie?IREE?bd39009584dcea45606af9a0f73380027510eebdb51d46c0391a527b032459ad 10%+
* Resnet50TF https://perf.iree.dev/serie?IREE?e496c2ea8de7fdffdb7597da63eed12cc5fb0595605d70e1f9d67a33857a299a 12%+
* BertForMaskedLMTF https://perf.iree.dev/serie?IREE?8cf9c331c7ec9e59884fe37b1a6e4326edc902e749daa2ad5f873c0b5433051b 9%+
* EfficientNetV2STF  https://perf.iree.dev/serie?IREE?974086586c080164bf56972646f76a8f116cd849d51713ca3d9b380366c8d305 8%
* Resnet50TF https://perf.iree.dev/serie?IREE?2cbf22689ea9dd3ac54c3a66da0fed845f3314f5ca96afef57c7e3697409536a 7.5%+
* BertForMaskedLMTF https://perf.iree.dev/serie?IREE?fe3b81659dda02e5b75d72c813626309b9c44232a5d23a7be79cc1320921add6 6%+
* ...

![image](https://user-images.githubusercontent.com/75337/220799232-a3bbc0cf-2b54-4ace-ac61-07bb1b4395ac.png)

**Comment by antiagainst** [comment]
Assigning to @dcaballe to route the issue for now..

**Comment by hanhanW** [comment]
I'm not sure if I reproduced it successfully or not.. it's quite noisy. It looks like we have regressions on convolution kernels:

Before integrate:

![image](https://user-images.githubusercontent.com/6949191/223907081-5396dd84-588c-46bd-9630-7c03401c2b29.png)

After integrate:

![image](https://user-images.githubusercontent.com/6949191/223907156-fabb867b-0204-4f55-b12a-d4777e74a453.png)

**Comment by pzread** [comment]
To help reproduce, this is how CI compiles and runs Resnet50TF:

```
Run:
  iree-benchmark-module --module=module.vmfb --function=forward --input=1x224x224x3xf32=0 --device_allocator=caching --device=local-sync

Compile:
  iree-compile iree_Resnet50TF_a122dabcac56c201a4c98d3474265f15adba14bff88353f421b1a11cadcdea1f.mlir --iree-hal-target-backends=llvm-cpu --iree-input-type=mhlo --iree-llvm-target-triple=x86_64-unknown-linux-gnu --iree-llvm-target-cpu=cascadelake
```

**Comment by hanhanW** [comment]
This is very weird. The IR dump before and after the integrate are identical. @pzread is there a way to get the Resnet50TF mlir file used by https://github.com/openxla/iree/commit/a04c262e54816a3e7d34e76df76510ce6324803e and https://github.com/openxla/iree/commit/1290401bd7c02c4ac35d5689c278d9c32665e6a0 ?

**Comment by hanhanW** [comment]
I found the buildkite link, I can dump some artifacts from it.

**Comment by hanhanW** [comment]
I can reproduce the regression with the artifacts on buildkite. I can't reproduce it if I compile the module myself. Probably we have different setup for building IREE?

**Comment by hanhanW** [comment]
Found other weird things.

This is the buildkite build before integrate: https://buildkite.com/iree/iree-benchmark-linux/builds/3056#_

This is the buildkite build after integrate: https://buildkite.com/iree/iree-benchmark-linux/builds/3057#_

The iree-compile binaries from iree-host-tools are identical. Did I do something wrong? @pzread could you help check it?

**Comment by pzread** [comment]
Besides the iree-compile, I also see all VMFB modules for TF models and iree-benchmark-module are the same from the two commits on buildkite. I built the Resnet50TF with two commits locally and surprisingly also got the same VMFBs.

We switched the x86_64 benchmark machines (from Ubuntu 20.04 to 22.04) at that integration commit and due to #11884, some benchmarks have regressions because of that (already marked some of them as intended for the cases we are sure about)

If we see the VMFB modules and `iree-benchmark-module` are the same in these regressions and they run at similar performance locally, I think it might be safe to conclude that they are also affected by #11884 and can be closed.

**Comment by hanhanW** [comment]
I just checked the VMFB files, they are identical. Closing the issue since they are affected by machines switching.

Thanks for helping on this, @pzread !

**Comment by antiagainst** [comment]
Nice, thanks @hanhanW and @pzread! I'll mark these as intended in the dashboard then.

**Comment by antiagainst** [comment]
Ha, it's already done. :)
