### ISSUE TITLE
Noisy x86_64 latency benchmarks that need adjusting flagging threshold

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#12330]
There are a few x86_64 benchmarks having their numbers fluctuate a lot. We should consider changing their flagging threshold to avoid always being confusing to folks looking at the dashboard:

* MobileNetV2_fp32  https://perf.iree.dev/serie?IREE?6272e089c33b7c5333b6188b6f61fbb15e7b6a0e9fcd9d54b3b7271cd730e0da
* PoseNet https://perf.iree.dev/serie?IREE?51181aae886260ff3c24d829e8bf9e3a892aa93305321c1012476aace79f9e65
* MobileSSD https://perf.iree.dev/serie?IREE?d15406ab9fa52f130a4947059f1616c6ee94c1c2b36a6078ec708d475556a9a4
* MobileBert https://perf.iree.dev/serie?IREE?4d92c9901b7c73d8e02e63adfdcdf63ef0fb529360a908f93b888dee1c3f9c31
* MobileNetV1 https://perf.iree.dev/serie?IREE?175234258abc061d624fad12b5f814c63c5031f71d59e1bafa0df468cb756f38
* ...

Some of them are just because one inference latency is small so that 5% is not a good threshold. We could use absolute time as the flagging threshold too.

**Comment by antiagainst** [comment]
@dcaballe, @hanhanW, or @vmurali could you advise how to treat these? @pzread maybe able to help do the change accordingly.

**Comment by pzread** [comment]
I'm testing to use larger GCP machines to run x86_64 benchmarks, to see if they will give us more stable numbers

**Comment by dcaballe** [comment]
Something that could help, esp. for the multi-threading versions, is to make sure that the threads are always pinned to the same core and memory is allocated closer to that socket. I've been able to achieve that with `numacl --membind --cpunodebind` when using oneDNN but I haven't been able to achieve the same level of consistency with IREE yet. @benvanik pointed me to [these flags](https://github.com/google/iree/blob/main/runtime/src/iree/task/api.c/#L65-L95) but I haven't found the right configuration yet. Perhaps he can provide more specific details.

Something that would also help is https://github.com/openxla/iree/issues/12152
