### ISSUE TITLE
Support lowering of non-power of 2 MHLO FFT

### ISSUE THREAD

**Issue by jpienaar** [iree-org/iree#12335]
### Request description

Currently only powers of 2 supported for this op lowering.

### What component(s) does this issue relate to?

Frontends

**Comment by hanhanW** [comment]
I think it is a dup of https://github.com/openxla/iree/issues/12263. The other one has more context. Maybe we should close this one, and have better title for the other one.

**Comment by benvanik** [comment]
(probably right - "FFT" isn't a very useful issue title on that other one - think you can put a better one in so people can find it?)

**Comment by jpienaar** [comment]
Ah you are correct, I missed it. Yes it is, marking as closed and will retitle.
