### ISSUE TITLE
Add the linux nightly builder (~22min) to the pre-submit CI

### ISSUE THREAD

**Issue by powderluv** [iree-org/iree#12341]
### What happened?

Our nightly builds being shipped to end users use GCC10 + manylinux docker. 

We have failures such as https://discord.com/channels/689900678990135345/1078332034830835833 that can sometime compound. 

https://github.com/openxla/iree/actions/runs/4251432533 is an example of a CUDA toolkit failure hiding a Transform Dialect failure. 

Lets please add this to the pre-submit CI. Also we can reduce the 22min by just building for one Python version instead of 4/5 with

**Comment by benvanik** [comment]
+1 to a smoketest (not all the python versions)!
