### ISSUE TITLE
Error Compiling T5 PyTorch Model

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#12389]
### What happened?

When compiling the PyTorch model `T5-base`, I run into this error:

```
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
error: 'func.call' op operand type mismatch: expected operand type '!torch.float', but provided '!torch.number' for operand number 0
note: see current operation: %2092 = "func.call"(%1008, %2088, %2089, %2090, %2091) {callee = @__torch_mlir_shape_fn.aten.arange} : (!torch.number, !torch.optional<int>, !torch.optional<int>, !torch.optional<Device>, !torch.optional<bool>) -> !torch.list<int>
```

### Steps to reproduce your issue

Run: 

```
torch-mlir-opt -pass-pipeline='builtin.module(torchscript-module-to-torch-backend-pipeline{backend-legal-ops=torch.aten.flatten.using_ints})' ./t5.mlir
```

MLIR file: [t5.zip](https://github.com/openxla/iree/files/10836210/t5.zip)

### What component(s) does this issue relate to?

Frontends

### Version information

Torch-MLIR version 20230222.757
Torch version 2.0.0.dev20230212+cu117
IREE version 20230221.437

**Comment by silvasean** [comment]
This is a bug in Torch-MLIR. Can you file it at https://github.com/llvm/torch-mlir so that it can be addressed?

**Comment by mariecwhite** [comment]
Created https://github.com/llvm/torch-mlir/issues/1977
