### ISSUE TITLE
Implement PJRT_Executable_OptimizedProgram in PjRt Plugin

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#12407]
PJRT_Executable_OptimizedProgram is not implemented in the OpenXLA PjRt integration. Add a working implementation.

**Comment by allieculp** [comment]
@rsuderman - I assume 'in progress' by you?

**Comment by ramiro050** [comment]
Draft patch: https://github.com/openxla/openxla-pjrt-plugin/pull/147
XLA issue with some questions regarding this method: https://github.com/openxla/xla/issues/3282

**Comment by ramiro050** [comment]
Patch merged.
