### ISSUE TITLE
Implement  PJRT_Buffer_OnDeviceSizeInBytes in PjRt Plugin

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#12406]
PJRT_Buffer_OnDeviceSizeInBytes is not implemented in the OpenXLA PjRt integration. Add a working implementation.

**Comment by allieculp** [comment]
@rsuderman - I assume 'in progress' by you?

**Comment by ramiro050** [comment]
Made a patch fixing this: https://github.com/openxla/openxla-pjrt-plugin/pull/118

**Comment by ramiro050** [comment]
Patch has been merged.
