### ISSUE TITLE
Implement non-row major PJRT_Client_BufferFromHostBuffer in PJRT Plugin

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#12408]
PJRT_Client_BufferFromHostBuffer does not support non-row major ordering  in the OpenXLA PjRt plugin.
Expand the implementation to transfer alternative row orderings.

**Comment by aaron-schneider** [comment]
Please update on P0 issue, or perhaps lower to P1. P0 is meant for urgent interruptions and should be consistently updated. Thanks!

**Comment by rsuderman** [comment]
> Please update on P0 issue, or perhaps lower to P1. P0 is meant for urgent interruptions and should be consistently updated. Thanks!

Fixed and landed
https://github.com/openxla/openxla-pjrt-plugin/pull/38

**Comment by rsuderman** [comment]
Reopening and assigning to @ramiro050 as we know this is failing for some additional tests

**Comment by ramiro050** [comment]
Closing this since `PJRT_Client_BufferFromHostBuffer` uses `DeviceInstance::HostBufferToDevice` to copy to device, and `DeviceInstance::HostBufferToDevice` [now supports non-row major inputs](https://github.com/openxla/openxla-pjrt-plugin/pull/199).
