### ISSUE TITLE
Implement PJRT_Buffer_UnsafePointer in PjRt PlugIn

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#12404]
PJRT_Buffer_UnsaferPointer is not implemented in the OpenXLA PjRt integration. Add a working implementation.

**Comment by allieculp** [comment]
@rsuderman - I assume 'in progress' by you?

**Comment by ramiro050** [comment]
Patch: https://github.com/openxla/openxla-pjrt-plugin/pull/130

**Comment by ramiro050** [comment]
Patch merged.
