### ISSUE TITLE
Lowering plan for  `mhlo.optimization_barrier`

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#12409]
`MHLO` has an optimization barrier designed to prevent fusion / optimization between operations. While
this serves no performance advantage we should respect it's design OR make a conscious choice to strip
these operations from JAX models.

**Comment by rsuderman** [comment]
We can lower to the Util::OptimizationBarrierOp https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Dialect/Util/IR/UtilOps.td#L308

**Comment by jpienaar** [comment]
Fixed #12963
