### ISSUE TITLE
commit 5c78e87 causes big regression on generated library size

### ISSUE THREAD

**Issue by lundong** [iree-org/iree#12431]
### What happened?

The commit 5c78e87 (https://github.com/openxla/iree/commit/5c78e870a80620256ac73f0d83ac07b262bddf25) has caused big regression on generated static/dynamic library size. This regression seems to be applicable for models without the fused op of RELU.

### Steps to reproduce your issue

Use a simple mobilenet_v1 model as an example.
1. Download and unzip the attached mobilenet_v1.mlir.
2. Build IREE based on commit 49de0b6b (the commit right before 5c78e87).
3. Generate static library via iree-compile:

/path/to/iree-compile -iree-input-type=tosa -iree-hal-target-backends=llvm-cpu --iree-llvm-debug-symbols=false --iree-vm-bytecode-module-strip-source-map=true --iree-vm-emit-polyglot-zip=false --iree-llvm-link-embedded=false --output-format=vm-bytecode --iree-llvm-link-static --iree-llvm-static-library-output-path=/tmp/mobilenet_v1_static.o /path/to/mobilenet_v1.mlir -o /tmp/mobilenet_v1.vmfb

4. Generate dynamic library via iree-compile:

/path/to/iree-compile -iree-input-type=tosa -iree-hal-target-backends=llvm-cpu --iree-llvm-keep-linker-artifacts --iree-llvm-embedded-linker-path=/path/to/lld /path/to/mobilenet_v1.mlir -o /tmp/mobilenet_v1.vmfb

5. See generated library size:

static:  mobilenet_v1_static.o 948KB
dynamic:  mobilenet_v1_0_25_224_quant_linked_llvm_cpu-xxxxxx.so   864KB

6. repeat the above steps 2 - 4, but build IREE based on commit 5c78e87 and see generated library size

static:  mobilenet_v1_static.o 1.6MB
dynamic:  mobilenet_v1_0_25_224_quant_linked_llvm_cpu-xxxxxx.so   1.3MB

Clearly there is a big regression.

[mobilenet_v1.zip](https://github.com/openxla/iree/files/10855815/mobilenet_v1.zip)

### What component(s) does this issue relate to?

Compiler

### Version information

IREE release since commit 5c78e870a80620256ac73f0d83ac07b262bddf25.

**Comment by lundong** [comment]
@MaheshRavishankar @hcindyl

**Comment by MaheshRavishankar** [comment]
Thanks for reporting. I'll take a look sometime tomorrow. Please ping again if you don't hear back from me

**Comment by MaheshRavishankar** [comment]
Did a bit of digging, definitely there is a change, but it might be triggering badness in the backend LLVM compiler rather than an IREE issue. 

This is the IR after dispatch formation and lowering to LLVM before the change https://gist.github.com/MaheshRavishankar/8ecf5be165f10dc9f5bd5aa926290f62

This is the IR after dispatch formation and lowering to LLVM after the change
https://gist.github.com/fda89085bff12894630e0c849ebcef50

There is not much difference between the two. Actually even the `.vmfb` file I get is not that different

```
-rw-r-----  1 ravishankarm primarygroup  489472 Mar  3 21:13 mobilenet_v1.after.vmfb
-rw-r-----  1 ravishankarm primarygroup  489600 Mar  3 21:12 mobilenet_v1.before.vmfb
```

**Comment by hcindyl** [comment]
Did you fallow the CLI in step 3 or step 4? Please note for step 3 a static LLVM library `.o` is created and _not_ embedded into vmfb, so there is no or minor size change in vmfb, whereas in step 4 the device distpatch .so is embedded with the vmfb. 

At 5c78e87, the linked artifact `mobilenet_v1_0_25_224_quant_linked_llvm_cpu-xxxxxx.so` itself is already at 1.2MB, where as at 49de0b6 it was 835kB.

**Comment by MaheshRavishankar** [comment]
THis is the command I used 

```
~/iree/build_debug/tools/iree-compile -iree-input-type=tosa -iree-hal-target-backends=llvm-cpu --iree-llvm-debug-symbols=false --iree-vm-bytecode-module-strip-source-map=true --iree-vm-emit-polyglot-zip=false --iree-llvm-link-embedded=false --outpu\
t-format=vm-bytecode --iree-llvm-link-static --iree-llvm-static-library-output-path=mobilenet_v1_static.after.o mobilenet_v1.mlir -o mobilenet_v1.after.vmfb
```

Either way, I dont see any major changes in codegen (directly attributable to that change) that can cause a big regression in IREE... I suspect this is a downstream LLVM issue?

**Comment by benvanik** [comment]
Maybe another autovectorizer thing?

**Comment by hcindyl** [comment]
Thanks for providing the CLI. In this CLI, the device workload dispatch is in `mobilenet_v1_static.after.o`, and you can see the size of that library grows dramatically.

at 5c78e87 
1612624 mobilenet_v1_bytecode_module_static.o

at 49de0b6
948000  mobilenet_v1_bytecode_module_static.o

**Comment by lundong** [comment]
FYI, I just did another experiment.

if I checkout the IREE commit 5c78e87, but manually cherry-pick to revert the change in compiler/src/iree/compiler/Dialect/Flow/Transforms/FormDispatchRegions.cpp, then after rebuilding IREE, the regression would be gone. 

During this experiment, no other changes were made and all submodule versions stay the same.

**Comment by benvanik** [comment]
Can use `--iree-hal-dump-executable-sources-to=` if you want narrow down which dispatch it is; untested example but you get the idea:
```
iree-compile some_input.mlir -o ignored.mlir \
    --iree-hal-target-backends=llvm-cpu \
    --iree-hal-dump-executable-sources-to=sources/ | \
  ls -1 sources/ | xargs -i sh -c "iree-compile sources/{} --compile-mode=hal-executable -o {}.so"
```
that'll produce one .so per dispatch so you can see which ones are growing.

**Comment by MaheshRavishankar** [comment]
> Maybe another autovectorizer thing?

autovectorizer is turned off. If its loop unrolling, that might be a thing....

**Comment by hcindyl** [comment]
> iree-compile some_input.mlir -o ignored.mlir \
>     --iree-hal-target-backends=llvm-cpu \
>     --iree-hal-dump-executable-sources-to=sources/ | \
>   ls -1 sources/ | xargs -i sh -c "iree-compile sources/{} --compile-mode=hal-executable -o {}.so"

Cannot run the intermediate output with the CLI :(

```
/usr/local/google/home/hcindyl/Projects/iree-dev/iree/build-host/install/bin/iree-compile sources/module_main_dispatch_1.mlir --compile-mode=hal-executable  -o module_main_dispatch_1.mlir.so
Please report issues to https://github.com/openxla/iree/issues and include the crash backtrace.
Stack dump:
0.	Program arguments: /usr/local/google/home/hcindyl/Projects/iree-dev/iree/build-host/install/bin/iree-compile sources/module_main_dispatch_1.mlir --compile-mode=hal-executable -o module_main_dispatch_1.mlir.so
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libIREECompiler.so.0 0x00007fcee24c4917
1  libIREECompiler.so.0 0x00007fcee24c287e
2  libIREECompiler.so.0 0x00007fcee24c4faa
3  libc.so.6            0x00007fceda45af90
4  libIREECompiler.so.0 0x00007fcee23c3606
5  libIREECompiler.so.0 0x00007fcedd0f63f3
6  libIREECompiler.so.0 0x00007fcedd0ef202 ireeCompilerInvocationOutputHALExecutable + 274
7  libIREECompiler.so.0 0x00007fcedd0e96f5
8  libIREECompiler.so.0 0x00007fcedd0e9391
9  libc.so.6            0x00007fceda44618a
10 libc.so.6            0x00007fceda446245 __libc_start_main + 133
11 iree-compile         0x0000555a5acf4721
Segmentation fault
```

**Comment by lundong** [comment]
I was able to run Ben's CLI, and have nailed down the specific .so dispatch that causes this regression.

problematic dispatch: module_main_dispatch_113.mlir.so
The size grew from 3.9kB to 461.3kB.

The relevant mlir and dispatch files are attached.
[dispatches.zip](https://github.com/openxla/iree/files/10973345/dispatches.zip)

Note that I used the more recent commit 5a10e3c, and then manually reverted the change in commit 5c78e87 to compare the differences.

The CLI I used is  almost the same as Ben's above one, only with this flag "--iree-input-type=tosa" added.

@MaheshRavishankar : please go ahead to fix the issue with this updated info on the specific dispatch. Thanks very much.

**Comment by MaheshRavishankar** [comment]
> I was able to run Ben's CLI, and have nailed down the specific .so dispatch that causes this regression.
> 
> problematic dispatch: module_main_dispatch_113.mlir.so The size grew from 3.9kB to 461.3kB.
> 
> The relevant mlir and dispatch files are attached. [dispatches.zip](https://github.com/openxla/iree/files/10973345/dispatches.zip)
> 
> Note that I used the more recent commit [5a10e3c](https://github.com/openxla/iree/commit/5a10e3c85e99f8904ec822baa5e14f28f3446e27), and then manually reverted the change in commit [5c78e87](https://github.com/openxla/iree/commit/5c78e870a80620256ac73f0d83ac07b262bddf25) to compare the differences.
> 
> The CLI I used is almost the same as Ben's above one, only with this flag "--iree-input-type=tosa" added.
> 
> @MaheshRavishankar : please go ahead to fix the issue with this updated info on the specific dispatch. Thanks very much.

This is the same dispatch that I saw earlier. Now this is fused and before it wasnt.... But if you actually generate the LLVM IR for the dispatch with the change, it looks reasonable.... (at least it was last I checked). I can take a look again, but like I said earlier it seems to be triggering something in the LLVM -> RISC-V lowering that is causing the blowup.. Let me verify this though....

**Comment by lundong** [comment]
> > I was able to run Ben's CLI, and have nailed down the specific .so dispatch that causes this regression.
> > problematic dispatch: module_main_dispatch_113.mlir.so The size grew from 3.9kB to 461.3kB.
> > The relevant mlir and dispatch files are attached. [dispatches.zip](https://github.com/openxla/iree/files/10973345/dispatches.zip)
> > Note that I used the more recent commit [5a10e3c](https://github.com/openxla/iree/commit/5a10e3c85e99f8904ec822baa5e14f28f3446e27), and then manually reverted the change in commit [5c78e87](https://github.com/openxla/iree/commit/5c78e870a80620256ac73f0d83ac07b262bddf25) to compare the differences.
> > The CLI I used is almost the same as Ben's above one, only with this flag "--iree-input-type=tosa" added.
> > @MaheshRavishankar : please go ahead to fix the issue with this updated info on the specific dispatch. Thanks very much.
> 
> This is the same dispatch that I saw earlier. Now this is fused and before it wasnt.... But if you actually generate the LLVM IR for the dispatch with the change, it looks reasonable.... (at least it was last I checked). I can take a look again, but like I said earlier it seems to be triggering something in the LLVM -> RISC-V lowering that is causing the blowup.. Let me verify this though....

Just a quick comment: the backend is llvm-cpu for x86_64 target, not Risc-V.

**Comment by MaheshRavishankar** [comment]
> > > I was able to run Ben's CLI, and have nailed down the specific .so dispatch that causes this regression.
> > > problematic dispatch: module_main_dispatch_113.mlir.so The size grew from 3.9kB to 461.3kB.
> > > The relevant mlir and dispatch files are attached. [dispatches.zip](https://github.com/openxla/iree/files/10973345/dispatches.zip)
> > > Note that I used the more recent commit [5a10e3c](https://github.com/openxla/iree/commit/5a10e3c85e99f8904ec822baa5e14f28f3446e27), and then manually reverted the change in commit [5c78e87](https://github.com/openxla/iree/commit/5c78e870a80620256ac73f0d83ac07b262bddf25) to compare the differences.
> > > The CLI I used is almost the same as Ben's above one, only with this flag "--iree-input-type=tosa" added.
> > > @MaheshRavishankar : please go ahead to fix the issue with this updated info on the specific dispatch. Thanks very much.
> > 
> > 
> > This is the same dispatch that I saw earlier. Now this is fused and before it wasnt.... But if you actually generate the LLVM IR for the dispatch with the change, it looks reasonable.... (at least it was last I checked). I can take a look again, but like I said earlier it seems to be triggering something in the LLVM -> RISC-V lowering that is causing the blowup.. Let me verify this though....
> 
> Just a quick comment: the backend is llvm-cpu for x86_64 target, not Risc-V.

Understood. I am not saying it is specific to RISC-V. I am saying this seems to be triggering badness in LLVM itself.

**Comment by MaheshRavishankar** [comment]
#12639 gets us back to the size of the binary before the commit flagged here. I dont really want to submit it, but it is an option.

**Comment by hcindyl** [comment]
If possible, we can toggle the two modes behind a flag. As we discuss offline, this class of models is unique in no RELU in the `fused_activation_function` field, so they may be the special case that needs a deeper look.

**Comment by MaheshRavishankar** [comment]
ok, if flag is an option that would be great. I was  planning to look at the LLVM IR. If I can narrow it down do you think there is someone who can chase this down in LLVM itself?

**Comment by hcindyl** [comment]
If it is a bad interaction with the auto vectorization, maybe @dcaballe is most knowledgeable about this?

**Comment by MaheshRavishankar** [comment]
> If it is a bad interaction with the auto vectorization, maybe @dcaballe is most knowledgeable about this?

We dont use auto-vectorization. I am almost convinced it has to do with LLVM loop unrolling.

**Comment by MaheshRavishankar** [comment]
@hcindyl or @lundong can you try #12661 . That seems to fix the issue as well and I can land that one.

**Comment by MaheshRavishankar** [comment]
> @hcindyl or @lundong can you try #12661 . That seems to fix the issue as well and I can land that one.

I checked locally and it did help but would be good for you guys to verify

**Comment by lundong** [comment]
> > @hcindyl or @lundong can you try #12661 . That seems to fix the issue as well and I can land that one.
> 
> I checked locally and it did help but would be good for you guys to verify

@MaheshRavishankar I can confirm that #12661 does fix the issue.

**Comment by hcindyl** [comment]
Working on https://github.com/openxla/iree/pull/12690 to add regression coverage.
