### ISSUE TITLE
Add ability to measure peak memory usage in SHARK

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#12449]
### Request description

This includes memory usage for IREE, PyTorch and TF.

**Comment by ScottTodd** [comment]
Can SHARK issues be tracked in SHARK? It isn't clear how this issue relates to IREE itself.

**Comment by allieculp** [comment]
@mariecwhite Any update?

**Comment by mariecwhite** [comment]
Phoenix has added some support to SHARK. @phoenix-meadowlark is this considered complete?

**Comment by phoenix-meadowlark** [comment]
I think we can consider it complete for our current purposes! Support for measuring framework memory usage on CPU is missing, but that's not currently prioritized.
