### ISSUE TITLE
Add ability to use a version of Tensorflow built from source

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#12453]
### Request description

SHARK currently uses TF releases when benchmarking XLA. Releases happen quarterly and we require benchmark results on a monthly cadence that ideally uses the latest XLA updates. We need to be able to benchmark against TF head.

### What component(s) does this issue relate to?

Other

**Comment by ScottTodd** [comment]
This doesn't look to be related to IREE itself. Move to another repo?
