### ISSUE TITLE
Benchmark models with varying batch sizes nightly

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#12452]
### Request description

Batch sizes of interest: 1, 8, 16, 32, 64, 128, 256, 512 and 1024. Not all models will support higher batch sizes due to OOM.

### What component(s) does this issue relate to?

Other

**Comment by ScottTodd** [comment]
Not sure what this issue is tracking specifically. Maybe move to https://github.com/openxla/openxla-benchmark or another repo?
