### ISSUE TITLE
Add ability to measure compilation time

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#12450]
### Request description

This includes compilation time for IREE, PyTorch and TF.

### What component(s) does this issue relate to?

Other

**Comment by jpienaar** [comment]
What does the current tracing not provide here?

**Comment by ScottTodd** [comment]
Not enough info in this issue, so closing for now. We have some compilation time tracking on perf.iree.dev: https://perf.iree.dev/IREE/default-compilation-time-series. Can help with pointers for how that data is extracted if there is a specific request.

Maybe open a separate issue in https://github.com/openxla/openxla-benchmark if that was the intent?

**Comment by ScottTodd** [comment]
Oh, I see the `infrastructure/shark` label. Maybe track in SHARK-Turbine or elsewhere then?
