### ISSUE TITLE
Fix TF GPU Memory Allocation Issue

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#12456]
### Request description

When running Tensorflow with GPU, it allocates 90% of the GPU memory and does not release it until the process it is running on shuts down. This becomes a problem when benchmarking both TF and IREE on GPU because there is no GPU memory left for IREE to run. We need to isolate TF GPU benchmarking into its own process and propagate errors to the parent SHARK process.

### What component(s) does this issue relate to?

Other

**Comment by ScottTodd** [comment]
This doesn't look to be related to IREE itself. Move to another repo?
