### ISSUE TITLE
`TileAndDistributeToWorkgroupsPass` Crashing

### ISSUE THREAD

**Issue by vivekkhandelwal1** [iree-org/iree#12468]
### What happened?

Hi, the `TileAndDistributeToWorkgroupsPass` for the following IR: https://gist.github.com/8dc22faacf58d923d632ea960d3e308f, with the following stack trace: https://gist.github.com/b8a80225ecd419ee3860deb04b0a5687.

### Steps to reproduce your issue

To reproduce the issue, compile the following IR: https://gist.github.com/8dc22faacf58d923d632ea960d3e308f, with the following command:
```
./build/tools/iree-compile --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=cuda --iree-llvm-embedded-linker-path=/home/vivek/work/02_07/vivekkhandelwal1-iree/build/compiler/bindings/python/iree/compiler/_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs reproducible.mlir -o crash.vmfb
```

### What component(s) does this issue relate to?

Compiler

### Version information

git commit hash: `d6f8f151bd633a586d5afecf88bd8c64ea96f16c`

**Comment by vivekkhandelwal1** [comment]
@ThomasRaoux PTAL at this issue.

**Comment by vivekkhandelwal1** [comment]
Hi @ThomasRaoux, any update on this issue?

**Comment by ThomasRaoux** [comment]
Fix under review

**Comment by vivekkhandelwal1** [comment]
> Fix under review

Thanks!

**Comment by ThomasRaoux** [comment]
@MaheshRavishankar could you please help us land the fix or suggest something else? Thanks

**Comment by MaheshRavishankar** [comment]
This seems fine https://github.com/openxla/iree/pull/12558 . Is there an issue there?

**Comment by ThomasRaoux** [comment]
> This seems fine #12558 . Is there an issue there?

No issue, if this is fine then we can just lands this.

**Comment by ThomasRaoux** [comment]
looks like #12558 doesn't any obvious performance regressions, @MaheshRavishankar do you want to stamp it then?
