### ISSUE TITLE
Shark Tank nightly runs using wrong version of IREE?

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#12485]
It looks like the version used in our Shark Tank nightly runs is stuck at `20230221.437`. For example, this is [today's](https://pantheon.corp.google.com/storage/browser/shark-benchmark-artifacts/2023-03-02.sha_23f1.timestamp_1677762597;tab=objects?pageState=(%22StorageObjectListTable%22:(%22s%22:%5B(%22i%22:%22displayName%22,%22s%22:%221%22)%5D,%22f%22:%22%255B%255D%22))&project=iree-oss&prefix=&forceOnObjectsSortingFiltering=false) nightly run and there is a `cpu_iree_20230221.437.csv` file and `version_info.txt` says `iree=20230221.437`.

**Comment by GMNGeoffrey** [comment]
My guess is that it's not set to install pre-releases and `20230221.437` was the stable release at the time it ran. See https://pip.pypa.io/en/stable/cli/pip_install/#pre-release-versions

**Comment by mariecwhite** [comment]
SHARK tank is pointing to https://openxla.github.io/iree/pip-release-links.html and the latest version published on that page is the 20230221. Is there a separate URL for pre-releases?

**Comment by mariecwhite** [comment]
The workflow has been failing for a week: https://github.com/openxla/iree/actions/workflows/publish_website.yml

**Comment by mariecwhite** [comment]
@GMNGeoffrey can you take a look?

**Comment by GMNGeoffrey** [comment]
Ugh, it looks like during the repo migration GitHub deleted the branch protection setting that allowed `iree-github-actions-bot` to push to the `gh-pages` branch. I've restored that and rerun the website publication workflow. Also very annoying that we don't have any failure notifications 😕

**Comment by GMNGeoffrey** [comment]
The rerun was successful and the release links page has been updated.
