### ISSUE TITLE
Failure to legalize tm_tensor.scatter

### ISSUE THREAD

**Issue by gpetters94** [iree-org/iree#12504]
### What happened?

Compiling Stable Diffusion with iree-compile (and attention slicing enabled) outputs

```
<eval_with_key>.8:185:12: error: failed to legalize operation 'tm_tensor.scatter' that was explicitly marked illegal
<unknown>:0: error: Failures have been detected while processing an MLIR pass pipeline
<unknown>:0: note: Pipeline failed while executing [`mlir::iree_compiler::IREE::HAL::{anonymous}::ConvertToHALPass` on 'builtin.module' operation]: reproducer generated at `iree-tmp/core-reproducer.mlir`
```

### 

### Steps to reproduce your issue

1. Run `cat core-reproducer.mlir | /home/gap/code/SHARK/venv/lib/python3.11/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=cuda --iree-llvm-embedded-linker-path=/home/gap/code/SHARK/venv/lib/python3.11/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --mlir-pass-pipeline-crash-reproducer=iree-tmp/core-reproducer.mlir --iree-llvm-target-cpu-features=host --iree-hal-cuda-disable-loop-nounroll-wa --iree-hal-cuda-llvm-target-arch=sm_80 --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs --iree-preprocessing-pass-pipeline='builtin.module(func.func(iree-flow
-detach-elementwise-from-named-ops,iree-flow-convert-1x1-filter-conv2d-to-matmul,iree-preprocessing-convert-conv2d-to-img2col,iree-preprocessing-pad-linalg-ops{pad-size=16}))'`

### What component(s) does this issue relate to?

MLIR

### Version information

20230302.322

### Additional context

This is produced for both cuda and vulkan on an Nvidia A100

**Comment by gpetters94** [comment]
[Here](https://gist.github.com/gpetters94/2591f2ec2738b5762f1307f04da28637) is the mlir file

**Comment by ThomasRaoux** [comment]
The command line seems wrong, don't you need `--iree-input-type=tm_tensor`?

**Comment by ThomasRaoux** [comment]
It compiles fine with `--iree-input-type=tm_tensor` for me. Could you please verify and close the issue if this is the case?

**Comment by gpetters94** [comment]
That does fix it, odd that it was set to `none`.
