### ISSUE TITLE
In f64 to f32 pass: support complex dtypes

### ISSUE THREAD

**Issue by pashu123** [iree-org/iree#12521]
### What happened?

Currently, the IR fails in the `iree-util-demote-f64-to-f32` not taking into account complex dtype.

The part of the failed IR looks like 

```
      %8 = "tensor.extract"(%arg0, %4, %5, %6, %7, %1) : (tensor<1x6x32x64x2xf32>, index, index, index, index, index) -> f32 loc(#loc12)
      %9 = "tensor.extract"(%arg0, %4, %5, %6, %7, %0) : (tensor<1x6x32x64x2xf32>, index, index, index, index, index) -> f32 loc(#loc13)
      %10 = "complex.create"(%8, %9) : (f32, f32) -> complex<f64> loc(#loc14)
```
It should also have demoted the `complex<f64>` to `complex<f32>` dtype or shouldn't have applied the rewrite at all.

### Steps to reproduce your issue

Original Linalg IR: 
```
#map = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
module {
  func.func @forward(%arg0: tensor<1x6x32x64x2xf32>) -> tensor<1x6x32x64xcomplex<f64>> {
    %c1 = arith.constant 1 : index
    %c0 = arith.constant 0 : index
    %0 = tensor.empty() : tensor<1x6x32x64xcomplex<f64>>
    %1 = linalg.generic {indexing_maps = [#map], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} outs(%0 : tensor<1x6x32x64xcomplex<f64>>) {
    ^bb0(%out: complex<f64>):
      %2 = linalg.index 0 : index
      %3 = linalg.index 1 : index
      %4 = linalg.index 2 : index
      %5 = linalg.index 3 : index
      %extracted = tensor.extract %arg0[%2, %3, %4, %5, %c0] : tensor<1x6x32x64x2xf32>
      %extracted_0 = tensor.extract %arg0[%2, %3, %4, %5, %c1] : tensor<1x6x32x64x2xf32>
      %6 = arith.extf %extracted : f32 to f64
      %7 = arith.extf %extracted_0 : f32 to f64
      %8 = complex.create %6, %7 : complex<f64>
      linalg.yield %8 : complex<f64>
    } -> tensor<1x6x32x64xcomplex<f64>>
    return %1 : tensor<1x6x32x64xcomplex<f64>>
  }
}
```

Compile Command: 
`iree-compile  --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false  -iree-llvm-target-triple=x86_64-linux-gnu --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs ~/above_ir.mlir`

**Comment by MaheshRavishankar** [comment]
I dont have any idea about this pass. Ben added him, but I dont want to assign this to him since he is overloaded. It'd be great if someone from Nod can pick it up, I am starting from scratch on this anyway, so it would be the same for anyone else.

**Comment by powderluv** [comment]
This is required for LLaMA to run via IREE

**Comment by jpienaar** [comment]
We can look at it integrations side.

**Comment by jpienaar** [comment]
(of course agreed with Mahesh if someone Nod side can and we can review, just meaning it's not on Ben)

**Comment by benvanik** [comment]
Thanks @jpienaar!
