### ISSUE TITLE
RISC-V multi-core computation

### ISSUE THREAD

**Issue by hahayeong** [iree-org/iree#12536]
I am working on a RISC-V architecture ML chip that has many cores. IREE is used to enable ML models on my chip. However, I am not sure if multi-core is supported in RISC-V. 

I find `--task-topology_group_count=1` in the CMake code. Does this indicate the number of threads or cores? If not, which file should be modified to add these features?

Does anyone have some ideas?

Thanks so much!

**Comment by dcaballe** [comment]
Hi @hahayeong,

`task_topology_group_count` refers to the number of threads. I've been using it on RISC-V. You can use it with `iree-benchmark-module` or any other runner tools (e.g, `iree-run-mlir`, iree-run-module`, etc.).

Feel free to reach out if you have any other questions!
Diego

**Comment by hahayeong** [comment]
Hi @dcaballe ,

Thanks so much for your swift reply. 

As my RISC-V chip will have many cores to run threads that are designed to achieve parallel computations of matrix multiplications, may I know if I need to implement this part by myself or if the current IREE has supported the multi-thread matrix multiplications?

Btw, I am also if there is a max limit for `task_topology_group_count`, as my designed chip has hundreds of cores (similar to CUDA cores).

Best,
Yeong

**Comment by benvanik** [comment]
The task system is for coarse-grained workgroups on a reasonable number of workers. If you're on 2 to 64 big cores (or multiple sets of those on independent NUMA nodes) then our task system should work fine. If you're doing low-level dispatch where you control interrupts/scheduling/etc on hundreds+ cores then you're going to have to build that yourself as it gets very hardware/platform dependent. There may be some reusable components in there but it'll end up much easier to debug/tune if that fine-grained scheduling is handled by you - you don't want to be using any kind of syscalls to manage thousands of threads :)

**Comment by hahayeong** [comment]
Hi @benvanik ,

Thanks a lot! I will try to use IREE first, and extend it for my hardware.

Best,
Yeong

**Comment by TCHeish** [comment]
Hi @benvanik ,
Does IREE Python binding support multi-threads setting?
I use `local-task` driver and pass it to [load_vm_flatbuffer_file](https://github.com/openxla/iree/blob/15c306fc1d397d690433cfa5405a3e6b968b3390/runtime/bindings/python/iree/runtime/system_api.py#L320) API but it barely speeds up. (compare #1 core vs #4 core, etc.)
