### ISSUE TITLE
e2e_matmul_mmt4d_i8 test failure on Android devices after LLVM integration

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#12546]
After https://github.com/openxla/iree/commit/d015bbc5f1e0c6b117e5e1fbbbf8f42c381e09fb, we started to see [test failures](https://buildkite.com/iree/iree-test-android/builds/8439#0186b5dd-2de9-450b-ab41-acdddd40d778/488-1677) on all Android phones:

```
The following tests FAILED:
27 - iree/tests/e2e/matmul/e2e_matmul_mmt4d_i8_small_llvm-cpu_local-task_dotprod_on_android_device (Failed)
35 - iree/tests/e2e/matmul/e2e_matmul_mmt4d_i8_intrinsics_small_llvm-cpu_local-task_dotprod_on_android_device (Failed)
```

**Comment by bjacob** [comment]
Thanks for flagging, I'll bisect tomorrow if Hanhan doesn't beat me to it!  (EOD here).

**Comment by bjacob** [comment]
Bisection results are in...

```
benoitjacob@cloud:~/iree/third_party/llvm-project$ git bisect good
83bbd3fdbd75295669cf97967c38810d427c5c25 is the first bad commit
commit 83bbd3fdbd75295669cf97967c38810d427c5c25
Author: David Green <david.green@arm.com>
Date:   Wed Mar 1 13:54:03 2023 +0000

    [AArch64] Load into zero vector patterns
    
    A LDR will implicitly zero the rest of the vector, so vector_insert(zeros,
    load, 0) can use a single load. This adds tablegen patterns for both scaled and
    unscaled loads, detecting where we are inserting a load into the lower element
    of a zero vector.
    
    Differential Revision: https://reviews.llvm.org/D144086

 llvm/lib/Target/AArch64/AArch64InstrInfo.td        |  42 +++++
 llvm/test/CodeGen/AArch64/load-insert-zero.ll      | 172 +++++++--------------
 .../CodeGen/AArch64/speculation-hardening-loads.ll |   3 +-
 3 files changed, 97 insertions(+), 120 deletions(-)
```

**Comment by bjacob** [comment]
Confirmed that it's indeed
https://github.com/llvm/llvm-project/commit/83bbd3fdbd75295669cf97967c38810d427c5c25
https://reviews.llvm.org/D144086

**Comment by bjacob** [comment]
Minimized e2e regression testcase: #12556. Summary: it's in the codegen of the `tensor.pack` op doing the  packing+padding+transposing of the RHS.

**Comment by bjacob** [comment]
Attached testcase LLVM IR and good/bad generated aarch64 code at https://reviews.llvm.org/D144086 .

**Comment by bjacob** [comment]
Fixed upstream: https://github.com/llvm/llvm-project/commit/1c6ea961938488997712763762079e535b8b704e

**Comment by bjacob** [comment]
If we want to cherry-pick then we need this sequence of 4 commits:
https://github.com/llvm/llvm-project/commit/ae12e57a777f2287a656e17a6ce86ca6b86edb6e
https://github.com/llvm/llvm-project/commit/0847cc06a6c4feae5414f062141fbbd9b9aea4e0
https://github.com/llvm/llvm-project/commit/a10ac6554db4dee93232139d5c29f8d91ee01f3b
https://github.com/llvm/llvm-project/commit/1c6ea961938488997712763762079e535b8b704e

Maybe not worth it if the next integrate is already on the horizon?
