### ISSUE TITLE
Use opaque pointers in LLVM passes

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#12592]
We need to migrate, ideally before our LLVM integrate process catches up to the default change (https://github.com/llvm/llvm-project/commit/946f8030b58d3d6975369c1b8e047385b86c7ab0) and definitely before the support is fully removed from LLVM/MLIR (4 weeks from now).

Related (for LLVM, not MLIR): https://github.com/openxla/iree/issues/9319

See
* https://discourse.llvm.org/t/psa-in-tree-conversion-passes-can-now-be-used-with-llvm-opaque-pointers-please-switch-your-downstream-projects/68738
* https://discourse.llvm.org/t/psa-conversion-to-llvm-passes-now-emit-opaque-pointers-by-default/69125

We have uses of `LLVMTypeConverter` that are currently relying on the default of `options.useOpaquePointers = false;`, and many lit tests that use the typed pointer IR syntax (e.g. `!llvm.ptr<i32>` instead of `!llvm.ptr`).

We are definitely affected, as naively switching in `ConvertToLLVM.cpp` results in errors like this:
```
[build] D:/dev/projects/iree/tests/e2e/linalg/conv2d.mlir:2:13: error: 'llvm.insertvalue' op Type mismatch: cannot insert '!llvm.ptr<f32>' into '!llvm.struct<(ptr, ptr, i64, array<4 x i64>, array<4 x i64>)>'
[build]   %inputs = util.unfoldable_constant dense<[[[
[build]             ^
```

**Comment by ScottTodd** [comment]
@manishucsd was this fixed by https://github.com/openxla/iree/pull/12653, or is there still more work to do?

**Comment by ScottTodd** [comment]
Looks mostly fixed. The integrate PR missed a few opaque pointers in comments though: https://github.com/openxla/iree/blob/af4c377e392dc9f55f69b2f51c7b325fef7a1951/compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp#L89-L94 https://github.com/openxla/iree/blob/af4c377e392dc9f55f69b2f51c7b325fef7a1951/samples/custom_dispatch/cpu/embedded/example_hal.mlir#L132-L137

**Comment by allieculp** [comment]
@ScottTodd @manishucsd Is there more work to do here?

**Comment by manishucsd** [comment]
I only worked on it during llvm-integrate. 
@MaheshRavishankar helped me on it and my understanding that we can close it.

**Comment by ScottTodd** [comment]
Okay, let's close this then. Would still be nice to keep the documentation (comments) up to date when making mechanical changes though.
