### ISSUE TITLE
Inline HAL compilation fails on VMVX backend

### ISSUE THREAD

**Issue by lundong** [iree-org/iree#12620]
### What happened?

 inline-static compilation have failed on vmvx-inline backend since commit e6425d6.

The description on commit e6425d6 mentioned that inline-dynamic support was not yet available. But actually inline-dynamic (llvm-cpu backend) worked fine and inline-static (vmvx-inline backend) didn't work. Need to clarify this inconsistency or fix this issue.

### Steps to reproduce your issue

1. Build IREE based on commit e6425d6
2. Inline HAL compilation
path/to/iree-compile --iree-input-type=mhlo --iree-hal-target-backends=vmvx-inline --iree-execution-model=inline-static /path/to/iree/samples/static_library/simple_mul.mlir
3. See error

Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libIREECompiler.so.0 0x00007f6d5c478177
1  libIREECompiler.so.0 0x00007f6d5c476540
2  libIREECompiler.so.0 0x00007f6d5c4787fa
3  libc.so.6            0x00007f6d5745af90
4  libIREECompiler.so.0 0x00007f6d5c2e6ab3
5  libIREECompiler.so.0 0x00007f6d5c2f045a
6  libIREECompiler.so.0 0x00007f6d57fe993e
7  libIREECompiler.so.0 0x00007f6d5c38afde
8  libIREECompiler.so.0 0x00007f6d5c38afde
9  libIREECompiler.so.0 0x00007f6d57fe3f89
10 libIREECompiler.so.0 0x00007f6d5c195072
11 libIREECompiler.so.0 0x00007f6d5c195528
12 libIREECompiler.so.0 0x00007f6d5c197594
13 libIREECompiler.so.0 0x00007f6d57bdd8db ireeCompilerInvocationPipeline + 2331
14 libIREECompiler.so.0 0x00007f6d57bd99ac
15 libIREECompiler.so.0 0x00007f6d57bd9761
16 libc.so.6            0x00007f6d5744618a
17 libc.so.6            0x00007f6d57446245 __libc_start_main + 133
18 iree-compile         0x000055a031456071
Segmentation fault

### What component(s) does this issue relate to?

Compiler

### Version information

commit e6425d6

### Additional context

@benvanik @hcindyl

**Comment by marbre** [comment]
Does this duplicates #12586?

**Comment by lundong** [comment]
> Does this duplicates #12586?

@marbre Yes, it is indeed a duplicate of #12586.
