### ISSUE TITLE
Unsupported VM Buffer -> numpy dtype mapping

### ISSUE THREAD

**Issue by pashu123** [iree-org/iree#12631]
### What happened?

```
Traceback (most recent call last):
  File "/home/prashant/test.py", line 43, in <module>
    print(x.to_host())
  File "/home/prashant/iree-build/runtime/bindings/python/iree/runtime/array_interop.py", line 102, in to_host
    self._transfer_to_host(False)
  File "/home/prashant/iree-build/runtime/bindings/python/iree/runtime/array_interop.py", line 112, in _transfer_to_host
    self._mapped_memory, self._host_array = self._map_to_host()
  File "/home/prashant/iree-build/runtime/bindings/python/iree/runtime/array_interop.py", line 116, in _map_to_host
    raw_dtype = self._get_raw_dtype()
  File "/home/prashant/iree-build/runtime/bindings/python/iree/runtime/array_interop.py", line 128, in _get_raw_dtype
    return HalElementType.map_to_dtype(self._buffer_view.element_type)
ValueError: Unsupported VM Buffer -> numpy dtype mapping
```

### Steps to reproduce your issue

Python script: https://gist.github.com/pashu123/9976376b2e387f1cb5d0493ba7f531f5
Run command: python test.py

The inbuilt complex-f32  dtype in MLIR should map to `np.complex64` which is `Complex number type composed of 2 32-bit-precision floating-point numbers`.

**Comment by benvanik** [comment]
looks like the switch needs to support these:
IREE_HAL_ELEMENT_TYPE_COMPLEX_FLOAT_64
IREE_HAL_ELEMENT_TYPE_COMPLEX_FLOAT_128

**Comment by powderluv** [comment]
Thanks @benvanik @jpienaar let us know if you want to add it or want us to add.

**Comment by powderluv** [comment]
(this is required for LLaMA support)

**Comment by Eliasj42** [comment]
> Does the complex-f32 dtype in MLIR map to np.complex64 because np.complex32 doesn't exist, or is this a pattern that should be applied to MLIR complex-f64 by mapping it to np.complex128?

**Comment by benvanik** [comment]
MLIR named the type differently - `complex<f32>` says two f32 fields representing imaginary/real, while numpy went with a total size so `np.complex64` is two f32 fields representing imaginary/real summed to 64 total bits. They're the same thing, just depends on which direction you look at it from ("a template containing two fields type T" or "64-bits of total precision (or whatever) as a single complex number").

**Comment by aaron-schneider** [comment]
Removing "needs-triage" since this has both priority and assignee.

**Comment by allieculp** [comment]
@jpienaar Can you add the appropriate workstream? P1?

**Comment by ScottTodd** [comment]
I think this was recently fixed.

**Comment by ScottTodd** [comment]
Fixed by https://github.com/openxla/iree/pull/12872
