### ISSUE TITLE
stablehlo.round_nearest_even fails with BF16 and complex<f32> lowerings

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#12647]
Current version generates a `llvm.intr.roundeven` operation that fails at linking time.  Determine why compilation is failing, this is likely due to an approximation / decomposition function not existing and therefore an intrinsic being invoked.

```
module @jit_rint {
  func.func public @main(%arg0: tensor<3x4xbf16> {jax.arg_info = "x", mhlo.sharding = "{replicated}"}) -> (tensor<3x4xbf16> {jax.result_info = ""}) {
    %0 = stablehlo.round_nearest_even %arg0 : tensor<3x4xbf16>
    return %0 : tensor<3x4xbf16>
  }
}
```

```
module @jit_rint {
  func.func public @main(%arg0: tensor<complex<f32>> {jax.arg_info = "x", mhlo.sharding = "{replicated}"}) -> (tensor<complex<f32>> {jax.result_info = ""}) {
    %0 = stablehlo.real %arg0 : (tensor<complex<f32>>) -> tensor<f32>
    %1 = call @rint(%0) : (tensor<f32>) -> tensor<f32>
    %2 = stablehlo.imag %arg0 : (tensor<complex<f32>>) -> tensor<f32>
    %3 = call @rint_0(%2) : (tensor<f32>) -> tensor<f32>
    %4 = stablehlo.complex %1, %3 : tensor<complex<f32>>
    return %4 : tensor<complex<f32>>
  }
  func.func private @rint(%arg0: tensor<f32>) -> tensor<f32> {
    %0 = stablehlo.round_nearest_even %arg0 : tensor<f32>
    return %0 : tensor<f32>
  }
  func.func private @rint_0(%arg0: tensor<f32>) -> tensor<f32> {
    %0 = stablehlo.round_nearest_even %arg0 : tensor<f32>
    return %0 : tensor<f32>
  }
}
```

**Comment by ramiro050** [comment]
The expand pattern for `roundeven` has landed: https://github.com/llvm/llvm-project/commit/8d2bae9abdc30e104bab00a4dd0f9d39f5bdda6e

**Comment by jpienaar** [comment]
OOC is there any work needed for complex?

**Comment by rsuderman** [comment]
This is one of the last remaining `bf16` failures. We may need to move the `math` to `arith` conversion to after our `bf16` cleanup.

```
module @jit_rint {
  func.func public @main(%arg0: tensor<4xbf16> {jax.arg_info = "x", mhlo.sharding = "{replicated}"}) -> (tensor<4xbf16> {jax.result_info = ""}) {
    %0 = stablehlo.round_nearest_even %arg0 : tensor<4xbf16>
    return %0 : tensor<4xbf16>
  }
}
```

**Comment by ramiro050** [comment]
> This is one of the last remaining `bf16` failures. We may need to move the `math` to `arith` conversion to after our `bf16` cleanup.
> 
> ```
> module @jit_rint {
>   func.func public @main(%arg0: tensor<4xbf16> {jax.arg_info = "x", mhlo.sharding = "{replicated}"}) -> (tensor<4xbf16> {jax.result_info = ""}) {
>     %0 = stablehlo.round_nearest_even %arg0 : tensor<4xbf16>
>     return %0 : tensor<4xbf16>
>   }
> }
> ```

@rsuderman, by failure, do you mean it fails to compile, or a runtime error? The snippet compiles without a problem on my machine using the `llvm-cpu` backend.

**Comment by aaron-schneider** [comment]
@rsuderman Will through this.

**Comment by rsuderman** [comment]
Appears to build at head now.
