### ISSUE TITLE
Support BF16 on args/returns of functions in promote pass

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#12646]
The promotion pass for BF16 -> F32 only should support keeping BF16 on the function boundaries to keep ABI correctness. The element type change causes failures in the JAX test for any BF16 test.

https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Dialect/Util/Transforms/ConvertPrimitiveType.cpp#L269

**Comment by dellis23** [comment]
Do you have a link to a test that's failing that would be easy for me to run as a repro, or some other way of reproducing the issue?

**Comment by aaron-schneider** [comment]
Please update on P0 issue, or perhaps lower to P1. P0 is meant for urgent interruptions and should be consistently updated. Thanks!

**Comment by rsuderman** [comment]
BF16 is now supported end-to-end. Marking closed.
