### ISSUE TITLE
JAX: Preserve unsigned return type information for return types

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#12665]
Compiled models return signless tensors from execution. We need to preserve the check that the element type is unsigned when necessary. Likely this means including an ABI change.

E.g. Jax integration test below produces a tensor with the correct contents but is assumed to be signed integers when it should be unsigned:

`JAX_PLATFORMS=iree_cpu pytest jax/tests/lax_numpy_operators_test.py::JaxNumpyOperatorTests::testBitwiseOp8`

**Comment by rsuderman** [comment]
Before MHLOToLinalgOnTensors we see the following block:
```
module {  func.func @main(%arg0: tensor<4xui32>) -> tensor<4xui32> {
    %0 = mhlo.add %arg0, %arg0 : tensor<4xui32>
    return %0 : tensor<4xui32>
  } 
} 
```
    
 With all unsigned types stripped as part of the lowering:
```    
module {
  func.func @main(%arg0: tensor<4xi32>) -> tensor<4xi32> {
    %0 = tensor.empty() : tensor<4xi32>
    %1 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel"]} ins(%arg0 : tensor<4xi32>) outs(%0 : tensor<4xi32>) {
    ^bb0(%in: i32, %out: i32):
      %2 = arith.addi %in, %in : i32
      linalg.yield %2 : i32
    } -> tensor<4xi32>
    return %1 : tensor<4xi32>
  }
}
```

We need to persist the `ui32` type on the function boundaries. Assuming we can have a `util` for preserving element types (e.g. `util.reinterpret`), we can maintain types on function boundaries but reinterpret the buffers before generating the the `hal.tensor.import` and `hal.tensor.export` functions the ultimately construct the buffer_view validation and construction.

**Comment by benvanik** [comment]
Still would be nice if there were any upstream op for bitcasting - arith.bitcast is typed for memref+primitives but many other arith ops support tensors so I'm not sure why. Since the HAL buffer view import/export happens on the function arg/result types preserving the original types + adding the bitcast on the arg/results (at all return sites) should just work.
