### ISSUE TITLE
[CUDA] mma.sync pipeline failed compilation with some tuning configs

### ISSUE THREAD

**Issue by yzhang93** [iree-org/iree#12675]
### What happened?

I tried to tune the matmul ops with mma.sync pipeline and used the same tile/workgroup size constraints from wmma pipeline. But a lot of them failed with the error ```error: Cannot determine operandId this vector::TransferReadOp is used as in the vector::TransferContractOp```

### Steps to reproduce your issue

Input IR:
```func.func @matmul() -> tensor<32x1280xf16>
{
  %arg0 = util.unfoldable_constant dense<1.0> : tensor<32x320xf16>
  %arg1 = util.unfoldable_constant dense<0.4> : tensor<320x1280xf16>
  %cst = arith.constant 0.000000e+00 : f16
  %0 = tensor.empty() : tensor<32x1280xf16>
  %1 = linalg.fill ins(%cst : f16) outs(%0 : tensor<32x1280xf16>) -> tensor<32x1280xf16>
  %2 = linalg.matmul {compilation_info = #iree_codegen.compilation_info<lowering_config = <tile_sizes = [[16, 32, 64]]>, translation_info = <LLVMGPUMatmulTensorCoreMmaSync pipeline_depth = 6>, workgroup_size = [256, 1, 1]>} ins(%arg0, %arg1 : tensor<32x320xf16>, tensor<320x1280xf16>)
    outs(%1: tensor<32x1280xf16>) -> tensor<32x1280xf16>
  return %2: tensor<32x1280xf16>
}
```
Compilation command:
```iree-compile --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=cuda --iree-hal-cuda-llvm-target-arch=sm_80 --iree-hal-cuda-disable-loop-nounroll-wa ~/tmp/matmul_32x1280x320.mlir -o matmul.vmfb```

### Version information

Nvidia A100

**Comment by allieculp** [comment]
@manishucsd Have you been able to take a look at this?

**Comment by manishucsd** [comment]
> @manishucsd Have you been able to take a look at this?

No, I haven't yet looked into this. 

Just eyeballing this, I have a suspicion the matmul shape here is similar to the one I am working here #13075

**Comment by yzhang93** [comment]
I tried to tune mma.sync with the updated IREE library and I think the error was gone by then. So feel free to close the issue.
