### ISSUE TITLE
RISC-V: Value mismatch error after LLVM-integration

### ISSUE THREAD

**Issue by okkwon** [iree-org/iree#12703]
The failure is here: https://github.com/openxla/iree/actions/runs/4471762535/jobs/7859606789?pr=12653#step:8:449

The test will be disabled to make the integration continue.

**Comment by dcaballe** [comment]
The failure is on a dynamic matmul:

```
func.func @matmul_DYNxDYNxi8_times_DYNxDYNxi8_into_DYNxDYNxi32(%lhs: tensor<?x?xi8>, %rhs: tensor<?x?xi8>, %acc: tensor<?x?xi32>) -> tensor<?x?xi32> {                
  %result = linalg.matmul ins(%lhs, %rhs: tensor<?x?xi8>, tensor<?x?xi8>) outs(%acc: tensor<?x?xi32>) -> tensor<?x?xi32>                                              
  return %result: tensor<?x?xi32>                                                                                                                                     
}
```

The MLIR is identical in both the healthy and the buggy version. We generate a single vector.outerproduct that should lead to something like:
```
    vle8.v	v10, (s2)
    vsext.vf2	v11, v10
    vwmacc.vx	v8, a5, v11
```

Full MLIR log:
Healthy: https://gist.github.com/dcaballe/2be71dab9abb787fef717eef005f9d98
Buggy: https://gist.github.com/dcaballe/ad71026c44f3cb43a041dac71d491c75


I haven't had a change to look at the LLVM-IR level but I do see significant differences at assembly level. It looks like the healthy version has some kind of multi-versioning that the buggy version doesn't have...

Healthy: https://gist.github.com/dcaballe/360f7f1b8a147b1f8a78f9203c01d7e0
Buggy: https://gist.github.com/dcaballe/07b45a198c345fa39bfe150a830dac23

**Comment by topperc** [comment]
@dcaballe were you able to look at the IR? The healthy assembly is 6x more lines than the buggy assembly. It seems unlikely that is caused by a change to the backend unless the buggy backend thought something was dead and deleted 60% of the code.

**Comment by dcaballe** [comment]
I haven't had a chance to look at the LLVM IR yet. @MaheshRavishankar was also looking into it. Do you have any update, Mahesh?

**Comment by MaheshRavishankar** [comment]
> I haven't had a chance to look at the LLVM IR yet. @MaheshRavishankar was also looking into it. Do you have any update, Mahesh?

No update yet, sorry doing other things, and havent been able to prioritize this.

**Comment by topperc** [comment]
I don't know if its relevant, but we did just find a bug in 
```
commit a9d9616c0de3f07654ee139bead48b8d78f44e1f
Author: Luke Lau <luke@igalia.com>
Date:   Mon Mar 13 11:12:12 2023

    [RISCV][NFC] Share interleave mask checking logic
```

So it wasn't NFC.

Patch to fix is here https://reviews.llvm.org/D147268

**Comment by dcaballe** [comment]
Thanks, Craig! Testing here: https://github.com/openxla/iree/pull/12868

**Comment by dcaballe** [comment]
The fix seems to be related as the impacted test output changes with it and it seems to be closer to the reference but not yet correct: https://github.com/openxla/iree/actions/runs/4578527416/jobs/8085365775?pr=12868. I tried to revert the buggy commit but there seems to be a few dependencies on it already.

**Comment by dcaballe** [comment]
Correction, this fix doesn't seem to be related to the issue here. I was looking at a different benchmark failure that was also included as part of this issue. Looking into the failure more in detail now...

**Comment by allieculp** [comment]
@dcaballe Any update on this one?

**Comment by dcaballe** [comment]
I'm my TODO list... I just need to get to it.

**Comment by allieculp** [comment]
Will set to 'needs scheduling' for now - thanks!

**Comment by allieculp** [comment]
@dcaballe Assigning this to you as we had no owner. Please redirect if needed!
