### ISSUE TITLE
Move MacOS builds to GitHub-managed runners

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#12727]
We now have access to GitHub managed large macOS runners (closed beta), accessible by specifying `runs-on: macos-12-xl`. See https://github.blog/2023-03-01-github-actions-introducing-faster-github-hosted-x64-macos-runners/ for the announcement. We should shift as much of our CI as possible to these runners, as they are actually scalable as opposed to our one mac mini in a closet. Note that these are only x86-64 runners, so we will likely want maintain some arm coverage. This might open up the possibility of mac presubmits, if the builds are fast enough

https://github.com/openxla/iree/pull/12725 is my initial attempt, but I'm having issues installing ninja for some reason.

**Comment by GMNGeoffrey** [comment]
@antiagainst, @stellaraccident, or @powderluv. If any of you have a spare cycle to iterate on the build, that would be most appreciated. I was hoping for a quick win, but I don't have time to debug what's going on with the ninja install right now. I really hate that we don't have docker...

**Comment by GMNGeoffrey** [comment]
We are seeing the new Mac XL runners stall out trying to fetch using actions/cache. They get to 74% of the way and then stall, repeatedly saying "Received 2143289343 of 2866279051 (74.8%)" (literally the same byte each time). Here is a run with debugging enabled that demonstrates the issue: https://github.com/openxla/iree/actions/runs/4522483132/jobs/7990992043

Here are some other failing runs. Note that in both of them happens literally after the same bytes received "Received 2143289343 of 2866279051"

- https://github.com/openxla/iree/actions/runs/4530137880/jobs/7978692296. 
- https://github.com/openxla/iree/actions/runs/4522483132/jobs/7964985557

A previous run fetched the cache and proceeded fine: https://github.com/openxla/iree/actions/runs/4516271068/jobs/7954411399

I've filed a ticket with GitHub support

**Comment by ScottTodd** [comment]
That's suspiciously close to 2^31:
```
2143289343 <-- received this many
2147483648 <--- 2^31
```

https://github.com/actions/cache#v3

> Fixed download issue for files > 2GB during restore.

**Comment by ScottTodd** [comment]
We're already using a pretty recent version (v3.2.3, well past when that changelog note was added) though.
