### ISSUE TITLE
Generalize target information for CUDA GPUs and use it to pick codegen config

### ISSUE THREAD

**Issue by ThomasRaoux** [iree-org/iree#12735]
### Request description

When compiling for a given cuda target we need to decide the right configuration based on the target information. Right now IREE has concentrating on sm_80 A100 target but should enable sm_86, sm_90 kind of target by choosing the right codegen configuration based on the amount of shared memory available.

Currently we only have very basic target info:
https://github.com/openxla/iree/blob/d9b052d57713122b8c74a89aa4f383b3063105d4/compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp#L75

One improvement would be to add shared memory available for each target. Then we should use it to decide whether we support a given configuration or not here:
https://github.com/openxla/iree/blob/d9b052d57713122b8c74a89aa4f383b3063105d4/compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp#L327

### What component(s) does this issue relate to?

Compiler

**Comment by antiagainst** [comment]
We have a common `#iree_gpu.target` shared by all GPU backends to describe the target information now.
