### ISSUE TITLE
Tracking issue for supporting larger x86_64/CUDA benchmarks

### ISSUE THREAD

**Issue by pzread** [iree-org/iree#12740]
We are planning to onboard more benchmarks including different batch sizes on x86_64 and CUDA benchmarks. However currently the x86_64 benchmarks already take ~50mins to finish (CUDA only takes ~7mins). We need to take some actions before adding more benchmarks.

**Comment by pzread** [comment]
@mariecwhite for the new benchmarks for different batch sizes, can you help me find out:

- The list of benchmarks we want to add
- How long will the step `build_e2e_test_artifacts` need to finish with all the new benchmarks
- How long will CUDA benchmarks run with all the new benchmarks
- How long will x86_64 benchmarks run with all the new benchmarks
- What is the total size of
  - All saved models
  - All compiled modules

Based on these, we can know

- Will it take too long to build all benchmarks in presubmit? (check the build is not broken in presubmit)
- Will it take too long to run x86_64/CUDA benchmarks in presubmit?
  - Likely will take too long on x86_64 in the current setup
  - If so, how many shards needed to have acceptable run time in presubmit
  - If it's not feasible to run in presubmit, can we still run for each postsubmit? Or we can only run nightly
- How much disk space will we need

**Comment by mariecwhite** [comment]
https://github.com/openxla/iree/pull/12890 adds ResNet50 TF models at various batch sizes to CUDA. Increases benchmark time from 10 mins to 3.5 hours.

**Comment by mariecwhite** [comment]
If I run T5-Large for both CUDA and x86_CPU, I get an out of disk space error. The saved model is 1.4 GB zipped and 3 GB unzipped.

**Comment by mariecwhite** [comment]
I'm unable to run Bert-Large at different batch sizes due to lack of disk space. This is now blocking adding new benchmarks. @pzread is it possible to increase the disk space size?

Bert-Large consists of 9 benchmarks, each with a zipped saved model of 1.2GB. I'm guessing we'll need roughly 30GB for Bert-Large.

T5-Large is also 1.4GB zipped + 3 GB unzipped. We also plan on benchmarking this model at different batch sizes.

**Comment by pzread** [comment]
Sure, I think we can enlarge the disk size of the build machines as required (currently it's a 100GB ram disk and we have about 360GB ram in total). Before doing that, I want to make sure how much we need.

Can you use https://github.com/openxla/iree/pull/13000 as the merge base with all models we want to add now and post the output of "After disk size" in the build step `build_e2e_test_artifacts` (https://github.com/openxla/iree/actions/runs/4660055553/jobs/8247995730#step:11:1) ? It will give you 200GB disk space to build all artifacts

You can do that by changing your PR target base from `main` to `jerry-enlarge-cpu-disk`.

Also are these large models all part of the "long" benchmarks? It will probably make sense to put them into a different build target (currently all models are built under `iree-benchmark-suites`) and only built in the postsubmit or nightly job. I can start working on this

**Comment by mariecwhite** [comment]
200GB looks good for now:

![image](https://user-images.githubusercontent.com/5143063/231028001-36350bb6-ae6e-4f59-904c-49a93fe08358.png)

**Comment by pzread** [comment]
Since we have created a separate workflow to run long benchmarks and the disk size has been increased. I think we can close this issue for now.
