### ISSUE TITLE
Bytecode version mismatch in iree-compile

### ISSUE THREAD

**Issue by wukefe** [iree-org/iree#12762]
### What happened?

I saw an error when running iree with a simple pytorch example.

```
class foo(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x, y):
        return x.sin() + y.cos()
```

The code is saved to attached `main.py` and you can run it with

```
python main.py
```

The error is related to bytecode version mismatch: (see full log attached as `error.txt`)

```
...
Diagnostics:
<stdin>:0:0: error: bytecode version 1 is newer than the current version 0
...
```

Attached files

[error.txt](https://github.com/openxla/iree/files/11067477/error.txt)
[main.py.txt (change to main.py)](https://github.com/openxla/iree/files/11067478/main.py.txt)
[pip-list.txt](https://github.com/openxla/iree/files/11067479/pip-list.txt)

### Steps to reproduce your issue

1. Download files
2. Run: `python main.py`
3. See error

### Version information

Ubuntu 20.04.5 LTS

List of installed packages

```
Package           Version
----------------- ---------------------
certifi           2022.12.7
cmake             3.26.1
filelock          3.10.4
iree-compiler     20230209.425
iree-runtime      20230209.425
iree-tools-tf     20230209.425
iree-tools-tflite 20230209.425
iree-tools-xla    20230209.425
iree-torch        0.0.1
Jinja2            3.1.2
lit               16.0.0
MarkupSafe        2.1.2
mpmath            1.3.0
networkx          3.0
numpy             1.24.2
pip               23.0.1
PyYAML            6.0
setuptools        65.6.3
sympy             1.11.1
torch             2.1.0.dev20230323+cpu
torch-mlir        20230324.787
triton            2.0.0
typing_extensions 4.5.0
wheel             0.38.4
```

**Comment by rsuderman** [comment]
This means the the tooling used to generate the `ir` is generating a newer version of the bytecode. The update was relatively recently and looks at your version numbers your `iree-compile` is back from early February. Try updating to the most recent version of `iree` and it might just fix everythin.

**Comment by wukefe** [comment]
Is there a way to install the latest iree via `pip install`?  What I can see is that there is no version later than the one I installed.  Or should I build iree from the source?

**Comment by jpienaar** [comment]
There is way to install the nightly :

-f https://openxla.github.io/iree/pip-release-links.html

**Comment by wukefe** [comment]
Thanks for your help!  The issue was resolved after iree was upgraded to the latest version.

```
...
iree-compiler     20230324.468
iree-runtime      20230324.468
...
```

**Comment by trholding** [comment]
I also have this issue, tried it with the nightly too. Same output.

**Comment by jpienaar** [comment]
What versions of iree-compiler, iree-runtime and JAX/PyTorch/torch-mlir do you have?

**Comment by trholding** [comment]
> What versions of iree-compiler, iree-runtime and JAX/PyTorch/torch-mlir do you have?

Thanks for getting back,

I have tried both iree compiler & runtime from regular pip and also the nightly (pip install -f https://iree-org.github.io/iree/pip-release-links.html iree-compiler iree-runtime)

iree_compiler-20230228.444
iree_runtime-20230228.444
torch-mlir 20230413.807

I followed torch-mlir instructions from here: https://openxla.github.io/iree/getting-started/pytorch/

**Comment by jpienaar** [comment]
That's the problem: post the GH org move, the URL changed and pip install doesn't follow the redirect.

**Comment by trholding** [comment]
> That's the problem: post the GH org move, the URL changed and pip install doesn't follow the redirect.

That sounds good and bad at the same time. How do I get the right url?

**Comment by trholding** [comment]
> That's the problem: post the GH org move, the URL changed and pip install doesn't follow the redirect.

I think a manual download could fix this issue:

[iree_compiler-20230414.489-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl](https://github.com/openxla/iree/releases/download/candidate-20230414.489/iree_compiler-20230414.489-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
[iree_compiler-20230414.489-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl](https://github.com/openxla/iree/releases/download/candidate-20230414.489/iree_compiler-20230414.489-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)

[iree_runtime-20230414.489-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl](https://github.com/openxla/iree/releases/download/candidate-20230414.489/iree_runtime-20230414.489-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
[iree_runtime-20230414.489-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl](https://github.com/openxla/iree/releases/download/candidate-20230414.489/iree_runtime-20230414.489-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)

But I am not sure which one to get - is this a version number: cp310-cp310 ?

**Comment by trholding** [comment]
> That's the problem: post the GH org move, the URL changed and pip install doesn't follow the redirect.

I think there is a issue with the downloads via wget.

I got errors like this: HTTP request sent, awaiting response... Read error (Decryption has failed.) in headers.
Retrying. 

But downloading via chrome worked!

**Comment by jpienaar** [comment]
Yes https://openxla.github.io/iree/pip-release-links.html is the new URL and if you go to the old URL in Chome in taxes you there, but pip [probably correctly] decides not to do that (sorry was on mobile for first response, luckily you resolved by time I go to desk)

**Comment by trholding** [comment]
For any one facing this issue in future, this is the solution until url redirects are fixed:

Manually download the compiler and runtime wheels with a browser from: https://iree-org.github.io/iree/pip-release-links.html

Then install the wheels with pip.

Please mark this as closed.

**Comment by jpienaar** [comment]
```
pip install -f https://openxla.github.io/iree/pip-release-links.html iree-compiler iree-runtime
```

should also do it (I'll go edit the URL in my old suggestion).
