### ISSUE TITLE
`CUDA_ERROR_INVALID_VALUE` when running Bert-Large with batch size 128

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#12774]
### What happened?

Error when trying to run BERT-Large with batch size 128:

```
/work/runtime/src/iree/hal/drivers/cuda/stream_command_buffer.c:516: INTERNAL; CUDA driver error 'CUDA_ERROR_INVALID_VALUE' (1): invalid argument; cuLaunchKernel; while invoking native function hal.device.queue.execute; while calling import; 
[ 1]   native hal.device.queue.execute:0 -
[ 0] bytecode module.forward:49184 [
...
```

### Steps to reproduce your issue

1. Download https://storage.googleapis.com/iree-model-artifacts/pytorch/torch_models_20230321.784_1679461251/BERT_LARGE/batch_128/linalg.mlir

2. Compile:

```
iree-compile --iree-hal-target-backends=cuda \
    --iree-input-type=none \
    --iree-hal-cuda-llvm-target-arch=sm_80 \
    linalg.mlir -o linalg.vmfb
```

3. Run:

```
iree-benchmark-module --module=linalg.vmfb \
    --function=forward \
    --input=128x384xi64=0 \
    --input=128x384xi64=0 \
    --device_allocator=caching \
    --device=cuda://0
```

### What component(s) does this issue relate to?

Runtime

### Version information

Based on IREE SHA https://github.com/openxla/iree/commit/c6092c4c57ab2dc1165c437b59b7de573e45c69e

**Comment by mariecwhite** [comment]
Also occurs with ResNet50 batch 16. Model source: https://storage.googleapis.com/iree-model-artifacts/pytorch/torch_models_20230321.784_1679461251/RESNET50/batch_16/linalg.mlir

Commands:
```
iree-compile --iree-hal-target-backends=cuda \
    --iree-input-type=none \
    --iree-hal-cuda-llvm-target-arch=sm_80 \
    linalg.mlir -o linalg.vmfb

iree-benchmark-module --module=linalg.vmfb \
    --function=forward \
    --input=16x3x224x224xf32=0 \
    --device_allocator=caching \
    --device=cuda://0
```

**Comment by mariecwhite** [comment]
FYI @monorimet

**Comment by KoolJBlack** [comment]
Ack this for now. May be related to #12642. I just pushed #12726 so this issue may be addressed. Will see if I can still repro in a bit.
