### ISSUE TITLE
MathToArith lowerings for select operations are missing

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#12783]
Multiple Math dialect operations  (e.g. `roundevenf`) map to llvm intrinsic operations that later map to glibc commands. This is less helpful as these function calls are not vectorized and significantly slow down the code generated.

We should include a `MathToArith` conversion pass that converts a set of `math` dialect operations to simple `arith` ops.  A list of the operations that currently take this path is located in the link below:

https://github.com/iree-org/iree/blob/0c53d822e7a4699ab36ca4446baa5a9914dd1ff7/runtime/src/iree/builtins/musl/Makefile_wasm32.iree

- [x] env
- [x] ceilf
- [x] floorf
- [x] fmaf
- [x] fmodf
- [x] powf ([bviyer](https://github.com/bviyer))
- [x] expf
- [x] powf_data
- [x] exp2f_data
  - [x] #12974  
- [x] roundf
- [x] roundevenf ([ramiro050](https://github.com/ramiro050) https://github.com/llvm/llvm-project/commit/8d2bae9abdc30e104bab00a4dd0f9d39f5bdda6e)
- [x] src/math/__math_invalidf
- [x] src/math/__math_oflowf
- [x] src/math/__math_uflowf
- [x] src/math/__math_xflowf
- [x] __truncsfbf2

Best first start is to implement `roundevenf` to address: https://github.com/openxla/iree/issues/12778

**Comment by ScottTodd** [comment]
Related:

* https://github.com/openxla/iree/blob/main/tests/e2e/regression/libm_linking.mlir
* https://github.com/openxla/iree/issues/4717 (in particular the last few comments about following up on the scalar intrinsics)

**Comment by jpienaar** [comment]
Ramiro is looking at roundeven.

@bviyer was going to look at some others here, any preference to one to start on?

**Comment by bviyer** [comment]
I will start looking into src/math/fmaf

**Comment by bviyer** [comment]
> Ramiro is looking at roundeven.
> 
> @bviyer was going to look at some others here, any preference to one to start on?


I will start looking into src/math/fmaf

**Comment by rsuderman** [comment]
> > Ramiro is looking at roundeven.
> > @bviyer was going to look at some others here, any preference to one to start on?
> 
> I will start looking into src/math/fmaf

Added your ldap next to the operation.

**Comment by bviyer** [comment]
Rob and I spoke and agreed that its best if I pick up ceilf and floorf first.

**Comment by rsuderman** [comment]
I need to check post-integrate but most of these features should be completed. If so we can remove the `musl` dependency and see what breaks.

**Comment by jpienaar** [comment]
Ran into __truncsfbf2 too (bf16 related) and added it.

Given Ramiro's roundeven issue has been split out, I'll change assignment to Balaji here who is working on more of the pending items.

**Comment by rsuderman** [comment]
> Ran into __truncsfbf2 too (bf16 related) and added it.
> 
> Given Ramiro's roundeven issue has been split out, I'll change assignment to Balaji here who is working on more of the pending items.

This should be getting fixed in the ConvertToLLVM pass (or prior). Support for `bf16` truncation depends quite a bit on backed but the explicit expansion should handle the conversion to regular arith operations.

**Comment by hcindyl** [comment]
https://github.com/llvm/llvm-project/commit/8d2bae9abdc30e104bab00a4dd0f9d39f5bdda6e fixed the llvm backend, but vmvx backend still misses the musl mapping. As a result, vmvx backend still mark `math.roundeven` is illegal.

I filed a separated https://github.com/openxla/iree/issues/13488 for it. Feel free to add back to this one if the team think we should consolidate the discussion here.

**Comment by bviyer** [comment]
I think this work is complete, so closing.
