### ISSUE TITLE
Linkage of libIREECompiler.so.0 fails when IREE_TARGET_BACKEND_LLVM_CPU is not set

### ISSUE THREAD

**Issue by marbre** [iree-org/iree#12830]
### What happened?

Trying to compile the sample `iree_samples_simple_embedding_simple_embedding_vmvx_sync` if `IREE_TARGET_BACKEND_DEFAULTS=OFF` and `IREE_TARGET_BACKEND_VMVX=ON` are set, the CMake target `iree_compiler_API_SharedImpl` fails with

```
[..]
 /usr/lib/x86_64-linux-gnu/libtinfo.so  third_party/iree/llvm-project/lib/libLLVMDemangle.a && :
/usr/bin/ld: cannot find -llldCOFF
/usr/bin/ld: cannot find -llldCommon
/usr/bin/ld: cannot find -llldELF
/usr/bin/ld: cannot find -llldMachO
/usr/bin/ld: cannot find -llldWasm
```

This can be resolved by setting `IREE_TARGET_BACKEND_LLVM_CPU=ON`. However, this increases the build time dramatically, with is essentially a not so nice thing for the [iree-template-cpp](https://github.com/iml130/iree-template-cpp) project in which it is demonstrated how to build a VMVX-based sample. This is also executed in a GitHub action (and this already takes quite long).

If it should not be legal to build the VMVX target backend without the LLVM CPU backend, CMake could already error on this.

### Steps to reproduce your issue

```bash
mkdir build
cd build
cmake -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DIREE_HAL_DRIVER_DEFAULTS=OFF -DIREE_TARGET_BACKEND_DEFAULTS=OFF -DIREE_TARGET_BACKEND_VMVX=ON ..
cmake --build . --target iree_compiler_API_SharedImpl
```

### What component(s) does this issue relate to?

Compiler

### Version information

candidate-20230328.472

**Comment by stellaraccident** [comment]
We really need a "min-spec" CI job that evaluates the compiler build with the minimum set of options enabled.

**Comment by ScottTodd** [comment]
This patch works around the issue: https://github.com/openxla/iree/pull/12583

**Comment by ScottTodd** [comment]
> We really need a "min-spec" CI job that evaluates the compiler build with the minimum set of options enabled.

Unfortunately for issues like this, we don't find out about the issue until build/link time. We have a large state space of CMake options that should be valid, so I'd feel more comfortable testing that they just _configure_ without errors. One definition of "min-spec" getting CI coverage would be better than none though.
