### ISSUE TITLE
IREE compilation has failed for TOSA-imported models since iree candidate-20230329.473

### ISSUE THREAD

**Issue by lundong** [iree-org/iree#12836]
### What happened?

Since iree release candidate-20230329.473, iree-compile has failed to compile the imported TOSA MLIR into vmfb for both the VMVX and llvm-cpu backends. It was further found that the commit 9778acb caused this issue.

A failed tflite example is the person detection model: https://storage.googleapis.com/iree-model-artifacts/person_detect.tflite

### Steps to reproduce your issue

1. Build IREE
Import TFLite model (use person.detect.tflite as an example)
/path/to/iree-import-tflite /path/to/person_detect.tflite -o=/tmp/person_detect.mlir
2. Use iree-compile to compile TOSA MLIR
/path/to/iree-compile -iree-input-type=tosa -iree-hal-target-backends=vmvx /tmp/person_detect.mlir
3. See error
error: failed to legalize operation 'math.roundeven' that was explicitly marked illegal ...
4. Repeat step 2-3 but change backend to llvm-cpu (-iree-hal-target-backends=llvm-cpu)
lld: error: undefined symbol: roundevenf

### What component(s) does this issue relate to?

Compiler

### Version information

iree candidate-20230329.473
commit 9778acb

### Additional context

may be related to upstream llvm change.

@hcindyl

**Comment by ScottTodd** [comment]
Looks like https://github.com/llvm/llvm-project/commit/89a1af749166627704cdf9d676455d32616c2c06, related to https://github.com/openxla/iree/issues/12783. @rsuderman 

If person detection is failing to compile, shouldn't some of our CI / benchmarks be broken too?

**Comment by hcindyl** [comment]
We actually don't have an extensive test converge today with vmvx config. Benchmark does not use vmvx , and iree-samples/tflitehub does not check the vmvx backend either.

I was thinking about adding vmvx coverage in iree-samples. If others have cycles, feel free to take it on.

**Comment by hcindyl** [comment]
It turns out `iree-samples` does not use the recent nightly IREE releases. https://github.com/iree-org/iree-samples/pull/122 is proposed to fix it, and we can see those failures once `iree-compile` is updated to the latest release.

Still not sure why CI `build_e2e_test_artfacts` can pass.

**Comment by ScottTodd** [comment]
> Repeat step 2-3 but change backend to llvm-cpu (-iree-hal-target-backends=llvm-cpu)
lld: error: undefined symbol: roundevenf

I can repro this in the regression test file https://github.com/openxla/iree/blob/main/tests/e2e/regression/libm_linking.mlir via

```mlir
// CHECK: vm.func private @roundeven
func.func @roundeven(%input : tensor<f32>) -> (tensor<f32>) {
  // May lower to llvm.intr.roundeven (roundToIntegralTiesToEven / roundeven)
  %result = math.roundeven %input : tensor<f32>
  return %result : tensor<f32>
}
```

https://llvm.org/docs/LangRef.html#llvm-roundeven-intrinsic

Tracing through the history, I found https://github.com/llvm/llvm-project/commit/4639a85f94be6355c55dcc802a9b01b622d6f7b1 ... interesting that there are two lowering paths - `MathToLLVM.cpp` and `MathToLibm.cpp`.

I think we can work around that by adding roundeven to https://github.com/openxla/iree/blob/main/runtime/src/iree/builtins/musl/Makefile_wasm64.iree (and the other related files).

**Comment by ScottTodd** [comment]
I don't see `roundeven` or `roundToIntegralTiesToEven` in https://github.com/powderluv/musl/tree/3f701faace7addc75d16dea8a6cd769fa5b3f260/src/math or https://git.musl-libc.org/cgit/musl. Is there some other impl we could link in?

Also looking through https://reviews.llvm.org/D75670 which added the LLVM intrinsic...

**Comment by hcindyl** [comment]
Add vmvx tflite test coverage with  https://github.com/iree-org/iree-samples/pull/125

**Comment by ScottTodd** [comment]
Ah, other rounding modes are included in musl, but I still don't see an exact match for `roundeven`:

| musc function | c standard | 
| --- | --- |
| [`nearbyintf.c`](https://github.com/powderluv/musl/blob/3f701faace7addc75d16dea8a6cd769fa5b3f260/src/math/nearbyintf.c) | [nearbyint](https://en.cppreference.com/w/c/numeric/math/nearbyint) (C99) |
| [`lrintf.c`](https://github.com/powderluv/musl/blob/3f701faace7addc75d16dea8a6cd769fa5b3f260/src/math/lrintf.c) | [rint](https://en.cppreference.com/w/c/numeric/math/rint) (C99) |
| [`rint.c`](https://github.com/powderluv/musl/blob/3f701faace7addc75d16dea8a6cd769fa5b3f260/src/math/rintf.c) | [rint](https://en.cppreference.com/w/c/numeric/math/rint) (C99)
| [`lroundf.c`](https://github.com/powderluv/musl/blob/3f701faace7addc75d16dea8a6cd769fa5b3f260/src/math/lroundf.c) | [round](https://en.cppreference.com/w/c/numeric/math/round) (C99) |
| [`roundf.c`](https://github.com/powderluv/musl/blob/3f701faace7addc75d16dea8a6cd769fa5b3f260/src/math/roundf.c) | [round](https://en.cppreference.com/w/c/numeric/math/round) (C99)  |
| ??? | [roundeven](https://en.cppreference.com/w/c/numeric/math/roundeven) (C23) |

**Comment by ScottTodd** [comment]
> If person detection is failing to compile, shouldn't some of our CI / benchmarks be broken too?

Turns out the tests _are_ broken (but not benchmarks?), but we just disabled them and filed an issue to follow-up. Sorry about that - we really shouldn't be regressing on compilation correctness for user programs for the sake of keeping up with the latest LLVM code.

**Comment by allieculp** [comment]
Should we close this in favor of the other issue?

**Comment by ScottTodd** [comment]
We can close this issue and merge it into the other one, yeah.
