### ISSUE TITLE
Why does CI action `test_all` check out git repo + submodules?

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#12844]
Just noticed this, e.g. [here](https://github.com/openxla/iree/actions/runs/4559501450/jobs/8043622625).  Since this is downloading build artifacts, not building from sources, why check out all these git repos?

<img width="580" alt="Screenshot 2023-03-29 at 9 18 51 PM" src="https://user-images.githubusercontent.com/79535/228703416-ad41c27b-bf47-45f7-a55e-843ea77875c2.png">

**Comment by bjacob** [comment]
@GMNGeoffrey @pzread

**Comment by marbre** [comment]
Side-note: If this is changed, you may want to set `IREE_ERROR_ON_MISSING_SUBMODULES=OFF` :)

**Comment by GMNGeoffrey** [comment]
I believe I tried without the checkout and we have tests that depend on source files both from IREE and from submodules. We could likely try to identify some subset, but I think the correct fix is to instead create installable tests

**Comment by GMNGeoffrey** [comment]
And it's not just one oddball test or something. Like all the lit tests are run against .mlir source files, for instance

**Comment by bjacob** [comment]
I see. Maybe at least we can drop the git submodules ?

**Comment by GMNGeoffrey** [comment]
Unfortunately not trivially. We depend on source files from submodules as well. It is at least lit from LLVM and it might only be that. So we could hack together a sparse checkout, but I didn't investigate more deeply at the time. I still think the right solution is installable tests, but a workaround wouldn't be the worst thing.

**Comment by bjacob** [comment]
ok. thank you for the answers! closing this issue now.
