### ISSUE TITLE
[RISC-V] ~40% slowdown on MobileBert after #12653 integrate

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#12867]

**Comment by ScottTodd** [comment]
Linking the suspected culprit: https://github.com/openxla/iree/pull/12653

Can you include more context, such as linking to a dashboard series, Tracy captures, or intermediate .mlir files from compilation before/after?

**Comment by dcaballe** [comment]
(shared internally)

**Comment by allieculp** [comment]
Marking as P1, please downgrade if needed.

**Comment by ScottTodd** [comment]
Old/stale issue, closing. I don't think we can act on this issue so far after the culprit change.
