### ISSUE TITLE
Format IREE compiler code in LLVM style

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#12866]
The IREE compiler code has always followed LLVM style, but for historical reasons related to our original source-of-truth in Google's monorepo, used Google formatting configuration. These reasons no longer apply and the mismatch has caused friction for upstreaming to and pulling from LLVM. The team has agreed to reformat the compiler code in LLVM style as well. Practically, that means putting the appropriate .clang-format file under the compiler/ directory and running clang-format. The tools/ directory may require some more careful handling. We should also update the git "non-interesting commits" config file so that Git blame will ignore the commit (need to look up exactly how to do that).

**Comment by GMNGeoffrey** [comment]
Assigning myself, but not sure when I'll get to this, so if someone feels inspired, go for it

**Comment by ScottTodd** [comment]
> We should also update the git "non-interesting commits" config file so that Git blame will ignore the commit (need to look up exactly how to do that).

Cool:

https://git-scm.com/docs/git-blame
https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

**Comment by ScottTodd** [comment]
Though I'm not sure the functionality is worth adding _another_ top level dotfile to the repo (`.git-blame-ignore-revs`)...

**Comment by GMNGeoffrey** [comment]
Unassigning myself from issues that I'm not actively working on

**Comment by ScottTodd** [comment]
As part of this, we should set [`PointerAlignment`](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#pointeralignment) and [`DerivePointerAlignment`](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#derivepointeralignment) in each directory explicitly.

**Comment by ScottTodd** [comment]
Here's a draft: https://github.com/openxla/iree/compare/main...ScottTodd:clang-format-compiler?expand=1 (I was curious if the diff would be small or large, since a few people were quick to wonder how disruptive this would be)

**Comment by kuhar** [comment]
> Here's a draft: https://github.com/openxla/iree/compare/main...ScottTodd:clang-format-compiler?expand=1 (I was curious if the diff would be small or large, since a few people were quick to wonder how disruptive this would be)

This includes the runtime directory which was supposed to keep using the current style

**Comment by ScottTodd** [comment]
Yep - quick draft, turning that into a PR is left as an exercise for the reader ;P

**Comment by ScottTodd** [comment]
We still have a top level .clang-format file that uses the `Google` style, so I think the runtime directory diffs in my draft were just from files that haven't been touched recently. Our lint checks use git-clang-format and only run on changed files.

**Comment by ScottTodd** [comment]
Pretty sure this was finished in the already referenced commits.
