### ISSUE TITLE
2x performance drop on riscv_32 tests after LLVM 3/28 integrate

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#12862]
The e2e_matmul_direct_f32_large_split_k_llvm-cpu test takes 2x time to finish after the integrate: https://github.com/openxla/iree/commit/3f37bf513290e82cb6c8544f3d887639b3392a63

35.21 sec before LLVM integrate, >60 sec after

https://github.com/openxla/iree/actions/runs/4557756253/jobs/8040376093#step:8:901

https://github.com/openxla/iree/actions/runs/4558468195/jobs/8041611057#step:8:901 

FYI, @dcaballe @hcindyl

**Comment by allieculp** [comment]
@mattwalsh This looks like one we might want to set as a P1 - can you take a look?

**Comment by hanhanW** [comment]
closing stale issue
