### ISSUE TITLE
Add support for running Vulkan benchmarks on NVIDIA GPUs

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#12871]
### Request description

We are benchmarking Vulkan on mobile devices only. We should extend that to run on desktop for Stable Diffusion use cases.

### What component(s) does this issue relate to?

Other

**Comment by antiagainst** [comment]
Thanks @mariecwhite! The cloud VM (containing NVIDIA GPUs) should already have Vulkan drivers installed; so likely just to use the proper compiler triple and runtime driver. Let me know if you hit other issues!

**Comment by ScottTodd** [comment]
Should we include both AMD and NVIDIA GPUs in this?

**Comment by antiagainst** [comment]
> Should we include both AMD and NVIDIA GPUs in this?

With NVIDIA GPUs supported we should be able to guard against quite a lot of compilation/runtime regressions, which we see frequently recently. We don't have AMD GPUs readily in the cloud right now; enabling runtime checks on them takes extra effort to manage local AMD GPU cards. We can worry about that in a later step.

**Comment by allieculp** [comment]
@mariecwhite Setting status to 'needs scheduling' - please edit if/when this is in progress!
