### ISSUE TITLE
Create benchmarks for user-specificed matmul shapes for f16 and f32 datatype

### ISSUE THREAD

**Issue by manishucsd** [iree-org/iree#12899]
# Request description
Monitor the performance improvements of matmul operations in the continuous integration (CI) system on square aligned matmul shapes. Also see #12919 .

### Square Aligned Matrix Shape Sweep Shapes
Matmul operation (sweep M and N for a large K=8192) : `m = 512:4096:128`,` n = 512:4096:128`, `k = 8192`
Tile configuration : Find the best tile configuration locally (once) and use it for different matmul shapes
Data type : `f16` and `f32`
Providers: `IREE Codegen`, `Triton` (at least what we have in mmperf), 
Additional matmul providers: `cuBLAS` and `CUTLASS` (Optional)

### What component(s) does this issue relate to?

Compiler, Runtime

**Comment by julianwa** [comment]
@manishucsd can you specify the data you would like this benchmark to produce?

**Comment by mattwalsh** [comment]
I think we mainly want the throughput per combination (e.g. GF/s).

Eventually it'd also be great to have % of Cublas (and eventually others) performance

**Comment by manishucsd** [comment]
The goal is to get performance numbers produced with mmperf (a graph similar to [this](https://drive.google.com/corp/drive/u/0/folders/18WESZKKDciZlUCDfojrBvpLBiuXBUer6) one). We want continuous perf tracking for some selected square aligned matmul shapes. Unlike the graph in the mmperf graph, it will be better to track aligned matmul shapes in here. We can track unaligned matmul shapes separately.

**Comment by julianwa** [comment]
@manishucsd once #13396 lands, can you provide command to invoke IREE Dispatch Profiler for the desired sweep(s) here? As an initial step to automated benchmarking, we can run this nightly as we do mmperf.

**Comment by manishucsd** [comment]
I was hoping mmperf is being fixed and this particular case in CI is going to be supported through mmperf. My understanding is that mmperf also runs Triton which is one of the requirement for this issue 

> Providers: IREE Codegen, Triton (at least what we have in mmperf),

We can support by generating these using IREE dispatch profiler as follows:

```bash
$ python3 ../iree/experimental/dispatch_profiler/profiler.py --op-kind=matmul --problem-m=512:4096:128 --problem-n=512:4096:128 --problem-k=8192

$ python3 ../iree/experimental/dispatch_profiler/compile.py
```

I recommend following `/iree/experimental/dispatch_profiler/README.md` after #13396 lands for the rest, if we decide to move with IREE dispatch profiler over mmperf.

**Comment by allieculp** [comment]
@manishucsd What is needed to close this one out? Do we need an owner?

**Comment by allieculp** [comment]
@manishucsd to break this up into multiple issues.
