### ISSUE TITLE
Create a vscode dev container

### ISSUE THREAD

**Issue by pjannaty** [iree-org/iree#12907]
### Request description

Jonathan: It essentially only adds a folder: .devcontainer with two file inside (a Docker Compose & a config file).

**Comment by ScottTodd** [comment]
Initial support has landed: https://github.com/openxla/iree/tree/main/.devcontainer

Possible next steps:

* Advertise to developers and see if they have feedback ("soft launch"?)
* Mention on https://openxla.github.io/iree/building-from-source/getting-started/ (I'd start with a ["Tip" call out](https://squidfunk.github.io/mkdocs-material/reference/admonitions/))
* Extend the dev container with other settings and extensions
  * I think lint and formatting tools should be installed and configured, at least enough for [`build_tools/scripts/lint.sh`](https://github.com/openxla/iree/blob/main/build_tools/scripts/lint.sh) to run successfully
* Add a top level configure script that runs [`.devcontainer/configure.py`](https://github.com/openxla/iree/blob/main/.devcontainer/configure.py), [`configure_bazel.py`](https://github.com/openxla/iree/blob/main/configure_bazel.py) (move into `build_tools/bazel/`?), and other developer configuration scripts

**Comment by pjannaty** [comment]
Thank you all! Looking snazzy!

**Comment by allieculp** [comment]
@DEKHTIARJonathan @pjannaty Is this still an active effort on your side? This issue has gone stale so checking in.

**Comment by jpienaar** [comment]
I believe this is done.
