### ISSUE TITLE
Support MPI for IREE OSS side to enable development in CLI without a hosting layer

### ISSUE THREAD

**Issue by julianwa** [iree-org/iree#12931]

**Comment by ScottTodd** [comment]
@julianwa did you mean to file this issue? Maybe this was created from a task list (https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists)? Can you add a description and issue title?

(Anyone that watches repo issues or browses the issues list got a notification/email for this)

**Comment by julianwa** [comment]
Yes, sorry, I'm experimenting with a few things. It will be tidied up in a bit!

**Comment by okkwon** [comment]
WIP PR: https://github.com/openxla/iree/pull/12902

**Comment by okkwon** [comment]
PR got merged. Closing.
