### ISSUE TITLE
mmperf workflow is failing due to third_party/spirv_cross submodule fetch failure

### ISSUE THREAD

**Issue by julianwa** [iree-org/iree#12944]
### What happened?

All mmperf workflows are failing

### Steps to reproduce your issue

See failed workflow: https://github.com/openxla/iree/actions/runs/4618811926
Sample log: https://pipelines.actions.githubusercontent.com/serviceHosts/fc4d0f0b-8039-4b0a-8de2-442c528b630e/_apis/pipelines/1/runs/97764/signedlogcontent/10?urlExpires=2023-04-06T01%3A15%3A55.8854303Z&urlSigningMethod=HMACV1&urlSignature=XrkaQJPV%2BHp%2FykrG6ivASXEZ%2BuOTyrxc2hAzQWPMwUI%3D

### What component(s) does this issue relate to?

Other

**Comment by allieculp** [comment]
@mariecwhite @monorimet Please update status once you have had a chance to look at this!

**Comment by mariecwhite** [comment]
Fixed in https://github.com/openxla/iree/pull/13034. Just need to get it reviewed and merged.

**Comment by mariecwhite** [comment]
This got merged but more API changes broke mmperf again. New fix in https://github.com/openxla/iree/pull/13221 that needs review.

**Comment by allieculp** [comment]
@mariecwhite Is this fixed?

**Comment by mariecwhite** [comment]
Yes this is fixed.
