### ISSUE TITLE
Support multiple devices in a single PJRT client

### ISSUE THREAD

**Issue by julianwa** [iree-org/iree#12948]

**Comment by okkwon** [comment]
@benvanik assuming that we are going to use multi threads in the PJRT plugin to support multiple devices concurrently, what components we want to make thread local? To maximize the parallelism, I think device/vm can be created and maintained in each thread. Please shed some light. Thanks

**Comment by benvanik** [comment]
you can share iree_vm_module_t's across threads (as they are immutable). iree_vm_context_t is thread-compatible but not thread-safe (https://faithlife.codes/blog/2008/03/degrees_of_thread_safety/) so if you plan on having multiple invocations running concurrently you'd need one per thread performing the invocation. iree_hal_device_t is thread safe but today generally designed around a single physical device (though exposing multiple physical devices as a single logical device with multiple queues makes sense in some scenarios) - if you are creating one thread per physical device then it's best to give each thread its own iree_hal_device_t of just that specific device.

the iree_vm_instance_t and iree_hal_driver_t should be shared across all threads - they are thread-safe and important to share.

**Comment by julianwa** [comment]
Per discussion today, we do *not* want to use a multiple-threads-in-the-PJRT-client approach with this, and instead wait for the CUDA HAL Async work to complete, and use that instead. /cc @antiagainst

**Comment by julianwa** [comment]
@antiagainst is going to sketch out the PJRT -> IREE API interaction we expect to build to enable this, and make sure there aren't any other feature gaps other than the CUDA HAL Async work

**Comment by antiagainst** [comment]
Thanks Julian! I'll look into details and analyze starting next week to have a clear picture. So assigning to me for now.

**Comment by julianwa** [comment]
Sounds good! Don't assume you need to pick up this work beyond the design work sufficient to validate that you're meeting the requirement cuda hal work.

**Comment by benvanik** [comment]
Closing as PJRT is not being actively worked on.
