### ISSUE TITLE
Lower StableHLO ops with multiple replica groups into flow ops

### ISSUE THREAD

**Issue by julianwa** [iree-org/iree#12946]

**Comment by okkwon** [comment]
This needs `num_replicas` and `num_partitions` in the MLIR module. https://github.com/openxla/stablehlo/issues/650.

**Comment by burmako** [comment]
@okkwon To double-check: in the meanwhile, you folks can use the unregistered `mhlo.num_replicas` and `mhlo.num_partitions` attributes produced by JAX, right?

**Comment by okkwon** [comment]
@burmako Yes, I can use them. Thanks!

**Comment by okkwon** [comment]
https://github.com/openxla/iree/pull/13288

**Comment by allieculp** [comment]
@okkwon Is this done?

**Comment by okkwon** [comment]
Yes, it is done. Closing.
