### ISSUE TITLE
Add support for f32 scalar input in Python bindings

### ISSUE THREAD

**Issue by sogartar** [iree-org/iree#12966]
### Request description

When calling a VM module function that accepts `f32` as input it should support `numpy.float32` and zero-dimensional `numpy.array`. The rational is that in the other cases IREE accepts f32 numpy arrays.
Other data types may be missing this support as well.

For example
```mlir
func.func @f(%arg0: f32) -> f32 {
  %0 = math.exp2 %arg0 : f32
  return %0 : f32
}
```
You should be able to do
```python
vm_module.f(numpy.float32(1))
vm_module.f(numpy.array(1, dtype=numpy.float32))
```

Doing this right now returns
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/petkantchin/ws/iree/build/ninja/RelWithDebInfo/runtime/bindings/python/iree/runtime/function.py", line 130, in __call__
    self._invoke(arg_list, ret_list)
  File "/home/petkantchin/ws/iree/build/ninja/RelWithDebInfo/runtime/bindings/python/iree/runtime/function.py", line 154, in _invoke
    self._vm_context.invoke(self._vm_function, arg_list, ret_list)
RuntimeError: Error invoking function: repo/runtime/src/iree/vm/list.c:710: FAILED_PRECONDITION; variant at index 0 is not a value type
```

### What component(s) does this issue relate to?

Python

**Comment by jpienaar** [comment]
VM is very low level, it should probably be stricter (e.g., #12967 ) rather than looser.

**Comment by benvanik** [comment]
Yeah, we don't generally perform implicit conversions like this at the lower layers of the system. Think of the modules we have in the VM as being statically-typed, and the interfaces we want to expose on top of them being something that potentially type checked in python with pytype. This is consistent with numpy.typing (https://numpy.org/doc/stable/reference/typing.html#module-numpy.typing) and jax.typing (https://jax.readthedocs.io/en/latest/jax.typing.html#module-jax.typing) which both have a way of annotating array-like values. If your original model takes a numpy arraylike then you can pass in a numpy arraylike and if it takes a primitive value then you can pass in a primitive value. Layers on top of IREE's bindings can add additional implicit conversion magic by reflecting on the exported function to get its expected signature but it's a massive source of footguns we don't want to encourage.
