### ISSUE TITLE
NV+Google collaborate on creating an openxla/dev-tools repo and building automation

### ISSUE THREAD

**Issue by pjannaty** [iree-org/iree#12995]
### Request description

See RFC https://github.com/openxla/community/issues/72

**Comment by allieculp** [comment]
@jpienaar customer engagements?

**Comment by stellaraccident** [comment]
OSS Infra

**Comment by allieculp** [comment]
From triage meeting: @aaron-schneider picking this up.

**Comment by aaron-schneider** [comment]
This is live now: https://github.com/openxla/openxla-dev-tools

Stella and Geoffrey and Jacques talking about simplifying name to openxla-devtools.
