### ISSUE TITLE
[vulkan-spirv] Invalid output values (nan) while running UNet model on Intel ARC

### ISSUE THREAD

**Issue by nithinsubbiah** [iree-org/iree#13009]
### What happened?

Compiling UNet model to vulkan target and running on Intel ARC cards (Windows) produces `nan` values as output.

UNet MLIR download link: https://storage.googleapis.com/shark_tank/latest/unet64_512_512_fp16_stabilityai_stable_diffusion_2_1_base/unet64_512_512_fp16_stabilityai_stable_diffusion_2_1_base_torch.mlir

Dispatch graph: https://gist.github.com/nithinsubbiah/9bee1d7a7d8ee7674ff0ebadaf1d5ffc

Upon triaging the issue further the model was found to fail at the following dispatch (dispatch_index - 501): https://gist.github.com/nithinsubbiah/c623f003083300636edcee88421afbb1

The dispatch contains a matmul with fused elementwise operation.

### Steps to reproduce your issue

1. Download the UNet MLIR from the link above
2. Run the following command to compile the MLIR file:
```
.\iree-build\tools\iree-compile.exe --iree-input-type=none --iree-hal-target-backends=vulkan  --iree-vulkan-target-triple=arc-770-windows --iree-stream-partitioning-favor=min-peak-memory --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs --iree-preprocessing-pass-pipeline='builtin.module(func.func(iree-flow-detach-elementwise-from-named-ops,iree-preprocessing-convert-conv2d-to-img2col,iree-flow-convert-1x1-filter-conv2d-to-matmul,iree-preprocessing-pad-linalg-ops{pad-size=32}))' --iree-flow-dump-dispatch-graph=1 unet.mlir -o unet.vmfb
```
3. Run the following command to run the compiled module:
```
.\iree-build\tools\iree-run-module.exe --module=unet.vmfb --function=forward --device=vulkan --input=1x4x64x64xf16 --input=1xf16 --input=2x64x1024xf16 --input=f32=1.0
```

### What component(s) does this issue relate to?

Compiler

**Comment by allieculp** [comment]
From triage meeting: @antiagainst @kuhar can you help take a look at this?

**Comment by antiagainst** [comment]
I don't have a Intel ARC cards with me.. Would you mind to verify if this is reproducible on NVIDIA or AMD cards? Thanks.

**Comment by nithinsubbiah** [comment]
I compiled the model to vulkan target on a A100 with the following command:
```
./build/tools/iree-compile --iree-input-type=none --iree-hal-target-backends=vulkan  --iree-vulkan-target-triple=ampere-rtx3080-linux --iree-stream-partitioning-favor=min-peak-memory --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs --iree-preprocessing-pass-pipeline='builtin.module(func.func(iree-flow-detach-elementwise-from-named-ops,iree-preprocessing-convert-conv2d-to-img2col,iree-flow-convert-1x1-filter-conv2d-to-matmul,iree-preprocessing-pad-linalg-ops{pad-size=32}))' --iree-flow-dump-dispatch-graph=1 unet.mlir -o unet.vmfb
```
and it hit `error: failed to legalize operation 'gpu.subgroup_mma_store_matrix' that was explicitly marked illegal`.

**Comment by antiagainst** [comment]
https://github.com/openxla/iree/issues/13051 was reported for the above issue. It's fixed now; could you try again? Thanks.

**Comment by nithinsubbiah** [comment]
@antiagainst #13051 did fix that lowering error and UNet looks to be running on AMD vulkan path which seems to make the current issue pertinent to ARC.

**Comment by antiagainst** [comment]
Okay thanks. Then could you try to compile using the ARC triple and run the generated vmfb on NVIDIA card to see whether it works there? (Running on AMD would cause issues for reduction given that they have different subgroup size. But you could try there too to see if the result is still NaN.) If it works then that means there are issue in the ARC driver stack.

**Comment by nithinsubbiah** [comment]
I compiled to ARC triple and ran it on the Nvidia card and got results (no `NaN`) but the values were different compared to Nvidia compiled vmfb.

**Comment by antiagainst** [comment]
Do you see large meaningful differences? If the difference is within tolerance then that's fine. It would be good to verify the generated pictures to see if they are okay.

**Comment by nithinsubbiah** [comment]
I ran it through SHARK and using arc target triple on Nvidia does produce legible results. I'll see how I can flag this as a driver issue, thanks!

**Comment by antiagainst** [comment]
Okay thanks. Closing this for now given this is a driver issue and there is nothing for IREE to do.
