### ISSUE TITLE
Relaxing the restrictions that the problem reduction shape is divisible by split-ratio 

### ISSUE THREAD

**Issue by manishucsd** [iree-org/iree#13015]
### Request description

IREE Codegen has restrictions on `split-k-slices` a.k.a. `split-ratio`:

```
(ProblemK % split-ratio == 0)
```

Matmul problem k or the reduction dimension should be divisible with split-ratio. This restrict us to use optimal split-ratio for a problem size when the divisibility rule fails. 

It will be great to have a discussion here if this is possible and what should be the path for removing this restriction on split-ratio.

**Comment by allieculp** [comment]
From triage meeting: @manishucsd is this in progress?

**Comment by manishucsd** [comment]
@allieculp , We have identified this issue and this is not in progress. I created this issue so as to have discussion on this. 
cc: @ThomasRaoux , @julianwa

**Comment by allieculp** [comment]
Thanks Manish, sounds like we also need triaging here to set priority and next steps.
@mattwalsh for visibility

**Comment by allieculp** [comment]
Can be closed by #13115 ?

**Comment by manishucsd** [comment]
We have decent confidence that we can get performance of split-k matmul to match the library/cuBLAS performance, but there are a two issues in path to production: 

- [] 1. An intuitive split-k API which does NOT use batch_matmul as a proxy to trigger split-k ([#13014](https://github.com/openxla/iree/issues/13014) - Issue closed but not fixed) 
- [x] 2. Relaxing the restrictions on the reduction dim to be divisible by split-ratio ([#13015](https://github.com/openxla/iree/issues/13015) - Issue closed but not fixed)  **[This issue]**

**Note:** We are trying to feed two bird with one seed by the solution proposed in [#13155](https://github.com/openxla/iree/issues/13115)

The above two issue is being handled in the discussion and solutions proposed here [#13155](https://github.com/openxla/iree/issues/13115) (Open issue and addressing 1. And 2. from path to production).
