### ISSUE TITLE
An op that allocates a tensor in flow/stream dialect that cannot be CSE-ed

### ISSUE THREAD

**Issue by vmurali** [iree-org/iree#13022]
### Request description

A `tensor.empty()` creates a tensor that can be CSE-ed with other `tensor.empty()` ops. When calling an external C(++) function which uses destination-passing-style semantics for the results, a tensor created from `tensor.empty()` is passed as an operand to the external call that will be aliased with the result. Unfortunately, we don't have a mechanism to specify the aliasing behavior in the external function, and as a result, the buffer allocated to the `tensor.empty()` op would be modified. For instance, consider the program:

```
module @example {
  func.func private @Some.function(tensor<10xi32>, tensor<10xi32>) -> (tensor<10xi32> {iree.abi.tied = 1 : index}) attributes {
    iree.abi.model = "coarse-fences",
    nosideeffects
  }

  func.func @main(%arg0: tensor<10xi32>) -> tensor<10xi32> {

    %init = tensor.empty() : tensor<10xi32>
    %p1 = call @Some.function(%0, %init) : (tensor<10xi32>, tensor<10xi32>) -> tensor<10xi32>
    %init2 = tensor.empty() : tensor<10xi32>
    %1 = call @Some.function(%p1, %init2) : (tensor<10xi32>, tensor<10xi32>) -> tensor<10xi32>

    return %1 : tensor<10xi32>
  }
}
```
Here, `%init` and `%init2` get CSE-ed, with them aliased to `%p1` because of `@Some.function`, thus corrupting the input `%p1` when `@Some.function` updates what it thinks as `%init2` buffer, to store the result `%1`.

This is somewhat related to https://github.com/openxla/iree/issues/13003

A solution is to create a new op which has the semantics of `tensor.empty()`, but has side-effects attribute, to avoid CSE-ing (or rather `MemAlloc` attribute to avoid CSE, but permit DCE).

A question to ponder is if there's any situation where `tensor.empty()` being CSE-ed is a good idea. It seems `tensor.empty()` is un-CSE-ed [here](https://github.com/openxla/iree/blob/0587a95dd3984a1df6011c0c3855e9f495b5242a/compiler/src/iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp#L279-L281) in codegen when converting ops to destination passing style.

### What component(s) does this issue relate to?

Compiler

**Comment by benvanik** [comment]
> A question to ponder is if there's any situation where tensor.empty() being CSE-ed is a good idea.

It's a good idea - it's not an allocation and instead functionally equivalent to arith.constant with an undefined value. Just as arith.constant CSE's so too can tensor.empty. In tensor land all tensors are immutable and as such two tensor.empty ops of the same type are both immutable tensors with undefined contents of the same type - it's actually a design bug that codegen (or users) are relying on it for allocation behavior.

The only reason to not use tensor.empty is for boundary interop where analysis breaks down - like making custom external calls - and the proper tensor semantics (immutability, copy on write) cannot be applied.

I still think we'll need to make a util.func/util.call that enables #13003 and all the other things we need for analysis but for now adding a flow.tensor.alloca that maps to a stream.async.alloca feels reasonable. I'll get on that now.

**Comment by allieculp** [comment]
Setting to P1 'in progress' - please edit as needed!
