### ISSUE TITLE
Transition TF benchmarks to stablehlo dumps

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#13033]
When we generate TF benchmarks, we are persisting the savedmodel in GCS and then, at build/test time, running iree-import-tf to generate stablehlo that can be compiled. With the [new flow](https://github.com/openxla/iree/pull/13025) all of the import code is upstream with just a small Python stub in IREE that generates a stablehlo+ml_program dump. Given that this all lives upstream, we should eliminate our in-tree dependence on the actual importers, instead just having stablehlo benchmarks and offline model generation generating/persisting that directly (versus the savedmodel).

This same workflow will generalize well to jax and torch-xla.

**Comment by stellaraccident** [comment]
@julianwa @mariecwhite @jpienaar I'm going to fix the current thing, but we should really maneuver this as I've described.

**Comment by julianwa** [comment]
> @julianwa @mariecwhite @jpienaar I'm going to fix the current thing, but we should really maneuver this as I've described.

Ack. @mariecwhite, can you incorporate this into the in-progress OOBI design work and next steps?

**Comment by mariecwhite** [comment]
@stellaraccident @jpienaar Can you add commands here that would replace the existing flow? That way I can look into how this would integrate into OOBI.

**Comment by stellaraccident** [comment]
You basically want to run iree-import-tf with the correct args on the savedmodel and persist the output. I had to derive the commands myself from the corresponding CMake vars as they are model specific.

(for doing this for real, you'll want to wait until we land the iree-import-tf upgrade as that will output a more robust form of output -- if you do it now at head, you'll get a form that can still vary a bit from time to time)

**Comment by allieculp** [comment]
@mariecwhite Can you set to 'in progress' when you've started on this?

**Comment by mariecwhite** [comment]
The new importer requires changes in TF that haven't been officially released. These changes are available in tf-nightly but it has some breaking API changes that are not compatible with the model libraries HuggingFace Transformers and Keras (see https://github.com/huggingface/transformers/issues/22421). We will need to wait until TF 2.13 is released or an RC version.

**Comment by jpienaar** [comment]
Could we just use the previous iree-import-tf binary? E.g., use that specific tool version for those models that need it and upstream python API for rest. However the StableHLO is generated just needs to be noted somewhere, but here we just consume the serialized StableHLO.

**Comment by allieculp** [comment]
@mariecwhite I believe #13445 addresses this issue - can you confirm it's in progress?

**Comment by mariecwhite** [comment]
Correct, that PR uses stablehlo dumps instead of SavedModel. We're seeing a 2x increase in compilation time that we'll need to debug. Also, it uses 'mhlo' as the input type since 'stablehlo_experimental' is resulting in errors. We can make the switch once stablehlo is ready.

**Comment by allieculp** [comment]
@mariecwhite is this fixed with #13445 ?

**Comment by mariecwhite** [comment]
Yes fixed!
