### ISSUE TITLE
[Epic] Convert to using TF Python API & reap the benefits in CI and benchmarks

### ISSUE THREAD

**Issue by julianwa** [iree-org/iree#13043]
```[tasklist]
### Tasks
- [x] #13025 
- [ ] #13033 
- [x] #13037
```

**Comment by julianwa** [comment]
@stellaraccident @jpienaar can you confirm there are no big items that are not covered in the above list?

**Comment by jpienaar** [comment]
Could we just use https://github.com/openxla/iree/issues/13037 and convert the items to tasks? (I'm not sure what this is supposed to track that converted tasks from that task list there doesn't do - I can see migrating TF benchmarks different, but that could be added to the task list there).

**Comment by benvanik** [comment]
(+1 to using #13037)

**Comment by julianwa** [comment]
> Could we just use https://github.com/openxla/iree/issues/13037 and convert the items to tasks? (I'm not sure what this is supposed to track that converted tasks from that task list there doesn't do - I can see migrating TF benchmarks different, but that could be added to the task list there). 

It doesn't matter to me provided your end result is an Epic that includes the superset of all of these PRS/tasks. Copy these there and rename the other or extract some of the tasks from the other and copy here. I created this because it wasn't clear if 13037 was meant to be a subset or the overall thing. I want one issue where I can follow the deps to get overall history and status of the effort.

**Comment by allieculp** [comment]
@jpienaar @julianwa Where did we land on this Epic? Are we switching to #13037 or leaving this here?

**Comment by julianwa** [comment]
If nobody does the work to rebase on #13037, I suggest we leave as-is.

**Comment by allieculp** [comment]
@jpienaar Please provide an update on this Epic - looks like WIP?

**Comment by jpienaar** [comment]
Fixed 3 items pending from https://github.com/openxla/iree/issues/13037 , final item there @ScottTodd self-assigned. I'm not doing any work in 2nd item here.

**Comment by allieculp** [comment]
@julianwa @jpienaar Seems like we have a disconnect on this Epic, particularly task #13033 . Should we adjust? Rename or include #13037 ?

**Comment by julianwa** [comment]
@mariecwhite has a PR out for #13033: #13445 (Although it's possible there are follow-ons.)

I think we're getting close to completing this Epic.

**Comment by allieculp** [comment]
Update today, #13033 is in progress by Marie with #13445.
Scott is finishing docs for #13037 this week.

**Comment by julianwa** [comment]
Looks like all of the tasks here were completed! marking done, but re-open if we missed something.

**Comment by jpienaar** [comment]
@vmurali ran into issue whereby we are still importing TFLite models IREE side rather than using TOSA input which introduces a linkage by way of LLVM repo here on TOSA op set. That introduces issues when dialect changes.

**Comment by allieculp** [comment]
@jpienaar Do we need to reopen this?

**Comment by ScottTodd** [comment]
> @vmurali ran into issue whereby we are still importing TFLite models IREE side rather than using TOSA input which introduces a linkage by way of LLVM repo here on TOSA op set. That introduces issues when dialect changes.

That was already discussed on https://github.com/openxla/iree/issues/13037, with docs added in https://github.com/openxla/iree/pull/13065. What's missing?

**Comment by vmurali** [comment]
> @vmurali ran into issue whereby we are still importing TFLite models IREE side rather than using TOSA input which introduces a linkage by way of LLVM repo here on TOSA op set. That introduces issues when dialect changes.

It was because of integrate (https://github.com/openxla/iree/pull/13666)
