### ISSUE TITLE
[Vulkan] Failed to legalize operation 'gpu.subgroup_mma_store_matrix' 

### ISSUE THREAD

**Issue by yzhang93** [iree-org/iree#13051]
### What happened?

Several dispatches of Unet model failed with
```unknown>:0: error: failed to legalize operation 'gpu.subgroup_mma_store_matrix' that was explicitly marked illegal```

Here's the full [error message](https://storage.googleapis.com/shark-public/vivian/error.txt)  

### Steps to reproduce your issue

1. Download the latest [Unet model](https://storage.googleapis.com/shark-public/vivian/unet_1_64_512_512_fp16_stable-diffusion-2-1-base_vulkan_torch.mlir)
2. Compile command for Vulkan
iree-compile --iree-input-type=none --iree-hal-target-backends=vulkan --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs -iree-vulkan-target-triple=rdna3-7900-linux --iree-preprocessing-pass-pipeline='builtin.module(func.func(iree-flow-detach-elementwise-from-named-ops,iree-flow-convert-1x1-filter-conv2d-to-matmul,iree-preprocessing-convert-conv2d-to-img2col,iree-preprocessing-pad-linalg-ops{pad-size=32}))' unet_1_64_512_512_fp16_stable-diffusion-2-1-base_vulkan_torch.mlir -o unet.vmfb

### Version information

iree-compiler            20230412.487
iree-runtime              20230412.487

**Comment by allieculp** [comment]
@antiagainst Can you take a look at this?

**Comment by antiagainst** [comment]
Uploaded #13062 to fix this.
