### ISSUE TITLE
Move iree-import-tflite either to its own repo or into Tensorflow itself

### ISSUE THREAD

**Issue by pzread** [iree-org/iree#13061]
According to #13037, we likely want to stop building iree-import-tflite in IREE and maybe switch to using Tensorflow Python API to import tflite models.

**Comment by pzread** [comment]
@jpienaar correct me if the description is wrong. I also want to use the new Python-API based iree-import-tflite to import tflite models for CI benchmarks.

**Comment by jpienaar** [comment]
SG, also what Stella mentioned wrt using pinned version is good. I have an idea of how to do this rather minimally (its ~4 files at this point, so probably 200 loc and I should have it done by end of week)

**Comment by allieculp** [comment]
@jpienaar Can I set to P1 in progress?

**Comment by jpienaar** [comment]
Sure, I've already landed multiple changes here :) (TF repo side). Post moving the passes I may need help with invoking the Python API this side and bumping revisions.

**Comment by jpienaar** [comment]
https://github.com/tensorflow/tensorflow/commit/f400ea3878424f26ea66a22bf2b0d3e74883fdbb was last one to move all the parts, haven't checked if it made it into nightly.

**Comment by jpienaar** [comment]
With tf-nightly at head:

```python
from tensorflow.python.pywrap_mlir import experimental_tflite_to_tosa_bytecode
experimental_tflite_to_tosa_bytecode("64.tflite", "64.mlirbc")
```

```sh
../iree-build/tools/iree-compile --iree-input-type=tosa  --iree-hal-target-backends=llvm-cpu 64.mlirbc -o 64.vmfb
../iree-build/tools/iree-run-module --module=64.vmfb --function=main --input="1x64xi32=1"
```

This could probably have all been done in Python.

(@dellis23 I used the example from your issue, for the shape I just looked at the textual format of MLIR bytecode output, the name of main graph is just main, the subgraphs have names but technically only for debugging TFLite side).

**Comment by dellis23** [comment]
@jpienaar Putting this error here for posterity:

```shell
$ iree-compile --iree-input-type=tosa  --iree-hal-target-backends=llvm-cpu 64.mlirbc -o 64-tfnightly.vmfb
64.mlirbc:0:0: error: bytecode version 1 is newer than the current version 0
```

I'm running on tf-nightly and iree nightly.  I'm guessing since the latest IREE nightly published is from February that I need to be building directly from the repo.

Edit: indeed, installing directly from the repo via `pip install -e compiler/` worked (as well as `pip install -e runtime/`).

**Comment by ScottTodd** [comment]
> I'm guessing since the latest IREE nightly published is from February that I need to be building directly from the repo.

The latest IREE _stable_ release (published on the official pypi package index) is from February. We publish nightly releases to https://openxla.github.io/iree/pip-release-links.html, which you can install via `python -m pip install [IREE PACKAGES HERE] --find-links https://openxla.github.io/iree/pip-release-links.html`. See https://openxla.github.io/iree/bindings/python/#prebuilt-packages

**Comment by jpienaar** [comment]
I think we may have some leftover references to old repo and then pip doesn't follow redirect (well could even be in folks bash history - really seems like pip should warn!)

**Comment by dellis23** [comment]
Yeah, I definitely installed from the pip-release-links page URL, but it looks like I was indeed using the `iree-org.github.io` address.
