### ISSUE TITLE
stablehlo.dot_general incorrectly throws error claiming batching dimension sizes don't match  

### ISSUE THREAD

**Issue by phoenix-meadowlark** [iree-org/iree#13085]
### What happened?

`iree-compile` incorrectly throws the following error when attempting to compile a `dot_general` call in GPT3's decoder:

```mlir
/tmp/dot_general_batching.mlir:9:10: 
  error: batching dimension sizes must match for lhs/rhs
    %0 = "stablehlo.dot_general"(%arg0, %arg1) {
      dot_dimension_numbers = #stablehlo.dot<
        lhs_batching_dimensions = [0, 1],
        rhs_batching_dimensions = [0, 2],
        lhs_contracting_dimensions = [2],
        rhs_contracting_dimensions = [3]
      >,
      precision_config = [
        #stablehlo<precision DEFAULT>,
        #stablehlo<precision DEFAULT>
      ]} : (tensor<1x2x3xf32>, tensor<1x4x2x3xf32>) -> tensor<1x2x4xf32>
```

The batching sizes for `lhs` and `rhs` are both `[1, 2]`, so they both match. Removing the second dimension from `rhs` avoids the error, but the issue is not as simple as unmatched unspecified dimensions always leading to failures.

Related to #12873

### Steps to reproduce your issue

```python
import jax
import jax.numpy as jnp


class DotGeneral(iree.jax.Program):

  def decode(
      self,
      x=jax.core.ShapedArray([1, 2, 3], jnp.float32),
      y=jax.core.ShapedArray([1, 4, 2, 3], jnp.float32),
  ):
    return self._dot_general(x, y)

  @iree.jax.kernel
  def _dot_general(x, y):
    return jax.lax.dot_general(
        x,
        y,
        [
            [
                [2],  # lhs_contracting_dimensions
                [3],  # rhs_contracting_dimensions
            ],
            [
                [0, 1],  # lhs_batching_dimensions
                [0, 2],  # rhs_batching_dimensions
            ],
        ],
    )
```

```mlir
module @dot_general {
  func.func @decode(%arg0: tensor<1x2x3xf32>, %arg1: tensor<1x4x2x3xf32>) -> tensor<1x2x4xf32> {
    %0 = call @jit__dot_general$main(%arg0, %arg1) : (tensor<1x2x3xf32>, tensor<1x4x2x3xf32>) -> tensor<1x2x4xf32>
    return %0 : tensor<1x2x4xf32>
  }
  func.func private @jit__dot_general$main(%arg0: tensor<1x2x3xf32> {jax.arg_info = "x", mhlo.sharding = "{replicated}"}, %arg1: tensor<1x4x2x3xf32> {jax.arg_info = "y", mhlo.sharding = "{replicated}"}) -> (tensor<1x2x4xf32> {jax.result_info = "", mhlo.sharding = "{replicated}"}) {
    %0 = stablehlo.dot_general %arg0, %arg1, batching_dims = [0, 1] x [0, 2], contracting_dims = [2] x [3], precision = [DEFAULT, DEFAULT] : (tensor<1x2x3xf32>, tensor<1x4x2x3xf32>) -> tensor<1x2x4xf32>
    return %0 : tensor<1x2x4xf32>
  }
}
```

```shell
iree-compile \
  --iree-hal-target-backends=llvm-cpu \
  --iree-input-type=mhlo \
  /tmp/dot_general_batching.mlir \
  -o /tmp/dot_general_batching.vmfb
```

### What component(s) does this issue relate to?

Frontends, Compiler

### Version information

40ecb037fc0ed22fe4b60f01ed84011d88c2e413

**Comment by jpienaar** [comment]
@burmako could you dispatch this? Seems like verifier issue (unless it is semantics one)

**Comment by burmako** [comment]
@jpienaar I was just looking at this too. Also thought this is a verifier issue, but at least the snippet in question passes verification:

```
$ cat ~/example.mlir
func.func @test(%arg0: tensor<1x2x3xf32>, %arg1: tensor<1x4x2x3xf32>) -> tensor<1x2x4xf32> {
  %0 = "stablehlo.dot_general"(%arg0, %arg1) {
    dot_dimension_numbers = #stablehlo.dot<
      lhs_batching_dimensions = [0, 1],
      rhs_batching_dimensions = [0, 2],
      lhs_contracting_dimensions = [2],
      rhs_contracting_dimensions = [3]
    >,
    precision_config = [
      #stablehlo<precision DEFAULT>,
      #stablehlo<precision DEFAULT>
    ]} : (tensor<1x2x3xf32>, tensor<1x4x2x3xf32>) -> tensor<1x2x4xf32>
  return %0 : tensor<1x2x4xf32>
}

$ build/bin/stablehlo-opt ~/example.mlir
module {
  func.func @test(%arg0: tensor<1x2x3xf32>, %arg1: tensor<1x4x2x3xf32>) -> tensor<1x2x4xf32> {
    %0 = stablehlo.dot_general %arg0, %arg1, batching_dims = [0, 1] x [0, 2], contracting_dims = [2] x [3], precision = [DEFAULT, DEFAULT] : (tensor<1x2x3xf32>, tensor<1x4x2x3xf32>) -> tensor<1x2x4xf32>
    return %0 : tensor<1x2x4xf32>
  }
}
```

Could it be a pass that accidentally transforms valid IR into invalid IR? I wonder if there is an easy way to see a printout of the invalid IR.

**Comment by burmako** [comment]
Apologies - I was trying to assign @sdasgup3, but I don't think I succeeded at that. Jacques, can you do the assignment on your side? Most likely I don't have sufficient permissions.

**Comment by jpienaar** [comment]
I can't either - @sdasgup3 could you look at this and or file an issue StableHLO repo side and I can mark as closed. (I thought anyone inside openxla org could be assigned ... perhaps missing invite acceptance?)

`--mlir-print-ir-after-failure` should print out all on failure.

**Comment by sdasgup3** [comment]
@jpienaar I am on it.

**Comment by sdasgup3** [comment]
Hello All,


IMO it is the [MHLOToMHLOPreprocessing](https://github.com/openxla/iree/blob/26a145abcd31f6756ac6207f3afddf8d65616a6c/compiler/src/iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp#L312) pass which converts a valid dot general to invalid one. 
The function, among other things, does the followings:
1. rewrites, using transposes,  `mhlo.dot_general` so that `lhs` shape becomes `{batch_dims, parallel_dims, contraction_dims}` and `rhs` shape becomes `{batch_dims, contraction_dims, parallel_dims}`.
2. Reshapes the `lhs` and `rhs` to collapse the multiple batching, contracting and parallel dimensions so that at the end of this reshape there will be only 3 dimensions. 

But (2) is performed only when [size(shape) > 3](https://github.com/openxla/iree/blob/26a145abcd31f6756ac6207f3afddf8d65616a6c/compiler/src/iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp#L298). Maybe the assumption with `size(shape) < 3` is that the shape is already as expected.
 
In the running example, `lhs_shape = [1(b),2(b),3(c)]` and `rhs_shape = [1(b), 4(p), 2(b), 3(c)]`, where `b = batch dimension, p=parallel dimension and c=contracting dimension`. 

As `size(rhs_shape) > 3`, the reshape happens after the transpose, but `lhs_shape` does not get re-shaped as `size <=3`.  

Here is the dump of the IR after the `MHLOToMHLOPreprocessing` pass after which the error is thrown 

```
"func.func"() ({
^bb0(%arg0: tensor<1x2x3xf32>, %arg1: tensor<1x4x2x3xf32>):
  %0 = "mhlo.transpose"(%arg1) {permutation = dense<[0, 2, 3, 1]> : tensor<4xi64>} : (tensor<1x4x2x3xf32>) -> tensor<1x2x3x4xf32>
  %1 = "mhlo.reshape"(%0) : (tensor<1x2x3x4xf32>) -> tensor<2x3x4xf32>
  %2 = "mhlo.dot_general"(%arg0, %1) {dot_dimension_numbers = #mhlo.dot<lhs_batching_dimensions = [0], rhs_batching_dimensions = [0], lhs_contracting_dimensions = [2], rhs_contracting_dimensions = [1]>, precision_config = [#mhlo<precision DEFAULT>, #mhlo<precision DEFAULT>]} : (tensor<1x2x3xf32>, tensor<2x3x4xf32>) -> tensor<1x2x4xf32>
  "func.return"(%2) : (tensor<1x2x4xf32>) -> ()
}) {function_type = (tensor<1x2x3xf32>, tensor<1x4x2x3xf32>) -> tensor<1x2x4xf32>, sym_name = "test"} : () -> ()
```


@jpienaar If the above reasoning looks good, should we keep it open in the current repo? 

A potential fix could be to make sure that in the event of `size(shape) <= 3`, the `lhs` shape follows  `[collapsed_batch_dim, collapsed_parallel_dim, collapsed_contracting_dim]` and  `rhs` shape follows `[collapsed_batch_dim, collapsed_contracting_dim, collapsed_parallel_dim]`.

**Comment by jpienaar** [comment]
Yes, leave it open here (did `--mlir-print-ir-after-failure` help or how did you see this?)

**Comment by sdasgup3** [comment]
>> did --mlir-print-ir-after-failure help or how did you see this?

I used the exact switch to get the dump :). I looked for something similar to llvm-opt-tool's switch `print-after-all` and got to know about this super useful savior. Thanks for pointing though!

**Comment by phoenix-meadowlark** [comment]
I attempted to compile this after rebuilding IREE at head with #13153 applied and the faulty rewrite seems to have persisted. Including `--mlir-print-ir-after-failure` this is the error I'm seeing:

```shell
iree-compile \
  --iree-hal-target-backends=llvm-cpu \
  --iree-input-type=mhlo \
  --mlir-print-ir-after-failure \
  /tmp/dot_general_batching.mlir \
  -o /tmp/dot_general_batching.vmfb
```
```mlir
// -----// IR Dump After MHLOToMHLOPreprocessing Failed (iree-mhlo-to-mhlo-preprocessing) //----- //
"func.func"() ({
^bb0(%arg0: tensor<1x2x3xf32>, %arg1: tensor<1x4x2x3xf32>):
  %0 = "mhlo.transpose"(%arg1) {permutation = dense<[0, 2, 3, 1]> : tensor<4xi64>} : (tensor<1x4x2x3xf32>) -> tensor<1x2x3x4xf32>
  %1 = "mhlo.reshape"(%0) : (tensor<1x2x3x4xf32>) -> tensor<2x3x4xf32>
  %2 = "mhlo.dot_general"(%arg0, %1) {
    dot_dimension_numbers = #mhlo.dot<
      lhs_batching_dimensions = [0],
      rhs_batching_dimensions = [0],
      lhs_contracting_dimensions = [2],
      rhs_contracting_dimensions = [1]
    >,
    precision_config = [
      #mhlo<precision DEFAULT>, 
      #mhlo<precision DEFAULT>
    ]} : (tensor<1x2x3xf32>, tensor<2x3x4xf32>) -> tensor<1x2x4xf32>
  "func.return"(%2) : (tensor<1x2x4xf32>) -> ()
}) {arg_attrs = [{jax.arg_info = "x", mhlo.sharding = "{replicated}"}, {jax.arg_info = "y", mhlo.sharding = "{replicated}"}], function_type = (tensor<1x2x3xf32>, tensor<1x4x2x3xf32>) -> tensor<1x2x4xf32>, res_attrs = [{jax.result_info = "", mhlo.sharding = "{replicated}"}], sym_name = "jit__dot_general$main", sym_visibility = "private"} : () -> ()

/tmp/dot_general_batching.mlir:9:10: error: batching dimension sizes must match for lhs/rhs
    %0 = "stablehlo.dot_general"(%arg0, %arg1) {dot_dimension_numbers = #stablehlo.dot<lhs_batching_dimensions = [0, 1], rhs_batching_dimensions = [0, 2], lhs_contracting_dimensions = [2], rhs_contracting_dimensions = [3]>, precision_config = [#stablehlo<precision DEFAULT>, #stablehlo<precision DEFAULT>]} : (tensor<1x2x3xf32>, tensor<1x4x2x3xf32>) -> tensor<1x2x4xf32>
         ^
```

It looks like this is probably coming from the MHLO dependency? Does it make sense to triage this here?

**Comment by jpienaar** [comment]
I'm not seeing this:

```sh
$ git pull
$ git submodule update --init -j 8
$ cmake --build ../iree-build --target iree-compile
$ ./tools/iree-compile --iree-hal-target-backends=llvm-cpu \
                                             --iree-input-type=mhlo /tmp/t4.mlir -o /tmp/t4.vmfb
```

with /tmp/t4.mlir being

```mlir
module @dot_general {
  func.func @decode(%arg0: tensor<1x2x3xf32>, %arg1: tensor<1x4x2x3xf32>) -> tensor<1x2x4xf32> {
    %0 = call @jit__dot_general$main(%arg0, %arg1) : (tensor<1x2x3xf32>, tensor<1x4x2x3xf32>) -> tensor<1x2x4xf32>
    return %0 : tensor<1x2x4xf32>
  }
  func.func private @jit__dot_general$main(%arg0: tensor<1x2x3xf32> {jax.arg_info = "x", mhlo.sharding = "{replicated}"}, %arg1: tensor<1x4x2x3xf32> {jax.arg_info = "y", mhlo.sharding = "{replicated}"}) -> (tensor<1x2x4xf32> {jax.result_info = "", mhlo.sharding = "{replicated}"}) {
    %0 = stablehlo.dot_general %arg0, %arg1, batching_dims = [0, 1] x [0, 2], contracting_dims = [2] x [3], precision = [DEFAULT, DEFAULT] : (tensor<1x2x3xf32>, tensor<1x4x2x3xf32>) -> tensor<1x2x4xf32>
    return %0 : tensor<1x2x4xf32>
  }
}
```

**Comment by phoenix-meadowlark** [comment]
Ah it looks like I need to make sure the python version of `iree-compile` doesn't supersede the built version – thanks!!
