### ISSUE TITLE
Create benchmarks for a model-specific set of matmuls, batch_matmul, and einsum shapes

### ISSUE THREAD

**Issue by mattwalsh** [iree-org/iree#13086]
### Request description

Steps:
1. Take the [list of matmul ops](https://gist.github.com/silvasean/6f89b5d6817b2bf06601292895e643f7) from @silvasean 
2. Using @manishucsd [Dispatch Profiler](https://github.com/openxla/iree/pull/12559), create the scripting needed to sweep the items in 1.
3. While the items were collected as f32, for each test also cover int8 and f16.

once we have a preliminary version of this put together we can then extend for tuning configuration and more

### What component(s) does this issue relate to?

Other

**Comment by allieculp** [comment]
@julianwa @jpienaar Looking for a resource that can help with this FYI

**Comment by silvasean** [comment]
I have a couple other lists of sizes. Once we have the basic infra in place I can provide more for other workloads of interest.

**Comment by allieculp** [comment]
@manishucsd Assigning to you for now as a P1 item.

**Comment by julianwa** [comment]
Similar to #12899, what data do we want this benchmark to produce?

**Comment by allieculp** [comment]
@julianwa Is Kojo picking up this issue?

**Comment by allieculp** [comment]
Might need a rename? Evolve dispatch profiler with problematic sizes

**Comment by julianwa** [comment]
> Might need a rename? Evolve dispatch profiler with problematic sizes

I gathered all related work in #13259, updated the name of this issue, and linked it there.

**Comment by allieculp** [comment]
@KoolJBlack Any update on this issue?

**Comment by silvasean** [comment]
Matmul lists to add to the tool:
AlphaFold: protein size 702: https://gist.github.com/silvasean/e6e6b587ba810d740050311f0803906b
FermiNet: https://gist.github.com/silvasean/6f89b5d6817b2bf06601292895e643f7
Psiformer: https://gist.github.com/silvasean/df97e401b410e0baa9fa6871b678344e

**Comment by manishucsd** [comment]
> Matmul lists to add to the tool: AlphaFold: protein size 702: https://gist.github.com/silvasean/e6e6b587ba810d740050311f0803906b FermiNet: https://gist.github.com/silvasean/6f89b5d6817b2bf06601292895e643f7 Psiformer: https://gist.github.com/silvasean/df97e401b410e0baa9fa6871b678344e

The types of operations in the list above include:
- Matmul              
- Batch Matmul   
- Einsum 

IREE dispatch profiler has Matmul and Batch Matmul. To fully realize this in IREE dispatch profiler, we need to add einsum in the dispatch profiler.

**Comment by allieculp** [comment]
@mattwalsh Should we remove einsum from this issue?

**Comment by allieculp** [comment]
@KoolJBlack Can you update this issue?

**Comment by allieculp** [comment]
From meeting: @KoolJBlack to edit this issue as needed to make it up to date.

**Comment by allieculp** [comment]
Closing as this issue is getting stale - we will open up more specific issues as needed per model instead.
