### ISSUE TITLE
Separate out Cuda tests that depend on specific architecture

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#13095]
It's not great that we have tests depending on specific device architectures. @ThomasRaoux, can we generalize these tests or find a different way to filter them in the build system?

https://github.com/openxla/iree/blob/60b8ef4aa4bfc1db2e4ecafb6f3c8dc417a4da2a/tests/transform_dialect/cuda/mma_reduction_layout_analysis.mlir#L26-L34

(changing tags here to unblock our infra process is okay though)

_Originally posted by @ScottTodd in https://github.com/openxla/iree/pull/13077#discussion_r1165727354_

**Comment by GMNGeoffrey** [comment]
It's fine to have some tests that can only run on a specific architecture when they're arch-specific tests, but we don't want to in general limit our GPU tests to that. Could we separate them out and specifically label them? This is similar to the case of Vulkan fp16:

https://github.com/openxla/iree/blob/544f7856b7e1cf6a8079cc3488376cd826e34fab/tests/e2e/vulkan_specific/BUILD.bazel#L30

**Comment by ThomasRaoux** [comment]
> It's fine to have some tests that can only run on a specific architecture when they're arch-specific tests, but we don't want to in general limit our GPU tests to that. Could we separate them out and specifically label them? This is similar to the case of Vulkan fp16:

I agree, I don't think we limit our GPU tests to that, it's just that those are meant to test tensorcore feature. So we should be adding a new tag for that? Let me file an issue.

**Comment by GMNGeoffrey** [comment]
Yes :-) I already created this issue though!

**Comment by ThomasRaoux** [comment]
> Yes :-) I already created this issue though!

ok, let me close the one I created

**Comment by ThomasRaoux** [comment]
duh this is the issue...

**Comment by ScottTodd** [comment]
I think this might have been fixed on https://github.com/openxla/iree/pull/13077 ? We have a bunch of hardware or shader-model -dependent tests but I think they are all tagged at the moment.
