### ISSUE TITLE
Add a tag to mark tests depending on tensorcore for GPU

### ISSUE THREAD

**Issue by ThomasRaoux** [iree-org/iree#13097]
### Request description

In order to differentiate tests that can run on any GPU to the one that require tensorcore features we should add new tag. 
There is already such tag for f16 support on Vulkan:
https://github.com/openxla/iree/blob/544f7856b7e1cf6a8079cc3488376cd826e34fab/tests/e2e/vulkan_specific/BUILD.bazel#L30
We should add a new tag `cuda_use_sm_80_tensor_core`

CC: @GMNGeoffrey @ScottTodd 

### What component(s) does this issue relate to?

Other

**Comment by GMNGeoffrey** [comment]
Duplicate of #13095
