### ISSUE TITLE
Stabilize `ukernel.generic`'s lowering of `memref` operands

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#13096]
When lowered to a function call, `ukernel.generic` is currently lowering each `memref` operand to buffer, offset, and N-1 strides (for rank N, that is, all but the innermost stride). That encodes an assumption that the memref's innermost dimension tends to be contiguous. That assumption is a bit of a departure from what the name `ukernel.generic` suggests.

Consider changing this to lowering all N stride. Also consider maybe also passing all N size values. Even more redundancy but more true to the idea that `ukernel.generic` just works, passing all relevant fields by default, at risk of being redundant.

#13053 is introducing a `ukernel.generic_raw` that passes 0 strides. This will allow us to migrate all existing ukernels to that. That will free us to fix the semantics of `ukernel.generic` without having to adjust those other ukernels.

**Comment by MaheshRavishankar** [comment]
Thanks for filing the issue.
