### ISSUE TITLE
synchronization.c:(.text+0x55): undefined reference to `pthread_mutex_trylock'

### ISSUE THREAD

**Issue by RechieKho** [iree-org/iree#13114]
### What happened?

I am compiling the samples. I downloaded the tools ([iree-dist](https://github.com/openxla/iree/releases/tag/candidate-20230415.490]) and then set `IREE_HOST_BIN_DIR` to the `bin` directory in the archive in cmake. With `IREE_HAL_EXECUTABLE_LOADER_VMVX_MODULE ` and `IREE_HAL_DRIVER_LOCAL_SYNC ` turned on, I compile the samples. And I met the problem, the pthread is not linked to `libiree_base_internal_synchronization.a`.

The linker error:
```
/usr/bin/ld: ../../../../dist/misc/lib/libiree_base_internal_synchronization.a(synchronization.c.o): in function `iree_mutex_try_lock':
synchronization.c:(.text+0x55): undefined reference to `pthread_mutex_trylock'
collect2: error: ld returned 1 exit status
```

Here is the compile command:
```
ccache /usr/bin/c++ -O3 -DNDEBUG -lm -lpthread CMakeFiles/iree_samples_simple_embedding_simple_embedding_vmvx_sync.dir/device_vmvx_sync.c.o CMakeFiles/iree_samples_simple_embedding_simple_embedding_vmvx_sync.dir/simple_embedding.c.o -o ../../../../dist/misc/bin/simple_embedding_vmvx_sync  ../../../../dist/misc/lib/libiree_samples_simple_embedding_simple_embedding_test_bytecode_module_vmvx_c.a ../../../../dist/misc/lib/libiree_base_base.a ../../../../dist/misc/lib/libiree_hal_hal.a ../../../../dist/misc/lib/libiree_hal_drivers_local_sync_sync_driver.a ../../../../dist/misc/lib/libiree_hal_local_local.a ../../../../dist/misc/lib/libiree_hal_local_loaders_vmvx_module_loader.a ../../../../dist/misc/lib/libiree_modules_hal_hal.a ../../../../dist/misc/lib/libiree_vm_bytecode_module.a ../../../../dist/misc/lib/libiree_base_internal_fpu_state.a ../../../../dist/misc/lib/libiree_hal_utils_buffer_transfer.a ../../../../dist/misc/lib/libiree_hal_utils_deferred_command_buffer.a ../../../../dist/misc/lib/libiree_hal_utils_resource_set.a ../../../../dist/misc/lib/libiree_base_internal_arena.a ../../../../dist/misc/lib/libiree_base_internal_atomic_slist.a ../../../../dist/misc/lib/libiree_hal_utils_semaphore_base.a ../../../../dist/misc/lib/libiree_vm_bytecode_utils_utils.a ../../../../dist/misc/lib/libflatcc_parsing.a -lm -lpthread ../../../../dist/misc/lib/libiree_hal_local_executable_loader.a ../../../../dist/misc/lib/libiree_hal_local_executable_environment.a ../../../../dist/misc/lib/libiree_modules_vmvx_vmvx.a ../../../../dist/misc/lib/libiree_base_internal_cpu.a ../../../../dist/misc/lib/libiree_builtins_ukernel_ukernel.a ../../../../dist/misc/lib/libiree_builtins_ukernel_arch_x86_64_x86_64.a ../../../../dist/misc/lib/libiree_builtins_ukernel_arch_x86_64_x86_64_avx2_fma.a ../../../../dist/misc/lib/libiree_builtins_ukernel_arch_x86_64_x86_64_avx512_base.a ../../../../dist/misc/lib/libiree_builtins_ukernel_arch_x86_64_x86_64_avx512_vnni.a ../../../../dist/misc/lib/libiree_modules_hal_utils_buffer_diagnostics.a ../../../../dist/misc/lib/libiree_modules_hal_types.a ../../../../dist/misc/lib/libiree_hal_hal.a ../../../../dist/misc/lib/libiree_base_internal_path.a ../../../../dist/misc/lib/libiree_base_internal_synchronization.a ../../../../dist/misc/lib/libiree_vm_impl.a ../../../../dist/misc/lib/libiree_base_base.a ../../../../dist/misc/lib/libiree_base_tracing.a
```

And it is fixed when I add the `-lpthread` at the **VERY** end of the compile command. 

So I tried to edit the cmake file (thirdparty/iree/runtime/src/iree/base/internal/CMakeLists.txt):
On line 293
```
iree_cc_library(
  NAME
    synchronization
  HDRS
    "call_once.h"
    "synchronization.h"
  SRCS
    "synchronization.c"
  DEPS
    pthread # I added this 
    ::internal
    iree::base
    iree::base::core_headers
    iree::base::tracing
  PUBLIC
)
```
And the compilation is a success.

So yea, the solution is to include pthread as a dependency to the `synchronization` module, but I'm not sure adding pthread like that will result issue when compiling cross-platform. 

### Steps to reproduce your issue

1. Compile the sample with `IREE_HOST_BIN_DIR` set to [`iree-dist`](https://github.com/openxla/iree/releases/tag/candidate-20230415.490)'s `bin` directory.

### What component(s) does this issue relate to?

Runtime, Other

### Version information

candidate-20230408.483 for the source I am compiling 
[iree candidate candidate-20230415.490](https://github.com/openxla/iree/releases/tag/candidate-20230415.490) for the tools I am using. 

### Additional context

I'm trying to embedding the runtime into Godot. I need to compile the sample to check whether it is working or not. I am compiling the samples from git submodule.

**Comment by RechieKho** [comment]
I'll handle this by slapping a cmake generator expression into the dependency for the sake of cross-compilation.

**Comment by benvanik** [comment]
This should be done with https://cmake.org/cmake/help/latest/module/FindThreads.html instead. I'm not actually sure how anything works today given we aren't doing this and would like to root cause why you're having issues but none of our other builds are.

**Comment by RechieKho** [comment]
Yes, I am confused as well that why only mine sucked. 

For the cmake generator expression, I read the build files. It handles threads by using raw string "-lthread" so I was thought to follow the raw way, which is use some raw string as well. Cool that FindThreads is acceptable.

**Comment by ScottTodd** [comment]
This comes to mind regarding FindThreads: https://github.com/openxla/iree/pull/6258

**Comment by RechieKho** [comment]
So this happens before #6466

**Comment by RechieKho** [comment]
And one thing, I scan through the synchronization.c and the build script (CMakeLists.txt) regarding it. It seems like pthread is a must, at least on linux. Then why giving option for disabling pthread? (IREE_ENABLE_THREADING)

**Comment by benvanik** [comment]
Threading is not a must on any platform. IREE_ENABLE_THREADING allows you to disable threading which is useful if you don't need it or your platform doesn't support it. See IREE_SYNCHRONIZATION_DISABLE_UNSAFE which neuters the entire synchronization implementation and works without pthreads. IREE is a library and is reactive to the needs of the hosting application and deployment scenario and we don't add required dependencies unless absolutely required (and scoped appropriately).
