### ISSUE TITLE
[spirv][vulkan] Add missing e2e runtime i8 matmul tests

### ISSUE THREAD

**Issue by kuhar** [iree-org/iree#13123]
We recently had a regression in the Mali codegen path that went unnoticed: https://reviews.llvm.org/D148470.

The test should check the results for numerical correctness.

**Comment by kuhar** [comment]
cc: @antiagainst

**Comment by allieculp** [comment]
@antiagainst Please help to add a priority for this!

**Comment by kuhar** [comment]
After talking with @antiagainst, we should add the dot prod extension/capabilities to the nvidia triple and have the test run on nvidia gpu in CI.

We need to wait with this until the mlir fix (https://reviews.llvm.org/D148470) gets imported into iree.
