### ISSUE TITLE
Compile Time and 5x Latency Regression on CUDA

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#13189]
### What happened?

Compilation of some T5 models is taking >5 hours for batches 64 and 512. This is a recent regression as earlier this week we were able to compile all T5 models in under 15 mins (see this CI run: https://github.com/openxla/iree/actions/runs/4738436860/jobs/8412407639). 

### Steps to reproduce your issue

1. Download SavedModel: https://storage.googleapis.com/iree-model-artifacts/tensorflow/tf_models_2.12.0_1681193933/T5_LARGE/batch_512/tf-model.tar.gz

2. Import:

iree-import-tf --output-format=mlir-bytecode --tf-import-type=savedmodel_v2 --tf-savedmodel-exported-names=forward <saved_model> -o </path/to/model.mlirbc>

3. Compile:

iree-compile --iree-hal-target-backends=cuda --iree-input-type=mhlo --iree-hal-cuda-llvm-target-arch=sm_80 </path/to/model.mlirbc> -o </path/to/model.vmfb>

### What component(s) does this issue relate to?

Compiler

### Version information

Rebased from 8a1182c

### Additional context

This is blocking our ability to track performance progress on large models.

**Comment by jpienaar** [comment]
Please include profile before and after. And it would be useful to summarize differences too.

**Comment by ScottTodd** [comment]
Here's some IR for one of the slow-to-compile executables: https://gist.github.com/ScottTodd/fc30c728a1d1774b799830600d21e3f1 (~9000 ops of `vector.transfer_read` -> elementwise -> `vector.transfer_write`, 1000s of `gpu.subgroup_mma_load_matrix`, `gpu.subgroup_mma_compute`, `gpu.subgroup_mma_elementwise`, `gpu.subgroup_mma_store_matrix`)

My gist isn't even uploading for the _really_ slow-to-compile executable...
Input IR:
```mlir
// -----// IR Dump Before mlir::iree_compiler::IREE::HAL::TranslateExecutablesPass (iree-hal-translate-executables) //----- //
hal.executable private @forward_dispatch_18 {
  hal.executable.variant public @cuda_nvptx_fb, target = <"cuda", "cuda-nvptx-fb", {target_arch = "sm_80"}> {
    hal.executable.export public @forward_dispatch_18_generic_512x16x512x512x64_f32 ordinal(0) layout(#hal.pipeline.layout<push_constants = 1, sets = [<0, bindings = [<0, storage_buffer, ReadOnly>, <1, storage_buffer>]>]>) {
    ^bb0(%arg0: !hal.device, %arg1: index, %arg2: index, %arg3: index, %arg4: index):
      %x, %y, %z = flow.dispatch.workgroup_count_from_dag_root %arg1, %arg2, %arg3, %arg4
      hal.return %x, %y, %z : index, index, index
    }
    builtin.module {
      func.func @forward_dispatch_18_generic_512x16x512x512x64_f32() {
        %cst = arith.constant 9.99999971E-10 : f32
        %cst_0 = arith.constant 0.000000e+00 : f32
        %c2147483648 = arith.constant 2147483648 : index
        %c2164260864 = arith.constant 2164260864 : index
        %c3238002688 = arith.constant 3238002688 : index
        %0 = hal.interface.constant.load[0] : i32
        %1 = arith.index_castui %0 {stream.alignment = 16777216 : index, stream.values = [4311744512 : index, 5385486336 : index]} : i32 to index
        %2 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c3238002688) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<512x512x16x64xf32>>
        %3 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c2164260864) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<512x512x16x64xf32>>
        %4 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c2147483648) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<512x512x16xf32>>
        %5 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%1) : !flow.dispatch.tensor<writeonly:tensor<512x16x512x512xf32>>
        %6 = flow.dispatch.tensor.load %2, offsets = [0, 0, 0, 0], sizes = [512, 512, 16, 64], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<512x512x16x64xf32>> -> tensor<512x512x16x64xf32>
        %7 = flow.dispatch.tensor.load %3, offsets = [0, 0, 0, 0], sizes = [512, 512, 16, 64], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<512x512x16x64xf32>> -> tensor<512x512x16x64xf32>
        %8 = flow.dispatch.tensor.load %4, offsets = [0, 0, 0], sizes = [512, 512, 16], strides = [1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<512x512x16xf32>> -> tensor<512x512x16xf32>
        %9 = tensor.empty() : tensor<512x16x512x512xf32>
        %10 = linalg.fill ins(%cst_0 : f32) outs(%9 : tensor<512x16x512x512xf32>) -> tensor<512x16x512x512xf32>
        %11 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4) -> (d0, d2, d1, d4)>, affine_map<(d0, d1, d2, d3, d4) -> (d0, d3, d1, d4)>, affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2, d3)>], iterator_types = ["parallel", "parallel", "parallel", "parallel", "reduction"]} ins(%6, %7 : tensor<512x512x16x64xf32>, tensor<512x512x16x64xf32>) outs(%10 : tensor<512x16x512x512xf32>) {
        ^bb0(%in: f32, %in_1: f32, %out: f32):
          %13 = arith.mulf %in, %in_1 : f32
          %14 = arith.addf %out, %13 : f32
          linalg.yield %14 : f32
        } -> tensor<512x16x512x512xf32>
        %12 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d2, d3, d1)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%11, %8 : tensor<512x16x512x512xf32>, tensor<512x512x16xf32>) outs(%9 : tensor<512x16x512x512xf32>) {
        ^bb0(%in: f32, %in_1: f32, %out: f32):
          %13 = arith.addf %in, %in_1 : f32
          %14 = arith.addf %13, %cst : f32
          linalg.yield %14 : f32
        } -> tensor<512x16x512x512xf32>
        flow.dispatch.tensor.store %12, %5, offsets = [0, 0, 0, 0], sizes = [512, 16, 512, 512], strides = [1, 1, 1, 1] : tensor<512x16x512x512xf32> -> !flow.dispatch.tensor<writeonly:tensor<512x16x512x512xf32>>
        return
      }
    }
  }
}
```

Similar pattern of vector ops -> gpu ops, but with 98000 ops (yes, _ninety-eight thousand_ ops) between `LLVMGPUVectorToGPU` and `SCFToControlFlow`

Pretty slow executable / input -> hal phase: 
![image](https://user-images.githubusercontent.com/4010439/233436147-2fa0fbb3-80cd-474c-bfff-3441c2d8f8fc.png)

Slowest executable, zoomed out: 
![image](https://user-images.githubusercontent.com/4010439/233436430-bad0dc02-49f1-4b43-a4f6-51b535d3c895.png)

**Comment by ScottTodd** [comment]
Only 15 unique hal.executables, so deduping is working well enough. Seems like vectorization / tiling is just generating a _lot_ of code for a few of the executables.

**Comment by ScottTodd** [comment]
Still collecting a trace (50GB of memory used so far...), sampling is pointing to one thread, deep in LLVM instruction code, right after `CombineInitializers` (so in `SerializeExecutables` -> `LLVMIR/ModuleTranslation`): 
![image](https://user-images.githubusercontent.com/4010439/233440023-4b8b6d75-d2b7-454c-af02-9edf9a375f7f.png)
![image](https://user-images.githubusercontent.com/4010439/233439787-0ca47275-e12a-4cda-a598-14aec10e97a8.png)
My machine has spent 30 minutes on that one thread, likely serializing that one huge executable

**Comment by benvanik** [comment]
What's the leaf there? isBlockIn...?
If we're emitting 20 million instructions in a single function it'd likely lead to things like that during LLVM codegen

**Comment by benvanik** [comment]
thought: serialize executables pass could append an int64 trace zone value of the number of ops within the executable - would at least give us a signal as to how much work we're sending down to llvm

**Comment by ScottTodd** [comment]
`isBlockInLCSSAForm`
`llvm::ScalarEvolution::visitAndClearUsers`
![image](https://user-images.githubusercontent.com/4010439/233441298-3c4f5afa-d1cc-43b3-8900-58652f295fe2.png)

**Comment by benvanik** [comment]
yeah that's probably too much IR in a loop body hitting a pathologically slow path in there - may need a "0 days since last lack of vectorization making things sad" sign :P

**Comment by ScottTodd** [comment]
Here's are some snippets from the middle of the slowest executable to compile:
```mlir
    %452729 = vector.fma %452728, %452630, %452681 : vector<16xf32>
    %452730 = vector.extract %108464[1] : vector<8xf32>
    %452731 = vector.splat %452730 : vector<16xf32>
    %452732 = vector.fma %452731, %452630, %452684 : vector<16xf32>
    %452733 = vector.extract %108465[1] : vector<8xf32>
    %452734 = vector.splat %452733 : vector<16xf32>
    %452735 = vector.fma %452734, %452630, %452687 : vector<16xf32>
    %452736 = vector.extract %108466[1] : vector<8xf32>
    %452737 = vector.splat %452736 : vector<16xf32>
    %452738 = vector.fma %452737, %452630, %452690 : vector<16xf32>
    %452739 = vector.extract %108451[2] : vector<8xf32>
    %452740 = vector.splat %452739 : vector<16xf32>
    %452741 = vector.fma %452740, %452632, %452693 : vector<16xf32>

  %62058 = vector.insert %62057, %62051 [6] : vector<16xf32> into vector<16x16xf32>
  %c57344_32872 = arith.constant 57344 : index
  %62059 = arith.addi %c57344_32872, %22 : index
  %c8192_32873 = arith.constant 8192 : index
  %62060 = arith.muli %24, %c8192_32873 : index
  %62061 = arith.addi %62059, %62060 : index
  %c16_32874 = arith.constant 16 : index
  %62062 = arith.muli %35, %c16_32874 : index
  %62063 = arith.addi %62061, %62062 : index
  %62064 = scf.for %arg0 = %c0 to %c16 step %c1 iter_args(%arg1 = %cst_0) -> (vector<16xf32>) {
    %c16_44555 = arith.constant 16 : index
    %98866 = arith.muli %arg0, %c16_44555 : index
    %98867 = arith.addi %62063, %98866 : index
    %reinterpret_cast = memref.reinterpret_cast %base_buffer_20502 to offset: [%98867], sizes: [1, 1, 1], strides: [8192, 16, 1] : memref<f32> to memref<1x1x1xf32, strided<[8192, 16, 1], offset: ?>>
    %98868 = memref.load %reinterpret_cast[%c0, %c0, %c0] : memref<1x1x1xf32, strided<[8192, 16, 1], offset: ?>>
    %98869 = vector.insertelement %98868, %arg1[%arg0 : index] : vector<16xf32>
    scf.yield %98869 : vector<16xf32>
  }
```
so not only are there ~100k ops, but many of those are used within `16xf32` loops

**Comment by benvanik** [comment]
![well there's your problem](https://user-images.githubusercontent.com/75337/233443880-7f5c03da-06a1-45e6-94de-ec14c624ddb2.png)

**Comment by ScottTodd** [comment]
Compilation is nice and fast at https://github.com/openxla/iree/commit/e19fc8ee473001780e5713ce22e3e7d973026087

![image](https://user-images.githubusercontent.com/4010439/233455673-7469066b-2b0d-4462-b6a5-3af4a502e591.png)

I can try diffing the IR to see where it diverges (I don't see that `forward_dispatch_18`)

**Comment by aaron-schneider** [comment]
Scott's going to find the commit, and figure out what to do next (set status to Inbox) to find someone to fix.

**Comment by ScottTodd** [comment]
Looking for patterns in the IR to see what changed. The IR before (from ~1 week ago) has `linalg.batch_matmul` ops, while the IR after does not.

Scanning for commits that might be relevant (could also run a bisect):
* https://github.com/openxla/iree/commit/ed174dc866c38b3cc0802f9a950b354ad373b255
* https://github.com/openxla/iree/commit/20e014b8d63264d6f4cc0ae78de27bcefc25af0e
* LLVM integrates

@manishucsd anything here ring any bells?

**Comment by ScottTodd** [comment]
Started a [`git bisect`](https://git-scm.com/docs/git-bisect), should have a culprit identified in ~4 steps x 10-15 minutes per step to build + check compile time / IR dumps

**Comment by ScottTodd** [comment]
bisect points to https://github.com/openxla/iree/commit/479900afe1467cd10f349894f758135e54d487e2
(https://github.com/openxla/iree/pull/13153 , @jpienaar , @hanhanW )

**Comment by jpienaar** [comment]
That pattern is incorrect and blocks other models. Which pass is producing that huge amount of IR?

**Comment by ScottTodd** [comment]
Here's IR before and after `iree-mhlo-to-mhlo-preprocessing` with that commit reverted: https://gist.github.com/ScottTodd/62c453547b4bb53cb1fb3709ba10b5d8

**Comment by ScottTodd** [comment]
Most of the op explosion occurs in `iree-llvmgpu-tensorcore-vectorization`.

Here's `forward_dispatch_6_generic_512x16x512x512x64_f32` before/after that pass: https://gist.github.com/ScottTodd/4435728d6b66550282b6ae64c23634c2

**Comment by ScottTodd** [comment]
I've done what I can to triage this. Who can follow-up next?

It sounds like removing the incorrect pattern in `iree-mhlo-to-mhlo-preprocessing` exposed a latent issue in `iree-llvmgpu-tensorcore-vectorization`.

**Comment by mariecwhite** [comment]
This change has also increased latency in all TF models on CUDA:

![image](https://user-images.githubusercontent.com/5143063/233534224-bb290a13-8d26-4f49-b5c9-3ef1de7f0c12.png)

![image](https://user-images.githubusercontent.com/5143063/233534322-ca8b3269-b244-4579-aa46-f0ba0522aa58.png)

**Comment by mariecwhite** [comment]
Can we revert that PR while it gets resolved? The benchmarks are now taking several hours to run instead of 15 mins.

**Comment by jpienaar** [comment]
I'd prefer not to revert as both Phoenix's model and a proprietary model runs into a failure with that faulty pattern and regression is due to triggering an underlying issue that needs to be addressed (it could be triggered by regular linalg-on-tensor input or other HLOs, so revert only helps avoid issues on a specific path). It depends on timelines and different workarounds could be considered, the "final" fix is already in progress and folks have been working towards that, but I don't think it is at "flip switch" ready yet.

For this specific case I don't know what alternatives there are with this vectorization behavior - @dcaballe is our expert there and could list some options. E.g., I heard that one option was to limit tile size. That would help consider shorter term options.

We definitely need to address this before our next stable release.

**Comment by dcaballe** [comment]
It looks like the outermost dimension (512) is fully unrolled. There should be a pass where we are tiling for vectorization and generating `subview_3` below. That subview should have [1, 1, 16, 16] sizes and not [512, 1, 16, 16] sizes if we don't want the 512 unrolling to happen. Then another `scf.for` should be generated in addition to the existing one, to iterate over the 512 size one by one:

```
    %subview_3 = memref.subview %subview[0, 0, %11, %12] [512, 1, 16, 16] [1, 1, 1, 1] : memref<512x1x32x32xf32, strided<[4194304, 262144, 512, 1], offset: ?>> to memref<512x1x16x16xf32, strided<[4194304, 262144, 512, 1], offset: ?>>
    linalg.fill {__internal_linalg_transform__ = "vectorize", lowering_config = #iree_codegen.lowering_config<tile_sizes = [[0, 1, 32, 32, 16]]>} ins(%cst_0 : f32) outs(%subview_3 : memref<512x1x16x16xf32, strided<[4194304, 262144, 512, 1], offset: ?>>)
    scf.for %arg0 = %c0 to %c64 step %c16 {
      %subview_6 = memref.subview %subview_1[0, 0, 0, %arg0] [512, 32, 1, 16] [1, 1, 1, 1] : memref<512x32x1x64xf32, strided<[524288, 1024, 64, 1], offset: ?>> to memref<512x32x1x16xf32, strided<[524288, 1024, 64, 1], offset: ?>>
      %subview_7 = memref.subview %subview_2[0, 0, 0, %arg0] [512, 32, 1, 16] [1, 1, 1, 1] : memref<512x32x1x64xf32, strided<[524288, 1024, 64, 1], offset: ?>> to memref<512x32x1x16xf32, strided<[524288, 1024, 64, 1], offset: ?>>
      %subview_8 = memref.subview %subview_6[0, %11, 0, 0] [512, 16, 1, 16] [1, 1, 1, 1] : memref<512x32x1x16xf32, strided<[524288, 1024, 64, 1], offset: ?>> to memref<512x16x1x16xf32, strided<[524288, 1024, 64, 1], offset: ?>>
      %subview_9 = memref.subview %subview_7[0, %12, 0, 0] [512, 16, 1, 16] [1, 1, 1, 1] : memref<512x32x1x16xf32, strided<[524288, 1024, 64, 1], offset: ?>> to memref<512x16x1x16xf32, strided<[524288, 1024, 64, 1], offset: ?>>
      linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4) -> (d0, d2, d1, d4)>, affine_map<(d0, d1, d2, d3, d4) -> (d0, d3, d1, d4)>, affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2, d3)>], iterator_types = ["parallel", "parallel", "parallel", "parallel", "reduction"]} ins(%subview_8, %subview_9 : memref<512x16x1x16xf32, strided<[524288, 1024, 64, 1], offset: ?>>, memref<512x16x1x16xf32, strided<[524288, 1024, 64, 1], offset: ?>>) outs(%subview_3 : memref<512x1x16x16xf32, strided<[4194304, 262144, 512, 1], offset: ?>>) attrs =  {__internal_linalg_transform__ = "vectorize", lowering_config = #iree_codegen.lowering_config<tile_sizes = [[0, 1, 32, 32, 16]]>} {
      ^bb0(%in: f32, %in_10: f32, %out: f32):
        %13 = arith.mulf %in, %in_10 : f32
        %14 = arith.addf %out, %13 : f32
        linalg.yield %14 : f32
      }
    }
```

I'm not very familiar with this pipeline but there should be a Tile or TileAndFuse pass doing that.

**Comment by MaheshRavishankar** [comment]
It should be related to https://github.com/openxla/iree/issues/13205 . We only distribute three dimensions today on CPU backend... just havent changed it to distribute all dimensions (even though `TileAndDistribute` can do that)
Then we just need to set the tile sizes of the dimensions greater than three to 1.

**Comment by allieculp** [comment]
@MaheshRavishankar @hanhanW @dcaballe Trying to follow here, who is working on this next? I think we need to update the assignee and status.

**Comment by MaheshRavishankar** [comment]
I am confused too actually... Is this a CUDA bug or CPU bug?

**Comment by mariecwhite** [comment]
It's a CUDA bug and in addition to causing a compile-time regression, it has also caused a 5x latency regression.

**Comment by MaheshRavishankar** [comment]
> It's a CUDA bug and in addition to causing a compile-time regression, it has also caused a 5x latency regression.

Is the compile time regression with CUDA backend, or all backends

**Comment by mariecwhite** [comment]
Looking at perf.iree.dev, only CUDA is affected.

**Comment by MaheshRavishankar** [comment]
Moved it to Thomas. Thomas is OOO, so assigning to Kojo for now.

**Comment by allieculp** [comment]
@KoolJBlack Let us know when you've had a chance to review this!

**Comment by manishucsd** [comment]
> @manishucsd anything here ring any bells?

This didn't hit me in my flow of improving codegen, where I compile `linalg.matmul` down to nvptx. I also discussed with  @jpienaar on this and this is expected. The issue only affects the lowering pass leading up to `linalg`.

**Comment by allieculp** [comment]
@KoolJBlack have you had a chance to review this?

**Comment by KoolJBlack** [comment]
@allieculp I will get to it later today

**Comment by KoolJBlack** [comment]
So I've done a dump and believe this issue is related to https://github.com/openxla/iree/issues/13202

Looking at the dump below `LLVMGPUTensorCoreVectorization` we're endlessly unrolling the patch dimensions which are tiled to 0. The fix in https://github.com/openxla/iree/pull/13294 should hopefully address this bug.

**Comment by ThomasRaoux** [comment]
Some of the latency regressions in MiniLM (and most likely in more of the models) come from the fact that we now fuse elementwise producer into matmul op. In general it is not a good idea but here it is worse because it makes us not use the tensorcore pipeline.

For instance those ops:
```
   %8 = linalg.fill {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[1, 32, 32, 16]]>} ins(%cst : f32) outs(%7 : tensor<12x128x128xf32>) -> tensor<12x128x128xf32>
      %9 = linalg.batch_matmul {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[1, 32, 32, 16]]>} ins(%4, %5 : tensor<12x128x32xf32>, tensor<12x32x128xf32>) outs(%8 : tensor<12x128x128xf32>) -> tensor<12x128x128xf32>
 ```
 
 Became:
```
 %20 = linalg.fill {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[1, 1, 1], [0, 0, 0, 32]]>} ins(%cst_1 : f32) outs(%19 : tensor<12x128x128xf32>) -> tensor<12x128x128xf32>
 %21 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d1, d0, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d3)>, affine_map<(d0, d1, d2, d3) -> (d2, d0, d3)>, affine_map<(d0, d1, d2, d3) -> (d2, d0, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel", "reduction"]} ins(%14, %15, %16, %17 : tensor<128x12x32xf32>, tensor<12x32xf32>, tensor<128x12x32xf32>, tensor<128x12x32xf32>) outs(%20 : tensor<12x128x128xf32>) attrs =  {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[1, 1, 1], [0, 0, 0, 32]]>} {
      ^bb0(%in: f32, %in_2: f32, %in_3: f32, %in_4: f32, %out: f32):
        %23 = arith.addf %in_3, %in_4 : f32
        %24 = arith.addf %in, %in_2 : f32
        %25 = arith.mulf %24, %23 : f32
        %26 = arith.addf %out, %25 : f32
        linalg.yield %26 : f32
      } -> tensor<12x128x128xf32>

```

This is due to the https://github.com/openxla/iree/commit/479900afe1467cd10f349894f758135e54d487e2 as pointed out by Scott.

to solve this we would need to change the fusion heuristic to prevent this assuming we want to keep this representation. We had discussed using the generic representation for matmul in the past however this is most likely not going to be a trivial change and will have performance impact on potentially many cases.
My suggestion would be to first try to revert back to a state like we had before and if we want to support the generic version of matmul work on it separately and enable it when it is ready doing it as a fix forward is most likely going to be hard.

@jpienaar @MaheshRavishankar @hanhanW do you have any suggestions?

**Comment by MaheshRavishankar** [comment]
Yup, this was discussed earlier. https://github.com/openxla/iree/pull/13308 prevents those fusions when it's not a named op. That was blocked on some time out during compilation on CUDA backend. I have to try on ToT after some recent fixes went in

**Comment by ThomasRaoux** [comment]
> Yup, this was discussed earlier. #13308 prevents those fusions when it's not a named op. That was blocked on some time out during compilation on CUDA backend. I have to try on ToT after some recent fixes went in

yes with ToT the problems should be gone

**Comment by ThomasRaoux** [comment]
BTW, I still think we should start with going back to named ops and then work on supporting the generalized version step by step

**Comment by KoolJBlack** [comment]
> 

https://github.com/openxla/iree/issues/13202#issuecomment-1535433910


> Some of the latency regressions in MiniLM (and most likely in more of the models) come from the fact that we now fuse elementwise producer into matmul op. In general it is not a good idea but here it is worse because it makes us not use the tensorcore pipeline.
> 
> For instance those ops:
> 
> ```
>    %8 = linalg.fill {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[1, 32, 32, 16]]>} ins(%cst : f32) outs(%7 : tensor<12x128x128xf32>) -> tensor<12x128x128xf32>
>       %9 = linalg.batch_matmul {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[1, 32, 32, 16]]>} ins(%4, %5 : tensor<12x128x32xf32>, tensor<12x32x128xf32>) outs(%8 : tensor<12x128x128xf32>) -> tensor<12x128x128xf32>
> ```
> 
> Became:
> 
> ```
>  %20 = linalg.fill {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[1, 1, 1], [0, 0, 0, 32]]>} ins(%cst_1 : f32) outs(%19 : tensor<12x128x128xf32>) -> tensor<12x128x128xf32>
>  %21 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d1, d0, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d3)>, affine_map<(d0, d1, d2, d3) -> (d2, d0, d3)>, affine_map<(d0, d1, d2, d3) -> (d2, d0, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel", "reduction"]} ins(%14, %15, %16, %17 : tensor<128x12x32xf32>, tensor<12x32xf32>, tensor<128x12x32xf32>, tensor<128x12x32xf32>) outs(%20 : tensor<12x128x128xf32>) attrs =  {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[1, 1, 1], [0, 0, 0, 32]]>} {
>       ^bb0(%in: f32, %in_2: f32, %in_3: f32, %in_4: f32, %out: f32):
>         %23 = arith.addf %in_3, %in_4 : f32
>         %24 = arith.addf %in, %in_2 : f32
>         %25 = arith.mulf %24, %23 : f32
>         %26 = arith.addf %out, %25 : f32
>         linalg.yield %26 : f32
>       } -> tensor<12x128x128xf32>
> ```
> 
> This is due to the [479900a](https://github.com/openxla/iree/commit/479900afe1467cd10f349894f758135e54d487e2) as pointed out by Scott.
> 
> to solve this we would need to change the fusion heuristic to prevent this assuming we want to keep this representation. We had discussed using the generic representation for matmul in the past however this is most likely not going to be a trivial change and will have performance impact on potentially many cases. My suggestion would be to first try to revert back to a state like we had before and if we want to support the generic version of matmul work on it separately and enable it when it is ready doing it as a fix forward is most likely going to be hard.
> 
> @jpienaar @MaheshRavishankar @hanhanW do you have any suggestions?

Just a heads up, this bad IR transform you're seeing here is related to the loss of the dot_general lowering from the frontend. See comment here: https://github.com/openxla/iree/issues/13202#issuecomment-1535433910

This will likely be addressed by reverting https://github.com/openxla/iree/issues/13458

**Comment by MaheshRavishankar** [comment]
@mariecwhite this should be fixed  at ToT (by https://github.com/openxla/iree/pull/13468 ) . Please verify and close.

**Comment by mariecwhite** [comment]
This is fixed and the benchmarks have been re-enabled in https://github.com/openxla/iree/pull/13515
