### ISSUE TITLE
Remove usage of VMVX ops in computation for number of workgroups.

### ISSUE THREAD

**Issue by MaheshRavishankar** [iree-org/iree#13181]
There are a couple of issues discovered as part of #13038 . The main issue is the dependence of `vmvx.query_tile_size` for tile and distribute. This is the IR before and after  tile and distribute with #13038 

```
// -----// IR Dump After TileAndDistributeToWorkgroups (iree-codegen-tile-and-distribute-to-workgroups) //----- // 
func.func @matmul_DYNxDYNxi8_times_DYNxDYNxi8_into_DYNxDYNxi32_dispatch_0_set_encoding_MATMUL_I8I8I32_LHS_DxD() {
  %c-9223372036854775808 = arith.constant -9223372036854775808 : index
  %c0_i8 = arith.constant 0 : i8
  %c0 = arith.constant 0 : index
  %0 = hal.interface.constant.load[0] : i32
  %1 = hal.interface.constant.load[1] : i32
  %2 = hal.interface.constant.load[2] : i32
  %3 = hal.interface.constant.load[3] : i32
  %4 = arith.index_castui %0 : i32 to index
  %5 = flow.dispatch.workload_ordinal %4 0 : index
  %6 = arith.index_castui %1 : i32 to index
  %7 = flow.dispatch.workload_ordinal %6 1 : index
  %8 = arith.index_castui %2 : i32 to index
  %9 = flow.dispatch.workload_ordinal %8 2 : index
  %10 = arith.index_castui %3 : i32 to index
  %11 = flow.dispatch.workload_ordinal %10 3 : index
  %12 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<?x?xi8>>{%5, %7}
  %13:2 = vmvx.query_tile_sizes sizes(%c-9223372036854775808, %c-9223372036854775808) flags(1048576) -> index, index
  %14 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%9, %13#0]
  %15 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%11, %13#1]
  %16 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) : !flow.dispatch.tensor<writeonly:tensor<?x?x?x?xi8>>{%14, %15, %13#0, %13#1}
  %17 = flow.dispatch.tensor.load %12, offsets = [0, 0], sizes = [%5, %7], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<?x?xi8>>{%5, %7} -> tensor<?x?xi8>
  %18 = affine.apply affine_map<()[s0, s1] -> (-s0 + s1 + (s0 ceildiv 16) * 16)>()[%5, %5]
  %19 = affine.apply affine_map<()[s0, s1] -> (-s0 + s1 + (s0 ceildiv 16) * 16)>()[%7, %7]
  %20:2 = vmvx.query_tile_sizes sizes(%c-9223372036854775808, %c-9223372036854775808) flags(1048576) -> index, index
  %21 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%18, %20#0]
  %22 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%19, %20#1]
  %23 = tensor.empty(%21, %22, %20#0, %20#1) : tensor<?x?x?x?xi8>
  %pack = tensor.pack %17 padding_value(%c0_i8 : i8) inner_dims_pos = [0, 1] inner_tiles = [%20#0, %20#1] into %23 {encoding = #iree_linalg_ext.encoding<MATMUL_I8I8I32_LHS>} : tensor<?x?xi8> -> tensor<?x?x?x?xi8>
  %24:2 = vmvx.query_tile_sizes sizes(%c-9223372036854775808, %c-9223372036854775808) flags(1048576) -> index, index
  %25 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%9, %24#0]
  %26 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%11, %24#1]
  flow.dispatch.tensor.store %pack, %16, offsets = [0, 0, 0, 0], sizes = [%25, %26, %24#0, %24#1], strides = [1, 1, 1, 1] : tensor<?x?x?x?xi8> -> !flow.dispatch.tensor<writeonly:tensor<?x?x?x?xi8>>{%25, %26, %24#0, %24#1}
  return
}
```

and 

```
// -----// IR Dump After TileAndDistributeToWorkgroups (iree-codegen-tile-and-distribute-to-workgroups) //----- //                                                                                                                                                                                                 
hal.executable.variant public @vmvx_bytecode_fb, target = <"vmvx", "vmvx-bytecode-fb", {ukernels = true}> {
  hal.executable.export public @matmul_DYNxDYNxi8_times_DYNxDYNxi8_into_DYNxDYNxi32_dispatch_0_set_encoding_MATMUL_I8I8I32_LHS_DxD ordinal(0) layout(#hal.pipeline.layout<push_constants = 4, sets = [<0, bindings = [<0, storage_buffer, ReadOnly>, <1, storage_buffer>]>]>) attributes {translation_info = #iree\
_codegen.translation_info<VMVXDefault>} {
  ^bb0(%arg0: !hal.device, %arg1: index, %arg2: index, %arg3: index, %arg4: index):
    %c1 = arith.constant 1 : index
    %c-9223372036854775808 = arith.constant -9223372036854775808 : index
    %0 = affine.apply affine_map<()[s0, s1] -> (-s0 + s1 + (s0 ceildiv 16) * 16)>()[%arg1, %arg1]
    %1:2 = vmvx.query_tile_sizes sizes(%c-9223372036854775808, %c-9223372036854775808) flags(1048576) -> index, index
    %2 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%0, %1#0]
    %3 = affine.apply affine_map<()[s0, s1] -> (-s0 + s1 + (s0 ceildiv 16) * 16)>()[%arg2, %arg2]
    %4 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%3, %1#1]
    %5 = affine.apply affine_map<()[s0] -> (s0 ceildiv 64)>()[%2]
    %6 = affine.apply affine_map<()[s0] -> (s0 ceildiv 64)>()[%4]
    hal.return %6, %5, %c1 : index, index, index
  }
  builtin.module {
    func.func @matmul_DYNxDYNxi8_times_DYNxDYNxi8_into_DYNxDYNxi32_dispatch_0_set_encoding_MATMUL_I8I8I32_LHS_DxD() {
      %c-9223372036854775808 = arith.constant -9223372036854775808 : index
      %c0_i8 = arith.constant 0 : i8
      %c0 = arith.constant 0 : index
      %0 = hal.interface.constant.load[0] : i32
      %1 = hal.interface.constant.load[1] : i32
      %2 = hal.interface.constant.load[2] : i32
      %3 = hal.interface.constant.load[3] : i32
      %4 = arith.index_castui %0 : i32 to index
      %5 = arith.index_castui %1 : i32 to index
      %6 = arith.index_castui %2 : i32 to index
      %7 = arith.index_castui %3 : i32 to index
      %8 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<?x?xi8>>{%4, %5}
      %9:2 = vmvx.query_tile_sizes sizes(%c-9223372036854775808, %c-9223372036854775808) flags(1048576) -> index, index
      %10 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%6, %9#0]
      %11 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%7, %9#1]
      %12 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) : !flow.dispatch.tensor<writeonly:tensor<?x?x?x?xi8>>{%10, %11, %9#0, %9#1}
      %13:2 = vmvx.query_tile_sizes sizes(%c-9223372036854775808, %c-9223372036854775808) flags(1048576) -> index, index
      %14 = affine.apply affine_map<()[s0, s1] -> (((s1 ceildiv 16) * 16) ceildiv s0)>()[%13#0, %4]
      %15 = affine.apply affine_map<()[s0, s1] -> (((s1 ceildiv 16) * 16) ceildiv s0)>()[%13#1, %5]
      %workgroup_id_x = hal.interface.workgroup.id[0] : index
      %workgroup_count_x = hal.interface.workgroup.count[0] : index
      %workgroup_id_y = hal.interface.workgroup.id[1] : index
      %workgroup_count_y = hal.interface.workgroup.count[1] : index
      %16 = affine.apply affine_map<()[s0] -> (s0 * 64)>()[%workgroup_id_y]
      %17 = affine.apply affine_map<()[s0] -> (s0 * 64)>()[%workgroup_count_y]
      scf.for %arg0 = %16 to %14 step %17 {
        %18 = affine.min affine_map<(d0)[s0, s1] -> (-d0 + ((s1 ceildiv 16) * 16) ceildiv s0, 64)>(%arg0)[%13#0, %4]
        %19 = affine.apply affine_map<()[s0] -> (s0 * 64)>()[%workgroup_id_x]
        %20 = affine.apply affine_map<()[s0] -> (s0 * 64)>()[%workgroup_count_x]
        scf.for %arg1 = %19 to %15 step %20 {
          %21 = affine.min affine_map<(d0)[s0, s1] -> (-d0 + ((s1 ceildiv 16) * 16) ceildiv s0, 64)>(%arg1)[%13#1, %5]
          %22 = affine.min affine_map<(d0, d1)[s0, s1] -> (d0 * s0, -(d1 * s0) + s1)>(%18, %arg0)[%13#0, %4]
          %23 = affine.min affine_map<(d0, d1)[s0, s1] -> (d0 * s0, -(d1 * s0) + s1)>(%21, %arg1)[%13#1, %5]
          %24 = affine.apply affine_map<(d0)[s0] -> (d0 * s0)>(%arg0)[%13#0]
          %25 = affine.apply affine_map<(d0)[s0] -> (d0 * s0)>(%arg1)[%13#1]
          %26 = flow.dispatch.tensor.load %8, offsets = [%24, %25], sizes = [%22, %23], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<?x?xi8>>{%4, %5} -> tensor<?x?xi8>
          %27 = tensor.empty(%18, %21, %13#0, %13#1) : tensor<?x?x?x?xi8>
          %pack = tensor.pack %26 padding_value(%c0_i8 : i8) inner_dims_pos = [0, 1] inner_tiles = [%13#0, %13#1] into %27 {encoding = #iree_linalg_ext.encoding<MATMUL_I8I8I32_LHS>, lowering_config = #iree_codegen.lowering_config<tile_sizes = [[64, 64]]>} : tensor<?x?xi8> -> tensor<?x?x?x?xi8>
          %28 = arith.index_castui %2 : i32 to index
          %29:2 = vmvx.query_tile_sizes sizes(%c-9223372036854775808, %c-9223372036854775808) flags(1048576) -> index, index
          %30 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%28, %29#0]
          %31 = arith.index_castui %3 : i32 to index
          %32 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%31, %29#1]
          flow.dispatch.tensor.store %pack, %12, offsets = [%arg0, %arg1, 0, 0], sizes = [%18, %21, %13#0, %13#1], strides = [1, 1, 1, 1] : tensor<?x?x?x?xi8> -> !flow.dispatch.tensor<writeonly:tensor<?x?x?x?xi8>>{%30, %32, %29#0, %29#1}
        }
      }
      return
    }
  }
}
```

The number of workgroups for the generated loop are computed based on program slice results in the `vmvx.query_tile_size` being used. Since the workgroup count region is effectively host-side code (and `vmvx.query_tile_size` is device side code). So firstly we need a better way to determine workgroup count that does not depend on this function. For now the computation has been fixed to arbitrarily replace all `vmvx.query_tile_size` with `16`. (Not great!). 
A solution here might be to pre-empt the workgroup count computation during `MaterializeEncoding..` to get it to a form that can be managed better during `TileAndDistribute`. Not sure what that looks like yet.

At the very least, the dependencies with VMVX need to be managed better. #13038  adds a dependency from VMVX -> Codegen, which actually already exists here https://github.com/openxla/iree/blob/85482169432caefcb8f99e75a3901d307f3d51e7/compiler/src/iree/compiler/Codegen/Common/MaterializeEncodingIntoPackUnPack.cpp#L19 . These dependencies need to be severed....

**Comment by MaheshRavishankar** [comment]
For the issue with the workgroup count region, some notes based on the analysis. Take

```
    %1:2 = vmvx.query_tile_sizes sizes(%c-9223372036854775808, %c-9223372036854775808) flags(1048576) -> index, index

    %0 = affine.apply affine_map<()[s0, s1] -> (-s0 + s1 + (s0 ceildiv 16) * 16)>()[%arg1, %arg1]
    %2 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%0, %1#0]
    %5 = affine.apply affine_map<()[s0] -> (s0 ceildiv 64)>()[%2]

    %3 = affine.apply affine_map<()[s0, s1] -> (-s0 + s1 + (s0 ceildiv 16) * 16)>()[%arg2, %arg2]
    %4 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%3, %1#1]
    %6 = affine.apply affine_map<()[s0] -> (s0 ceildiv 64)>()[%4]
    return %5, %6 : index, index
```

The `(s0 ceildiv 16) * 16` is strange. The reason that happens is because we pad everything to next multiple of 16. That is manifesting in this computation. So one way to avoid this is make the padding we use also parameteric. This parameteric value is same as the inner tile size. So with that the above expressions will become

```
    %1:2 = vmvx.query_tile_sizes sizes(%c-9223372036854775808, %c-9223372036854775808) flags(1048576) -> index, index

    %0 = affine.apply affine_map<()[s0, s1, s2] -> (-s0 + s1 + (s0 ceildiv s2) * 16)>()[%arg1, %arg1, %1#0]
    %2 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%0, %1#0]
    %5 = affine.apply affine_map<()[s0] -> (s0 ceildiv 64)>()[%2]

    %3 = affine.apply affine_map<()[s0, s1, s2] -> (-s0 + s1 + (s0 ceildiv s2) * s2)>()[%arg2, %arg2, %1#1]
    %4 = affine.apply affine_map<()[s0, s1] -> (s0 ceildiv s1)>()[%3, %1#1]
    %6 = affine.apply affine_map<()[s0] -> (s0 ceildiv 64)>()[%4]
    return %5, %6 : index, index
```

These then simplify to

```
    #map3 = affine_map<()[s0, s1] -> ((s1 ceildiv s0) ceildiv 64)>
   %0:2 = vmvx.query_tile_sizes sizes(%c-9223372036854775808, %c-9223372036854775808) flags(1048576) -> index, index
    %1 = affine.apply #map3()[%0#0, %arg0]
    %2 = affine.apply #map3()[%0#1, %arg1]
    return %1, %2 : index, index
```

which makes sense in terms of workgroup count calculation. We actually dont need to be exact here. The generated code can handle ANY number of workgroups here. We can go with saying that we compute the minimum number of workgroups here. If we bound the result of `vmvx.query_tile_size` to some value (say `16`). then using the new `ValueBoundsOpInterface` we should be able to get rid of the usage of `vmvx.query_tile_size` in workgroup count calculation.

Now for how we remove the padding chosen during `SetEncoding` at Flow level, we can just introduce a new op (say `iree_linalg_ext.get_encoding_inner_tile_size` which takes the encoding attribute and the dimension index along which we want to query the tile size. During `MaterializeEncoding` we can get this value.

**Comment by benvanik** [comment]
> Now for how we remove the padding chosen during SetEncoding at Flow level, we can just introduce a new op (say iree_linalg_ext.get_encoding_inner_tile_size which takes the encoding attribute and the dimension index along which we want to query the tile size. During MaterializeEncoding we can get this value.

we'll still want that to be a dynamic call for ukernels - the inner tile size is decided by the ukernel library and not something the compiler can (in general) know about, though it's possible for IPO to fold it all away when statically linking. instead of vmvx.query_tile_size there's going to be a func.call to an iree_uk_query_tile_size (or whatever it's called) - we could then replace the vmvx op with that call/an export too.

**Comment by MaheshRavishankar** [comment]
> > Now for how we remove the padding chosen during SetEncoding at Flow level, we can just introduce a new op (say iree_linalg_ext.get_encoding_inner_tile_size which takes the encoding attribute and the dimension index along which we want to query the tile size. During MaterializeEncoding we can get this value.
> 
> we'll still want that to be a dynamic call for ukernels - the inner tile size is decided by the ukernel library and not something the compiler can (in general) know about, though it's possible for IPO to fold it all away when statically linking. instead of vmvx.query_tile_size there's going to be a func.call to an iree_uk_query_tile_size (or whatever it's called) - we could then replace the vmvx op with that call/an export too.

We just need to make sure whatever is used for workgroup count calculation is host visible function.

**Comment by benvanik** [comment]
not quite - it either needs to be completely derived from device queries (`hal.device.query`) or completely independent of device information (based on how much work is being performed across execution units, not how it's being performed in the inner loop on a particular execution unit). best to think about separating a declaration of how much work there is to do from the definition of how the work is processed. today they're intertwined and that's causing this issue.

workgroup count should be based on work to be done (global problem size), problem traversal (x fastest varying and hottest cache, z coldest), and execution unit count (`hal.dispatch` :: `concurrency` indicating worker count). what tile size an inner loop on a particular execution unit decides to process the work allocated to it in must be separate (heterogenous cores, etc). the amount of work in a workgroup should be one or two orders of magnitude more than the inner tiles and that gives us the ability to keep them separate - processing in 4x8 or 8x8 tiles doesn't matter when a workgroup should be processing 64-256k elements.

we may be saying the same thing, but just want to ensure we aren't assuming there's a host visible function to call :)

**Comment by MaheshRavishankar** [comment]
> not quite - it either needs to be completely derived from device queries (`hal.device.query`) or completely independent of device information (based on how much work is being performed across execution units, not how it's being performed in the inner loop on a particular execution unit). best to think about separating a declaration of how much work there is to do from the definition of how the work is processed. today they're intertwined and that's causing this issue.
> 
> workgroup count should be based on work to be done (global problem size), problem traversal (x fastest varying and hottest cache, z coldest), and execution unit count (`hal.dispatch` :: `concurrency` indicating worker count). what tile size an inner loop on a particular execution unit decides to process the work allocated to it in must be separate (heterogenous cores, etc). the amount of work in a workgroup should be one or two orders of magnitude more than the inner tiles and that gives us the ability to keep them separate - processing in 4x8 or 8x8 tiles doesn't matter when a workgroup should be processing 64-256k elements.
> 
> we may be saying the same thing, but just want to ensure we aren't assuming there's a host visible function to call :)

Yeah agreed. I think the way it is today it ends up getting dependent on the inner tile size when it shouldnt. That is what this bug is for. Need to find a way where it doesnt get dependent on these things to begin with... I dont have the full end-state in mind here. For now the work around I have keeps the existing state, but at the cost of wrong layering... This needs to be revisited (by me) and cleaned up.
