### ISSUE TITLE
[MLIR] Entry block arg types get converted

### ISSUE THREAD

**Issue by aaron-schneider** [iree-org/iree#13203]
Using this to track an external issue: 

- [x] https://github.com/llvm/llvm-project/issues/62249
- [x] check that it resolves the original issue in IREE

**Comment by aaron-schneider** [comment]
Adding this to track the LLVM issue. Downgrading to P1 as we explore the workaround in https://github.com/openxla/iree/issues/13202

**Comment by ftynse** [comment]
I proposed a fix in MLIR.

**Comment by ftynse** [comment]
MLIR fix has landed upstream, waiting for IREE integrate.

**Comment by allieculp** [comment]
@ftynse Checking in on this, still waiting for integrate?

**Comment by ftynse** [comment]
Looks like it has been integrated.
