### ISSUE TITLE
iree-compile not reporting version

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#13213]
Released iree-compile binaries should be reporting their version (i.e. via `iree-compile --version`) but seem to be printing "unknown".

**Comment by ScottTodd** [comment]
I still see "unknown" in the printed version using the `iree-compiler-20230426.501` nightly: https://colab.research.google.com/gist/ScottTodd/9b629922d32e43a313cd1ebe125163f5/iree-python-version-printing.ipynb

```bash
python -m pip install iree-compiler -f https://openxla.github.io/iree/pip-release-links.html
iree-compile --version

IREE (https://openxla.github.io/iree):
  IREE compiler version (unknown)
  LLVM version 17.0.0git
  Optimized build
```

Also, do we / should we expose a `__version__` in Python? (see that notebook for what I mean)

**Comment by allieculp** [comment]
@ScottTodd @stellaraccident What is the next step here?

**Comment by allieculp** [comment]
@ScottTodd @stellaraccident Setting to P2, if this should be P1 please update and we will need a resource.

**Comment by stellaraccident** [comment]
I noticed this last week and unclear if a regression or never worked. Should be a P1: it is difficult to support these things without version plumbing working.

**Comment by allieculp** [comment]
@julianwa @jpienaar @mattwalsh Need a resource for this P1 issue.

**Comment by ScottTodd** [comment]
Confirmed that this is fixed in nightly releases
```
!iree-compile --version

IREE (https://openxla.github.io/iree):
  IREE compiler version 20230511.516 @ 8c6f57711e72f300bd5649cec8b944ed95f8c1d5
  LLVM version 17.0.0git
  Optimized build
```
