### ISSUE TITLE
RFC: Removing original/low-level IREE compiler API

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#13215]
For quite a while, we have had a low level API to [IREE's compiler pipelines](https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/API/MLIRInterop.h). This API is built on top of the unstable MLIR-C API and exposes a subset of the functionality that `iree-compile` exposes in the form of some low level pass pipelines.

We've since built out a [full-featured JIT-compatible, stable C API for the compiler](https://github.com/openxla/iree/blob/main/compiler/bindings/c/iree/compiler/embedding_api.h) which exposes all features of `iree-compile` (in fact `iree-compile` is built on top of this API) plus additional features needed for in-process, multi-tenant use within JIT systems.

The original API has proven to be a bit of a maintenance burden, I'm not sure anyone ever really used it, and it is not being updated. Further, it is considered an internal API of the compiler vs installed as public headers.

I propose removing this API (and the corresponding Python API).

cc @edubart (since they contributed a [test case](https://github.com/openxla/iree/blame/main/compiler/src/iree/compiler/API/test/api-test-main.c))

**Comment by stellaraccident** [comment]
Per offline discussion in the #julia channel, there is a user: https://github.com/Pangoraw/Coil.jl/blob/main/src/IREE/compiler.jl

Paul Berg:

Thanks for the heads up! To replace ireeCompilerTranslateModuletoVMBytecode, I need to create iree_compiler_invocation_t from a MlirModule by going through textual IR  -> iree_compiler_source_t -> ireeCompilerInvocationParseSource or is there a function to provide the module directly to the invocation ?

Stella Laurenzo:

Ah, good point - I had intended to provide some better bridging there. We should be able to provide an entry point to directly give ownership of an in-memory Module to iree_compiler_source_t.
(the use cases for the API all involved artifacts as input, not in-memory IR so it slipped my mind)
I might need to provide that interop as an "unstable" part of the API since the corresponding mlir-c API is unstable and can change without notice. This is just me thinking out loud.

**Comment by allieculp** [comment]
@stellaraccident Any idea of priority for this - should we be assigning a resource?

**Comment by stellaraccident** [comment]
It's open for comment per our process. Ideally, we have a way to categorize RFCs as they are precursors to work.

**Comment by allieculp** [comment]
In fact we have a whole workstream tag for RFCs, I see @julianwa already added this there - thank you!

**Comment by stellaraccident** [comment]
Note that this was forced by some other work. PR which adds the interop and drops the old API above.
