### ISSUE TITLE
[Epic] Determine library needs for LLMs: Sort, FFT, and solve

### ISSUE THREAD

**Issue by allieculp** [iree-org/iree#13243]
@julianwa @mattwalsh These may be deprioritized, but we need someone to check the LLMs we are targeting and see if these are required.

**Comment by allieculp** [comment]
@silvasean Can you help take a look at this Epic item for Q2? We need to determine whether Sort/FFT/solve are needed for LLMs. 
@ezhulenev Do we get these with cuDNN already?

**Comment by silvasean** [comment]
This is blocked by picking the LLM workloads we will consider for our immediate goals. We may need sort for beam search. I can't think about what in the model would need fft/solve for an LLM (at least the core model architecture).

**Comment by allieculp** [comment]
@silvasean Pinging this again - are these libraries important at the moment?

**Comment by silvasean** [comment]
None of these libraries (Sort, FFT, Solve) will be critical to LLM efforts.

**Comment by silvasean** [comment]
I think we can close this.

**Comment by silvasean** [comment]
(we will likely need libraries, but mostly for performance of matmuls which should be tracked elsewhere)
