### ISSUE TITLE
[Epic] Bring up all benchmark models in the suite

### ISSUE THREAD

**Issue by aaron-schneider** [iree-org/iree#13258]

**Comment by ScottTodd** [comment]
Please add context to issues. All benchmark models in _which_ suite?

**Comment by mariecwhite** [comment]
We have a tracking bug here that I created before this: https://github.com/openxla/iree/issues/12873. Should we link it or use that instead as the epic?

**Comment by allieculp** [comment]
@mariecwhite Let's use #12873 as the Epic instead. I will update the title and close this one - thanks!
