### ISSUE TITLE
[Epic] Improved JAX -> PJRT client option passing

### ISSUE THREAD

**Issue by allieculp** [iree-org/iree#13252]
- [ ] #13262

**Comment by ScottTodd** [comment]
What part of this intersects with IREE? Could this issue be filed on JAX instead?

**Comment by allieculp** [comment]
This is one of our Epic level goals for MS2. @julianwa Can you provide clarity?

**Comment by julianwa** [comment]
@okkwon can add some detail. This is currently being addressed by the JAX team

**Comment by stellaraccident** [comment]
fyi - going to want to land https://github.com/openxla/iree/pull/13262 so that more options are available to set to the compiler APIs.

**Comment by okkwon** [comment]
A work related to the device topology is in progress in the PJRT Client API side too. (But it is not really specific to IREE though.)

**Comment by julianwa** [comment]
Closing this item. I rolled it into https://github.com/openxla/iree/issues/12930
