### ISSUE TITLE
Flesh out HAL conformance testing suite

### ISSUE THREAD

**Issue by allieculp** [iree-org/iree#13250]

**Comment by ScottTodd** [comment]
Can someone add more detail to this issue title and description? Is this related to https://github.com/openxla/iree/tree/main/runtime/src/iree/hal/cts ?

Meta: filing 25+ issues with [Epic] in the title, no context in the descriptions, and no labels/assignees/task lists is pretty confusing (and noisy). Work tracking is nice, but I can't even tell if this is a feature request related to IREE or what...

**Comment by allieculp** [comment]
@mattwalsh We should review this Epic and provide more description to the title / body. Also I believe this may move to MS3 - please take a look.

**Comment by allieculp** [comment]
@mattwalsh Reminder this Epic needs an update: still valid? Needs a better description?

**Comment by allieculp** [comment]
Moving this as a task under Epic #13245. Assigned to @antiagainst

**Comment by ScottTodd** [comment]
@antiagainst + @sogartar do you want to use this issue for tracking, or should we just close it? Context was never added here...

**Comment by antiagainst** [comment]
Let's close this one. We are adding semaphore tests that are recorded as Todo in the cts now. No need to duplicate it again here just for issue purposes.
