### ISSUE TITLE
[Epic] Verified threading behavior with internal fibers

### ISSUE THREAD

**Issue by allieculp** [iree-org/iree#13251]

**Comment by allieculp** [comment]
@jpienaar @mattwalsh This Epic for MS2 needs review - not sure if it is relevant anymore?

**Comment by ScottTodd** [comment]
Can someone add more context here? Threading behavior for what? Runtime CPU task system? Without more information, this also seems very specific for a "Epic" issue.

**Comment by jpienaar** [comment]
This is an internal implementation detail for a specific deployment and should not be a GH issue. Closing and will give context to folks affected.
