### ISSUE TITLE
Explore IREE out-of-tree plugin functionality

### ISSUE THREAD

**Issue by pjannaty** [iree-org/iree#13277]
### Request description

Explore IREE out-of-tree plugin functionality

**Comment by allieculp** [comment]
@DEKHTIARJonathan Let us know if this is in progress, or needs an additional resource? Thanks!

**Comment by pjannaty** [comment]
Hi Allie, is anyone else from your side planning on working on this? cc @stellaraccident

**Comment by stellaraccident** [comment]
I think we can remove that TODO. I'm planning to keep the sample plugins here, and they are currently enabled when samples build (https://github.com/openxla/iree/blob/main/CMakeLists.txt#L157).

The next step to generalize is the supported in-tree plugins (non-sample). The first of which is here: https://github.com/openxla/iree/pull/13262 (pending fixing some API and bazel build issues that are blocking it). The idea is that in-tree, we will build all plugins under `compiler/plugins` all the time, sample plugins when IREE_BUILD_SAMPLES is enabled, and out of tree plugins when that are explicitly passed to [IREE_COMPILER_PLUGIN_PATHS](https://github.com/openxla/iree/blob/main/CMakeLists.txt#L154). Future work will let these be built as shared libraries, et al, but we're a way off from that.

**Comment by pjannaty** [comment]
Ok sounds good. 
Jonathan is looking into ways to possibly integrate the TRT module as an IREE plugin. Updated issue title.

**Comment by stellaraccident** [comment]
Is there any code I could look at? (I don't need to but may have advice)

**Comment by pjannaty** [comment]
Suggestions/advice is much appreciated. We have not published that code but I can look into fast tracking that.

**Comment by DEKHTIARJonathan** [comment]
@stellaraccident for now I'm really investigating if a simple "IREE compiler plug-in" can be defined and compiled out of tree while being registered at runtime.

The main motivation is to allow IEEE to interface with anyone's IREE extension if they so wish. I don't think it's very sustainable for IREE to merge in-tree every "plug-in from the community, partners or HW vendors...

And indeed as @pjannaty mentioned we are trying to bring an MLIR based TRT plug-in into IREE. Without having to force you to merge it in tree.

Let me know if you have resources that could help. I'm actively working on that atm.

**Comment by allieculp** [comment]
@DEKHTIARJonathan @pjannaty Is this still an active effort on your side? This issue has gone stale so checking in.

**Comment by pjannaty** [comment]
Thanks for the ping. We're not working on this at the moment, closing!
