### ISSUE TITLE
(Vulkan / RDNA2) Runtime Error with RDNA2 devices on some batch matmuls.

### ISSUE THREAD

**Issue by monorimet** [iree-org/iree#13289]
### What happened?

Hi,

I've run into an issue on RDNA2 cards (6900xt and users report the same for other RDNA2 cards) with running the VAE for SHARK's stable diffusion upscaler app (tested on SHARK-runtime as well as stock IREE).
The specific HF model id
I've tracked down the failure to a specific dispatch which contains a batch matmul of dims 1x512x512x256.

Here is the error output:
```
(iree.venv) PS C:\V\s> .\iree-build\tools\iree-benchmark-module.exe --module=upscaler_vae_27.vmfb --device=vulkan
C:\V\s\runtime\src\iree\hal\drivers\vulkan\native_executable.cc:157: UNKNOWN; VkResult=4294967283; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module@1:254 -
```

This is what the .vmfb was compiled with:
```
(iree.venv) PS C:\V\s> .\iree-build\tools\iree-compile.exe "module_forward_dispatch_27_vulkan_spirv_fb.mlir" --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --mlir-pass-pipeline-crash-reproducer=./iree_tmp/core-reproducer.mlir --iree-llvmcpu-target-cpu-features=host --iree-vulkan-target-env="#vk.target_env<v1.3, r(120), [VK_KHR_16bit_storage, VK_KHR_8bit_storage, VK_KHR_shader_float16_int8, VK_KHR_spirv_1_4, VK_KHR_storage_buffer_storage_class, VK_KHR_variable_pointers, VK_EXT_subgroup_size_control], AMD:DiscreteGPU, #vk.caps< maxComputeSharedMemorySize = 65536, maxComputeWorkGroupInvocations = 1024, maxComputeWorkGroupSize = dense<[1024, 1024, 1024]>: vector<3xi32>, subgroupSize = 64, subgroupFeatures = 255: i32, minSubgroupSize = 32, maxSubgroupSize = 64, shaderFloat16 = unit, shaderFloat64 = unit, shaderInt8 = unit, shaderInt16 = unit, shaderInt64 = unit, storageBuffer16BitAccess = unit, storagePushConstant16 = unit, uniformAndStorageBuffer16BitAccess = unit, storageBuffer8BitAccess = unit, storagePushConstant8 = unit, uniformAndStorageBuffer8BitAccess = unit, variablePointers = unit, variablePointersStorageBuffer = unit >>" --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=true --iree-util-zero-fill-elided-attrs -iree-vulkan-target-triple=rdna2-unknown-windows -o upscaler_vae_27.vmfb
```

The dispatch .mlir can be downloaded here: [module_forward_dispatch_27_vulkan_spirv_fb.mlir](https://console.cloud.google.com/storage/browser/_details/shark-public/ean/reproducers/upscaler_vae/module_forward_dispatch_27_vulkan_spirv_fb.mlir)

The .vmfb is here: [upscaler_vae_27.vmfb](https://console.cloud.google.com/storage/browser/_details/shark-public/ean/reproducers/upscaler_vae/upscaler_vae_27.vmfb)

The e2e .mlir for the 128x128 fp32 upscaler VAE model lowered through torch-mlir can be found here: [core-input.mlir](https://console.cloud.google.com/storage/browser/_details/shark-public/ean/reproducers/upscaler_vae/core-input.mlir)

It should be noted that this error can only be reproduced on rdna2 cards. Using an RDNA3 device with the `rdna2-unknown-windows` triple fails to reproduce the issue. 

In fact, the same .vmfb as above running on an A100 with Vulkan also succeeds without error. Hence I believe the issue is specific to RDNA2 devices.

### Steps to reproduce your issue

Download the .mlir / .vmfb for dispatch 27 from above and run on a system with an RDNA2 device using the given CLI inputs.

### What component(s) does this issue relate to?

Compiler, Runtime

### Version information

5ad8800039323162aa1790bca142a32acf59a242

**Comment by monorimet** [comment]
This is tracked on the SHARK repo here: https://github.com/nod-ai/SHARK/issues/1230

**Comment by monorimet** [comment]
It seems to work with `AMD_ENABLE_LLPC = 1`. Closing this issue.

**Comment by yongzhiGH** [comment]
Can you please also attach the SPIR-V code? Anush said there is a reduced SPIR-V kernel that make the repro eaiser.

**Comment by yongzhiGH** [comment]
This issue can be reproduced navi21 with old driver: 2023-02-16_012720-xgl_#7a3f6c1_pal_#d1cacef_sc_#b15b855.
 
And issue is gone with new xgl driver: 2023-05-28_143120-xgl_#99a1541_pal_#a955b3b_sc_#ac2c4ad.

Please try the newest driver.
