### ISSUE TITLE
stablehlo.dot_general has no custom assembly form

### ISSUE THREAD

**Issue by wangkuiyi** [iree-org/iree#13280]
### What happened?

When building the MLIR source file generated by [`iree-jax/models/gpt2/export.py`](https://github.com/iree-org/iree-jax/blob/2f7536918bed9e6ede6c40c79265958ba654924b/models/gpt2/export.py#L105-L106), the IREE compiler complains that custom op `stablehlo.dot_general` has no custom assembly form.

```
14:05 $ iree-compile --iree-input-type=mhlo --iree-hal-target-backends=llvm-cpu --iree-metal-compile-to-metallib=false /tmp/gpt2.mlir -o /tmp/gpt2-llvm.vmfb
/tmp/gpt2.mlir:2670:10: error: custom op 'stablehlo.dot_general' has no custom assembly form
    %0 = stablehlo.dot_general %arg1, %arg0, contracting_dims = [3] x [2], precision = [DEFAULT, DEFAULT] : (tensor<3x12x64x768xf32>, tensor<4x8x768xf32>) -> tensor<3x12x64x4x8xf32>
         ^
```

### Steps to reproduce your issue

1. Build IREE compiler, runtime, and Python binding on macOS
2. Build and run iree-jax following steps in [the CI workflow](https://github.com/iree-org/iree-jax/blob/2f7536918bed9e6ede6c40c79265958ba654924b/.github/workflows/test_gpt2_model.yaml#L17-L36) to get /tmp/gpt2.mlir`.
3. Run the above command to compile `/tmp/gpt2.mlir`.

I should clarify that step 2 will call the IREE compiler to compile `/tmp/gpt2.mlir` after generating the source file. That invocation fails with the same error message:
```
  File "/Users/y/w/iree-jax/models/gpt2/export.py", line 108, in main
    compiler.compile_file(
  File "/Users/y/w/iree-for-apple-os/build/compiler/compiler/bindings/python/iree/compiler/tools/core.py", line 237, in compile_file
    result = invoke_immediate(cl)
  File "/Users/y/w/iree-for-apple-os/build/compiler/compiler/bindings/python/iree/compiler/tools/binaries.py", line 194, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
/tmp/gpt2.mlir:2670:10: error: custom op 'stablehlo.dot_general' has no custom assembly form
    %0 = stablehlo.dot_general %arg1, %arg0, contracting_dims = [3] x [2], precision = [DEFAULT, DEFAULT] : (tensor<3x12x64x768xf32>, tensor<4x8x768xf32>) -> tensor<3x12x64x4x8xf32>
         ^
```

And, this error seem indepenent with backends, because all these settings`--iree-hal-target-backends=llvm-cpu | vmvx | metal` do not change the error.

### What component(s) does this issue relate to?

Compiler

### Version information

8cf1db2b757c3dfb5e098ac3e198198cc3e59194, the most recent one in the main branch

**Comment by ScottTodd** [comment]
IIRC we recommend using the generic form (or MLIR bytecode, not MLIR text) when persisting stablehlo or passing it between tools, to avoid issues like this. (I don't know the flags for those off the top of my head though)

**Comment by wangkuiyi** [comment]
@ScottTodd . Thanks. Do you suggest us to change [`export.py`](https://github.com/iree-org/iree-jax/blob/2f7536918bed9e6ede6c40c79265958ba654924b/models/gpt2/export.py#L105-L106) somehow to make it generate the MLIR bytecode? Could you please point me to some examples of generating MLIR bytecode? I can change `export.py`.

**Comment by ScottTodd** [comment]
In iree-jax (might want to move this issue there)? https://github.com/iree-org/iree-jax/commit/c9d656bed09ca7959ab7fd4b27c61194719a6be9 looks relevant

**Comment by wangkuiyi** [comment]
I am not sure if this is a iree-jax/models/gpt2/ specific issue, or something more general. I changed `export.py` to write the byte code
```python
  with open(FLAGS.ir_path, 'wb') as f:
    Program.get_mlir_module(module).operation.write_bytecode(file=f)
```

Then, I ran the following command to compile it
```bash
iree-compile \
 --iree-hal-target-backends=llvm-cpu \
 --iree-metal-compile-to-metallib=false /tmp/gpt2.mlir \
 -o /tmp/gpt2-llvm.vmfb
```

It gave me an error 
```
/tmp/gpt2.mlir:0:0: error: bytecode version 1 is newer than the current version 0
```

**Comment by jpienaar** [comment]
Could you verify that the IREE version is indeed newest and not due to old pip index page? (https://github.com/openxla/iree/issues/12762)

**Comment by wangkuiyi** [comment]
Yes, @jpienaar - I confirm that my IREE was built from source code

```
(iree-jax) ✔ ~/w/openxla-pjrt-plugin [main|✔]
09:33 $ pip list | grep iree
iree-jax           0.1.dev1
(iree-jax) ✔ ~/w/openxla-pjrt-plugin [main|✔]
09:33 $ echo $PYTHONPATH
/Users/y/w/iree-for-apple-os/build/compiler/compiler/bindings/python:/Users/y/w/iree-for-apple-os/build/compiler/runtime/bindings/python:/Users/y/w/iree-jax
(iree-jax) ✔ ~/w/openxla-pjrt-plugin [main|✔]
09:33 $ python3 -c 'import iree.runtime'
```

**Comment by wangkuiyi** [comment]
Thanks to @jpienaar for pointing out that this issue is related to https://github.com/openxla/iree/issues/12762

**Comment by wangkuiyi** [comment]
I will try install the CI-verified nightly versions of jax, jaxlib, iree, iree-jax using https://github.com/openxla/openxla-pjrt-plugin/blob/main/sync_deps.py, as suggested by @stellaraccident and update here.

At the same time, I am curious why my own build of iree-compile throws out `/tmp/gpt2.mlir:0:0: error: bytecode version 1 is newer than the current version 0`.

It seems that the above error message is from this MLIR function [`BytecodeReader::parseVersion(EncodingReader &reader)`](https://github.com/llvm/llvm-project/blob/55c88aafa6965646d46404eab16393ba8b1bff95/mlir/lib/Bytecode/Reader/BytecodeReader.cpp#L1335-L1353).

```cpp
LogicalResult BytecodeReader::parseVersion(EncodingReader &reader) {
  if (failed(reader.parseVarInt(version)))
    return failure();

  // Validate the bytecode version.
  uint64_t currentVersion = bytecode::kVersion;
  uint64_t minSupportedVersion = bytecode::kMinSupportedVersion;
  if (version < minSupportedVersion) {
    return reader.emitError("bytecode version ", version,
                            " is older than the current version of ",
                            currentVersion, ", and upgrade is not supported");
  }
  if (version > currentVersion) {
    return reader.emitError("bytecode version ", version,
                            " is newer than the current version ",
                            currentVersion);
  }
  return success();
}
```

The [recent version of llvm-projects](https://github.com/llvm/llvm-project/blob/6600ea1d1c7abd52b5d7aa5de8f09e0c961a4eb3/mlir/lib/Bytecode/Encoding.h#L30) has
```cpp
enum {
  /// The minimum supported version of the bytecode.
  kMinSupportedVersion = 0,

  /// The current bytecode version.
  kVersion = 1,

  /// An arbitrary value used to fill alignment padding.
  kAlignmentByte = 0xCB,
};
```

So does my local clone in `~/w/iree/third-party/llvm-projects`. 

So, it makes sense for my iree-compile to print ` bytecode version 1`, because I used a new version of iree-jax, which outputs MLIR bytecode of version 1 as expected. However, it does not make sense for iree-compile to print `is newer than the current version 0`, because the current version is `kVersion=1`, not `0`.

I rebuilt my iree-compiler and tried it again. It still printed `bytecode version 1 is newer than the current version 0`.

**Comment by wangkuiyi** [comment]
So embarassing for this false alarm - I have PATH, PYTHONPATH, and DYLD_LIBRARY_PATH pointing to an old git local clone.
