### ISSUE TITLE
[Batch Matmuls] Functional Verification and Performance Profiling

### ISSUE THREAD

**Issue by manishucsd** [iree-org/iree#13281]
### Request description

For **batch matmul** (`Batch x M x N x K`), this issue aims to collect information and resolve: 
(a) functional verification 
(b) performance profiling 

Batch matrix multiplication, which has one additional dimension compared to regular matrix multiplication (`M x N x K`), relies on some distinct codegen passes and code. Ensuring that IREE Codegen and upstream LLVM/MLIR do not break batch matrix multiplication is crucial..

Current end-to-end CUDA backend functional tests include the following:
```
$ ctest -j128 -R e2e_matmul.*cuda
Test project /mnt/disks/gcloud_workspace/repos/iree/iree_tree_4/build-debug
    Start 52: iree/tests/e2e/matmul/e2e_matmul_direct_f32_gpu_large_LLVMGPUMatmulSimt_cuda_cuda
    Start 53: iree/tests/e2e/matmul/e2e_matmul_direct_f32_gpu_large_LLVMGPUMatmulTensorCore_cuda_cuda
    Start 54: iree/tests/e2e/matmul/e2e_matmul_direct_f32_gpu_large_mma_sync_LLVMGPUMatmulTensorCoreMmaSync_cuda_cuda
    Start 55: iree/tests/e2e/matmul/e2e_matmul_direct_f16_gpu_large_LLVMGPUMatmulTensorCore_cuda_cuda
    Start 56: iree/tests/e2e/matmul/e2e_matmul_direct_f16_gpu_large_mma_sync_LLVMGPUMatmulTensorCoreMmaSync_cuda_cuda
    Start 57: iree/tests/e2e/matmul/e2e_matmul_direct_f32_large_split_k_cuda_cuda
```

However, no tests specifically verify batch matrix multiplication. Considering the recent functional ([D147749](https://reviews.llvm.org/D147749)) and performance improvements ([D148161](https://reviews.llvm.org/D148161), #13060 ) to batch matrix multiplication, it would be helpful to identify any existing tests related to this functionality. Additionally, these tests should be enabled in the continuous integration pipeline.

Missing functional verification tests for batch matrix multiplication should cover the following scenarios:

1. Batch matrix multiplication with varying batch sizes.
2. Different data types (e.g., `float16`, `float32`) for input matrices.
3. Various matrix sizes (M, N, K) within each batch.
4. Tests utilizing different codegen passes and code specific to batch matrix multiplication.
5. Performance profiling capability to monitor performance. Additionally, profiling also enables the user to pick top-performing tiling config. 

Once the missing tests are identified and implemented, they should be added to the continuous integration pipeline to ensure ongoing functional verification.

**Comment by manishucsd** [comment]
cc: @mattwalsh , @allieculp , @KoolJBlack , @MaheshRavishankar , @julianwa

**Comment by allieculp** [comment]
@manishucsd Should we add this to your queue? Or is this for someone else?

**Comment by allieculp** [comment]
@manishucsd Can you update this issue with the latest progress?

**Comment by allieculp** [comment]
Batch matmuls can be functionally verified, but not running in CI
