### ISSUE TITLE
[Split-K Matmuls] Functional Verification and Performance Profiling

### ISSUE THREAD

**Issue by manishucsd** [iree-org/iree#13290]
### Request description

For **split-k matmul** `[(M x N x K), split-k-slices]`, this issue aims to collect information and resolve:
(a) functional verification
(b) performance profiling

We have recently pushed functional and performance fixes for split-k matmul and want to ensuring that IREE Codegen and upstream LLVM/MLIR do not break split-k matmul. 

Current end-to-end CUDA backend functional tests include the following for split-k matmul variant:
```bash
    Start 57: iree/tests/e2e/matmul/e2e_matmul_direct_f32_large_split_k_cuda_cuda
```

The above test checks for split-k with FFMA math instruction (SIMT cores). The existing test does not ensure the functional correctness of WMMA or `mma.sync.*[f16|f32]` (Tensor cores). Additionally, there isn't an easy way to profile and sweep through supported split_k_slices value to get performance data and/or make split_k selection.. 

Missing functional verification tests for split-k matmul should cover the following scenarios:

1. Split-k matmul with different split_k_slices values.
2. Different data types (e.g., float16, float32) for input matrices.
3. A few matrix sizes (M, N, K).
4. Tests utilizing different codegen pass pipelines (WMMA and `mma.sync`)
5. Performance profiling capability to monitor performance. Additionally, profiling also enables the user to pick top-performing tiling config and split_k_slice value.

Once the missing tests are identified and implemented, they should be added to the continuous integration pipeline to ensure correctness and health of split-k matmuls.

PS: Note that split_k_slices is also referred as split_factor, split_count.

**Comment by manishucsd** [comment]
cc: @mattwalsh, @allieculp , @julianwa , @MaheshRavishankar

**Comment by allieculp** [comment]
@manishucsd Adding to our sprint boards! Will you be working on this, or needs an owner?

**Comment by allieculp** [comment]
@manishucsd Can you update this issue with the latest progress?

**Comment by allieculp** [comment]
Split-K matmuls can be functionally verified, but not running in CI
