### ISSUE TITLE
Move MPI out of the CUDA HAL driver and decouple it from drivers.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#13303]
In #12902 the channel provider got moved into cuda_device.c and as a tooling-only mechanism it shouldn't be in there as even when dynamic we don't want to be initializing/defaulting to MPI as part of the core library code. We also don't want the behavior in iree_hal_cuda_driver_create_internal that overrides device selection as part of the core driver code as overwriting the options set from flags/API use is generally not allowed (leads to really hard to diagnose configuration issues). As we look to share the MPI usage across other backends we don't want to fork a copy of the iree_hal_cuda_nccl_query_group_params for each of them. Having MPI ownership (init/finalize) tied to drivers is also not good as drivers are able to be created/destroyed multiple times within a process and multiple drivers may be in use at a time (if both CUDA and CPU tried to make global MPI changes things will go bad fast).

After #13152 lands and the dynamic library code is moved out of the CUDA driver we need to remove all of the MPI usage from cuda_device.c/cuda_driver.c/dynamic_symbols/etc. The only files that should be referencing MPI are the driver_module.c files _or_ iree/tooling/device_util.c, which is likely a better place for multi-backend usage.

The iree/tooling/ code is only used in IREE command line tools and not exported as part of the API. MPI's use in IREE is for tooling only and we have more lax standards around lifetime/initialization/etc as the only consumers are our own tools. We can move all MPI loading, symbols, the iree_hal_channel_provider_t/the query fn, and assignment to devices there and set it on devices via an `iree_hal_device_replace_channel_provider` (ala `iree_hal_device_replace_allocator`). It'd be worth making the channel provider a retained virtual object so that the device can then own the lifetime and multiple devices can share the same provider instance. OpenMPI has non-trivial logic in MPI_Finalize and we need to ensure it's called properly.

**Comment by allieculp** [comment]
@benvanik Setting this as P1, please downgrade if needed. Thanks!
