### ISSUE TITLE
[runtime] Dynamic VM modules should have access to HAL device

### ISSUE THREAD

**Issue by ezhulenev** [iree-org/iree#13313]
### Request description

Async module example (https://github.com/openxla/iree/blob/main/samples/custom_module/async/module.cc#L299-L303) can't be converted to a dynamic module, because dynamic module registration does not give access to the HAL device (https://github.com/openxla/iree/blob/main/samples/custom_module/dynamic/module.cc#L199-L202).

**Comment by benvanik** [comment]
If you need a device you'll have to expose a setter method on your module and pass it in - either once at initialization time (some `my_module.set_device(!hal.device)` called from a `util.initializer` op) or when required (passed as an argument to your functions that need it ala the `hal.*` methods). It's possible for there to be more than one device and the compiler is the only side that knows what device(s) should be used when. Today you could technically make a VM call to `hal.ex.shared_device` from your module but that's an internal method that will go away at some point and it's better to have that on the compiler side anyway (less coupling to the HAL module internals as they exist today).

**Comment by ScottTodd** [comment]
This also highlights how the HAL module is not privileged, and how it is valid to have a program that doesn't use the HAL at all (such as when running a scalar program through just the VM after detensoring)
