### ISSUE TITLE
Upgrade GitHub Actions Runner to at least v2.304.0 by 2023-05-25

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#13350]
New release is out, so we've got a month to upgrade: https://github.com/actions/runner/releases/tag/v2.304.0. See past issues: https://github.com/openxla/iree/issues?q=is%3Aissue+Upgrade+GitHub+Actions+Runner

**Comment by allieculp** [comment]
@GMNGeoffrey Are you the owner for this, or do we need one?

**Comment by GMNGeoffrey** [comment]
Well it would be welcome if someone else wanted to take this, but de facto I'm the owner. I haven't assigned myself because I'm not actually doing it right now (at the point I do it, we'll go from assigned to fixed).
