### ISSUE TITLE
Re-enable disabled iree dialects tests

### ISSUE THREAD

**Issue by okkwon** [iree-org/iree#13374]
source: https://github.com/openxla/iree/actions/runs/4866593061/jobs/8678290836?pr=13338

Disabled tests:
  IREE_DIALECTS :: Dialect/iree_linalg_ext/foreach-thread-to-async.mlir
  IREE_DIALECTS :: Dialect/iree_linalg_ext/foreach-thread-to-scf-for.mlir

**Comment by allieculp** [comment]
@okkwon I assume this was meant for Nicolas to review? He is OOO until next week, so for now I will mark as 'needs scheduling' P1.

**Comment by matthias-springer** [comment]
Fixed with #13406.
