### ISSUE TITLE
Change "benchmarks:" trailer to "benchmark-extra:" and support long benchmarks

### ISSUE THREAD

**Issue by pzread** [iree-org/iree#13392]
After #12890, we create the `cuda-long` preset to run heavy benchmarks that are not suitable in presubmit.

We need to update [configre_ci.py](https://github.com/openxla/iree/blob/main/build_tools/github_actions/configure_ci.py) to support the options to run them in presubmit.

My current idea is renaming our `benchmarks:` to `benchmark-extra:` (it looks like most of the people have switched to labels to trigger benchmarks). And we support new options, like:
- x86_64-long
- cuda-long
- all-long: the meta option to enable all long benchmarks

**Comment by pzread** [comment]
Renamed in #13623

**Comment by allieculp** [comment]
@pzread is this closed?

**Comment by pzread** [comment]
I have one more change to submit.
