### ISSUE TITLE
`custom_module/async/test/example.mlir` is flaky on macos_arm64

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#13404]
I'm not sure if this is an infrastructure issue or a code issue, but it seems extremely unlikely that this [PR editing android benchmarking scripting](https://github.com/openxla/iree/pull/13385) caused the failure

https://github.com/openxla/iree/actions/runs/4878143115/jobs/8703513609

> -- Testing: 1 tests, 1 workers --
> FAIL: IREE :: custom_module/async/test/example.mlir (1 of 1)
> ******************** TEST 'IREE :: custom_module/async/test/example.mlir' FAILED ********************
> Script:
> --
> : 'RUN: at line 1';   iree-compile /Users/antiagainst/actions-runner/_work/iree/iree/samples/custom_module/async/test/example.mlir --iree-execution-model=async-external --iree-hal-target-backends=llvm-cpu | custom-module-async-run - example.main | FileCheck /Users/antiagainst/actions-runner/_work/iree/iree/samples/custom_module/async/test/example.mlir
> --
> Exit Code: 1
> 
> Command Output (stderr):
> --
> libc++abi: terminating with uncaught exception of type std::__1::system_error: thread::detach failed: Invalid argument
> /Users/antiagainst/actions-runner/_work/iree/iree/samples/custom_module/async/test/example.mlir:58:12: error: CHECK: expected string not found in input
>  // CHECK: VM INVOKE END
>            ^
> <stdin>:3:29: note: scanning from here
> VM INVOKE BEGIN example.main
>                             ^
> 
> Input file: <stdin>
> Check file: /Users/antiagainst/actions-runner/_work/iree/iree/samples/custom_module/async/test/example.mlir
> 
> -dump-input=help explains the following input dump.
> 
> Input was:
> <<<<<<
>           1: INITIALIZE T=0 
>           2: SIGNALED T=1 
>           3: VM INVOKE BEGIN example.main 
> check:58                                 X error: no match found
> >>>>>>
> 
> --
> 
> ********************
> ********************
> Failed Tests (1):
>   IREE :: custom_module/async/test/example.mlir

**Comment by GMNGeoffrey** [comment]
Happened again here: https://github.com/openxla/iree/actions/runs/4884407293/jobs/8717113402

**Comment by allieculp** [comment]
@antiagainst Have you had a chance to look at this?

**Comment by antiagainst** [comment]
No I don't think this is a high priority right now. I've updated status and priority accordingly.

**Comment by antiagainst** [comment]
Closing this given #13501 is used to track this after disabling the test.
