### ISSUE TITLE
[riscv] re-enable disabled tests for llvm integrate

### ISSUE THREAD

**Issue by okkwon** [iree-org/iree#13421]
Tests are disabled by https://github.com/openxla/iree/pull/13412

**Comment by allieculp** [comment]
@okkwon @dcaballe Setting to P1 - please edit if needed.

**Comment by allieculp** [comment]
@okkwon Checking on this one - should we assign an owner?

**Comment by okkwon** [comment]
I assigned @dcaballe since it is RiscV related. @dcaballe any reason for the un-assignment?

**Comment by dcaballe** [comment]
Happy to get it reassigned but I'm not working on this right now. The feedback in one of our recent CPU meetings is that we shouldn't have issues assigned that we are not or plan to be working on in the near future so I did a clean up in that regard.

**Comment by okkwon** [comment]
If its priority gets reviewed periodically, that's fine, but if there is no such thing, I'd like to suggest getting someone assigned. Otherwise, it can be easily forgotten.
