### ISSUE TITLE
lint script failing on mac

### ISSUE THREAD

**Issue by jpienaar** [iree-org/iree#13447]
Ran into a few issues on mac:

- `grep: invalid option -- P`
- readarray missing

**Comment by allieculp** [comment]
@jpienaar Who is the right person to pick this up? Priority?

**Comment by allieculp** [comment]
@jpienaar Setting to P2 - please bump if needed.

**Comment by ScottTodd** [comment]
Moving the lint script to pre-commit (https://github.com/iree-org/iree/issues/17430), closing this as obsolete.
