### ISSUE TITLE
[StableHLO] Error compiling model with StableHLO

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#13467]
### What happened?

```
(iree.venv) mariewhite@marie:~/github/iree$ iree-compile --iree-hal-target-backends=cuda --iree-input-type=stablehlo_experimental --iree-hal-cuda-llvm-target-arch=sm_80 /tmp/hlo.mlirbc -o /tmp/hlo.vmfb
/tmp/hlo.mlirbc:1:1: error: one or more illegal operations were found in the compiler input (are you missing an --iree-input-type= flag, or did you mean to pre-process through an IREE importer frontend?)
module {
^
/tmp/hlo.mlirbc:660:12: note: failed to legalize operation 'stablehlo.batch_norm_inference' that was explicitly marked illegal
    %337 = "stablehlo.batch_norm_inference"(%336, %17, %16, %15, %14) {epsilon = 1.001000e-05 : f32, feature_index = 3 : i64} : (tensor<128x112x112x64xf32>, tensor<64xf32>, tensor<64xf32>, tensor<64xf32>, tensor<64xf32>) -> tensor<128x112x112x64xf32
```

### Steps to reproduce your issue

1. Download MLIR at https://storage.googleapis.com/iree-model-artifacts/tensorflow/tf_models_2.12.0_1683544084/RESNET50/batch_128/hlo.mlirbc

2. Compile:

```
iree-compile --iree-hal-target-backends=cuda --iree-input-type=stablehlo_experimental --iree-hal-cuda-llvm-target-arch=sm_80 /tmp/hlo.mlirbc -o /tmp/hlo.vmfb
```

Changing `stablehlo_experimental` to `mhlo` works.

### What component(s) does this issue relate to?

Compiler

### Version information

iree-compiler version 20230503.508

**Comment by kuhar** [comment]
Thanks for reporting, @mariecwhite. This works for me on https://github.com/openxla/iree/commit/8cd5dd93e6764cd3c8f0ec4c376e7705758aa23e and compiles without any errors.

Please reopen if this still happens to you on a newer build.
