### ISSUE TITLE
Running IREE dispatch profiler in CI 

### ISSUE THREAD

**Issue by manishucsd** [iree-org/iree#13464]
- [ ] Running IREE dispatch profiler in CI to ensure the tools functional health 
- [ ] Using IREE dispatch profiler in CI to achieve nightly nightly benchmarking runs, and then pre-submit regression tests.

**Steps to execute:**
1. Move the dispatch profiler from `iree/experimental` to `iree/benchmark`
2. [Waiting for concrete step 2. with examples]

**Comment by manishucsd** [comment]
The[ README.md](https://github.com/openxla/iree/blob/main/experimental/dispatch_profiler/README.md) here describes some basic command lines.

Can someone describe steps to run the below sequence of command lines as a part of CI?
```bash
$ python3 ../iree/experimental/dispatch_profiler/generator.py
$ python3 ../iree/experimental/dispatch_profiler/compile.py
$ python3 ../iree/experimental/dispatch_profiler/profiler.py --dispatches=matmul_3456x1024x2048_f16t_f16t_f16t_tile_config_128x128_32x5_tensorcore_mmasync,matmul_3456x1024x2048_f32t_f32t_f32t_tile_config_128x128_16x5_tensorcore_mmasync
```

**Comment by julianwa** [comment]
> Can someone describe steps to run the below sequence of command lines as a part of CI?

@GMNGeoffrey @ScottTodd do you have any suggestions on how to run IREE Dispatch Profiler for functional testing as an IREE pre-submit for a bounded number of cases? It would need to run on GPU instances.

**Comment by ScottTodd** [comment]
Step 1 for running on presubmit is to promote the code out of `experimental/`.

Tests should be authored using [`iree_py_test`](https://github.com/openxla/iree/blob/main/build_tools/cmake/iree_python.cmake) (or [`iree_native_test`](https://github.com/openxla/iree/blob/main/build_tools/cmake/iree_native_test.cmake), or [`iree_cc_test`](https://github.com/openxla/iree/blob/main/build_tools/cmake/iree_cc_test.cmake)), then you won't need to do anything special to get the tests included in our CI builds. Tests requiring physical GPUs should be more carefully evaluated, but they can be added using some labels.

I'd also be careful about test sizes - try to keep the total test time under 2 minutes.

**Comment by julianwa** [comment]
Thanks, @ScottTodd. I think IREE Dispatch Profiler can meet the requirements (move out of `experimental/`, have bounded test run times, have reasonable stable deps). @manishucsd, we should plan on implementing this as an `iree_py_test`. I recommend you do this yourself (hopefully < 1 day?), so that you become familiar with how to create these tests.

**Comment by manishucsd** [comment]
> Step 1 for running on presubmit is to promote the code out of experimental/.

What is a good pace for IREE dispatch profiler outside of `experimental/`?

**Comment by benvanik** [comment]
benchmarks/ perhaps?

**Comment by GMNGeoffrey** [comment]
Haven't read all history, but +1 to Scott. I'd also recommend that you test this as a library and test interesting functions with unit tests. We could have some smoke tests that invoke the tool via a shell script or something, but mostly this should be tested with normal python testing facilities

**Comment by julianwa** [comment]
> I'd also recommend that you test this as a library and test interesting functions with unit tests. We could have some smoke tests that invoke the tool via a shell script or something, but mostly this should be tested with normal python testing facilities

Just to clarify, the discussion is about using the IREE Dispatch Profiler to test functional correctness of codegen. I read your comments to be suggestions on how to test the IREE Dispatch Profiler itself, which isn't necessarily a bad thing, but not the entirety of what we're after.

**Comment by GMNGeoffrey** [comment]
Uh, why are we using a profiler tool to test functional correctness? I thought the goal was to test the tool itself and make sure it continued working

> Running IREE dispatch profiler in CI to ensure the tools functional health

But also my point was that these should be normal Python tests using the `unittest` module, rather than custom thing invoking a binary. The entry point function for the CLI should be directly testable

**Comment by benvanik** [comment]
> Uh, why are we using a profiler tool to test functional correctness?

Massive +1. Keeping this simple and focused should be the goal.

**Comment by ScottTodd** [comment]
I'm a bit out of the loop on how the dispatch profiler works, but my general guidance on adding new benchmarks would be to generate programs (MLIR files using dialects that IREE can import/compile) and then plug those programs into our existing benchmark suites.
* https://github.com/openxla/iree/tree/main/build_tools/python/e2e_test_artifacts
* https://github.com/openxla/iree/tree/main/tests/e2e/test_artifacts

There's been a separate thread of work/ideas (not a literal email thread / discussion) around running correctness tests on every program we benchmark. This could feed into that too...

Also, if these are microbenchmarks, we'd want to ensure the numbers they produce are stable, which might be more difficult than for full program benchmarks.

**Comment by julianwa** [comment]
> > Uh, why are we using a profiler tool to test functional correctness?
> 
> Massive +1. Keeping this simple and focused should be the goal.

A large part of the IREE Dispatch Profiler as implemented is a generator for dispatch regions and golden inputs/outputs. @manishucsd has added functionality to specify sweeps over ops, ranges etc. The tool also verifies IREE outputs match the golden outputs, although this does not necessarily need to be leveraged in CI-based correctness testing. 

I agree there are open questions about whether we should do this, and how it intersects with existing functional testing. I may have been over-eager in suggesting we add this to testing CI, without working through those. We'll circle back.

**Comment by manishucsd** [comment]
> Uh, why are we using a profiler tool to test functional correctness? I thought the goal was to test the tool itself and make sure it continued working

Currently, we need functional correctness tests for batch_matmul and matmul with split-k. We are also looking to add several new features in the matmul codegen such as supporting unaligned shapes, split-k on unaligned reduction dimension, and new data types (BF16). For the new features, we need simple tool achieve functional verification and performance reporting. 

IREE dispatch profiler provides Python-only solution to: 
- generate mlir dispatches
- create/write reference implementation using numpy to produce golden inputs/outputs 
- runs verification of the generated dispatches against the golden when enabled (--verification-enabled=<true|false>)
- runs profiling for the generated mlir dispatch (--profiling-enabled=<true|false>)
(Please find the [dispatch_profiler/README.md](https://github.com/openxla/iree/blob/main/experimental/dispatch_profiler/README.md) that describes IREE dispatch profiler capabilities as of today).

**Comment by ScottTodd** [comment]
Ideally, verification would use `iree-run-module` or `iree-run-trace` with `--expected_output`. We support multiple platforms where the Python interpreter cannot run, so using native (C/C++) tools is preferred. (We've already reinvented this wheel several times... would be good to not do it yet again)

**Comment by manishucsd** [comment]
> Ideally, verification would use iree-run-module or iree-run-trace with --expected_output.

IREE dispatch profiler uses all of the above features to achieve its goals:

```bash
$ python3 ../iree/experimental/dispatch_profiler/profiler.py --dispatches=matmul_3456x1024x2048_f16t_f16t_f16t_tile_config_128x256_32x3_tensorcore_mmasync --verification-enabled=true --profiling-enabled=true --verbose
Skipping compilation of operation: generated/linalg/matmul/matmul_3456x1024x2048_f16t_f16t_f16t/matmul_3456x1024x2048_f16t_f16t_f16t_verify.vmfb since it already exists.
[Verification] tools/iree-run-module --module=generated/linalg/matmul/matmul_3456x1024x2048_f16t_f16t_f16t/matmul_3456x1024x2048_f16t_f16t_f16t_verify.vmfb --device=cuda --function=matmul_3456x1024x2048_f16t_f16t_f16t_tile_config_128x256_32x3_tensorcore_mmasync --input=@generated/reference_cache/matmul_3456x1024x2048_f16t_f16t_f16t/m3456xk2048_f16t_random_lhs.npy --input=@generated/reference_cache/matmul_3456x1024x2048_f16t_f16t_f16t/k2048xn1024_f16t_random_rhs.npy --expected_output=@generated/reference_cache/matmul_3456x1024x2048_f16t_f16t_f16t/m3456xn1024_f16t_reference_result.npy
EXEC @matmul_3456x1024x2048_f16t_f16t_f16t_tile_config_128x256_32x3_tensorcore_mmasync
[SUCCESS] all function outputs matched their expected values.

Skipping compilation of operation: generated/linalg/matmul/matmul_3456x1024x2048_f16t_f16t_f16t/matmul_3456x1024x2048_f16t_f16t_f16t_profile.vmfb since it already exists.
[Profiling] tools/iree-benchmark-module --module=generated/linalg/matmul/matmul_3456x1024x2048_f16t_f16t_f16t/matmul_3456x1024x2048_f16t_f16t_f16t_profile.vmfb --device=cuda --benchmark_repetitions=5 --batch_size=100 --function=matmul_3456x1024x2048_f16t_f16t_f16t_tile_config_128x256_32x3_tensorcore_mmasync --input=3456x2048xf16 --input=2048x1024xf16
---------------------------------------------------------------- 
Dispatch      : matmul_3456x1024x2048_f16t_f16t_f16t_tile_config_128x256_32x3_tensorcore_mmasync
Provider      : IREE Codegen
OpKind        : OperationKind.Matmul
Operation     : matmul_3456x1024x2048_f16t_f16t_f16t
Configuration : tile_config_128x256_32x3_tensorcore_mmasync
Arguments     : --batch_count=1 --m=3456 --n=1024 --k=2048 --lhs=f16t --rhs=f16t --result=f16t
                --split_k_mode=N/A --split_k_slices=N/A
Verification  : SUCCESS
Runtime(ms)   : 0.062
GFLOPs        : 233798.62
```

**Comment by manishucsd** [comment]
Based on the discussion from IREE dev weekly, please provide an example of similar enablement in the CI. I understand that it won't be a one-to-one mapping for `dispatch_profiler` use case. IIUC, we are planning on a flow which already exists. Thus, I am hoping the flow has a few examples that would be good starting point to look at.

**Comment by ScottTodd** [comment]
Can you clarify the scope of this testing and profiling a bit? How many individual program runs are you interested in testing/profiling? How are those program runs organized? How long do those take to test correctness and to benchmark?

We'd want a different style of CI integration for running 10-100 variations, 100-10000 variations, and 10000+ variations.

**Comment by julianwa** [comment]
For the sake of functional testing, is there any reason why we can't just have IREE Dispatch Profiler's generator conform to the same output as https://github.com/openxla/iree/blob/b33c37537d5278019aa5b5865197b0b3f2e121a3/tests/e2e/matmul/generate_e2e_matmul_tests.py and use it in the same manner, as an additional test case generator?

(This is putting aside benchmarking, which I think we should leave as a follow-up, because that's a larger problem, and one that we don't have the right people involved in this thread to figure out.)

**Comment by stellaraccident** [comment]
Folks, we've got a testing deficit on a bunch of this stuff, and we're going to need to work together to close on it. I haven't reviewed this whole thread or the implications. I will and will help drive a recommendation, but I wanted to set the expectation that we will need to find a way here.

**Comment by mattwalsh** [comment]
I think the naming of Dispatch Profiler might be causing confusion.  Think of this more as an extensible set of scripts that can run a growing set of workloads in various configurable ways.   It should subsume mmperf, for instance.  What it does and how we use it will evolve, and I ask for some patience in the meantime, but what I was after was to first get this landed so that 
- we can start getting matmul (and other op) sweeps 
- have a simple place for others to add more tests
- have it also be easily-runnable by folks locally

**Comment by julianwa** [comment]
my current target for near-term CI integration is:
1) (optionall) get some of its functional testing coverage and goodness integrated into pre-submits. We should answer the question of how this relates to the current matmul tests, and make sure we incorporate lessons learned from those tests. I think a simple integration that follows the model of adding IREE Dispatch Profiler as an additional generator should work here?
2) Run a defined set of fixed IREE Dispatch Profiler runs nightly (or twice-daily) as we currently do mmperf. This is largely independent of the IREE CI. But that data can be ingested into analytics and dashboards. You don't get pre-submit testing, but it gets us pretty far. We can re-visit pre-submit testing and a deeper benchmark infa integration after this.

**Comment by julianwa** [comment]
> I think a simple integration that follows the model of adding IREE Dispatch Profiler as an additional generator should work here?

I connected with @benvanik on this this morning. For functional testing, which we expect to have on the order of O(10000) calls across a number of invocations of dispatch profiler, we want to bottom out on the IREE trace runner (as the current e2e matmul tests do) instead of iree-benchmark-module. The current e2e matmul tests use https://github.com/openxla/iree/blob/main/tools/iree-e2e-matmul-test.c, which has specialized handling for verifying matmul calls against expected results. @benvanik and I propose creating an iree-check-trace.c, which would be a general utility for validating invocation results in a trace using gTest. IREE Dispatch Profiler can export its invocations w/ golden inputs/outputs in the trace, and have the existing test infra + iree-check-trace.c execute the validation efficiently. I'll start implementating this tomorrow, May 12.

**Comment by GMNGeoffrey** [comment]
We've wanted something like that for a while. It's the natural convergence of iree-run-trace and check test. I'd love to see it replace the latter eventually, which would require an ergonomic way to write a test containing a runtime trace spec and an uncompiled model to be compiled on the host (not jit compiled on the test device)

**Comment by benvanik** [comment]
The traces can take modules on stdin today or can include relative file paths so that the generator tool can produce the yaml indicating calls/inputs/outputs and a .mlir source file, the mlir can be compiled into many different vmfbs (different flags, backends, etc), and the same yaml can be used across all of them.

**Comment by GMNGeoffrey** [comment]
Yeah mostly I want it to be possible to write a test in one file (that's a nice feature of lit tests) where I specify the IR as well the expected pattern of calls. Except that I don't write code anymore :cry: so I guess I really just mean that I think that would be a nice interface for others. More importantly from an infra perspective, any compilation needs to be separable from execution, but the generator design gives us that.

**Comment by julianwa** [comment]
Based on feedback, I prioritized running dispatch profiler in a Github Workflow regularly (as opposed to starting with pre-submit testing). See details in #13585.

**Comment by allieculp** [comment]
@mariecwhite who is looking into helping out here.
