### ISSUE TITLE
IREE dispatch profiler command line invocation options

### ISSUE THREAD

**Issue by manishucsd** [iree-org/iree#13461]
Modify IREE Dispatch profiler to support invocation from CLI of two use cases : 

- [x] specific sweeps of matmuls shapes

Check : [dispatch_profiler/README.md#generate-a-user-specified-sweep-of-matmul-shapes](https://github.com/openxla/iree/blob/ec6faf938ba2bfe5574177eddfca43b992e8c224/experimental/dispatch_profiler/README.md#generate-a-user-specified-sweep-of-matmul-shapes)

```bash
$ python3 ../iree/experimental/dispatch_profiler/generator.py --problem-m=64:1024:128 --problem-n=64:1024:128 --problem-k=4096
```

- [ ] specific sweeps of matmuls datatypes
```
$ python3 ../iree/experimental/dispatch_profiler/generator.py --problem-m=64:1024:128 --problem-n=64:1024:128 --problem-k=4096 --lhs=f16 --rhs=f16 --result=f16

```

- [ ] a defined input format representing a corpus of dispatch regions (expressed in MLIR)

- [ ] specify golden inputs/outputs.

**Archived description** 
The issue description is populated based on the below text  that was originally found in #13259.

Original text : "Modify IREE Dispatch profiler to support invocation from CLI of two use cases (a) specific sweeps of matmuls (or other ops) or (b) a defined input format representing a corpus of dispatch regions (expressed in MLIR) and, optionally, golden inputs/outputs."

**Comment by manishucsd** [comment]
> Can someone provide example and update the description for what we are looking for in ?
> - [ ] Specify golden inputs/outputs.
> - [ ] a defined input format representing a corpus of dispatch regions (expressed in MLIR)

**Comment by julianwa** [comment]
> a defined input format representing a corpus of dispatch regions (expressed in MLIR)
> Specify golden inputs/outputs.

Examples use cases:
1) Extract all of the matmul shapes from a small set of models in the benchmark suite, track performance relative to baseline on that corpus.
2) Extract the matmul shapes from a model and use that to run tuning on those shapes.
3) Extract all dispatch regions from a model and perform regression tracking on those dispatch regions to quickly flag where regressions occured.
4) Extract all dispatch regions from a suite of models, filter to the top 50 by time spent, then profile, categorize, burn down, etc.

I think this just looks like a set of dispatch regions as expressed in MLIR, along with optional npy golden input/output?
