### ISSUE TITLE
IREE dispatch profiler performance reporting

### ISSUE THREAD

**Issue by manishucsd** [iree-org/iree#13463]
Support dumping the performance runs into a csv format. The IREE dispatch profiler does the following for now, let us know if this is enough close this issue.

```bash
$ python3 ../iree/experimental/dispatch_profiler/profiler.py --dispatches=matmul_3456x1024x2048_f16t_f16t_f16t_*_tensorcore_mmasync --verification-enabled=false --profiling-enabled=true --output=data.csv
```
The data.csv has following field and values for the above run:

| Provider     | op_kind | Operation                   | bytes    | flops        | batch_count | m    | n    | k    | lhs  | rhs  | result | split_k_mode | split_k_slices | Tile config | Core class  | Instruction class | Verification | Runtime(ms) | GFLOPs     |
|--------------|---------|-----------------------------|----------|--------------|-------------|------|------|------|------|------|--------|--------------|---------------|-------------|-------------|------------------|--------------|------------|------------|
| IREE Codegen | matmul  | matmul_3456x1024x2048_f16t_f16t_f16t | 25427968 | 14495514624 | 1           | 3456 | 1024 | 2048 | f16t | f16t | f16t   | N/A          | N/A           | 128x256_32x3 | tensorcore | mmasync         | Not verified | 0.062      | 233798.62 |
| IREE Codegen | matmul  | matmul_3456x1024x2048_f16t_f16t_f16t | 25427968 | 14495514624 | 1           | 3456 | 1024 | 2048 | f16t | f16t | f16t   | N/A          | N/A           | 128x128_64x4 | tensorcore | mmasync         | Not verified | 0.064      | 226492.42 |
| IREE Codegen | matmul  | matmul_3456x1024x2048_f16t_f16t_f16t | 25427968 | 14495514624 | 1           | 3456 | 1024 | 2048 | f16t | f16t | f16t   | N/A          | N/A           | 128x128_32x5 | tensorcore | mmasync         | Not verified | 0.062      | 233798.62 |
| IREE Codegen | matmul  | matmul_3456x1024x2048_f16t_f16t_f16t | 25427968 | 14495514624 | 1           | 3456 | 1024 | 2048 | f16t | f16t | f16t   | N/A          | N/A           | 128x64_32x5  | tensorcore | mmasync         | Not verified | 0.077      | 188253.44 |
| IREE Codegen | matmul  | matmul_3456x1024x2048_f16t_f16t_f16t | 25427968 | 14495514624 | 1           | 3456 | 1024 | 2048 | f16t | f16t | f16t   | N/A          | N/A           | 64x64_64x5   | tensorcore | mmasync         | Not verified | 0.101      | 143519.95 |
| IREE Codegen | matmul  | matmul_3456x1024x2048_f16t_f16t_f16t | 25427968 | 14495514624 | 1           | 3456 | 1024 | 2048 | f16t | f16t | f16t   | N/A          | N/A           | 64x64_32x10  | tensorcore | mmasync         | Not verified | 0.103      |  140733.15

**Archived description**
The issue description is populated based on the below text that was originally found in https://github.com/openxla/iree/issues/13259.

Original text : "Modify IREE Distpach profiler to output results in a standard format, e.g. csv. We should choose something that can be converted readily to the format that our benchmark reporting can ingest."

**Comment by manishucsd** [comment]
@julianwa, @KoolJBlack , @mattwalsh let me know if this is sufficient for this issue to close?

**Comment by KoolJBlack** [comment]
Whats the purpose of the "Provider" column? Would we profile anything other than IREE codegen here? 

Other than that, looks fine by me. Not sure if others have things to add.

**Comment by manishucsd** [comment]
We plan to add other providers for performance profiler e.g. Triton. If we can call CUTLASS or cuBLAS through python directly, we should add those to run as well based on some flag `providers=<list of providers to run with default set to IREE codegen>`. Additional providers is  helpful for comparing performance and fast functional verification. The current verification on large matmuls is slow as it runs via numpy on a CPU.

**Comment by mattwalsh** [comment]
Looks like a nice improvement.  Sure looks parse-able to me.  Ok to close.
