### ISSUE TITLE
Square isn't working correctly when using the vulkan backend

### ISSUE THREAD

**Issue by Eliasj42** [iree-org/iree#13478]
### What happened?

when i try to square a tensor with negative values in it using vulkan, it gives the wrong output.  specifically it preserves the negative sign.  i have also tested on cuda and cpu which ran correctly

### Steps to reproduce your issue

if you run this script with a device with vulkan enabled you will get this output

https://gist.github.com/Eliasj42/af1d59e3451d3f13b7d134907ccaac9b

```
INVOKE SQR on CPU
Results: [[1. 1.]
 [1. 1.]]
INVOKE SQR on VULKAN
Results: [[-1. -1.]
 [-1. -1.]]
 ```

the script is meant to take a 2x2 tensor filled with -1 and square it.  cpu has the correct result, and vulkan has the incorrect result

### What component(s) does this issue relate to?

Compiler, Runtime

### Version information

im using iree-runtime version 20230504.386

**Comment by antiagainst** [comment]
Update on this from internal discussions:

[SPIR-V GLSL extended instruction](https://registry.khronos.org/SPIR-V/specs/1.0/GLSL.std.450.html) `Pow` is undefined for `x^y` where `x`/`y` is negative. So we have upstream [patterns](https://github.com/llvm/llvm-project/blob/ec77d1f3d9fcf7105b6bda25fb4d0e5ed5afd0c5/mlir/lib/Conversion/MathToSPIRV/MathToSPIRV.cpp#L295-L321) trying to guard against the corner cases. However, the pattern is faulty--it didn't handle the sign properly. We'd need to fix the upstream pattern to correctly handle signs. To cover all the corner cases would be quite some work. For now we can only focus on the cases where `y` is actually an integer.

**Comment by antiagainst** [comment]
Upstream fix in review from Dan: https://reviews.llvm.org/D150234

**Comment by antiagainst** [comment]
BTW, just wanted to say thanks for the clear and precise bug report! It makes it very easy to know what's wrong and propose fixes. Much appreciated!
