### ISSUE TITLE
Add back Windows Python releases

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#13484]
https://github.com/openxla/iree/pull/8935 "temporarily" removed the Windows release build. Release builds have gotten simpler now, especially for the tools (TF / TFLite importer) packages, and we now have Windows CI builds running on postsubmit that include building the Python bindings. I think now is a good time to add back the automated Windows python release builds.

As part of this, we should be able to fix https://github.com/openxla/iree/issues/6417.

Nod/SHARK has some code for building on Windows that we could reference:
* https://github.com/openxla/iree/commit/a914f65fe886b78e40bba2e235bff702f1177566

Prior discussions:
* Discord "Can we / should we reenable Windows builds and releases? There was a customer ask.": [message link](https://discord.com/channels/689900678990135345/689957613152239638/1012435553926533181)

Once added back, we can remove the warning about packages not being available on Windows at https://openxla.github.io/iree/bindings/python/

**Comment by powderluv** [comment]
Can't wait to drop our custom downstream windows builds :D

**Comment by ScottTodd** [comment]
I made some progress on building Windows Python releases locally today with the scripting we currently use for Linux and macOS. One thing I'm wondering about is: do we need separate wheels for different Python versions (3.9, 3.10, 3.11, etc.), or can we get by with just one for `iree-compiler` and `iree-runtime`? Looks like we're only publishing 3.11 for macOS right now.

**Comment by stellaraccident** [comment]
Just the latest is fine.
