### ISSUE TITLE
JSON serialization/deserialization for the manifest in iree dispatch profiler

### ISSUE THREAD

**Issue by manishucsd** [iree-org/iree#13495]
Currently IREE dispatch profiler uses pickle to serialize/deserialize, pickle has security concerns and we would like to use JSON for serialization/deserialization. 

See comment from from @pzread [here](https://github.com/openxla/iree/pull/13396#discussion_r1189142051)

**Comment by allieculp** [comment]
@manishucsd Are you working on this?
