### ISSUE TITLE
`arith.truncfop` throws error on `vector<f32>` post vectorization

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#13507]
Compilation post vectorization creates a `vector<f32>` that throws an error. This appears to be due to vectorization of a single `f32` constant. This occurs when using the `llvm-cpu` backend.

https://gist.github.com/rsuderman/d4d85b9574d8a91bdeb44acd367590a0

Failure message:
https://gist.github.com/rsuderman/c29decea07b69ec14cce92928e38319e

**Comment by dcaballe** [comment]
This looks like the `floating-point-like` trait doesn't support 0-D vectors. @nicolasvasilache and @qcolombet have been working on them so maybe they help with this.

**Comment by rsuderman** [comment]
This appears to have been fixed.
