### ISSUE TITLE
Add FP16 Models to Benchmark Library

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#13506]
### Request description

At the moment, all models in our benchmark suite are in FP32. We need coverage of other datatypes like FP16 and BF16 (when support becomes available). Below are instructions on how to add FP16 support on 2 models that are known to work with IREE.

PyTorch ResNet50 and BERT FP16 are known to work on the IREE CUDA backend, as demonstrated by SHARK: https://storage.googleapis.com/shark-benchmark-artifacts/2023-02-01.sha_3ece.timestamp_1675256963/summary.html

Let's port these implementations over to the shared OOBI model library.

*Background*
Torch model implementations are located in https://github.com/iree-org/iree-samples/tree/main/iree-torch/library. Note that both [ResNet50](https://github.com/iree-org/iree-samples/blob/main/iree-torch/library/models/resnet50.py) and [BertLarge](https://github.com/iree-org/iree-samples/blob/main/iree-torch/library/models/bert_large.py) already exist in [models/](https://github.com/iree-org/iree-samples/tree/main/iree-torch/library/models) but in FP32. Torch models are lowered to mlir through [import_models.py](https://github.com/iree-org/iree-samples/blob/main/iree-torch/library/import_models.py), see [import_torch_models.sh](https://github.com/iree-org/iree-samples/blob/main/iree-torch/library/import_models.py) for example usage.

*Adding FP16*
Using the SHARK [resnet50_fp16.py](https://sourcegraph.com/github.com/nod-ai/SHARK/-/blob/shark/examples/shark_inference/resnet50_fp16.py) implementation as inspiration, add similar functionality to the OOBI model library in iree-torch with the same batch sizes as the FP32 equivalents.

Ensure that the models can be lowered by running [import_models.py](https://github.com/iree-org/iree-samples/blob/main/iree-torch/library/import_models.py). Generated artifacts will need to be uploaded to gs://iree-model-artifacts/pytorch.

*Adding Benchmarks to IREE*
Once the models can be lowered to mlir, we can add the benchmarks to IREE CI. An example of adding Torch benchmarks can be found https://github.com/openxla/iree/pull/12773. Note that files in tests/e2e/test_artifacts are auto-generated by running `build_tools/scripts/generate_cmake_files.sh`.

### What component(s) does this issue relate to?

Other

**Comment by reichlfl** [comment]
I'll start to take a look at this.

**Comment by reichlfl** [comment]
I've made some progress on this, but I am not sure if this is going in the right direction - when running `import_torch_module_with_fx`, I ran into errors like this:

`RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'`

Apparently torch.jit.script and torch.jit.trace run the model with sample inputs, and lots of operations in PyTorch are not implemented for fp16 on CPU. According to discussions in Discord, the only good way to get around this is to trace on GPU, which is what SHARK is doing as well in the resnet50 implementation (https://sourcegraph.com/github.com/nod-ai/SHARK/-/blob/shark/examples/shark_inference/resnet50_fp16.py).

This still failed during `import_torch_module_with_fx` for some of the models:

````
python exception: Failure while executing pass pipeline:
error: "<eval_with_key>.8":12:24: 'tensor.cast' op operand type 'tensor<?xf32>' and result type 'tensor<0xf16>' are cast incompatible
note: "<eval_with_key>.8":12:24: see current operation: %742 = "tensor.cast"(%741) : (tensor<?xf32>) -> tensor<0xf16>
````

I ended up using `import_torch_module` instead (so without the fx framework), and with this I have an implementation that can now dump fp16 MLIR for ResNet50, EfficientNet_v2 and BertLarge: https://github.com/reichlfl/iree-samples/blob/benchmarks/resnet50-fp16/iree-torch/library/import_models.py (with some cleanup needed).

Before I start cleaning this up and submitting a PR: Is this even a feasible solution? @mariecwhite

**Comment by mariecwhite** [comment]
If the generated MLIR is able to compile and run through IREE then it's feasible. The `import_torch_module_with_fx` is used to make transformations to the graph in order for it to be compatible with `iree-torch`. If it works without it, then even better. 

I suggest testing the compile and run path:

```
iree-compile --output-format=vm-bytecode \
    --iree-hal-target-backends=cuda \
    --iree-input-type=none \
    --iree-hal-cuda-llvm-target-arch=sm_80 \
    resnet50_fp16.mlir -o resnet50_fp16.vmfb

iree-benchmark-module --module=resnet50_fp16.vmfb \
    --function=forward \
    --input=1x3x224x224xf32=0 \ // f32 may need to be changed to f16
    --device="cuda://0"
```

**Comment by reichlfl** [comment]
I verified that ResNet-50 and EfficientNet-V2 work. For Bert-Large, MLIR generation works with and without the fx framework. I'm struggling to find the correct formatting of input parameters for Bert-Large to verify, it seems to expect 2 tensors and I can't figure out how to specify this in the `input` parameter.

Edit: Verified Bert-Large to work as well. I'll need to clean up the scripts a bit, then the generation part is done for these three models.

**Comment by mariecwhite** [comment]
Fantastic!

Just for future use, the mlir itself will have details of the input and output sizes. There is usually a function at the top that specifies this:

```
func.func @forward(%arg0: tensor<1x384xi64>, %arg1: tensor<1x384xi64>) -> tensor<1x384x1024xf32> {
```

arg0 and arg1 are the inputs and the third tensor is the output.

**Comment by reichlfl** [comment]
BertLarge: https://github.com/openxla/iree/pull/13757
ResNet50: https://github.com/openxla/iree/pull/13739
As an extra, added EfficientNet V2: https://github.com/openxla/iree/pull/13758

Pipeline changes: https://github.com/iree-org/iree-samples/pull/169
