### ISSUE TITLE
Data Tiling: Fold pack into constants

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#13527]
The splat constant is a simple case, which can be upstreamed as a folding pattern. For non-splat constants, we can either emulate it. TPP has an [implementation](https://github.com/plaidml/tpp-mlir/blob/26d9e255bdd40b2c5588ab44bffa07f1a384b105/lib/TPP/ConstantFoldPack.cpp#L50); we can upstream it and add the pass to IREE. We don't add it to a folding pattern because that could execute for a long time, which increases compilation time.

**Comment by benvanik** [comment]
Note that if this becomes load bearing for performance we'll want to ensure that we are doing some hierarchical packing (macro/micro blocks) - if the exact innermost packing is not statically available then we can't fold it into constants but could still do some outermost packing (into 64x64 blocks, etc). A VMFB generated for one single specific architecture will be fine with basic packing, but a VMFB generated for multiple architectures (including the same major architecture but different features) will need this (think if the packing params differ between little and big ARM cores but the user compiling can't specify which cores they are running on in the iree-compile command line).

**Comment by hanhanW** [comment]
Seems to be a dup of https://github.com/openxla/iree/issues/11360, moving the context to that issue.
