### ISSUE TITLE
Add support for sub-byte elements in SPIR-V type conversion

### ISSUE THREAD

**Issue by qedawkins** [iree-org/iree#13552]
Compilation fails for
```
#map = affine_map<(d0, d1) -> (d0, d1)> 
module {
  func.func @forward(%arg0: tensor<64x64xi4>, %arg1: tensor<64x64xi4>) -> tensor<64x64xi4> {
    %0 = tensor.empty() : tensor<64x64xi4>
    %1 = linalg.generic {indexing_maps = [#map, #map, #map], iterator_types = ["parallel", "parallel"]} ins(%arg0, %arg1 : tensor<64x64xi4>, tensor<64x64xi4>) outs(%0 : tensor<64x64xi4>) {
    ^bb0(%in: i4, %in_0: i4, %out: i4): 
      %2 = arith.addi %in, %in_0 : i4 
      linalg.yield %2 : i4 
    } -> tensor<64x64xi4>
    return %1 : tensor<64x64xi4>
  }
}

```
With compile command
```
iree-compile int4_add.mlir \
    --iree-hal-target-backends=vulkan \
    --iree-stream-resource-index-bits=64 \
    --iree-vm-target-index-bits=64 \
    --iree-vulkan-target-triple=ampere-unknown-linux \
    -o /tmp/int4.vmfb
```

(IR immediately before convert to SPIR-V)
```
module {
  func.func @forward_dispatch_0_generic_4096_i4() {
    %c32 = arith.constant 32 : index
    %c0 = arith.constant 0 : index
    %c4096 = arith.constant 4096 : index
    %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<?xi4, #spirv.storage_class<StorageBuffer>>{%c4096}
    %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<?xi4, #spirv.storage_class<StorageBuffer>>{%c4096}
    %2 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%c0) : memref<?xi4, #spirv.storage_class<StorageBuffer>>{%c4096}
    %workgroup_id_x = hal.interface.workgroup.id[0] : index
    %3 = gpu.thread_id  x
    %4 = arith.muli %workgroup_id_x, %c32 : index
    %5 = arith.addi %3, %4 : index
    %6 = memref.load %0[%5] : memref<?xi4, #spirv.storage_class<StorageBuffer>>
    %7 = memref.load %1[%5] : memref<?xi4, #spirv.storage_class<StorageBuffer>>
    %8 = arith.addi %6, %7 : i4 
    memref.store %8, %2[%5] : memref<?xi4, #spirv.storage_class<StorageBuffer>>
    return
  }
}

```

fails to convert to SPIR-V due to `memref<?xi4, #spirv.storage_class<StorageBuffer>>` storage type.
```
%1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<?xi4, #spirv.storage_class<StorageBuffer>>{%c4096}
```

Currently for other sub-int32 types in SPIR-V, without something like the `SPV_KHR_8bit_storage` capability, a single byte load will get converted to a 32-bit load followed by some arithmetic to extract the single byte value.
```
      %9 = spirv.AccessChain %__resource_var_0_0__addr[%cst0_i32_0, %8] : !spirv.ptr<!spirv.struct<(!spirv.rtarray<i32, stride=4> [0])>, StorageBuffer>, i32, i32
      %10 = spirv.Load "StorageBuffer" %9 : i32
      %cst4_i32_2 = spirv.Constant 4 : i32 
      %cst8_i32 = spirv.Constant 8 : i32
      %11 = spirv.UMod %7, %cst4_i32_2 : i32 
      %12 = spirv.IMul %11, %cst8_i32 : i32
      %13 = spirv.ShiftRightArithmetic %10, %12 : i32, i32
      %cst255_i32 = spirv.Constant 255 : i32
      %14 = spirv.BitwiseAnd %13, %cst255_i32 : i32
```
However this is not properly kicking in for sub-byte element types.

**Comment by kuhar** [comment]
I think part of the issue may be that we hardcode the list of  bitwidths of int/float types considered scalar types in the spirv dialect. I wonder if we should relax this requirement?

**Comment by qedawkins** [comment]
> I think part of the issue may be that we hardcode the list of bitwidths of int/float types considered scalar types in the spirv dialect. I wonder if we should relax this requirement?

I haven't walked all the way through to see exactly what needs to be changed but I figure it is something along those lines. I'm assuming that sub-byte cases can be viewed as just never having the necessary storage/compute capabilities and it will just work? For sure relaxing the requirement to at least 2 and 4 bit would be a good starting point.

**Comment by antiagainst** [comment]
> I think part of the issue may be that we hardcode the list of bitwidths of int/float types considered scalar types in the spirv dialect. I wonder if we should relax this requirement?

These sub-byte types aren't supported in SPIR-V spec yet. We don't have corresponding SPIR-V compute/storage capabilities for them. Treating them similarly as other integer types it's easy to see subtle bugs (e.g., around capability checking and target environment support). So I won't just directly enable them in `spirv::ScalarType`. 

Instead I'd prefer to just have special conversion functions like `convertSubByteType` / `convertSubByteMemRefType` / etc. inside SPIR-V type converter. Just forcefully convert them to use i32 emulation. This makes it easy to recognize them and change afterwards.

**Comment by antiagainst** [comment]
Uploaded https://reviews.llvm.org/D150395 to enable sub-byte element types in SPIR-V type converter.
