### ISSUE TITLE
Support sub-byte types for LLMs

### ISSUE THREAD

**Issue by qedawkins** [iree-org/iree#13567]
This issue is meant to house the list of tasks/issues pertaining to enabling sub-byte types for large language models (LLMs). It spans different layers in the whole IREE stack, which are organized into different task lists. The immediate goal is to enable end-to-end solution to quantized matmul, examples in #12859; the ultimate goal is to enable end-to-end LLaMA/Alpaca/etc. inference. 

For sub-byte types, right now the focus is on power of two bit widths (`i4` and `i2`). We may need to extend to `i3` in the future; but that would likely mean its own tracking issues. 

```[tasklist]
## Flow/Stream tasks
- [ ] https://github.com/openxla/iree/pull/13344
```

```[tasklist]
## SPIR-V CodeGen Tasks
- [ ] https://github.com/openxla/iree/issues/13552
- [ ] https://github.com/openxla/iree/pull/13603
- [ ] https://github.com/openxla/iree/pull/13780
- [ ] https://github.com/openxla/iree/pull/13806
- [ ] https://github.com/openxla/iree/pull/13908
- [ ] https://github.com/openxla/iree/issues/13601
- [ ] Enable end-to-end `i4` matmul (tracking issue pending)
```

```[tasklist]
## LLVM CPU CodeGen Tasks
- [ ] https://github.com/llvm/llvm-project/issues/62662
- [ ] Push through the dequant operation in isolation (tracking issue pending)
- [ ] #14195
```

```[tasklist]
## VM tasks
- [ ] [vm] Make sure proper FlatBuffer serialization for sub-byte types (tracking issue pending)
- [ ] Expose sub-byte types to IREE ABI for data exchange with users (tracking issue pending)
- [ ] Enable sub-byte data read/write in IREE tools (tracking issue pending)
```

```[tasklist]
## Model tasks
- [ ] Generate full end-to-end i4 LLaMA/Alpaca model (tracking issue pending)
- [ ] https://github.com/openxla/iree/issues/13926
```

**Comment by powderluv** [comment]
@yzhang93 fyi

**Comment by pzread** [comment]
Hi @qedawkins , are you going to work on this task 🙂 ? Originally I was planning to pick this up next week (but will only spend 20% of my time).

If it's urgent and you are going to work on it then I'll skip this task. Otherwise feel free to assign any standalone tasks to me that still need some people to work on.

**Comment by qedawkins** [comment]
> Hi @qedawkins , are you going to work on this task slightly_smiling_face ? Originally I was planning to pick this up next week (but will only spend 20% of my time).
> 
> If it's urgent and you are going to work on it then I'll skip this task. Otherwise feel free to assign any standalone tasks to me that still need some people to work on.

Hi @pzread, it would be awesome if you want to help out here. There are a few items on the list and we have someone slated for `Move SPIRV small bitwidth load/store emulation to memref`, but there will certainly be tasks up for grabs and I can let you know (haven't really figured out all of the required work yet/work distribution necessary here).

The dequantization task is a subtask of #12859 which is more of an end goal than an individual item (also not all of which is specific to sub-byte element types). I don't think anyone is working on `Add support for power of 2 sub-byte aligned types to IREE tooling` yet though

**Comment by antiagainst** [comment]
I've updated the tile and the tasklist to make it more clear.

**Comment by qedawkins** [comment]
@hanhanW @yzhang93 Here is the current reference IR (and tracking issue): https://github.com/openxla/iree/issues/12859#issuecomment-1546067940

**Comment by hanhanW** [comment]
Thanks for the pointer!

@yzhang93 This is still aligned with our discussion, except the configuration of typeConverter. We'll return int4 for int4 input, not int8 for int4 input. In this context, the types match, so we don't have to create cast ops. Let me know if you run into any issues, I'm happy to look into the code and IRs. I can also help with generating the input IR for the pass from the reference IR.

**Comment by yzhang93** [comment]
> Thanks for the pointer!
> 
> @yzhang93 This is still aligned with our discussion, except the configuration of typeConverter. We'll return int4 for int4 input, not int8 for int4 input. In this context, the types match, so we don't have to create cast ops. Let me know if you run into any issues, I'm happy to look into the code and IRs. I can also help with generating the input IR for the pass from the reference IR.

I'm quite confused by what you said `return int4 for int4 input` for typeConverter. Then is the memref data linearization and shift logic still holds for this case? If possible can we have a VC sometime tomorrow? I can show you what I have right now.

**Comment by hanhanW** [comment]
Okay, SG. I'm available tomorrow, please send me an invitation. Or we can sync on Monday.

**Comment by bjacob** [comment]
Regarding the "Enable end-to-end `i4` matmul (tracking issue pending)" entries above for LLVM CPU, I have filed this issue with my brain-dump on the topic: https://github.com/openxla/iree/issues/14195 - consider linking it from the above tasks overview ?

**Comment by powderluv** [comment]
Don't we have most of this all supported ? Should we close and open a new one for future tasks ?

**Comment by stellaraccident** [comment]
Yeah, let's call this done and re-open with the roadmap of types you were showing this morning.
