### ISSUE TITLE
`flow.tensor.load` invalid with `ui32` loading value for JAX test

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#13576]
It appears that we do not fully support unsigned values in the `flow` dialect.

Compiling the following model fails when reaching `flow.tensor.load`:

https://gist.github.com/rsuderman/b75a385432356e39c17431741a96c0c7

Last known good IR prior to included pass included:

https://gist.github.com/rsuderman/96019c469abf2c42bbc24f68282c9843

Error is shown below:

```
/usr/local/google/home/suderman/Repos/jax/tests/lax_numpy_operators_test.py:439:0: error: 'flow.tensor.load' op result #0 must be index or signless integer or floating-point or complex-type or vector of any type values, but got 'ui32'
/usr/local/google/home/suderman/Repos/jax/tests/lax_numpy_operators_test.py:439:0: note: see current operation: %4 = "flow.tensor.load"(%3) {operand_segment_sizes = array<i32: 1, 0, 0>} : (tensor<ui32>) -> ui32
```

**Comment by benvanik** [comment]
We only support signless types down the stack today and require that users have made things signless earlier on - this is consistent with the rest of MLIR (arith/math/etc). Whatever is generating a flow.tensor.load of a ui32 should instead be generating one of an i32.

**Comment by rsuderman** [comment]
Sounds like we need to find the right area to strip unsigned component.

**Comment by rsuderman** [comment]
Appears to have been fixed in https://github.com/openxla/iree/pull/13678
