### ISSUE TITLE
Python Upgrade to 3.10 Causes Error in Colab Notebook Execution

### ISSUE THREAD

**Issue by xlinsist** [iree-org/iree#13583]
### What happened?

In Colab notebook ["Text classification with TFLite and IREE"](https://colab.research.google.com/github/openxla/iree/blob/main/samples/colab/tflite_text_classification.ipynb), The installation of tflite_runtime failed due to the upgrade of Python to version 3.10 in Colab. As a result, the subsequent code that depends on this package cannot run properly.

The current installation method for tflite_runtime in this Colab notebook is as follows:
```!pip3 install --extra-index-url https://google-coral.github.io/py-repo/ tflite_runtime```

However, the corresponding version of tflite_runtime for Python3.10 is not available in py-repo. Therefore, the script needs to be modified to install tflite_runtime in a different way to make sure the notebook can run properly.

### Steps to reproduce your issue

Run this Colab notebook ["Text classification with TFLite and IREE"](https://colab.research.google.com/github/openxla/iree/blob/main/samples/colab/tflite_text_classification.ipynb).

### What component(s) does this issue relate to?

Other

### Version information

Execution is on current Colab platform.

**Comment by ScottTodd** [comment]
Thanks for the report! Looks like our CI caught another issue with the notebook too: https://github.com/openxla/iree/actions/workflows/samples.yml
https://github.com/openxla/iree/actions/runs/4933042806/jobs/8816641408#step:3:314
```
----- stdout -----
/bin/sh: 1: /work/.notebook.venv/lib/python3.8/site-packages/iree/tools/tflite/iree-import-tflite: not found
```

This code should just run `iree-import-tflite` without going through `get_tool`:
```python
# Convert TFLite model to TOSA MLIR (bytecode) with IREE's import tool.
IREE_TFLITE_TOOL = iree_tflite.get_tool('iree-import-tflite')
tosa_mlirbc_file = ARTIFACTS_DIR.joinpath("text_classification.mlirbc")
!{IREE_TFLITE_TOOL} {ARTIFACTS_DIR}/text_classification.tflite --o={tosa_mlirbc_file}
```

https://pypi.org/project/tflite-runtime-nightly/ might work for tflite_runtime (that does have Python 3.10 wheels)

**Comment by ScottTodd** [comment]
https://github.com/openxla/iree/tree/main/samples/colab#working-with-github instructions for updating the checked in notebooks, if someone else wants to fix this before I get the chance :)
