### ISSUE TITLE
[Epic] Initial Hopper Exploration to prepare for LLM execution

### ISSUE THREAD

**Issue by allieculp** [iree-org/iree#13606]

**Comment by allieculp** [comment]
New Epic item to track hopper exploration this quarter.
@grypp Has recently started on this work and can add tasks here or updates as they are available.

**Comment by grypp** [comment]
I am done with the initial exploration is done, I think we can close this issue. 

I listed what needs to be done for Hopper codegen in #14106. We could that one Epic. Currently I am actively working on TMA #14126 which one of the Hopper codegen task.
