### ISSUE TITLE
[Epic] Add Datatype support: int4, fp8, int8

### ISSUE THREAD

**Issue by allieculp** [iree-org/iree#13638]
@mattwalsh Newly added epic per our discussion on datatype support. This is P2 for now - can bump up in priority in Q3 if needed. Please add any details here as needed.

```[tasklist]
### Tasks
- [ ] Clarify requirements for Int8 support, to determine priority/timeline (@silvasean)
- [ ] #13567 
```

**Comment by antiagainst** [comment]
Related: we are pushing for int4 for LLMs, tracked in https://github.com/openxla/iree/issues/13567.

**Comment by powderluv** [comment]
Just want to add int5 is seeing more traction in the recent weeks beyond #13567 effort to get int4.  Int3 is also something to consider for inferencing large models.

**Comment by allieculp** [comment]
@manishucsd Is this still relevant?
