### ISSUE TITLE
[StableHLO] Failed to lagalize 'chlo.erf' in JAX model

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#13650]
### What happened?

Eror compiling a JAX model with stablehlo:

```
error: failed to legalize operation 'chlo.erf' that was explicitly marked illegal
2023-05-17T01:17:15.9229194Z stablehlo.mlir:574:12: note: see current operation: %1562 = "chlo.erf"(%1561) : (tensor<1x384x4096xf32>) -> tensor<1x384x4096xf32>
```

### Steps to reproduce your issue

1. Download https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.10_1684283564/BERT_LARGE/batch_1/stablehlo.mlirbc

2. Compile:

```
iree-compile --output-format=vm-bytecode \
    --iree-hal-target-backends=cuda \
    --iree-input-type=stablehlo \
    --iree-hal-cuda-llvm-target-arch=sm_80 \
    /tmp/stablehlo.mlirbc -o /tmp/module.vmfb
```

### What component(s) does this issue relate to?

Compiler

### Version information

f8b4e44ba88eebc5c1ae066a573883c6389490b9

**Comment by allieculp** [comment]
@kuhar Can you help triage this?

**Comment by allieculp** [comment]
@kuhar is out of office until 5/23 - will circle back then.
@aaron-schneider for vis.

**Comment by kuhar** [comment]
Thanks @mariecwhite, CHLO support is known to be missing. I'm starting the work on CHLO op support this week.

**Comment by kuhar** [comment]
This was fixed by https://github.com/openxla/iree/pull/13838
