### ISSUE TITLE
Compilation crashes during `FormDispatchRegions` pass

### ISSUE THREAD

**Issue by vivekkhandelwal1** [iree-org/iree#13691]
### What happened?

Hi, I'm compiling the following IR using IREE:
```
#map = affine_map<(d0, d1, d2, d3) -> (0, 0, 0, d3)>
#map1 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#map2 = affine_map<(d0, d1, d2, d3, d4) -> (0, 0, 0, d3)>
#map3 = affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2, d4)>
module attributes {torch.debug_module_name = "_lambda"} {
  ml_program.global private mutable @global_seed(dense<0> : tensor<i64>) : tensor<i64>
  func.func @forward(%arg0: tensor<1x?xi64>, %arg1: tensor<1x1x1x84xi64>) -> tensor<1x1x1x84xf32> {
    %cst = arith.constant 1.000000e+00 : f32
    %0 = tensor.empty() : tensor<1x1x1x84xf32>
    %1 = linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%arg1 : tensor<1x1x1x84xi64>) outs(%0 : tensor<1x1x1x84xf32>) {
    ^bb0(%in: i64, %out: f32):
      %4 = arith.sitofp %in : i64 to f32
      linalg.yield %4 : f32
    } -> tensor<1x1x1x84xf32>
    %2 = linalg.generic {indexing_maps = [#map2, #map3], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel"]} ins(%1 : tensor<1x1x1x84xf32>) outs(%0 : tensor<1x1x1x84xf32>) {
    ^bb0(%in: f32, %out: f32):
      linalg.yield %in : f32
    } -> tensor<1x1x1x84xf32>
    %3 = linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%2 : tensor<1x1x1x84xf32>) outs(%0 : tensor<1x1x1x84xf32>) {
    ^bb0(%in: f32, %out: f32):
      %4 = arith.subf %cst, %in : f32
      linalg.yield %4 : f32
    } -> tensor<1x1x1x84xf32>
    return %3 : tensor<1x1x1x84xf32>
  }
}
```
and during compilation, it crashes with the following [stack trace](https://gist.github.com/vivekkhandelwal1/e7338bbefa26076c675b0d070a950c29).

### Steps to reproduce your issue

To reproduce the issue run the following command with the IR specified above:
```
./build/tools/iree-compile --iree-vm-bytecode-module-output-format=flatbuffer-binary  --iree-hal-target-backends=llvm-cpu --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-llvmcpu-target-triple=x86_64-linux-gnu --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=true --iree-util-zero-fill-elided-attrs reproducible.mlir
```

### What component(s) does this issue relate to?

MLIR, Compiler

### Version information

Git Commit: `5d15caf4bc2eefbc517461a2d78ae9b21008f40c`

**Comment by powderluv** [comment]
@MaheshRavishankar / @allieculp can you please direct.

**Comment by MaheshRavishankar** [comment]
oh, thats me.... ok.. ill take a look

**Comment by vivekkhandelwal1** [comment]
> oh, thats me.... ok.. ill take a look

Hi @MaheshRavishankar, any updates regarding the fix of this issue?

**Comment by raikonenfnu** [comment]
Seems to be breaking on this generic:
```mlir
%2 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4, d5, d6, d7) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3, d4, d5, d6, d7) -> (d4, d5, d6, d7)>], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel", "parallel", "parallel", "parallel"]} ins(%0 : tensor<1x1x1x84xi64>) outs(%1 : tensor<1x1x1x84xf32>) {
^bb0(%in: i64 loc("repro.mlir":11:10), %out: f32 loc("repro.mlir":16:20)):
  %5 = arith.sitofp %in : i64 to f32 loc(callsite("repro.mlir":12:12 at "repro.mlir":7:3))
  linalg.yield %5 : f32 loc(callsite("repro.mlir":15:10 at "repro.mlir":7:3))
} -> tensor<1x1x1x84xf32> loc(callsite("repro.mlir":15:10 at "repro.mlir":7:3))
```
Before breaking I tried printing and it seems producerProjectedDims.size() is 4 which corresponds to numResults, and producerIndexingMap.getNumDims() is 8 which corresponds to the input dimension size. 

I think the current implementation of projectDims is trying to check the all dimensions of the map from the producer parallel loop bitvector which would have less dimensions.

Any thoughts on modifying the `producerProjectedDims` to also represent the input dims rather than just the resulting dims? we can initialize non resulting dims to 1s so it doesn't get projected out. (sorry if the question is too noob :D)

**Comment by MaheshRavishankar** [comment]
Ill look into the crash, but this kind of an operation is not well formed

```
  %2 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4, d5, d6, d7) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3, d4, d5, d6, d7) -> (d4, d5, d6, d7)>], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel", "parallel", "parallel", "parallel"]} ins(%0 : tensor<1x1x1x84xi64>) outs(%1 : tensor<1x1x1x84xf32>) {
  ^bb0(%in: i64, %out: f32):
    %5 = arith.sitofp %in : i64 to f32
    linalg.yield %5 : f32
  } -> tensor<1x1x1x84xf32>
```

All the loops are parallel, but the `result`/`outs` operand rank is not same as the rank of the iteration space, i.e. what happens to the value computed from the iterations that are not represented in the indexing map of the result?

**Comment by MaheshRavishankar** [comment]
This is definitely because the op is not well formed. THere used to be a Linalg check to guard against these, but I dropped that, which I think I relaxed too much.... I can revisit that... but would be good to triage why this kind of is generated.

**Comment by raikonenfnu** [comment]
Yeah seems like the IR generated is not very good. I think it may be because for the input it treats the maps as 0/broadcast on dimension with size 1. I have a local wip patch that canonicalizes these cases out to dimensions rather from broadcasts. But I reckon the right move forward is to fix the pass that generate this ill-formed generic. :)

**Comment by powderluv** [comment]
This one is a little higher priority since we don't have a workaround and is for a popular model LLaMA/Vicuna.  FYI @allieculp

**Comment by MaheshRavishankar** [comment]
I have it already as a P0, but it seems to be a bad form op

**Comment by allieculp** [comment]
@MaheshRavishankar Reminder on this P0 item.

**Comment by MaheshRavishankar** [comment]
We can drop the P0 if needed... this is an input issue....

**Comment by MaheshRavishankar** [comment]
@raikonenfnu please close if this is not an issue anymore.

**Comment by vivekkhandelwal1** [comment]
Fixed with changes in the Torch-MLIR.
