### ISSUE TITLE
Reenable ukernels bitcode on Windows

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#13699]
In #13697 I had to disable building ukernels bitcode on Windows due to a linking error:
https://github.com/openxla/iree/pull/13697#issuecomment-1555184414

**Comment by ScottTodd** [comment]
https://github.com/openxla/iree/actions/runs/5027770230/jobs/9017669780#step:8:8408
```
error: linking module flags 'wchar_size': IDs have conflicting values in 'ukernel_bitcode.bc' and 'e2e_matmul_mmt4d_f32_small_ukernel_x86_llvm_cpu_local_task_linked_llvm_cpu'
```

https://developer.arm.com/documentation/100067/0612/armclang-Command-line-Options/-fshort-wchar---fno-short-wchar
> All linked objects must use the same `wchar_t` size, including libraries. It is not possible to link an object file compiled with `-fshort-wchar`, with another object file that is compiled without `-fshort-wchar`.

I tried adding those flags in https://github.com/openxla/iree/blob/main/runtime/src/iree/builtins/ukernel/arch/x86_64/CMakeLists.txt. With `-fshort-wchar`, I see the error above. With `-fno-short-wchar`, I see this instead:
```
error: linking module flags 'wchar_size': IDs have conflicting values in 'ukernel_bitcode_base.bc' and 'llvm-link'
```

**Comment by ScottTodd** [comment]
Ah, I need to edit https://github.com/openxla/iree/blob/main/runtime/src/iree/builtins/ukernel/CMakeLists.txt also

**Comment by ScottTodd** [comment]
Cool, `-fno-short-wchar` in all those places fixes the build (`iree-test-deps`) for me.

I'll see if I can fix/silence the warnings too, e.g.
```
[build] [876/2701  30% :: 8.108] Compiling query_tile_sizes.c to ukernel_bitcode_base_query_tile_sizes.c.bc
[build] In file included from D:/dev/projects/iree/runtime/src/iree/builtins/ukernel/query_tile_sizes.c:7:
[build] In file included from D:/dev/projects/iree/runtime/src\iree/builtins/ukernel/query_tile_sizes_internal.h:10:
[build] In file included from D:/dev/projects/iree/runtime/src\iree/builtins/ukernel/query_tile_sizes.h:10:
[build] D:/dev/projects/iree/runtime/src\iree/builtins/ukernel/common.h:290:23: warning: overflow in expression; result is -9223372036854775808 with type 'long long' [-Winteger-overflow]
[build] IREE_UK_STATIC_ASSERT(IREE_UK_INT64_MIN == -(1ULL << 63));
[build]                       ^
[build] D:/dev/projects/iree/runtime/src\iree/builtins/ukernel/common.h:277:27: note: expanded from macro 'IREE_UK_INT64_MIN'
[build] #define IREE_UK_INT64_MIN -0x8000000000000000LL
[build]                           ^
[build] 1 warning generated.
```
