### ISSUE TITLE
Failed to compile reduction + broadcast dispatch in CPU backend

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#13706]
I noticed that CPU codegen generates bad code when the split_reduction is involved. A giant vector is generated because we do not tile on consumer. This impacts more after we enable it for FP cases (https://github.com/openxla/iree/pull/13685). The lowering_config is disappeared after split_reduction, so the elementwise op is not tiled and it results in a vector<8xMxf32> type. We can't compile BertLarge now and I expect we'll see this pattern in more upcoming models.

I think we should teach the pipeline to tile the parallel op before applying split reduction.

To repro, run `iree-compile --output-format=vm-bytecode --iree-hal-target-backends=llvm-cpu ~/repro.mlir -o /tmp/a.vmfb`

```mlir
#map = affine_map<(d0, d1) -> (d0, d1)>
#map1 = affine_map<(d0, d1) -> (d0)>
#map2 = affine_map<(d0, d1) -> (d1)>
module {
  func.func @foo(%arg0: tensor<512x1024xf32>, %arg1: tensor<1024xf32>) -> tensor<512x1024xf32> {
    %cst = arith.constant 9.99999997E-7 : f32
    %cst_0 = arith.constant 1.024000e+03 : f32
    %cst_1 = arith.constant -0.000000e+00 : f32
    %0 = tensor.empty() : tensor<512x1024xf32>
    %1 = tensor.empty() : tensor<512xf32>
    %2 = linalg.fill ins(%cst_1 : f32) outs(%1 : tensor<512xf32>) -> tensor<512xf32>
    %3 = linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["parallel", "reduction"]} ins(%arg0 : tensor<512x1024xf32>) outs(%2 : tensor<512xf32>) {
    ^bb0(%in: f32, %out: f32):
      %5 = arith.mulf %in, %in : f32
      %6 = arith.addf %out, %5 : f32
      linalg.yield %6 : f32
    } -> tensor<512xf32>
    %4 = linalg.generic {indexing_maps = [#map2, #map, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%arg1, %arg0, %3 : tensor<1024xf32>, tensor<512x1024xf32>, tensor<512xf32>) outs(%0 : tensor<512x1024xf32>) {
    ^bb0(%in: f32, %in_2: f32, %in_3: f32, %out: f32):
      %5 = arith.divf %in_3, %cst_0 : f32
      %6 = arith.addf %5, %cst : f32
      %7 = math.rsqrt %6 : f32
      %8 = arith.mulf %in_2, %7 : f32
      %9 = arith.mulf %in, %8 : f32
      linalg.yield %9 : f32
    } -> tensor<512x1024xf32>
    return %4 : tensor<512x1024xf32>
  }
}
```

**Comment by dcaballe** [comment]
Created a revert commit for https://github.com/openxla/iree/pull/13685. IIRC, split-reduction is doing some kind of tiling internally because there was some problem with preserving the lowering config. I have to refresh my mind. We did that as an initial approach but I think we should revisit that approach. I'll come back to this next week.

**Comment by hanhanW** [comment]
I think we had an assumption that "root op" always has more dimensions than other operations. (or maybe just me). In the kernel configuration, we only consider the loops of reduction op. Do we use the reduction tiling size for the consumer? What if the generic op has more loops than the reduction op? I think we can discuss this in today's meeting..

**Comment by dcaballe** [comment]
We discussed this internally and I think @hanhanW will be looking into duplicating the lowering config for ops as a first step.

**Comment by hanhanW** [comment]
Okay, I found that this becomes very critical. It makes MobileNetV2_Int8 compilation time so looooooooong. Because the int8 reduction goes with split reduction; the broadcast dimension of consumer is not tiled which results in huge IR. I'm going to look into this which can put us to a reasonable state and unblock some work on my plate..
