### ISSUE TITLE
IREE compilation fails on TOSA-imported tflite models since candidate-20230525.530

### ISSUE THREAD

**Issue by lundong** [iree-org/iree#13783]
### What happened?

Since IREE candidate-20230525.530, iree compllation has failed for TOSA-imported tflite models. The error message is error: 'tosa.avg_pool2d' op requires attribute 'acc_type'. The issue doesn't exist for candidate-20230524.529 or earlier releases.

### Steps to reproduce your issue

1. Build IREE
2. Use person.detect.tflite as an example, which can be downloaded from https://storage.googleapis.com/iree-model-artifacts/person_detect.tflite
3. Import TFLite model
/path/to/iree-import-tflite /path/to/person_detect.tflite -o=/tmp/person_detect.mlir
4. Use iree-compile to compile TOSA MLIR
/path/to/iree-compile -iree-input-type=tosa -iree-hal-target-backends=llvm-cpu /tmp/person_detect.mlir
5. See error
error: 'tosa.avg_pool2d' op requires attribute 'acc_type'
note: see current operation: %114 = "tosa.avg_pool2d"(%113) <{kernel = array<i64: 3, 3>, pad = array<i64: 0, 0, 0, 0>, quantization_info = #tosa.unary_quant<input_zp = 0, output_zp = 0>, stride = array<i64: 2, 2>}> : (tensor<1x3x3x256xi8>) -> tensor<1x1x1x256xi8>
note: in bytecode version 0 produced by: MLIR17.0.0git

### What component(s) does this issue relate to?

Compiler

### Version information

 IREE candidate-20230525.530

### Additional context

I further nailed down the issue to this commit: https://github.com/openxla/iree/pull/13666

**Comment by lundong** [comment]
@jpienaar @hcindyl

**Comment by lundong** [comment]
It appears that the issue is that the tf-nightly version in our side did not match with IREE (https://github.com/openxla/iree/blob/main/integrations/tensorflow/test/requirements.txt), so it's not an IREE issue. Closing it.

**Comment by lundong** [comment]
It appears that the issue is that the tf-nightly version in our side did not match with latest IREE (https://github.com/openxla/iree/blob/main/integrations/tensorflow/test/requirements.txt), so it's not an IREE issue. Closing it.

**Comment by hcindyl** [comment]
@jpienaar What's the plan for the tensorflow package dependency? Do we plan to always pick the latest TOSA API change via tf-nightly, or Does IREE plan to pin to an TensorFlow stable release? I know 2.13.0-rc0 was cut, but not sure what the plan of the team is.

**Comment by jpienaar** [comment]
We plan on pinning to latest nightly needed, unfortunately we are missing an interchange/set of functions here that would enable pinning to stable alone. I'll start a discussion on that, but we might have to rely on the same nightly for a bit.

**Comment by ScottTodd** [comment]
Can we encode the compatible version range in [pyproject.toml](https://github.com/openxla/iree/blob/main/integrations/tensorflow/python_projects/iree_tflite/pyproject.toml) or [requirements.txt](https://github.com/openxla/iree/blob/main/integrations/tensorflow/test/requirements.txt), so that `python-m pip install --find-links https://openxla.github.io/iree/pip-release-links.html --upgrade iree-tools-tflite` gets people something usable (or fails early)?

**Comment by stellaraccident** [comment]
At the expense of risking some cargo-culting of only partially considered Python code, have a look here: https://github.com/openxla/openxla-pjrt-plugin/blob/main/python_packages/openxla_cuda_plugin/setup.py#L41

That grabs version pins dynamically in setup.py from the project requirements.txt file and converts the (CI friendly) specific version pins with user friendly(er) ranges.
