### ISSUE TITLE
TF importer doesn't work with Keras model

### ISSUE THREAD

**Issue by ghost** [iree-org/iree#13787]
### What happened?

Got
```
tensorflow/compiler/mlir/tensorflow/transforms/xla_cluster_formation.cc:74] no entry function is found
```
when trying to import a keras model

### Steps to reproduce your issue

```
import tensorflow as tf
from iree.compiler import tf as tfc

inputs = tf.keras.Input(shape=(32, 32, 3))
resnet = tf.keras.applications.ResNet50(weights='imagenet',
                                        include_top=True, input_tensor=inputs)

resnet.save("/tmp/resnet50")

loaded_model = tf.saved_model.load("/tmp/resnet50")
print(loaded_model.signatures.keys())

compiler_module = tfc.compile_saved_model("/tmp/resnet50", import_only=True, exported_names="serving")
```

We can see the serving signature is there, but it still fails to compile.

### What component(s) does this issue relate to?

Frontends

### Version information

6a46afd4f82715979b54c57fb41a8505466cd68f

**Comment by aaron-schneider** [comment]
Thanks for the query. Since there's no one on the other side of this issue, we're closing for now. Feel free to open a new issue if you'd like to bring it up again.

**Comment by ShuaiShao93** [comment]
Sorry I filed it with a wrong account and now that account has been deleted. Filed another issue: https://github.com/openxla/iree/issues/13854, please help triage, thanks!
