### ISSUE TITLE
[Epic] Mixed Data Type Support

### ISSUE THREAD

**Issue by manishucsd** [iree-org/iree#13812]
# Mixed data type can categorized into two broad categories:

### 1.a. Mixed precision data type : Inputs and accumulation/output data type are different.
- [x] `F32 <= F16 * F16 + F32` #13813
- [ ] `F32 <= BF16 * BF16 + F32` #13414 

### 1.b. Mixed precision data type : Inputs, accumulation and output data type are different.
- [ ] `F16 <= F16 * F16 + F32` #14004
- [ ] `BF16 <= BF16 * BF16 + F32` #13816

### 1.b. Integer data type : Inputs I8, accumulation is S32, output is S32.
- [ ] `S32 <= I8 * I8 + S32`

### 2. Mixed input data type : Input lhs and rhs data type are different.
- [ ] #14025

### Legends

`ResultType <= LhsType * RhsType + AccumulationType`

```[tasklist]
### Tasks
- [ ] https://github.com/openxla/iree/issues/13969
```

**Comment by qcolombet** [comment]
@manishucsd do you have a sense of which variant(s) we should support first?

**Comment by manishucsd** [comment]
We should start with #13813. I have listed the data types in the order which these should be implemented.

**Comment by allieculp** [comment]
@manishucsd Is this still relevant?
