### ISSUE TITLE
BF16 input, F32 accumulation, BF16 output (Mixed precision)

### ISSUE THREAD

**Issue by manishucsd** [iree-org/iree#13816]
## `BF16 <= BF16 * BF16 + F32`

BF16 input for lhs, and BF16 input for rhs, F32 for accumulation, and BF16 output data types can be supported on CUDA backend by lowering to `mma.sync.aligned.m16n8k16.row.col.f32.bf16.bf16.f32` ptx instruction for accumulation and cast the accumulated `f32` result to `bf16` before writing the output out in epilogue.

**Comment by manishucsd** [comment]
Can `linalg.matmul` represent this computation? 


```mlir
  %result = linalg.matmul {
                     ins(%lhs, %rhs: tensor<256x128xbf16>, tensor<128x512xbf16>)
                     outs(%inital_result: tensor<256x512xf32>) -> tensor<256x512xbf16>
```

We will need to specify lhs, rhs, result, and accumulation types. I don't see accumulation data type in `linalg.matmul`. This will be two ops `linalg.matmul` followed by element-wise cast (`F32`->`BF16`) and element-wise cast will then need to be fused into matmul's epilogue?

**Comment by allieculp** [comment]
@manishucsd @qcolombet Adding this to 'GPU Sprint B' as I assume this work will start next week. Please edit if needed.

**Comment by qcolombet** [comment]
> Can `linalg.matmul` represent this computation?
> 
> ```mlir
>   %result = linalg.matmul {
>                      ins(%lhs, %rhs: tensor<256x128xbf16>, tensor<128x512xbf16>)
>                      outs(%inital_result: tensor<256x512xf32>) -> tensor<256x512xbf16>
> ```
> 
> We will need to specify lhs, rhs, result, and accumulation types. I don't see accumulation data type in `linalg.matmul`. This will be two ops `linalg.matmul` followed by element-wise cast (`F32`->`BF16`) and element-wise cast will then need to be fused into matmul's epilogue?

No it can't.
The `outs` type must have the same type as the result type.

**Comment by qcolombet** [comment]
What does the input IR using this mixed-types form look like?

I would have expected a matmul followed by some down casting and codegen should be enough to handle that (with fusing the downcast with the matmul) as soon as we've fixed https://github.com/openxla/iree/issues/13813.

**Comment by manishucsd** [comment]
> What does the input IR using this mixed-types form look like?

I am not sure how to represent this in linalg using `linalg.matmul`. We need the following separate data types:
- lhs 
- rhs
- accumulator
- result

We do have lhs, rhs, result/accumulator. Yes, I think it will be `linalg.matmul`  followed by downcasting.

```
result <= lhs * rhs + initial_result;   // `linalg.matmul`
output <= ElementOutput(result);  // `arith.fptofp ?` for casting F32 to BF16
```

Two issues here:
1. I don't find appropiate casting in `arith` so it has to come from somewhere else.
2. We will need to fuse `output <= ElementOutput(result)` into the `linalg.matmul`
