### ISSUE TITLE
move CUDART default version to use 12.1 from 11.6.2

### ISSUE THREAD

**Issue by powderluv** [iree-org/iree#13830]
### Request description

Currently we download and use CUDA 11.6.2.  Filing a tracker bug to move us to 12.1.1

We need 12.1.1 (https://developer.download.nvidia.com/compute/cuda/redist/redistrib_12.1.1.json) for Aarch64 CPU + CUDA.  11.6.2 doesn't expose aarch64 builds for CUDA.

**Comment by benvanik** [comment]
This would be great - we need 12 for other new APIs as well!

**Comment by stellaraccident** [comment]
Yes, we should go ahead and do this.

**Comment by allieculp** [comment]
@julianwa @jpienaar @qcolombet Who is the correct owner for this?

**Comment by qcolombet** [comment]
No idea.

**Comment by antiagainst** [comment]
Given that I'm gonna work on the CUDA HAL rewrite, I can take a look at this along the way..

**Comment by stellaraccident** [comment]
I'm seeing what the CI says about this: https://github.com/openxla/iree/pull/13872

**Comment by stellaraccident** [comment]
I think only the packaging flow uses the auto download now. So need to bump versions in the CUDA docker images too...

**Comment by antiagainst** [comment]
Yup. I'm rebuilding the docker images now.

**Comment by antiagainst** [comment]
After some further investigation, this is more than just bumping a version number.  See https://github.com/openxla/iree/pull/13875#issuecomment-1571254158. To repeat:

CUDA 12.1.x requires the driver version to be >=525.60.13, while we are using 460 for the normal dockers, and 515 for bleeding edge dockers. So those all needs to be updated. It means we also need to update Vulkan drivers along the way, given they are intertwined. In addition to docker images, We might also need to update the host machine's drivers to make NVIDIA container toolkit happy (or not limiting CUDA performance).

Also, right now we are using Ubuntu 18.04 for those docker images. It'll be throw away work to update those drivers (with all the pain to satisfying ancient Ubuntu versions) given we are [dropping support for Ubuntu 18.04](https://groups.google.com/g/iree-discuss/c/XrKjhUmz2CA/m/C96Z9zxiAgAJ). We do have [v530 drivers for Ubuntu 20.04](https://packages.ubuntu.com/focal/libnvidia-compute-530). 

So, the order to actions should be:

- [x] Update `base.Dockerfile` to use Ubuntu 20.04
- [x] Update shared CUDA/Vulkan drivers to v530 in both normal and bleeding edge docker images
- [x] Update host machines to v530 drivers if necessary
- [x] Update CUDA toolkit to v12.1.1

**Comment by pzread** [comment]
I can help setup host machine with newer driver if needed.

**Comment by antiagainst** [comment]
> I can help setup host machine with newer driver if needed.

That'd be nice, thanks! After #13907 we'll need that. What Ubuntu versions we are at for the host VMs?
