### ISSUE TITLE
Transform dialect `iree.pipeline_shared_memory_copies ` needs to use `nvidiaTensorCore`

### ISSUE THREAD

**Issue by grypp** [iree-org/iree#13859]
### Request description

For A100, `nvidiaTensorCore` should be always used. I worked on enabling that, but using it make the compiler crash :/ I think this can be fixed it with slightly different transform dialect script.

This is because `nvidiaTensorCore` strategy expects only one `device_async_create_group`, `barriers`, see lines below.
[https://github.com/grypp/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/GPU/GPUPipelining.cpp#L494-L502](https://www.google.com/url?q=https://github.com/grypp/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/GPU/GPUPipelining.cpp%23L494-L502&sa=D&source=docs&ust=1685526470989082&usg=AOvVaw3_Wqfz4SY984iqIb009Fng)

Transform dialect generates 2 `device_async_create_group` and `barrier`. Because transform dialect separates load loops for LHS and RHS, see the IR before than this stage
[https://gist.github.com/grypp/83ef18f584a4bd9ec2502ff4563d7e28#file-transform_matmul-mlir-L43-L69](https://www.google.com/url?q=https://gist.github.com/grypp/83ef18f584a4bd9ec2502ff4563d7e28%23file-transform_matmul-mlir-L43-L69&sa=D&source=docs&ust=1685526470989544&usg=AOvVaw1fiKf5q6TmgWoF2mdNcMpA)

If these 2 loops can be fused, the `nvidiaTensorCore` should work.

### What component(s) does this issue relate to?

Compiler

**Comment by allieculp** [comment]
@grypp Are you working on this? Or looking for an owner?

**Comment by grypp** [comment]
Sorry I forgot to answer that, yes I am looking for an owner. 
@qcolombet or @nicolasvasilache might have better idea about where we are here.

**Comment by nicolasvasilache** [comment]
We have a fix for this, I'll send PRs soon

**Comment by allieculp** [comment]
PR has landed, closing.
