### ISSUE TITLE
Auto input conversion pipeline pass does not declare dependent dialects

### ISSUE THREAD

**Issue by kuhar** [iree-org/iree#13860]
### What happened?

IREE's [`--iree-auto-input-conversion` pass](https://github.com/openxla/iree/pull/13443) walks the input module and decides which input conversion pipeline to run based on the module contents.

The issue with this implementation is that the selected pipeline may produce ops from some other dialects which were not registered by the auto input conversion pass.

I'm not sure how to fix this -- I think we would have to query all the dependent dialects across all input conversion pipelines available, so that we can declare the dependencies before the pass manager starts executing the input conversion pass. Or perhaps it shouldn't be a pass in the first place?

### Steps to reproduce your issue

Repro:
```mlir
func.func @simple_add(%arg0: tensor<2x2xi32>, %arg1: tensor<2x2xi32>) -> tensor<2x2xi32> {
  %0 = "mhlo.add"(%arg0, %arg1) : (tensor<2x2xi32>, tensor<2x2xi32>) -> tensor<2x2xi32>
  return %0 : tensor<2x2xi32>
}
```

Command: `tools/iree-opt --split-input-file --iree-auto-input-conversion repro.mlir`

Error:
```
LLVM ERROR: Building op `tensor.empty` but it isn't registered in this MLIRContext: the dialect may not be loaded or this operation isn't registered by the dial
ect. See also https://mlir.llvm.org/getting_started/Faq/#registered-loaded-dependent-whats-up-with-dialects-management                                          
Please report issues to https://github.com/openxla/iree/issues and include the crash backtrace.                                                                 
Stack dump:  
```

**Comment by benvanik** [comment]
Good catch - registering everything is the only way I was able to get something like this to work on the HAL side but it's always been a massive footgun: if something loads all dialects then it's really easy to miss adding a dependent dialect where required as you'll never see the errors (register all transitive deps of dialects A + B, but B has a dep on something A does but doesn't declare it, you'll never know). Would be nice if dynamic pass managers could handle loading things dynamically better.

Here's where I had to do the full transitive registration (which still makes me sad):
https://github.com/openxla/iree/blob/22f04e91d15a66441813927ef354fd057581185e/compiler/src/iree/compiler/Dialect/HAL/Transforms/TranslateExecutables.cpp#L119-L127

**Comment by jpienaar** [comment]
I had these in and then forgot to do that back in a refactor ... And yes easiest is just register all.

**Comment by kuhar** [comment]
OK I'll use Ben's registration to unblock the stablehlo work then
