### ISSUE TITLE
mhlo compile results in `failed to legalize operation 'mhlo.rsqrt'`

### ISSUE THREAD

**Issue by marcospazianibrunella** [iree-org/iree#13864]
### What happened?

When trying to compile GPT-2 from TF to `llvm-cpu`, I get the following error:

```
gpt2/gpt2.mhlo:154:12: error: failed to legalize operation 'mhlo.rsqrt' that was explicitly marked illegal
    %123 = mhlo.rsqrt %122 : tensor<*xf32>
```

The command that I launch to compile is:
```
iree-compile --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-target-triple=riscv64-unknown-elf --iree-llvmcpu-target-cpu=generic-rv64 --iree-llvmcpu-target-abi=lp64d  --iree-llvmcpu-target-cpu-features="+m,+a,+f,+d,+zvl1024b,+v" --riscv-v-fixed-length-vector-lmul-max=1 --riscv-v-vector-bits-min=-1 --iree-vm-bytecode-module-output-format=flatbuffer-text --iree-input-type=mhlo gpt2.mhlo -o dump.vmfb
```

### Steps to reproduce your issue

1) Create a GPT-2 model from the `transformers` package
2) Define a concrete function for the forward pass and convert the function with `tf.mlir.experimental.convert_function()`
3) Legalize the TF dialect with `tf-opt`
```
tf-opt -- \
    --tf-executor-to-functional-conversion \
    --tf-region-control-flow-to-functional \
    --mhlo-broadcast-propagation \
    --chlo-legalize-to-hlo \
    --xla-legalize-tf \
    --reconcile-unrealized-casts \
    --mhlo-broadcast-propagation \
    ${PWD}/gpt2.tf-mlir \
    -o ${PWD}/gpt2.mhlo 2> /dev/null
```
4) Run the above-mentioned `iree-compile` command

### What component(s) does this issue relate to?

Compiler

**Comment by allieculp** [comment]
@jpienaar @aaron-schneider Can you help triage?

**Comment by jpienaar** [comment]
That's an unranked operation, don't think it'll go much further down codegen wise. The tf-opt invocation is non standard and you'll need to at least run shape inference. Consider using the same pipeline that iree-import-tf uses. That's also the one closest to what TF/XLA bridge runs today.

**Comment by benvanik** [comment]
yep, unranked is entirely unsupported in IREE today - we may be able to support it for marshaling trickery (a `!util.list<tensor<*xf32>>` or something) but will require that anything but assignment has shape casts to a ranked type we can work with.

**Comment by allieculp** [comment]
@marcospazianibrunella We will close this as 'not planned'. Please re-open if you have additional question or comments!
