### ISSUE TITLE
[Python] LLaMA/Vicuna 7B: Different results with `iree-run-module` and Python for local-sync vs local-task 

### ISSUE THREAD

**Issue by pashu123** [iree-org/iree#13887]
### What happened?

The python binding and `iree-run-module` is giving different results for the same module. If we pass device=`local-sync` instead of `local-task` then it's giving correct result for both.

### Steps to reproduce your issue

1. Download the `.mlir` from https://storage.googleapis.com/shark-public/prashant/traced_vicuna/vicuna_fp32.mlir
2. Compile the file with `iree-compile --iree-input-type=none --iree-hal-target-backends=llvm-cpu --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64   vicuna_fp32.mlir -o vicuna_fp32_cpu.vmfb` or directly download the compiled .vmfb from https://storage.googleapis.com/shark-public/prashant/traced_vicuna/vicuna_fp32_cpu.vmfb
3. Download the inputs: inp1: https://storage.googleapis.com/shark-public/prashant/traced_vicuna/inp1.npy and inp2: https://storage.googleapis.com/shark-public/prashant/traced_vicuna/inp2.npy
4. Run via iree-module: `iree-run-module --device=local-task --function=forward --input=@inp1.npy --input=@inp2.npy   --module=vicuna_fp32_cpu.vmfb` 
5. Run via python file present here: https://gist.github.com/pashu123/7f6ac404e16df6e5f5ee69904a06e172 (Make sure .vmfb and inputs.npy is present in the working directory).

### What component(s) does this issue relate to?

Python

**Comment by powderluv** [comment]
@stellaraccident Do you know if there are some hard coded limits for large models in Python ? It seems to work with `local-sync` but  `local-task` is broken.

**Comment by allieculp** [comment]
@stellaraccident bumping up this question for you.

**Comment by monorimet** [comment]
Also seeing this on OPT-1.3b causalLM in SHARK ([scripts](https://github.com/nod-ai/SHARK/tree/ean-examples/tank/examples/opt))
(Though with the minimal reproducer here I don't get zero outputs anymore, there is still a large numerical discrepancy between the CLI and python results). I can post in a separate issue if needed.

First, download [OPT1-3b_causallm_torch.mlir](https://console.cloud.google.com/storage/browser/_details/shark-public/ean/reproducers/OPT-1.3b/opt1-3b_causallm_torch.mlir) and [opt_inputs.npy](https://console.cloud.google.com/storage/browser/_details/shark-public/ean/reproducers/OPT-1.3b/opt_inputs.npy) from google storage.

Next, compile the .vmfb via iree-compile CLI:
```
$ iree-compile   --iree-hal-target-backends=llvm-cpu   --iree-llvmcpu-target-cpu-features=host   --iree-input-type=tm_tensor  ./OPT1-3b_causallm_torch.mlir -o opt_1-3b_causallm_cpu.vmfb
```
Then, compare outputs.

Result via iree-run-module CLI:
```
$ iree-run-module --module=opt_1-3b_causallm_cpu.vmfb --device=local-task --input=@opt_inputs.npy --function="forward"
```
```
EXEC @forward
result[0]: hal.buffer_view
7x50272xf32=[2.94834 14.5756 9.30927 6.47363 -0.313437 7.38492 4.88616 4.59728 7.25485 -0.911679 3.15185 4.6557 1.59125 1.29481 6.41556 7.47692 4.95574 -2.14268 -0.248475 1.17093 4.68253 1.96632 5.32784 4.15875 5.9347 8.25203 3.23525 6.50799 -3.0548 6.74529 1.40539 3.53389 6.88356 3.19104 3.76952 2.37053 3.91945 5.73581 0.524927 1.65923 4.69843 1.61035 3.21051 8.26458 4.23162 4.77576 2.19247 4.63977 4.66689 0.588942 0.792177 3.35028 20.784 3.42859 2.08424 2.19214 4.59036 4.87135 4.76075 3.07932 5.64034 5.44788 4.78164 6.3468 0.63651 3.55223 16.8496 2.24174 -3.31263 3.13459 4.0594 2.36896 6.61765 3.66641 3.33533 6.8761 6.73006 3.80089 3.69612 5.49512 6.96646 -3.55853 -2.15474 -1.08208 0.229271 0.259296 5.65823 13.9674 6.30538 12.07 0.634577 9.06112 2.40593 8.36117 5.24504 -0.417371 10.4688 1.2569 4.4273 5.70295 23.6944 8.04695 3.35502 6.89965 -1.19157 7.52434 7.7293 39.9424 6.58937 1.88599 0.494768 5.7799 1.81822 6.65554 60.3262 1.34465 4.02639 -2.36716 1.0582 1.41486 3.58317 3.21436 8.41087 4.32962 4.56617 -9.82714 -0.103582 11.35 -0.020276 6.95651 7.29273 3.85615 6.15948 2.20276 0.127518 6.51213 4.94281 6.61898 3.77186 7.19528 5.03174 4.7914 2.37093 6.53323 -7.27013 4.65589 4.20186 0.476012 6.70296 7.64788 8.99031 2.27889 1.61391 3.01017 11.1871 2.79387 4.15395 22.4841 -0.577497 4.43767 1.24889 5.44902 -0.951902 2.68433 7.71838 9.71642 1.49543 3.7686 3.40918 37.3999 0.99854 4.7456 3.95081 13.9818 1.20547 0.877985 10.0417 8.65834 1.17496 1.51917 -2.76199 4.01237 8.06007 -16.3872 7.58932 4.2766 7.68889 2.02545 18.6167 -0.938989 7.79755 -0.093023 5.26815 5.66329 3.9232 4.63055 10.3052 3.83729 4.93727 0.180159 7.99011 5.11897 5.98957 -12.8736 5.6559 -4.04781 19.2541 2.483 4.13887 3.43563 12.0108 0.266381 5.95207 6.49906 1.19491 5.01571 7.53914 1.43691 1.90622 1.80129 4.96079 9.85133 3.73206 2.97885 5.21216 9.74323 4.27326 12.5599 6.81814 2.93796 2.70624 0.980518 5.11668 5.89395 2.34502 2.29661 8.8651 8.93802 -4.61994 8.10523 2.32475 6.34241 4.89974 0.698173 -1.13667 5.21234 3.00442 1.28195 8.44585 1.25997 -0.0198879 3.33991 7.52755 6.2915 -1.54593 3.23401 21.4296 1.72268 5.7409 8.07652 7.59363 5.04918 -1.03765 1.63127 1.35323 1.19743 1.75499 6.42178 2.79407 5.82361 6.34583 1.04357 9.44636 9.42863 1.99969 5.20075 4.40394 5.28143 7.74076 -3.88358 9.24959 -1.26748 7.67163 3.80908 7.42529 -1.74011 6.57035 0.857516 3.53969 4.26208 -0.297097 10.7245 5.83582 -45.9941 9.3174 0.58099 0.361688 5.2242 3.87918 6.17008 12.9844 3.94556 -1.2013 1.4726 -0.20297 2.7017 6.09492 5.04951 6.98747 10.9099 3.27381 7.94978 -4.05055 8.62831 3.21525 4.98096 1.8495 0.566623 1.32883 10.074 10.6832 9.80744 3.00608 0.73638 2.47947 37.0239 2.73073 8.19678 6.84128 3.30923 4.24859 1.22497 7.53529 -3.71395 8.44995 0.90246 5.64334 31.1919 6.76813 7.64256 3.73746 9.25642 7.83286 0.79587 5.15696 1.09701 5.38709 1.63566 3.55568 0.601934 14.1719 8.16992 15.394 27.715 7.40352 3.24067 5.55772 3.06972 2.57133 -0.941667 3.10338 34.2619 9.96275 13.1527 -1.1506 0.778797 7.86861 3.49076 7.20688 7.71802 -0.233527 6.41392 -2.28233 -0.0546718 4.38932 5.20563 4.74641 2.43041 2.08818 4.95213 13.7702 8.19769 4.96525 9.1206 7.16902 10.3871 -5.17685 2.69316 5.46975 3.32267 0.330511 5.21704 2.57142 8.80811 10.5984 3.85856 6.27868 6.57451 11.0909 -7.29617 1.71231 8.86106 0.0272421 8.91339 5.9394 7.43471 7.02097 3.46954 2.58332 4.56573 2.14004 1.76901 7.98302 10.742 5.24322 6.24755 10.1236 2.57617 4.76589 5.18782 5.65418 6.95826 3.51378 2.32643 2.55887 3.62295 1.816 5.21066 0.507074 3.08973 5.08201 9.88456 5.99365 6.88611 6.99539 0.0861117 8.86616 11.6564 4.95789 3.35621 5.69229 3.97976 1.56502 0.664644 8.03287 1.36826 3.20662 22.1762 3.88279 4.85906 12.6934 2.19614 6.65419 1.49071 1.6223 2.51792 6.47215 24.974 2.7795 7.98519 4.07335 0.538515 7.79107 3.16269 2.13975 7.53027 2.94785 8.19419 0.749182 4.62506 2.26326 7.70942 0.572177 11.6926 47.1223 -3.32938 0.702576 3.45374 4.56358 6.94536 -0.00444734 15.5254 5.61669 10.5894 10.8647 -1.69715 -3.36514 0.452223 6.10897 2.43097 8.01135 0.165261 7.39069 4.80941 6.66529 2.1852 -8.13614 -0.752949 5.93196 7.28865 6.79724 -0.988823 4.0435 6.15449 2.47481 1.48666 3.12404 2.63603 -0.312227 6.13189 5.6071 0.876941 1.97472 5.75993 34.4012 21.3297 -0.338606 1.59009 3.43077 7.32683 11.2568 0.619672 2.79299 0.571761 6.91695 4.3812 6.33303 2.4205 -2.85566 3.91252 6.03459 7.932 6.63101 5.20744 1.77652 0.281253 4.79458 10.3363 0.617449 6.7919 3.80615 2.37006 7.18952 -1.81954 1.36022 8.10103 -0.00112903 4.90635 5.47068 4.95526 4.2826 5.63165 6.42912 6.14021 9.42864 3.60787 0.15519 -0.248615 1.09022 4.95492 3.08552 -16.9545 4.58337 5.48841 4.75738 4.23428 9.00939 3.88571 3.52152 2.66326 -16.895 6.34931 7.7703 39.262 6.81221 2.97796 8.71187 1.95618 1.33331 4.20138 -0.260283 2.18549 8.52712 7.30723 0.220219 4.80534 1.78412 5.7427 6.66241 3.24528 2.78924 4.67822 5.62007 4.81652 5.84866 4.8761 3.23169 3.51943 2.67263 2.39989 1.03107 1.43068 10.9178 39.698 4.09857 11.1629 7.57305 5.04969 5.04982 0.847995 5.13631 3.04743 1.07226 1.32204 6.46061 7.1132 3.74321 -0.424424 0.195628 -0.680593 2.45492 6.12704 -0.276623 7.00432 2.28607 0.540432 -0.267938 0.136792 8.84125 6.75202 7.14631 10.9719 0.614862 12.2512 10.817 39.7222 1.40288 4.47556 3.12724 1.771 -0.731866 4.22008 3.54444 9.46353 9.48026 46.7658 0.420833 -0.429809 -2.5973 0.332361 8.00279 5.63607 1.94172 5.16059 4.73461 8.00974 5.3987 16.8656 1.44075 15.7052 6.05149 3.25539 1.75049 1.76956 2.6969 3.45118 9.06044 1.40847 -1.84214 1.42192 -4.95299 7.99245 3.23711 5.74125 7.42232 5.88035 2.10327 8.47351 -0.0183524 6.60062 7.44755 5.87337 10.119 3.10312 4.45453 12.7134 6.27745 5.41678 3.80058 -0.548185 -0.603305 8.40583 4.68203 8.14324 7.59123 4.01495 1.71522 3.78318 5.36191 6.57578 6.37356 4.91261 0.963246 3.77043 -7.44217 5.07138 2.33761 2.19641 7.33943 1.54207 9.13806 5.43469 8.26491 4.23483 -0.807678 1.22859 0.903595 -1.61375 4.83995 7.90862 8.86006 3.64684 28.6511 2.15856 3.81894 2.67405 8.80639 10.8877 1.15295 7.61567 6.66208 3.19925 1.24426 -0.78798 -3.76183 0.688506 0.677957 -1.11061 3.87255 10.0773 4.61958 3.54312 1.39276 2.9118 0.0256047 4.18747 5.00702 3.87672 4.74112 2.39156 4.69182 1.91478 3.83872 0.267542 4.43059 5.68231 5.1325 4.27786 -1.8466 3.64055 0.802484 5.57674 7.31685 6.81487 6.68881 0.740587 3.00292 8.4123 8.54982 8.27742 2.65532 5.03131 1.94029 1.44337 60.6036 6.04263 5.09592 -1.36944 9.19342 4.32808 7.72768 8.56478 8.35456 1.25826 3.12301 6.07682 -0.350705 1.87986 6.44226 -47.3564 3.62287 6.31355 5.472 3.43914 0.528657 6.73231 1.32923 7.51019 0.653297 -5.11447 7.13278 9.57158 7.25321 12.4178 1.10473 46.8132 5.28414 1.85038 8.04544 0.737446 -1.84865 -13.0904 4.99317 6.18007 17.5929 3.93501 7.01666 2.53972 5.6844 4.61888 4.88256 1.78797 33.4263 2.52434 3.28633 2.95614 6.50113 4.45199 5.80053 5.46889 4.08105 5.79316 4.655 8.07873 -2.72754 3.17546 1.38662 6.08766 4.52608 6.49184 31.4295 5.65546 0.00874248 4.37265 8.09895 30.7958 1.27111 5.92358 2.55091 6.58639 6.97127 0.369028 8.40868 3.04068 3.42195 10.2559 1.34539 0.317024 4.33061 9.98743 2.5216 5.77993 15.8003 1.28343 9.72739 6.30308 1.99898 -1.37273 10.0737 6.96748 0.97819 5.00121 2.23749 -2.8877 4.64796 18.4443 2.47831 6.49352 3.37294 0.29326 1.57256 4.51505 2.81605 3.13474 0.5363 6.50827 7.97169 5.73318 1.81404 0.881727 7.47614 10.6936 1.21798 3.13017 1.87705 1.44359 8.25364 2.76287 5.4201 9.95462 5.37013 6.01919 2.52633 -7.96248 2.97448 2.63133 7.69234 2.70321 3.81554 4.14315 7.65338 0.937114 5.55588 -0.176203 -4.06987 6.36662 5.57378 6.36037 0.489957 0.83102 1.94642 12.0761 9.72281 8.04834 1.59371 6.70904 9.82342 8.7897 -1.2636 7.26696 12.5162 7.09035 6.40716 2.17167 1.19517 4.69253 3.4689 5.03508 3.54669 7.34515 3.64983 4.46447 0.563884 5.27299 1.55054 10.0226 3.28602 3.79621 -0.627512 1.95582 5.21046 5.11296 8.79448 2.56304 0.0525335 2.00451 1.08398 4.17983 1.30569 4.49934 3.67829 0.0932291 3.96918 1.96688 4.20979 3.75736 3.97223 7.51659 8.93922 1.64232 10.2478 5.33374 0.827418 2.0152 0.323691 4.52538 0.726873 7.62935 3.63006 2.68294 6.7558 6.28431 4.29938 14.1057 5.62125 -1.88496 5.95677 6.49843 3.48598 11.0535 0.273667 8.5397 -4.78582 36.5867 3.74281 9.8521 0.526064 2.8 1.80268 7.82008 3.35961 6.18777 2.02348 -2.68585 8.55171 4.32436 2.91047 6.37027 3.07858 7.39598 -0.602105 10.9998 -0.499573 8.26048 3.44361 2.5413 6.45624 -0.860877 10.1935 3.94506 -1.8854 2.78602 16.3088 3.86918...][...][...][...][...][...][...]
result[1]: hal.buffer_view
0x7x2048xf32=
```
Result via python (can be reproduced with [this python file](https://gist.github.com/monorimet/1633b2e95ddd15156988e2ed4bf588bd))
```
$ python opt_test.py
```
```
[[ 3.194312   14.64125     9.192374   ...  3.8184016   2.64964
  -0.5783603 ]
 [ 3.0902762  15.804577    7.2782545  ...  3.9580245   3.7676458
   0.40852466]
 [ 3.0401552  17.358082    7.2172465  ...  3.5345457   3.6020813
  -0.20694567]
 ...
 [ 2.854957   18.644693    5.1286902  ...  4.240262    3.4892058
  -1.0118058 ]
 [ 2.166676   22.891552    7.766478   ...  3.8540208   3.1496656
   0.1291914 ]
 [ 2.5119016  14.818969    5.8827424  ...  2.7389405   3.8110926
  -0.7152195 ]] []
```

**Comment by benvanik** [comment]
In a program the compiler correctly compiles (which this may not be :) there should be no difference between local-sync and local-task, nor any limits on either from python.

Can you please enumerate what value is what so we can start to triage? ("python produces X with local-sync, python produces Y with local-task, iree-run-module ...." and "Z is the correct answer we expect all to provide")

Two things I'd try are passing `--iree-stream-partitioning-favor=debug` to iree-compile (should disable the compiler's attempts at concurrently issuing work even when running with local-task) and passing `--task_topology_group_count=1` to the runtime to make local-task single-threaded (still may have some behavioral differences but rules out threads stomping on each other and limits it to ordering).

**Comment by monorimet** [comment]
Thanks Ben. I'll try with the compile/runtime flags.

For clarification:
Python produces this result on local-sync: (non-truncated -> [local_sync_opt_logits.txt](https://github.com/openxla/iree/files/11658749/local_sync_opt_logits.txt))
```
local-sync result: 7x50272=
[[ 2.9483373  14.57561     9.309269   ...  3.8072436   2.736043
  -0.48549324]
 [ 2.8499205  15.748621    7.3167763  ...  3.9052784   3.8763328
   0.42264798]
 [ 2.8242998  17.309875    7.2879767  ...  3.4833791   3.7424765
  -0.1637713 ]
 ...
 [ 2.660748   18.589664    5.18831    ...  4.1783724   3.6274369
  -0.9794496 ]
 [ 1.9488358  22.832752    7.8331327  ...  3.781442    3.3019094
   0.1572762 ]
 [ 2.2833219  14.766316    5.9369116  ...  2.6796591   3.9609249
  -0.6819936 ]]
```

Python produces this result on local-task: (non-truncated ->[local_task_opt_logits.txt](https://github.com/openxla/iree/files/11658752/local_task_opt_logits.txt))
```
local-task result: 7x50272= 
[[ 3.194312   14.64125     9.192374   ...  3.8184016   2.64964
  -0.5783603 ]
 [ 3.0902762  15.804577    7.2782545  ...  3.9580245   3.7676458
   0.40852466]
 [ 3.0401552  17.358082    7.2172465  ...  3.5345457   3.6020813
  -0.20694567]
 ...
 [ 2.854957   18.644693    5.1286902  ...  4.240262    3.4892058
  -1.0118058 ]
 [ 2.166676   22.891552    7.766478   ...  3.8540208   3.1496656
   0.1291914 ]
 [ 2.5119016  14.818969    5.8827424  ...  2.7389405   3.8110926
  -0.7152195 ]]
```
the local-sync result appears the same as the output of iree-run-module (with `--device=local-task`) given above.

The result from pytorch that we hope to validate both against: 
[golden_out.txt](https://github.com/openxla/iree/files/11658804/golden_out.txt)

**Comment by benvanik** [comment]
ok cool so nothing produces the right results? (that makes it easier to diagnose as we can ignore that it's different between them and focus on where the compiler is having issues)

**Comment by monorimet** [comment]
In the case of OPT-1.3b, yes. I believe LLaMa/vicuna may be a different case.

**Comment by stellaraccident** [comment]
Skimming, is it safe to assume that this is just broken in all configurations tested? (i.e. none of python, local-sync, local-task are producing correct results)

**Comment by monorimet** [comment]
> Skimming, is it safe to assume that this is just broken in all configurations tested? (i.e. none of python, local-sync, local-task are producing correct results)

I'm actually hoping we move the OPT numerics discussion elsewhere as these may not be the same issue and I don't want to lose track of the LLaMa/vicuna numerics if the problem there is different. @powderluv do you know more about the LLaMa issue? Do our `local-sync` numerics validate against pytorch for vicuna?

**Comment by monorimet** [comment]
> Two things I'd try are passing `--iree-stream-partitioning-favor=debug` to iree-compile (should disable the compiler's attempts at concurrently issuing work even when running with local-task) and passing `--task_topology_group_count=1` to the runtime to make local-task single-threaded (still may have some behavioral differences but rules out threads stomping on each other and limits it to ordering).

These two flags didn't seem to affect the local-task results from python.
Here is the modified script: [gist](https://gist.github.com/monorimet/3130ccf4f701348ce763bce0ee9d3512)

**Comment by benvanik** [comment]
Have you tried non-llvm-cpu backends (CUDA?)? knowing that may isolate it to HLO/linalg/etc vs the particular platform codegen vs the runtime.

**Comment by monorimet** [comment]
CUDA works! (I'll show the pytorch vs. SHARK python numerics at-a-glance for A100 cuda):
```
SHARK logits have shape:  (7, 50272) : [[  1.8319876    1.5199093    6.082119   ...   2.109685     1.9062941
    1.9811553 ]
 [-12.1053505  -11.442817     0.08139505 ... -10.795685   -11.532479
  -11.433617  ]
 [-12.078147   -12.59089      2.0352333  ... -11.382179   -11.428994
  -11.703665  ]
 ...
 [ -7.102992    -7.6976204    4.072431   ...  -7.376941    -6.719622
   -7.269612  ]
 [-11.234247   -11.439148    -6.903964   ... -11.79036    -11.258774
  -11.402507  ]
 [ -2.255033    -2.3394425   16.018326   ...  -1.0540967   -2.1388423
   -1.4458579 ]]
PyTorch logits have shape: torch.Size([7, 50272]) : tensor([[  1.8320,   1.5199,   6.0821,  ...,   2.1097,   1.9063,   1.9812],
        [-12.1054, -11.4428,   0.0814,  ..., -10.7957, -11.5325, -11.4336],
        [-12.0782, -12.5909,   2.0352,  ..., -11.3822, -11.4291, -11.7037],
        ...,
        [ -7.1030,  -7.6976,   4.0724,  ...,  -7.3770,  -6.7196,  -7.2696],
        [-11.2342, -11.4391,  -6.9040,  ..., -11.7903, -11.2587, -11.4024],
        [ -2.2550,  -2.3394,  16.0183,  ...,  -1.0541,  -2.1388,  -1.4458]],
       grad_fn=<MmBackward0>)
```
which are well within our tolerances for correctness validation.

**Comment by jpienaar** [comment]
Well that's a change, GPU works and CPU doesn't. And this is all F32?

**Comment by powderluv** [comment]
just to summarize (@pashu123 can correct if wrong) lets ignore the OPT 1.3B issue for now

For Vicuna/LLaMA:
Pytorch, IREE Python local-sync, CUDA match in FP32.  Just local-task fails.  So can't be an overflow in Python land since the CUDA and local-sync work ok.

**Comment by pashu123** [comment]
> just to summarize (@pashu123 can correct if wrong) lets ignore the OPT 1.3B issue for now
> 
> For Vicuna/LLaMA: Pytorch, IREE Python local-sync, CUDA match in FP32. Just local-task fails. So can't be an overflow in Python land since the CUDA and local-sync work ok.

Also, local-task works fine via `iree-run-module` and outputs right results but gives wrong result via the python's local-task.

**Comment by stellaraccident** [comment]
There isn't much different from the Python API level between the working/not-working cases...

**Comment by benvanik** [comment]
I think the OPT issue is what we should tackle first - having _any_ correctness issues like that scares me and would explain all kinds of other failures (if uninitialized memory is being read then what's in the uninitialized memory that is read will vary between local-sync and local-task, whether python/the long-lived process is recycling memory instead of using 0-initialized OS allocs, etc).

**Comment by allieculp** [comment]
@stellaraccident @jpienaar Looking to get this triaged and understand the priority here. Do we need immediate assignment or can this wait?
@powderluv let us know your needs as well.

**Comment by monorimet** [comment]
OK, after cleaning up and trying to run OPT with iree-run-module CLI, I was able to get correct results for local-task.

I also verified local-sync when running my test script and got the expected results (validated against pytorch).

But loading the flatbuffer into the iree-runtime python context and running on local-task produces zero output just like the llama/vicuna case.

This means we can rule out any underlying correctness issues specific to (or exposed by) OPT, as my case now matches the original issue with zeroes on FP32 vicuna/llama in python local-task. @MaheshRavishankar mentioned that this may be a python garbage collection issue.

**Comment by powderluv** [comment]
@monorimet can you also attach your OPT 1.3B failure case here. It will be easier to debug with a 1.3B parameter model than the 7B in the first comment.

**Comment by monorimet** [comment]
I have uploaded a gist for a minimal reproducer of the local-task zeros issue with the OPT1.3B model in python: [OPT_1.3B_zeroes_case.py](https://gist.github.com/monorimet/cedf5f231139538e65db270e387f0246)

To run the script you will want the following files in the script directory:

- opt-1.3b_causallm_64_torch_cpu.vmfb -- [google storage link]()

  This .vmfb can also be generated via the following iree-compile command (with [this .mlir file](https://storage.cloud.google.com/shark-public/ean/reproducers/OPT-1.3b/opt-1.3b_causallm_64_torch.mlir))
  
  ```
  iree-compile   --iree-hal-target-backends=llvm-cpu   --iree-llvmcpu-target-cpu-features=host   --iree-input-type=tm_tensor  ./opt-1.3b_causallm_64_torch.mlir -o opt-1.3b_causallm_64_torch_cpu.vmfb
  ```
  
- [model_inputs_0.npy](https://storage.googleapis.com/shark-public/ean/reproducers/OPT-1.3b/model_inputs_0.npy) and [model_inputs_1.npy](https://storage.googleapis.com/shark-public/ean/reproducers/OPT-1.3b/model_inputs_1.npy)

**Comment by monorimet** [comment]
In my sentence completion script I can work around this (for example) by running `iree-run-module` via the CLI.

It also works if I run in python via local-sync (can be tested on [OPT_1.3B_zeroes_case.py](https://gist.github.com/monorimet/cedf5f231139538e65db270e387f0246) by changing to local-sync)

Here's what I'm doing to run in a subprocess in case it's relevant for debug:

```
    inputs = (
        model_inputs["input_ids"],
        model_inputs["attention_mask"],
    )
    np.save("model_inputs_0.npy", inputs[0])
    np.save("model_inputs_1.npy", inputs[1])
    #output = shark_model("forward", inputs)
    cmd = [
        "iree-run-module",
        f"--module={vmfb_path}",
        f"--input=@model_inputs_0.npy",
        f"--input=@model_inputs_1.npy",
        f"--device=local-task",
        f"--output=@model_outputs_0.npy",
        f"--output=@model_outputs_1.npy",
    ]
    run_cmd(cmd)
    output = torch.FloatTensor(np.load("model_outputs_0.npy"))
```

**Comment by stellaraccident** [comment]
Ok, I have successfully repro'd on my mac.

**Comment by stellaraccident** [comment]
The plot thickens. In an attempt to shorten the memory thrash on my poor laptop, I switched to mmap:

```
import mmap

vmfb_file = open(os.path.join("vicuna_fp32_cpu_local.vmfb"), "r+b")
mf = mmap.mmap(vmfb_file.fileno(), 0)
flatbuffer_blob = mf

# print("Loading")
# with open(os.path.join("vicuna_fp32_cpu_local.vmfb"), "rb") as mlir_file:
#     flatbuffer_blob = mlir_file.read()
```

... and it gets the right answers.

(as an aside, you all should definitely be using mmap for this sort of thing, but the non-mmap case needs to be nailed down because something nasty must be happening)

**Comment by stellaraccident** [comment]
Ok, I've redone the patch (see above) and tested it comprehensively on Windows. It should now be impossible to use the Python API in a way that violates alignment constraints, but the existing `from_flatbuffer` will now make an extra copy if necessary (and issue a warning).

I expect that most such uses that are coming from files anyway should just use `VmModule.mmap`. But you can also use `VmModule.copy_buffer` (to unconditionally make a copy) or `VmModule.wrap_buffer` if you've been (somehow) able to guarantee that it is aligned (i.e. if you mmap'd it yourself or something).

I'm not sure that I can make it more automatic than that: these exceptionally large modules must be used in a way that reduces loading thrash, and the default way folks have been doing it (i.e. `read` from a file) internally involves multiple copies anyway. I found this to carry large systemic costs no matter what, so I didn't feel too badly about at least making an aligned copy.

If using one of these in-memory APIs (vs mapping), you'll want to make sure that you `del` any references to the backing buffer to limit the possibility of having committed memory for multiple copies.
