### ISSUE TITLE
Periodic failures in `process_benchmark_results`

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#13894]
I'm seeing occasional failures in the `process_benchmark_results` job. It seem to get stuck downloading the results:

https://github.com/openxla/iree/actions/runs/5147952977/jobs/9270529472

**Comment by pzread** [comment]
Not sure if it's related but I also saw this one https://github.com/openxla/iree/actions/runs/5139373686/jobs/9251064372

It seems like there is a stability issue on the dashboard server.

**Comment by pzread** [comment]
Closed as we didn't see this issue for a while
