### ISSUE TITLE
Add a legalization from `stablehlo.custom_call` for `top_k` to `chlo.top_k`

### ISSUE THREAD

**Issue by silvasean** [iree-org/iree#13927]
### Request description

The output of openxla_partitioner [creates TopK stablehlo.custom_call ops](https://github.com/openxla/openxla-pjrt-plugin/blob/382960ba4ba52124ed49ff5278f89d257e64fa5d/partitioner/src/openxla/partitioner/GSPMDPipeline.cpp#L77). IREE does not seem to accept them.

Repro:

```
iree-compile --iree-hal-target-backends=cuda --iree-input-type=xla --iree-hal-cuda-llvm-target-arch=sm_80 topk_partitioner.mlir
```

```
module @main {
  func.func @main(%arg0: tensor<4x8000xbf16>) -> (tensor<4x40xbf16>, tensor<4x40xi32>) {
    %0 = stablehlo.custom_call @TopK(%arg0) {called_computations = [@region_220.6599], xla_shape = "(bf16[4,40]{1,0}, s32[4,40]{1,0})"} : (tensor<4x8000xbf16>) -> tuple<tensor<4x40xbf16>, tensor<4x40xi32>>
    %1 = stablehlo.get_tuple_element %0[0] : (tuple<tensor<4x40xbf16>, tensor<4x40xi32>>) -> tensor<4x40xbf16>
    %2 = stablehlo.get_tuple_element %0[1] : (tuple<tensor<4x40xbf16>, tensor<4x40xi32>>) -> tensor<4x40xi32>
    return %1, %2 : tensor<4x40xbf16>, tensor<4x40xi32>
  }
  func.func private @region_220.6599(%arg0: tensor<bf16>, %arg1: tensor<bf16>, %arg2: tensor<i32>, %arg3: tensor<i32>) -> tensor<i1> {
    %0 = stablehlo.compare  GT, %arg0, %arg1,  TOTALORDER : (tensor<bf16>, tensor<bf16>) -> tensor<i1>
    return %0 : tensor<i1>
  }
}
```

### What component(s) does this issue relate to?

Compiler

### Additional context

iree.git @ 28cdc467bfb61273ee1a1613f6d7efbd961951e3

**Comment by silvasean** [comment]
(bf16 can be replaced by f32 here if desired for simplicity)

**Comment by silvasean** [comment]
Assigning to Rob for triage and next steps

**Comment by stellaraccident** [comment]
Was waiting for this one to come through. We should either add a cleanup pass to the partitioner that undoes some of its HLO-ization of custom ops or teach IREE's input pipeline to do so. I'm 50-50 on what the right answer is.

**Comment by rsuderman** [comment]
I'll quickly put together a custom_call -> top_k conversion. Fixing this properly should be done once we have a `stablehlo.top_k`, which @kuhar is putting a proposal together for.
