### ISSUE TITLE
[CUDA] Get shared memory limit according to the target

### ISSUE THREAD

**Issue by okkwon** [iree-org/iree#13943]
Currently we have the limit according to sm_80, but the value should be derived from the target.

In `compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp`,

```c++
  // Run checks on shared memory usage.                                                                                                                                                                     
  // TODO: query this from the target.                                                                                                                                                                      
  auto getSharedMemoryLimit = [](func::FuncOp) { return 163 * 1024; };
  pm.addPass(createGPUCheckResourceUsagePass(getSharedMemoryLimit));
```

**Comment by allieculp** [comment]
@okkwon Do we have an owner for this? @qcolombet for visibility

**Comment by okkwon** [comment]
Let's initially assign it to @qcolombet. He will prioritize it.

**Comment by qcolombet** [comment]
We'll need a solution for that for at least Hopper.
If I am not mistaken Hopper has more shared memory than Ampere.

@antiagainst may you help us hook the target information for LLVMGPU?
I don't see where the target limits are described and since you've already done it for SPIRV, I think, that would be helpful to have your guidance here.

**Comment by benvanik** [comment]
The easiest path would be to stick the target information on the IREE::HAL::DeviceTargetAttr configuration dictionary as set by the TargetBackend and query that (`IREE::HAL::DeviceTargetAttr::lookup(anyOp)` to get the info). Could also build more complex stuff/things upstream but that should provide you what you need to hoist out the constant value, anyway.

**Comment by allieculp** [comment]
@antiagainst Raising this again if you have a moment to review / give guidance.

**Comment by antiagainst** [comment]
This is done now--we can query from `#iree_gpu.target`.
