### ISSUE TITLE
CPU ukernel breaks byo LLVM builds

### ISSUE THREAD

**Issue by JackWolfard** [iree-org/iree#13957]
### What happened?

[runtime/src/iree/builtins/ukernel/arch/x86_64/common_x86_64.h](https://github.com/openxla/iree/blob/main/runtime/src/iree/builtins/ukernel/arch/x86_64/common_x86_64.h) relies on `immintrin.h` which is included from Clang via `set(_BUILTIN_HEADERS_PATH "${IREE_BINARY_DIR}/llvm-project/lib/clang/${_CLANG_VERSION_MAJOR}/include/")` in [build_tools/cmake/iree_bitcode_library.cmake](https://github.com/openxla/iree/blob/main/build_tools/cmake/iree_bitcode_library.cmake).

However, when building IREE using [build_tools/scripts/byo_llvm.sh](https://github.com/openxla/iree/blob/main/build_tools/scripts/byo_llvm.sh), the system's LLVM is used instead of being built, so `${IREE_BINARY_DIR}` does not contain `llvm-project`.

Trying to build IREE using the `byo_llvm.sh` breaks due to this issue. To fix, check if `IREE_BUILD_BUNDLED_LLVM=OFF` and look for the installed Clang headers.

### What component(s) does this issue relate to?

Runtime

### Version information

686860c6ba561401f8df1b86f193723470703954

**Comment by JackWolfard** [comment]
I am going to open a PR to fix this

**Comment by benvanik** [comment]
we'll probably want to make the include path a cmake variable that gets overridden by the byo_llvm.sh script - not sure if there's a way to ask clang where it lives but the path usually looks something like `/usr/lib/clang/17/include/`

**Comment by JackWolfard** [comment]
> we'll probably want to make the include path a cmake variable that gets overridden by the byo_llvm.sh script - not sure if there's a way to ask clang where it lives but the path usually looks something like `/usr/lib/clang/17/include/`

Could we use `CLANG_INCLUDE_DIRS` from [llvm/llvm-project/clang/cmake/modules/ClangConfig.cmake.in#L11](https://github.com/llvm/llvm-project/blob/main/clang/cmake/modules/ClangConfig.cmake.in#L11)?

We get this CMake module in [build_tools/cmake/iree_llvm.cmake#L71](https://github.com/openxla/iree/blob/main/build_tools/cmake/iree_llvm.cmake#L71), so the variable should be available when building IREE w/ `IREE_BUILD_BUNDLED_LLVM=OFF`.

**Comment by benvanik** [comment]
good idea! if we used CLANG_INCLUDE_DIRS then we'd want to set it like we do for LLVM/MLIR/LLD_INCLUDE_DIRS above in iree_llvm_configure_bundled to the proper paths

**Comment by powderluv** [comment]
also is byo_llvm.sh in the CI ? If not we probably should add it.

**Comment by JackWolfard** [comment]
Just tried using `CLANG_INCLUDE_DIRS`, but sadly, it doesn't seem to contain `immintrin.h`.

- `CLANG_INCLUDE_DIRS: /.../llvm/include`
- Need to find `/.../llvm/lib/clang/17/include/immintrin.h` instead

~I was able to use `${LLVM_INSTALL_DIR}/llvm/lib/clang/${_CLANG_VERSION_MAJOR}/include/`. `LLVM_INSTALL_DIR` gets set by `byo_llvm.sh`, but this seems kinda brittle. Going to try and see if any of the other variables from the Clang CMake module can help.~

EDIT: Ran into issues where `_CLANG_VERSION_MAJOR` is only defined when Clang is being built by IREE. The best course of action IMO is to override a CMake variable from `byo_llvm.sh` with the right Clang include path.

**Comment by benvanik** [comment]
SGTM - that feels like the most robust way and it'll always be useful to have around even if we find some more clever ways to pick a better default in the future.

**Comment by bjacob** [comment]
The location if `immintrin.h` in the Clang source tree is actually there:
https://github.com/llvm/llvm-project/blob/main/clang/lib/Headers/immintrin.h

**Comment by JackWolfard** [comment]
These headers get installed to `/.../llvm/lib/clang/17/include` for me with `immintrin.h` being in this folder. Above, I was referring to `/.../llvm/include/clang` which does not contain `immintrin.h` but instead the headers from https://github.com/llvm/llvm-project/tree/main/clang/include. `CLANG_INCLUDE_DIRS` only points to the latter and not the former which is necessary to get `immintrin.h`.

**Comment by bjacob** [comment]
just saw this was assigned to me; I'd like to help, but I can't get `byo_llvm.sh` to cmake-configure. The `build_llvm` and `build_mlir` steps work, but `build_iree` fails like this:

```
$ ./build_tools/scripts/byo_llvm.sh build_iree

(...)

CMake Error at build_tools/cmake/iree_llvm.cmake:85 (find_package):
  Found package configuration file:

    /usr/lib/cmake/clang-14/ClangConfig.cmake

  but it set Clang_FOUND to FALSE so package "Clang" is considered to be NOT
  FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: LLVM

Call Stack (most recent call first):
  CMakeLists.txt:778 (iree_llvm_configure_installed)
```

**Comment by bjacob** [comment]
The CMake command line here was passing a `-DCLANG_DIR=` that does contain a ClangConfig.cmake so i suppose the problem here is that  build_tools/cmake/iree_llvm.cmake didn't look there.

**Comment by bjacob** [comment]
I can fix one by one the issues I'm running into, to the point that I do reproduce 'byo-llvm build breaks somewhere in iree_bitcode_library'.

But there's too much local hackery involved in getting there, that I'm not confident that what I had is representative of anyone else.

Moreover, once I do reproduce the failure, it fails in a more basic way than what this Issue describes: in iree_bitcode_library we have code explicitly referring to Clang as a target in a CMake generator-expression, and that's failing because in the BYO-llvm case, by definition, Clang is not a target:
https://github.com/openxla/iree/blob/18a1bac40e049075567b6500a3c81f95eca57052/build_tools/cmake/iree_bitcode_library.cmake#L28

So I wonder how to interprete the fact that this Issue is originally filed as a C include directory issue. @JackWolfard.

**Comment by bjacob** [comment]
Since this is nontrivial to fix, I think we should at least for now unblock this by disabling the bitcode build in the non-bundled-Clang case.

**Comment by benvanik** [comment]
yeah we'd need to sniff to see if IREE_CLANG_TARGET was set - if not then use an IREE_CLANG_BINARY the user/script specifies

**Comment by bjacob** [comment]
> yeah we'd need to sniff to see if IREE_CLANG_TARGET was set - if not then use an IREE_CLANG_BINARY the user/script specifies

OK, https://github.com/openxla/iree/pull/13968 implements that idea.

@JackWolfard does that fix it for you?

Note: to reproduce the build error, I have to manually edit the byo-llvm cmake config (for IREE) to pass:   `cmake -DIREE_TARGET_BACKEND_LLVM_CPU=ON". Otherwise, IREE's ukernel bitcode simply isn't built, and so I couldn't reproduce the error.  I assume that @JackWolfard had this turned on as well.

Also note: it's not just ukernels, it's also libdevice. Really anything that was using `iree_bitcode_library` (these are the two things at the moment).

**Comment by JackWolfard** [comment]
> does that fix it for you?

Yes, that fixed it for me.
