### ISSUE TITLE
e2e test artifacts are large

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#13959]
Repro in a IREE build directory - just importing the models, not even compiling modules yet:

```
benoitjacob@cloud:~/iree-build-linux$ rm -rf e2e_test_artifacts/
benoitjacob@cloud:~/iree-build-linux$ cmake -DIREE_BUILD_E2E_TEST_ARTIFACTS=ON .
benoitjacob@cloud:~/iree-build-linux$ cmake --build . --target iree-benchmark-import-models
benoitjacob@cloud:~/iree-build-linux$ du -h e2e_test_artifacts/
112G    e2e_test_artifacts/
```

Looking at the files:
```
benoitjacob@cloud:~/iree-build-linux$ ls -lS e2e_test_artifacts/
total 117054468
-rw-r--r-- 1 benoitjacob primarygroup 5908164466 Jun  6 14:39 model_587e595d-2adf-4e41-9617-43178a133725-batch-1_T5LargeTFBatch1.mlirbc
-rw-r--r-- 1 benoitjacob primarygroup 5906084033 Jun  6 14:38 model_587e595d-2adf-4e41-9617-43178a133725-batch-24_T5LargeTFBatch24.mlirbc
-rw-r--r-- 1 benoitjacob primarygroup 5906084033 Jun  6 14:38 model_587e595d-2adf-4e41-9617-43178a133725-batch-32_T5LargeTFBatch32.mlirbc
-rw-r--r-- 1 benoitjacob primarygroup 5906084033 Jun  6 14:38 model_587e595d-2adf-4e41-9617-43178a133725-batch-48_T5LargeTFBatch48.mlirbc
-rw-r--r-- 1 benoitjacob primarygroup 5906084033 Jun  6 14:38 model_587e595d-2adf-4e41-9617-43178a133725-batch-64_T5LargeTFBatch64.mlirbc
-rw-r--r-- 1 benoitjacob primarygroup 5906082640 Jun  6 14:38 model_587e595d-2adf-4e41-9617-43178a133725-batch-16_T5LargeTFBatch16.mlirbc

... (more of the same for other models, though that one is the largest) ...
```

Could these batch-X variants of the same model share what they have in common?

Is this set of batch values the right trade-off of benchmark coverage vs heaviness?

**Comment by benvanik** [comment]
yeah wow, that's a lot of redundant GB!
feels like a pass that fixated inputs/shapes/etc may be able to help keep this kind of combinatorial explosion in check - one mlirbc with dynamic shapes and input #3 as `tensor<?x1024xf32>` gets stamped out with `--iree-abi-fixate-input-shape=3:1x1024` (or whatever) - then shape propagation should hopefully get it all back to static

in the short term it feels like there should probably be an iree-benchmark-import-models-extra/large/whatever - downloading 36GB for a single model type makes the current target extremely unfriendly for people to use.

/cc @mariecwhite

**Comment by pzread** [comment]
Yeah, we have done this for benchmark compilation (having `iree-benchmark-suites` and `iree-benchmark-suites-large`). Sent out #13963 to also do the separation for `iree-benchmark-import-models`.

> feels like a pass that fixated inputs/shapes/etc may be able to help keep this kind of combinatorial explosion in check - one mlirbc with dynamic shapes and input https://github.com/openxla/iree/pull/3 as tensor<?x1024xf32> gets stamped out with --iree-abi-fixate-input-shape=3:1x1024 (or whatever) - then shape propagation should hopefully get it all back to static

This sounds a good idea! Although we will still compile VMFB for each batch size. It seems to be also useful in the real world when user only has the dynamic-shape model and want to compile it into VMFB with fixed batch sizes, before IREE has a proper support on dynamic-shape models.
