### ISSUE TITLE
Add byo_llvm to the CI

### ISSUE THREAD

**Issue by powderluv** [iree-org/iree#13989]
Multiple vendors downstream use the byo_llvm.sh flow.  We need to add a CI for it so we can catch issues like https://github.com/openxla/iree/issues/13957

**Comment by allieculp** [comment]
@benvanik @bjacob I believe this is adjacent to what you were working on in #13957 
Who is the best owner for this?

**Comment by bjacob** [comment]
i'm OK to do it if others say it's useful. @MaheshRavishankar @GMNGeoffrey .  Most of the work though will be deciding what on we want that CI to do.

**Comment by MaheshRavishankar** [comment]
Should be fine  adding it to CI... but the priority/resources needs to be set by someone, I cant gauge it (sorry for the non-answer, but just responding to ping). Ideally someone other than Benoit can do it.

**Comment by allieculp** [comment]
@powderluv Might need to set this as a P2 for now - let us know if this is more urgent.

**Comment by bjacob** [comment]
Though as long as we don't have this on CI, we will break it, specifically I will break it, and then I will again spend time fixing it.

**Comment by powderluv** [comment]
Yeah we have downstream customers who rely on this. Maybe worth spending the time to spin up the CI to save @bjacob time chasing the breakages later.  (but priority is up to @bjacob and others - we can complain when it breaks next)

**Comment by bjacob** [comment]
Alas, @stellaraccident , what have you unleashed?

**Comment by GMNGeoffrey** [comment]
This was added in https://github.com/openxla/iree/pull/12274 "so that we can run in CI", but then never actually added to CI. It was also created, reviewed and merged over the weekend :-/ So yeah this seems like something we want to support, but when adding stuff like this we need to make sure that it actually lands and is tested. We should not be creating things that we advertise for general usage until *after* there's CI for it.

**Comment by powderluv** [comment]
> It was also created, reviewed and merged over the weekend

Please don't discourage this. We want to the option to move fast when we want (in this case a customer was going to give up on tracking IREE). Creating / reviewing and merging in a day can be a good thing in some cases :D 

We can be considered non-general usage for now and we are happy to live without a CI for it (without this patch life would be worse downstream where they can't integrate IREE cleanly). It would just be nice to add the CI at some point as it keeps us clean from all the ukernel / vendor libs that are getting added. 

We (or the vendor themselves) could add this CI if you give the directions on what machines they should run on etc.

**Comment by GMNGeoffrey** [comment]
My point about the over the weekend thing is not that people shouldn't feel free to do things over the weekend, but rather that if something requires that someone else see it, you shouldn't expect that they will be around over the weekend (or really any specific short span of time).

I think we probably *should* support this use case, but it's hard to plan for doing that when I didn't even know that this existed.

**Comment by bjacob** [comment]
i'm doing it; shouldn't be a lot of work. Most of it is just getting a green CTest run locally, so not a CI problem, just a matter of finishing up the byo-llvm setup. I just reached that point locally so i'm confident it won't be much more work from here.

**Comment by bjacob** [comment]
Note: I agree with all what Geoffrey says here and I hope we'll learn from this. I just happen to have pattern-matched as something that seems easy and useful to just implement.

**Comment by bjacob** [comment]
https://github.com/openxla/iree/pull/14035 is up for review.
