### ISSUE TITLE
CI job for ASAN vmfbs

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#13995]
Why aren't we doing this asan testing on the CI? This particular test is constructing manual shell commands via lit (that's a separate complaint), but in general I don't see any usage of that flag for asan in the codebase. Seems like we should turn it on for all our check/trace/matmul tests? Maybe it's a different CMake switch than building the IREE code with asan. @bjacob because I remember we discussed the flags around this at some point

_Originally posted by @GMNGeoffrey in https://github.com/openxla/iree/issues/13967#issuecomment-1581676591_

**Comment by benvanik** [comment]
> Having an ASAN bot with it running would be a nice addition but since it's a completely different lowering and runtime pipeline we still need the one we have testing the production path. It also breaks cross-compilation as the vmfbs become target specific which makes things a lot more complicated (have to build and ship the vmfbs on a bot that has all platform toolchains and build one vmfb per platform, which isn't really possible with mac/etc).


_Originally posted by @benvanik in https://github.com/openxla/iree/issues/13967#issuecomment-1581683015_

**Comment by GMNGeoffrey** [comment]
Lol I was just in the process of sticking your reply in here too :grin:

**Comment by GMNGeoffrey** [comment]
So my understanding is that we need to rebuild the runtime with asan for this, but we don't need to build the compiler at all, right? The normal compiler should be capable of compiling asan VMFBs. They VMFBs are target-specific, but the compiler is not. So we pull the prebuilt compiler from the `build_all` job and use it as an external tool to build the test deps and the runtime, then run the tests there

**Comment by benvanik** [comment]
The compiler is fine but when link-embedded=false the system toolchain is used for producing the final executable code so you get .so/.dll/.dyld files and that requires a full toolchain as system libraries are linked in. x64-only may be viable but it won't catch arm/riscv/etc issues.

**Comment by GMNGeoffrey** [comment]
I'm ok starting with that :-)
