### ISSUE TITLE
Issues with moto edge and pixel 6 lab phones

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#13996]
We're seeing CI failures on the Moto and Pixel 6 phones

Failures on both moto edge jobs:
- https://github.com/openxla/iree/actions/runs/5195027264
- https://github.com/openxla/iree/actions/runs/5198625482
- https://github.com/openxla/iree/actions/runs/5202963145
- https://github.com/openxla/iree/actions/runs/5203119491
- https://github.com/openxla/iree/actions/runs/5203468383
- https://github.com/openxla/iree/actions/runs/5205065001

This one the test on pixel 6 pro failed in addition to the benchmark on moto edge. The test on moto edge didn't run: https://github.com/openxla/iree/actions/runs/5205719609

Related, it looks like a failure on any of the phones cancels all the other jobs. I'm not sure whether we want that behavior.

The consistent error message is:

> adb: error: failed to get feature set: no devices/emulators found

**Comment by pzread** [comment]
We will need to physically unlock those devices. Pending until the lab manager can access the devices.

**Comment by pzread** [comment]
Fixed.
