### ISSUE TITLE
Track the performance of `tensor.pad` with the dispatch profiler

### ISSUE THREAD

**Issue by qcolombet** [iree-org/iree#14021]
### Request description

@nicolasvasilache landed some improvements to `tensor.pad` in https://github.com/openxla/iree/pull/14000.
It would be great to have this operation tracked in our CI so that we know if it ever regresses.

See this commit https://github.com/openxla/iree/pull/14000#issuecomment-1584255612 for the perf measured at the time of the merge.

@manishucsd Could you add that to the thing we track in the dispatch profiler?

**Comment by ScottTodd** [comment]
The experimental dispatch profiler code was deleted. This sort of testing should live out of tree somewhere if still needed.
