### ISSUE TITLE
Pass `--incompatible_no_implicit_file_export` to `bazel build`

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#14020]
Context: https://github.com/openxla/iree/pull/13982

Once that PR is merged and the upstream https://reviews.llvm.org/D152491 is also merged, we can do that.

In order to prevent this from regressing upstream and ending up adding friction to LLVM integrates, ideally upstream would enable that too.

**Comment by allieculp** [comment]
@bjacob Is anyone assigned to this already?

**Comment by bjacob** [comment]
let me self-assign.

**Comment by bjacob** [comment]
The upstream LLVM commit we need to get integrated before doing this is: https://github.com/llvm/llvm-project/commit/1c532b5e44fa1fbff84c494c659fe722b7df4b10

**Comment by ScottTodd** [comment]
We could flip this.... or just leave the Bazel build unmaintained. Doesn't seem very pressing.
