### ISSUE TITLE
[CUDA driver] query the compute capability from the device

### ISSUE THREAD

**Issue by okkwon** [iree-org/iree#14031]
### Request description

The PJRT plugin needs to know the device's compute capability to set the target option correctly for the compiler. See https://github.com/openxla/openxla-pjrt-plugin/issues/151.

This can be implemented using `cuDeviceGetAttribute` with `CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR` and `CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR`.

See here for more information.

https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__DEVICE.html#group__CUDA__DEVICE_1g9c3e1414f0ad901d3278a4d6645fc266

**Comment by benvanik** [comment]
The only thing the HAL would support is iree_hal_cuda_device_query_i64 returning those values for `cuda.device` :: `compute_capability_major` / `compute_capability_minor` - PJRT could then use the iree_hal_device_query_i64 API to get this info.
