### ISSUE TITLE
`flow.dispatch.workgroup_count_from_slice` surviving due to 0-element tensors.

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#14077]
In some cases there is an `arith.constant` operator with an `index`. This constant fails to lower to the correct vm operation.

Source IR:
https://gist.github.com/rsuderman/bc2b81addc511d0925c94030c73d37ba

Last Pass:
`mlir::iree_compiler::IREE::VM::ConversionPass (iree-vm-conversion)`

IR Immediately before failure:
https://gist.github.com/rsuderman/24d5c02cbfb2ca1fb4c98ebae0057aed

**Comment by benvanik** [comment]
(thanks for filing - can you post the exact errors when you do too please? sometimes I can tell what something is just from that)

**Comment by rsuderman** [comment]
It looks like `index` was never convert to an `i64`. Here is the error.

```
STDERR:
-------
/usr/local/google/home/suderman/Repos/jax/tests/lax_test.py:1918:4: error: 'vm.trunc.i64.i32' op operand #0 must be 64-bit signless integer, but got 'index'
    self._CompileAndCheck(fun, args_maker)
   ^
/usr/local/google/home/suderman/Repos/jax/tests/lax_test.py:1918:4: note: called from
    self._CompileAndCheck(fun, args_maker)
   ^
/usr/local/google/home/suderman/Repos/jax/tests/lax_test.py:1918:4: note: see current operation: %98 = "vm.trunc.i64.i32"(%96#0) : (index) -> i32
    self._CompileAndCheck(fun, args_maker)
   ^
```

**Comment by benvanik** [comment]
weeeeird! I'll get it fixed, thanks!

**Comment by benvanik** [comment]
oh, something has gone off the rails earlier - there's `flow.dispatch.workgroup_count_from_slice` ops still remaining in the IR!
```mlir
    %x, %y, %z = flow.dispatch.workgroup_count_from_slice
    hal.command_buffer.dispatch<%cmd : !hal.command_buffer> target(%_executable_jit__cumulative_reduction_linked_llvm_cpu : !hal.executable)[5] workgroups([%x, %y, %z])
```
Those should have been replaced earlier so it may be something in TileAndDistributeToWorkgroupsPass missing a case in `lowerWorkgroupCount`. I'll see if I can narrow down the dispatch.

/cc @MaheshRavishankar

**Comment by rsuderman** [comment]
I should also note that this is with `--iree-input-demote-i64-to-i32=false`

**Comment by benvanik** [comment]
Here's the dispatch, which, uh, is weird.
It's slicing out nothing (3x0) and then storing that so the whole thing goes away. We probably should have elided this earlier. I'm guessing TileAndDistributeToWorkgroupsPass is not handling a case where the entire dispatch is empty.

```mlir
  flow.executable private @main_dispatch_5 {
    flow.executable.export public @main_dispatch_5 workgroups() -> (index, index, index) {
      %x, %y, %z = flow.dispatch.workgroup_count_from_slice 
      flow.return %x, %y, %z : index, index, index
    }
    builtin.module {
      func.func @main_dispatch_5(%arg0: !flow.dispatch.tensor<readonly:tensor<3x0xi32>>, %arg1: !flow.dispatch.tensor<readwrite:tensor<3x1xi32>>) {
        %0 = flow.dispatch.tensor.load %arg0, offsets = [0, 0], sizes = [3, 0], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<3x0xi32>> -> tensor<3x0xi32>
        flow.dispatch.tensor.store %0, %arg1, offsets = [0, 1], sizes = [3, 0], strides = [1, 1] : tensor<3x0xi32> -> !flow.dispatch.tensor<readwrite:tensor<3x1xi32>>
        return
      }
    }
  }
```
which later becomes
```mlir
  func.func @main_dispatch_5() {
    return
  }
```

Here's the original linalg:
```mlir
    %extracted_slice_3 = tensor.extract_slice %3[0, 0] [3, 0] [1, 1] : tensor<3x1xi32> to tensor<3x0xi32>
    %extracted_slice_4 = tensor.extract_slice %1[0, 2] [3, 0] [1, 2] : tensor<3x2xi32> to tensor<3x0xi32>
    %4 = tensor.empty() : tensor<3x0xi32>
    %5 = linalg.generic {indexing_maps = [#map, #map, #map], iterator_types = ["parallel", "parallel"]} ins(%extracted_slice_3, %extracted_slice_4 : tensor<3x0xi32>, tensor<3x0xi32>) outs(%4 : tensor<3x0xi32>) {
    ^bb0(%in: i32, %in_15: i32, %out: i32):
      %21 = arith.addi %in, %in_15 : i32
      linalg.yield %21 : i32
    } -> tensor<3x0xi32>
    %extracted_slice_5 = tensor.extract_slice %1[0, 0] [3, 1] [1, 1] : tensor<3x2xi32> to tensor<3x1xi32>
    %inserted_slice = tensor.insert_slice %5 into %extracted_slice_5[0, 1] [3, 0] [1, 1] : tensor<3x0xi32> into tensor<3x1xi32>
```

and the original HLO:
```mlir
  %7 = "stablehlo.slice"(%6) {limit_indices = dense<[3, 0]> : tensor<2xi64>, start_indices = dense<0> : tensor<2xi64>, strides = dense<1> : tensor<2xi64>} : (tensor<3x1xi32>) -> tensor<3x0xi32>
  %8 = "stablehlo.slice"(%3) {limit_indices = dense<[3, 2]> : tensor<2xi64>, start_indices = dense<[0, 2]> : tensor<2xi64>, strides = dense<[1, 2]> : tensor<2xi64>} : (tensor<3x2xi32>) -> tensor<3x0xi32>
  %9 = stablehlo.add %7, %8 : tensor<3x0xi32>
  %10 = "stablehlo.slice"(%3) {limit_indices = dense<[3, 1]> : tensor<2xi64>, start_indices = dense<0> : tensor<2xi64>, strides = dense<1> : tensor<2xi64>} : (tensor<3x2xi32>) -> tensor<3x1xi32>
  %11 = stablehlo.concatenate %10, %9, dim = 1 : (tensor<3x1xi32>, tensor<3x0xi32>) -> tensor<3x1xi32>
```

I swore we had a "this tensor is statically known to have a 0 dim so replace the whole thing with a tensor.empty pass" - maybe that broke - I'll see if I can find it.

**Comment by MaheshRavishankar** [comment]
Will take a look later today

**Comment by benvanik** [comment]
Ah we have this on flow ops but not on linalg - would be nice if linalg could do the same thing but if not I can make dispatch regions handle it better by dropping outputs via ReplaceOpIfTensorOperandZeroElements/ReplaceOpIfTensorResultZeroElements on flow.dispatch.workgroups or something.

**Comment by MaheshRavishankar** [comment]
Actually that load/store is just illegal. We should head this out way before even flow kicks in.

**Comment by benvanik** [comment]
Feels like a good defense-in-depth thing to have at both stablehlo and linalg - would be much easier to spot when parts of the models disappear at the hlo level but may not always be possible to elide things until linalg once the hlo ops are decomposed so probably worth starting there. I tried to look at also adding checks to dispatch regions but it's trickier to do once formed (in-place updates of 0 length tensors, consumed 0 length tensors that get elided will still leave empty dispatch regions unless we start analyzing the black boxes, etc). Still would love to have more safety though so let me know if you think of anything that would be worth having!

**Comment by benvanik** [comment]
@rsuderman thoughts on adding stablehlo canonicalization patterns for 0-element stuff? (if any dim of a tensor - even dynamically shaped - is known static 0 and the op has no side-effects then replace the op producing it with tensor.empty or the stablehlo equivalent)
would that be something stablehlo would want upstream or something we'd have in our input pipeline?

**Comment by MaheshRavishankar** [comment]
I forget if we do this in our input pipeline somewheres

**Comment by MaheshRavishankar** [comment]
Ok, I dont find anything. I can add a pass for handling 0-dim tensors early on in Flow and head it out there.... Will probably not get to it till later in the week (I have something else of higher priority to pick up before).

**Comment by rsuderman** [comment]
> @rsuderman thoughts on adding stablehlo canonicalization patterns for 0-element stuff? (if any dim of a tensor - even dynamically shaped - is known static 0 and the op has no side-effects then replace the op producing it with tensor.empty or the stablehlo equivalent) would that be something stablehlo would want upstream or something we'd have in our input pipeline?

Adding a canonicalizer makes sense to me. The migration to `stablehlo` likely introduced a bunch of failures previously handle via the `mhlo` route.

**Comment by MaheshRavishankar** [comment]
> > @rsuderman thoughts on adding stablehlo canonicalization patterns for 0-element stuff? (if any dim of a tensor - even dynamically shaped - is known static 0 and the op has no side-effects then replace the op producing it with tensor.empty or the stablehlo equivalent) would that be something stablehlo would want upstream or something we'd have in our input pipeline?
> 
> Adding a canonicalizer makes sense to me. The migration to `stablehlo` likely introduced a bunch of failures previously handle via the `mhlo` route.

Yeah let me know. I might do this just as a pass in Flow to head off this issue across backends.
