### ISSUE TITLE
Nightly Release builds still build with CUDA 11.6 while CI is 12.1

### ISSUE THREAD

**Issue by powderluv** [iree-org/iree#14080]
### What happened?

We need to update the nightly release builds to pull the latest cuda SDK. Right now it still pulls 11.6 

https://github.com/openxla/iree/actions/runs/5242183105/jobs/9465268441

**Comment by powderluv** [comment]
@GMNGeoffrey fyi

**Comment by antiagainst** [comment]
Okay we have two copies of `fetch_cuda_deps.sh`: one [here](https://github.com/openxla/iree/blob/main/build_tools/docker/context/fetch_cuda_deps.sh) and one [here](https://github.com/openxla/iree/blob/main/third_party/nvidia_sdk_download/fetch_cuda_toolkit.py). That's quite confusing. @GMNGeoffrey is there a particular reason that we cannot unify them?

**Comment by GMNGeoffrey** [comment]
Not that I'm aware of. The release stuff was mostly built entirely separately from all the rest of our docker stuff, so has many inconsistencies like this

**Comment by antiagainst** [comment]
> Not that I'm aware of. The release stuff was mostly built entirely separately from all the rest of our docker stuff, so has many inconsistencies like this

Ah, okay. If many such cases, I won't bother for now.

**Comment by GMNGeoffrey** [comment]
Well I think each step to unify is useful :-) Does this mean the releases are relying on fetching cuda dynamically at build time. That's not awesome. We should make the docker containers use the same script as the build. We have things set up such that that's possible. I'm also confused though: It looks like we don't actually use that fetch script anywhere: https://github.com/search?q=fetch_cuda_toolkit+repo%3Aopenxla%2Firee&type=code and the only mention of parse_redist fetches it from upstream: https://github.com/search?q=parse_redist+repo%3Aopenxla%2Firee&type=code

**Comment by GMNGeoffrey** [comment]
No it's used here: https://github.com/openxla/iree/blob/d1a65a7cc08bac4a2a2159402f09e8ea34b9fc83/build_tools/third_party/cuda/CMakeLists.txt#L8

I goes GitHub codesearch isn't working. Maybe it doesn't index directories named "third_party/"
