### ISSUE TITLE
Illegal 'arith.index_cast' generated during EncodeHostTensors

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#14090]
`index` conversion to `i64` generates an illegal `index_cast` operation.

Source StableHLO:
https://gist.github.com/rsuderman/c467328678683e7c7e103b2567164fcb

IR Before EncodeHostTensors:
https://gist.github.com/rsuderman/4faa5b9b98c9307b17622d60b05b906b

Last known error:
```
/usr/local/google/home/suderman/Repos/jax/tests/scipy_signal_test.py:97:4: error: 'arith.index_cast' op operand type 'i32' and result type 'i64' are cast incompatible
    self._CheckAgainstNumpy(osp_fun, jsp_fun, args_maker, check_dtypes=False, tol=tol)
   ^
/usr/local/google/home/suderman/Repos/jax/tests/scipy_signal_test.py:97:4: note: see current operation: %16 = "arith.index_cast"(%13) : (i32) -> i64
```

**Comment by benvanik** [comment]
Reproed, I think this is splat complex handling. Will fix.

**Comment by benvanik** [comment]
ah yes legit issue here that only happens with non-constant complex splat patterns - will get some new tests in and a fix pushed after lunch
