### ISSUE TITLE
Build a proper HoistShapeCalculationsPass

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#1410]
The current pass to hoist shape calculations is not general for arbitrary control flow and provides few invariants but is sufficient to generate correct programs for some simple cases we are working on now. Eventually, it will need to be built properly (or solved in another way).

**Comment by benvanik** [comment]
Obsolete?

**Comment by stellaraccident** [comment]
No - still a real generalization gap.

**Comment by benvanik** [comment]
This shape stuff is all gone now (or at least pushed to frontends).
