### ISSUE TITLE
Support Unaligned Matmul Shapes for CUDA Codegen

### ISSUE THREAD

**Issue by manishucsd** [iree-org/iree#14116]
### Request description

The goal is to support unaligned matmul shapes with CUDA codegen. Please find input IR that we can begin with. 

## Input Linalg MLIR
```mlir
#tile_config_128x128_64x4_tensorcore_mmasync = #iree_codegen.compilation_info<
  lowering_config = <tile_sizes = [[128, 128, 64]]>,
  translation_info = <LLVMGPUMatmulTensorCoreMmaSync pipeline_depth = 4>,
  workgroup_size = [64 : index, 2 : index, 1 : index]
>

// Dispatch linalg.matmul row-row layout 
func.func @matmul_3448x1016x2040_f16t_f16t_f16t_tile_config_128x128_64x4_tensorcore_mmasync(
  %lhs: tensor<3448x2040xf16>,
  %rhs: tensor<2040x1016xf16>) -> tensor<3448x1016xf16>
{
  %c0 = arith.constant 0.0 : f16
  %init = tensor.empty() : tensor<3448x1016xf16>
  %inital_result = linalg.fill ins(%c0 : f16) outs(%init : tensor<3448x1016xf16>) -> tensor<3448x1016xf16>
  %result = linalg.matmul {compilation_info = #tile_config_128x128_64x4_tensorcore_mmasync} 
                     ins(%lhs, %rhs: tensor<3448x2040xf16>, tensor<2040x1016xf16>)
                     outs(%inital_result: tensor<3448x1016xf16>) -> tensor<3448x1016xf16>
  return %result : tensor<3448x1016xf16>
}
```

## Final Pseudo PTX 
```
// Number of Shared Memory Stages = 4; [S0, S1, S2, S3]
// Consider the following shapes 
//  ThreadblockShape = 128x128_64x4    [Tile-MxTileN_Tile-KxNumStages]
//  WarpShape        = 64x64x64
//  InstructionShape = 16x8x16         [mma.sync.m16n8k16]


// Prologue (Issues 3 stages worth of async_copy)
cp.async.cg S0, @mask; // cp.async zfill
commit_group;

cp.async.cg S1, @mask; // cp.async zfill
commit_group;

cp.async.cg S2, @mask; // cp.async zfill
commit_group;

device_async_wait 2;   // Wait for at least stage to be committed
bar.sync 0;

// Initialize accumulators
accum = 0;

// Mainloop 
for (i = 0; i < iteration; i++) {

    // Load stage 0, kgroup 1 into registers
    ldmatrix reg_a, smem_stage[i];                     
    ldmatrix reg_b, smem_stage[i];                         

    // Accumulate stage 0, consuming reg_a and reg_b
    mma.sync accum, reg_a, reg_b, accum; // in-place accumulation using Tensor Core instruction mma.sync             
    
    // Async copy for next stage
    pred = compute_or_load_predicates();
    @pred cp.async.cg smem_stage[i + 3], src_elements; 
    commit_group;
    device_async_wait 2;
    bar.sync 0;
}

// Epilogue 
st.shared smem_epilogue, accum; // smem_epilogue <- accum
bar.sync 0;
ld.shared reg<8xf16>, smem_epilogue;  // reg<8xf16> <- smem_epilogue

// compute coordinates that the thread is responsible for 
// storing say (coord_m, coord_n)
pred = (coord_m < problem_M) && (coord_n < problem_N)
@pred st.global gmem_output, reg<8xf16>; // gmem_output <- reg<8xf16>
```

**Comment by manishucsd** [comment]
@nicolasvasilache , Can you please fill here what support already exists for unaligned matmul without global memory padding? 

cc: @dcaballe , @nicolasvasilache , @MaheshRavishankar , @jpienaar,  @qcolombet

**Comment by nicolasvasilache** [comment]
The transformations and strategy are implemented and have been announced [here](https://github.com/openxla/iree/discussions/13227).

There is still active ongoing work for generalization in various directions (generalized contraction, data types, putting in a simple heuristic).

You can look at this iree-samples [PR](https://github.com/iree-org/iree-samples/commit/05ee2175f1bea82e7d853f66217667f5497467ef) and try other configurations [here](https://github.com/iree-org/iree-samples/commit/05ee2175f1bea82e7d853f66217667f5497467ef#diff-4fd7fedfee8250508bcce311bf3057e4dfad9567fc0133f3567db9a8032ce135R20).

I don't have cycles to incorporate this in the dispatch profiler so I did something that accelerated my own work.
I will happily reuse the dispatch profiler if support is added.

On the ongoing work side, this [PR](https://github.com/openxla/iree/pull/14083) improves and generalizes the copy schedule
but it does trigger a bug when using `copy` + `zfill` of sizes `8B` and `16B` (works properly with `4B`) that I have not been able to nail down yet. I suspect it could be that we hit unaligned cases for which we have no safety in cp.async generation. 

In contrast, regular masked load/stores of vector do not hit this issue.

Any help in diagnosing this issue would speed up the remaining generalizations, which include degrading to fma on small sizes < 8 and allow getting close to peak memory BW in such cases (we have a few important such cases).

**Comment by nicolasvasilache** [comment]
I have put a minimal repro of the cp.async + zfill issue here: https://github.com/openxla/iree/pull/14138

The code compile and runs properly without the async part but breaks with turning async on.
I have not yet been able to debug this and would love a second set of eyes.

**Comment by qcolombet** [comment]
We already had a sprint for unaligned matmul, see https://github.com/openxla/iree/issues/13242 and https://github.com/openxla/iree/issues/13104.
I've fine re-opening this, but I don't think this is on the critical path.
