### ISSUE TITLE
`stablehlo.rng_bit_generator` should work for `i8`

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#14131]
Turns out some tests use `stablehlo.rng_bit_generator` for `ui8` types. Should be a similar support for `i16` with a `trunci` at the end. This should land the IREE's StableHLO lowerings.

```
func.func @main(%arg0 : tensor<2xui64>) -> -> (tensor<2xui64>, tensor<10000xui8>) {
    %output_state, %output = stablehlo.rng_bit_generator %arg0, algorithm =  DEFAULT : (tensor<2xui64>) -> (tensor<2xui64>, tensor<10000xui8>)
   return %output_state, %output : tensor<2xui64>, tensor<10000xui8>
}
```

**Comment by cc10512** [comment]
@jvstokes is there any reason that this issue is still open? [#14483](https://github.com/openxla/iree/pull/14483) states this should be fixed.

**Comment by jvstokes** [comment]
No, I'll go ahead and close it.
