### ISSUE TITLE
Enable e2e sub-byte quantized matmul on LLVM CPU

### ISSUE THREAD

**Issue by yzhang93** [iree-org/iree#14139]
### Request description

This issue is part of https://github.com/openxla/iree/issues/13567. As now we have a [MemRef type converter](https://github.com/openxla/iree/issues/13567) to convert memref of narrow bitwidth (e.g., i4) into wider bitwidth (e.g., i8), and currently it supports memref.load conversion, we need to verify it running e2e through IREE. 

The example IR for weights dequantization is shown below 
```
#map = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
#map1 = affine_map<(d0, d1, d2) -> (d0, d1, 0)>

module {
  func.func @dequant(%arg0: tensor<4096x4096xi4>) -> tensor<4096x32x128xf32> {
    %cst = arith.constant dense_resource<__elided__> : tensor<4096x32x1xf32>
    %cst_0 = arith.constant dense_resource<__elided__> : tensor<4096x32x1xf32>
    %expanded = tensor.expand_shape %arg0 [[0], [1, 2]] : tensor<4096x4096xi4> into tensor<4096x32x128xi4>
    %0 = tensor.empty() : tensor<4096x32x128xf32>
    %1 = linalg.generic {indexing_maps = [#map, #map1, #map1, #map], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded, %cst_0, %cst : tensor<4096x32x128xi4>, tensor<4096x32x1xf32>, tensor<4096x32x1xf32>) outs(%0 : tensor<4096x32x128xf32>) {
    ^bb0(%in: i4, %in_61: f32, %in_62: f32, %out: f32):
      %94 = arith.extui %in : i4 to i32
      %95 = arith.uitofp %94 : i32 to f32
      %96 = arith.subf %95, %in_62 : f32
      %97 = arith.mulf %96, %in_61 : f32
      linalg.yield %97 : f32
    } -> tensor<4096x32x128xf32>
    return %1 : tensor<4096x32x128xf32>
  }
} 
```

The dumped IR after all current LLVMCPU passes is here: https://storage.googleapis.com/shark-public/vivian/vicuna_i4/dump_i4_dequant.mlir

From the dumped IR, it exposes two unsupported features:
1. There's no direct use of `memref.load` on i4 types, but it uses `memref.assume_alignment` and `memref.subview` ops. I tried to add the type conversions for these ops to get rid of the error `failed to legalize operation 'memref.assume_alignment' that was explicitly marked illegal`, but I'm not sure if some bit manipulations are still needed similar to what we did for `memref.load` op.

2. After adding the type conversions for the above two memref ops, it has a new error `failed to legalize operation 'vector.load' that was explicitly marked illegal` ([full error message](https://storage.googleapis.com/shark-public/vivian/vicuna_i4/error_dequant_1.txt)).  We probably need to add some support for vector ops as well.

**Comment by MaheshRavishankar** [comment]
> 1. There's no direct use of `memref.load` on i4 types, but it uses `memref.assume_alignment` and `memref.subview` ops. I tried to add the type conversions for these ops to get rid of the error `failed to legalize operation 'memref.assume_alignment' that was explicitly marked illegal`, but I'm not sure if some bit manipulations are still needed similar to what we did for `memref.load` op.

Looks like you were able to get past it. The `memref.assume_alignment` should be simple, `memref.subview` not so much. Maybe we should try to fold the `memref.subview` with its uses (we do that on other backends) to avoid them

> 2. After adding the type conversions for the above two memref ops, it has a new error `failed to legalize operation 'vector.load' that was explicitly marked illegal` ([full error message](https://storage.googleapis.com/shark-public/vivian/vicuna_i4/error_dequant_1.txt)).  We probably need to add some support for vector ops as well.

So this is already vectorized. So you need to support `vector.load` similar to `memref.load` (its sad that there are two). You should be able to reuse most of the implementation from `memref.load` with `vector.load`. Maybe to land the change upstream we start with something that doestn vectorize?

**Comment by yzhang93** [comment]
Thanks @MaheshRavishankar for taking a look at the issues. I still need to know some details for the above suggestions.

1. Could you point me to some examples that fold the memref.subview op?
2. Could you let me know where I should disable the vectorization and then check the results?

**Comment by yzhang93** [comment]
After doing some research myself, I found `fold-memref-alias-ops` may do what you suggested. I tried to disable vectorization and plug in this pass, and the `memref.subview` ops now turn to a single `memref.load %0[%19, %20] : memref<131072x128xi4>`. The new printed IR and the errors after all passes can be found [here](https://storage.googleapis.com/shark-public/vivian/vicuna_i4/error_dequant_2.txt).

Now the new issue is `error: failed to legalize unresolved materialization from 'memref<131072x128xi4>' to 'memref<131072x128xi8>' that remained live after conversion`. I made a simple test to reproduce this error

```
func.func @test_0() {
  %c0 = arith.constant 0 : index
  %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<131072x128xi4>
  memref.assume_alignment %0, 64 : memref<131072x128xi4>
  return
}
```

And the error is shown as

```  
test.mlir:4:3: error: failed to legalize unresolved materialization from 'memref<131072x128xi4>' to 'memref<131072x128xi8>' that remained live after conversion
  memref.assume_alignment %0, 64 : memref<131072x128xi4>
  ^
test.mlir:4:3: note: see current operation: %2 = "builtin.unrealized_conversion_cast"(%1) : (memref<131072x128xi4>) -> memref<131072x128xi8>
test.mlir:4:3: note: see existing live user here: memref.assume_alignment %1, 64 : memref<131072x128xi8>

```

I think the error happens because it creates `builtin.unrealized_conversion_cast` before the `memref.assume_alignment` op. To prove this, if I change the test IR as below, the `iree-emulate-narrow-type` pass works without error.

```
func.func @test_1(%0: memref<131072x128xi4>, %arg0: index, %arg1: index) {
  memref.assume_alignment %0, 64 : memref<131072x128xi4>
  %1 = memref.load %0[%arg0,%arg1] : memref<131072x128xi4>
  %2 = arith.extui %1 : i4 to i32
  return
}
```

@MaheshRavishankar So my question is how to avoid the error with the original IR just like what is shown in `func.func @test_0()`?

**Comment by MaheshRavishankar** [comment]
> After doing some research myself, I found `fold-memref-alias-ops` may do what you suggested. I tried to disable vectorization and plug in this pass, and the `memref.subview` ops now turn to a single `memref.load %0[%19, %20] : memref<131072x128xi4>`. The new printed IR and the errors after all passes can be found [here](https://storage.googleapis.com/shark-public/vivian/vicuna_i4/error_dequant_2.txt).

Awesome! That was the pass I was talking about. Maybe only comment here is that you should probably run the pass before conversion from SCF -> CF. 

> 
> Now the new issue is `error: failed to legalize unresolved materialization from 'memref<131072x128xi4>' to 'memref<131072x128xi8>' that remained live after conversion`. I made a simple test to reproduce this error
> 
> ```
> func.func @test_0() {
>   %c0 = arith.constant 0 : index
>   %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<131072x128xi4>
>   memref.assume_alignment %0, 64 : memref<131072x128xi4>
>   return
> }
> ```
> 
> And the error is shown as
> 
> ```
> test.mlir:4:3: error: failed to legalize unresolved materialization from 'memref<131072x128xi4>' to 'memref<131072x128xi8>' that remained live after conversion
>   memref.assume_alignment %0, 64 : memref<131072x128xi4>
>   ^
> test.mlir:4:3: note: see current operation: %2 = "builtin.unrealized_conversion_cast"(%1) : (memref<131072x128xi4>) -> memref<131072x128xi8>
> test.mlir:4:3: note: see existing live user here: memref.assume_alignment %1, 64 : memref<131072x128xi8>
> ```
> 
> I think the error happens because it creates `builtin.unrealized_conversion_cast` before the `memref.assume_alignment` op. To prove this, if I change the test IR as below, the `iree-emulate-narrow-type` pass works without error.
> 
> ```
> func.func @test_1(%0: memref<131072x128xi4>, %arg0: index, %arg1: index) {
>   memref.assume_alignment %0, 64 : memref<131072x128xi4>
>   %1 = memref.load %0[%arg0,%arg1] : memref<131072x128xi4>
>   %2 = arith.extui %1 : i4 to i32
>   return
> }
> ```
> 
> @MaheshRavishankar So my question is how to avoid the error with the original IR just like what is shown in `func.func @test_0()`?

I think you just need to add a pattern to the pass to handle `memref.assume_alignment` (I think we discussed that above as one of the necessary things). It should be a simple replacement of the operand with the value from the `Adaptor` since the alignment is already expressed in bytes.

**Comment by yzhang93** [comment]
> I think you just need to add a pattern to the pass to handle `memref.assume_alignment` (I think we discussed that above as one of the necessary things). It should be a simple replacement of the operand with the value from the `Adaptor` since the alignment is already expressed in bytes.

Yes, I've added the conversion pattern for `memref.assume_alignment`, and so my above `@test_1` works. But for `@test_0`, `%0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<131072x128xi4>` couldn't be converted to i8, so it creates `builtin.unrealized_conversion_cast`, and `memref.assume_alignment` can be converted. But then it generates error that some ops remained live after conversion.

**Comment by MaheshRavishankar** [comment]
> > I think you just need to add a pattern to the pass to handle `memref.assume_alignment` (I think we discussed that above as one of the necessary things). It should be a simple replacement of the operand with the value from the `Adaptor` since the alignment is already expressed in bytes.
> 
> Yes, I've added the conversion pattern for `memref.assume_alignment`, and so my above `@test_1` works. But for `@test_0`, `%0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<131072x128xi4>` couldn't be converted to i8, so it creates `builtin.unrealized_conversion_cast`, and `memref.assume_alignment` can be converted. But then it generates error that some ops remained live after conversion.

Ok, make sense.. You probably need to add some IREE specific patterns. The binding changes should also be just a type change for the result (and potentially change of the offset). We can chat more on GVC.

**Comment by hanhanW** [comment]
(cc myself to the issue)

**Comment by yzhang93** [comment]
After adding the type conversion pattern for IREE::HAL::InterfaceBindingSubspanOp, now the above example IR compiles fine with `iree-emulate-narrow-type` pass. Here's the printed IR after all passes https://storage.googleapis.com/shark-public/vivian/vicuna_i4/dequant_after_all.mlir.

However, if I run the above example IR with `--input=4096x4096xi4`, it has a runtime error:
```
iree/runtime/src/iree/hal/buffer_view_util.c:39: INVALID_ARGUMENT; opaque and sub-byte aligned element types cannot be indexed; parsing value '4096x4096xi4'; parsing function inputs
```

Instead of taking `tensor<4096x4096xi4>` as an input argument, if it takes the tensor as a constant, e.g.,
```
  func.func @dequant() -> tensor<4096x32x128xf32> {
    %arg0 = arith.constant dense_resource<__elided__> : tensor<4096x4096xi4>
   ....
 }
```
It runs without any error.


On the other hand, I still have compilation error when running the real [vicuna model](https://storage.googleapis.com/shark-public/vivian/vicuna_i4/0_0_linalg_i4.mlir), the error is shown as
```
<unknown>:0: error: unhandled integer element bitwidth 4 for type 'tensor<131072x128xi4>'
0_0_linalg_i4.mlir:18:1: error: failed to write embedded file to the output stream - possibly out of memory or storage (file size: 217153536)
```

**Comment by hanhanW** [comment]
> However, if I run the above example IR with --input=4096x4096xi4, it has a runtime error:

I suspect i4 inputs is not working in IREE, @antiagainst do you know any update about that?

> Instead of taking tensor<4096x4096xi4> as an input argument, if it takes the tensor as a constant, e.g.,

Is the output correct? There is an opening issue about packed int4 constant, https://github.com/openxla/iree/issues/13926. I don't know if it is supported in IREE or not. If it does not work and we want to test the emulation correctness, we can emulate the case "load i8 as i32".

> <unknown>:0: error: unhandled integer element bitwidth 4 for type 'tensor<131072x128xi4>'

I don't know where is the error from. If the dest buffer is i4 in a dispatch, I'm not surprised that it's not working. Let's focus on simple example before looking into the real model. Those issue could be caught in a simple example.

**Comment by yzhang93** [comment]
> Is the output correct? There is an opening issue about packed int4 constant, #13926. I don't know if it is supported in IREE or not. If it does not work and we want to test the emulation correctness, we can emulate the case "load i8 as i32".

The output is correct for uniform constant tensor<4096x4096xi4>. I also wanted to tried with a non-uniform input, with 
```
    %arg0 = arith.constant dense<[[0,1,2,3,..,]]> : tensor<1x128xi4>
```
However, during lowering it becomes `%0 = memref.get_global @__constant_128xi4 : memref<128xi4>` instead of `hal.interface.binding.subspan`. There's an error because I didn't populate conversion pattern for memref.get_global. Is there any way to avoid using the `memref.get_global` op?

**Comment by MaheshRavishankar** [comment]
No. For constants that are not splat constants, they need to be lowered through memref.get_global. so if we need to support that, we need to add that pattern

**Comment by yzhang93** [comment]
> No. For constants that are not splat constants, they need to be lowered through memref.get_global. so if we need to support that, we need to add that pattern

Okay, I've tried to add conversion pattern for `memref.get_global` and `memref.global` ops. There's no problem for `memref.get_global` type conversion, however, I wasn't able to successfully convert `memref.global "private" constant @__constant_4xi4 : memref<4xi4> = dense<[1, 2, 3, 5]>`. Is this op not rewritable or something?



Also, I think these two ops are only needed for a small constant like in the test example. I tried to add the large weights from the model by `%arg0 = arith.constant dense<....> : tensor<4096x4096xi4>`, and then hit the error I mentioned above

```
<unknown>:0: error: unhandled integer element bitwidth 4 for type 'tensor<131072x128xi4>'
```

**Comment by hanhanW** [comment]
Instead of fixing all plumbing through issue, I'd suggest to test it with `emulate i8 load using i32 types`. That will give us confidence that the pass is correct; we can land the patch. It will move CPU to the state as SPIRV. Then we can fix the issues listed in https://github.com/openxla/iree/issues/13567#issue-1706421393 ; evaluate what's missing.

**Comment by MaheshRavishankar** [comment]
> > No. For constants that are not splat constants, they need to be lowered through memref.get_global. so if we need to support that, we need to add that pattern
> 
> Okay, I've tried to add conversion pattern for `memref.get_global` and `memref.global` ops. There's no problem for `memref.get_global` type conversion, however, I wasn't able to successfully convert `memref.global "private" constant @__constant_4xi4 : memref<4xi4> = dense<[1, 2, 3, 5]>`. Is this op not rewritable or something?
> 

This is a module level object. So you will need a module pass, and replace that op. Also you wont be replacing all uses, but all symbolic uses. (This op exports a symbol that is referenced by users). 

> Also, I think these two ops are only needed for a small constant like in the test example. I tried to add the large weights from the model by `%arg0 = arith.constant dense<....> : tensor<4096x4096xi4>`, and then hit the error I mentioned above
> 
> ```
> <unknown>:0: error: unhandled integer element bitwidth 4 for type 'tensor<131072x128xi4>'
> ```





> Instead of fixing all plumbing through issue, I'd suggest to test it with `emulate i8 load using i32 types`. That will give us confidence that the pass is correct; we can land the patch. It will move CPU to the state as SPIRV.

That makes sense... but do check manually that the arith is happening in i32 and loads from i8 are converted to i32 (IIUC the intent here). If that passes, we can land the change upstream....

**Comment by yzhang93** [comment]
Sounds good. Is there a good test case in your mind? Should I start with linalg ops? I found some simple tests that don't have memref.load after lowering or need memref.store to work.

**Comment by hanhanW** [comment]
Maybe try this, and verify the IR dumps after all.

https://github.com/openxla/iree/blob/14452a172feae3f88b2f11d9f38cc90985648ced/tests/e2e/stablehlo_ops/convert.mlir#L8-L13

I'm happy to verify IR dumps if you share the IR with me.

**Comment by yzhang93** [comment]
I have tried to emulate i8 to i32, and here is the [dumped IR](https://storage.googleapis.com/shark-public/vivian/vicuna_i4/test_i8toi32_dump.mlir).

The run results are showing to me as:
result[0]: hal.buffer_view
3x4xf32=[-4 -2 0 2][4 6 8 10][12 14 16 18]

Please let me know if these seem right to you.

For record, I've also updated the [llvm patch](https://reviews.llvm.org/D151519) and the IREE pass in [my branch](https://github.com/openxla/iree/commit/ea49d2b1531f1c7855ec2c65d7d9f97e5458d2ae).

**Comment by hanhanW** [comment]
It is doing `f(x) = (x - 3) * 2`. The output looks correct to me.

The IR dump also looks good to me. Thanks!

```mlir
// -----// IR Dump After ExpandOps (memref-expand) //----- //
func.func @dequant_dispatch_0_generic_3x4_i8xf32xf32xf32() {
  %c1 = arith.constant 1 : index
  %c4 = arith.constant 4 : index
  %c3 = arith.constant 3 : index
  %c0 = arith.constant 0 : index
  %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<3x4xi8>
  memref.assume_alignment %0, 64 : memref<3x4xi8>
  %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<3xf32>
  memref.assume_alignment %1, 64 : memref<3xf32>
  %2 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<3x4xf32>
  memref.assume_alignment %2, 64 : memref<3x4xf32>
  %3 = hal.interface.binding.subspan set(0) binding(3) type(storage_buffer) alignment(64) offset(%c0) : memref<3x4xf32>
  memref.assume_alignment %3, 64 : memref<3x4xf32>
  %workgroup_id_x = hal.interface.workgroup.id[0] : index
  %workgroup_count_x = hal.interface.workgroup.count[0] : index
  %workgroup_id_y = hal.interface.workgroup.id[1] : index
  %workgroup_count_y = hal.interface.workgroup.count[1] : index
  %4 = affine.apply affine_map<()[s0] -> (s0 * 3)>()[%workgroup_id_y]
  %5 = affine.apply affine_map<()[s0] -> (s0 * 3)>()[%workgroup_count_y]
  cf.br ^bb1(%4 : index)
^bb1(%6: index):  // 2 preds: ^bb0, ^bb9
  %7 = arith.cmpi slt, %6, %c3 : index
  cf.cond_br %7, ^bb2, ^bb10
^bb2:  // pred: ^bb1
  %8 = affine.apply affine_map<()[s0] -> (s0 * 4)>()[%workgroup_id_x]
  %9 = affine.apply affine_map<()[s0] -> (s0 * 4)>()[%workgroup_count_x]
  cf.br ^bb3(%8 : index)
^bb3(%10: index):  // 2 preds: ^bb2, ^bb8
  %11 = arith.cmpi slt, %10, %c4 : index
  cf.cond_br %11, ^bb4(%c0 : index), ^bb9
^bb4(%12: index):  // 2 preds: ^bb3, ^bb7
  %13 = arith.cmpi slt, %12, %c3 : index
  cf.cond_br %13, ^bb5(%c0 : index), ^bb8
^bb5(%14: index):  // 2 preds: ^bb4, ^bb6
  %15 = arith.cmpi slt, %14, %c4 : index
  cf.cond_br %15, ^bb6, ^bb7
^bb6:  // pred: ^bb5
  %16 = memref.load %0[%12, %14] : memref<3x4xi8>
  %17 = memref.load %1[%12] : memref<3xf32>
  %18 = memref.load %2[%12, %c0] : memref<3x4xf32>
  %19 = arith.extui %16 : i8 to i32
  %20 = arith.uitofp %19 : i32 to f32
  %21 = arith.subf %20, %18 : f32
  %22 = arith.mulf %21, %17 : f32
  memref.store %22, %3[%12, %14] : memref<3x4xf32>
  %23 = arith.addi %14, %c1 : index
  cf.br ^bb5(%23 : index)
^bb7:  // pred: ^bb5
  %24 = arith.addi %12, %c1 : index
  cf.br ^bb4(%24 : index)
^bb8:  // pred: ^bb4
  %25 = arith.addi %10, %9 : index
  cf.br ^bb3(%25 : index)
^bb9:  // pred: ^bb3
  %26 = arith.addi %6, %5 : index
  cf.br ^bb1(%26 : index)
^bb10:  // pred: ^bb1
  return
}

// -----// IR Dump After EmulateNarrowType (iree-emulate-narrow-type) //----- //
module {
  func.func @dequant_dispatch_0_generic_3x4_i8xf32xf32xf32() {
    %c1 = arith.constant 1 : index
    %c4 = arith.constant 4 : index
    %c3 = arith.constant 3 : index
    %c0 = arith.constant 0 : index
    %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<3x4xi32>
    memref.assume_alignment %0, 64 : memref<3x4xi32>
    %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<3xf32>
    memref.assume_alignment %1, 64 : memref<3xf32>
    %2 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<3x4xf32>
    memref.assume_alignment %2, 64 : memref<3x4xf32>
    %3 = hal.interface.binding.subspan set(0) binding(3) type(storage_buffer) alignment(64) offset(%c0) : memref<3x4xf32>
    memref.assume_alignment %3, 64 : memref<3x4xf32>
    %workgroup_id_x = hal.interface.workgroup.id[0] : index
    %workgroup_count_x = hal.interface.workgroup.count[0] : index
    %workgroup_id_y = hal.interface.workgroup.id[1] : index
    %workgroup_count_y = hal.interface.workgroup.count[1] : index
    %4 = affine.apply affine_map<()[s0] -> (s0 * 3)>()[%workgroup_id_y]
    %5 = affine.apply affine_map<()[s0] -> (s0 * 3)>()[%workgroup_count_y]
    cf.br ^bb1(%4 : index)
  ^bb1(%6: index):  // 2 preds: ^bb0, ^bb9
    %7 = arith.cmpi slt, %6, %c3 : index
    cf.cond_br %7, ^bb2, ^bb10
  ^bb2:  // pred: ^bb1
    %8 = affine.apply affine_map<()[s0] -> (s0 * 4)>()[%workgroup_id_x]
    %9 = affine.apply affine_map<()[s0] -> (s0 * 4)>()[%workgroup_count_x]
    cf.br ^bb3(%8 : index)
  ^bb3(%10: index):  // 2 preds: ^bb2, ^bb8
    %11 = arith.cmpi slt, %10, %c4 : index
    cf.cond_br %11, ^bb4(%c0 : index), ^bb9
  ^bb4(%12: index):  // 2 preds: ^bb3, ^bb7
    %13 = arith.cmpi slt, %12, %c3 : index
    cf.cond_br %13, ^bb5(%c0 : index), ^bb8
  ^bb5(%14: index):  // 2 preds: ^bb4, ^bb6
    %15 = arith.cmpi slt, %14, %c4 : index
    cf.cond_br %15, ^bb6, ^bb7
  ^bb6:  // pred: ^bb5
    %base_buffer, %offset, %sizes:2, %strides:2 = memref.extract_strided_metadata %0 : memref<3x4xi32> -> memref<i32>, index, index, index, index, index
    %16 = affine.apply affine_map<()[s0, s1, s2, s3] -> ((s0 * s1 + s2 * s3) floordiv 4)>()[%12, %strides#0, %14, %strides#1]
    %17 = affine.apply affine_map<()[s0, s1] -> (s0 * s1)>()[%sizes#0, %sizes#1]
    %18 = affine.apply affine_map<()[s0] -> (s0 floordiv 4)>()[%offset]
    %reinterpret_cast = memref.reinterpret_cast %base_buffer to offset: [%18], sizes: [%17], strides: [%strides#1] : memref<i32> to memref<12xi32, strided<[?], offset: ?>>
    %19 = memref.load %reinterpret_cast[%16] : memref<12xi32, strided<[?], offset: ?>>
    %20 = arith.index_castui %14 : index to i32
    %c4_i32 = arith.constant 4 : i32
    %c8_i32 = arith.constant 8 : i32
    %21 = arith.remui %20, %c4_i32 : i32
    %22 = arith.muli %21, %c8_i32 : i32
    %23 = arith.shrsi %19, %22 : i32
    %24 = arith.trunci %23 : i32 to i8
    %25 = memref.load %1[%12] : memref<3xf32>
    %26 = memref.load %2[%12, %c0] : memref<3x4xf32>
    %27 = arith.extui %24 : i8 to i32
    %28 = arith.uitofp %27 : i32 to f32
    %29 = arith.subf %28, %26 : f32
    %30 = arith.mulf %29, %25 : f32
    memref.store %30, %3[%12, %14] : memref<3x4xf32>
    %31 = arith.addi %14, %c1 : index
    cf.br ^bb5(%31 : index)
  ^bb7:  // pred: ^bb5
    %32 = arith.addi %12, %c1 : index
    cf.br ^bb4(%32 : index)
  ^bb8:  // pred: ^bb4
    %33 = arith.addi %10, %9 : index
    cf.br ^bb3(%33 : index)
  ^bb9:  // pred: ^bb3
    %34 = arith.addi %6, %5 : index
    cf.br ^bb1(%34 : index)
  ^bb10:  // pred: ^bb1
    return
  }
}
```

**Comment by yzhang93** [comment]
@hanhanW Thanks for your verification! Could you and @MaheshRavishankar review the llvm patch again? https://reviews.llvm.org/D151519

**Comment by hanhanW** [comment]
We can compile it on ToT now, closing the issue
