### ISSUE TITLE
Move shape validation from pybind runtime code to exported stub

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#1415]
Currently, there is a pretty non-trivial amount of code in [function_abi.cc](https://github.com/google/iree/blob/ba47fd25f09e752e5d60ce5babf31fd07d06da4d/bindings/python/pyiree/rt/function_abi.cc#L52) to validate ndarray shapes and such against the reflection metadata. Most of this could be safely moved to generated code, which would reduce a lot of complexity.

We could then choose whether to have a simplified ABI-checker that ran on exception only to generate full error messages.

**Comment by benvanik** [comment]
Obsolete? We at least have the pieces for it to be moved into generated code (vm.cond_fail).

**Comment by benvanik** [comment]
Getting this moved into the generated export stub will also help all other bindings (java/etc) get the same benefits.

**Comment by benvanik** [comment]
Closing as obsolete.
