### ISSUE TITLE
Use `T4` for main GPU CI instead of `A100`

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#14169]
These GPUs are much more widely available and cheaper. We can reserve a100 GPUs for testing that specifically requires them and benchmarking. This adds another job to run the a100 (sm80) tests. I think we should consider making it postsubmit only. Unfortunately, a lot of the time in the CI is spent on things other than running the tests. In fact, the whole a100 job takes 7 minutes, of which only 8 seconds is spent actually running tests :-/ So that is something to optimize. Even given that though, I think it's still worthwhile to split these out. That huge difference is mostly a result of not having very many arch-specific tests. The general GPU job spends more like 6 minutes running tests.

The other advantage is that it tests our GPU code that isn't *supposed* to be arch specific on something else. We've had a few cases of these tests not getting correctly tagged, but more importantly this also prevents accidentally adding an arch-specific dependency. In fact, I believe it has revealed a number of arch-specific tests on the e2e matmul (now that https://github.com/openxla/iree/issues/14133 is fixed).

This is going to require a staged rollout with multiple PRs. I sent out https://github.com/openxla/iree/pull/14121 as an initial proof that this works, but it actually needs to be submitted as separate PRs.

**Comment by GMNGeoffrey** [comment]
Well CI on the PRs here is taking forever because we're hitting stockouts for GPU machines. Seems like another reason to switch :-)

**Comment by GMNGeoffrey** [comment]
The rollout for this is proving difficult because the a100 capacity issues are preventing a reasonable canary. I basically just rolled it out 100%. So if CI starts falling over, make some noise!

**Comment by stellaraccident** [comment]
Test in prod

**Comment by GMNGeoffrey** [comment]
My monitoring is people complaining on discord :crying_cat_face:

**Comment by GMNGeoffrey** [comment]
We are now running on T4s
