### ISSUE TITLE
[DT][CPU] Data-tiled `i4` matmuls on LLVM-CPU

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#14195]
Here is an overview of steps toward fast `i4` matmuls on LLVM-CPU, under the assumption that `i4` is a compression-only thing, that we still want to go to `i8` for arithmetic that fits current CPU ISAs, and that there is enough RAM to hold some whole matrices (though not the entire workload) in wider element types than `i4`.

Steps:

1. Finish basic `i4` support - so that a `linalg.matmul` with `i4` element types works, even if it's slow for now.
2. Data-tiling: let `--iree-flow-enable-data-tiling` turn `linalg.matmul` with `i4` LHS/RHS element types into a familiar `linalg.mmt4d` on `i8` LHS/RHS element types, inserting `tensor.pack` ops to go from row-major `i4` source matrices to tiled `i8` packed matrices.
3. At this point, assuming `--iree-llvmcpu-enable-microkernels` is enabled, the core arithmetic work is as fast as the existing `i8` case and that's as fast as it can go on current CPU ISAs, which tend to have good support for `i8` matmuls but no native support for `i4`. There still remains to make those `i4`-to-`i8` `tensor.pack` go fast. For that, add a new code path in the `pack` microkernel.
4. Orchestrate the dispatches/scheduling to minimize peak RAM usage by minimizing the maximum number of 2x-widened `i8` packed matrices (as opposed to source `i4` matrices) that are simultaneously live.

**Comment by MaheshRavishankar** [comment]
We have quite a few issues filed related to i4 support. Its probably good to consolidate these.

> Here is an overview of steps toward fast `i4` matmuls on LLVM-CPU, under the assumption that `i4` is a compression-only thing, that we still want to go to `i8` for arithmetic that fits current CPU ISAs, and that there is enough RAM to hold some whole matrices (though not the entire workload) in wider element types than `i4`.
> 
> Steps:
> 
> 1. Finish basic `i4` support - so that a `linalg.matmul` with `i4` element types works, even if it's slow for now.

This is basically discussed in https://github.com/openxla/iree/issues/12859 . That is in flight.

> 2. Data-tiling: let `--iree-flow-enable-data-tiling` turn `linalg.matmul` with `i4` LHS/RHS element types into a familiar `linalg.mmt4d` on `i8` LHS/RHS element types, inserting `tensor.pack` ops to go from row-major `i4` source matrices to tiled `i8` packed matrices.

I am not sure about changing the data type while doing the packing.... We should be able to keep it in i4 for the packing since it is essentially just load/stores which is covered by (1).

> 3. At this point, assuming `--iree-llvmcpu-enable-microkernels` is enabled, the core arithmetic work is as fast as the existing `i8` case and that's as fast as it can go on current CPU ISAs, which tend to have good support for `i8` matmuls but no native support for `i4`. There still remains to make those `i4`-to-`i8` `tensor.pack` go fast. For that, add a new code path in the `pack` microkernel.

Micro kernels is an option, but this should be just transpose + load/store. If the pack is already vectorized, then the data type shouldnt matter. Basically whether we do `vector<8xi4>` or `vector<4xi8>` they are the same thing. But if that doesnt work, of course microkernels work.

> 4. Orchestrate the dispatches/scheduling to minimize peak RAM usage by minimizing the maximum number of 2x-widened `i8` packed matrices (as opposed to source `i4` matrices) that are simultaneously live.

I am not sure I follow this one.

**Comment by bjacob** [comment]
> I am not sure about changing the data type while doing the packing.... We should be able to keep it in i4 for the packing since it is essentially just load/stores which is covered by (1).

Actually you're right :-)

I was writing this from the generic perspective that the role of packing is to prepare data into the optimal layout for the O(N^3) arithmetic kernel. And on most CPU ISAs, that does involve expanding `i4` to `i8`.

However, in this very specific situation,

* Expanding `i4` to `i8` is really cheap -- the even-numbered `i4` lanes are just a matter of AND'ing `0x0f` bytes, and the odd-numbered `i4` lanes are just a matter of right-shifting `i8` lanes by 4 bits. This is lightweight enough that with the right instruction scheduling, this should have near zero cost depending on CPU details (given enough dual-issuing opportunities).
* The whole rationale for `i4` being to minimize RAM usage, avoiding the 2x widening of going to `i8` in buffers, and instead keeping the `i8` expanded data at the register scale, would be worth even a performance trade-off.

This is very specific to `i4` though and the topic will resurface as soon as we do minor variations around that... e.g. `i5` and `i6` would change the calculus in both of the above bullet points.

> Micro kernels is an option, but this should be just transpose + load/store.

Sure, we always default to giving pure codegen a chance and only write a ukernel as needed. Now I have to say, our of some experience, pure codegen doesn't always find it easy to handle arbitrary byte permutations, let alone bit permutations. It will vary depending on each tile shape. 

> I am not sure I follow this one.

A lot of memrefs being traversed across an e2e program are only referenced by one or two ops. So in any ML execution framework, there is some kind of byte-reusing allocator at play, taking advantage of non-overlapping lifespans. This aspect has always been present but has rarely been at the center of attention.  If we have scenarios where we are so RAM-constrained that we go through the hassle of less-than-8-bit quantization to relieve RAM pressure, then that buffer allocation concern will become important.

**Comment by MaheshRavishankar** [comment]
> > I am not sure about changing the data type while doing the packing.... We should be able to keep it in i4 for the packing since it is essentially just load/stores which is covered by (1).
> 
> Actually you're right :-)
> 
> I was writing this from the generic perspective that the role of packing is to prepare data into the optimal layout for the O(N^3) arithmetic kernel. And on most CPU ISAs, that does involve expanding `i4` to `i8`.
> 
> However, in this very specific situation,
> 
> * Expanding `i4` to `i8` is really cheap -- the even-numbered `i4` lanes are just a matter of AND'ing `0x0f` bytes, and the odd-numbered `i4` lanes are just a matter of right-shifting `i8` lanes by 4 bits. This is lightweight enough that with the right instruction scheduling, this should have near zero cost depending on CPU details (given enough dual-issuing opportunities).
> * The whole rationale for `i4` being to minimize RAM usage, avoiding the 2x widening of going to `i8` in buffers, and instead keeping the `i8` expanded data at the register scale, would be worth even a performance trade-off.
> 
> This is very specific to `i4` though and the topic will resurface as soon as we do minor variations around that... e.g. `i5` and `i6` would change the calculus in both of the above bullet points.
> 
> > Micro kernels is an option, but this should be just transpose + load/store.
> 
> Sure, we always default to giving pure codegen a chance and only write a ukernel as needed. Now I have to say, our of some experience, pure codegen doesn't always find it easy to handle arbitrary byte permutations, let alone bit permutations. It will vary depending on each tile shape.

Yeah, if we need to do transposes, micro-kernels make sense.

> 
> > I am not sure I follow this one.
> 
> A lot of memrefs being traversed across an e2e program are only referenced by one or two ops. So in any ML execution framework, there is some kind of byte-reusing allocator at play, taking advantage of non-overlapping lifespans. This aspect has always been present but has rarely been at the center of attention. If we have scenarios where we are so RAM-constrained that we go through the hassle of less-than-8-bit quantization to relieve RAM pressure, then that buffer allocation concern will become important.

I think this is a concern for even non sub-byte models. IREEs buffer allocation already does this to some extent. Within certain scopes the same buffer is reused for non-overlapping sets to reduce the maxlive memory usage at any given time.
