### ISSUE TITLE
CMake tracking of the test host being an emulator

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#14197]
At the moment we are tagging `noriscv` a bunch of tests just because they take to long to run on emulators on CI. #14157 is proposing to instead centralize the logic that long tests are disabled on RISC-V, which is a step towards solving that in that at least it makes this localized, but we should really solve that problem that we are incorrectly treating RISC-V as slow.

We could have a CMake boolean option tracking whether the test host is an emulator. Then our RISC-V CI scripts could set that option.

**Comment by allieculp** [comment]
@bjacob should this be assigned to you? or looking for someone to pick it up?

**Comment by allieculp** [comment]
@bjacob Checking on this one again - is this in your queue?

**Comment by ScottTodd** [comment]
Closing stale issue. All tests currently tagged `noriscv` are in tests/e2e/matmul, and we plan on moving that test suite to https://github.com/iree-org/iree-test-suites. We'll have more/different control over platforms and filtering there than we do in IREE's monolithic CMake project.
