### ISSUE TITLE
Switch to llvm-cpu for consteval for perf and accuracy

### ISSUE THREAD

**Issue by powderluv** [iree-org/iree#14199]
### Request description

SHARK-Runtime carries a local consteval with llvm-cpu https://github.com/openxla/iree/commit/cf1977b0740124805565b579f78b39e8f1772a65 patch for accuracy reasons but it may also help for compile time performance. Consider making it permanent in ToM. 

Large MLIR file to test is available at 

https://github.com/nod-ai/SHARK/issues/1581

**Comment by allieculp** [comment]
@stellaraccident @benvanik Bumping this up, please take a look!

**Comment by allieculp** [comment]
Setting as P2 for now. Please edit as needed.

**Comment by ScottTodd** [comment]
Fixed by https://github.com/openxla/iree/pull/14530
