### ISSUE TITLE
`spirv.Bitcast` op result type verification failure

### ISSUE THREAD

**Issue by Ranvirsv** [iree-org/iree#14227]
### What happened?

Compiling the mlir, throws the error 
```
dispatches/module_forward_dispatch_37.mlir:39:15: error: 'spirv.Bitcast' op result #0 must be 8/16/32/64-bit integer or 16/32/64-bit float or bool or vector of bool or 8/16/32/64-bit integer or 16/32/64-bit float values of length 2/3/4/8/16 or any SPIR-V pointer type, but got 'vector<1xf32>'
        %26 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0)>, affine_map<(d0, d1) -> (d0)>], iterator_types = ["parallel", "reduction"]} ins(%18, %19 : tensor<8192x320xf32>, tensor<8192xf32>) outs(%25 : tensor<8192xf32>) {
```

Here is the iree-compile command used:
```
iree-compile dispatches/module_forward_dispatch_37.mlir  --iree-hal-target-backends=vulkan --iree-vulkan-target-triple=m1-moltenvk-macos --iree-stream-resource-index-bits=64 -o compiled-dispatch/fd37.vmfb 2> compiled-dispatch/fd37-error.log
```
Attached error log:
[fd37-error.log](https://github.com/openxla/iree/files/11874999/fd37-error.log)

Attached falling dispatch:
[module_forward_dispatch_37.txt](https://github.com/openxla/iree/files/11874911/module_forward_dispatch_37.txt)

**Comment by antiagainst** [comment]
So we are not handling size-1 vector / scalar cases corner properly with `spirv.Bitcast`. @kuhar could you take a look and fix it?

**Comment by Ranvirsv** [comment]
Update for mac:

Dispatch:
[mac-module_forward_dispatch_37.txt](https://github.com/openxla/iree/files/11886700/mac-module_forward_dispatch_37.txt)

Error-Log:
[mac-fd37-error.log](https://github.com/openxla/iree/files/11886701/mac-fd37-error.log)

**Comment by kuhar** [comment]
Thanks for the detailed repro, @Ranvirsv. I am able to reproduce the error and minimized it to:
```mlir
func.func @cast7(%arg0 : vector<2xf16>) {
  %0 = spirv.Bitcast %arg0 : vector<2xf16> to vector<1xf32>
  return
}
```

Command: `mlir-opt repro.mlir --verify-diagnostics`.

Doesn't seem to be related to fp16 specifically, I can also reproduce it with `2xf32 -> 1xi64`.

---

edit:
I think this is as-intended if we do not allow 1-element vectors elsewhere in the SPIR-V dialect and instead we should handle it before we convert to SPIR-V.

**Comment by kuhar** [comment]
Separately, I'm wondering why these values are loaded like this in the first place:
```mlir
    %117 = "spirv.AccessChain"(%59, %106, %116) : (!spirv.ptr<!spirv.struct<(!spirv.rtarray<vector<2xf16>, stride=4> [0])>, StorageBuffer>, i32, i32) -> !spirv.ptr<vector<2xf16>, StorageBuffer>
    %118 = "spirv.Load"(%117) : (!spirv.ptr<vector<2xf16>, StorageBuffer>) -> vector<2xf16>
    %119 = "spirv.Bitcast"(%114) : (vector<2xf16>) -> vector<1xf32>
```

instead of accessing f32 directly.

**Comment by benvanik** [comment]
True! Feels like some propagation could happen and simplify these cases - wonder where that gets introduced.

**Comment by antiagainst** [comment]
Yeah worth seeing how this is converted in the CodeGen flow. Though during conversion to SPIR-V we should be able to handle size-1 vectors; that's also something needs to be fixed.

**Comment by kuhar** [comment]
These bitcasts come from `--spirv-unify-aliased-resource` where it tries to unify loads of ptrs with different element types:
```mlir
Convert load: %67 = spirv.Load "StorageBuffer" %65 : vector<2xf32>
        ptr: %65 = spirv.AccessChain %__resource_var_0_0__1_addr[%cst0_i32_24, %62] : !spirv.ptr<!spirv.struct<(!spirv.rtarray<vector<2xf32>, stride=8> [0])>, StorageBuffer>, i32, i32
New load: %66 = spirv.Load "StorageBuffer" %64 : vector<2xf16>
        ptr: %64 = spirv.AccessChain %__resource_var_0_0__addr[%cst0_i32_24, %63] : !spirv.ptr<!spirv.struct<(!spirv.rtarray<vector<2xf16>, stride=4> [0])>, StorageBuffer>, i32, i32
```

**Comment by powderluv** [comment]
@kuhar is there any workaround for this ? This prevents Stable Diffusion from running on the Metal backend (used to work with moltenvk and we would like to avoid going back to it).

**Comment by kuhar** [comment]
> @kuhar is there any workaround for this ? This prevents Stable Diffusion from running on the Metal backend (used to work with moltenvk and we would like to avoid going back to it).

I have a WIP fix in MLIR: https://reviews.llvm.org/D156207. Could you try applying it and see if it makes it work?

**Comment by Ranvirsv** [comment]
Sure I can try that.

**Comment by Ranvirsv** [comment]
Still get the same error `'spirv.Bitcast' op result #0 must be 8/16/32/64-bit integer...`

**Comment by powderluv** [comment]
You will have to apply it to the local fork of LLVM. Please double check it was getting pulled into your build.

**Comment by kuhar** [comment]
Did it work, @Ranvirsv? The patch landed in MLIR earlier today, so IREE should pick it up the next time we integrate llvm-project.

**Comment by kuhar** [comment]
The mlir change should have been integrated with https://github.com/openxla/iree/pull/14532. I'm going to close this as resolved, but feel free to reopen is you can still reproduce this.
