### ISSUE TITLE
Compiling Resnet50 takes a really long time

### ISSUE THREAD

**Issue by ramiro050** [iree-org/iree#14245]
### What happened?

Running

```
iree-compile --iree-hal-target-backends="cuda" resnet50.mlir
```

on [resnet50.mlir](https://gist.github.com/ramiro050/ac630dc88e4d051b4cf7baa180d32e14) gets stuck. I have not seen it complete despite running for 10+ minutes. 

### What component(s) does this issue relate to?

Compiler

### Version information

IREE compiler version 20230625.563 @ 3898dc6707be2a3d0bbb7164c628cd82250279a3

**Comment by ramiro050** [comment]
The pass taking a long time is `iree-codegen-rematerialize-parallel-ops`. [This is the IR](https://gist.github.com/ramiro050/00d0f626250f93966e09f335f8801325) before that pass.

**Comment by ScottTodd** [comment]
Do you think this is a regression (i.e. was it fast to compile on that machine before)? https://github.com/openxla/iree/blob/main/docs/developers/debugging/compile_time_regressions.md has some tips for identifying culprit commits if so. Also thanks for doing some initial analysis and finding which pass is slow + grabbing the IR!

**Comment by ScottTodd** [comment]
I think this was fixed in https://github.com/openxla/iree/pull/14259
