### ISSUE TITLE
cmake configuration with `IREE_BUILD_PYTHON_BINDINGS` fails to find python3 packages

### ISSUE THREAD

**Issue by suryajasper** [iree-org/iree#14248]
CMAKE configuration command: 
`cmake -G Ninja -B "../iree-build-softmax-patch/" -DIREE_BUILD_PYTHON_BINDINGS=ON -DPython3_EXECUTABLE="/home/nod/Documents/SHARK/shark.venv/bin/python3" -S .`

- Using python version 3.11.4 (ensured correct executable path specified with `Python3_EXECUTABLE` variable)
- Using cmake version 3.27
- Running on amd64 Ubuntu 20.04

The configuration is failing with the following error message.
```
-- IREE HAL drivers:
--   - cuda
--   - local-sync
--   - local-task
--   - vulkan
-- IREE HAL local executable library loaders:
--   - embedded-elf
--   - system-library
--   - vmvx-module
-- IREE HAL local executable plugin mechanisms:
--   - embedded-elf
--   - system-library
-- IREE compiler input dialects:
--   - StableHLO
--   - Torch MLIR
--   - TOSA
-- IREE compiler output formats:
--   - 'vm-c': textual C source module
--   - 'vm-bytecode': VM bytecode
--   - 'vm-asm': VM MLIR assembly
-- IREE_ENABLE_ASSERTIONS force disabled NDEBUG for CMAKE_CXX_FLAGS_RELWITHDEBINFO: '-O2 -g -DNDEBUG' -> '-O2 -g '
-- IREE_ENABLE_ASSERTIONS force disabled NDEBUG for CMAKE_C_FLAGS_RELWITHDEBINFO: '-O2 -g -DNDEBUG' -> '-O2 -g '
-- Enabling gdb-index (binaries with debug info are not relocatable)
-- Enabling thin archives (static libraries will not be relocatable)
-- Could NOT find Python3 (missing: Development NumPy Development.Module Development.Embed) (found suitable version "3.11.4", minimum required is "3.8")
CMake Error at /usr/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Development.Module
  NumPy) (found suitable version "3.11.4", minimum required is "3.8")
Call Stack (most recent call first):
  /usr/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.27/Modules/FindPython/Support.cmake:3824 (find_package_handle_standard_args)
  /usr/share/cmake-3.27/Modules/FindPython3.cmake:545 (include)
  CMakeLists.txt:631 (find_package)
```

Checking the source of the error in `CMakeLists.txt` reveals that these issues are coming up before the python executable path is even configured, so I'm guessing it's looking for packages in the wrong place. Configuring `Python3_INCLUDE_DIRS` and `Python3_LIBRARY` doesn't fix the issue either.
https://github.com/openxla/iree/blob/444eb7ca307fbd8db08a7e7001070947b37aa78a/CMakeLists.txt#L620-L632

**Comment by stellaraccident** [comment]
We did just tweak this recently, so I'd like to figure out if this is newly broken or never worked for you.

The error message you are getting makes it seem like the python or numpy development packages are not installed. If running on ubuntu, can you confirm that python3-devel is installed? Also, of you installed numpy as a system package, python3-numpy-devel (I usually install the pip package).

Also, you need to pip install the build_requirements.txt if running CMake manually (vs creating a wheel).

**Comment by suryajasper** [comment]
Had the build dependencies and python3-dev installed. The issue was that my python3-dev was installed for the wrong version of python. Bumped it up and it resolved the issue.
