### ISSUE TITLE
`func.func` op exceeded stack allocation limit

### ISSUE THREAD

**Issue by Ranvirsv** [iree-org/iree#14252]
Get this error while compiling `resnet101`, `resnet50` and `resnet50_2` torch models. 

```
dispatches/module_forward_dispatch_60.mlir:9:6: error: 'func.func' op exceeded stack allocation limit of 32768 bytes for function. Got 66368 bytes
      func.func @forward_dispatch_60_generic_128x784_f32() {
     ^
dispatches/module_forward_dispatch_60.mlir:9:6: note: see current operation:
"func.func"() <{function_type = () -> (), sym_name = "forward_dispatch_60_generic_128x784_f32"}> ({
```

The issue seems to be linked to the flag `--iree-preprocessing-pass-pipeline="builtin.module(func.func(iree-preprocessing-convert-conv2d-to-img2col))"`

Iree-compile command:
```
iree-compile ../../Models/Nod/builder_repro_artifacts_eaa4_resnet101_torch_False_cpu_core-input.mlir --iree-input-type=auto --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-embedded-linker-path=/Users/ranvirsinghvirk/Eclipse/NOD/SHARK/shark.venv/lib/python3.11/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --mlir-pass-pipeline-crash-reproducer=./resnet101_torch_True_cpu9c2cbm9e/core-reproducer.mlir --iree-llvmcpu-target-cpu-features=host --iree-llvmcpu-target-triple=arm64-apple-darwin22.4.0 --iree-flow-enable-data-tiling --iree-llvmcpu-enable-microkernels --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=true --iree-util-zero-fill-elided-attrs --iree-preprocessing-pass-pipeline="builtin.module(func.func(iree-flow-convert-conv-nchw-to-nhwc))" --iree-preprocessing-pass-pipeline="builtin.module(func.func(iree-preprocessing-convert-conv2d-to-img2col))" -o resnet101_torch_False.vmfb 2> error.log
```

Attached the error.log file and the failing MLIR dispatch 
[module_forward_dispatch_60.txt](https://github.com/openxla/iree/files/11898899/module_forward_dispatch_60.txt)
[error.log](https://github.com/openxla/iree/files/11898901/error.log)

**Comment by MaheshRavishankar** [comment]
Your dispatch has the `set_encoding/unset_encoding` operations. This seems to be using the data tiling path which isnt turned on by default yet... I think there are a few PRs that @hanhanW has in flight that might address these, but may drop the `--iree-flow-enable-data-tiling` for now?

**Comment by MaheshRavishankar** [comment]
(also tip: For small dispatches like this it is more ergonomic to just post the IR directly in the bug  . But thanks for narrowing down to a dispatch!)

**Comment by hanhanW** [comment]
Looks like the generic op and tensor.pack op are not vectorized for some reasons. They are scalar codes after bufferization.

```mlir
      "scf.for"(%7, %53, %9) ({
      ^bb0(%arg2: index):
        %63 = "memref.load"(%55, %7, %arg2) <{nontemporal = false}> : (memref<1x?xf32, strided<[784, 1], offset: ?>>, index, index) -> f32
        %64 = "memref.load"(%56, %7) <{nontemporal = false}> : (memref<1xf32, strided<[1], offset: ?>>, index) -> f32
        %65 = "memref.load"(%57, %7) <{nontemporal = false}> : (memref<1xf32, strided<[1], offset: ?>>, index) -> f32
        %66 = "memref.load"(%58, %7) <{nontemporal = false}> : (memref<1xf32, strided<[1], offset: ?>>, index) -> f32
        %67 = "memref.load"(%59, %7) <{nontemporal = false}> : (memref<1xf32, strided<[1], offset: ?>>, index) -> f32
        %68 = "arith.addf"(%67, %12) <{fastmath = #arith.fastmath<none>}> : (f32, f32) -> f32
        %69 = "math.rsqrt"(%68) <{fastmath = #arith.fastmath<none>}> : (f32) -> f32
        %70 = "arith.subf"(%63, %66) <{fastmath = #arith.fastmath<none>}> : (f32, f32) -> f32
        %71 = "arith.mulf"(%70, %69) <{fastmath = #arith.fastmath<none>}> : (f32, f32) -> f32
        %72 = "arith.mulf"(%71, %64) <{fastmath = #arith.fastmath<none>}> : (f32, f32) -> f32
        %73 = "arith.addf"(%72, %65) <{fastmath = #arith.fastmath<none>}> : (f32, f32) -> f32
        %74 = "arith.cmpf"(%73, %11) <{predicate = 9 : i64}> : (f32, f32) -> i1
        %75 = "arith.select"(%74, %73, %11) : (i1, f32, f32) -> f32
        "memref.store"(%75, %54, %7, %arg2) <{nontemporal = false}> : (f32, memref<1x?xf32, strided<[64, 1]>>, index, index) -> ()
        "scf.yield"() : () -> ()
      }) : (index, index, index) -> ()
```

It will allocate a big buffer if not all ops are vecotized.

**Comment by MaheshRavishankar** [comment]
is `math.rsqrtf` operation vectorized?

**Comment by hanhanW** [comment]
> is `math.rsqrtf` operation vectorized?

Yes, I think so. All the math ops and arith ops have the trait.

```
class Math_Op<string mnemonic, list<Trait> traits = []> :
    Op<Math_Dialect, mnemonic, traits # [Pure,
    DeclareOpInterfaceMethods<VectorUnrollOpInterface>] #
    ElementwiseMappable.traits>;

...

class Arith_Op<string mnemonic, list<Trait> traits = []> :
    Op<Arith_Dialect, mnemonic,
       traits #
       [DeclareOpInterfaceMethods<VectorUnrollOpInterface>, NoMemoryEffect] #
       ElementwiseMappable.traits>;
```


It would be good to see the IR before and after vectorization pass..

**Comment by Ranvirsv** [comment]
Here is the IR before and after the vectorization:
[dispatch_60_before_vectorization.log](https://github.com/openxla/iree/files/11910989/dispatch_60_before_vectorization.log)
[dispatch_60_after_vectorization.log](https://github.com/openxla/iree/files/11911003/dispatch_60_after_vectorization.log)


Believe this is what was needed?

**Comment by Ranvirsv** [comment]
> Your dispatch has the `set_encoding/unset_encoding` operations. This seems to be using the data tiling path which isnt turned on by default yet... I think there are a few PRs that @hanhanW has in flight that might address these, but may drop the `--iree-flow-enable-data-tiling` for now?

I was asked to keep the `--iree-flow-enable-data-tiling`

**Comment by MaheshRavishankar** [comment]
ok... then this is not a simple fix. @hanhanW please prioritize appropriately.

**Comment by hanhanW** [comment]
There are missing features for data-tiling path, and it's easy to hit stack allocation issue. This dispatch is not trivial, and it's not an easy fix. Can you share the IR after `LLVMCPUMaterializeEncodingPass` and the IR before `DecomposePackUnPackOpsPass`? That would give us a better repro and understand what's happening.

**Comment by Ranvirsv** [comment]
Sure here are the IR's requested:
[dispatch_60_after_materialize_encoding_pass.log](https://github.com/openxla/iree/files/11911190/dispatch_60_after_materialize_encoding_pass.log)
[dispatch_60_before_deconpose_pack_unpack_ops.log](https://github.com/openxla/iree/files/11911191/dispatch_60_before_deconpose_pack_unpack_ops.log)

**Comment by powderluv** [comment]
should we increase the stack size ? Or should we disable data-tiling on these models for now ?

**Comment by MaheshRavishankar** [comment]
The stack allocation should be bounded. So you can just use a flag to ignore the error. I don't have the flag handy.

EDIT found it :     `--iree-llvmcpu-fail-on-out-of-bounds-stack-allocation=false`

**Comment by hanhanW** [comment]
I took a look and found that there are two issues:

1. Adjusting tile sizes because of pack op needs to consider interchange factors. We set lowering config based on generic op while the tiling starts from pack ops. The tile sizes (in the list) should be interchanged.
2. We need to handle vectorization for pad op with bounded dynamic shapes, but there were concerns in my mind (I don't remember all details now :p). Or we wait for multi_lowering config patch. With the patch, we will tile those dimensions to `1`, then we don't see dynamic shapes.

I'll work on (1) and will figure out how to address (2).

**Comment by hanhanW** [comment]
Smaller repro:

```mlir
#map = affine_map<(d0, d1) -> (d0, d1)>
#map1 = affine_map<(d0, d1) -> (d0)>
module {
  func.func @forward_dispatch_60_generic_128x784_f32(%arg0: tensor<16x98x8x8xf32>, %arg1: tensor<128xf32>, %arg2: tensor<128xf32>, %arg3: tensor<128xf32>, %arg4: tensor<128xf32>) -> tensor<98x128x8x1xf32> {
    %cst = arith.constant 0.000000e+00 : f32
    %cst_0 = arith.constant 9.99999974E-6 : f32
    %0 = tensor.empty() : tensor<128x784xf32>
    %1 = tensor.empty() : tensor<128x784xf32>
    %unpack = tensor.unpack %arg0 inner_dims_pos = [0, 1] inner_tiles = [8, 8] into %1 : tensor<16x98x8x8xf32> -> tensor<128x784xf32>
    %2 = linalg.generic {indexing_maps = [#map, #map1, #map1, #map1, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%unpack, %arg1, %arg2, %arg3, %arg4 : tensor<128x784xf32>, tensor<128xf32>, tensor<128xf32>, tensor<128xf32>, tensor<128xf32>) outs(%0 : tensor<128x784xf32>) {
    ^bb0(%in: f32, %in_1: f32, %in_2: f32, %in_3: f32, %in_4: f32, %out: f32):
      %4 = arith.addf %in_4, %cst_0 : f32
      %5 = math.rsqrt %4 : f32
      %6 = arith.subf %in, %in_3 : f32
      %7 = arith.mulf %6, %5 : f32
      %8 = arith.mulf %7, %in_1 : f32
      %9 = arith.addf %8, %in_2 : f32
      %10 = arith.cmpf ugt, %9, %cst : f32
      %11 = arith.select %10, %9, %cst : f32
      linalg.yield %11 : f32
    } -> tensor<128x784xf32>
    %3 = tensor.empty() : tensor<98x128x8x1xf32>
    %pack = tensor.pack %2 outer_dims_perm = [1, 0] inner_dims_pos = [1, 0] inner_tiles = [8, 1] into %3 : tensor<128x784xf32> -> tensor<98x128x8x1xf32>
    return %pack : tensor<98x128x8x1xf32>
  }
}

```
