### ISSUE TITLE
Control flow / RNG operations fail to compile due to `tensor.from_elements` operation

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#14255]
We are failing to compile some models with control flow due to the `tensor.from_elements` operator. See the IR below.

Overall it results in a `tensor.from_elements` operation existing and being unable to compile away during compilation
 to ConvertToLLVM. It is likely this should be cleaned up earlier in the pipeline through detensorization.

Input IR:
```
  func.func public @main(%arg0: tensor<i32> {mhlo.sharding = "{replicated}"}, %arg1: tensor<2x2xi32>, %arg2: tensor<2x2xi32>) -> (tensor<i32>, tensor<2x2xi32>, tensor<2x2xi32>) {
    %0:3 = stablehlo.while(%iterArg = %arg0, %iterArg_0 = %arg1, %iterArg_1 = %arg2) : tensor<i32>, tensor<2x2xi32>, tensor<2x2xi32>
     cond {
      %1 = stablehlo.constant dense<5> : tensor<i32>
      %2 = stablehlo.compare  LT, %iterArg, %1,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1>
      stablehlo.return %2 : tensor<i1>
    } do {
      %1 = stablehlo.constant dense<1> : tensor<i32>
      %2 = stablehlo.add %iterArg, %1 : tensor<i32>
      stablehlo.return %2, %iterArg_1, %iterArg_0 : tensor<i32>, tensor<2x2xi32>, tensor<2x2xi32>
    }
    return %0#0, %0#1, %0#2 : tensor<i32>, tensor<2x2xi32>, tensor<2x2xi32>
  }
```

**Comment by rsuderman** [comment]
Related in part to https://github.com/openxla/iree/issues/6948

**Comment by rsuderman** [comment]
Another gist of a model that fails to compile:
https://gist.github.com/rsuderman/8faea40b1ae00255536696d265ffc75d

**Comment by ScottTodd** [comment]
> It is likely this should be cleaned up earlier in the pipeline through detensorization.

This could also be similar to https://github.com/openxla/iree/issues/12509. We'd like for detensoring to be an optimization, and not something necessary for correctness.

**Comment by rsuderman** [comment]
I agree. I imagine we are missing a `tensor.from_elements` canonicalization somewhere in the TensorToHAL patterns. Happy to write it if we think the issue is there.

**Comment by MaheshRavishankar** [comment]
So I think the issue is something else. This is IR at some point during compilation 
```
func.func public @main(%arg0: tensor<i32> {mhlo.sharding = "{replicated}"}, %arg1: tensor<2x2xi32>, %arg2: tensor<2x2xi32>) -> (tensor<i32>, tensor<2x2xi32>, tensor<2x2xi32>) {
  %0 = stablehlo.constant dense<1> : tensor<i32>
  %1 = stablehlo.constant dense<5> : tensor<i32>
  %extracted = tensor.extract %arg0[] : tensor<i32>
  %extracted_0 = tensor.extract %1[] : tensor<i32>
  %extracted_1 = tensor.extract %0[] : tensor<i32>
  cf.br ^bb1(%extracted, %arg0, %arg1, %arg2 : i32, tensor<i32>, tensor<2x2xi32>, tensor<2x2xi32>)
^bb1(%2: i32, %3: tensor<i32>, %4: tensor<2x2xi32>, %5: tensor<2x2xi32>):  // 2 preds: ^bb0, ^bb2                                                                                                                                                                                                                  
  %6 = arith.cmpi slt, %2, %extracted_0 : i32
  cf.cond_br %6, ^bb2, ^bb3
^bb2:  // pred: ^bb1                                                                                                                                                                                                                                                                                               
  %from_elements = tensor.from_elements %2 : tensor<i32>
  %7 = stablehlo.add %from_elements, %0 : tensor<i32>
  %8 = arith.addi %2, %extracted_1 : i32
  cf.br ^bb1(%8, %7, %5, %4 : i32, tensor<i32>, tensor<2x2xi32>, tensor<2x2xi32>)
^bb3:  // pred: ^bb1                                                                                                                                                                                                                                                                                               
  return %3, %4, %5 : tensor<i32>, tensor<2x2xi32>, tensor<2x2xi32>
}
```

This is some sort of loop construct that is being lowered into a control flow... The loop being split across multiple blocks this way makes it hard to do what should be the right solution here, which is move this entire thing onto the ~~host~~ device as a scalar computation....
So I think the best way forward here is to fix the lowering to use some structured control flow op, and then make that entire loop move into a single dispatch that is executed as scalar computations. I can do the latter. We can do something that can recognize control flow and convert it back to scf (Ben I think has an issue for this as well). But ideally we dont even lower it to this form.

**Comment by rsuderman** [comment]
That makes sense. This conversion happens during the TopLevelSCFToCFG conversion. I wonder if we could potentially push the conversion to occur later in the compilation?

**Comment by MaheshRavishankar** [comment]
> That makes sense. This conversion happens during the TopLevelSCFToCFG conversion. I wonder if we could potentially push the conversion to occur later in the compilation?

We should basically do that. But will require adapting the rest of the stack to handle this. It will be a better end state, but will need some work (maybe something to push on when everyone is back)

**Comment by stellaraccident** [comment]
We've been meaning to pipe clean this for a while. Would be a good task for someone to take up.

**Comment by jpienaar** [comment]
I'll take a look

**Comment by rsuderman** [comment]
I am going to see if I can plumb a fix through.

**Comment by jpienaar** [comment]
Thanks, and sorry for dropping the ball here.

**Comment by rsuderman** [comment]
Not sure what commit fixed it, but this is now fixed. Closing.
