### ISSUE TITLE
`FormScalarDispatches` generates illegal IR (dominate use issue)

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#14267]
FormScalarDispatches appears to construct some illegal IR during scalar dispatch formation.

Source IR:
https://gist.github.com/rsuderman/ed5a3d9565487c0c30941774f8f554f0

IR Immediately before failure:
https://gist.github.com/rsuderman/b19f54cbdeb0987bf03bb77b4737f07e

**Comment by rsuderman** [comment]
Appears to be related to degenerate `stablehlo` operations. Specifically 0-length tensors.

**Comment by allieculp** [comment]
@MaheshRavishankar @rsuderman I see #14269 linked here - is this the fix?

**Comment by rsuderman** [comment]
Fixed.
