### ISSUE TITLE
Adding support for scalable vectors to the Linalg vectorizer

### ISSUE THREAD

**Issue by banach-space** [iree-org/iree#14276]
[Implements #13334 ]

As per https://discourse.llvm.org/t/rfc-scalable-vectorisation-in-linalg/, we need to teach the Linalg vectoriser how to generated scalable vectors.

**Comment by banach-space** [comment]
Implemented by @dcaballe in https://reviews.llvm.org/D152599

**Comment by banach-space** [comment]
Extension to the vector type to unblock scalable vectorisation of `linalg.matmul`:
*  https://reviews.llvm.org/D153372
*   https://reviews.llvm.org/D153412

PSA on Discourse:  https://discourse.llvm.org/t/psa-vectortype-scalable-dimensions/71658/1

**Comment by allieculp** [comment]
@dcaballe Setting to 'in progress' with you as assignee. Please edit if needed!

**Comment by dcaballe** [comment]
@banach-space, I think we can claim that the core work is done, right?

**Comment by banach-space** [comment]
> @banach-space, I think we can claim that the core work is done, right?

Agreed. We can create a dedicated ticket to track the vectorisation of `linalg.matmul` -  If anything comes up :) (I've not checked yet)
