### ISSUE TITLE
getting "error : use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'" when building IREE from source

### ISSUE THREAD

**Issue by wynterr** [iree-org/iree#14273]
### What happened?

I'm building IREE from source and encounter this error.

### Steps to reproduce your issue

My configuration setting:
`cmake -G Ninja -B ../iree-build/ -S . \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DIREE_ENABLE_ASSERTIONS=ON \
    -DIREE_ENABLE_SPLIT_DWARF=ON \
    -DIREE_ENABLE_THIN_ARCHIVES=ON \
    -DCMAKE_C_COMPILER=clang-10 \
    -DCMAKE_CXX_COMPILER=clang++-10 \
    -DCMAKE_C_COMPILER_LAUNCHER=ccache \
    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
    -DIREE_ENABLE_LLD=ON`

### Version information

I'm using 

- CUDA 11.2
- Clang 10.0.0-4ubuntu1~18.04.2

### Additional context

Full error log:

[0/2] Re-checking globbed directories...
[1/784] Linking C static library runtime/src/iree/hal/local/loaders/libiree_hal_local_loaders_embedded_elf_loader.a
[2/784] Linking C static library runtime/src/iree/hal/local/loaders/libiree_hal_local_loaders_static_library_loader.a
[3/784] Linking C static library runtime/src/iree/hal/local/plugins/libiree_hal_local_plugins_embedded_elf_plugin.a
[4/784] Linking C static library runtime/src/iree/hal/local/loaders/libiree_hal_local_loaders_system_library_loader.a
[5/784] Linking C executable runtime/src/iree/hal/local/elf/elf_module_test_binary
[6/784] Building C object runtime/src/iree/hal/utils/CMakeFiles/iree_hal_utils_allocators.objects.dir/allocators.c.o
[7/784] Building C object runtime/src/iree/hal/local/plugins/CMakeFiles/iree_hal_local_plugins_system_library_plugin.objects.dir/system_library_plugin.c.o
[8/784] Building C object runtime/src/iree/hal/utils/CMakeFiles/iree_hal_utils_collective_batch.objects.dir/collective_batch.c.o
[9/784] Building C object runtime/src/iree/hal/local/plugins/registration/CMakeFiles/iree_hal_local_plugins_registration_registration.objects.dir/init.c.o
[10/784] Building C object runtime/src/iree/hal/local/plugins/CMakeFiles/iree_hal_local_plugins_static_plugin.objects.dir/static_plugin.c.o
[11/784] Linking C static library runtime/src/iree/hal/local/plugins/libiree_hal_local_plugins_system_library_plugin.a
[12/784] Linking C static library runtime/src/iree/hal/local/plugins/libiree_hal_local_plugins_static_plugin.a
[13/784] Linking C static library runtime/src/iree/hal/local/plugins/registration/libiree_hal_local_plugins_registration_registration.a
[14/784] Building C object runtime/src/iree/hal/utils/CMakeFiles/iree_hal_utils_debug_allocator.objects.dir/debug_allocator.c.o
[15/784] Linking C static library runtime/src/iree/hal/utils/libiree_hal_utils_debug_allocator.a
[16/784] Building C object runtime/src/iree/hal/utils/CMakeFiles/iree_hal_utils_buffer_transfer.objects.dir/buffer_transfer.c.o
[17/784] Building C object runtime/src/iree/hal/utils/CMakeFiles/iree_hal_utils_libmpi.objects.dir/libmpi.c.o
[18/784] Linking C static library runtime/src/iree/hal/utils/libiree_hal_utils_buffer_transfer.a
[19/784] Linking C static library runtime/src/iree/hal/utils/libiree_hal_utils_libmpi.a
[20/784] Building C object runtime/src/iree/hal/utils/CMakeFiles/iree_hal_utils_resource_set.objects.dir/resource_set.c.o
[21/784] Building C object runtime/src/iree/hal/utils/CMakeFiles/iree_hal_utils_caching_allocator.objects.dir/caching_allocator.c.o
[22/784] Building C object runtime/src/iree/hal/utils/CMakeFiles/iree_hal_utils_mpi_channel_provider.objects.dir/mpi_channel_provider.c.o
[23/784] Linking C static library runtime/src/iree/hal/utils/libiree_hal_utils_resource_set.a
[24/784] Building C object runtime/src/iree/hal/drivers/cuda/CMakeFiles/iree_hal_drivers_cuda_dynamic_symbols.objects.dir/dynamic_symbols.c.o
FAILED: runtime/src/iree/hal/drivers/cuda/CMakeFiles/iree_hal_drivers_cuda_dynamic_symbols.objects.dir/dynamic_symbols.c.o 
ccache /usr/bin/clang-10  -isystem /home/ubuntu/xxx/iree -isystem /home/ubuntu/xxx/iree-build -isystem /home/ubuntu/xxx/iree/runtime/src/iree/.. -isystem /home/ubuntu/xxx/iree-build/runtime/src/iree/.. -isystem /usr/local/cuda/include -isystem /home/ubuntu/xxx/iree/third_party/nccl -O2 -g   -gsplit-dwarf -ggnu-pubnames -fPIC -fvisibility=hidden -Werror -Wall -Wno-ambiguous-member-template -Wno-char-subscripts -Wno-extern-c-compat -Wno-gnu-alignof-expression -Wno-gnu-variable-sized-type-not-at-end -Wno-ignored-optimization-argument -Wno-invalid-offsetof -Wno-invalid-source-encoding -Wno-mismatched-tags -Wno-pointer-sign -Wno-reserved-user-defined-literal -Wno-return-type-c-linkage -Wno-self-assign-overloaded -Wno-sign-compare -Wno-signed-unsigned-wchar -Wno-strict-overflow -Wno-trigraphs -Wno-unknown-pragmas -Wno-unknown-warning-option -Wno-unused-command-line-argument -Wno-unused-const-variable -Wno-unused-function -Wno-unused-local-typedef -Wno-unused-private-field -Wno-user-defined-warnings -Wc++20-extensions -Wctad-maybe-unsupported -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wformat-security -Wgnu-redeclared-enum -Wimplicit-fallthrough -Winfinite-recursion -Wliteral-conversion -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wself-assign -Wstring-conversion -Wtautological-overlap-compare -Wthread-safety -Wthread-safety-beta -Wunused-comparison -Wvla -fno-omit-frame-pointer -fmacro-prefix-map=/home/ubuntu/xxx/iree=iree -pthread -MD -MT runtime/src/iree/hal/drivers/cuda/CMakeFiles/iree_hal_drivers_cuda_dynamic_symbols.objects.dir/dynamic_symbols.c.o -MF runtime/src/iree/hal/drivers/cuda/CMakeFiles/iree_hal_drivers_cuda_dynamic_symbols.objects.dir/dynamic_symbols.c.o.d -o runtime/src/iree/hal/drivers/cuda/CMakeFiles/iree_hal_drivers_cuda_dynamic_symbols.objects.dir/dynamic_symbols.c.o -c /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:9:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuGetErrorName, CUresult, const char**)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:10:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuGetErrorString, CUresult, const char**)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:11:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuCtxCreate, CUcontext*, unsigned int, CUdevice)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:12:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuCtxDestroy, CUcontext)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:13:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuDevicePrimaryCtxRetain, CUcontext*, CUdevice)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:14:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuDevicePrimaryCtxRelease, CUdevice)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:15:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuCtxSetCurrent, CUcontext)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:16:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuCtxPushCurrent, CUcontext)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:17:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuCtxPopCurrent, CUcontext*)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:18:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuDeviceGet, CUdevice*, int)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:19:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuDeviceGetCount, int*)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:20:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuDeviceGetName, char*, int, CUdevice)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:21:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuDeviceGetAttribute, int*, CUdevice_attribute, CUdevice)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:22:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuDeviceGetUuid, CUuuid*, CUdevice)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:23:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuEventCreate, CUevent*, unsigned int)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:24:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuEventDestroy, CUevent)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:25:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuEventElapsedTime, float*, CUevent, CUevent)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:26:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuEventQuery, CUevent)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
In file included from /home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:55:
/home/ubuntu/xxx/iree/runtime/src/iree/../iree/hal/drivers/cuda/dynamic_symbol_tables.h:27:1: error: use of undeclared identifier 'CU_GET_PROC_ADDRESS_DEFAULT'
CU_PFN_DECL(cuEventRecord, CUevent, CUstream)
^
/home/ubuntu/xxx/iree/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c:50:26: note: expanded from macro 'CU_PFN_DECL'
                         CU_GET_PROC_ADDRESS_DEFAULT),                \
                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[25/784] Linking C static library runtime/src/iree/hal/utils/libiree_hal_utils_caching_allocator.a
[26/784] Linking C static library runtime/src/iree/hal/utils/libiree_hal_utils_collective_batch.a
[27/784] Linking C static library runtime/src/iree/hal/utils/libiree_hal_utils_mpi_channel_provider.a
[28/784] Building C object runtime/src/iree/hal/utils/CMakeFiles/iree_hal_utils_deferred_command_buffer.objects.dir/deferred_command_buffer.c.o
[29/784] Building C object runtime/src/iree/hal/utils/CMakeFiles/iree_hal_utils_resource_set_benchmark.dir/resource_set_benchmark.c.o
[30/784] Building C object runtime/src/iree/hal/utils/CMakeFiles/iree_hal_utils_semaphore_base.objects.dir/semaphore_base.c.o
[31/784] Building CXX object runtime/src/iree/hal/utils/CMakeFiles/iree_hal_utils_libmpi_test.dir/libmpi_test.cc.o
[32/784] Building CXX object runtime/src/iree/hal/utils/CMakeFiles/iree_hal_utils_resource_set_test.dir/resource_set_test.cc.o
[33/784] Building CXX object runtime/src/iree/hal/utils/CMakeFiles/iree_hal_utils_semaphore_base_test.dir/semaphore_base_test.cc.o
ninja: build stopped: subcommand failed.

**Comment by stellaraccident** [comment]
I don't believe we ever supported CUDA 11.2. until recently, we did regularly build cuda 11.6. however, our minimums have been slowly creeping towards Ubuntu 20.04 and cuda 12.

I don't think the core team has the bandwidth to backport, but if you identify a fix that increases compatible with older versions, we can accept a patch.

Since you listed your cuda version, I assume you need to be building cuda support. However, if this was not your intent, cuda runtime support can be disabled with a CMake flag.

(Sorry)

**Comment by wynterr** [comment]
Oh, then I'll try with CUDA 11.6 and see how it works. 
Also I don't see a document that specifies the minimum version of required tools/dependencies. If there is one document I can find those minimum version information please point it out. Thanks a lot.

**Comment by allieculp** [comment]
@ScottTodd Is there any documentation to point to here? Just checking.
@wynterr Do you want to keep this open? Any update with CUDA 11.6?

**Comment by ScottTodd** [comment]
> @ScottTodd Is there any documentation to point to here? Just checking.

Sort of - it takes a bit of digging:

* https://openxla.github.io/iree/building-from-source/getting-started/#optional-components
* https://openxla.github.io/iree/guides/deployment-configurations/gpu-cuda-rocm/#prerequisites

We assume that targets that are enabled by default will build without extra effort.

We could add more version checking to https://github.com/openxla/iree/blob/main/build_tools/third_party/cuda/CMakeLists.txt and https://github.com/openxla/iree/blob/90499ddd1c2873a09156393585e8602722cdca8f/CMakeLists.txt#L177-L189

**Comment by wynterr** [comment]
> @ScottTodd Is there any documentation to point to here? Just checking. @wynterr Do you want to keep this open? Any update with CUDA 11.6?

Yeah, CUDA 11.6 works fine. We can close this.
Would suggest to show the prerequisites in the get-started document more straight-forward, or add more version checking.

**Comment by ScottTodd** [comment]
Filed https://github.com/openxla/iree/issues/14420 for version checking
