### ISSUE TITLE
[Regression][CUDA] Increased latency on TF BERT

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#14297]
### What happened?

From June 30 to July 1, latency on TF BERT increased on CUDA:

![image](https://github.com/openxla/iree/assets/5143063/3aee2a87-e001-4601-a5b1-635fd1409e5b)

### Steps to reproduce your issue

Download https://storage.googleapis.com/iree-model-artifacts/tensorflow/tf_models_2.12.0_1683544084/BERT_LARGE/batch_32/hlo.mlirbc

iree-compile --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80 </path/to/model.mlirbc> -o </path/to/model.vmfb>

iree-benchmark-module --module=</path/to/model.vmfb> --function=forward --input=32x384xi32=0 --input=32x384xi32=0 --device_allocator=caching --device=cuda://0

### What component(s) does this issue relate to?

Compiler, Runtime

**Comment by allieculp** [comment]
@julianwa @jpienaar Anyone to look at this regression?

**Comment by ScottTodd** [comment]
Given no action in almost a year (despite the release-blocker label), I'm going to close this regression as stale/obsolete.
