### ISSUE TITLE
`hal.buffer.load` fails when loading a`complex<f32>`

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#14319]
It appears that `hal.buffer.load` can fail when loading a `complex<f32>`. When correcting for the segmentation fault there are additional failures. We likely need to convert to an `i64` load earlier in the pipeline.

Input StableHLO:
https://gist.github.com/rsuderman/e3c9bdc6f6e26905f287b9b0db5a7853

IR Before failure:
https://gist.github.com/rsuderman/de681e1c33e506b437a64ee62da07004

**Comment by allieculp** [comment]
@rsuderman Is anyone working on this currently? Or P2?

**Comment by rsuderman** [comment]
Verified to be fixed.
