### ISSUE TITLE
`iree.runtime.system_api.load_vm_flatbuffer_file` should use the new VMModule.mmap function

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#14321]
Found this while working on a reproducer. It prints a warning (and is horribly inefficient).

**Comment by ScottTodd** [comment]
Related: I noticed a bunch of our Colab notebooks that use `iree_rt.VmModule.from_flatbuffer()` (usually after in-memory `compile_str` or `compile_file` usage) print warnings. I have a local change to flip one of those over to `copy_buffer()`.

Unrelated: I'm also considering standardizing our imports to `from iree import compiler as ireec` and `from iree import runtime as ireert`. We have various samples using imports like `from iree.compiler import compile_str` and I think consistent namespacing would help with forking samples and grepping the codebase.

**Comment by stellaraccident** [comment]
Thanks - this is why I added the warning. I know it is noisy, but the old behavior is really suboptimal and needs updating. At least it is correct now, though (won't run mis-aligned).
