### ISSUE TITLE
performance redundant of some flow.tensor.splat and eventually memset(in cuda)

### ISSUE THREAD

**Issue by chongxing** [iree-org/iree#14397]
### Request description

There is flow.tensor.splat for pad or other reduction op. It is used to initialize the output buffer and its value. 
The splat will be lowered to fill_buffer, and eventually lowered to memset (in cuda).

have we thought of removing this memset? The output buffer could be initialized at the next 'real' kernel. 
For the following case, initialize the output buffer inside pad kernel.

```
func.func @pad_conv2d() {
  %input = util.unfoldable_constant dense<1.1> : tensor<1x16x16x3xf32>
  %weight0 = util.unfoldable_constant dense<1.2> : tensor<3x3x3x3xf32>
  %zero0 = util.unfoldable_constant dense<0.0> : tensor<f32>

  %652 = "mhlo.pad"(%input, %zero0) {edge_padding_high = dense<[0, 1, 1, 0]> : tensor<4xi64>, edge_padding_low = dense<[0, 1, 1, 0]> : tensor<4xi64>, interior_padding = dense<0> : tensor<4xi64>} : (tensor<1x16x16x3xf32>, tensor<f32>) -> tensor<1x18x18x3xf32>
  %653 = "mhlo.convolution"(%652, %weight0) {batch_group_count = 1 : i64, dimension_numbers = #mhlo.conv<raw input_batch_dimension = 0, input_feature_dimension = 3, input_spatial_dimensions = [1, 2], kernel_input_feature_dimension = 2, kernel_output_feature_dimension = 3, kernel_spatial_dimensions = [0, 1], output_batch_dimension = 0, output_feature_dimension = 3, output_spatial_dimensions = [1, 2]>, feature_group_count = 1 : i64, padding = dense<0> : tensor<2x2xi64>, rhs_dilation = dense<1> : tensor<2xi64>, window_strides = dense<2> : tensor<2xi64>} : (tensor<1x18x18x3xf32>, tensor<3x3x3x3xf32>) -> tensor<1x8x8x3xf32>
  check.expect_almost_eq_const(%653, dense<[[
      [[15.84, 15.84, 15.84],[23.76, 23.76, 23.76],[23.76, 23.76, 23.76],[23.76, 23.76, 23.76],[23.76, 23.76, 23.76],[23.76, 23.76, 23.76],[23.76, 23.76, 23.76],[23.76, 23.76, 23.76]],
      [[23.76, 23.76, 23.76],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64]],
      [[23.76, 23.76, 23.76],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64]],
      [[23.76, 23.76, 23.76],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64]],
      [[23.76, 23.76, 23.76],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64]],
      [[23.76, 23.76, 23.76],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64]],
      [[23.76, 23.76, 23.76],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64]],
      [[23.76, 23.76, 23.76],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64],[35.64, 35.64, 35.64]]
  ]]> : tensor<1x8x8x3xf32>) : tensor<1x8x8x3xf32>
  return
}
```

IR after FormDispatchWorkgroups

```
// -----// IR Dump After FormDispatchWorkgroups (iree-flow-form-dispatch-workgroups) //----- //
func.func private @_pad_conv2d() {
  %cst = arith.constant dense<"0xA4707D41A4707D41A4707D417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE417B14BE415C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E427B14BE417B14BE417B14BE415C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E427B14BE417B14BE417B14BE415C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E427B14BE417B14BE417B14BE415C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E427B14BE417B14BE417B14BE415C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E427B14BE417B14BE417B14BE415C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E427B14BE417B14BE417B14BE415C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E425C8F0E42"> : tensor<1x8x8x3xf32>
  %cst_0 = arith.constant dense<0.000000e+00> : tensor<f32>
  %cst_1 = arith.constant dense<1.200000e+00> : tensor<3x3x3x3xf32>
  %cst_2 = arith.constant dense<1.100000e+00> : tensor<1x16x16x3xf32>
  %0 = util.optimization_barrier %cst_2 : tensor<1x16x16x3xf32>
  %1 = util.optimization_barrier %cst_1 : tensor<3x3x3x3xf32>
  %2 = util.optimization_barrier %cst_0 : tensor<f32>
  %3 = flow.tensor.load %2 : tensor<f32>
  %4 = flow.tensor.splat %3 : tensor<1x18x18x3xf32>
  %5 = flow.tensor.reshape %0 : tensor<1x16x16x3xf32> -> tensor<16x16x3xf32>
  %6 = flow.dispatch.workgroups(%5, %4) : (tensor<16x16x3xf32>, tensor<1x18x18x3xf32>) -> %4 =
      (%arg0: !flow.dispatch.tensor<readonly:tensor<16x16x3xf32>>, %arg1: !flow.dispatch.tensor<readwrite:tensor<1x18x18x3xf32>>) {
    %8 = flow.dispatch.tensor.load %arg0, offsets = [0, 0, 0], sizes = [16, 16, 3], strides = [1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<16x16x3xf32>> -> tensor<16x16x3xf32>
    flow.dispatch.tensor.store %8, %arg1, offsets = [0, 1, 1, 0], sizes = [1, 16, 16, 3], strides = [1, 1, 1, 1] : tensor<16x16x3xf32> -> !flow.dispatch.tensor<readwrite:tensor<1x18x18x3xf32>>
    flow.return
  } count() -> (index, index, index) {
    %x, %y, %z = flow.dispatch.workgroup_count_from_slice 
    flow.return %x, %y, %z : index, index, index
  }
  %7 = flow.dispatch.workgroups(%6, %1) : (tensor<1x18x18x3xf32>, tensor<3x3x3x3xf32>) -> tensor<1x8x8x3xf32> =
      (%arg0: !flow.dispatch.tensor<readonly:tensor<1x18x18x3xf32>>, %arg1: !flow.dispatch.tensor<readonly:tensor<3x3x3x3xf32>>, %arg2: !flow.dispatch.tensor<writeonly:tensor<1x8x8x3xf32>>) {
    %cst_3 = arith.constant 0.000000e+00 : f32
    %8 = flow.dispatch.tensor.load %arg0, offsets = [0, 0, 0, 0], sizes = [1, 18, 18, 3], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<1x18x18x3xf32>> -> tensor<1x18x18x3xf32>
    %9 = flow.dispatch.tensor.load %arg1, offsets = [0, 0, 0, 0], sizes = [3, 3, 3, 3], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<3x3x3x3xf32>> -> tensor<3x3x3x3xf32>
    %10 = tensor.empty() : tensor<1x8x8x3xf32>
    %11 = linalg.fill ins(%cst_3 : f32) outs(%10 : tensor<1x8x8x3xf32>) -> tensor<1x8x8x3xf32>
    %12 = linalg.conv_2d_nhwc_hwcf {dilations = dense<1> : tensor<2xi64>, strides = dense<2> : tensor<2xi64>} ins(%8, %9 : tensor<1x18x18x3xf32>, tensor<3x3x3x3xf32>) outs(%11 : tensor<1x8x8x3xf32>) -> tensor<1x8x8x3xf32>
    flow.dispatch.tensor.store %12, %arg2, offsets = [0, 0, 0, 0], sizes = [1, 8, 8, 3], strides = [1, 1, 1, 1] : tensor<1x8x8x3xf32> -> !flow.dispatch.tensor<writeonly:tensor<1x8x8x3xf32>>
    flow.return
  } count() -> (index, index, index) {
    %x, %y, %z = flow.dispatch.workgroup_count_from_slice 
    flow.return %x, %y, %z : index, index, index
  }
  check.expect_almost_eq(%7, %cst) : tensor<1x8x8x3xf32>
  return
}

```

### What component(s) does this issue relate to?

Compiler, Runtime

**Comment by benvanik** [comment]
Yep, definitely should be fixed! There are some open issues around removing these fills - in most programs there should never be the need for a fill (or fills should be partial) and any place we see them popping up usually indicates a place where we could have avoided them. #6972 is tracking eliminating subranges of partial fills (not what you're seeing above) - #11049 and #13514 are two I recall that are more pad-specific and match this case. `--iree-flow-enable-fuse-padding-into-linalg-consumer-op` is a compiler flag you can try (mentioned in #11049) but I'm not sure of other issues that may come around with it. If either of those issues look interesting you can post some more examples of what you're seeing there!

**Comment by chongxing** [comment]
This is an example of splat. I meet with this in another softmax case (it's in a model, and not yet extracted as a small case).

Generally, it look likes for any reduction kernel, there will be one splat before the real kernel, and it would be lowered to memset eventually. 

One more idea is to make these splat constants as read-only value (that will be copy into memory during init()). But I find there is one check here, this would prevent from making these splat value init once? I would try to simply remove this check, still i doesn't work. I have't further debug into it yet.
Thanks if any more suggestions

// Returns true if |value| is worth outlining (large, etc).
static bool isOutlinableValue(Attribute value) {
  if (auto elementsAttr = llvm::dyn_cast<DenseElementsAttr>(value)) {
    // Don't outline splats - we want those fused.
    return !elementsAttr.isSplat();
  }
  return false;
}

**Comment by benvanik** [comment]
Someone more familiar with the codegen side will have to say, but depending on how the reduction is implemented it can sometimes require a pre-zeroing. There's ways around this (or ways of making it zero much less) but I'm not sure any are implemented yet.

The issue there is if you want to parallelize something like this:
```
int sum = 0;
for (int i = 0; i < count; ++i) sum += element[i];
```
With more complex reduction schemes like tree reductions/input-aligned reductions/subgroup-level reductions you can avoid this, but it's situational. Ideally we'd never need to zero the output prior to a reduction and in-place reductions (that accumulate/etc into the output storage directly) are only when the producer is expensive.

So far these haven't been on the perf critical path so it hasn't got much investment. It still offends the sensibilities and would be great to avoid for many reasons but out of curiosity are you seeing a model where the fills take non-trivial amounts of time?

**Comment by MaheshRavishankar** [comment]
The issue in the example is about pad handling. There are two options w.r.t pad
1) You fuse pad with a consumer (in this case convolution). That has the downside that the convolution codegen itself gets complicated, but it does help in some cases.
2) In a full program you have the option of fusing pad with the producer. Thats always cheaper.

Both of these options havent really been fully realized on all backends. The SPIR-V side has support for fusing pad with consumer. A few months ago I was focusing of trying to make the CPU side work with it, but I couldnt push it too far. I documented the state I left with here https://github.com/openxla/iree/issues/13514#issue-1703132539



> This is an example of splat. I meet with this in another softmax case (it's in a model, and not yet extracted as a small case).
> 
> Generally, it look likes for any reduction kernel, there will be one splat before the real kernel, and it would be lowered to memset eventually.

That shouldnt be happening. We typically try to fuse the splat with the following reduction, but that has a tendency to regress periodically. If you have a repro that would be good to look into.

**Comment by chongxing** [comment]
> So far these haven't been on the perf critical path so it hasn't got much investment. It still offends the sensibilities and would be great to avoid for many reasons but out of curiosity are you seeing a model where the fills take non-trivial amounts of time?

It's noticeable. For more accurate consuming time percentage, I would have a try to see. 
You know, memset operation can execute parallel with kernel in gpu, in-case-of multi-cuda stream environment, it's not easy to measure the perf impact.
