### ISSUE TITLE
Add CUDA Toolkit version checking to CMake build

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#14420]
As reported on https://github.com/openxla/iree/issues/14273, we enable the CUDA HAL target if we find _any_ CUDA Toolkit, which can lead to compilation errors at build time if the toolkit version is older than what we support.

If the detected CUDA Toolkit is unsupported, we should either

* emit an error at configure time
* gracefully degrade to not enabling the CUDA HAL target by default
* ignore the detected CUDA Toolkit and download our own version

We have several different detection / auto-install mechanisms, so there's some nuance. Some ideas:

* If an explicit path is set by the user, such as via `-DCUDAToolkit_ROOT=/some/path`, and the version is unsupported, we should emit an error
* If an explicit path is _not set_, try to set a minimum version in `find_package()`, with "required" false
  * If no version is found that satisfies that property, install our own version

## References

https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html

https://github.com/openxla/iree/blob/main/build_tools/third_party/cuda/CMakeLists.txt

https://github.com/openxla/iree/blob/90499ddd1c2873a09156393585e8602722cdca8f/CMakeLists.txt#L177-L189

**Comment by allieculp** [comment]
@ScottTodd Feels like a P1? Do we have an owner yet?

**Comment by ScottTodd** [comment]
P1/P2, depends on how many people encounter this. Installing recent versions of SDKs prior to using a project is fairly normal, but it would certainly be nice to have a more clear failure mode when an unsupported version is used.

**Comment by ScottTodd** [comment]
This is fixed by https://github.com/openxla/iree/pull/16142
