### ISSUE TITLE
`const-expr-hoising` failure: 'util.global.load' op global type mismatch; global "hoisted" is '!stream.resource<constant>' but load is 'index'

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#14437]
Testcase: [b.mlir](https://gist.github.com/bjacob/024f7ae8424cbefad94f9e0066d08586#file-b-mlir). (minimized from https://github.com/nod-ai/SHARK/issues/1589)

Repro:
```
tools/iree-compile /tmp/b.mlir --iree-hal-target-backends=llvm-cpu --iree-opt-const-expr-hoisting -o /tmp/a.vmfb
```

[Log with `print-ir-after-all`](https://gist.githubusercontent.com/bjacob/024f7ae8424cbefad94f9e0066d08586/raw/01a5815eb12b1140281a0e7863b1b0452ea8620a/log)

**Comment by bjacob** [comment]
Less-minimized testcase / closer error message to the one I get on the e2e workload: https://github.com/openxla/iree/issues/14439

**Comment by benvanik** [comment]
I think this has been fixed (can't repro at head).
