### ISSUE TITLE
Unexpected results for int4

### ISSUE THREAD

**Issue by jinchen62** [iree-org/iree#14481]
### What happened?

Tested two simple IR with the only difference on int4 and int8. They are supposed to have same output, but the int4 gave weird results.

int4:
> #map = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
module {
  func.func @forward() -> tensor<8x4x2xf32> {
    %cst = arith.constant dense<[[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]]> : tensor<8x8xi4>
    %expanded_4 = tensor.expand_shape %cst [[0], [1, 2]] : tensor<8x8xi4> into tensor<8x4x2xi4>
    %0 = tensor.empty() : tensor<8x4x2xf32>
    %5 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded_4 : tensor<8x4x2xi4>) outs(%0 : tensor<8x4x2xf32>) {
    ^bb0(%in: i4, %out: f32):
      %6 = arith.extui %in : i4 to i32
      %7 = arith.uitofp %6 : i32 to f32
      linalg.yield %7 : f32
    } -> tensor<8x4x2xf32>
    return %5 : tensor<8x4x2xf32>
  }
}

output:
> 8x4x2xf32=[[0 1][2 3][8 9][10 11]][[0 1][2 3][8 9][10 11]][[0 1][2 3][8 9][10 11]][[0 1][2 3][8 9][10 11]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]]

int8:
> #map = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
module {
  func.func @forward() -> tensor<8x4x2xf32> {
    %cst = arith.constant dense<[[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]]> : tensor<8x8xi8>
    %expanded_4 = tensor.expand_shape %cst [[0], [1, 2]] : tensor<8x8xi8> into tensor<8x4x2xi8>
    %0 = tensor.empty() : tensor<8x4x2xf32>
    %5 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded_4 : tensor<8x4x2xi8>) outs(%0 : tensor<8x4x2xf32>) {
    ^bb0(%in: i8, %out: f32):
      %6 = arith.extui %in : i8 to i32
      %7 = arith.uitofp %6 : i32 to f32
      linalg.yield %7 : f32
    } -> tensor<8x4x2xf32>
    return %5 : tensor<8x4x2xf32>
  }
}

output:
> 8x4x2xf32=[[0 1][2 3][4 5][6 7]][[8 9][10 11][12 13][14 15]][[0 1][2 3][4 5][6 7]][[8 9][10 11][12 13][14 15]][[0 1][2 3][4 5][6 7]][[8 9][10 11][12 13][14 15]][[0 1][2 3][4 5][6 7]][[8 9][10 11][12 13][14 15]]

### Steps to reproduce your issue

1. iree-compile --iree-hal-target-backends=llvm-cpu int4.mlir -o int4.vmfb --iree-flow-inline-constants-max-byte-length=0
2. iree-run-module --device=local-task --module=int4.vmfb --function=forward
3. same steps for int8.mlir

**Comment by jinchen62** [comment]
cc: @qedawkins

**Comment by benvanik** [comment]
I'll take a look!

**Comment by benvanik** [comment]
Whoops - I just spent too long trying to figure this out without having really processed what the outputs above were showing 🤦 

I think we're generating bad LLVM IR that doesn't take the sub-byte offsets into account.
Starting from the end the final LLVM output unrolls everything and we can see the offsets being wrong with it going in 4xi4 chunks but advancing the byte offset 4 at a time - it should be +=2 (4*4bits=16 bits/8=2bytes):
```llvm
  %29 = or i64 %10, 16, !dbg !82
  %30 = getelementptr i4, ptr @__constant_64xi4, i64 %29, !dbg !82
  %31 = load <4 x i4>, ptr %30, align 16, !dbg !82
  %32 = uitofp <4 x i4> %31 to <4 x float>, !dbg !83
  %33 = getelementptr float, ptr %4, i64 16, !dbg !82
  store <4 x float> %32, ptr %33, align 64, !dbg !82
  %34 = or i64 %10, 20, !dbg !82
  %35 = getelementptr i4, ptr @__constant_64xi4, i64 %34, !dbg !82
  %36 = load <4 x i4>, ptr %35, align 4, !dbg !82
  %37 = uitofp <4 x i4> %36 to <4 x float>, !dbg !83
  %38 = getelementptr float, ptr %4, i64 20, !dbg !82
  store <4 x float> %37, ptr %38, align 16, !dbg !82
```

Here's the program before translation:
```mlir
#executable_target_embedded_elf_x86_64_ = #hal.executable.target<"llvm-cpu", "embedded-elf-x86_64", {cpu = "generic", cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf", ukernels = false}>
#map = affine_map<(d0) -> (d0)>
#pipeline_layout = #hal.pipeline.layout<push_constants = 0, sets = [<0, bindings = [<0, storage_buffer>]>]>
#device_target_llvm_cpu = #hal.device.target<"llvm-cpu", {executable_targets = [#executable_target_embedded_elf_x86_64_]}>
module attributes {hal.device.targets = [#device_target_llvm_cpu]} {
  hal.executable private @forward_dispatch_0 {
    hal.executable.variant public @embedded_elf_x86_64, target = #executable_target_embedded_elf_x86_64_ {
      hal.executable.export public @forward_dispatch_0_generic_64_i4xf32 ordinal(0) layout(#pipeline_layout) {
      ^bb0(%arg0: !hal.device):
        %x, %y, %z = flow.dispatch.workgroup_count_from_slice 
        hal.return %x, %y, %z : index, index, index
      }
      builtin.module {
        func.func @forward_dispatch_0_generic_64_i4xf32() {
          %c0 = arith.constant 0 : index
          %cst = arith.constant dense<[0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1]> : tensor<64xi4>
          %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) : !flow.dispatch.tensor<writeonly:tensor<64xf32>>
          %1 = tensor.empty() : tensor<64xf32>
          %2 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel"]} ins(%cst : tensor<64xi4>) outs(%1 : tensor<64xf32>) {
          ^bb0(%in: i4, %out: f32):
            %3 = arith.extui %in : i4 to i32
            %4 = arith.uitofp %3 : i32 to f32
            linalg.yield %4 : f32
          } -> tensor<64xf32>
          flow.dispatch.tensor.store %2, %0, offsets = [0], sizes = [64], strides = [1] : tensor<64xf32> -> !flow.dispatch.tensor<writeonly:tensor<64xf32>>
          return
        }
      }
    }
  }
  func.func @forward() -> !hal.buffer_view attributes {iree.abi.stub} {
    %c0 = arith.constant 0 : index
    %c256 = arith.constant 256 : index
    %0 = stream.resource.alloc uninitialized : !stream.resource<external>{%c256}
    %1 = stream.cmd.execute with(%0 as %arg0: !stream.resource<external>{%c256}) {
      stream.cmd.dispatch @forward_dispatch_0::@embedded_elf_x86_64::@forward_dispatch_0_generic_64_i4xf32 {
        wo %arg0[%c0 for %c256] : !stream.resource<external>{%c256}
      } attributes {hal.interface.bindings = [#hal.interface.binding<0, 0>]}
    } => !stream.timepoint
    %2 = stream.timepoint.await %1 => %0 : !stream.resource<external>{%c256}
    %3 = stream.tensor.export %2 : tensor<8x4x2xf32> in !stream.resource<external>{%c256} -> !hal.buffer_view
    return %3 : !hal.buffer_view
  }
}
```

and by the time we hit the end of the LLVM dialect it's got that advance-by-4-and-use-that-as-a-byte-offset issue:
```mlir
  hal.executable private @forward_dispatch_0 {
    hal.executable.variant public @embedded_elf_x86_64, target = #executable_target_embedded_elf_x86_64_ {
      hal.executable.export public @forward_dispatch_0_generic_64_i4xf32 ordinal(0) layout(#pipeline_layout) attributes {translation_info = #translation} {
      ^bb0(%arg0: !hal.device):
        %c1 = arith.constant 1 : index
        hal.return %c1, %c1, %c1 : index, index, index
      }
      builtin.module attributes {llvm.data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", llvm.target_triple = "x86_64-unknown-unknown-eabi-elf"} {
        llvm.mlir.global private constant @__constant_64xi4(dense<[0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1]> : tensor<64xi4>) {addr_space = 0 : i32, sym_visibility = "private"} : !llvm.array<64 x i4>
        llvm.func @forward_dispatch_0_generic_64_i4xf32(%arg0: !llvm.ptr {llvm.align = 16 : i64, llvm.noalias}, %arg1: !llvm.ptr {llvm.align = 16 : i64, llvm.noalias}, %arg2: !llvm.ptr {llvm.align = 16 : i64, llvm.noalias}) -> i32 {
          %0 = llvm.mlir.constant(0 : i32) : i32
          %1 = llvm.mlir.constant(63 : index) : i64
          %2 = llvm.mlir.constant(4 : index) : i64
          %3 = llvm.mlir.constant(64 : index) : i64
          %4 = llvm.mlir.constant(0 : index) : i64
          %5 = llvm.mlir.addressof @__constant_64xi4 : !llvm.ptr
          %6 = llvm.getelementptr %5[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.array<64 x i4>
          %7 = llvm.load %arg1 : !llvm.ptr -> !llvm.struct<"iree_hal_executable_dispatch_state_v0_t", (i32, i32, i16, i16, i32, i32, i16, i8, i8, ptr, ptr, ptr)>
          %8 = llvm.extractvalue %7[10] : !llvm.struct<"iree_hal_executable_dispatch_state_v0_t", (i32, i32, i16, i16, i32, i32, i16, i8, i8, ptr, ptr, ptr)> 
          %9 = llvm.load %8 : !llvm.ptr -> !llvm.ptr
          %10 = llvm.ptrtoint %9 : !llvm.ptr to i64
          %11 = llvm.and %10, %1  : i64
          %12 = llvm.icmp "eq" %11, %4 : i64
          "llvm.intr.assume"(%12) : (i1) -> ()
          %13 = llvm.load %arg2 : !llvm.ptr -> !llvm.struct<"iree_hal_executable_workgroup_state_v0_t", (i32, i32, i16, i16, i32, ptr, i32)>
          %14 = llvm.extractvalue %13[0] : !llvm.struct<"iree_hal_executable_workgroup_state_v0_t", (i32, i32, i16, i16, i32, ptr, i32)> 
          %15 = llvm.zext %14 : i32 to i64
          %16 = llvm.mul %15, %3  : i64
          llvm.br ^bb1(%4 : i64)
        ^bb1(%17: i64):  // 2 preds: ^bb0, ^bb2
          %18 = llvm.icmp "slt" %17, %3 : i64
          llvm.cond_br %18, ^bb2, ^bb3
        ^bb2:  // pred: ^bb1
          %19 = llvm.add %17, %16  : i64
          %20 = llvm.getelementptr %6[%19] : (!llvm.ptr, i64) -> !llvm.ptr, i4
          %21 = llvm.load %20 {alignment = 1 : i64} : !llvm.ptr -> vector<4xi4>
          %22 = llvm.zext %21 : vector<4xi4> to vector<4xi32>
          %23 = llvm.uitofp %22 : vector<4xi32> to vector<4xf32>
          %24 = llvm.getelementptr %9[%17] : (!llvm.ptr, i64) -> !llvm.ptr, f32
          llvm.store %23, %24 {alignment = 4 : i64} : vector<4xf32>, !llvm.ptr
          %25 = llvm.add %17, %2  : i64
          llvm.br ^bb1(%25 : i64)
        ^bb3:  // pred: ^bb1
          llvm.return %0 : i32
        }
      }
    }
  }
```

This being the suspect part:
```mlir
          %19 = llvm.add %17, %16  : i64
          %20 = llvm.getelementptr %6[%19] : (!llvm.ptr, i64) -> !llvm.ptr, i4
          %21 = llvm.load %20 {alignment = 1 : i64} : !llvm.ptr -> vector<4xi4>
```
%17 is element index (+=4 each loop) but the load is not dividing by 2 first (2 elements per byte). This is why the output jumps from 0,1,2,3 (first 4xi4) to 8,9,10,11 (third 4xi4), as it's skipping the 2 bytes containing 4,5,6,7:
```
8x4x2xf32=[[0 1][2 3][8 9][10 11]][[0 1][2 3][8 9][10 11]][[0 1][2 3][8 9][10 11]][[0 1][2 3][8 9][10 11]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]]
```
After that it runs off the end and I'd expect this to trigger ASAN violations (if we weren't padding out things) but I didn't try that.

/cc @MaheshRavishankar / @dcaballe / @hanhanW know anything about the state of sub-byte addressing in LLVM CPU? Supported at all or something particular about this case not playing well?

**Comment by jinchen62** [comment]
@benvanik Thanks for looking into it. FYI we also got the same output on vulkan backend.

The commands for vulkan:
1. iree-compile --iree-hal-target-backends=vulkan --iree-vulkan-target-triple=rdna2-unknown-unknown int4.mlir -o int4.vmfb --iree-flow-inline-constants-max-byte-length=0
2. iree-run-module --device=vulkan --module=int4.vmfb --function=forward

**Comment by benvanik** [comment]
Ah yeah nice the `-iree-flow-inline-constants-max-byte-length=0` is load bearing there - I had to futz with the IR to add a util.optimization_barrier on the constant to prevent it from getting inlined and dying in SPIR-V codegen - that'll be good to fix at some point!

**Comment by hanhanW** [comment]
We've developed upstream patterns to handle subtype load. Vivian had a draft commit integrating it into CPU backend, but it's not sent out for review before her vacation. It should work with that commit, and we're waiting for her back, likely would be next week.

**Comment by jinchen62** [comment]
@hanhanW Vivian won't be back until 8/7, can we unblock it without her?

**Comment by stellaraccident** [comment]
@hanhanW we seem very close to the end here, and with Vivian out for a while more, would you at all be able to help us pull the final threads of this?

**Comment by MaheshRavishankar** [comment]
#14488 should fix this. Currently this fails on

```
module {
  memref.global "private" constant @__constant_64xi4 : memref<64xi4> = dense<[0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, \
-4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1]>
  func.func @forward_dispatch_0_generic_64_i4xf32() {
    %c4 = arith.constant 4 : index
    %c64 = arith.constant 64 : index
    %c0 = arith.constant 0 : index
    %0 = memref.get_global @__constant_64xi4 : memref<64xi4>
    %1 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) : memref<64xf32>
    memref.assume_alignment %1, 64 : memref<64xf32>
    %workgroup_id_x = hal.interface.workgroup.id[0] : index
    %2 = affine.apply affine_map<()[s0] -> (s0 * 64)>()[%workgroup_id_x]
    cf.br ^bb1(%c0 : index)
  ^bb1(%3: index):  // 2 preds: ^bb0, ^bb2                                                                                                                                     
    %4 = arith.cmpi slt, %3, %c64 : index
    cf.cond_br %4, ^bb2, ^bb3
  ^bb2:  // pred: ^bb1                                                                                                                                                         
    %5 = arith.addi %3, %2 : index
    %6 = vector.load %0[%5] : memref<64xi4>, vector<4xi4>
    %7 = arith.extui %6 : vector<4xi4> to vector<4xi32>
    %8 = arith.uitofp %7 : vector<4xi32> to vector<4xf32>
    vector.store %8, %1[%3] : memref<64xf32>, vector<4xf32>
    %9 = arith.addi %3, %c4 : index
    cf.br ^bb1(%9 : index)
  ^bb3:  // pred: ^bb1                                                                                                                                                         
    return
  }
}
```

This is currently failing with PR #14488 with 
```
pass_repro.mlir:18:10: error: failed to legalize operation 'vector.load' that was explicitly marked illegal
    %6 = vector.load %0[%5] : memref<64xi4>, vector<4xi4>
         ^
pass_repro.mlir:18:10: note: see current operation: %10 = "vector.load"(%3, %9) : (memref<64xi4>, index) -> vector<4xi4>
ImplicitTypeIDRegistry::lookupOrInsert(mlir::detail::PreservedAnalyses::AllAnalysesType)
```

**Comment by hanhanW** [comment]
It is quite tricky because of type converter things. We missed the type conversion for memref types, and I pushed a fix to the branch. I have the pass working but we will need to add a pattern for `%0 = memref.get_global @__constant_64xi4 : memref<64xi4>`. I'm able to generate below snippet if we move `%0` to one of function arguments. Probably just need a simple fix about adding simple replacement pattern (or type converter config) for `memref.get_global`.

```mlir
#map = affine_map<()[s0] -> (s0 * 64)>
#map1 = affine_map<()[s0, s1] -> ((s0 * s1) floordiv 2)>
#map2 = affine_map<()[s0] -> (s0 floordiv 2)>
module {
  memref.global "private" constant @__constant_64xi4 : memref<64xi4> = dense<[0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, -8, -7, -6, -5, -4, -3, -2, -1]>
  func.func @forward_dispatch_0_generic_64_i4xf32(%arg0: memref<64xi8>) {
    %c4 = arith.constant 4 : index
    %c64 = arith.constant 64 : index
    %c0 = arith.constant 0 : index
    %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) : memref<64xf32>
    memref.assume_alignment %0, 64 : memref<64xf32>
    %workgroup_id_x = hal.interface.workgroup.id[0] : index
    %1 = affine.apply #map()[%workgroup_id_x]
    cf.br ^bb1(%c0 : index)
  ^bb1(%2: index):  // 2 preds: ^bb0, ^bb2
    %3 = arith.cmpi slt, %2, %c64 : index
    cf.cond_br %3, ^bb2, ^bb3
  ^bb2:  // pred: ^bb1
    %4 = arith.addi %2, %1 : index
    %base_buffer, %offset, %sizes, %strides = memref.extract_strided_metadata %arg0 : memref<64xi8> -> memref<i8>, index, index, index
    %5 = affine.apply #map1()[%4, %strides]
    %6 = affine.apply #map2()[%offset]
    %reinterpret_cast = memref.reinterpret_cast %base_buffer to offset: [%6], sizes: [%sizes], strides: [%strides] : memref<i8> to memref<64xi8, strided<[1], offset: ?>>
    %7 = vector.load %reinterpret_cast[%5] : memref<64xi8, strided<[1], offset: ?>>, vector<2xi8>
    %8 = vector.bitcast %7 : vector<2xi8> to vector<4xi4>
    %9 = arith.extui %8 : vector<4xi4> to vector<4xi32>
    %10 = arith.uitofp %9 : vector<4xi32> to vector<4xf32>
    vector.store %10, %0[%2] : memref<64xf32>, vector<4xf32>
    %11 = arith.addi %2, %c4 : index
    cf.br ^bb1(%11 : index)
  ^bb3:  // pred: ^bb1
    return
  }
}
```

**Comment by jinchen62** [comment]
@hanhanW Hi, I wonder if `%c4` is supposed to be `%c2` cuz Ben was saying it should advance the byte offset 2 for int4.

**Comment by benvanik** [comment]
I think
```
#map1 = affine_map<()[s0, s1] -> ((s0 * s1) floordiv 2)>
#map2 = affine_map<()[s0] -> (s0 floordiv 2)>
```
may help here - that was missing in mine 🤞

**Comment by hanhanW** [comment]
It does not really make sense that we have small constants in int4 types. To support that, we can add a pattern to rewrite it. We will need to construct the raw_data in packed layout, because the MLIR internal implementation is storing each 4 bit in a 8-bit char separately. I updated the test case to use `util.unfoldable_constant` for the test case which matches practice scenario better.

**Comment by qedawkins** [comment]
> It does not really make sense that we have small constants in int4 types. To support that, we can add a pattern to rewrite it. We will need to construct the raw_data in packed layout, because the MLIR internal implementation is storing each 4 bit in a 8-bit char separately. I updated the test case to use `util.unfoldable_constant` for the test case which matches practice scenario better.

I think I should clarify that the shapes (and values) are synthetic here. The reason it's so small is primarily so that it's easier to look at the values directly/pass the IR around (hence `-iree-flow-inline-constants-max-byte-length=0`). In actual models we don't see small int4 constants like you said. Apologies for the confusion it might be causing here.

**Comment by MaheshRavishankar** [comment]
> > It does not really make sense that we have small constants in int4 types. To support that, we can add a pattern to rewrite it. We will need to construct the raw_data in packed layout, because the MLIR internal implementation is storing each 4 bit in a 8-bit char separately. I updated the test case to use `util.unfoldable_constant` for the test case which matches practice scenario better.
> 
> I think I should clarify that the shapes (and values) are synthetic here. The reason it's so small is primarily so that it's easier to look at the values directly/pass the IR around (hence `-iree-flow-inline-constants-max-byte-length=0`). In actual models we don't see small int4 constants like you said. Apologies for the confusion it might be causing here.

Thats fine. There were real issues. That was fixed by your repro. Fixing constants can also be done if needed (using what Ben did on the vmfb serialization front). We can do that if needed.

**Comment by benvanik** [comment]
IREE::Util::SerializableAttrInterface will let you serialize all kinds of attributes
