### ISSUE TITLE
IREE GCC build warnings

### ISSUE THREAD

**Issue by hcindyl** [iree-org/iree#14507]
IREE GCC build has fewer warning flags defined/silenced in iree_macros.cmake compared with clang
https://github.com/openxla/iree/blob/72995e1bc2b34755dbcddc49ebbd81c8ce7736ea/build_tools/cmake/iree_copts.cmake#L209-L218

As a result GCC build has a lot of warnings
https://github.com/openxla/iree/actions/runs/5687030636/job/15414819274

- [x] /work/third_party/libyaml/src/emitter.c:28:6: warning: value computed is not used [-Wunused-value]
- [x] /work/runtime/src/iree/builtins/device/device_generic.c:26:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   26 |       float fres = *((float *)(&res));
      |                     ~^~~~~~~~~~~~~~~~
- [x] /work/tools/iree-cpuinfo.c:19:12: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'int' [-Wformat=]
- [x] /work/tools/iree-dump-instruments-main.c:182:25: warning: format '%lX' expects argument of type 'long unsigned int', but argument 3 has type 'const long unsigned int:40' [-Wformat=]
- [x] /work/runtime/bindings/python/././vm.h:228:11: warning: typedef 'using RawPtrType = typename PyClass::Type::RawPtrType' locally defined but not used [-Wunused-local-typedefs]
- [x] /work/compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPULowerToUKernels.cpp:401:1: warning: control reaches end of non-void function [-Wreturn-type]
- [x] /work/compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp:613:42: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
- [x] /work/compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUTensorPad.cpp:41:8: warning: 'nofold' may be used uninitialized in this function [-Wmaybe-uninitialized]
- [x] /work/compiler/src/iree/compiler/Codegen/LLVMGPU/Utils/LLVMGPULayoutAnalysisAndDistribution.cpp:1184:46: warning: 'batchDim' may be used uninitialized in this function [-Wmaybe-uninitialized]
- [x] /work/third_party/llvm-project/llvm/include/llvm/ADT/DenseMap.h:1197:18: warning: '*((void*)(& loopsToIgnore)+8).llvm::SmallDenseMap<mlir::scf::ForOp, llvm::detail::DenseSetEmpty, 4, llvm::DenseMapInfo<mlir::scf::ForOp, void>, llvm::detail::DenseSetPair<mlir::scf::ForOp> >::LargeRep::NumBuckets' may be used uninitialized in this function [-Wmaybe-uninitialized]
- [x] /work/compiler/src/iree/compiler/Codegen/TransformStrategies/GPU/Common.cpp:85:31: warning: suggest parentheses around '-' in operand of '&' [-Wparentheses]
- [x] /work/compiler/src/iree/compiler/Codegen/VMVX/LowerLinalgMicrokernels.cpp:124:8: warning: '*((void*)(&<anonymous>)+24).mlir::iree_compiler::{anonymous}::StridedBufferDescriptor::memRefType' may be used uninitialized in this function [-Wmaybe-uninitialized]
- [x] /work/compiler/src/iree/compiler/Dialect/HAL/Conversion/ConversionTarget.cpp:59:66: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
- [x] /work/compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.cpp:1716:10: warning: the address of 'static bool mlir::iree_compiler::IREE::Stream::AsyncCallOp::verifySymbolUses(mlir::SymbolTableCollection&)::<lambda(mlir::Type, mlir::Type)>::_FUN(mlir::Type, mlir::Type)' will never be NULL [-Waddress]
- [x] /work/tools/iree-run-mlir-main.cc:228:14: warning: unused variable 'error' [-Wunused-variable]
- [x] /work/build-gcc/runtime/src/iree/vm/test/emitc/buffer_ops.h:6825:6: warning: 'v29' may be used uninitialized in this function [-Wmaybe-uninitialized]
- [x] /work/runtime/src/iree/task/executor_demo.cc:40:16: warning: second argument of 'int {anonymous}::main(int, char*)' should be 'char **' [-Wmain]
   40 | extern "C" int main(int argc, char* argv) {

**Comment by hcindyl** [comment]
@ScottTodd FYI

**Comment by hcindyl** [comment]
@harsh-nod Could you please help review the un-initialzed problem in https://github.com/openxla/iree/blob/3b652d46e86cd82cc81922a964327b12dc914428/compiler/src/iree/compiler/Codegen/LLVMGPU/Utils/LLVMGPULayoutAnalysisAndDistribution.cpp#L1152-L1187

for `vecDim` and `batchDim` ?

**Comment by harsh-nod** [comment]
> @harsh-nod Could you please help review the un-initialzed problem in
> 
> https://github.com/openxla/iree/blob/3b652d46e86cd82cc81922a964327b12dc914428/compiler/src/iree/compiler/Codegen/LLVMGPU/Utils/LLVMGPULayoutAnalysisAndDistribution.cpp#L1152-L1187
> 
> for `vecDim` and `batchDim` ?

Yes I can take a look. Will send a link to the PR when done.

**Comment by harsh-nod** [comment]
> > @harsh-nod Could you please help review the un-initialzed problem in
> > https://github.com/openxla/iree/blob/3b652d46e86cd82cc81922a964327b12dc914428/compiler/src/iree/compiler/Codegen/LLVMGPU/Utils/LLVMGPULayoutAnalysisAndDistribution.cpp#L1152-L1187
> > 
> > for `vecDim` and `batchDim` ?
> 
> Yes I can take a look. Will send a link to the PR when done.

Here is the PR: https://github.com/openxla/iree/pull/14512

**Comment by hcindyl** [comment]
https://github.com/openxla/iree/pull/14519

**Comment by hcindyl** [comment]
It is now down to the `-Wmaybe-uninitialized` in https://github.com/llvm/llvm-project/blob/f88f8fd0bca34dc8e5571cb828b1a159a50fd504/llvm/include/llvm/ADT/DenseMap.h#L1187-L1198

GCC can't detect the union type casting in this case. I tried a few variations and could not seem to make GCC happy. I would like to propose we silence this flag here.

Also, it seems `-Wmaybe-uninitialized` flag is notoriously buggy
https://gcc.gnu.org/bugzilla/buglist.cgi?quicksearch=maybe%20uninitialized
https://stackoverflow.com/questions/14132898/gcc-wuninitialized-wmaybe-uninitialized-issues
