### ISSUE TITLE
Move test_a100 CI job to postsubmit during capacity shortage

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#14545]
Following up on https://github.com/openxla/iree/pull/14312#discussion_r1254807756 and https://github.com/openxla/iree/pull/14521#issuecomment-1659125871

Our `test_a100` CI job is stalling presubmits, sometimes taking hours before a runner is available. As long as we use ephemeral cloud runners and global device supply is limited, we will continue to see queuing like this. If we switched to always-on / reserved / pinned (not sure what specific cloud terminology is here) VMs/machines, then this would be less of an issue.

For now, I think we should move that job to postsubmit, with opt-in presubmits available with a mechanism like `ci-extra: test_a100`.

**Comment by benvanik** [comment]
👍 not worth the queuing

**Comment by pzread** [comment]
SG, we can't get any A100 in presubmit currently
