### ISSUE TITLE
Failed to compile an int4 model

### ISSUE THREAD

**Issue by jinchen62** [iree-org/iree#14547]
### What happened?

With #14488 landing, #14481 was fixed, we got expected results for the int4 unit test and a single layer example. But now getting a iree compilation error for the whole vicuna model. I extracted the dispatch which causes the error.

https://gist.github.com/jinchen62/575746e509ffb9e7d628953796295a88

> error: 'memref.alloca' op expected no unbounded stack allocations

Could you please take a look? @MaheshRavishankar @hanhanW @benvanik 
CC: @qedawkins @powderluv 

### Steps to reproduce your issue

iree-compile --iree-hal-target-backends=llvm-cpu dispatch_4.mlir

**Comment by jinchen62** [comment]
Also get errors for these dispatches.

https://gist.github.com/jinchen62/ef9d09696b5261562ed29e3be6cc1192
> error: failed to legalize operation 'memref.subview' that was explicitly marked illegal

https://gist.github.com/jinchen62/962283dd39c892b212228dad3c2a2ecd
> error: failed to legalize operation 'memref.subview' that was explicitly marked illegal

https://gist.github.com/jinchen62/ebc15c9bf28985f2544a2f539c4a5f10
> error: 'memref.alloca' op expected no unbounded stack allocations

**Comment by jinchen62** [comment]
Hi @hanhanW, I would love to take a stab at it, would be nice if you could give me some guidance.

**Comment by powderluv** [comment]
Isn't there a flag to disable the unbounded stack alloc check ?

**Comment by MaheshRavishankar** [comment]
Yes, but this is an error. My guess is that the bounds check is failing to find the static size. I haven't looked at the IR after each pass, but it's all a single generic op. It's probably a missing folding cause there is no fusion that might trigger a stack allocation

**Comment by jinchen62** [comment]
Adding `--iree-llvmcpu-fail-on-out-of-bounds-stack-allocation=false` does skip the `memref.alloca` error, but think it still needs a proper fix. For the `memref.subview` error, I tried adding it as a legal op in the `EmulateNarrowTypePass` and got 

> error: failed to legalize unresolved materialization from 'memref<64x64xi4, strided<[128, 1], offset: ?>>' to 'memref<64x64xi8, strided<[128, 1], offset: ?>>' that remained live after conversion

**Comment by hanhanW** [comment]
I will take a look at it today, and will post what I found to the issue. Thanks for helping it!

**Comment by MaheshRavishankar** [comment]
Thanks @hanhanW

**Comment by hanhanW** [comment]
We can probably fix the issue, but the dispatch looks weird to me. IMO, it's better to fix it before dispatch formation.

So this is a gather case on filled tensor. The value in `%8` is always `true`, and what the computation does is extracting a value from `%8` (which is always a constant scalar `true` value). I think this kind of input should be tuned before dispatch formation. What it wants is just creating a `dense<1.0>` constants with dynamic shape (i.e., `tensor<?x?xf32>`).

```mlir
      func.func @first_vicuna_forward_dispatch_4_generic_DxD_f32() {
        %c0 = arith.constant 0 : index
        %true = arith.constant true
        %0 = hal.interface.constant.load[0] : i32
        %1 = hal.interface.constant.load[1] : i32
        %2 = arith.index_castui %0 : i32 to index
        %3 = arith.index_castui %1 : i32 to index
        %4 = flow.dispatch.workload.ordinal %3, 0 : index
        %5 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%2) : !flow.dispatch.tensor<writeonly:tensor<?x?xf32>>{%4, %4}
        %6 = tensor.empty(%4, %4) : tensor<?x?xf32>
        %7 = tensor.empty(%4) : tensor<1x1x1x?xi1>
        %8 = linalg.fill ins(%true : i1) outs(%7 : tensor<1x1x1x?xi1>) -> tensor<1x1x1x?xi1>
        %9 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} outs(%6 : tensor<?x?xf32>) {
        ^bb0(%out: f32):
          %10 = linalg.index 1 : index
          %extracted = tensor.extract %8[%c0, %c0, %c0, %10] : tensor<1x1x1x?xi1>
          %11 = arith.uitofp %extracted : i1 to f32
          linalg.yield %11 : f32
        } -> tensor<?x?xf32>
        flow.dispatch.tensor.store %9, %5, offsets = [0, 0], sizes = [%4, %4], strides = [1, 1] : tensor<?x?xf32> -> !flow.dispatch.tensor<writeonly:tensor<?x?xf32>>{%4, %4}
        return
```

I know that we are not able to create a dynamic constant. My point is that this should at least be lowered like something below?

```mlir
%cst = arith.constant 1.0 : f32
%6 = tensor.empty(%4, %4) : tensor<?x?xf32>
%fill = linalg.fill ins(%cst: f32) outs(%7 : tensor<?x?xf32>) -> tensor<?x?xf32>
```

@jinchen could you help check how we get these ops generated on frontend side?

(I can put in more context if we want to fix it on codegen side.)

**Comment by benvanik** [comment]
heh yeah that's just a dynamic splat - I think it'd be useful to look at what's consuming it - this should never be materialized in memory (unless it's being returned from the program or something).

**Comment by MaheshRavishankar** [comment]
> We can probably fix the issue, but the dispatch looks weird to me. IMO, it's better to fix it before dispatch formation.
> 
> So this is a gather case on filled tensor. The value in `%8` is always `true`, and what the computation does is extracting a value from `%8` (which is always a constant scalar `true` value). I think this kind of input should be tuned before dispatch formation. What it wants is just creating a `dense<1.0>` constants with dynamic shape (i.e., `tensor<?x?xf32>`).
> 
> ```mlir
>       func.func @first_vicuna_forward_dispatch_4_generic_DxD_f32() {
>         %c0 = arith.constant 0 : index
>         %true = arith.constant true
>         %0 = hal.interface.constant.load[0] : i32
>         %1 = hal.interface.constant.load[1] : i32
>         %2 = arith.index_castui %0 : i32 to index
>         %3 = arith.index_castui %1 : i32 to index
>         %4 = flow.dispatch.workload.ordinal %3, 0 : index
>         %5 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%2) : !flow.dispatch.tensor<writeonly:tensor<?x?xf32>>{%4, %4}
>         %6 = tensor.empty(%4, %4) : tensor<?x?xf32>
>         %7 = tensor.empty(%4) : tensor<1x1x1x?xi1>
>         %8 = linalg.fill ins(%true : i1) outs(%7 : tensor<1x1x1x?xi1>) -> tensor<1x1x1x?xi1>
>         %9 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} outs(%6 : tensor<?x?xf32>) {
>         ^bb0(%out: f32):
>           %10 = linalg.index 1 : index
>           %extracted = tensor.extract %8[%c0, %c0, %c0, %10] : tensor<1x1x1x?xi1>
>           %11 = arith.uitofp %extracted : i1 to f32
>           linalg.yield %11 : f32
>         } -> tensor<?x?xf32>
>         flow.dispatch.tensor.store %9, %5, offsets = [0, 0], sizes = [%4, %4], strides = [1, 1] : tensor<?x?xf32> -> !flow.dispatch.tensor<writeonly:tensor<?x?xf32>>{%4, %4}
>         return
> ```
> 

Good catch!

**Comment by jinchen62** [comment]
@hanhanW I wonder which error you are referring to.

When I compared with int8 case I got same `memref.alloca` error if I compile it without any flag, but actually shark compile it with `--iree-vm-target-truncate-unsupported-floats` `--iree-codegen-check-ir-before-llvm-conversion=false` `--iree-vm-bytecode-module-output-format=flatbuffer-binary` and int8 works well. With those flags I don't get that error for int4, so I think the `memref.alloca` one is fine.

And I believe the `memref.subview` error is coming from the `EmulateNarrowTypePass`.

**Comment by hanhanW** [comment]
I'm referring to dispatch_4, and the error is `error: 'memref.alloca' op expected no unbounded stack allocations`. I can look into other failures tomorrow. It would be good if we can file the issues separately, so the comments won't be interleaved. For this issue, let's scope it to `dispatch_4` error. What do you think?

**Comment by jinchen62** [comment]
Actually I think we don't need to worry about the `memref.alloca` error now, I tested and it won't be a matter for the compilation through shark. Could you please take a look at the other error? I will open a new issue.

**Comment by MaheshRavishankar** [comment]
We might be missing a fold of the `memref.subview`... @jinchen62 since you have the context here easiest way to triage is to post IR before and after the pass that fails.

**Comment by powderluv** [comment]
Is this fixed ? Can we close it if we have landed the fix ?

**Comment by jinchen62** [comment]
I think we can close this since the stack allocations is not an issue and #14567 is open.
