### ISSUE TITLE
Failed to legalize operation 'memref.subview'

### ISSUE THREAD

**Issue by jinchen62** [iree-org/iree#14567]
### What happened?

Open a separate issue for `memref.subview` error from #14547.

Dispatch 7 and 34 get same error
> error: failed to legalize operation 'memref.subview' that was explicitly marked illegal

`--mlir-print-ir-after-all` shows
> IR Dump After EmulateNarrowType Failed (iree-codegen-emulate-narrow-type)

https://gist.github.com/jinchen62/ef9d09696b5261562ed29e3be6cc1192
https://gist.github.com/jinchen62/962283dd39c892b212228dad3c2a2ecd

### Steps to reproduce your issue

iree-compile first_vicuna_forward_dispatch_7.mlir --iree-hal-target-backends=llvm-cpu --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-llvmcpu-target-cpu-features=host --iree-llvmcpu-target-triple=x86_64-linux-gnu --iree-flow-enable-data-tiling --iree-llvmcpu-enable-microkernels --iree-llvmcpu-stack-allocation-limit=256000 --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=true --iree-util-zero-fill-elided-attrs --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false

**Comment by jinchen62** [comment]
@hanhanW @MaheshRavishankar 
cc @qedawkins

**Comment by hanhanW** [comment]
Can you share the IR before and after EmulateNarrowType pass? I think we are missing the pattern for `memref.subview`. In this case, we need to add a pattern to upstream, i.e., https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/MemRef/Transforms/EmulateNarrowType.cpp

**Comment by MaheshRavishankar** [comment]
I responded on the other bug. We probably dont want to support `subview`s directly. We want to fold the `subview`s into loads/stores....

**Comment by jinchen62** [comment]
[printouts.txt](https://github.com/openxla/iree/files/12253666/printouts.txt)
@hanhanW pls lmk if you need anything else, thanks

**Comment by hanhanW** [comment]
Okay, then we probably want to add `memref::createFoldMemRefAliasOpsPass()` before emulation. I can take a stab at it.

**Comment by hanhanW** [comment]
yep, `build/tools/iree-opt --fold-memref-alias-ops --iree-codegen-emulate-narrow-type ~/repro.mlir` does fix the issue. I'll prepare a patch.

**Comment by hanhanW** [comment]
[This](https://github.com/openxla/iree/pull/14569/commits/e8fa6d5c811d95eb71ee966c6a60eab4789980d6) may address your issue. I can't just land it because there are regressions. I have to understand what's happening and fix it.

**Comment by jinchen62** [comment]
Yes it fixes the error.
