### ISSUE TITLE
Request for more models in RISC-V benchmarks

### ISSUE THREAD

**Issue by rednoah91** [iree-org/iree#14623]
### Request description

First, I would like to express my appreciation to Che-Yu Wu for his dedicated efforts in enabling RISC-V benchmarks on the IREE dashboard. This highlights the end-to-end performance optimization achieved by IREE on the RISC-V platform.
Currently, the models benchmarking on RISC-V are:
```
tflite_models.DEEPLABV3_FP32,
tflite_models.MOBILEBERT_FP32,
tflite_models.MOBILENET_V1,
tflite_models.MOBILEBERT_INT8,
tflite_models.PERSON_DETECT_INT8,
tflite_models.EFFICIENTNET_INT8,
tflite_models.MOBILENET_V2_INT8,
```
Could we enable more models on RISC-V benchmarks? Our specific interest lies in the following:
```
tf_models.MINILM_L12_H384_UNCASED_INT32_SEQLEN128
tf_models.BERT_LARGE_TF_FP32_SEQLEN384
torch_models.MODEL_CLIP_TEXT_SEQLEN64_FP32_TORCH
torch_models.MODEL_UNET_2D_FP32_TORCH
torch_models.EFFICIENTNET_V2_S_FP32_TORCH
```
Thanks.

**Comment by pzread** [comment]
I'll test them on the FPGA and post the results here, to see how long it will take to run.

**Comment by pzread** [comment]
Sorry for the long delay. Here are some updates:

So the first problem I found is that some models are too big to be copied to our FPGA. The free disk space of the SD card is less than 1GB. And these are the model sizes:

```
1.3G    ./iree_module_BertLargeTF_stablehlo___riscv_64-generic-linux_gnu-llvm_cpu__default-flags_/module.vmfb
470M    ./iree_module_ClipTextSeqLen64PT_linalg___riscv_64-generic-linux_gnu-llvm_cpu__default-flags_/module.vmfb
84M     ./iree_module_EfficientNetV2SPT_linalg___riscv_64-generic-linux_gnu-llvm_cpu__default-flags_/module.vmfb
128M    ./iree_module_MiniLML12H384Uncased_stablehlo___riscv_64-generic-linux_gnu-llvm_cpu__default-flags_/module.vmfb
3.2G    ./iree_module_Unet2dPT_linalg___riscv_64-generic-linux_gnu-llvm_cpu__default-flags_/module.vmfb
```

For the models that I can copy to the FPGA, here are the run times:

| Model | Single thread | 2 threads |
| ----------| ------------| ---------------- |
| EfficientNetV2SPT | 1340.3s | 1119.5s |
| MiniLML12H384Uncased | 21s |  18.6s |
| ClipTextSeqLen64PT | 66.7s | 42.8s |

`EfficientNetV2SPT` took quite a long time to run but it might be feasible. Single thread vs. 2 threads doesn't seem to be scaled very well but I can double check. I ran 2-thread benchmarks with `--task_topology_group_count=2 --device=local-task`

I'm currently testing BertLargeTF and Unet2dPT with model files on NFS to see if they can fit in memory and how the overhead of NFS affects benchmark results.

**Comment by rednoah91** [comment]
Thanks for your effort, Jerry.
It a little surprise that `EfficientNetV2SPT` took quite a long time to run. In the dashboard, `EfficientNet_int8(tflite)` takes only ~3.3s, I thought their are similar. Do you know any special ops in `EfficientNetV2SPT`? We can disable it until we find the root cause because 1340.3s might be too long.
My team member @ElEHsiang will help comment the storage part.

**Comment by ElEHsiang** [comment]
For the disk space of the SD card, you can plug the SD card to an Ubuntu PC. Use the `gparted` to fix the partition table(`gparted` will ask you when first time plug in) and extend the rootfs size. I can provide the screenshots of the steps if needed.

**Comment by pzread** [comment]
Here is the result of BertLarge with models on NFS folder. I also ran MiniLM as the reference and in this case NFS seems to not affect the performance too much (AFAIK the model is loaded into memory before benchmarking).

| Model | Single thread with model on NFS |
| ----------| ------------|
| BERT_LARGE_TF_FP32_SEQLEN384 | 2619.1s |
| MiniLML12H384Uncased | 21.5s |

But BertLarge also takes quite a long time to run. 

> It's a little surprise that EfficientNetV2SPT took quite a long time to run. In the dashboard, EfficientNet_int8(tflite) takes only ~3.3s, I thought their are similar.

I think it also could be the difference in model sizes. IIUC EfficientNet has a variety of sizes. EfficientNetV2SPT also runs 0x slower than EfficientNet_int8 (270s vs, 30s) in our x86_64 benchmarks. @mariecwhite might know more about their differences.

It looks like for now `MiniLML12H384Uncased` and `ClipTextSeqLen64PT` can be added. I'll send out the PR soon.

For the storage size, thanks for the instructions and I'll try to extend the rootfs.

**Comment by dcaballe** [comment]
IIRC, NFS was faster than the SD on my side so moving from SD to NFS was actually a major improvement.

**Comment by rednoah91** [comment]
Regarding NFS, our experience is that single-thread seems no impact but we saw some overhead in multi-thread.
Thanks @pzread, I think we can close this issue after your PRs are merged.
Let's enable the large models when we have a x280 real-chip.
