### ISSUE TITLE
Python Runtime: ImportError: dynamic module does not define module export function (PyInit__runtime)

### ISSUE THREAD

**Issue by JackWolfard** [iree-org/iree#14644]
### What happened?

After building IREE, I built and installed the Python wheel for the IREE runtime yet noticed I ran into an `ImportError`

```sh
$ python -m pip wheel -w <path to wheel directory> <path to IREE build directory>/runtime/
$ python -m pip install <path to wheel directory>/iree_runtime*
$ python
Python 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iree._runtime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit__runtime)
```

From the [nanobind FAQ](https://nanobind.readthedocs.io/en/latest/faq.html#importing-my-module-fails-with-an-importerror)

> ### Importing my module fails with an ImportError
> If importing the module fails as shown below, you have not specified a matching module name in [nanobind_add_module()](https://nanobind.readthedocs.io/en/latest/api_cmake.html#command:nanobind_add_module) and [NB_MODULE()](https://nanobind.readthedocs.io/en/latest/api_core.html#c.NB_MODULE).
> ```
> import my_ext
> ImportError: dynamic module does not define module export function (PyInit_my_ext)
> ```

In the IREE runtime (which uses nanobind), these names do not match.

In [runtime/bindings/python/CMakeLists.txt](https://github.com/openxla/iree/blob/main/runtime/bindings/python/CMakeLists.txt#L63), `nanobind_add_module(iree_runtime_bindings_python_PyExtRt ... )`

In [runtime/bindings/python/initialize_module.cc](https://github.com/openxla/iree/blob/main/runtime/bindings/python/initialize_module.cc), `NB_MODULE(_runtime ...)`

### What component(s) does this issue relate to?

Python, Runtime

### Version information

e372c2d2575975e40c35079e06d2466bf91264f0

**Comment by JackWolfard** [comment]
cc: @stellaraccident

**Comment by stellaraccident** [comment]
The CMake target name doesn't matter. The output name on disk is correct and should match (`_runtime.*.so`). This matches the NB_MODULE.

**Comment by JackWolfard** [comment]
> The CMake target name doesn't matter. The output name on disk is correct and should match (`_runtime.*.so`). This matches the NB_MODULE.

Thanks for letting me know that's not a problem. I haven't used nanobind before, so I was naively reading into the docs.

There must be a different issue with my environment causing this problem. I will try and put together a Gist to reproduce, and if I cannot, then close this issue.

**Comment by JackWolfard** [comment]
Figured out what was going on. I was building IREE's runtime Python package w/ GCC, but I also had `IREE_ENABLE_LLD=ON` set in the CMake options. If I omit this option, then I do not get this error. Otherwise, I can leave this option on as long as I build with Clang instead of GCC.
