### ISSUE TITLE
iree-compile OOMs on models with large batch size for all backends

### ISSUE THREAD

**Issue by pzread** [iree-org/iree#14668]
In `benchmark_large.yml` we found that IREE took lots of memory (>200GB, couldn't finish the compilations) to compile ResNet50 and BertLarge models with large batch sizes and caused OOM in build stage. Those models were able to be compiled before.

### To Reproduce

Download models:

```sh
# ResNet50 batch size 2048
wget https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.13_1688607404/RESNET50_FP32_JAX_3X224X224XF32_BATCH2048/stablehlo.mlirbc -O model_RESNET50_FP32_JAX_3X224X224XF32_BATCH2048.mlirbc

# BertLarge batch size 1280
wget https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.13_1688607404/BERT_LARGE_FP32_JAX_384XI32_BATCH1280/stablehlo.mlirbc -O model_BERT_LARGE_JAX_384XI32_BATCH1280.mlirbc
```

Compile:

```sh
# ResNet50 batch size 2048
iree-compile model_RESNET50_FP32_JAX_3X224X224XF32_BATCH2048.mlirbc -o resnet50.vmfb --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80

# BertLarge batch size 1280
iree-compile model_BERT_LARGE_JAX_384XI32_BATCH1280.mlirbc -o bert_large.vmfb --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80
```

**Comment by mariecwhite** [comment]
I am working my way through updating the models. ResNet50 batch 2048 passes compilation but fails at runtime with:

```
work/runtime/src/iree/base/allocator.c:110: RESOURCE_EXHAUSTED; system allocator failed the request;
reading file '.../module.vmfb'; loading bytecode module at '.../module.vmfb'
```

To reproduce:
```
wget https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.14_1691969180/RESNET50_FP32_JAX_3X224X224XF32_BATCH2048/stablehlo.mlirbc -O model_RESNET50_FP32_JAX_3X224X224XF32_BATCH2048.mlirbc

iree-compile model_RESNET50_FP32_JAX_3X224X224XF32_BATCH2048.mlirbc -o resnet50.vmfb --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80

iree-benchmark-module resnet50.vmfb --function=main --input=2048x3x224x224xf32=0 --device_allocator=caching --device=cuda://0 --print_statistics=true --benchmark_repetitions=10
```

**Comment by mariecwhite** [comment]
JAX BertLarge batch size 512 is also OOM'ing at compile time. Link to mlir: 

https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.14_1691969180/BERT_LARGE_FP32_JAX_384XI32_BATCH512/stablehlo.mlirbc

**Comment by mariecwhite** [comment]
PyTorch BertLarge batch size 512 and above is also OOM'ing at compile time. Link to mlir:

https://storage.googleapis.com/iree-model-artifacts/pytorch/pt_models_20230813.929_1692010793/BERT_LARGE_FP32_PT_384XI32_BATCH512/linalg.mlirbc

**Comment by benvanik** [comment]
these should be pretty straightforward to triage - do iree-compile --compile-to=executable-sources, then xargs each source with iree-compile --compile-mode=hal-executable and see which ones OOM

that something compiling 1 KB of source can OOM is ... sad x_x

**Comment by mariecwhite** [comment]
It OOMs even when I run `iree-compile --compile-to=executable-sources`. Here's the command I used `iree-compile /tmp/stablehlo.mlirbc --compile-to=executable-sources --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80 --iree-hal-dump-executable-sources-to=/tmp/sources -o /dev/null`

**Comment by benvanik** [comment]
that implies it may have nothing to do with codegen - have you tried anything but CUDA?

**Comment by mariecwhite** [comment]
Ohh getting the same error on `llvmcpu`:
```
iree-compile --iree-hal-target-backends=llvm-cpu --iree-input-type=stablehlo --iree-llvmcpu-target-triple=x86_64-unknown-linux-gnu /tmp/stablehlo.mlirbc -o /tmp/module.vmfb
Killed
```

**Comment by benvanik** [comment]
well, that changes things :) this likely has nothing to do with CUDA and may be something happening much earlier - possibly some constant folding? I'm guessing there's an infinite loop happening or something in some pass - a print-ir-before-all dumped to a file will let us see where it hangs (or a debugger)

**Comment by mariecwhite** [comment]
Here's what's dumped when I add `--print-before-all` to `iree-compile`: https://gist.github.com/mariecwhite/a2e46e570e0568eb00bf1870d9cdb5b5

**Comment by benvanik** [comment]
oof, that looks unrelated but something in the LLVM IR we're generating that's bad, what happens with CUDA?

**Comment by mariecwhite** [comment]
CUDA shows the same error: https://gist.github.com/mariecwhite/f330f40517768fc8d662457c28359f51

**Comment by allieculp** [comment]
@mariecwhite @benvanik Anyone actively working on this one? Flagged as P0.

**Comment by mariecwhite** [comment]
This is as far as I can take it unless someone has more instructions on how to debug.

**Comment by cc10512** [comment]
Is this still an issue? When I tried to reproduce the OOM, unfortunately, it seems that the stored models are no longer compatible with the current version of StableHLO:
```
iree-compile --iree-hal-target-backends=llvm-cpu --iree-input-type=stablehlo --iree-llvmcpu-target-triple=x86_64-unknown-linux-gnu stablehlo.mlirbc -o /tmp/module.vmfb
/tmp/jax_models_0.4.14_1691969180/BERT_LARGE_FP32_JAX_384XI32_BATCH512/stablehlo.mlir:413:12: error: 'stablehlo.slice' op attribute 'start_indices' failed to satisfy constraint: i64 dense array attribute
/tmp/jax_models_0.4.14_1691969180/BERT_LARGE_FP32_JAX_384XI32_BATCH512/stablehlo.mlir:413:12: note: see current operation: %410 = "stablehlo.slice"(%409) {limit_indices = dense<[1, 512, 384]> : tensor<3xi64>, start_indices = dense<0> : tensor<3xi64>, strides = dense<1> : tensor<3xi64>} : (tensor<2x512x384xf32>) -> tensor<1x512x384xf32>
/tmp/jax_models_0.4.14_1691969180/BERT_LARGE_FP32_JAX_384XI32_BATCH512/stablehlo.mlir:413:12: note: in bytecode version 6 produced by: MLIR18.0.0git
```
and
```
iree-compile --iree-hal-target-backends=llvm-cpu --iree-input-type=stablehlo --iree-llvmcpu-target-triple=x86_64-unknown-linux-gnu linalg.mlirbc -o /tmp/bertlarge.vmfb 
linalg.mlirbc:0:0: error: attempting to parse a byte at the end of the bytecode
linalg.mlirbc:0:0: note: in bytecode version 6 produced by: MLIR18.0.0git
```

**Comment by mariecwhite** [comment]
I'll regenerate the MLIR

**Comment by mariecwhite** [comment]
@cc10512 do you mind trying with https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.23_1705868085/BERT_LARGE_FP32_JAX_384XI32_BATCH512/stablehlo.mlirbc?
