### ISSUE TITLE
int4 outputs different results w/wo fuse dispatch bindings

### ISSUE THREAD

**Issue by yzhang93** [iree-org/iree#14662]
### What happened?

int4 outputs different results w/wo `IREE::Stream::createFuseDispatchBindingsPass();`

### Steps to reproduce your issue

1. Download Int4 IR: https://storage.googleapis.com/shark_tank/vicuna/unsharded/mlir/vicuna_int4.mlir

2. Command: `../shark-build/tools/iree-compile vicuna_int4.mlir -o vicuna_int4.vmfb --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-target-cpu-features=host --iree-llvmcpu-target-triple=x86_64-linux-gnu --iree-llvmcpu-enable-microkernels --iree-llvmcpu-stack-allocation-limit=256000 --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=true --iree-util-zero-fill-elided-attrs --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false --iree-opt-const-expr-hoisting=False --iree-flow-break-dispatch=@first_vicuna_forward:7`

`../shark-build/tools/iree-run-module --module=vicuna_int4.vmfb --function=first_vicuna_forward --input=1x1xi64`

3. Adding flag `--iree-scheduling-optimize-bindings=false` and re-run the above commands, the results are different.

Note: a simple test with a 8x12 input tensor doesn't have the above issue. The problem only happens when the inputs are large.

Dispatch 7 dumped source: https://storage.googleapis.com/shark-public/vivian/vicuna_i4/module_first_vicuna_forward_dispatch_7.mlir

Vicuna dumped IR after all: 
https://storage.googleapis.com/shark-public/vivian/vicuna_i4/vicuna_dump_i4.txt

**Comment by yzhang93** [comment]
@MaheshRavishankar You can use [this](https://storage.googleapis.com/shark-public/vivian/vicuna_i4/fake_i4_dispatch7.npy) as the groundtruth of dispatch 7 to compare against.

**Comment by yzhang93** [comment]
Similar issue is also observed on SPIR-V with this [branch](https://github.com/openxla/iree/tree/stella_test_matvec_fused_dequant) of codes.

As for now there's compilation issue for entire vicuna, the tests are performed on [second_vicuna_int4.mlir](https://storage.googleapis.com/shark_tank/vicuna/unsharded/mlir/second_vicuna_int4.mlir).

Commands to reproduce:
```./iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=false --iree-util-zero-fill-elided-attrs --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false --iree-vulkan-target-triple=rdna3-unknown-linux --iree-opt-const-expr-hoisting=false --iree-consteval-jit-debug=true ~/Downloads/vicuna_unsharded_mlir_second_vicuna_int4.mlir -o vicuna_vulkan_i4.vmfb --iree-stream-resource-max-allocation-size=3221225472```

```./iree-run-module --device_allocator=caching --vulkan_vma_allocator=false --module=vicuna_vulkan_i4.vmfb --device=vulkan --function=forward --input=1x1xi64 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32  --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32 --input=1x32x1x128xf32```

With `--iree-scheduling-optimize-bindings=false` flag added, then the results are correct.

The groundtruth results (i4 weights in i8 container) are compared with CPU and validated. It can be downloaded from [here](https://storage.googleapis.com/shark-public/vivian/vicuna_i4/vicuna_vulkan_fake_i4_results.txt)

**Comment by MaheshRavishankar** [comment]
@yzhang93 and (@qedawkins maybe) https://github.com/openxla/iree/pull/14664 seems to fix the issue with dispatch 7. Might fix overall model correctness too. Please let me know

**Comment by yzhang93** [comment]
I confirmed the CPU correctness issue has been fixed.

I tried to apply https://github.com/openxla/iree/pull/14664 on top of the SPIR-V [test branch](https://github.com/openxla/iree/tree/stella_test_matvec_fused_dequant). I see the emulation happens as expected, but the results are still not correct.

Here are the dump IR before and after emulation pass.

https://storage.googleapis.com/shark-public/vivian/vicuna_i4/dump_before_emulation.txt
https://storage.googleapis.com/shark-public/vivian/vicuna_i4/dump_after_emulation.txt

**Comment by MaheshRavishankar** [comment]
> I confirmed the CPU correctness issue has been fixed.
> 
> I tried to apply #14664 on top of the SPIR-V [test branch](https://github.com/openxla/iree/tree/stella_test_matvec_fused_dequant?rgh-link-date=2023-08-17T17%3A49%3A11Z). I see the emulation happens as expected, but the results are still not correct.
> 
> Here are the dump IR before and after emulation pass.
> 
> [storage.googleapis.com/shark-public/vivian/vicuna_i4/dump_before_emulation.txt](https://storage.googleapis.com/shark-public/vivian/vicuna_i4/dump_before_emulation.txt) [storage.googleapis.com/shark-public/vivian/vicuna_i4/dump_after_emulation.txt](https://storage.googleapis.com/shark-public/vivian/vicuna_i4/dump_after_emulation.txt)

@antiagainst this is all with offset 0 on the subspan.... (@yzhang93 please confirm that using `--iree-schedule-optimize-binding=false` has the error as well cause all the offsets here are 0 already). So issue might be something in the lowering to SPIRV

**Comment by yzhang93** [comment]
@MaheshRavishankar @antiagainst Here are dump IR files with `--iree-schedule-optimize-binding=false`

https://storage.googleapis.com/shark-public/vivian/vicuna_i4/dump_before_emulation_wo_bindings.txt
https://storage.googleapis.com/shark-public/vivian/vicuna_i4/dump_after_emulation_wo_bindings.txt

With this flag, the results are correct.

**Comment by yzhang93** [comment]
I added these two passes 

`pm.addPass(createEmulateNarrowTypePass());
pm.addPass(createLowerAffinePass());`

here https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp#L242.

And for the test, you can follow the commands [here](https://github.com/openxla/iree/issues/14662#issuecomment-1679645162)

**Comment by yzhang93** [comment]
Moved discussion for SPIRV correctness issue to https://github.com/openxla/iree/issues/14739
