### ISSUE TITLE
const_cast statements are introduced after 2023-08-15 integrate

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#14702]
With upstream https://github.com/llvm/llvm-project/commit/ce254598b73b119c9463f5b7f4131559e276e844 commit, we have to introduce `const` qualifier for TypeConverter. However, it is not trivial for EmitCTypeConverter. E.g.,

l.1361:

```
auto vmAnalysis = typeConverter->lookupAnalysis(funcOp);
```

l.1395:

```
    typeConverter->analysisCache.insert(
        std::make_pair(newFuncOp.getOperation(), VMAnalysis(functionType)));
```

The former example requires [all methods ](https://github.com/openxla/iree/blob/aef8d3ce065826e915a45e12135d6f791737d8b4/compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCTypeConverter.h#L22-L60)to be added `const` qualifier. This is very tricky for [lookupAnalysis](https://github.com/openxla/iree/blob/aef8d3ce065826e915a45e12135d6f791737d8b4/compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCTypeConverter.cpp#L119-L127) method because the infer-ed type mismatch return type.

The latter example is very very very tricky. `analysisCache` has [llvm::DenseMap<Type, int> type](https://github.com/openxla/iree/blob/aef8d3ce065826e915a45e12135d6f791737d8b4/compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCTypeConverter.h#L58), and it will require `insert` method having `const` qualified -- which is impossible to me.

The workaround is adding `const_cast` to remove const qualifier. We should untangle the type converter and the analysis; @simon-camp  will help on this.

**Comment by hanhanW** [comment]
@simon-camp thanks for working on it. I don't see `const_cast` in https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCTypeConverter.h anymore. Can we say that it is fixed?

**Comment by simon-camp** [comment]
Hi @hanhanW, the `const_cast` is used in the [conversion](https://github.com/openxla/iree/blob/ac9548469e8e46f8ad6ea29c1c7144a774ebba19/compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp#L1342C9-L1342C19).

I've started to work on this today. I'm not sure if we can get to a perfect solution, but the plan is to encapsulate all stateful methods into a helper struct, and give the type converter a mutable member. Then there will be only one place where we work around constness.

**Comment by hanhanW** [comment]
> Hi @hanhanW, the `const_cast` is used in the [conversion](https://github.com/openxla/iree/blob/ac9548469e8e46f8ad6ea29c1c7144a774ebba19/compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp#L1342C9-L1342C19).
> 
> I've started to work on this today. I'm not sure if we can get to a perfect solution, but the plan is to encapsulate all stateful methods into a helper struct, and give the type converter a mutable member. Then there will be only one place where we work around constness.

SG, thanks for working on it!
