### ISSUE TITLE
[VM] DeduplicateRodataPass takes ~50% of compilation time

### ISSUE THREAD

**Issue by ezhulenev** [iree-org/iree#14754]
### What happened?

![image](https://github.com/openxla/iree/assets/1174378/f777c777-31cf-4e07-907f-a586928cba14)

`DeduplicateRodataPass` takes significant portion of the compilation time in `SymbolTable::replaceAllSymbolUses`. Can it be improved?

**Comment by ScottTodd** [comment]
Can you share more details? Compiler version information + input IR + compile command with all flags + Tracy capture would be ideal.

What is the total compilation time? 50% of 3 seconds is pretty different than 50% of 1 hour.

We have some general information about debugging compiler performance here: https://github.com/openxla/iree/blob/main/docs/developers/debugging/compile_time_regressions.md#profiling-and-tracing

**Comment by ezhulenev** [comment]
Model is exported from internal Google XLA LLM model, didn't try to reproduce it with any OSS models. I'm using IREE built from head.

```
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DIREE_ENABLE_ASSERTIONS=ON \
```

```
time build/tools/iree-compile xla_program.mlir --iree-hal-target-backends=cuda > /tmp/foo
80.76s user 3.12s system 106% cpu 1:18.98 total
```

I didn't look into what `DeduplicateRodataPass` is doing, and what is the IR right before it, will update this bug when will collect it, but judging by how slow it is, I suspect it's accidental O(n^2) complexity somewhere, or maybe worse.

**Comment by ScottTodd** [comment]
`DeduplicateRodataPass` runs towards the end of the VM pipeline. A trace would show if it's slow at the end of the full compilation pipeline or just during consteval. Since your screenshot shows Stream code running after, I suspect this is during consteval...

**Comment by benvanik** [comment]
I'm kind of shocked - this would indicate that consteval is generating _a lot_ of duplicate constants. We could make the module walk faster (and should) but also would be good to figure out why there's so many dupes and if we could avoid creating them in the first place.

**Comment by ezhulenev** [comment]
Execution time report: https://gist.github.com/ezhulenev/b918557ec9f21fc4955b894df505a9f9

**Comment by ezhulenev** [comment]
Looks like the problem is in 5500 identical rodata globals:

```
vm.rodata private @_utf8_tensor_3C6209B4FD120BDC_986 {alignment = 1 : i64} "tensor"
```

And problem is in MLIR symbol use replacement.

**Comment by benvanik** [comment]
I'll take a look at making the symbol replacement better (O(ops in module) instead of O(symbol replacements * ops in module)). You'll need to post some IR if you want to have it validated as improving performance, though.
