### ISSUE TITLE
TOSA importer failed after 08-17-2023 integrate

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#14775]
See https://github.com/openxla/iree/pull/14725 and https://github.com/openxla/iree/actions/runs/5898571518/job/16000106665

```
Failed Tests (11):
  TENSORFLOW_TESTS :: iree_tfl_tests/east_text_detector.run
  TENSORFLOW_TESTS :: iree_tfl_tests/gpt2.run
  TENSORFLOW_TESTS :: iree_tfl_tests/llvmcpu_mobilenet_v1.run
  TENSORFLOW_TESTS :: iree_tfl_tests/llvmcpu_mobilenet_v3-large_uint8.run
  TENSORFLOW_TESTS :: iree_tfl_tests/llvmcpu_resnet_50_int8.run
  TENSORFLOW_TESTS :: iree_tfl_tests/mnasnet.run
  TENSORFLOW_TESTS :: iree_tfl_tests/mobilenet_v3.run
  TENSORFLOW_TESTS :: iree_tfl_tests/person_detect.run
  TENSORFLOW_TESTS :: iree_tfl_tests/vmvx_mobilebert_tf2_quant.run
  TENSORFLOW_TESTS :: iree_tfl_tests/vmvx_person_detect.run
  TENSORFLOW_TESTS :: iree_tfl_tests/vulkan_mobilenet_v1.run
```

**Comment by hcindyl** [comment]
FYI, tf-nightly 2.15.0.dev20230817 picked up the required fix. Not sure if anyone has raised a PR to re-enable the tflite tests.

**Comment by hanhanW** [comment]
@jpienaar I've seen you bumped tf-nightly couple times, could you help bump tf-nightly version and re-enable the tests and benchmarks?

**Comment by jpienaar** [comment]
@rsuderman is already working on this AFAIK

**Comment by hanhanW** [comment]
Hey @rsuderman I'd like check in what's the status about this? I have a couple PRs that needs to test if there are regression. It would be awesome if this is prioritized.

**Comment by hanhanW** [comment]
I'm trying to bump it. It looks like we need to bump python to 3.9 as well.

![image](https://github.com/openxla/iree/assets/6949191/162f791d-1778-44a4-9caf-8ae2bbf44fd0)
