### ISSUE TITLE
CPU compilation issue due to Introduce GlobalOptimization layers to Pipeline. (#14767)

### ISSUE THREAD

**Issue by Abhishek-Varma** [iree-org/iree#14822]
### What happened?

Llama2 13B fails to compile on CPU due to the following commit :-
```
commit c477184d1da45e091eafeb6ca0887a029f2a6f3b
Author: Han-Chung Wang <hanchung@google.com>
Date:   Wed Aug 23 14:15:52 2023 -0700

    Introduce GlobalOptimization layers to Pipeline. (#14767)
    
    It moves all the passes before elementwise fusion (and cleanups) to
    global optimization pipeline.
    
    - Creates GlobalOptimization directory and move pipeline build method to
    it.
    - Adds GlobalOptimization layers to compilation pipeline.
```
It leads to `iree/runtime/src/iree/hal/buffer.c:444: OUT_OF_RANGE; attempted to access an address outside of the valid buffer range (offset=0, adjusted_length=8, end=7, buffer byte_length=4)`.

I tried removing this commit from IREE/SRT and the compilation succeeds!

### Steps to reproduce your issue

1. Input IR : [llama2 13b int4](https://console.cloud.google.com/storage/browser/_details/shark_tank/llama2_13b/unsharded/mlir/llama2_13b_int4.mlirbc;tab=live_object?authuser=0)
2. Command:
```
time ./build/tools/iree-compile --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-llvmcpu-target-triple=x86_64-linux-gnu --iree-flow-enable-data-tiling --iree-llvmcpu-enable-microkernels --iree-llvmcpu-stack-allocation-limit=256000 --iree-stream-resource-index-bits=64 --iree-stream-resource-max-allocation-size=4294967295 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=true --iree-util-zero-fill-elided-attrs --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false --iree-vm-bytecode-module-output-format=flatbuffer-binary llama2_13b_int4.mlirbc -o llama2_13b_int4_cpu.vmfb
```

**Comment by hanhanW** [comment]
I can't reproduce it on ToT. Maybe it's fixed by someone already. Could you try rebasing it to main and give it another shot?

**Comment by Abhishek-Varma** [comment]
I confirm this doesn't exist anymore.
Gets fixed by [this commit](https://github.com/openxla/iree/commit/585e5ca36587a9d74f1cc2f9ef8fc19f535e3a1e).

Closing this issue. Thanks @hanhanW !
