### ISSUE TITLE
Failed to legalize operation 'stablehlo.return' that was explicitly marked illegal for LLM helper function

### ISSUE THREAD

**Issue by phoenix-meadowlark** [iree-org/iree#14837]
### What happened?

Compiling the following LLM helper function throws an error that `stablehlo.return` was explicitly marked illegal:

```mlir
module @jit_call_model_function {
  func.func @top_k_gt_f32_comparator(%arg0: tensor<f32>, %arg1: tensor<f32>, %arg2: tensor<i32>, %arg3: tensor<i32>) -> tensor<i1> {
    %0 = stablehlo.compare  GT, %arg0, %arg1 : (tensor<f32>, tensor<f32>) -> tensor<i1>
    stablehlo.return %0 : tensor<i1>
  }
}
```
```
/tmp/top_k.mlir:4:5: error: failed to legalize operation 'stablehlo.return' that was explicitly marked illegal
    stablehlo.return %0 : tensor<i1>
    ^
/tmp/top_k.mlir:4:5: note: see current operation: "stablehlo.return"(%2) : (tensor<i1>) -> ()
```

### Steps to reproduce your issue

Compile the above MLIR snippet.

```shell
iree-compile \
  --iree-hal-target-backends=llvm-cpu \
  --iree-input-type=stablehlo \
  /tmp/top_k.mlir \
  -o /tmp/top_k.vmfb
```

### What component(s) does this issue relate to?

Frontends

### Version information

8314b5ccb30abac44f59672849bb385e212fa84d

**Comment by ScottTodd** [comment]
This fails in `ConvertStableHloToIreeInputDialects`. Here's output from `--mlir-print-ir-before-all`: https://gist.github.com/ScottTodd/c97a52a3168074931db0d5096b955887. I see some tests in the repo using both `stablehlo.compare` and `stablehlo.return`, but `stablehlo.return` always appears to exist inside of other stablehlo ops. Looks like we expect `return` at the top level (from the builtin dialect)?

**Comment by phoenix-meadowlark** [comment]
Replacing that specific `stablehlo.return` with `return` sidesteps the issue (none of the other `stablehlo.return`s are at the top level). It also fails without the `compare` operation:

```mlir
module @top_level_return {
  func.func @top_level_return() -> tensor<i32> {
    %1 = stablehlo.constant dense<1> : tensor<i32>
    stablehlo.return %1 : tensor<i32>
  }
}
```

The top-level `stablehlo.return` is directly generated by JAX, so if that's incorrect for some reason it may need to be fixed upstream.

**Comment by rsuderman** [comment]
We should add a rewriter that a `stablehlo.return` within a `FuncOp` should rewrite to `func::ReturnOp`. @bviyer mind looking at this on Monday?

Somewhere in https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/InputConversion/StableHLO/StableHLOToArith.cpp

should be good enough.

**Comment by bviyer** [comment]
This issue should be fixed with the patch in https://github.com/openxla/iree/pull/14849.
Here is the screenshot of the output when I compiled the test after applying the patch:
```
<shell>:$ cat test2.mlir 
module @jit_call_model_function {
  func.func @top_k_gt_f32_comparator(%arg0: tensor<f32>, %arg1: tensor<f32>, %arg2: tensor<i32>, %arg3: tensor<i32>) -> tensor<i1> {
    %0 = stablehlo.compare  GT, %arg0, %arg1 : (tensor<f32>, tensor<f32>) -> tensor<i1>
    stablehlo.return %0 : tensor<i1>
  }
}
<shell>:$ ./iree-compile   --iree-hal-target-backends=llvm-cpu   --iree-input-type=stablehlo  test2.mlir   -o /tmp/top_k.vmfb
<shell>:$
```
