### ISSUE TITLE
[consteval] Reshuffling flow/global opt passes caused large increase in neutral consteval transactions

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#14865]
See https://github.com/openxla/iree/pull/14707

Note that the PkgCI tests for llama2 are logging a large increase in consteval expressions that appear to just be a tensor.collapse_shape. We may want to restrict consteval from only performing metadata updates (or fastpath it). Seems to have not regressed anything so just noting this for later investigation.

**Comment by stellaraccident** [comment]
For a frame of reference, this went from a couple dozen consteval transactions to 456. Many are of the form:

```
  func.func @jit_eval_444(%arg0: tensor<4096x32x1xf16>) -> tensor<4096x32xf16> {
    %collapsed = tensor.collapse_shape %arg0 [[0], [1, 2]] : tensor<4096x32x1xf16> into tensor<4096x32xf16>
    return %collapsed : tensor<4096x32xf16>
  }
```

It took 1.4s to compile the whole consteval program. And then about 300us per transaction to evaluate these. Total consteval time was 2.4s.

**Comment by hanhanW** [comment]
Good catch, thanks for reporting this! I have https://github.com/openxla/iree/pull/14872 which should address the issue. I verified that the final vmfb file is as large as before. Please help verify if it addresses your issue, thanks!
