### ISSUE TITLE
Support the new HAL file API in `inline_dynamic` execution mode

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#14878]
The brand new HAL file API introduces new ops, such as `stream.file.constant`, `stream.file.read` and `stream.file.write`.  Unfortunately, these new ops are not supported by `inline_dynamic` execution mode and compilations fails. In particular, I see that patterns to lower these ops in `Dialect/HAL/Conversion/StreamToHAL/Patterns.cpp` are not implemented in `Modules/HAL/Inline/Conversion/StreamToHALInline/Patterns.cpp`.

To repro the specific issue that I'm hitting right now:
```
iree-opt --split-input-file --iree-hal-inline-conversion compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/test/file_ops.mlir
```

Not sure what else is needed to have that fully working with `inline_dynamic`.

This is currently blocking our critical path so it would be great to give this some priority or perhaps provide a workaround.
Thanks!

**Comment by benvanik** [comment]
These ops can be removed as ResourceTryMapOp should always return 1 on these backends and the else of the scf.if that guards them should be dead - they just need some patterns that strip them in StreamToHALInline/Patterns.cpp.
