### ISSUE TITLE
Introduce fused Dequantize+Matmul op with data-tiling and ukernel

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#14905]
https://github.com/openxla/iree/issues/14864 is about a matmul (in this case, a vec-mat) where the big matrix operand is produced by dequantizing narrow integer values. The intended use case is where memory traffic is the overriding concern, so the dequantization is meant to be fused into the matmul. That Issue is about this currently running slow, and the most obvious reason for the slowness is suboptimal codegen, leading one to consider writing a ukernel for this fusion while codegen catches up.

However, if one did overcome all codegen issues or had a good ukernel, the next performance bottleneck would be memory performance issues from not doing data-tiling.  So let's jump right away to doing this right with data-tiling.

In order for SetEncoding to be able to match this fusion and set the appropriate encodings to prepare for data-tiling, it will be good to have this fusion represented as a single op, perhaps something like `LinalgExt::DequantMatmulOp` (naming is tentative for now; to be debated on future PRs introducing that).

MaterializeEncoding will then rewrite that to usual `PackOp`, `UnpackOp`, and a new `LinalgExt::DequantMmt4dOp`.

`DequantMmt4dOp` is what we will have a ukernel for.

Steps:

```mermaid
graph TD;
a1["1. Create a new ukernel, `dequant_mmt4d`, with slow reference code for now.
That will solidify what exactly that op should be doing, and will provide an easy
lowering path for the ops created at the next steps - won't have to think about
lowering to linalg or vectorization etc."]
a2["2. Create the `LinalgExt::DequantMmt4dOp`
and implement its lowering to the `dequant_mmt4d` ukernel."]
a3["3. Create the `LinalgExt::DequantMatmulOp`
and implement data-tiling for it, with MaterializeEncoding picking for now any
dummy tile size and lowering it to `PackOp`, `UnpackOp`,
and a new `LinalgExt::DequantMmt4dOp`."]
a4["4. For some specific CPU ISA, pick appropriate data tile size
and implement a specific ukernel code path."]
a1-->a2-->a3
a1-->a4
```

**Comment by MaheshRavishankar** [comment]
Could we hold off on adding a new op and new encoding here. We already have a custom way of creating dispatches for dequant ops. We can use that as a place to introduce data tiling to experiment with. If we start building ops based on dequant + matmul that can cause an explosion in the number of operations
