### ISSUE TITLE
[CPU] Lower matvec and other "degenerated" matmuls to a more appropriate Linalg representation

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#14947]
It seems like we are currently using `linalg.matmul` to represent any kind of dot product operation, including matvec and 1-D dot products. Linalg also has `linalg.matvec` and `linalg.dot`, which would be really helpful to differentiate these simpler (at least optimization wise) operations from the full matrix multiplication. All these operations require a complex and significantly different optimization strategy and we shouldn't be looking at which dimensions are `1` in a `linalg.matmul` to decide what to do. That would also help remove some of these annoying size `1` dims from the code since we can't do so from a `linalg.matmul` op.

Would it be possible to lower to them directly from StableHLO? These are a few examples that I see internally:
```
%63 = "stablehlo.dot"(%62, %16) {precision_config = [#stab     lehlo<precision DEFAULT>, #stablehlo<precision DEFAULT>]} : (tensor<1x256xf32>, tensor<256x40xf32>) -> tensor<1x40xf32>

%14 = "stablehlo.dot_general"(%10, %13) {dot_dimension_numbers = #stablehlo.dot<lhs_contracting_dimensions = [1], rhs_contracting_dimensions = [1]>, precision_config = [#stablehlo<precision DEFAULT>, #stablehlo<precision DEFAULT>]} : (tensor<20x144xf32>, tensor<1x144xf32>) -> tensor<20x1xf32>

%168 = "stablehlo.dot"(%arg45, %144#2) {precision_config = [#stablehlo<precision DEFAULT>, #stablehlo<precision DEFAULT>]} : (tensor<32xf64>, tensor<32x1xf64>) -> tensor<1xf64>
```

Thoughts? 
@rsuderman, @jpienaar

**Comment by rsuderman** [comment]
Seems pretty fixable. Plan should be a `StableHLOToStableHLO` pattern that identifies MatVec operations and converts them to a standard form, then lowers them to `linalg.matvec`.
