### ISSUE TITLE
Different results for Vulkan target triples while executing llama2

### ISSUE THREAD

**Issue by Abhishek-Varma** [iree-org/iree#14972]
### What happened?

Llama2 7B and 13B yields correct results for vulkan target triple `ampere-rtx4090-windows`, whereas it leads to bad output in `rdna3-w7900-windows`.

I've narrowed it down to originate from dispatch number 3.

### Steps to reproduce your issue

1. [Llama 7B int4 IR](https://storage.googleapis.com/shark_tank/llama2_7b/unsharded/mlir/llama2_7b_int4.mlir)
2. IREE compile for `ampere-rtx4090-windows` (breaking at `dispatch 3`) :
```
iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary  --iree-hal-target-backends=vulkan --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=false --iree-util-zero-fill-elided-attrs --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false --iree-vulkan-target-triple=ampere-rtx4090-windows --iree-opt-const-expr-hoisting=false --iree-hal-dump-executable-sources-to=hal_sources_nvidia --iree-consteval-jit-debug=true --iree-stream-resource-max-allocation-size=3221225472 --iree-flow-break-dispatch=first_vicuna_forward_dispatch_3_ llama2_7b_int4.mlir -o vulkan_correct_7b.vmfb
```
3. IREE compile for `rdna3-w7900-windows` (breaking at `dispatch 3`):
```
iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary  --iree-hal-target-backends=vulkan --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=false --iree-util-zero-fill-elided-attrs --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false --iree-vulkan-target-triple=rdna3-w7900-windows --iree-opt-const-expr-hoisting=false --iree-hal-dump-executable-sources-to=hal_sources_amd --iree-consteval-jit-debug=true --iree-stream-resource-max-allocation-size=3221225472  --iree-flow-break-dispatch=first_vicuna_forward_dispatch_3_ llama2_7b_int4.mlir -o vulkan_faulty_7b.vmfb
```
4. For the INPUT tensor:
```
tensor([[1, 1128, 1784, 11192, 947, 263, 17205, 505, 29973, 673, 297, 3109, 1135, 29871, 29953, 3838]])
```
vulkan_correct_7b.vmfb gives correct output whereas vulkan_faulty_7b.vmfb doesn't.

Same steps for [Llama 13B int4 IR](https://storage.googleapis.com/shark_tank/llama2_13b/unsharded/mlir/llama2_13b_int4.mlir)

### Version information

I verified that this issue is in both IREE/SRT.
```
IREE
    iree-compiler             20230914.645
    iree-runtime              20230914.645
SRT
    iree-compiler             20230913.520
    iree-runtime              20230913.520 
```

### Additional context

I also worked on adding the following script to verify the differing issue via SHARK:
1. [python debug_via_shark.py](https://gist.github.com/Abhishek-Varma/d1de533bd18260559b1b630949e848eb)
2. With the vmfbs generated using the compile commands above (breaking at `dispatch 3`) I observed the following :-
```
7B
ampere-rtx4090-windows
Correct: [-0.269 -0.1919 0.0752 … 0.632 -0.05347 0.378]
rdna3-w7900-windows
Faulty: [0.10675 -0.4026 0.752 … -0.1033 0.624 0.1853]

13B
ampere-rtx4090-windows
Correct: [-0.643 1.396 1.822 … 1.127 1.137 -1.142]
rdna3-w7900-windows
Faulty: [-0.352 0.7744 1.173 … 1.071 1.125 -1.083]
```

**Comment by qedawkins** [comment]
@Abhishek-Varma how did you verify that the results for `ampere` are correct in this case? Is it a matter of quality of generated text?

**Comment by Abhishek-Varma** [comment]
> @Abhishek-Varma how did you verify that the results for `ampere` are correct in this case? Is it a matter of quality of generated text?

Yep, that'll be correct.
`rdna3-w7900-windows` on Windows:
<img width="1303" alt="New_7B_Vulkan_Windows_AMD" src="https://github.com/openxla/iree/assets/19207788/2da59489-24ef-4833-931d-b6ef7beb0e34">

`ampere-rtx4090-window` on Windows:
<img width="1263" alt="New_7B_Vulkan_Windows_NVIDIA" src="https://github.com/openxla/iree/assets/19207788/584b85c5-c0b3-4f4c-8232-a6e307bb2c43">

The same happens for 13B as well.

**Comment by qedawkins** [comment]
Does int8 generate good text on W7900? I'm seeing identical results with int8 codegen comparing against int4. Also does CPU generates good text for int4?

**Comment by Abhishek-Varma** [comment]
I haven't tested int8 on W7900.
@Shukla-Gaurav can you comment on the output of int4 on CPU?

**Comment by qedawkins** [comment]
For context, I'm seeing results closer to the W7900 numbers provided above when breaking on dispatch_3 across multiple settings.
CPU is giving
```
16x4096xf16=[0.106201 -0.394043 0.806152 0.0969238 0.585938 -0.92334 0.996094 0.133057 ...
```
for `int8` codegen (by replacing `i4` with `i8` in the source IR), without the fusion of dynamic dequant + matvec (which is what we used to do and I had thought we verified output for).

Similarly Vulkan is giving something close to the above for the first few elements
```
16x4096xf16=[0.106628 -0.401855 0.751953 0.0961914 0.586914 -1.0127 0.928711 ...
```
for all of the following settings (all on an RDNA3 7900xtx)
 - Default SRT (i4 codegen)
 - Default SRT (i8 codegen)
 - With `--iree-scheduling-optimize-bindings=false`
 - With `CsWaveSize=32` + subgroup size 32 to replicate ampere codegen
 - With the dequant + matvec fusion disabled

**Comment by qedawkins** [comment]
@Abhishek-Varma I was unable to reproduce the `ampere` vs `rdna3` discrepancy but was able to find a problem when comparing against cpu. Can you check whether adding `--iree-spirv-index-bits=64` fixes the discrepancy you're seeing?

**Comment by Abhishek-Varma** [comment]
Hi @qedawkins 

I tried with a fresh setup and have the SRT versions :-
```
iree-compiler             20230918.525
iree-runtime              20230918.525
```

With the above versions, following has been my observations after using `--iree-spirv-index-bits=64` for the `int4` IR attached in the above issue :-
1. `Dispatch 3`: <ins>**_Apologies for the interchange of values reported earlier which gave an incorrect view of the bug_**</ins>. I confirmed the same numbers without `--iree-spirv-index-bits=64` flag as well.
Here is the correct set of discrepancies (I used the script which I've attached in the issue earlier to compare the values) :- 
```
rdna3 => [-0.269   -0.1919   0.0752  ...  0.632   -0.05347  0.378  ] (I incorrectly reported `ampere` here earlier while formatting the issue writeup)

ampere => [ 0.10675 -0.4026   0.752   ... -0.1033   0.624    0.1853 ] (I incorrectly reported `rdna3` here earlier while formatting the issue writeup)
```
2. `Dispatch 6`:
```
rdna3 => [[-0.269   -0.1919   0.0752  ... -2.354    1.087    0.4185 ]
 [ 0.2659  -1.244    1.913   ... -0.6885   0.5947  -0.793  ]
 [ 0.2365  -1.332    1.547   ... -0.576    0.4453  -0.802  ]
 ...
 [-0.11414 -0.3618   0.4163  ...  0.0224  -0.1921  -0.1787 ]
 [ 0.1904  -0.7056   1.407   ... -0.533    0.508   -0.658  ]
 [ 0.129   -1.191    2.023   ... -0.777    0.6475  -0.8604 ]]

ampere => [[ 0.10675 -0.4026   0.752   ... -3.125    1.701   -0.338  ]
 [ 0.207   -1.197    2.023   ... -0.7666   0.577   -0.927  ]
 [ 0.186   -1.211    1.837   ... -0.6973   0.445   -0.9375 ]
 ...
 [-0.03003 -0.4082   1.106   ... -0.4446   0.1421  -0.707  ]
 [ 0.3794  -0.875    1.858   ... -0.8525   0.75    -0.964  ]
 [ 0.1377  -1.16     2.088   ... -0.8555   0.702   -0.985  ]]
 ```
3. `Complete e2e compilation` : 
```
rdna3 => [[-1.201  -1.408   1.585  ... -2.594   3.637   0.5215]
 [-1.261  -1.57    1.67   ... -2.768   3.549   0.4375]
 [-1.268  -1.672   1.66   ... -2.848   3.541   0.419 ]
 ...
 [-1.485  -1.925   1.565  ... -2.715   3.828   0.2451]
 [-1.496  -1.941   1.574  ... -2.707   3.838   0.2578]
 [-1.539  -1.96    1.582  ... -2.664   3.916   0.2002]]
 
ampere => [[ -0.456    -0.6816    0.7715  ...   0.543     0.757     0.571  ]
 [-10.14     -6.617    -1.289   ...  -5.49     -6.97     -7.504  ]
 [ -4.16     -1.201     0.5845  ...  -2.627    -0.6978   -1.768  ]
 ...
 [ -3.328    -5.797     5.113   ...  -0.459    -1.549    -0.02441]
 [ -3.705    -2.938     8.35    ...  -2.36     -3.861    -1.33   ]
 [  1.348     1.863    14.15    ...  -2.477     2.664    -0.4531 ]]
 ```
 4. The above were observed when using the CLI.
      When I use SHARK - By adding the flag `--iree-spirv-index-bits=64` to the llama script it leads to `RESOURCE_EXHAUSTED` for `rdna3` while there seems to be no issue for `ampere`. Strange how this isn't the case in CLI compilation/execution - perhaps an orthogonal issue, but I'm still stating it here nonetheless as this doesn't happen without the flag.
 5. Also, I still get "good output" for `ampere` whereas the `rdna3` yields "bad output".
 
 With the above outputs for individual dispatch breaks and e2e compilation, using `--iree-spirv-index-bits=64`, I confirm that discrepancy in `rdna3` vs `ampere` does indeed exist.

**Comment by MaheshRavishankar** [comment]
If I can ask a stupid question, does the IR vary with the two. If it hasn't already been tried could someone dump the IR and do a diff to see what changed. I recommend adding `--mlir-print-ir-after-all --mlir-disable-threading --mlir-elide-elementsattrs-if-larger=4` . If someone can dump the IR and upload it somewhere I can take a peek.

**Comment by qedawkins** [comment]
The IR does vary between the two due to subgroup size on ampere is 32 instead of 64. I can try getting a dump with that though as all the host code should be the same. For a little more context on why I suggested `--iree-spirv-index-bits=64`, there is a problem related to indexing that seemingly happens to be pushed over the edge by sub-byte types. In short, we end up multiplying the byte offset by 2 to recover the element offset and then subsequently scale back down by 8 to do a load aligned on 32 bits, however doubling the byte offset already pushed it past the limit of i32 and causes a seemingly random dispatch in the middle of the model to start emitting completely wrong results (at least this is my interpretation of what was happening).

As a result, `--iree-spirv-index-bits=64` fixed it because we would do the indexing bit width with 64 bits (addressing is still 32). Also `--iree-scheduling-optimize-bindings=false` fixed it because the offset would be zero.

**Comment by MaheshRavishankar** [comment]
Well, let's fix this issue, but we should just migrate to use `EmulateNarrowTypes` on SPIRV asap. @yzhang93 could we pick that up again. Cc @kuhar and @antiagainst

**Comment by antiagainst** [comment]
Great catch, thanks @qedawkins!!
