### ISSUE TITLE
int4 x int4 matmul from StableHLO causes illegal 'memref.subview'

### ISSUE THREAD

**Issue by phoenix-meadowlark** [iree-org/iree#14989]
### What happened?

Compiling the following IR from JAX for a fully quantized matmul causes the error below to be thrown:

```mlir
module @jit_quantized_matmul attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<128x256xi4> {mhlo.sharding = "{replicated}"}, %arg1: tensor<256x512xi4> {mhlo.sharding = "{replicated}"}) -> (tensor<128x512xi32> {jax.result_info = ""}) {
    %0 = stablehlo.dot_general %arg0, %arg1, contracting_dims = [1] x [0], precision = [DEFAULT, DEFAULT] : (tensor<128x256xi4>, tensor<256x512xi4>) -> tensor<128x512xi32>
    return %0 : tensor<128x512xi32>
  }
}

```

```mlir
iree-compile --iree-hal-target-backends=llvm-cpu --iree-input-type=stablehlo /tmp/int4_int4_matmul.mlir -o /tmp/int4_int4_matmul.vmfb
/tmp/int4_int4_matmul.mlir:3:10: error: failed to legalize operation 'memref.subview' that was explicitly marked illegal
    %0 = stablehlo.dot_general %arg0, %arg1, contracting_dims = [1] x [0], precision = [DEFAULT, DEFAULT] : (tensor<128x256xi4>, tensor<256x512xi4>) -> tensor<128x512xi32>
         ^
/tmp/int4_int4_matmul.mlir:2:3: note: called from
  func.func public @main(%arg0: tensor<128x256xi4> {mhlo.sharding = "{replicated}"}, %arg1: tensor<256x512xi4> {mhlo.sharding = "{replicated}"}) -> (tensor<128x512xi32> {jax.result_info = ""}) {
  ^
/tmp/int4_int4_matmul.mlir:3:10: note: see current operation: %46 = "memref.subview"(%27, %45, %42) <{operandSegmentSizes = array<i32: 1, 2, 0, 0>, static_offsets = array<i64: -9223372036854775808, -9223372036854775808>, static_sizes = array<i64: 8, 16>, static_strides = array<i64: 1, 1>}> : (memref<128x256xi4>, index, index) -> memref<8x16xi4, strided<[256, 1], offset: ?>>
    %0 = stablehlo.dot_general %arg0, %arg1, contracting_dims = [1] x [0], precision = [DEFAULT, DEFAULT] : (tensor<128x256xi4>, tensor<256x512xi4>) -> tensor<128x512xi32>
         ^
/tmp/int4_int4_matmul.mlir:3:10: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"llvm-cpu", "embedded-elf-x86_64", {cpu = "generic", cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf", ukernels = false}>
    %0 = stablehlo.dot_general %arg0, %arg1, contracting_dims = [1] x [0], precision = [DEFAULT, DEFAULT] : (tensor<128x256xi4>, tensor<256x512xi4>) -> tensor<128x512xi32>
         ^
```

[Full error](https://gist.github.com/phoenix-meadowlark/24486279cd8ed9b0debddd423b8bf42e).

### Steps to reproduce your issue

Tested compiling to the `llvm-cpu` backend.

### What component(s) does this issue relate to?

Frontends, Compiler

### Version information

2f72249fcbc310d41a179e76344f1a853e0547b9

**Comment by qcolombet** [comment]
cc @MaheshRavishankar 
This fails in the `EmulateNarrowTypePass`.

**Comment by stellaraccident** [comment]
I'm just going to create an auto responder which posts that on every issue, and I think it will be right a lot :)

Would be good to robustify this. It isn't clear to me if it just needs more work/tests or has design issues that are making it hard to be comprehensive.

**Comment by qcolombet** [comment]
> Would be good to robustify this. It isn't clear to me if it just needs more work/tests or has design issues that are making it hard to be comprehensive.

I cannot really comment on the design aspect of it, I didn't follow how any of this was plumbed through, but I am surprised that we care about `memref` operations other than `load` and `store` and hence choke on them.

Aside from load/store, everything should be just pointer arithmetic (and make the type system happy), which IMHO should not need to be massaged. But I may be missing something.

**Comment by MaheshRavishankar** [comment]
I am not sure there are any design issues. We do care only about `memref.load/memref.store`. Will repro and look at it.

**Comment by MaheshRavishankar** [comment]
Hmmm... I cant repro this error on  ToT.

```
$ ./repro.sh
+ IREE_ROOT_DIR=/home/mahesh/iree
+ BUILD_TYPE=RelWithDebInfo
+ IREE_SOURCE_DIR=/home/mahesh/iree/iree
+ IREE_BUILD_DIR=/home/mahesh/iree/build/RelWithDebInfo
+ IREE_TOOLS_DIR=/home/mahesh/iree/build/RelWithDebInfo/tools
+ IREE_COMPILE=/home/mahesh/iree/build/RelWithDebInfo/tools/iree-compile
+ /home/mahesh/iree/build/RelWithDebInfo/tools/iree-compile --iree-hal-target-backends=llvm-cpu --iree-input-type=stablehlo -o output.vmfb repro.mlir
mahesh@mahesh-dev:~/iree/scratchspace/issues/14989$ ls
output.vmfb  repro.mlir  repro.sh  repro.sh~
```

**Comment by phoenix-meadowlark** [comment]
> Hmmm... I cant repro this error on ToT.
> 
> ```
> $ ./repro.sh
> + IREE_ROOT_DIR=/home/mahesh/iree
> + BUILD_TYPE=RelWithDebInfo
> + IREE_SOURCE_DIR=/home/mahesh/iree/iree
> + IREE_BUILD_DIR=/home/mahesh/iree/build/RelWithDebInfo
> + IREE_TOOLS_DIR=/home/mahesh/iree/build/RelWithDebInfo/tools
> + IREE_COMPILE=/home/mahesh/iree/build/RelWithDebInfo/tools/iree-compile
> + /home/mahesh/iree/build/RelWithDebInfo/tools/iree-compile --iree-hal-target-backends=llvm-cpu --iree-input-type=stablehlo -o output.vmfb repro.mlir
> mahesh@mahesh-dev:~/iree/scratchspace/issues/14989$ ls
> output.vmfb  repro.mlir  repro.sh  repro.sh~
> ```

This was incidentally fixed by https://github.com/openxla/iree/pull/14988.

If the failure is further down the stack and fixing it is still be relevant you can use 2f72249fcbc310d41a179e76344f1a853e0547b9 to reproduce it. Otherwise feel free to close this!

**Comment by phoenix-meadowlark** [comment]
Also, would it make sense for me to add this as a test somewhere?

**Comment by MaheshRavishankar** [comment]
I think this was not relevant to type emulation, the error was just caught there. I am closing this. Adding a test case would be nice, but it needs to be tracked down to the root issue (I am not looking into it).
