### ISSUE TITLE
Schedule Allocation can break buffer dependencies for `async.dispatch`

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#15007]
Depending whether a constant is read from a global value or constant value we are getting different results. Test program attached: https://gist.github.com/rsuderman/38e2752e697a02bd98f0ec4b9bd82aa8

So far a number of things have been narrowed down:
- `--iree-execution-model=inline-dynamic` appears to fix the issue
- increasing tensor dimensions to `4x4x4xi32` fixes the issue
- moving the global case first makes both cases pass
- enabling `iree-flow-trace-dispatch-tensors` fixes the issue

This feels like a nasty concurrency or dependency issue

**Comment by rsuderman** [comment]
Whats more interesting is that swapping triggers the numerical difference. The following two programs are identical minus ordering:

Broken: https://gist.github.com/rsuderman/0a45f821bcba989a6731be4fc683a0fa
Working: https://gist.github.com/rsuderman/0a54de6520f355d6ca34615c4c66788b

It appears the continue breaking if const eval, constant hoisting, or inline dynamic execution are enabled.

**Comment by rsuderman** [comment]
One version of the error appears to be related to loading from globals. During HAL loader conversion the file read to MLGlobals is dropped:
https://gist.github.com/rsuderman/141ba49eef76895676d9769b3788c033

@bviyer is going to look into a fix

Checking what the cause is for the non inline case

**Comment by rsuderman** [comment]
Repro found:
https://gist.github.com/rsuderman/ee970962b2a22620e66fb287f091b507

It appears the ScheduleAllocation can cause incorrect buffer dependencies when containing a `async.dispatch` operations. This can be observed  as the final dispatch in the above sample ends up point to an un-written to allocation instead of the result from the previous dispatch.

**Comment by benvanik** [comment]
![image](https://github.com/openxla/iree/assets/75337/e7098b1d-df3a-46dd-8b3c-63f6b796ffa0)

**Comment by rsuderman** [comment]
Should I look into fixing or should I leave it to you? Reading through `ScheduleAllocation` it sounds like a rewrite has been considered previously.

![garbage-kevin](https://github.com/openxla/iree/assets/5508949/6408a3a3-aaa3-4459-889b-15a7626af715)

**Comment by benvanik** [comment]
![image](https://github.com/openxla/iree/assets/75337/6dd5dd80-28ec-46d8-a0a5-2a43868f453c)
(I'll look deeper next week, just memeing now :)

**Comment by mariecwhite** [comment]
Could this be related to the accuracy errors for larger batch sizes? https://github.com/openxla/iree/issues/14601

**Comment by rsuderman** [comment]
> Could this be related to the accuracy errors for larger batch sizes? #14601

It could be. There is a pretty easy way to check - we just need to disable concurrent execution.

**Comment by jpienaar** [comment]
Skipping ScheduleConcurrency pass avoids the RNG failure, now I'm pretty sure that would decrease performance, but is that an option until this is triaged? (seems this would result in rather non-trivial numerical issues)

I also don't quite understand how to see that this pass is doing the wrong thing in Rob's example, the output post pass is:

```mlir
module {
  util.global private mutable @_constant__timepoint = #stream.timepoint<immediate> : !stream.timepoint
  util.global private @_constant : !stream.resource<constant>
  util.global private mutable @global_hlo_rng_state__timepoint = #stream.timepoint<immediate> : !stream.timepoint
  util.global private mutable @global_hlo_rng_state : !stream.resource<variable>
  func.func @rng_uniform_3d() -> (!hal.buffer_view, !hal.buffer_view) {
    %c0 = arith.constant 0 : index
    %c16 = arith.constant 16 : index
    %c32 = arith.constant 32 : index
    %global_hlo_rng_state__timepoint = util.global.load @global_hlo_rng_state__timepoint : !stream.timepoint
    %global_hlo_rng_state = util.global.load @global_hlo_rng_state : !stream.resource<variable>
    %_constant__timepoint = util.global.load @_constant__timepoint : !stream.timepoint
    %_constant = util.global.load @_constant : !stream.resource<constant>
    %0 = stream.timepoint.join max(%_constant__timepoint, %global_hlo_rng_state__timepoint) => !stream.timepoint
    %c0_0 = arith.constant 0 : index
    %1:3 = stream.resource.pack slices({
      [0, 0] = %c32,
      [0, 0] = %c32
    }) : index
    %result, %result_timepoint = stream.resource.alloca uninitialized await(%0) => !stream.resource<external>{%1#0} => !stream.timepoint
    %2 = stream.resource.subview %result[%1#1] : !stream.resource<external>{%1#0} -> !stream.resource<external>{%c32}
    %3 = stream.resource.subview %result[%1#2] : !stream.resource<external>{%1#0} -> !stream.resource<external>{%c32}
    %4:3 = stream.resource.pack slices({
      [1, 1] = %c32,
      [0, 2] = %c32
    }) : index
    %result_1, %result_timepoint_2 = stream.resource.alloca uninitialized await(%0) => !stream.resource<transient>{%4#0} => !stream.timepoint
    %5 = stream.timepoint.join max(%0, %result_timepoint, %result_timepoint_2) => !stream.timepoint
    %6 = arith.addi %4#1, %c16 : index
    %7 = stream.cmd.execute await(%5) => with(%_constant as %arg0: !stream.resource<constant>{%c32}, %global_hlo_rng_state as %arg1: !stream.resource<variable>{%c16}, %2 as %arg2: !stream.resource<external>{%c32}, %3 as %arg3: !stream.resource<external>{%c32}, %result_1 as %arg4: !stream.resource<transient>{%4#0}) {
      stream.cmd.concurrent {
        stream.cmd.dispatch @rng_uniform_3d_dispatch_0::@rng_uniform_3d_dispatch_0_generic_8_i32 {
          ro %arg0[%c0 for %c32] : !stream.resource<constant>{%c32},
          wo %arg2[%c0_0 for %c32] : !stream.resource<external>{%c32}
        }
        stream.cmd.dispatch @rng_uniform_3d_dispatch_1::@rng_uniform_3d_dispatch_1_generic_4_i32 {
          ro %arg1[%c0 for %c16] : !stream.resource<variable>{%c16},
          rw %arg4[%4#1 for %c16] : !stream.resource<transient>{%4#0},
          ro %arg4[%6 for %c16] : !stream.resource<transient>{%4#0}
        }
      }
      stream.cmd.dispatch @rng_uniform_3d_dispatch_0::@rng_uniform_3d_dispatch_0_generic_8_i32 {
        ro %arg4[%4#2 for %c32] : !stream.resource<transient>{%4#0},
        wo %arg3[%c0_0 for %c32] : !stream.resource<external>{%c32}
      }
    } => !stream.timepoint
    %8 = stream.resource.dealloca await(%7) => %result_1 : !stream.resource<transient>{%4#0} => !stream.timepoint
    %9 = stream.timepoint.join max(%8, %7) => !stream.timepoint
    %10:2 = stream.timepoint.await %9 => %2, %3 : !stream.resource<external>{%c32}, !stream.resource<external>{%c32}
    %11 = stream.tensor.export %10#0 : tensor<2x2x2xi32> in !stream.resource<external>{%c32} -> !hal.buffer_view
    %12 = stream.tensor.export %10#1 : tensor<2x2x2xi32> in !stream.resource<external>{%c32} -> !hal.buffer_view
    return %11, %12 : !hal.buffer_view, !hal.buffer_view
  }
}
```

The last dispatch here reads from arg4 which is transient and writes to arg3 which is external, and arg4 was written to. So not sure how to see this is wrong (potentially a more general question about how one debug these, but hey we have a failure here to learn from :) )

**Comment by allieculp** [comment]
@benvanik Any update on this one?

**Comment by allieculp** [comment]
@benvanik is this still open?

**Comment by rsuderman** [comment]
@allieculp @jpienaar @benvanik looks like whatever the source issue of this bug was it is not fixed. Closing.
