### ISSUE TITLE
GPTQ: Vmfb Size is Double of the IR size

### ISSUE THREAD

**Issue by vivekkhandelwal1** [iree-org/iree#15017]
### What happened?

Hi, while compiling the [falcon-7b-instruct-GPTQ](https://huggingface.co/TheBloke/falcon-7b-instruct-GPTQ) model, the size of the [Linalg IR](https://storage.googleapis.com/shark_tank/falcon/falcon_7b_gptq_linalg.mlir) I get is 7.7GB, on the other hand after the iree-compile the [vmfb](https://storage.googleapis.com/shark_tank/falcon/falcon_7b_gptq_cpu.vmfb) which I'm getting is of 13.4GB. I'm not able to understand how's this possible. Also, is this expected or not? The issue exists for both the CPU and CUDA backend. You can find the elided Linalg IR [here](https://gist.github.com/vivekkhandelwal1/8104982239e89e3be22730909fbb43d6).

### Steps to reproduce your issue

To reproduce the issue, run the following compilation command:
```
iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary     --iree-hal-target-backends=llvm-cpu --mlir-print-debuginfo     --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host     --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64     --iree-vm-bytecode-module-strip-source-map=false --iree-util-zero-fill-elided-attrs     --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false --iree-hal-dump-executable-sources-to=hal_sources_falcon_7b_gptq_cpu    --iree-consteval-jit-debug=true   --iree-stream-resource-max-allocation-size=3221225472 --iree-llvmcpu-target-triple=x86_64-linux-gnu falcon_7b_gptq_linalg.mlir -o falcon_7b_gptq_cpu.vmfb
```
over the following [Linalg IR](https://storage.googleapis.com/shark_tank/falcon/falcon_7b_gptq_linalg.mlir).

### What component(s) does this issue relate to?

MLIR, Compiler

**Comment by stellaraccident** [comment]
This isn't reproing on the stripped weights model. I'll need to dig in deeper and verify the problem. Pretty sure this is missing IPO aware CSE of const trees but would like to be certain before setting out to fix it. It's probably not more than a day of work to add the optimizations needed, and I will try to get to it tomorrow.

**Comment by stellaraccident** [comment]
The first thing I was thinking of appears to not be the major problem. These two constants (I think) are being duplicated:

```
  func.func @jit_eval_4(%arg0: tensor<32000x4096xf16>) -> tensor<4096x32000xf16> {                        
    %0 = tensor.empty() : tensor<4096x32000xf16>                                                                            
    %1 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1, d0)>], iterator_types = ["parallel", "parallel"]} ins(%arg0 : tensor<32000x4096xf16>) outs(%0 : tensor<4096x32000xf16>) {
    ^bb0(%in: f16, %out: f16):
      linalg.yield %in : f16
    } -> tensor<4096x32000xf16>                                                                                                                                                                                                                         
    return %1 : tensor<4096x32000xf16>                                                                                      
  }
  func.func @jit_eval_1(%arg0: tensor<32000x4096xf16>) -> tensor<4096x32000xf16> {                                    
    %0 = tensor.empty() : tensor<4096x32000xf16>                                                                            
    %1 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1, d0)>], iterator_types = ["parallel", "parallel"]} ins(%arg0 : tensor<32000x4096xf16>) outs(%0 : tensor<4096x32000xf16>) {
    ^bb0(%in: f16, %out: f16):                                                                                              
      linalg.yield %in : f16                                                                                                
    } -> tensor<4096x32000xf16>                                                                                             
    return %1 : tensor<4096x32000xf16>                                                                                      
  } 
```

However, this only accounts for ~128MB of duplication. So needs to be looked at but not our main problem. Still searching.

**Comment by stellaraccident** [comment]
FYI - this IR is from before the maxf rename. I fixed it up with: `sed -i 's/arith.maxf/arith.maximumf/g' falcon_7b_gptq_linalg.mlir`

**Comment by stellaraccident** [comment]
Hey Vivek, when I set out on this, I think I misunderstood that this was going to be similar to our existing llama2 models, but this is quite different, which now that I read it, is expected since you are working on an entirely new quantization system.

This is a real torture test for ConstEval, doing 411 constant expression tree simplifications (with a lot of multi-rooted expressions and complicated conditionals) and taking 231s to do them all on my machine (most other models I've seen have ~a couple dozen at most). Considering that this is the most complicated such thing we've yet seen by a long shot, I guess as a starting point, I'm glad it works at all.

Can you give me some more context on what is going on here? I'm not familiar with the model and its signature doesn't make much sense to me.

Also, could you describe the quantization regime that is being done here? It looks like it is quantizing to i8 in some fashion?

Just to set expectations, this is going to take some more digging and I'll need to develop some better tools for analyzing what is going on. Also, would be good to pump it through Turbine at some point as it represents things better with symbolic names that are much easier to track through.

**Comment by vivekkhandelwal1** [comment]
> Hey Vivek, when I set out on this, I think I misunderstood that this was going to be similar to our existing llama2 models, but this is quite different, which now that I read it, is expected since you are working on an entirely new quantization system.
> 
> This is a real torture test for ConstEval, doing 411 constant expression tree simplifications (with a lot of multi-rooted expressions and complicated conditionals) and taking 231s to do them all on my machine (most other models I've seen have ~a couple dozen at most). Considering that this is the most complicated such thing we've yet seen by a long shot, I guess as a starting point, I'm glad it works at all.
> 
> Can you give me some more context on what is going on here? I'm not familiar with the model and its signature doesn't make much sense to me.
> 
> Also, could you describe the quantization regime that is being done here? It looks like it is quantizing to i8 in some fashion?
> 
> Just to set expectations, this is going to take some more digging and I'll need to develop some better tools for analyzing what is going on. Also, would be good to pump it through Turbine at some point as it represents things better with symbolic names that are much easier to track through.

Hi @stellaraccident, thanks for taking a look at this issue. The quantization for the model is done as follows:
The weights are packed to `si32` tensors using the `pack` method here https://github.com/PanQiWei/AutoGPTQ/blob/51c043c6bef1380e121474ad73ea2a22f2fb5737/auto_gptq/nn_modules/qlinear/qlinear_cuda.py#L96 during the quantization. Although we are not doing the quantization on the fly, we are just using the pre-quantized model.

During the execution, the unpacking/dequant and matmul happens here: https://github.com/PanQiWei/AutoGPTQ/blob/51c043c6bef1380e121474ad73ea2a22f2fb5737/auto_gptq/nn_modules/qlinear/qlinear_cuda.py#L214-L270
