### ISSUE TITLE
Canonicalize SubViewParts fetches incorrect result type

### ISSUE THREAD

**Issue by Abhishek-Varma** [iree-org/iree#15016]
### What happened?

For [this dispatch](https://gist.github.com/Abhishek-Varma/89a07ea1eb939695d8774b992f8c7c9b) and the following compilation command :-
```
iree-compile --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-embedded-linker-path=/home/abhishek/avarma_iree/build/compiler/bindings/python/iree/compiler/_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-llvmcpu-target-triple=x86_64-linux-gnu --iree-opt-data-tiling --iree-llvmcpu-enable-microkernels --iree-llvmcpu-stack-allocation-limit=256000 --iree-stream-resource-max-allocation-size=4294967295 --iree-vm-bytecode-module-strip-source-map=true --iree-util-zero-fill-elided-attrs --iree-opt-strip-assertions=true --verify=false dispatch_10.mlir
```
It crashes at [llvm-project's ChainedTensorCast](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/Tensor/IR/TensorOps.cpp#L393-L394) because of operating on a `NULL` value.
The reason was it was trying to deal with the following shapes :-
```
Source :               %11 = flow.dispatch.tensor.load ... <3x1x16x257x88xf16> -> tensor<16x?xf16> 
Intermediate :         %cast = tensor.cast %11 : tensor<16x?xf16> to tensor<?x?x?xf16> 
Dest :                 %cast_0 = tensor.cast %cast : tensor<?x?x?xf16> to tensor<16x?x1xf16> 
```
I tried fixing it by decoupling the `joinShapes` - and the compilation succeeded.

But this turned out to be a red-herring because on closer inspection I found that the IR after canonicalization was being ill-formed - I saw quotes `""` around the operation and they weren't in their assembly format - I've removed it in the above section for readability.

On further inspection I traced this originating from [IREE's DispatchTensorLoadOpWithOffsetSizesAndStridesConstantArgumentFolder](https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp#L586).
And this further led me to finally trace that the issue is with [canonicalizeSubViewParts](https://github.com/openxla/iree/blob/4cb46cb0f09663ab1151e4da83bbfd5a516f51fc/compiler/src/iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp#L574).

For the following op (in the above dispatch) :-
```
%11 = flow.dispatch.tensor.load %4,
             offsets = [1, 0, %arg0, %10, %arg2],
             sizes = [1, 1, %c16, %9, %c1],      <---------- getDroppedDims and canonicalizeSubViewParts
             strides = [1, 1, 1, 1, 1]
        : !flow.dispatch.tensor<readonly:tensor<3x1x16x257x88xf16>> -> tensor<?x?x?xf16> 
```
`getDroppedDims()`, ideally, should have asked to DROP `0` and `1` dimension only, but it also says to DROP `4`th dimension as well and incorrectly yields `tensor<16x?xf16>` instead of `tensor<16x?x1xf16>`!

This is the fix for the above issue : [Fix canonicalizeSubViewParts](https://gist.github.com/Abhishek-Varma/f4496ab6205904aa2d7ccb47c1cdb22e).

I didn't think it'd be appropriate to change the implementation of `getDroppedDims` itself hence added the fix in the canonicalization and the issue gets fixed.

Let me know if I can go ahead with adding this fix (with appropriate test case) OR the dispatch itself is ill-formed (in which case please give me pointers to triage this).

**Comment by Abhishek-Varma** [comment]
This is for the Vision Model's compilation.
CC: @MaheshRavishankar @qedawkins @powderluv

**Comment by Abhishek-Varma** [comment]
Update:

I made changes to [getDroppedDimsImpl](https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp#L108-L129).

Following is the [commit for the fix](https://github.com/openxla/iree/compare/main...Abhishek-Varma:iree:fix_subview_parts) but this turned out to open many can of worms.

Perhaps the IR is indeed "ill-formed" ?

I've added a test case too to narrow down the scenario I'm trying to add this fix for.

**Comment by MaheshRavishankar** [comment]
So before I looked further, whats the issue with dropping the `innermost` size 1 dimension as well?

**Comment by MaheshRavishankar** [comment]
I submitted a PR to fix this issue.
