### ISSUE TITLE
[LLVMCPU] Support masked loads for sub-byte power of 2 types

### ISSUE THREAD

**Issue by qedawkins** [iree-org/iree#15031]
[This dispatch](https://gist.github.com/qedawkins/712513b87a786aea63e7dbad0492fc9b) will fail to compile without the kernel dispatch changes in #15018 due to the generation of masked loads of sub-byte types.

```
iree-compile \
        --iree-input-type=none \
        --iree-hal-target-backends=llvm-cpu \
        --iree-llvmcpu-target-triple=x86_64-unknown-linux \
        --iree-stream-resource-index-bits=64 \
        --iree-vm-target-index-bits=64 \
        --compile-from=flow \
        dispatch.mlir \
        -o /tmp/module.vmfb
```

```
sources/module_second_vicuna_forward_dispatch_30.mlir:39:15: error: failed to legalize operation 'memref.subview' that was explicitly marked illegal
        %22 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0)>], iterator_types = ["parallel", "reduction", "reduction"]} ins(%18, %21 : tensor<86x128xf16>, tensor<4096x86x128xf16>) outs(%19 : tensor<4096xf16>) {
              ^
sources/module_second_vicuna_forward_dispatch_30.mlir:39:15: note: see current operation: %58 = "memref.subview"(%30, %57, %42, %53, %45) <{operandSegmentSizes = array<i32: 1, 3, 1, 0>, static_offsets = array<i64: -9223372036854775808, -9223372036854775808, -9223372036854775808>, static_sizes = array<i64: 8, -9223372036854775808, 16>, static_strides = array<i64: 1, 1, 1>}> : (memref<4096x86x128xi4, strided<[11008, 128, 1], offset: ?>>, index, index, index, index) -> memref<8x?x16xi4, strided<[11008, 128, 1], offset: ?>> 
// -----// IR Dump After EmulateNarrowType Failed (iree-codegen-emulate-narrow-type) //----- //
```
for example, the following load remains a live user.
```
    %23 = affine.min affine_map<()[s0] -> (-s0 + 86, 8)>()[%20]
    %26 = vector.create_mask %23, %c16 : vector<8x16xi1>
    %33 = vector.extract %26[0] : vector<8x16xi1>
    %34 = vector.maskedload %subview_6[%c0, %c0], %33, %cst_0 : memref<?x16xf16, strided<[128, 1], offset: ?>>, vector<16xi1>, vector<16xf16> into vector<16xf16>
```
#15024 disables vector masking when sub-byte types are present, however we should support the simpler masked load cases that we typically see.

**Comment by dcaballe** [comment]
Thanks for tracking this. I think a good starting point would be to add support for masked ops assuming they are generated by a `vector.create_mask` or `vector.constant_mask` op, which implies they have the form [0, 0, 0, ..., 1, 1, 1]. I would start by adding patterns so that the mask operation is fed with a new `vector.create_mask` or `vector.constant_mask` op with the "compressed" mask. E.g., if we have a maskedload that takes a `vector.constant_mask 3 : vector<6xi4>`, replace the latter with `vector.constant_mask 2 : vector<3xi8>`. It looks like the "compression ratio" is just `size(i8)/size(i4) = 2`, and then we just have to ceiling divide the shape dim and the constant mask argument by that ratio?

**Comment by qedawkins** [comment]
The create_mask and constant_mask cases make sense to me. We might need to fold `vector.extract` into constant/create masks as well as the examples I see have something like this immediately before EmulateNarrowTypes
```
%27 = vector.create_mask %c8, %23, %c16 : vector<8x8x16xi1>
%73 = vector.extract %27[1, 0] : vector<8x8x16xi1>
%74 = vector.maskedload %subview_7[%c1, %c0, %c0], %73, %cst_2 : memref<8x?x16xi4, strided<[11       008, 128, 1], offset: ?>>, vector<16xi1>, vector<16xi4> into vector<16xi4>
```
`extract(constant/create_mask)` should still have the same easy compressibility property as the ops themselves.

**Comment by allieculp** [comment]
@qedawkins Are you working on this one? Looking to track down some assignees.

**Comment by qedawkins** [comment]
> @qedawkins Are you working on this one? Looking to track down some assignees.

I'm not working on this right now. Other takers would be welcome!

**Comment by dcaballe** [comment]
We already have someone internally looking at it but they are not on our github yet

**Comment by allieculp** [comment]
@dcaballe is this still being looked at? Or have resources shifted?

**Comment by dcaballe** [comment]
First patch under review: https://github.com/llvm/llvm-project/pull/68443

**Comment by allieculp** [comment]
Looks like this is merged. What are the next steps here?

**Comment by dcaballe** [comment]
@qedawkins, would you mind checking what happens if we re-enable masking for sub-byte types on the impacted dispatch/model? We should check that correctness is ok but we can also check performance on CI, if the model is there (I don't have high expectations for performance :)).

**Comment by qedawkins** [comment]
> @qedawkins, would you mind checking what happens if we re-enable masking for sub-byte types on the impacted dispatch/model? We should check that correctness is ok but we can also check performance on CI, if the model is there (I don't have high expectations for performance :)).

Correctness should be tested on the CI now (PkgCI regression test) so #15335 re-enables it. Performance is also tested, but I don't think there is any number it actually checks against, + the impacted model is currently using a different path for performance out-of-tree (not everything we need is enabled by default currently), so regressions on the defaults are fine IMO if it is to unblock this work.

**Comment by qedawkins** [comment]
Unfortunately looks like it's still failing: https://github.com/openxla/iree/actions/runs/6678684638/job/18150097607?pr=15335

The above reproducer still mostly works, with this new IR (there were some syntax changes to hal.executable.variant) https://gist.github.com/qedawkins/281cf46f20d60e91803bb6529721f347

Currently I am seeing
```
base_ir/dispatch.mlir:39:15: error: failed to legalize operation 'memref.subview' that was explicitly marked illegal
        %22 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0)>], iterator_types = ["parallel", "reduction", "reduction"]} ins(%18, %21 : tensor<86x128xf16>, tensor<4096x86x128xf16>) outs(%19 : tensor<4096xf16>) {
              ^
base_ir/dispatch.mlir:39:15: note: see current operation: %57 = "memref.subview"(%30, %56, %42, %52, %45) <{operandSegmentSizes = array<i32: 1, 3, 1, 0>, static_offsets = array<i64: -9223372036854775808, -9223372036854775808, -9223372036854775808>, static_sizes = array<i64: 8, -9223372036854775808, 16>, static_strides = array<i64: 1, 1, 1>}> : (memref<4096x86x128xi4, strided<[11008, 128, 1], offset: ?>>, index, index, index, index) -> memref<8x?x16xi4, strided<[11008, 128, 1], offset: ?>>
base_ir/dispatch.mlir:8:5: error: 'builtin.module' op failed to emulate bit width
    builtin.module {
```
so something is still going wrong, as I'm still seeing masked loads of sub-byte types persist
```
%88 = "vector.maskedload"(%55, %17, %8, %17, %87, %3) : (memref<8x?x16xi4, strided<[11008, 128, 1], offset: ?>>, index, index, index, vector<16xi1>, vector<16xi4>) -> vector<16xi4>
```

**Comment by qedawkins** [comment]
After a closer look, it seems like there are just some `vector.extract`s getting in the way of https://github.com/llvm/llvm-project/pull/68443/files#diff-f68461cf7c8ed8c292a7498aa2e86a5b3e741a68543a0c3397b74138158de5ebR208

I see
```
%27 = vector.create_mask %c8, %23, %c16 : vector<8x8x16xi1>
%57 = vector.extract %27[0, 3] : vector<16xi1> from vector<8x8x16xi1>
%58 = vector.maskedload %subview_7[%c0, %c3, %c0], %57, %cst_2 : memref<8x?x16xi4, strided<[11008, 128, 1], offset: ?>>, vector<16xi1>, vector<16xi4> into vector<16xi4>
```

**Comment by qedawkins** [comment]
sorry, after another closer look it seems like this should already be happening: https://github.com/llvm/llvm-project/pull/68443/files#diff-f68461cf7c8ed8c292a7498aa2e86a5b3e741a68543a0c3397b74138158de5ebR200

**Comment by qedawkins** [comment]
Ok so the actual problem seems to be missing support for dynamic subview: https://github.com/llvm/llvm-project/blob/b1554fe080e8b074a30f2a4cb88666bdb7b1ce9e/mlir/lib/Dialect/MemRef/Transforms/EmulateNarrowType.cpp#L262

Because masking also generates dynamic subviews like this, we are missing the pattern to handle
```
%subview_7 = memref.subview %10[%31, %20, %28] [8, %23, 16] [1, 1, 1] : memref<4096x86x128xi4, strided<[11008, 128, 1], offset: ?>> to memref<8x?x16xi4, strided<[11008, 128, 1], offset: ?>>
```

`FoldMemRefAliasOps` runs right before narrow type emulation, but I guess such a subview isn't foldable.

**Comment by tyb0807** [comment]
Thanks @qedawkins for taking a look. So do you have an idea of whether it's feasible to add support for dynamic subviews  when emulating narrow types?

**Comment by qedawkins** [comment]
> Thanks @qedawkins for taking a look. So do you have an idea of whether it's feasible to add support for dynamic subviews when emulating narrow types?

Tagging @MaheshRavishankar and @hanhanW who have more context on the patterns there and how we might want to handle this.

**Comment by hanhanW** [comment]
> Thanks @qedawkins for taking a look. So do you have an idea of whether it's feasible to add support for dynamic subviews when emulating narrow types?

Yes, I think we are able to support the case. The upstream emulation patterns we've been developing has the test. See https://github.com/llvm/llvm-project/blob/a396fb247e0719f56a830a9e4aab0449be7f843a/mlir/test/Dialect/MemRef/emulate-narrow-type.mlir#L99-L103

```mlir
func.func @memref_load_i4_dynamic(%arg0: index, %arg1 : index, %arg2 : index, %arg3 : index) -> i4 {
  %0 = memref.alloc(%arg0, %arg1) : memref<?x?xi4>
  %1 = memref.load %0[%arg2, %arg3] : memref<?x?xi4>
  return %1 : i4
}
```

**Comment by MaheshRavishankar** [comment]
Actually you cant really support n-d subviews since the emulation requires linear memref types. All patterns effectively fold the multi dimensional memrefs into a 1d memref. You can't do that for subviews. Only 1d subviews are supported, mostly for testing. The expectation is that you fold all the subviews into it's consumers using the `FoldMemrefAlias` pass.

**Comment by tyb0807** [comment]
Currently `FoldMemRefAliasOps` does not handle folding subviews into maskedloads, I'll go ahead and try to implement this pattern.

**Comment by tyb0807** [comment]
@qedawkins Do we want to merge https://github.com/openxla/iree/pull/15335 now?

**Comment by qedawkins** [comment]
> @qedawkins Do we want to merge #15335 now?

We need integrate to pull in https://github.com/llvm/llvm-project/pull/71380 first
