### ISSUE TITLE
INTERNAL; CUDA driver error 'CUDA_ERROR_ILLEGAL_ADDRESS' for Llama

### ISSUE THREAD

**Issue by Abhishek-Varma** [iree-org/iree#15041]
### What happened?

For the [llama IR](https://storage.googleapis.com/shark_tank/MiniGPT4/first_llama_int4_1700.mlir), after compiling with `iree-compile` (see the command below), I get the following runtime error :-
```
RuntimeError: Error invoking function: SHARK-Runtime/runtime/src/iree/hal/drivers/cuda/stream_command_buffer.c:517:
INTERNAL; CUDA driver error 'CUDA_ERROR_ILLEGAL_ADDRESS' (700): an illegal memory access was encountered;
cuLaunchKernel; while invoking native function hal.device.queue.execute; while calling import; 
[ 1]   native hal.device.queue.execute:0 -
[ 0] bytecode module@0:63472 -
Killed
```

Compile command:
```
iree-compile --iree-input-type=tm_tensor --iree-hal-target-backends=cuda \
--iree-llvmcpu-target-cpu-features=host --iree-stream-resource-max-allocation-size=4294967295 \
--iree-vm-bytecode-module-strip-source-map=true --iree-util-zero-fill-elided-attrs \
--iree-opt-strip-assertions=true --verify=false --iree-vm-target-truncate-unsupported-floats \
--iree-codegen-check-ir-before-llvm-conversion=false \
--iree-vm-bytecode-module-output-format=flatbuffer-binary first_llama_int4_1700.mlir -o first_llama.vmfb
```

Runtime command:
```
iree-run-module --device=cuda --function=forward --module=first_llama.vmfb \
--input=1x1700x4096xf32 --input=1x1700xi64 --input=1x1700xi32
```

Following is what I did :-
1. I first used a [stripped version of the above IR](https://storage.googleapis.com/shark_tank/MiniGPT4/elided_first_llama_7b.mlir).
2. I tried using `--iree-flow-break-dispatch=forward_dispatch_<NUMBER>_` (where `NUMBER` is the dispatch I tried bisecting into) to break at particular dispatch.
3. I found that breaking on [dispatch number 11](https://gist.github.com/Abhishek-Varma/d25be292e20ac1b2b4b3c6667c64a007) I'm able to reproduce a similar error - I'm claiming this because I was monitoring `htop` and the memory usage kept on increasing (went till ~500+GB, even with the stripped IR, so had to hit `Ctrl+C`).
Monitoring [dispatch number 11](https://gist.github.com/Abhishek-Varma/d25be292e20ac1b2b4b3c6667c64a007) doesn't show up any apparent reason for the above error.

Perhaps an ill-formed IR arising earlier in the pipeline?

### Edit:
Using `--iree-scheduling-optimize-bindings=false` + breaking on dispatch 11 + running doesn't seem to stuck anymore hogging on memory resources at runtime.

**Comment by Groverkss** [comment]
I'll have a look at this.

**Comment by Abhishek-Varma** [comment]
Adding an update here (as well as the original ticket content under `Edit`):

Using `--iree-scheduling-optimize-bindings=false` + breaking on dispatch 11 + running doesn't seem to stuck anymore hogging on memory resources at runtime.

**Comment by Groverkss** [comment]
> running doesn't seem to stuck anymore hogging on memory resources at runtime

What does this mean?

**Comment by Abhishek-Varma** [comment]
> > running doesn't seem to stuck anymore hogging on memory resources at runtime
> 
> What does this mean?

This was referring to what I mentioned in the issue content above :-
```
3. I found that breaking on dispatch number 11 I'm able to reproduce a similar error - 
   I'm claiming this because I was monitoring htop and the memory usage kept on 
   increasing (went till ~500+GB, even with the stripped IR, so had to hit Ctrl+C).
```

**Comment by Groverkss** [comment]
iree-reduce produces:

```
module {
  flow.executable private @forward_dispatch_644 {
    flow.executable.export public @forward_dispatch_644_generic_1700x32000x32x128_f16 workgroups() -> (index, index, index) {
      %x, %y, %z = flow.dispatch.workgroup_count_from_slice 
      flow.return %x, %y, %z : index, index, index
    }
    builtin.module {
      func.func @forward_dispatch_644_generic_1700x32000x32x128_f16(%arg0: !flow.dispatch.tensor<readonly:tensor<32000x32x128xi4>>, %arg1: !flow.dispatch.tensor<readonly:tensor<32000x32xf16>>, %arg2: !flow.dispatch.tensor<readonly:tensor<1700x32x128xf16>>, %arg3: !flow.dispatch.tensor<writeonly:tensor<1700x32000xf16>>) {
        %cst = arith.constant 0.000000e+00 : f16
        %0 = tensor.empty() : tensor<1700x32000xf16>
        %1 = linalg.fill ins(%cst : f16) outs(%0 : tensor<1700x32000xf16>) -> tensor<1700x32000xf16>
        %2 = linalg.fill ins(%cst : f16) outs(%1 : tensor<1700x32000xf16>) -> tensor<1700x32000xf16>
        flow.dispatch.tensor.store %2, %arg3, offsets = [0, 0], sizes = [1700, 32000], strides = [1, 1] : tensor<1700x32000xf16> -> !flow.dispatch.tensor<writeonly:tensor<1700x32000xf16>>
        return
      }
    }
  }
  func.func @forward(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view, %arg2: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub} {
    %cst = arith.constant 0.000000e+00 : f16
    %cst_0 = arith.constant dense_resource<__elided__> : tensor<32000x32x1xf16>
    %cst_1 = arith.constant dense_resource<__elided__> : tensor<32000x4096xi4>
    %0 = flow.tensor.splat %cst : tensor<1700x32x128xf16>
    %1 = flow.tensor.reshape %cst_1 : tensor<32000x4096xi4> -> tensor<32000x32x128xi4>
    %2 = flow.tensor.reshape %cst_0 : tensor<32000x32x1xf16> -> tensor<32000x32xf16>
    %3 = flow.dispatch @forward_dispatch_644::@forward_dispatch_644_generic_1700x32000x32x128_f16(%1, %2, %0) : (tensor<32000x32x128xi4>, tensor<32000x32xf16>, tensor<1700x32x128xf16>) -> tensor<1700x32000xf16>
    %5 = flow.tensor.reshape %3 : tensor<1700x32000xf16> -> tensor<1x1700x32000xf16>
    %6 = hal.tensor.export %5 "output 0" : tensor<1x1700x32000xf16> -> !hal.buffer_view
    return %6 : !hal.buffer_view
  }
}
```

**Comment by Groverkss** [comment]
Fixed by https://github.com/llvm/llvm-project/pull/67714

**Comment by stellaraccident** [comment]
I've reverted this patch upstream because it breaks llama compilation on Vulkan/SPIR-V.

**Comment by stellaraccident** [comment]
Steps to reproduce:

```
pip install -e experimental/regression_suite
pytest -s experiemental/regression_suite/tests
```

(The AMDGPU tests are failing, but because this is a compilation issue, you will see the crash and don't need a real GPU)

**Comment by antiagainst** [comment]
Hey @Abhishek-Varma I assume this should be fixe now. Please verify and close.

**Comment by Groverkss** [comment]
Should be fixed by https://github.com/llvm/llvm-project/pull/68181 . Please reopen if not.
