### ISSUE TITLE
[GPU] Vector transfer hoisting without view-like ops

### ISSUE THREAD

**Issue by qedawkins** [iree-org/iree#15083]
# Problem + repro
The most recent integrate (#15048) is pulling in https://github.com/llvm/llvm-project/pull/66930 which causes difficulties doing vector transfer hoisting on both the SPIR-V and LLVMGPU backends. To reproduce an example of this, the following in-tree test will fail to hoist transfer_reads on the output of a matmul
```
iree-opt --split-input-file --pass-pipeline='builtin.module(hal.executable(hal.executable.variant(iree-spirv-lower-executable-target-pass)))' /home/quinn/integrates/iree/compiler/src/iree/compiler/Codegen/SPIRV/test/lowering_matmul_fusion.mlir --debug-only=iree-spirv-vector-lowering
```
Before the change, we would see something like
```
scf.for %arg1 = %c0 to %c128 step %c32 {
  ...
  %subview_27 = memref.subview %subview_3[%33, %34] [4, 4] [1, 1] : memref<32x128xf32, strided<[2048, 1], offset: ?>, #hal.descriptor_type<storage_buffer>> to memref<4x4xf32, strided<[2048, 1], offset: ?>, #hal.descriptor_type<storage_buffer>>
  %37 = vector.transfer_read %subview_27[%c0, %c0], %cst_0 {in_bounds = [true, true]} : memref<4x4xf32, strided<[2048, 1], offset: ?>, #hal.descriptor_type<storage_buffer>>, vector<4x4xf32>
  ...
  vector.transfer_write %38, %subview_27[%c0, %c0] {in_bounds = [true, true]} : vector<4x4xf32>, memref<4x4xf32, strided<[2048, 1], offset: ?>, #hal.descriptor_type<storage_buffer>>
}
```
Which would then get unrolled and then hoisted to form a loop like
```
%37:4 = scf.for %arg5 = %c0 to %c128 step %c32 iter_args(%arg6 = %arg1, %arg7 = %arg2, %arg8 = %arg3, %arg9 = %arg4) -> (vector<4xf32>, vector<4xf32>, vector<4xf32>, vector<4xf32>)
```
The new change, however, disallows hoisting through view-like ops.
## Potential solutions

I see three potential ways to support this without hoisting through view-like ops. First, say that we run `FoldMemRefAliasOps` + `CSE` beforehand.
```
%7 = hal.interface.binding.subspan set(0) binding(4) type(storage_buffer) alignment(64) offset(%c0) : memref<4096x2048xf32, #hal.descriptor_type<storage_buffer>>
scf.for %arg1 = %c0 to %c128 step %c32 {
  %41 = vector.transfer_read %7[%8, %9], %cst_0 {in_bounds = [true, true]} : memref<4096x2048xf32, #hal.descriptor_type<storage_buffer>>, vector<4x4xf32>
  vector.transfer_write %42, %7[%8, %9] {in_bounds = [true, true]} : vector<4x4xf32>, memref<4096x2048xf32, #hal.descriptor_type<storage_buffer>>
}
```
1) We run hoisting right after folding here.
2) We unroll to SPIR-V's native vector sizes then hoist.
3) We unroll -> fold aliases -> hoist.

(1) Currently won't work because it will form a loop like
```
%26 = scf.for %arg2 = %c0 to %c128 step %c32 iter_args(%arg3 = %arg1) -> (vector<4x4xf32>)
```
Which will later fail to translate to SPIR-V due to the requirement for 1-D vector sizes of `2`, `3`, or `4`. If we had a way to unroll the vector iter_arg this would be a plausible solution; IREE's `ForOpCanonicalizationPass` has a few ad-hoc patterns that try to do similar things, but to my knowledge there isn't a direct way to break down this vector at the moment.

(2) Will currently fail due to trying to analyze "dynamic" vector transfer ranges and being unable to prove hoistability. Essentially after unrolling we would have something like
```
  %0 = gpu.thread_id  x
  %1 = gpu.thread_id  y
  %8 = affine.apply affine_map<()[s0, s1] -> (s0 * 32 + s1 * 4)>()[%workgroup_id_y, %1]
  %9 = affine.apply affine_map<()[s0, s1] -> (s0 * 128 + s1 * 4)>()[%workgroup_id_x, %0]
  %10 = affine.apply affine_map<(d0) -> (d0 + 1)>(%8)
  %11 = affine.apply affine_map<(d0) -> (d0 + 2)>(%8)
  %12 = affine.apply affine_map<(d0) -> (d0 + 3)>(%8)
  scf.for %arg1 = %c0 to %c128 step %c32 {
      %124 = vector.transfer_read %7[%8, %9], %cst_0 {in_bounds = [true]} : memref<4096x2048xf32, #hal.descriptor_type<storage_buffer>>, vector<4xf32>
      %125 = vector.transfer_read %7[%10, %9], %cst_0 {in_bounds = [true]} : memref<4096x2048xf32, #hal.descriptor_type<storage_buffer>>, vector<4xf32>
      %126 = vector.transfer_read %7[%11, %9], %cst_0 {in_bounds = [true]} : memref<4096x2048xf32, #hal.descriptor_type<storage_buffer>>, vector<4xf32>
      %127 = vector.transfer_read %7[%12, %9], %cst_0 {in_bounds = [true]} : memref<4096x2048xf32, #hal.descriptor_type<storage_buffer>>, vector<4xf32>
      ...
      vector.transfer_write %223, %7[%8, %9] {in_bounds = [true]} : vector<4xf32>, memref<4096x2048xf32, #hal.descriptor_type<storage_buffer>>
      vector.transfer_write %319, %7[%10, %9] {in_bounds = [true]} : vector<4xf32>, memref<4096x2048xf32, #hal.descriptor_type<storage_buffer>>
      vector.transfer_write %415, %7[%11, %9] {in_bounds = [true]} : vector<4xf32>, memref<4096x2048xf32, #hal.descriptor_type<storage_buffer>>
      vector.transfer_write %511, %7[%12, %9] {in_bounds = [true]} : vector<4xf32>, memref<4096x2048xf32, #hal.descriptor_type<storage_buffer>>
  }
```
Where none of the read + write pairs can be hoisted because the thread + workgroup ids are dynamic from the perspective of the hoisting analysis. Before hand, the offsetting based on the thread and workgroup ids was tied to the view-like subview op and thus it was easy to statically say that each of the 4 read/write pairs are non-overlapping. (3) doesn't work for the same reason because we're still hoisting after unrolling (and thus have 4 reads like this).

This could be made to work if the logic for `isDisjointTransferIndices` was improved to use bounds analysis to prove that the values are dynamically disjoint.

**Comment by stellaraccident** [comment]
Thanks, Quinn. In addition to solving this, let's rewind the integrate to just before this patch and land it.

**Comment by qedawkins** [comment]
> Thanks, Quinn. In addition to solving this, let's rewind the integrate to just before this patch and land it.

If we roll back PkgCI will fail without the revert to #67714. Should we just cherry-pick the revert then?

**Comment by stellaraccident** [comment]
Yeah, cherry-picking a landed revert >> than carrying something that diverges: it doesn't require any additional accounting and clears itself.

**Comment by antiagainst** [comment]
Yup, great summary in the above Quinn! I agree the above analyses. Unrolling first makes hoisting easier given that we don't need to mess with the loop carried values. We should give it a try to enhance `isDisjointTransferIndices` with bounds analysis.

**Comment by antiagainst** [comment]
https://github.com/llvm/llvm-project/pull/68500 for enhacing vector transfer op hoisting and forwarding.
