### ISSUE TITLE
[ROCM] incorrect device selection using UUID for multiple rocm devices

### ISSUE THREAD

**Issue by PhaneeshB** [iree-org/iree#15100]
### What happened?

Requirement : Ability to select rocm devices based on UUID

Steps:
1. add uuid to device info for rocm ([added here](https://github.com/nod-ai/SRT/commit/416ec59d940828a784bcb1ba2f740861efa99f91))
2. allow device selection logic to get appropriate device id from given UUID
3. Create hal device for the chosen device (2, 3 [added here](https://github.com/nod-ai/SRT/commit/476fb521fdeb47799636ec840037fb8a1989f2b2)) 

with the above mentioned changes it turns out that the device created by `iree_hal_rocm_device_create` is always the default device regardless of the input `device` id. 

Observation: 
with `hipCtxCreate` the device fetched from the created context turns out to be the default device 
(could be a that we're not using this API correctly or getting incorrect results from it)
[debug patch here](https://github.com/nod-ai/SRT/commit/3dff64e401ae2066136989d6f3b7cf1a285b957f)

output from debug patch on a system with 4 rocm supported cards,
choosing `--device=rocm://<uuid for device#4>` in `--iree-run-module`
```
...
Context creating! with device - 3
Context created!
 Checking for device created in this context
got device from ctx - device# : 0
...
```
Changes can be found in [this branch](https://github.com/nod-ai/SRT/tree/add_rocm_device_path) on SRT

**Comment by antiagainst** [comment]
Fixed by #15234.
