### ISSUE TITLE
Runtime C API: append_bytecode_module_from_memory bytespan ownership

### ISSUE THREAD

**Issue by gmmyung** [iree-org/iree#15122]
### What happened?

This is the api documentation of the function `iree_runtime_session_append_bytecode_module_from_memory`
```c
// Appends a bytecode module to the context loaded from the given memory blob.
// If the module exists as a file prefer instead to use
// iree_runtime_session_append_bytecode_module_from_file to use memory mapped
// I/O and reduce total memory consumption.
//
// The data must remain valid for the lifetime of the session. If a
// |flatbuffer_allocator| is provided then it will be used to free the
// |flatbuffer_data| when the module is destroyed. This call always consumes the
// data and even if the module fails to load or be registered with the session
// the |flatbuffer_allocator| will be used to release it.
//
// NOTE: only valid if the context is not yet frozen; see
// iree_vm_context_freeze for more information.
IREE_API_EXPORT iree_status_t
iree_runtime_session_append_bytecode_module_from_memory(
    iree_runtime_session_t* session, iree_const_byte_span_t flatbuffer_data,
    iree_allocator_t flatbuffer_allocator);
```
I want `iree_runtime_session_append_bytecode_module_from_memory` not to free flatbuffer_data. It says that "If a `flatbuffer_allocator` is provided then it will be used to free the `flatbuffer_data` when the module is destroyed", but I can't find a way to NOT pass the allocator.

If I try to pass a null allocator that does nothing, it outputs:
```
Status: "iree/runtime/src/iree/vm/context.c:238: INTERNAL; import function hal.allocator.allocate signature 
mismatch between arithmetic and source hal; expected 0riiI_r but got 0rIiiI_r; resolving module 'arithmetic' imports"
```
Is there any way to get around this?

### Version information

https://github.com/openxla/iree/commit/2b9ade513428ed9c0714134f120a50024c5718b5

**Comment by benvanik** [comment]
The null allocator should work just fine. I suspect you are not honoring the "The data must remain valid for the lifetime of the session." part of the comment: if you free the memory before the session is destroyed things will explode. Or, it's something completely unrelated.

**Comment by gmmyung** [comment]
Upon debugging, it appears that the bug originates from an unrelated source from this issue. Thanks for your response!

**Comment by gmmyung** [comment]
Well, I have yet to find out what went wrong here :(
```
DEBUG runtime: vmfb ptr: 0x12d02d200
DEBUG iree_rs::runtime::api: Appending bytecode module from memory...
DEBUG iree_rs::runtime::base: rust_allocator_ctl: IREE_ALLOCATOR_COMMAND_CALLOC: size: 584 -> 0x11c643e80
DEBUG iree_rs::runtime::base: rust_allocator_ctl: IREE_ALLOCATOR_COMMAND_CALLOC: size: 16 -> 0x6000006222f0
DEBUG iree_rs::runtime::base: rust_allocator_ctl: IREE_ALLOCATOR_COMMAND_CALLOC: size: 16 -> 0x600000622110
DEBUG iree_rs::runtime::base: rust_allocator_ctl: IREE_ALLOCATOR_COMMAND_FREE: size: 8->0x6000006223f0
DEBUG iree_rs::runtime::base: rust_allocator_ctl: IREE_ALLOCATOR_COMMAND_FREE: size: 8->0x600000621b30
DEBUG iree_rs::runtime::base: rust_allocator_ctl: IREE_ALLOCATOR_COMMAND_CALLOC: size: 1184 -> 0x11c8b2c10
DEBUG iree_rs::runtime::base: rust_allocator_ctl: IREE_ALLOCATOR_COMMAND_FREE: size: 1184->0x11c8b2c10
DEBUG iree_rs::runtime::base: null_allocator_ctl: IREE_ALLOCATOR_COMMAND_FREE, 0x12d02d200
DEBUG iree_rs::runtime::base: rust_allocator_ctl: IREE_ALLOCATOR_COMMAND_FREE: size: 584->0x11c643e80
DEBUG iree_rs::runtime::base: rust_allocator_ctl: IREE_ALLOCATOR_COMMAND_CALLOC: size: 216 -> 0x600003943670
DEBUG iree_rs::runtime::base: rust_allocator_ctl: IREE_ALLOCATOR_COMMAND_FREE: size: 216->0x600003943670
thread 'append_module' panicked at 'called `Result::unwrap()` on an `Err` value: StatusError(Status: "iree/runtime/src/iree/vm/context.c:238: 
INTERNAL; import function hal.allocator.allocate signature mismatch between arithmetic and source hal; 
expected 0riiI_r but got 0rIiiI_r; resolving module 'arithmetic' imports")', tests/runtime.rs:77:56
```
I've been troubleshooting this issue but haven't been able to identify the root cause. The error message seems to indicate a signature mismatch in the import function. I would greatly appreciate it if you could provide some insights or suggestions on where I should focus my investigation to resolve this issue. Any help would be highly valuable.

**Comment by ScottTodd** [comment]
> The error message seems to indicate a signature mismatch in the import function.

This is likely due to the breaking HAL change in https://github.com/openxla/iree/commit/f022d29ad6d9c9ba793e08e529c0472a6b43af12
![image](https://github.com/openxla/iree/assets/4010439/99838f46-a73e-4ece-802f-555a2054cdd1)
![image](https://github.com/openxla/iree/assets/4010439/6e3047b2-22f6-45bd-90f4-fbd07eb58987)

Breaking compiler/runtime changes are infrequent (a few each year). I thought we might have some version checking that could give better error messages, but maybe not...

Assuming the version info in your issue description is for the runtime, you could try updating your version of the compiler. From pip, you can do that by either switching to a nightly release by adding `--find-links https://openxla.github.io/iree/pip-release-links.html` to your `pip install` commands (docs: https://www.iree.dev/reference/bindings/python/#prebuilt-packages) OR by waiting a little bit. I'm just about to push a new stable release (https://groups.google.com/g/iree-discuss/c/_cBAm5VubN4/m/0-v0t9qvAwAJ).

**Comment by ScottTodd** [comment]
(Update the compiler and use that newer compiler tool to regenerate the .vmfb file that you pass to the more recent runtime using `iree_runtime_session_append_bytecode_module_from_memory`)

**Comment by gmmyung** [comment]
Problem solved! Thank you for helping out.
