### ISSUE TITLE
`hal.interface.load.constant` needs a `SymbolRefAttr` pointing to `hal.interface`

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#1519]
At the moment the `hal.interface.load.constant` op does not indicate from which `hal.interface` it is loading the push constant: https://google.github.io/iree/Dialects/HALDialect#halinterfaceloadconstant-ireehalinterfaceloadconstantop

**Comment by benvanik** [comment]
There is only ever one hal.interface available within the executable being translated so it's implicit, though it wouldn't hurt to specify.

**Comment by antiagainst** [comment]
IMO making explicit is better: in the lowering we are not relying on implicit information.

**Comment by benvanik** [comment]
This is blocking HAL interface canonicalization too, where the opaque push constant count attribute (vs having named push constants) prevents any kind of sharing. Fixing this would allow us to rearrange push constants to dedupe them across all dispatches of an executable so two executables that take the same shape could store the dynamic dimension/computed strides/etc in the same offsets, removing the need to upload them twice. It'd also make it possible to create gaps in the push constant list such that two executables using different sets of constants could have a compatible layout and avoid additional runtime executable layout creation and potential pipeline reconfiguration.

**Comment by ScottTodd** [comment]
This issue is quite old. Is it still relevant and blocking something? Have the op names changed since this was filed?

**Comment by benvanik** [comment]
I think we still want this so we can perform the canonicalizations - this is blocking that work. It's similar to the linking issue I've run into in https://github.com/iree-org/iree/issues/5662#issuecomment-1164609787 where symbols for executable level constants are also required.

**Comment by benvanik** [comment]
I'm not sure we need this anymore as defined now that interfaces have mostly been replaced with `#hal.pipeline.layout`. We still need a way to canonicalize the constants such that multiple dispatches taking the same values end up with those values in the same push constant slots but that could probably be done as a dedicated analysis + pass instead of being structural.
