### ISSUE TITLE
[DT][CPU] Lift `linalg.generic` to `linalg.batch_matmul` + transpose + `arith.ext*`

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#15214]
This is a key step in https://github.com/openxla/iree/issues/15158: the [workload there](https://gist.github.com/Max191/8ae398f4697edd31bd07a613b46dcbbd) consists of a couple of `linalg.generic` ops, and the first one, doing most of the arithmetic, is essentially a batch matmul, and can be lifted to an actual `linalg.batch_matmul` is we're willing to also create some transposes and around it.  Doing that will then compose with work on data-tiling and ukernels for the resulting flavors of `linalg.batch_matmul`.

Pasting here a function doing just that first `linalg.generic` to be handled here:

```mlir
#map = affine_map<(d0, d1, d2) -> (d1, d2)>
#map1 = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
#map2 = affine_map<(d0, d1, d2) -> (d0, d1)>
module {
  func.func @transpose_extend_batch_matmul(%arg0: tensor<32x128xi16>, %arg1: tensor<11008x32x128xi4>) -> tensor<11008x32xi32> {
    %c0_i32 = arith.constant 0 : i32
    %cst = arith.constant 0.000000e+00 : f32
    %0 = tensor.empty() : tensor<11008x32xi32>
    %1 = linalg.fill ins(%c0_i32 : i32) outs(%0 : tensor<11008x32xi32>) -> tensor<11008x32xi32>
    %2 = tensor.empty() : tensor<11008xf32>
    %3 = linalg.fill ins(%cst : f32) outs(%2 : tensor<11008xf32>) -> tensor<11008xf32>
    %4 = linalg.generic {indexing_maps = [#map, #map1, #map2], iterator_types = ["parallel", "parallel", "reduction"]} ins(%arg0, %arg1 : tensor<32x128xi16>, tensor<11008x32x128xi4>) outs(%1 : tensor<11008x32xi32>) {
    ^bb0(%in: i16, %in_0: i4, %out: i32):
      %5 = arith.extsi %in : i16 to i32
      %6 = arith.extui %in_0 : i4 to i32
      %7 = arith.muli %5, %6 : i32
      %8 = arith.addi %7, %out : i32
      linalg.yield %8 : i32
    } -> tensor<11008x32xi32>
    return %4 : tensor<11008x32xi32>
  }
}
```

**Comment by bjacob** [comment]
Update: lots of thinking as this has run into an unexpected subtlety, but we have a plan now following discussion yesterday with @hanhanW.

The subtlety is that this RHS is doing a batch matmul with a signed LHS and an unsigned RHS. But `linalg.batch_matmul` treats signless element types as signed, not unsigned. And clearly, we don't want to multiply the number of linalg named ops by 4x to cover separately all variants of signed/unsigned LHS/RHS. So we discussed two possibilities for how we are going to be representing these matmuls:

1. We could represent them as `arith.extsi` to `i32` (on the LHS), `arith.extui` to `i32` (on the RHS), `linalg.batch_matmul` on all-`i32` operands. Then existing patterns that are matching mixed-types `linalg.batch_matmul` need to be updated to match this sequence with `arith.ext*` ops.
2. We could just leave them as `linalg.generic`. Data-tiling becomes a rewrite from `linalg.generic` to `linalg.generic`. We still need to recognize them as matmuls and set a `MATMUL` encoding accordingly for data-tiling purposes.

We decided to go with 1. for now, while agreeing that we will over time converge towards 2.

Details of what 1. is going to look like in data-tiling transformations:

- In SetEncoding, when matching a `linalg.batch_matmul`, we should check if the defining ops of operands are `arith.ext` and if so, treat the inputs of those `arith.ext` as the true inputs. Set the element types in the encodings accordingly (so if the matmul operand is `i32` but is defined by a `extui` with input `i8` then set the encoding element type to `u8`). Insert the `set_encoding` ops on the producer side of the `arith.ext` (so that we pack un-extended data, leaving the extension part of the matmul kernel). Ensure that the `arith.ext` ops go into the same dispatch as the matmul.
- In MaterializeEncoding, nothing special needs to happen, actually --- surprisingly. A `matmul` continues being materialized into a `mmt4d`. It doesn't matter that the operands are now `i32`, being now defined by `arith.ext` ops, because `mmt4d` is the same in this respect. So the `matmul->mmt4d` materialization should be orthogonal to this change. It does depend on the encoding specifying the true-input narrow integer type, but that was set independently from the immediate-input extended element type at the above SetEncoding step.
- In LowerToUKernels, we will now need to match arith.ext+mmt4d where we were so far matching mixed-types mmt4d.

**Comment by bjacob** [comment]
Also since https://github.com/openxla/iree/pull/15273 is nearly ready, just waiting on the same LLVM integrate as I'm blocked on anyway, I'll rebase on that, so I won't duplicate the work to expand dims.  Just need to create the missing `batch_vecmat` named op.

**Comment by bjacob** [comment]
What needs to be done here @Max191 :

You need both of these MLIR PRs - already merged upstream but not yet integrated:
https://github.com/llvm/llvm-project/pull/70218
https://github.com/llvm/llvm-project/pull/70284

The first one is part of this integration:https://github.com/openxla/iree/pull/15296 so you can just apply that.

The second one is not part of that so need to apply it manually:
```
cd third_party/llvm-project
apply https://patch-diff.githubusercontent.com/raw/llvm/llvm-project/pull/70284.diff
```

There is another IREE PR that you will need to apply on top of that:
#15310 

Thanks to all that, you can rely on `linalg.batch_vecmat` existing as a linalg named op, and the ExpandVectors pass can rewrite any of these linalg vector-matrix multiplications into `linalg.matmul` or `linalg.batch_matmul`.

That means that in this PR, you should never need to expand any shape.  (Batch-)Vector shapes can remain as-is. You should be able do so something like

```c++
if (op.isBatchVecmat()) {
  create<linalg::BatchVecmatOp>(....);
} else {
  ... other kinds of matmul and matvec ...
}
```

I had started some stub... just some boilerplate and ensuring that `linalg::inferContractionDims` works as intended to recover the ordering of dimensions ( you will need that to generate the right transposes):
#15315

**Comment by bjacob** [comment]
The big #15296 is done and ended up including both of the above upstream PRs, so none of that is needed anymore if you just pull main now. And #15310 is merged too.

**Comment by Max191** [comment]
> The big #15296 is done and ended up including both of the above upstream PRs, so none of that is needed anymore if you just pull main now. And #15310 is merged too.

Cool, I have finished the implementation for the vecmat case. I still need to add some tests and implementations for matvec and matmul, but that should not be much work. For now, I'll rebase and make a new draft PR while I finish up the rest of the cases

**Comment by hanhanW** [comment]
@Max191 @bjacob I think we are able to lift the case to `linalg.batch_matmul` + transpose + cast ops. Can we mark it done?

**Comment by bjacob** [comment]
yes!
