### ISSUE TITLE
LLVM Integrate Rotation Set Up

### ISSUE THREAD

**Issue by allieculp** [iree-org/iree#15218]
### Request description

Hearing that we are setting up a rotation for LLVM integrate? @MaheshRavishankar @jpienaar can you provide the latest info?

### What component(s) does this issue relate to?

Other

**Comment by MaheshRavishankar** [comment]
Linking this post from Discord from @stellaraccident (https://discord.com/channels/689900678990135345/1080178290188374049/1163703996360425553) . I think we just need to get some volunteers and setup the rotation ,but first some one needs to drive the integrate. Ill see if I can pick that up, but I can try to coral people into doing integrate on our side.

**Comment by stellaraccident** [comment]
I've been building it out here:
https://github.com/shark-infra/megabump

It's pretty mechanical punctuated by... let's call it... opportunities to learn git.

Whoever the first folks are, I'll work with them to drive it. I wouldn't jump to a rotation yet... more of a train the trainer kind of thing. Hopefully can get some fresh faces doing it versus just anchoring it on the codegen teams.

**Comment by jpienaar** [comment]
It all starts with a spreadsheet I think :) Get a rotation sheet that we can see who is on when. Get enough folks on that it is a once in 3 month overhead & add the autobump to handle the trivial cases.

**Comment by qedawkins** [comment]
I can join the list if there is a rotation sheet!

**Comment by ScottTodd** [comment]
We have a spreadsheet linked in the #llvm-integration channel on Discord. Can close this issue now.
