### ISSUE TITLE
Using bazel build without CUDA

### ISSUE THREAD

**Issue by jpienaar** [iree-org/iree#15233]
Unclear how to use the bazel test without CUDA.

```
bazel test -k //... --test_env=IREE_CUDA_DISABLE=1
```

still failing on CUDA tests. 

```
Executing tests from //tests/e2e/stablehlo_ops:check_cuda_graph_concatenate.mlir
-----------------------------------------------------------------------------
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from module
[ RUN      ] module.xla_concatenate
runtime/src/iree/hal/driver_registry.c:319: NOT_FOUND; no driver 'cuda' registered; creating driver for device 'cuda'; resolving dependencies for 'module'
```

**Comment by ScottTodd** [comment]
Not sure if this is possible right now. The `--test_env` only changes runtime behavior for tests that look at environment variables (lit tests), and the check tests rely on build/configure-time filtering instead.

`iree_check_test_suite` currently does some filtering, but `iree_check_single_backend_test_suite` does not:
https://github.com/openxla/iree/blob/b13037b0c55b90a41d644cd9d55500906252a4be/build_tools/bazel/iree_check_test.bzl#L200-L205

[`tests/e2e/stablehlo_ops/BUILD.bazel`](https://github.com/openxla/iree/blob/main/tests/e2e/stablehlo_ops/BUILD.bazel) uses the `single_backend` version.

**Comment by ScottTodd** [comment]
We may be able to route `@iree_cuda//:enabled` through to `iree_check_single_backend_test_suite`. On the CMake side, we have many filtering options... Bazel might be able to get by with just a few. https://github.com/openxla/iree/blob/b13037b0c55b90a41d644cd9d55500906252a4be/build_tools/cmake/iree_check_test.cmake#L186-L224

**Comment by ScottTodd** [comment]
Started looking into this today but my Bazel is rusty. https://bazel.build/docs/configurable-attributes mentions a few different approaches that could be used. I'm not sure how to interface between those and our "macros" (which could be converted into "rules").

More context I found: `--iree_drivers=vulkan` works together with https://github.com/openxla/iree/blob/59297e0333c25ed31e2d6fb899a760191e939302/build_tools/bazel/iree.bazelrc#L41-L44 and https://github.com/openxla/iree/blob/main/runtime/src/iree/hal/drivers/BUILD.bazel

Similar discussion [back here on Discord](https://discord.com/channels/689900678990135345/1068655854376718468/1068658798249640047)

Actually, from that discussion - https://github.com/openxla/iree/blob/main/build_tools/bazel/build_core.sh adds the `-driver=cuda` test tag filter (to `--test_tag_filters`). So... that might resolve this question, but it isn't convenient... (It would be nice if CUDA unavailable / not enabled --> don't define build targets that depend on it).

---

Summarizing, this might do what you want:

`bazel test -k //... --iree_drivers=local-sync,local-task,vulkan --test_tag_filters="-driver=cuda"`

(may _also_ want `--test_env=IREE_CUDA_DISABLE=1`, `--test_env=IREE_NVIDIA_GPU_TESTS_DISABLE=1`, etc.)

**Comment by ScottTodd** [comment]
Whatever comes out of this could be documented here: https://iree.dev/developers/building/bazel/

(common recipes for setting flags, using filters, etc.)

**Comment by stellaraccident** [comment]
Wish I could help but I have flushed my knowledge of systems that refuse to have a usable `if` statement.

**Comment by ScottTodd** [comment]
```shell
bazel test -k //... \
  --iree_drivers=local-sync,local-task,vulkan
  --test_tag_filters="-driver=cuda,-driver=vulkan"
```

fails on my Linux machine in a few ways:

```
In file included from runtime/src/iree/hal/drivers/cuda/status_util.c:7:
In file included from runtime/src/iree/hal/drivers/cuda/status_util.h:13:
In file included from runtime/src/iree/hal/drivers/cuda/dynamic_symbols.h:12:
runtime/src/iree/hal/drivers/cuda/cuda_headers.h:10:10: fatal error: 'cuda.h' file not found
#include "cuda.h"                   // IWYU pragma: export
         ^~~~~~~~
1 error generated.
```

```
ERROR: /usr/local/google/home/scotttodd/code/iree/tests/e2e/stablehlo_ops/BUILD.bazel:339:37: Compiling IREE module check_cuda_graph_exponential_minus_one.mlir_bytecode_module... //tests/e2e/stablehlo_ops:check_cuda_graph_exponential_minus_one.mlir_bytecode_module failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox
tests/e2e/stablehlo_ops/exponential_minus_one.mlir:3:13: error: failed to parse libdevice.xx.bc bitcode: Invalid bitcode signature (possible LLVM bitcode incompatibility?)
  %result = "stablehlo.exponential_minus_one"(%input) : (tensor<4xf32>) -> tensor<4xf32>
            ^
tests/e2e/stablehlo_ops/exponential_minus_one.mlir:3:13: error: failed linking in embedded libdevice bitcode for target triple 'nvptx64-nvidia-cuda'
  %result = "stablehlo.exponential_minus_one"(%input) : (tensor<4xf32>) -> tensor<4xf32>
            ^
tests/e2e/stablehlo_ops/exponential_minus_one.mlir:3:13: error: failed to serialize executable for target backend cuda
  %result = "stablehlo.exponential_minus_one"(%input) : (tensor<4xf32>) -> tensor<4xf32>
            ^
tests/e2e/stablehlo_ops/exponential_minus_one.mlir:3:13: error: failed to serialize executables
  %result = "stablehlo.exponential_minus_one"(%input) : (tensor<4xf32>) -> tensor<4xf32>
            ^
```

I think I can exclude the iree_bytecode_module targets with more tags/filters. Not sure about the runtime code... could see why those are being built (e.g. for which tests/binaries). Could also debug into `cuda_auto_configure_impl` (somehow... Bazel.. ugh...) to see what is going on with the configuration.
