### ISSUE TITLE
Consider dropping SwiftShader as a software Vulkan test implementation

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#15299]
We've been using [SwiftShader](https://swiftshader.googlesource.com/SwiftShader)'s high-performance CPU-based implementation of Vulkan 1.3 for testing and development. Occasionally this has been a source of flaky tests (https://github.com/openxla/iree/issues/5716), but overall it has enabled us to run more tests on more platforms.

However, the SwiftShader project looks like it is on life support, and I worry that when we have a large Vulkan update or other testing environment changes occur, keeping it working may become more and more difficult. We are already seeing effects of this in Google's monorepo.

![image](https://github.com/openxla/iree/assets/4010439/1b47ecb5-709a-4f22-81ff-39fc7c428d4a)

I'm not actually sure how much concrete value we're getting out of SwiftShader today

* We have `test_gpu` and `test_a100` CI jobs that run our Vulkan tests on physical desktop GPUs (Linux)
* We have a `build_and_test_android` CI job that runs our Vulkan tests on physical  mobile GPUs (Pixel 6 Pro, moto edge x30)
* Our Dockerfiles have a bunch of plumbing and other infrastructure for SwiftShader that we could prune
* We have CUDA, Metal, and ROCm backends, none of which have software implementations like Vulkan/SwiftShader
* SwiftShader does act as a "min spec" implementation, which is a good way to keep our implementation from growing too many advanced features as default-enabled

**Comment by benvanik** [comment]
Min spec implementation is probably the biggest value it is providing today, but we can get that via the VK_LAYER_KHRONOS_profiles: https://vulkan.lunarg.com/doc/view/1.3.204.1/windows/profiles_layer.html

Idea is that you provide a config saying what the device should behave like (limits/features/etc) and so long as it's a subset of the physical device you're running on all queries/etc behave the same. The critical part we're testing on swiftshader isn't really the SPIR-V (IMO) but the HAL backend doing device feature queries and selecting the right things to run.

Haven't used the layer myself but every time I've heard it referenced it's been for this kind of usage, so probably works? We'd just need to craft some profiles - wonder if that's something we can do automatically from vulkan.gpuinfo.org.

**Comment by ScottTodd** [comment]
We could also re-evaluate lavapipe/[llvmpipe](https://docs.mesa3d.org/drivers/llvmpipe.html). I see a few other teams exploring it.

We currently exclude it explicitly: https://github.com/openxla/iree/blob/5610d8cf7c06b71fd3281fb3fa2e8e67fe378d57/runtime/src/iree/hal/drivers/vulkan/vulkan_driver.cc#L364-L374

Having a stable and tested software implementation does make it easier to work on the Vulkan HAL / codegen / etc. from a machine without a physical GPU (e.g. cloud Linux VM). I'm not sure how many of our developers/contributors are using that development model these days though.

**Comment by benvanik** [comment]
pretty sure that's even riskier than using swiftshader :)
I think we can focus on device config emulation with the layers - that's useful regardless of whether we support a software implementation and would let us drop swiftshader - could then see if anyone wants software support back.

**Comment by ScottTodd** [comment]
> We'd just need to craft some profiles - wonder if that's something we can do automatically from vulkan.gpuinfo.org.

There are a few at https://github.com/KhronosGroup/Vulkan-Profiles/tree/main/profiles already. I see several of those in the Vulkan SDK:

```
scotttodd:~/.../config/VK_LAYER_KHRONOS_profiles$ pwd
/usr/local/google/home/scotttodd/tools/vulkan/1.3.268.0/x86_64/share/vulkan/config/VK_LAYER_KHRONOS_profiles
scotttodd:~/.../config/VK_LAYER_KHRONOS_profiles$ ls
VP_ANDROID_baseline_2021.json  VP_LUNARG_desktop_baseline_2022.json
VP_ANDROID_baseline_2022.json  VP_LUNARG_desktop_baseline_2023.json
VP_KHR_roadmap_2022.json       VP_LUNARG_desktop_portability_2022.json
```

I'm also playing with the Vulkan Configurator (https://vulkan.lunarg.com/doc/view/1.3.204.1/windows/vkconfig.html) and `vulkaninfo`. 

For example:
```
scotttodd:~/code/iree$ bash build_tools/third_party/swiftshader/build_vk_swiftshader.sh
    
    Installing to /usr/local/google/home/scotttodd/.swiftshader
      Install directory already exists, cleaning it
    
    Ensure the following variable is set in your enviroment:
       export VK_ICD_FILENAMES=/usr/local/google/home/scotttodd/.swiftshader/vk_swiftshader_icd.json

scotttodd:~/code/iree$ export VK_ICD_FILENAMES=/usr/local/google/home/scotttodd/.swiftshader/vk_swiftshader_icd.json
scotttodd:~/code/iree$ vulkaninfo

    ...
    Presentable Surfaces:
    =====================
    GPU id : 0 (SwiftShader Device (LLVM 10.0.0)):
```

(I'd like to remove SwiftShader from our Docker images as part of refactoring our Docker images in https://github.com/openxla/iree/issues/15332, so seeing if we can get what we need here)

**Comment by ScottTodd** [comment]
I'm not sure from [the docs](https://vulkan.lunarg.com/doc/view/latest/windows/profiles_layer.html) or [profile samples](https://github.com/KhronosGroup/Vulkan-Profiles/tree/main/profiles) how to write a profile that turns off extensions. I did find `VK_KHRONOS_PROFILES_EXCLUDE_DEVICE_EXTENSIONS` environment variable that

> Removes the listed device extensions from being reported by the Vulkan physical device.

That can be used like this:

```
export VK_LOADER_LAYERS_ENABLE=*validation,*profiles
export VK_KHRONOS_PROFILES_PROFILE_FILE="D:/dev/scratch/iree-tmp/cmake/VP_IREE_minspec_test.json"
export VK_KHRONOS_PROFILES_PROFILE_NAME="VP_IREE_minspec_test"
export VK_KHRONOS_PROFILES_EMULATE_PORTABILITY=false
export VK_KHRONOS_PROFILES_EXCLUDE_DEVICE_EXTENSIONS=VK_KHR_timeline_semaphore,VK_KHR_storage_buffer_storage_class
ctest --test-dir ../iree-build --output-on-failure -R iree/tests/e2e/stablehlo_ops/check_vulkan-spirv_vulkan_broadcast.mlir

D:\dev\projects\iree (main -> upstream)
(.venv) λ bash D:\dev\scratch\iree-tmp\cmake\ctest_vulkan_profiles.sh
Internal ctest changing into directory: D:/dev/projects/iree-build
Test project D:/dev/projects/iree-build
    Start 338: iree/tests/e2e/stablehlo_ops/check_vulkan-spirv_vulkan_broadcast.mlir
1/1 Test #338: iree/tests/e2e/stablehlo_ops/check_vulkan-spirv_vulkan_broadcast.mlir ...***Failed
 0.41 sec
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from module
[ RUN      ] module.broadcast_2D_3D
D:\dev\projects\iree\runtime\src\iree\hal\drivers\vulkan\extensibility_util.cc:109: UNAVAILABLE; required extension VK_KHR_storage_buffer_storage_class not available; stack:
```

We could start by turning off all currently "optional" extensions in that way. Other features like device limits could also be set.

Another detail I noticed is that profile validation happens via the validation layers / debug utils extension. We have this [`iree_hal_vulkan_debug_reporter_t`](https://github.com/openxla/iree/blob/main/runtime/src/iree/hal/drivers/vulkan/debug_reporter.cc) to interface with that, but all it does it log warnings/errors, it doesn't propagate/raise those errors as status values or crashes. If we want failures to be noticed on CI / under ctest, we would need to rework that somehow.

**Comment by ScottTodd** [comment]
This is my rough plan:

- [ ] Ensure that Vulkan usage errors are treated as test failures (https://github.com/openxla/iree/pull/15884 or similar)
- [ ] Add min-spec test coverage via Vulkan profiles (still need to validate that these can actually get us the coverage we want)
- [ ] Land https://github.com/openxla/iree/pull/15837
- [ ] Eventually remove [`build_tools/third_party/swiftshader/build_vk_swiftshader.sh`](https://github.com/openxla/iree/blob/main/build_tools/third_party/swiftshader/build_vk_swiftshader.sh) and any other supporting code/scripts/docs

Getting pretty close to the holidays though, so I'm thinking about swapping the order around.
