### ISSUE TITLE
[EPIC][CPU] DT Enablement

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#15313]
Creating this issue to track all the DT issues related to compilation, runtime or performance issues that would need a fix before the default enablement. We shouldn't include here performance improvements that would be nice to have but currently do not necessarily lead to a performance regression over the existing non-DT approach.

The issues are sorted by priority:

```[tasklist]
### Tasks
- [ ] #15061
- [ ] #15692
- [ ] #15242
- [ ] #15349 
- [ ] #15391
- [ ] #15392
- [ ] #15249
```

**Comment by dcaballe** [comment]
I'm currently investigating a ~2x slowdown on an internal model when DT is enabled. I'll update the list once I know more!

**Comment by dcaballe** [comment]
I did another round of benchmarking with ToT and reverting the problematic `ExpandVector` commit. The performance regression of DT against the original CG base went from 10x to 4.9x slower. Not bad :). I'll look at the profiles again but fixing #15242 should be mostly what is remaining! Great job everyone and fantastic coordination and collaboration to address all these issues! Thank you all!

**Comment by dcaballe** [comment]
Good news! With @NatashaKnk's fix for the vecmat/matvec DT issue + @hanhanW's fix for the i1 issue, performance goes from 5x slower to ~17% faster for the i8 version of the model :) (the f32 version seems to be off still but probably some bug with an easy fix). I also see 2-3x improvements vs previous DT numbers for LLaMA and Falcon! Awesome work!

Thanks for bearing with me and sorry for the pressure to fix all of this before the default enablement. Green light from me to do so :) 

@stellaraccident @jpienaar

**Comment by stellaraccident** [comment]
This is great! I appreciate the high bar and I'm glad we were able to clear all of the hurdles. Thanks for all of the work on this. Really great to see the across the board improvements.
