### ISSUE TITLE
[CPU] Inefficient vector code for `tensor.pack` op

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#15349]
This is the hottest dispatch in one of our models. It looks like we are not generating good vector code for the following `tensor.pack` op. We use `#iree_codegen.lowering_config<tile_sizes = [[64, 4], [1, 1]]>} : tensor<?x?xf32> -> tensor<?x4x16x1xf32>` for it, which shouldn't map to any of the transpose patterns that we have?

```
hal.executable public @main_dispatch_1297 {
  hal.executable.variant public @system_elf_x86_64 target(<"llvm-cpu", "system-elf-x86_64", {cpu = "cascadelake", cpu_features = "+cmov,+mmx,+popcnt,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+avx,+avx2,+fma,+avx512f,+bmi,+bmi2,+aes,+pclmul,+avx512vl,+avx512bw,+avx512dq,+avx512cd,+avx512vnni,+adx,+clflushopt,+clwb,+cx16,+cx8,+crc32,+f16c,+fsgsbase,+fxsr,+invpcid,+lzcnt,+movbe,+pku,+prfchw,+rdrnd,+rdseed,+sahf,+x87,+xsave,+xsavec,+xsaveopt,+xsaves,+evex512", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128", link_embedded = false, native_vector_size = 64 : index, target_triple = "x86_64-unknown-linux-gnu", ukernels = false}>) {
    hal.executable.export public @main_dispatch_1297 ordinal(0) layout(#hal.pipeline.layout<push_constants = 0, sets = [<0, bindings = [<0, storage_buffer, ReadOnly>, <1, storage_buffer>]>]>) {
    ^bb0(%arg0: !hal.device):
      %x, %y, %z = flow.dispatch.workgroup_count_from_slice
      hal.return %x, %y, %z : index, index, index
    }
    builtin.module {
      func.func @main_dispatch_1297() {
        %c0 = arith.constant 0 : index
        %c12480 = arith.constant 12480 : index
        %cst = arith.constant 0.000000e+00 : f32
        %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<1200x500000xf32>>
        %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c12480) : !flow.dispatch.tensor<writeonly:tensor<31250x1200x16x1xf32>>
        %2 = flow.dispatch.tensor.load %0, offsets = [0, 0], sizes = [1200, 500000], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<1200x500000xf32>> -> tensor<1200x500000xf32>
        %3 = tensor.empty() : tensor<31250x1200x16x1xf32>
        %pack = tensor.pack %2 padding_value(%cst : f32) outer_dims_perm = [1, 0] inner_dims_pos = [1, 0] inner_tiles = [16, 1] into %3 : tensor<1200x500000xf32> -> tensor<31250x1200x16x1xf32>
        flow.dispatch.tensor.store %pack, %1, offsets = [0, 0, 0, 0], sizes = [31250, 1200, 16, 1], strides = [1, 1, 1, 1] : tensor<31250x1200x16x1xf32> -> !flow.dispatch.tensor<writeonly:tensor<31250x1200x16x1xf32>>
        return
      }
    }
  }
}
```

After vectorization we generate a 1D transpose:
 
```
      %11 = scf.for %arg2 = %c0 to %4 step %c1 iter_args(%arg3 = %7) -> (tensor<?x4x16x1xf32>) {
        %12 = scf.for %arg4 = %c0 to %c4 step %c1 iter_args(%arg5 = %arg3) -> (tensor<?x4x16x1xf32>) {
          %13 = affine.apply affine_map<(d0) -> (d0 * 16)>(%arg2)
          %14 = affine.min affine_map<(d0, d1) -> (16, d0 - d1 * 16)>(%8, %arg2)
          %extracted_slice = tensor.extract_slice %10[%arg4, %13] [1, %14] [1, 1] : tensor<4x?xf32> to tensor<1x?xf32>
          %extracted_slice_0 = tensor.extract_slice %arg5[%arg2, %arg4, 0, 0] [1, 1, 16, 1] [1, 1, 1, 1] : tensor<?x4x16x1xf32> to tensor<1x1x16x1xf32>
          %15 = vector.create_mask %c1, %14 : vector<1x16xi1>
          %16 = vector.transfer_read %extracted_slice[%c0, %c0], %cst, %15 {in_bounds = [true, true]} : tensor<1x?xf32>, vector<1x16xf32>
          %17 = vector.transpose %16, [1, 0] : vector<1x16xf32> to vector<16x1xf32>
          %18 = vector.transfer_write %17, %extracted_slice_0[%c0, %c0, %c0, %c0] {in_bounds = [true, true]} : vector<16x1xf32>, tensor<1x1x16x1xf32>
          %inserted_slice = tensor.insert_slice %18 into %arg5[%arg2, %arg4, 0, 0] [1, 1, 16, 1] [1, 1, 1, 1] : tensor<1x1x16x1xf32> into tensor<?x4x16x1xf32>
          scf.yield %inserted_slice : tensor<?x4x16x1xf32>
        }
        scf.yield %12 : tensor<?x4x16x1xf32>
      }
```

```
iree-compile --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-target-cpu=cascadelake \
     --iree-input-type=stablehlo --iree-llvmcpu-target-triple=x86_64-unknown-linux-gnu \
     --iree-llvmcpu-link-embedded=false --iree-opt-data-tiling=true --compile-from=executable-sources test.mlir -o test.vmfb
```

**Comment by hanhanW** [comment]
This is packing on RHS, which does not have transpose semantics. What the pack op does is like below. The innermost loop moves a 1x16 vector to destination. The load is continuous, but not store.

![image](https://github.com/openxla/iree/assets/6949191/16d96069-5959-430b-8ab4-6c04a5c757af)

->

![image](https://github.com/openxla/iree/assets/6949191/2b48f767-17d9-4e78-9fc2-bc4bb22497a9)

I compared the performance with ukernel and found that they all take 1 second to finish. I think we don't have much things to do on single-threaded. Below is the generated asm. Could you advice what instructions should be used in this case? Are we generating bad code?

```
00000000000013c0 <iree_hal_executable_library_query-0x80>:
    13c0:       55                      push   rbp
    13c1:       48 89 e5                mov    rbp,rsp
    13c4:       48 8b 4e 20             mov    rcx,QWORD PTR [rsi+0x20]
    13c8:       48 8b 01                mov    rax,QWORD PTR [rcx]
    13cb:       48 8b 49 08             mov    rcx,QWORD PTR [rcx+0x8]
    13cf:       31 d2                   xor    edx,edx
    13d1:       66 66 66 66 66 66 2e    data16 data16 data16 data16 data16 nop WORD PTR cs:[rax+rax*1+0x0]
    13d8:       0f 1f 84 00 00 00 00
    13df:       00
    13e0:       be 3c 00 00 00          mov    esi,0x3c
    13e5:       48 89 c7                mov    rdi,rax
    13e8:       0f 1f 84 00 00 00 00    nop    DWORD PTR [rax+rax*1+0x0]
    13ef:       00
    13f0:       62 f1 7c 48 28 07       vmovaps zmm0,ZMMWORD PTR [rdi]
    13f6:       c5 fc 29 44 31 c4       vmovaps YMMWORD PTR [rcx+rsi*1-0x3c],ymm0
    13fc:       c5 fc 28 47 20          vmovaps ymm0,YMMWORD PTR [rdi+0x20]
    1401:       c5 fc 29 44 31 e4       vmovaps YMMWORD PTR [rcx+rsi*1-0x1c],ymm0
    1407:       48 83 c6 40             add    rsi,0x40
    140b:       48 81 c7 80 84 1e 00    add    rdi,0x1e8480
    1412:       48 81 fe 3c 2c 01 00    cmp    rsi,0x12c3c
    1419:       75 d5                   jne    13f0 <iree_hal_executable_library_query-0x50>
    141b:       48 ff c2                inc    rdx
    141e:       48 83 c0 40             add    rax,0x40
    1422:       48 81 c1 00 2c 01 00    add    rcx,0x12c00
    1429:       48 81 fa 12 7a 00 00    cmp    rdx,0x7a12
    1430:       75 ae                   jne    13e0 <iree_hal_executable_library_query-0x60>
    1432:       31 c0                   xor    eax,eax
    1434:       5d                      pop    rbp
    1435:       c5 f8 77                vzeroupper
    1438:       c3                      ret
    1439:       cc                      int3
    143a:       cc                      int3
    143b:       cc                      int3
    143c:       cc                      int3
    143d:       cc                      int3
    143e:       cc                      int3
    143f:       cc                      int3
```

For 8-threaded, llvm-cpu is 1.5 x slower than microkernel. One takes 420 ms and the other takes 275 ms. I will take a look at it.

**Comment by hanhanW** [comment]
cc @bjacob who has experience about packing performance.

**Comment by bjacob** [comment]
@hanhanW 

```
00000000000013c0 <iree_hal_executable_library_query-0x80>:
```

pro tip: compile with `--iree-llvmcpu-link-embedded=false` to generate binaries that system tools such as `objdump` here understand properly --- here, that would give you proper function symbols instead of offsets into `iree_hal_executable_library_query`, the only symbol unless is passed `--iree-llvmcpu-link-embedded=false`.

```
    13f0:       62 f1 7c 48 28 07       vmovaps zmm0,ZMMWORD PTR [rdi]
    13f6:       c5 fc 29 44 31 c4       vmovaps YMMWORD PTR [rcx+rsi*1-0x3c],ymm0
    13fc:       c5 fc 28 47 20          vmovaps ymm0,YMMWORD PTR [rdi+0x20]
    1401:       c5 fc 29 44 31 e4       vmovaps YMMWORD PTR [rcx+rsi*1-0x1c],ymm0
    1407:       48 83 c6 40             add    rsi,0x40
    140b:       48 81 c7 80 84 1e 00    add    rdi,0x1e8480
    1412:       48 81 fe 3c 2c 01 00    cmp    rsi,0x12c3c
    1419:       75 d5                   jne    13f0 <iree_hal_executable_library_query-0x50>
```

That's the loop here. The loop body is copying 64 contiguous bytes (makes sense, that's 16 floats). It's doing it with 32-byte AVX instructions (see `ymm`), which is fair enough. Since AVX-512 is enabled here, it could technically do it with 2x fewer 64-byte instructions (with `zmm`), but that wouldn't necessarily be faster. I wouldn't bother.

There isn't much to improve on that. In any case, it's not bad in any way.

> I compared the performance with ukernel and found that they all take 1 second to finish. I think we don't have much things to do on single-threaded.

Indeed. This code being fine meshes well with your finding that it performs as well as the ukernel, so indeed there is no codegen issue here.

> For 8-threaded, llvm-cpu is 1.5 x slower than microkernel. One takes 420 ms and the other takes 275 ms. I will take a look at it.

Hah, that's interesting!  I suspect the performance difference might be caused by a suboptimal choice of distribution tile size (as in lowering_config) for the non-ukernel path.  Indeed, since you found that 1-thread performance is equivalent, it's not a codegen issue, and then if it's a threading issue, the choice of tile size in each codegen pipeline is the main thing that comes to mind that could explain such a difference.

**Comment by dcaballe** [comment]
I understand there is a transpose but we are transposing "sub-planes", not individual elements. I have to run right now but the second load seems redundant, as those 32 bytes are read by the first zmm load. The stores are also using ymm registers. I think we should be able to find a tile size configuration to end up with two zmm loads + some 256-bit-lane inserts/extracts + 2 zmm stores. That would have a larger memory footprint that we would be moving more element with the same number of loads/stores as above.

Ultimately, though, we want to make sure this is fused with its producer so I would prioritize https://github.com/openxla/iree/issues/15242 over this one.

**Comment by bjacob** [comment]
> I have to run right now but the second load seems redundant, as those 32 bytes are read by the first zmm load.

Oh! Good catch.  I totally missed that when I read this code.  I misread it as two ymm loads.  You're right that this is redundant.

**Comment by dcaballe** [comment]
> For 8-threaded, llvm-cpu is 1.5 x slower than microkernel. One takes 420 ms and the other takes 275 ms. I will take a look at it.

Ha! We are running with 8 threads so that's adding up to the regression, definitely. I was planning to file another issue about distribution because I see runtime methods pretty high in the profile. Let me do that tomorrow. I think that's an issue beyond the pack op. I was asking somewhere else if we have different distribution configurations for DT and non-DT. I would expect this layer to be shared between any strategy so we should at least make progress towards that goal. This is something that we should take into account for the tile size selection work (@pzread)

**Comment by hanhanW** [comment]
Scoping the work for this issue. Instead of generating below snippet

```
    13f0:       62 f1 7c 48 28 07       vmovaps zmm0,ZMMWORD PTR [rdi]
    13f6:       c5 fc 29 44 31 c4       vmovaps YMMWORD PTR [rcx+rsi*1-0x3c],ymm0
    13fc:       c5 fc 28 47 20          vmovaps ymm0,YMMWORD PTR [rdi+0x20]
    1401:       c5 fc 29 44 31 e4       vmovaps YMMWORD PTR [rcx+rsi*1-0x1c],ymm0
```

We need to replace it with either (1 zmm load, 1 zmm store) or change the first zmm load to be a ymm load instead.

For the distribution issue, let's track in https://github.com/openxla/iree/issues/15391

**Comment by hanhanW** [comment]
We are able to generate good code, thought it does not help performance. It's unrolled by LLVM backend. There are 8 zmm load and store pairs in the final code. I will work on the PR.

```
    13d0:	62 f1 7c 48 28 07    	vmovaps zmm0,ZMMWORD PTR [rdi]
    13d6:	62 f1 7c 48 29 44 31 	vmovaps ZMMWORD PTR [rcx+rsi*1-0x1c0],zmm0
    13dd:	f9 
    13de:	62 f1 7c 48 28 87 80 	vmovaps zmm0,ZMMWORD PTR [rdi+0x1e8480]
    13e5:	84 1e 00 
    13e8:	62 f1 7c 48 29 44 31 	vmovaps ZMMWORD PTR [rcx+rsi*1-0x180],zmm0
    13ef:	fa 
    13f0:	62 f1 7c 48 28 87 00 	vmovaps zmm0,ZMMWORD PTR [rdi+0x3d0900]
    13f7:	09 3d 00 
    13fa:	62 f1 7c 48 29 44 31 	vmovaps ZMMWORD PTR [rcx+rsi*1-0x140],zmm0
    1401:	fb 
    1402:	62 f1 7c 48 28 87 80 	vmovaps zmm0,ZMMWORD PTR [rdi+0x5b8d80]
    1409:	8d 5b 00 
    140c:	62 f1 7c 48 29 44 31 	vmovaps ZMMWORD PTR [rcx+rsi*1-0x100],zmm0
    1413:	fc 
    1414:	62 f1 7c 48 28 87 00 	vmovaps zmm0,ZMMWORD PTR [rdi+0x7a1200]
    141b:	12 7a 00 
    141e:	62 f1 7c 48 29 44 31 	vmovaps ZMMWORD PTR [rcx+rsi*1-0xc0],zmm0
    1425:	fd 
    1426:	62 f1 7c 48 28 87 80 	vmovaps zmm0,ZMMWORD PTR [rdi+0x989680]
    142d:	96 98 00 
    1430:	62 f1 7c 48 29 44 31 	vmovaps ZMMWORD PTR [rcx+rsi*1-0x80],zmm0
    1437:	fe 
    1438:	62 f1 7c 48 28 87 00 	vmovaps zmm0,ZMMWORD PTR [rdi+0xb71b00]
    143f:	1b b7 00 
    1442:	62 f1 7c 48 29 44 31 	vmovaps ZMMWORD PTR [rcx+rsi*1-0x40],zmm0
    1449:	ff 
    144a:	62 f1 7c 48 28 87 80 	vmovaps zmm0,ZMMWORD PTR [rdi+0xd59f80]
    1451:	9f d5 00 
    1454:	62 f1 7c 48 29 04 31 	vmovaps ZMMWORD PTR [rcx+rsi*1],zmm0
    145b:	48 81 c7 00 24 f4 00 	add    rdi,0xf42400
    1462:	48 81 c6 00 02 00 00 	add    rsi,0x200
    1469:	48 81 fe c0 2d 01 00 	cmp    rsi,0x12dc0
    1470:	0f 85 5a ff ff ff    	jne    13d0 <main_dispatch_0+0x30>
```

The full asm dump can be found at [here](https://gist.github.com/hanhanW/b89f2f6fe7d93dea06976bb3cb8280cd). Distribution is disabled, so it looks cleaner.

**Comment by dcaballe** [comment]
Thanks! I think we disabled LLVM unrolling quite some time ago, didn't we? Anyways, do you have a PR that I can try? More pack/unpack issues are bubbling up after some of the fixes and want to make sure it's not an issue that overlaps with this.

**Comment by hanhanW** [comment]
You can apply below patch to get it:

```mlir
diff --git a/compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp b/compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
index 900d564a0..736a92b5b 100644
--- a/compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
+++ b/compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
@@ -646,6 +646,8 @@ void addCPUDataTilingPipeline(OpPassManager &passManager,
   addBufferizePasses(nestedModulePM);
 
   {
+    nestedModulePM.addNestedPass<func::FuncOp>(
+        createOptimizeVectorTransferPass(/*flatten=*/false));
     LLVMCPUVectorLoweringPassOptions options;
     options.splitVectorTransfersTo = "linalg-copy";
     nestedModulePM.addNestedPass<func::FuncOp>(
```

**Comment by hanhanW** [comment]
> Thanks! I think we disabled LLVM unrolling quite some time ago, didn't we?

I thought we did it, but it seems not.

https://github.com/openxla/iree/blob/d99527b94d4f69f22982288625cec7c715cdca49/compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMTargetOptions.h#L41

**Comment by dcaballe** [comment]
Oh, we disabled vectorization but not unrolling... We should try again one of these days... :)

> You can apply below patch to get it:

Is this something you plan to land or are there any perf concerns?

**Comment by hanhanW** [comment]
> Is this something you plan to land or are there any perf concerns?

I will land it. It is a p2 issue on my plate because it does not help the issue. I will create a PR and kick start a benchmark later.
