### ISSUE TITLE
Support sub-byte emulation for vector.store

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#15369]
https://github.com/llvm/llvm-project/pull/70293 implements the emulation logic, and we need to test if that work with IREE. Below is one of examples that can't be compiled now. We should make sure that we are able to add the test to `tests/e2e/linalg/f32_to_i4.mlir`.

```mlir
func.func @f32_to_i4_1d() {
  %input = util.unfoldable_constant dense<[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]> : tensor<8xf32>
  %0 = tensor.empty() : tensor<8xi4>
  %res = linalg.generic {indexing_maps = [affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>], iterator_types = ["parallel"]}
    ins(%input : tensor<8xf32>) outs(%0 : tensor<8xi4>) {
  ^bb0(%in: f32, %out: i4):
    %2 = arith.fptoui %in : f32 to i32
    %3 = arith.trunci %2 : i32 to i4
    linalg.yield %3 : i4
  } -> tensor<8xi4>
  check.expect_eq_const(%res, dense<[0, 1, 2, 3, 4, 5, 6, 7]> : tensor<8xi4>) : tensor<8xi4>
  return
}
```

**Comment by hanhanW** [comment]
@saienduri please help verify if it's working with your patch or not; enable the test once the change gets into IREE.

**Comment by saienduri** [comment]
Sorry missed this, looking into it now.

**Comment by saienduri** [comment]
Hey @hanhanW , as an update regarding this, the test is not working with my patch. This is the error that is being thrown:
```
/home/sai/iree/tests/e2e/linalg/f32_to_i4.mlir:4:10: error: failed to legalize operation 'memref.store' that was explicitly marked illegal
  %res = linalg.generic {indexing_maps = [affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>], iterator_types = ["parallel"]}
```
When this sub-byte emulation task was initially brought to me, I remember Mahesh mentioning that vector.store and memref.store both have to be supported for sub-byte types before e2e will work. Do you think memref.store needs further implementation for sub-byte emulation?

**Comment by hanhanW** [comment]
I thought that we are able to run it because we are able to vectorize the dispatch. Can you share the command and IR dump?

We still need memref.store for some cases for sure. I put details to https://github.com/openxla/iree/issues/15370, please take a look.

**Comment by saienduri** [comment]
The memref error was happening on the Vulkan backend, but here is the status for llvm-cpu. It looks like the f32_to_i4.mlir can be compiled, but there is an error being thrown when running the e2e test (so probably compiler bug).
Here is the IR dump after iree-compile: https://gist.github.com/saienduri/d212f6080966524d171fcbff129e30f4#file-gistfile1-txt
Then, when we run the iree-check-module on the vmfb generated by the compile, we are running into this error:
```
iree/tools/iree-check-module-main.cc:66: Failure
Value of: iree_vm_invoke(context_, function_, IREE_VM_INVOCATION_FLAG_NONE, nullptr, nullptr, nullptr, iree_vm_instance_allocator(instance_))
Expected: error code OK
  Actual: 0x55b07356808b, whose error code is OUT_OF_RANGE: iree/runtime/src/iree/hal/buffer.c:449: OUT_OF_RANGE; attempted to access an address outside of the valid buffer range (offset=0, adjusted_length=8, end=7, buffer byte_length=4); while invoking C++ function check.expect_eq; while calling import; 
[ 1]   native check.expect_eq:0 -
[ 0] bytecode module.f32_to_i4_1d:724 ./tests/e2e/linalg/f32_to_i4.mlir:11:3
      at ./tests/e2e/linalg/f32_to_i4.mlir:1:1

[  FAILED  ] module.f32_to_i4_1d, where GetParam() = 0 (1 ms)
```
Hopefully this information helps, and we can support sub-byte emulation for storing soon :)

**Comment by hanhanW** [comment]
I took a look and feel that the emulation logic is okay. If we replace i4 with i8 and use 32 bit for load/store emulation, it passes the compilation and correctness test. The issue should happen on other place (e.g., subspan op conversion, etc), looking..

**Comment by hanhanW** [comment]
@MaheshRavishankar you fixed issues for i4 load, would you like to take a look at the dump when you're available?

**Comment by hanhanW** [comment]
I'm not sure if there are runtime or vm issues or not. If I passed `--trace_execution`, it looks like it successfully executes. But it fails in printing them out:

```
...
[module.f32_to_i4_1d+00000192]    vm.cond_br %i0(0), ^000001CE(), ^000001A2()
[module.f32_to_i4_1d+000001A3]    %r0 = vm.call.varadic @hal.buffer_view.create(%r0(!hal.buffer/0x0x6000007dc040), %i8(0), %i6(4), %i13(268435460), %i16(1), %i14(8))
[module.f32_to_i4_1d+000001C8]    vm.return %r0(!hal.buffer_view/0x0x6000029dc580)
OUT_OF_RANGE; printing results; stack:
  0x0000000104e1abdc iree-run-module <iree_tooling_run_module_with_data+0x4cc>
  0x0000000104e0988c iree-run-module <main+0x78>
  0x00000001a2f0ff28 dyld <start+0x8bc>
; processing function outputs
```

If the input is i8, it looks okay. They have the same vm log.

```mlir
...
[module.f32_to_i8_1d+00000186]    vm.cond_br %i0(0), ^000001C2(), ^00000196()
[module.f32_to_i8_1d+00000197]    %r0 = vm.call.varadic @hal.buffer_view.create(%r0(!hal.buffer/0x0x6000022f0040), %i8(0), %i6(8), %i13(268435464), %i14(1), %i6(8))
[module.f32_to_i8_1d+000001BC]    vm.return %r0(!hal.buffer_view/0x0x600000cfc040)
result[0]: hal.buffer_view
8xi8=0 1 2 3 4 5 6 7
```

@benvanik would you advice how do I narrow the issue down? The emulation works for i8 types, but not i4 types. Do you smell something suspicious?

We are able to execute the vmfb using `iree-run-module`, but not `iree-check-module`. If we try to print i4 buffers using `iree-run-module`, it also fails. I feel that there is something not implemented yet on runtime side or check dialects.

**Comment by hanhanW** [comment]
The error from `iree-check-module`:

```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from module
[ RUN      ] module.f32_to_i4_1d
iree2/tools/iree-check-module-main.cc:66: Failure
Value of: iree_vm_invoke(context_, function_, IREE_VM_INVOCATION_FLAG_NONE, nullptr, nullptr, nullptr, iree_vm_instance_allocator(instance_))
Expected: error code OK
  Actual: 0x60000268c02b, whose error code is OUT_OF_RANGE: iree2/runtime/src/iree/hal/buffer.c:449: OUT_OF_RANGE; attempted to access an address outside of the valid buffer range (offset=0, adjusted_length=8, end=7, buffer byte_length=4); stack:
  0x0000000100bce9dc iree-check-module <_ZN4iree12_GLOBAL__N_116CheckModuleState8ExpectEqENS_2vm3refI17iree_hal_device_tEENS3_I22iree_hal_buffer_view_tEES7_+0x170>
  0x0000000100be0060 iree-check-module <_ZN4iree2vm7packing19DispatchFunctorVoidINS_12_GLOBAL__N_116CheckModuleStateEJNS0_3refI17iree_hal_device_tEENS5_I22iree_hal_buffer_view_tEES9_EE4CallEMS4_FvvEPS4_P15iree_vm_stack_t23iree_vm_function_call_t+0x94>
  0x0000000100be0b30 iree-check-module <_ZN4iree2vm12NativeModuleINS_12_GLOBAL__N_116CheckModuleStateEE15ModuleBeginCallEPvP15iree_vm_stack_t23iree_vm_function_call_t+0x94>
  0x0000000100bf11f8 iree-check-module <iree_vm_bytecode_issue_import_call+0x60>
  0x0000000100bf0c14 iree-check-module <iree_vm_bytecode_call_import+0x11c>
  0x0000000100bee9d4 iree-check-module <iree_vm_bytecode_dispatch+0x38d0>
  0x0000000100beb0e4 iree-check-module <iree_vm_bytecode_dispatch_begin+0x118>
  0x0000000100bf2d3c iree-check-module <iree_vm_bytecode_module_begin_call+0xd4>
  0x0000000100c733a0 iree-check-module <iree_vm_begin_invoke+0x370>
  0x0000000100c72f28 iree-check-module <iree_vm_invoke+0x98>
  0x0000000100bbc840 iree-check-module <_ZN4iree12_GLOBAL__N_115CheckModuleTest8TestBodyEv+0x1e4>
  0x0000000100c1b8d8 iree-check-module <_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc+0x5c>
  0x0000000100c1b82c iree-check-module <_ZN7testing4Test3RunEv+0x1bc>
; while invoking C++ function check.expect_eq; while calling import;
[ 1]   native check.expect_eq:0 -
[ 0] bytecode module.f32_to_i4_1d:724 /Users/hanchung/z.mlir:11:3
      at /Users/hanchung/z.mlir:1:1
```

**Comment by hanhanW** [comment]
I think we are hitting this issue as well: https://github.com/openxla/iree/issues/14996

> Runtime buffer views don't currently support sub-byte types. I've got some progress on making them but it's still a ways out. As a workaround you can convert to a byte-aligned type and do the comparison instead.

@benvanik would you like to share the status about it?

**Comment by MaheshRavishankar** [comment]
One way to verify is to have a subsequent operation that converts i4 to i8 and checking on that. Might need an optimization barrier to stop those from fusing...

**Comment by hanhanW** [comment]
> Might need an optimization barrier to stop those from fusing...

The trick is using `util.optimization_barrier`, let me give it a shot

https://github.com/openxla/iree/blob/970e0f700a3fa1f6b761ca866e199fdfd34c6b57/tests/e2e/tensor_ops/pack.mlir#L15C2-L16

**Comment by hanhanW** [comment]
okay, I'm able to run it. We can at least land the test for coverage.
