### ISSUE TITLE
[DT][GlobalOpt] Add lifting for non-batch matmul generic ops

### ISSUE THREAD

**Issue by Max191** [iree-org/iree#15373]
https://github.com/openxla/iree/pull/15339 Implements a lifting of `linalg.generic` ops into transposes + `linalg.batch_matmul` when possible. Right now, it only handles batch cases, but in the future it would be good to fill out the remaining regular matmul cases.

**Comment by hanhanW** [comment]
do we still need this?

**Comment by Max191** [comment]
Nope, the pass is gone now
