### ISSUE TITLE
[CPU] Improve distribution tile sizes when using DT

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#15391]
I can see `iree_hal_cmd_dispatch_tile` and `iree_task_dispatch_shard_execute` pretty high in the profile of a large internal model when enabling DT. We know that we are not doing great wrt distribution tile sizes in general but it seems to get worse when enabling DT. I'm working on the long term solution of this (dynamic distribution sizes using the number of threads at runtime) but that's going to take some time and we should try to palliate this issue for DT in the time being to minimize the performance impact. It looks like for mmt4d, we are setting fixed distribution sizes like this (KernelDIspatch.cpp):

```
static LogicalResult setRootConfig(func::FuncOp entryPointFn,
                                   linalg::Mmt4DOp mmt4dOp) {
  assert(!getLoweringConfig(mmt4dOp) && "expected lowering_config is not set");
  auto getDistTileSizes = [&]() -> SmallVector<int64_t> {
    if (!clMmt4dDistributionTileSizes.empty()) {
      return SmallVector<int64_t>(clMmt4dDistributionTileSizes.begin(),
                                  clMmt4dDistributionTileSizes.end());
    }
    unsigned numLoops = mmt4dOp.getNumLoops();
    SmallVector<int64_t> minTileSizes(numLoops, 0);
    SmallVector<int64_t> maxTileSizes(numLoops, 0);
    minTileSizes[0] = 4;
    minTileSizes[1] = 4;
    maxTileSizes[0] = 48;
    maxTileSizes[1] = 32;
    SmallVector<int64_t> distTileSizes = getDefaultDistributedLevelTileSizes(
        mmt4dOp, minTileSizes, maxTileSizes);
    return distTileSizes;
  };
```

Perhaps we could try to use the same logic here as we use to compute the non-DT distribution sizes (kernel dispatch):

```
      if (numLoops == 3) {                                                                                                                                                                                            
        maxTileSizes[0] = 192;                                                                                                                                                                                        
        maxTileSizes[1] = 128;                                                                                                                                                                                        
      }
```

and see how it goes. It also looks like this might be impacting the performance of other ops beyond mmt4d (see https://github.com/openxla/iree/issues/15349#issuecomment-1790068368)

**Comment by hanhanW** [comment]
https://github.com/openxla/iree/pull/15448 + its parents will fix the issue.
