### ISSUE TITLE
[Perf Tracker] Falcon-180B-GPTQ

### ISSUE THREAD

**Issue by vivekkhandelwal1** [iree-org/iree#15404]
Current Perf with 4-way sharding: 79.5 seconds/token
Current Perf with single layer sharding: 94 seconds/token

Tracy Profile Screenshot (4-way sharding): For the first shard out of the four shards - 
https://drive.google.com/file/d/1nLZBYR-o6yb1tHLOqYgg569n3QOoMWKV/view?usp=sharing

Tracy Profile File: https://storage.googleapis.com/shark_tank/falcon/sharded/falcon_180b/falcon_180b_layer_0_20_int4_rocm.tracy

Dispatches are available at: `shark_tank/falcon/sharded/falcon_180b/falcon_180b_layer_0_20_int4_rocm_dispatches/`
URL: https://console.cloud.google.com/storage/browser/shark_tank/falcon/sharded/falcon_180b/falcon_180b_layer_0_20_int4_rocm_dispatches?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=1&prefix=&forceOnObjectsSortingFiltering=false 

Commands to run the model:
1.) 4-way sharded: 
`python apps/language_models/src/pipelines/falcon_pipeline.py --falcon_variant_to_use="180b" --precision="int4" --device="rocm" --sharded --compressed`

2.) Single layer sharded:
`python apps/language_models/src/pipelines/falcon_pipeline.py --falcon_variant_to_use="180b" --precision="int4" --device="rocm" --sharded --compressed`

**Comment by qedawkins** [comment]
This is supposed to be int4 quantized, but the matmuls are all f32. The first major step will be avoiding the materialization of the full f32 weights and keep things in i4.
![Screenshot from 2023-11-03 12-46-55](https://github.com/openxla/iree/assets/22101546/cb857fa5-fc40-45a9-8c75-1827769df42f)

**Comment by qedawkins** [comment]
Adding a follow up comment from an offline discussion. The IR that I have seen for this model will be quite difficult for IREE to handle. The first thing that needs to happen to improve performance here is to fuse the dequantization with the matmul (thereby removing the f32 matmuls), however the IR I remember seeing for this was using bitwise arithmetic to extract the i4 values from the i32 weight tensor into an i8 tensor (wasting 4 bits because pytorch can't represent i4 values).  Additionally, to handle the quantization grouping, it was broadcasting the scale/zero point values with a gather. For example,
```
broadcast 32x1 -> 32x128
torch.broadcast op

broadcast 32x1 -> 4096
index_tensor = [0, 1, 2, 3, ..., 31, 0, 1, ..., 31, ...] (tensor<index x 4096>)
```
@vivekkhandelwal1 are you able to upload the full elided IR either at the Torch or Linalg level? (or both). That would help with verifying that my claims about the IR are correct. Then we can see about improving the implementations within autogptq if need be.

**Comment by vivekkhandelwal1** [comment]
@qedawkins, here's the torch and linalg elided IR:
Torch IR: https://storage.googleapis.com/shark_tank/falcon/sharded/falcon_180b/falcon_180b_gptq_layer_0_20_int4_elided_torch.mlir
Linalg IR: https://storage.googleapis.com/shark_tank/falcon/sharded/falcon_180b/falcon_180b_gptq_layer_0_20_int4_elided_linalg.mlir

Also, the matmuls were originally in fp16 which were upcasted to fp32 because of the numerical precision issue. You can see in the IR that the results of the matmuls are downcasted to fp16.

**Comment by benvanik** [comment]
neat IR! probably some things we could improve the representation of to give codegen a better chance of producing efficient code - for example whatever this is shows up a bunch:
```
    %1340 = linalg.generic {indexing_maps = [#map10, #map11, #map12, #map13, #map14, #map15], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel"]} ins(%expanded_215, %expanded_214, %expanded_213, %expanded_212, %56 : tensor<1x1x1x1x1xi64>, tensor<100x1x1x1xi64>, tensor<8x1x1xi64>, tensor<1x1xi64>, tensor<64xi64>) outs(%62 : tensor<1x100x8x1x64xf16>) {
    ^bb0(%in: i64, %in_984: i64, %in_985: i64, %in_986: i64, %in_987: i64, %out: f16):
      %1610 = arith.cmpi slt, %in, %c0_i64 : i64
      %1611 = arith.addi %in, %c1_i64 : i64
      %1612 = arith.select %1610, %1611, %in : i64
      %1613 = arith.index_cast %1612 : i64 to index
      %1614 = arith.cmpi slt, %in_984, %c0_i64 : i64
      %1615 = arith.addi %in_984, %c100_i64 : i64
      %1616 = arith.select %1614, %1615, %in_984 : i64
      %1617 = arith.index_cast %1616 : i64 to index
      %1618 = arith.cmpi slt, %in_985, %c0_i64 : i64
      %1619 = arith.addi %in_985, %c8_i64 : i64
      %1620 = arith.select %1618, %1619, %in_985 : i64
      %1621 = arith.index_cast %1620 : i64 to index
      %1622 = arith.cmpi slt, %in_986, %c0_i64 : i64
      %1623 = arith.addi %in_986, %c18_i64 : i64
      %1624 = arith.select %1622, %1623, %in_986 : i64
      %1625 = arith.index_cast %1624 : i64 to index
      %1626 = arith.cmpi slt, %in_987, %c0_i64 : i64
      %1627 = arith.addi %in_987, %c64_i64 : i64
      %1628 = arith.select %1626, %1627, %in_987 : i64
      %1629 = arith.index_cast %1628 : i64 to index
      %extracted = tensor.extract %expanded_838[%1613, %1617, %1621, %1625, %1629] : tensor<1x100x8x18x64xf16>
      linalg.yield %extracted : f16
    } -> tensor<1x100x8x1x64xf16>
```
(doubt this is what is slow, but it's curious looking!)

**Comment by antiagainst** [comment]
Looking at the IR, quite a few issues:

1. What @qedawkins said in the above is to the point. We have quite some logic to process the i32 tensor weights on the fly, using i8 as an subsitute where i4 should exist. I'm expecting the weight should be directly encoded as i4 tensor. Fixing this would help us to avoid the redundant computation and make the IR less confusing.

```
    %expanded = tensor.expand_shape %cst_184 [[0], [1, 2]] : tensor<1x1152xi32> into tensor<1x1152x1xi32>
    %27 = tensor.empty() : tensor<1x1152x8xi32>
    %28 = linalg.generic {indexing_maps = [#map2, #map1], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded : tensor<1x1152x1xi32>) outs(%27 : tensor<1x1152x8xi32>) {
    ^bb0(%in: i32, %out: i32):
      linalg.yield %in : i32
    } -> tensor<1x1152x8xi32>
    %expanded_201 = tensor.expand_shape %cst_183 [[0, 1], [2]] : tensor<1x8xi32> into tensor<1x1x8xi32>
    %29 = linalg.generic {indexing_maps = [#map, #map5, #map1], iterator_types = ["parallel", "parallel", "parallel"]} ins(%28, %expanded_201 : tensor<1x1152x8xi32>, tensor<1x1x8xi32>) outs(%27 : tensor<1x1152x8xi32>) {
    ^bb0(%in: i32, %in_984: i32, %out: i32):
      %1610 = arith.shrsi %in, %in_984 : i32
      linalg.yield %1610 : i32
    } -> tensor<1x1152x8xi32>
    %30 = tensor.empty() : tensor<1x1152x8xi8>
    %31 = linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["parallel", "parallel", "parallel"]} ins(%29 : tensor<1x1152x8xi32>) outs(%30 : tensor<1x1152x8xi8>) {
    ^bb0(%in: i32, %out: i8):
      %1610 = arith.trunci %in : i32 to i8
      linalg.yield %1610 : i8
    } -> tensor<1x1152x8xi8>
    %32 = linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["parallel", "parallel", "parallel"]} ins(%31 : tensor<1x1152x8xi8>) outs(%30 : tensor<1x1152x8xi8>) {
    ^bb0(%in: i8, %out: i8):
      %1610 = arith.andi %in, %c15_i8 : i8
      linalg.yield %1610 : i8
    } -> tensor<1x1152x8xi8>
    %33 = linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["parallel", "parallel", "parallel"]} ins(%32 : tensor<1x1152x8xi8>) outs(%30 : tensor<1x1152x8xi8>) {
    ^bb0(%in: i8, %out: i8):
      %1610 = arith.addi %in, %c1_i8 : i8
      linalg.yield %1610 : i8
    } -> tensor<1x1152x8xi8>
    %collapsed_202 = tensor.collapse_shape %33 [[0], [1, 2]] : tensor<1x1152x8xi8> into tensor<1x9216xi8>
    %expanded_203 = tensor.expand_shape %collapsed_202 [[0], [1, 2]] : tensor<1x9216xi8> into tensor<1x1x9216xi8>
    %expanded_204 = tensor.expand_shape %cst_182 [[0], [1, 2]] : tensor<1x9216xf16> into tensor<1x1x9216xf16>
    %expanded_205 = tensor.expand_shape %cst_181 [[0], [1, 2]] : tensor<1024x9216xi32> into tensor<1024x1x9216xi32>
    %34 = tensor.empty() : tensor<1024x8x9216xi32>
    %35 = linalg.generic {indexing_maps = [#map6, #map1], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded_205 : tensor<1024x1x9216xi32>) outs(%34 : tensor<1024x8x9216xi32>) {
    ^bb0(%in: i32, %out: i32):
      linalg.yield %in : i32
    } -> tensor<1024x8x9216xi32>
    %expanded_206 = tensor.expand_shape %cst_183 [[0], [1, 2]] : tensor<1x8xi32> into tensor<1x8x1xi32>
    %36 = linalg.generic {indexing_maps = [#map1, #map3, #map1], iterator_types = ["parallel", "parallel", "parallel"]} ins(%35, %expanded_206 : tensor<1024x8x9216xi32>, tensor<1x8x1xi32>) outs(%34 : tensor<1024x8x9216xi32>) {
    ^bb0(%in: i32, %in_984: i32, %out: i32):
      %1610 = arith.shrsi %in, %in_984 : i32
      linalg.yield %1610 : i32
    } -> tensor<1024x8x9216xi32>
    %37 = tensor.empty() : tensor<1024x8x9216xi8>
    %38 = linalg.generic {indexing_maps = [#map1, #map1], iterator_types = ["parallel", "parallel", "parallel"]} ins(%36 : tensor<1024x8x9216xi32>) outs(%37 : tensor<1024x8x9216xi8>) {
    ^bb0(%in: i32, %out: i8):
      %1610 = arith.trunci %in : i32 to i8
      linalg.yield %1610 : i8
    } -> tensor<1024x8x9216xi8>
    %39 = linalg.generic {indexing_maps = [#map1, #map1], iterator_types = ["parallel", "parallel", "parallel"]} ins(%38 : tensor<1024x8x9216xi8>) outs(%37 : tensor<1024x8x9216xi8>) {
    ^bb0(%in: i8, %out: i8):
      %1610 = arith.andi %in, %c15_i8 : i8
      linalg.yield %1610 : i8
    } -> tensor<1024x8x9216xi8>
    %collapsed_207 = tensor.collapse_shape %39 [[0, 1], [2]] : tensor<1024x8x9216xi8> into tensor<8192x9216xi8>
    %expanded_208 = tensor.expand_shape %collapsed_207 [[0, 1], [2]] : tensor<8192x9216xi8> into tensor<1x8192x9216xi8>
    %40 = tensor.empty() : tensor<1x8192x9216xi8>
    %41 = linalg.generic {indexing_maps = [#map, #map5, #map1], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded_208, %expanded_203 : tensor<1x8192x9216xi8>, tensor<1x1x9216xi8>) outs(%40 : tensor<1x8192x9216xi8>) {
    ^bb0(%in: i8, %in_984: i8, %out: i8):
      %1610 = arith.subi %in, %in_984 : i8
      linalg.yield %1610 : i8
    } -> tensor<1x8192x9216xi8>
  ...
```

2. Once with the above done we need to fuse the i4 dequant linalg.generic togther the matmul linalg.generic together to avoid materializing the f32 inputs, which costs compute and memory bandwidth. 
3. The upcasting from f16 to f32 and then downcasting could be problematic given that it may require extra allocations depending how we fuse stuff.. I haven't verified this is indeed an issue though. I guess it's necessary for 180B. Do we also need that for 40B (https://github.com/openxla/iree/issues/15461)?
4. Even looking at the current f32 matmul pipeline, the heuristics is not good -- for MxNxK=100x8192x32768, we are using a workgorup size of 32 threads.. ROCm basically is reusing the hardcoded tile sizes chosen for CUDA A100.. We should clean that up.

**Comment by ScottTodd** [comment]
This issue look stale. Can we close it?
