### ISSUE TITLE
IREE perf dashboard provides a link which is 404 - Page Not Found

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#15408]
In one of [dashboard](https://perf.iree.dev/serie?IREE?c28be7f493ec9bc790631b3f90dfe611da5a10ac37e23ddebc80530fc61df2f5), it directs me to https://github.com/openxla/iree/tree/main/benchmarks/dashboard.md which is `404 - Page Not Found`.

![image](https://github.com/openxla/iree/assets/6949191/92d3c1d1-46b8-42a7-bafa-e5942d0fc2fb)

**Comment by ScottTodd** [comment]
I think those links are built into the site itself? New link should be https://iree.dev/developers/performance/benchmark-suites/
