### ISSUE TITLE
iree_vm_buffer_deinitialize aborts on Metal backend

### ISSUE THREAD

**Issue by gmmyung** [iree-org/iree#15422]
### What happened?

Sorry for not providing a reproducible code; it is quite difficult to reproduce, I have no idea where to start.

I tried to run a resnet50 model from HuggingFace by using the Rust bindings I have built, and it worked flawlessly on `llvm-cpu`.

But when I try to run it on the `metal` backend, the function invokes flawlessly once again, but aborts in `iree_runtime_session_release`, right on  `buffer.c` line 79.

https://github.com/openxla/iree/blob/8ca883f980612ab4b3a33f52e46ba75855b60c11/runtime/src/iree/vm/buffer.c#L77-L81

Call stack is as shown:
<img width="409" alt="image" src="https://github.com/openxla/iree/assets/25163944/59acf0c3-13d8-4263-b594-12053ddeeff4">

Variables just before aborting:
<img width="515" alt="image" src="https://github.com/openxla/iree/assets/25163944/a9eab605-64d6-4565-b79b-0a0755fcb4e3">

I have also tried a dummy function, and this time the weird reference count problem does not happen.
```mlir
module {
  func.func @serving_default(%arg0: tensor<1x3x224x224xf32>) -> tensor<1x1000xf32> {
    %0 = arith.constant dense<[[0.0, ....... 0.0]]> : tensor<1x1000xf32>
    return %0 : tensor<1x1000xf32>
  }
}
```

Here is what I am doing in Rust for context:

```Rust
fn run(vmfb: &[u8], image_bin: &[f32]) -> Vec<f32> {
    use iree_rs::runtime;
    use iree_rs::runtime::vm::ToRef;

    let instance = runtime::api::Instance::new(
        &runtime::api::InstanceOptions::new(&mut runtime::hal::DriverRegistry::new())
            .use_all_available_drivers(),
    )
    .unwrap();
    let device = instance
        .try_create_default_device("metal")
        .expect("Failed to create device");
    let session = runtime::api::Session::create_with_device(
        &instance,
        &runtime::api::SessionOptions::default(),
        &device,
    )
    .unwrap();
    unsafe { session.append_module_from_memory(vmfb) }.unwrap();
    let function = session.lookup_function("module.serving_default").unwrap();
    let input_list =
        runtime::vm::DynamicList::<runtime::vm::Ref<runtime::hal::BufferView<f32>>>::new(
            1, &instance,
        )
        .unwrap();
    let input_buffer = runtime::hal::BufferView::<f32>::new(
        &session,
        &[1, 224, 224, 3],
        runtime::hal::EncodingType::DenseRowMajor,
        image_bin,
    )
    .unwrap();
    let input_buffer_ref = input_buffer.to_ref(&instance).unwrap();
    input_list.push_ref(&input_buffer_ref).unwrap();
    let output_list =
        runtime::vm::DynamicList::<runtime::vm::Ref<runtime::hal::BufferView<f32>>>::new(
            1, &instance,
        )
        .unwrap();
    function.invoke(&input_list, &output_list).unwrap();
    let output_buffer_ref = output_list.get_ref(0).unwrap();
    let output_buffer: BufferView<f32> = output_buffer_ref.to_buffer_view();
    let output_mapping = BufferMapping::new(output_buffer).unwrap();
    let out = output_mapping.data().to_vec();
    out
}
```

`iree-run-module` runs without problem with the original mlir. Suggestions on where should I first look into? Any help will be appreciated.

### Version information

bb51f6f1a

**Comment by antiagainst** [comment]
I fixed a ref counting issue w.r.t. metal in https://github.com/openxla/iree/commit/0bdf3384fad72ada9b9ebe33199f479eccc2663c. The version you have there does not include that. Can you try to use the lastest `main` to see if it fixes for you?  The latest `main` also includes a few other fixes for metal like https://github.com/openxla/iree/commit/e79fb2b96efe855409b3d4f457604a8ae902acc5 & https://github.com/openxla/iree/commit/205c88d2aa9d2a9366fbc1b09281db56d2a2238b.

**Comment by gmmyung** [comment]
<img width="965" alt="image" src="https://github.com/openxla/iree/assets/25163944/1e61067f-64cb-4eb9-92a6-cb664d61e9e1">
Works flawlessly 🤣 Thanks for helping!

**Comment by antiagainst** [comment]
Nice!
