### ISSUE TITLE
 [Perf Tracker] Falcon-40B-GPTQ

### ISSUE THREAD

**Issue by vivekkhandelwal1** [iree-org/iree#15461]
Current Perf: 14 seconds/token

Tracy Profile Screenshot: https://drive.google.com/file/d/1Bpp5jo1g9fGCFsSNHB5D61bGTynz1jGI/view?usp=sharing

Tracy Profile File: https://storage.googleapis.com/shark_tank/falcon/falcon_40b_int4_rocm.tracy

Dispatches are available at: shark_tank/falcon/falcon_40b_int4_rocm_dispatches/
URL: https://console.cloud.google.com/storage/browser/shark_tank/falcon/falcon_40b_int4_rocm_dispatches?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=1&prefix=&forceOnObjectsSortingFiltering=false

Command to run the model:
```
python apps/language_models/src/pipelines/falcon_pipeline.py --falcon_variant_to_use="40b" --precision="int4" --device="rocm"
```

**Comment by benvanik** [comment]
(note your drive links are private - you can just post screenshots in github issues instead)

**Comment by vivekkhandelwal1** [comment]
Here's the screenshot, <img width="1400" alt="Screenshot 2023-11-07 at 6 29 13 PM" src="https://github.com/openxla/iree/assets/68822896/d06a0e2a-82ba-432f-8b67-bd565511e6db">

Thanks for the suggestion @benvanik!

**Comment by antiagainst** [comment]
I assume the structure of this model is quite similar to the 180B one (https://github.com/openxla/iree/issues/15404). That one has stripped IR for the original model so I commented there.

**Comment by ScottTodd** [comment]
This issue look stale. Can we close it?
