### ISSUE TITLE
Migrate compiler components to plugin system

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#15468]
<sub>Following up on topics discussed on https://github.com/openxla/iree/pull/15438</sub>

We can migrate more components to use the plugin system, which will help
* Standardize compiler extension points
* Put related components on equal footing, whether they are in-tree or out-of-tree
  * If an in-tree component needs some functionality, out-of-tree components might want it too
* Enforce optionality and keep dependencies separated
* Allow us to split apart the main project (if we want) by moving components from in-tree to out-of-tree

Plugin API docs are at [`compiler/src/iree/compiler/PluginAPI`](https://github.com/openxla/iree/tree/main/compiler/src/iree/compiler/PluginAPI) and https://iree.dev/reference/bindings/c-api/#plugins. In-tree plugins are located at [`compiler/plugins/`](https://github.com/openxla/iree/tree/main/compiler/plugins).

```[tasklist]
### HAL targets
- [x] CUDA --> [`plugins/target/CUDA`](https://github.com/openxla/iree/tree/main/compiler/plugins/target/CUDA) (see PR reference below)
- [x] [LLVMCPU](https://github.com/openxla/iree/tree/main/compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU)
- [x] [MetalSPIRV](https://github.com/openxla/iree/tree/main/compiler/src/iree/compiler/Dialect/HAL/Target/MetalSPIRV)
- [x] [ROCM](https://github.com/openxla/iree/tree/main/compiler/src/iree/compiler/Dialect/HAL/Target/ROCM)
- [x] [VMVX](https://github.com/openxla/iree/tree/main/compiler/src/iree/compiler/Dialect/HAL/Target/VMVX)
- [x] [VulkanSPIRV](https://github.com/openxla/iree/tree/main/compiler/src/iree/compiler/Dialect/HAL/Target/VulkanSPIRV)
- [x] [WebGPU](https://github.com/openxla/iree/tree/main/compiler/src/iree/compiler/Dialect/HAL/Target/WebGPU)
```

```[tasklist]
### Input conversions
- [x] Torch --> [`plugins/input/Torch/`](https://github.com/openxla/iree/tree/main/compiler/plugins/input/Torch) (see PR reference below)
- [x] [StableHLO](https://github.com/openxla/iree/tree/main/compiler/src/iree/compiler/InputConversion/StableHLO)
- [x] [TOSA](https://github.com/openxla/iree/tree/main/compiler/src/iree/compiler/InputConversion/TOSA)
```

```[tasklist]
### References
- [x] https://github.com/openxla/iree/pull/13262
- [x] https://github.com/openxla/iree/pull/14917
- [x] https://github.com/nod-ai/iree-amd-aie
```

**Comment by ScottTodd** [comment]
May want to implement Bazel support for plugin configuration as part of this: https://github.com/openxla/iree/blob/82dc9754ef5e79188c1ec7902cb8cbeaacdd60dd/build_tools/bazel/build_defs.oss.bzl#L87-L92 https://github.com/openxla/iree/blob/82dc9754ef5e79188c1ec7902cb8cbeaacdd60dd/compiler/src/iree/compiler/PluginAPI/Config/BUILD.bazel#L34-L45

**Comment by ScottTodd** [comment]
For the CPU plugin, see [this discussion on Discord](https://discord.com/channels/689900678990135345/1013824803075002389/1173845984955093013) (and surrounding messages)

> were you planning to tacke the CPU plugin? And if so, are there thoughts on how to organize it? I could imagine some approaches making modularity easier.
> (it seems to me that almost all of the code in HAL/Target/LLVMCPU is scaffolding that is needed to build any LLVM-CPU based target and should probably be moved to a support directory in the main code tree. Then the specific pipeline virtual methods, flags, and goo for interfacing to the right LLVM backend go in the plugin. And even those could depend on common code in the Codegen folder)
> (basically, policy in the plugin, scaffolding in the main source tree)
> (there is still some stuff that is commingled in there but it is better than it used to be... I can almost see how to pull it apart)

**Comment by ScottTodd** [comment]
Just a few compiler targets left to migrate.

I started on VulkanSPIRV at https://github.com/ScottTodd/iree/tree/plugin-vulkan. There is some tricky options/flag parsing in there that was introduced by https://github.com/openxla/iree/pull/15309 though (see discussion about it here: https://github.com/openxla/iree/pull/15309#discussion_r1375279507, cc @antiagainst and @qedawkins). I'm not sure how to pull that `llvm::cl` logic into a plugin (the code calls `.getPosition()` and `getNumOccurances()` on the flags themselves, before turning them into regular `SmallVector<std::string>` types).

If that logic is useful enough, maybe we can plumb a hook through the plugin API https://github.com/openxla/iree/blob/7e06b6e5ece2adcda91352331db817adaa058e85/compiler/src/iree/compiler/PluginAPI/Client.h#L222-L225 https://github.com/openxla/iree/blob/7e06b6e5ece2adcda91352331db817adaa058e85/compiler/src/iree/compiler/Utils/OptionUtils.h#L212-L235 

There was a simpler case of options initialization in the ROCM target, where no extra information about the flags themselves was needed: https://github.com/openxla/iree/blob/7e06b6e5ece2adcda91352331db817adaa058e85/compiler/plugins/target/ROCM/ROCMTarget.cpp#L411-L417

**Comment by qedawkins** [comment]
> Just a few compiler targets left to migrate.
> 
> I started on VulkanSPIRV at https://github.com/ScottTodd/iree/tree/plugin-vulkan. There is some tricky options/flag parsing in there that was introduced by #15309 though (see discussion about it here: [#15309 (comment)](https://github.com/openxla/iree/pull/15309#discussion_r1375279507), cc @antiagainst and @qedawkins). I'm not sure how to pull that `llvm::cl` logic into a plugin (the code calls `.getPosition()` and `getNumOccurances()` on the flags themselves, before turning them into regular `SmallVector<std::string>` types).

I might be missing details on what makes this tricky to do with a compiler plugin. How are flags normally supposed to work with a plugin and what is changing here?

Edit: Looking at your branch + some other examples I think I see what the problem is. FWIW this kind of heterogeneous mixing of targets might be useful for other backends too, so finding a good way to do this sounds good.

**Comment by ScottTodd** [comment]
I'm still digging through the code, but there is some indirection. From what I can tell, each plugin can define an options type that gets passed via a template to `PluginSession`, where the actual parsing happens. The plugin then gets created with an instance of that options struct, after the `llvm::cl` details have already been handled.

**Comment by qedawkins** [comment]
> I'm still digging through the code, but there is some indirection. From what I can tell, each plugin can define an options type that gets passed via a template to `PluginSession`, where the actual parsing happens. The plugin then gets created with an instance of that options struct, after the `llvm::cl` details have already been handled.

I will let Lei comment also because I know he has wanted to remove `target-triples` and might have more thoughts here, but one way to do it might be to just drop `iree-vulkan-target-triple` and do some string parsing to figure out whether it is an environment vs a triple. That would require updating a decent number of tests though and be a minor breakage for all downstream flows.

**Comment by qedawkins** [comment]
Or alternatively keep target triples, let envs represent both triples and the `#vk.target_env` attribute, and then make the two flags mutually exclusive. Only if you think the hook is difficult to manage for just this case though.

(Might be easier to chat on discord)

**Comment by ScottTodd** [comment]
Done! https://github.com/openxla/iree/tree/main/compiler/plugins

![image](https://github.com/openxla/iree/assets/4010439/96d10b7a-fa6f-45ee-b406-95ac2c0278c8)
![image](https://github.com/openxla/iree/assets/4010439/98158cdb-f4a8-4e1d-9bdf-ce1b32139e72)
