### ISSUE TITLE
[Python] Failure to send a tensor of < 4 bytes to host

### ISSUE THREAD

**Issue by qedawkins** [iree-org/iree#15508]
# Problem description
The following python code will fail with the following error
```
Traceback (most recent call last):
  File "/home/quinn/model_testing/only_conv.py", line 116, in <module>
    print(iree_output.to_host())
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/quinn/iree-build/runtime/bindings/python/iree/runtime/array_interop.py", line 107, in to_host
    self._transfer_to_host(False)
  File "/home/quinn/iree-build/runtime/bindings/python/iree/runtime/array_interop.py", line 135, in _transfer_to_host
    self._host_array = self._copy_to_host()
                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/quinn/iree-build/runtime/bindings/python/iree/runtime/array_interop.py", line 162, in _copy_to_host
    self._device.queue_copy(
ValueError: Source and target buffer length must match and it does not. Please check allocations

```

```python
import torch

module = """
#map = affine_map<(d0, d1) -> (d0, d1)>
#map1 = affine_map<(d0, d1) -> (d0)>
module {
  func.func @forward(%arg0: tensor<1x?xf16>) -> tensor<1xf16> {
    %c1 = arith.constant 1 : index
    %dim = tensor.dim %arg0, %c1 : tensor<1x?xf16>
    %0 = tensor.empty(%dim) : tensor<1x?xf16>
    %c1_0 = arith.constant 1 : index
    %dim_1 = tensor.dim %arg0, %c1_0 : tensor<1x?xf16>
    %1 = tensor.empty() : tensor<1xf16>
    %cst = arith.constant -6.550400e+04 : f16
    %res = flow.dispatch.region -> (tensor<1xf16>) {
      %2 = linalg.fill ins(%cst : f16) outs(%1 : tensor<1xf16>) -> tensor<1xf16>
      %3 = linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["parallel", "reduction"]} ins(%arg0 : tensor<1x?xf16>) outs(%2 : tensor<1xf16>) {
      ^bb0(%in: f16, %out: f16):
        %7 = arith.maximumf %in, %out : f16
        linalg.yield %7 : f16
      } -> tensor<1xf16>
      %cst_2 = arith.constant 0.000000e+00 : f16
      %4 = linalg.fill ins(%cst_2 : f16) outs(%1 : tensor<1xf16>) -> tensor<1xf16>
      %5 = linalg.generic {indexing_maps = [#map, #map1, #map1], iterator_types = ["parallel", "reduction"]} ins(%arg0, %3 : tensor<1x?xf16>, tensor<1xf16>) outs(%4 : tensor<1xf16>) {
      ^bb0(%in: f16, %in_3: f16, %out: f16):
        %7 = arith.subf %in, %in_3 : f16
        %8 = math.exp %7 : f16
        %9 = arith.addf %8, %out : f16
        linalg.yield %9 : f16
      } -> tensor<1xf16>
      flow.return %5 : tensor<1xf16>
    }
    return %res : tensor<1xf16>
  }
}
"""

example_input = torch.FloatTensor([[2.0, 0.0]]).half()

# Run through IREE vulkan
import iree.runtime as ireert
from iree.runtime import get_driver, get_device
import iree.compiler as ireec

device = "vulkan"
runtime_device = "vulkan"

flatbuffer = ireec.compile_str(
    module,
    target_backends=[device],
    extra_args=[
        "--iree-vulkan-target-triple=rdna3-unknown-linux",
        "--iree-stream-resource-index-bits=64",
        "--iree-vm-target-index-bits=64",
        ],
)

config = ireert.Config(driver_name=runtime_device)
vm_module = ireert.VmModule.from_flatbuffer(config.vm_instance, flatbuffer)
ctx = ireert.SystemContext(config=config)
ctx.add_vm_module(vm_module)
forward = ctx.modules.module["forward"]
iree_output = forward(example_input.numpy())

# Fails due to a size mismatch between the source and target buffer
print(iree_output.to_host())
```

# Investigation

The source (device) buffer will be `2` bytes for the single f16, however when trying to allocate the host buffer to copy into (https://github.com/openxla/iree/blob/d991dc9330d486b804a204e6e18f8287c256def1/runtime/bindings/python/iree/runtime/array_interop.py#L153), it ends up padding the allocation to `4` bytes, causing the sizes to mismatch.

**Comment by benvanik** [comment]
maybe could change the check in hal.cc L590 to instead take `min(source_length, target_length)` until the TODO in there for providing offsets/length is done

**Comment by qedawkins** [comment]
> maybe could change the check in hal.cc #590 to instead take `min(source_length, target_length)` until the TODO in there for providing offsets/length is done

That works for my case, but there are actual tests for this https://github.com/openxla/iree/blob/13de9f3bf706938027fcac9cccc89a02ff7d2ac6/runtime/bindings/python/tests/hal_test.py#L294
Is there some way to get the expected alignment for a buffer like this?

**Comment by qedawkins** [comment]
Actually I see the byte offset and length is already on the `iree_hal_buffer_t` https://github.com/openxla/iree/blob/13de9f3bf706938027fcac9cccc89a02ff7d2ac6/runtime/src/iree/hal/buffer.h#L856

And the HalBuffer class looks a reference to an `iree_hal_buffer_t` https://github.com/openxla/iree/blob/13de9f3bf706938027fcac9cccc89a02ff7d2ac6/runtime/bindings/python/hal.h#L175

How hard would it be to just use the offsets/lengths directly?

**Comment by stellaraccident** [comment]
I can look when at my desk. I don't think alignment will be a problem. An allocation sufficient for a 4byte transaction will always be sufficient for a two byte one.

**Comment by qedawkins** [comment]
> I can look when at my desk. I don't think alignment will be a problem. An allocation sufficient for a 4byte transaction will always be sufficient for a two byte one.

Makes sense, just trying to understand the reasoning behind the original check. If `source < target` is always fine then that works for me.
