### ISSUE TITLE
Missing sub-byte emulation support for memref.alloca

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#15515]
@Max191 reports the issue this morning. The emulation is missing at this moment. It should be as same as what has been done for `memref.alloc`.

https://github.com/llvm/llvm-project/blob/9ef829097bbc4cf908698e3891af11a154e1d3e2/mlir/lib/Dialect/MemRef/Transforms/EmulateNarrowType.cpp#L59

Assigning it to @Max191 for now. If you are not working at it, please reassign it to @saienduri

**Comment by Max191** [comment]
I have a patch that adds support for this. I am triaging some other issues that came up at the moment, but I can try to send it out tomorrow.

**Comment by hanhanW** [comment]
Nice, thanks for pushing on this!
