### ISSUE TITLE
Missing sub-bypte emulation support for vector.maskedstore

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#15540]
To repro, run `iree-opt --iree-codegen-emulate-narrow-type repro.mlir`

```mlir
func.func @foo() {
  %cst = arith.constant dense<0.000000e+00> : vector<16xf32>
  %c0 = arith.constant 0 : index
  %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<8xf32>
  memref.assume_alignment %0, 64 : memref<8xf32>
  %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) : memref<8xi4>
  memref.assume_alignment %1, 64 : memref<8xi4>
  %2 = vector.constant_mask [8] : vector<16xi1>
  %3 = vector.maskedload %0[%c0], %2, %cst : memref<8xf32>, vector<16xi1>, vector<16xf32> into vector<16xf32>
  %4 = arith.fptoui %3 : vector<16xf32> to vector<16xi32>
  %5 = arith.trunci %4 : vector<16xi32> to vector<16xi4>
  vector.maskedstore %1[%c0], %2, %5 : memref<8xi4>, vector<16xi1>, vector<16xi4>
  return
}
```

Error:

```
error: failed to legalize operation 'vector.maskedstore' that was explicitly marked illegal
  vector.maskedstore %1[%c0], %2, %5 : memref<8xi4>, vector<16xi1>, vector<16xi4>
```

**Comment by hanhanW** [comment]
This will be generated by https://github.com/openxla/iree/pull/15539 if we pass target-triple or target cpu to `iree-compile`.

**Comment by hanhanW** [comment]
@tyb0807 I noticed that you recently added support for `vector.maskedload` sub-type emulation. Would you be available to add support for `vector.maskedstore`?

@dcaballe FYI, this will be a blocker once we have const-eval on i4 types.

**Comment by hanhanW** [comment]
FYI @Max191 this might be needed.

**Comment by dcaballe** [comment]
@tyb0807 has been kindly helping here on his spare time so I want to make sure we are not putting any pressure on him. Please, feel free to decline if you don't have cycles!

**Comment by hanhanW** [comment]
@Max191 is offering some help, assign it to him for now.

**Comment by hanhanW** [comment]
https://github.com/llvm/llvm-project/pull/73871 should fix the issue. I will close the issue after I enable e2e tests in IREE.

**Comment by hanhanW** [comment]
verified that it's fixed by https://github.com/llvm/llvm-project/pull/73871
