### ISSUE TITLE
Compiler error from migrating the StableHLO input conversion to a compiler plugin.

### ISSUE THREAD

**Issue by LLITCHEV** [iree-org/iree#15631]
### What happened?

When pulling after commit commit ebb5b7d4a3c59b8dac9c5a4fe4ba78f0c736dc7f
I get the following build error.
/usr/local/google/home/lubol/iree/compiler/plugins/input/StableHLO/stablehlo-iree/Conversion/StableHLOToLinalgPointwise.cpp:261:63:   required from here
/usr/local/google/home/lubol/iree/third_party/llvm-project/mlir/include/mlir/IR/PatternMatch.h:254:16: error: ‘virtual void mlir::RewritePattern::rewrite(mlir::Operation*, mlir::PatternRewriter&) const’ was hidden [-Werror=overloaded-virtual=]
  254 |   virtual void rewrite(Operation *op, PatternRewriter &rewriter) const;
      |                ^~~~~~~
/usr/local/google/home/lubol/iree/third_party/llvm-project/mlir/include/mlir/Transforms/DialectConversion.h:544:16: note:   by ‘mlir::OpConversionPattern<mlir::stablehlo::XorOp>::rewrite’
  544 |   virtual void rewrite(SourceOp op, OpAdaptor adaptor,
      |                ^~~~~~~
cc1plus: all warnings being treated as errors
[5913/7172] Building CXX object compil...ib/Dialect/Torch/IR/TorchDialect.cpp.o
ninja: build stopped: subcommand failed.

### Steps to reproduce your issue

Clone the latest IREE repo and do a default build. The result is the error above.

**Comment by ScottTodd** [comment]
General troubleshooting tips/checklist/questions:

* Check and share your operating system (e.g. Linux/Windows/macOS) and compiler versions (e.g. `clang --version`)
* Check and share your full CMake configure command and output (looking for things like extra flags, build type Debug or RelWithDebInfo, etc.)
* Check that git submodules are initialized with `git status`, `git submodule sync`, and `git submodule update --init`
* If a build worked with the same configuration, try to narrow it down to which commit or range of commits caused the build to stop working. `git bisect` can help here (sample instructions: https://iree.dev/developers/debugging/compile-time-regressions/#running-git-bisect)

For this issue in particular, our continuous builds and other developers haven't reported issues, so I'd look for what is different about your setup. If the linked commit is truly the culprit, the logs would suggest some change in compiler flags getting applied to that code after moving it, or something like two headers are accidently using the same include guard.

**Comment by ScottTodd** [comment]
From some offline discussion, it sounds like this is a gcc build, using the basic instructions at https://iree.dev/building-from-source/getting-started/#quickstart-clone-and-build. (Full CMake configure output would confirm this, please include that in bug reports for building)

Our CI is using gcc 9: https://github.com/openxla/iree/blob/5b2cb64ab88aad57354c7b0f47b11ca9ae8dd73b/.github/workflows/ci.yml#L714-L717 I see gcc 13 on my Linux dev machine.

**Comment by ScottTodd** [comment]
I can reproduce with this gcc 13.2.0.

**Comment by ScottTodd** [comment]
Seems like an upstream issue, but I don't see related issues in https://github.com/llvm/llvm-project ?

`cmake --build ../iree-build --config RelWithDebInfo --target torch-mlir_CAPI` fails similarly. Trying to find the simplest target that fails...
