### ISSUE TITLE
Embed executable sources in vmfb files for portable Tracy captures

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#15699]
We can view executable sources for dispatch functions in Tracy thanks to https://github.com/openxla/iree/pull/9994, https://github.com/openxla/iree/pull/13333, and https://github.com/openxla/iree/pull/13500.

* The definition of "executable sources" in a multi-level compiler can have multiple values. We use whatever is snapshot into MLIR source locations, which practically equals the input .mlir locations (e.g. Python files / lines) by default and linalg sources prior to codegen when `--iree-hal-dump-executable-sources-to={path}` is set. (You could also snapshot PTX, spirv, LLVM dialect MLIR, x86 assembly, etc.)

  ![image](https://user-images.githubusercontent.com/4010439/182487590-a6b1fbae-9a04-482d-b9c8-c7da05c9c47d.png)

  ![image](https://github.com/openxla/iree/assets/4010439/35aef99d-5c43-40b9-a606-fe4dfe6fddd3)
* Source locations are stored as absolute file paths that are not portable across machines right now. This means that you can't view sources on platforms like Android without manually editing the .vmfb and copying files across.

Tracy 0.9 (https://github.com/wolfpld/tracy/releases/tag/v0.9) added this feature:
> You can now provide custom source file contents through a profiler callback. This enables profiler access to files contained in your custom data files, etc.

We can use that callback together with embedded sources to support viewing sources on Android and other non-host platforms.

* Prior discussion about this work [on Discord here](https://discord.com/channels/689900678990135345/760577505840463893/1035613526737301544).
* Work-in-progress patch here: https://github.com/ScottTodd/iree/commit/deb4956d78460f25c63c7cc449c68b78abc819d1 . Note the comments from the discussion:
  > we'll want to keep the loc and instead have an additional field for files - that way we can have multiple entry points that reference lines in the same file (N:M)
then we'd just walk src_files and register them all and let the existing src_locs reference them by file name
will be important when linking multiple source files together and such

**Comment by ScottTodd** [comment]
cc @KoolJBlack @dcaballe (sounded like there was some interest in improving Tracy workflows on Android, this could help and would be 1-3 days of work I think)

**Comment by ScottTodd** [comment]
This source snapshotting also helps connect locations with sampled assembly:

With `--iree-hal-dump-executable-sources-to={path}`:
![image](https://github.com/openxla/iree/assets/4010439/5d62b9c6-ad7e-41c2-95b4-bd9ebaaa97d3)

Without:
![image](https://github.com/openxla/iree/assets/4010439/b99bd488-b6fd-48f6-84e2-5150a9445f79)

**Comment by benvanik** [comment]
Nice! Would be cool if we could make embedded elfs work with this too - not sure tracy has enough API hooks for us to do that though.

**Comment by ScottTodd** [comment]
Yeah. With embedded (`--iree-llvmcpu-link-embedded=true`), I don't see any sampling or assembly for executable code: 
![image](https://github.com/openxla/iree/assets/4010439/9c38b885-73b5-4938-96e1-356d141a4409)

I do at least see the instrumented source though.

**Comment by ScottTodd** [comment]
To clarify (since I just confused myself about this):

* If you compile on machine A and run on machine A, the .tracy file _will_ be portable to machine B (including C/C++ and MLIR sources)
* If you compile on machine A and run on machine B, the .tracy file _will not_ be portable to machine C (without a fix for this)

The other element with this issue is decoupling the "I want to dump executable files to disk" workflow from the "I want debug information in my .vmfb so I get useful traces" workflow.

@benvanik or I might help land a fix for this, as reliable and easy profiling across different systems is high priority.

**Comment by ScottTodd** [comment]
Fixed by https://github.com/openxla/iree/pull/16757
