### ISSUE TITLE
IREE fails to build when it's source tree is not the root directory of the cmake call

### ISSUE THREAD

**Issue by dpackwood** [iree-org/iree#15761]
### What happened?

I build IREE by using cmake FetchContent to use in a larger project.
```
FetchContent_Declare(iree
        GIT_REPOSITORY ${IREE_GIT_REPOSITORY}
        GIT_TAG ${IREE_GIT_TAG}
        GIT_SHALLOW    ON)
FetchContent_MakeAvailable(iree)
```
The use case is reusing llvm-project "stuff" for other components, so targets created by irees fork of llvm project are available to the wider project.

When using such CMake, cmake build step fails instantly
```
runtime/src/iree/builtins/ukernel/arch/arm_64/ukernel_bitcode_arm_64.bc', needed by '_deps/iree-build/runtime/src/iree/builtins/ukernel/ukernel_bitcode.c', missing and no known rule to make it
```
(Note by default FetchContent creates the build dir for IREE at `${CMAKE_BUILD_DIR}/_deps/iree-build`

I *think* its because there are many CMakeLists.txt cmake calls like this:
```
iree_bitcode_library(
  NAME
    ukernel_bitcode_arm_64_entry_points
  ARCH
    wasm_64
  INTERNAL_HDRS
    "${CMAKE_BINARY_DIR}/runtime/src/iree/builtins/ukernel/internal_headers_filegroup.stamp"
    "${CMAKE_BINARY_DIR}/runtime/src/iree/schemas/cpu_data_headers_filegroup.stamp"
    "common_arm_64.h"
    "common_arm_64_entry_point.h"
    "mmt4d_arm_64_internal.h"
    "pack_arm_64_internal.h"
    "unpack_arm_64_internal.h"
  SRCS
    "mmt4d_arm_64_entry_point.c"
    "pack_arm_64_entry_point.c"
    "query_tile_sizes_arm_64_entry_point.c"
    "unpack_arm_64_entry_point.c"
)
```
where `${CMAKE_BINARY_DIR}` is not where the build system expects it to be (rather it is the root build dir of the larger project).

I am not 100% sure but I think then cmake fails to run the targets to create these files.

I think the fix might be to replace all these `${CMAKE_BINARY_DIR}` based paths to relative ones based on `${CMAKE_CURRENT_BINARY_DIR}`.

### What component(s) does this issue relate to?

Runtime

### Version information

candidate-20231201.725

**Comment by RoboTux** [comment]
I'll have a look. CMAKE_CURRENT_BINARY_DIR is not the solution unfortunately because iree_bitcode_library is called from all sorts of directory. Maybe there's a variable to hold the root of IREE tree.

**Comment by RoboTux** [comment]
I've got a patch. It's just a matter of using PROJECT_BINARY_DIR instead of CMAKE_BINARY_DIR and likewise PROJECT_SOURCE_DIR instead of CMAKE_SOURCE_DIR.

**Comment by ScottTodd** [comment]
> Maybe there's a variable to hold the root of IREE tree.

You can also try `IREE_ROOT_DIR` for this.

**Comment by qiuchuy** [comment]
I’ve just got the same error and this patch works, thank you!
