### ISSUE TITLE
[regression] Falcon7bGptqPT is 10x slower after #15766

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#15816]
I notice that "Fix accidental data-tiling tile selection" makes Falcon7bGptqPT model 10x slower. 

![image](https://github.com/openxla/iree/assets/6949191/9cbf06d3-ae3f-4fbd-8836-451f5ff4f797)

The root cause is that some matmul is not data-tiled (fp32.fp16.fp16). And a pack op is fused with the matmul op, i.e., we have matmul+generic+pack dispatch. I verified that we can fix the regression if disable pack fusion.

I think the fix is to break `matmul + generic + pack` dispatch -> `matmul + generic` dispatch + `pack` dispatch.

**Comment by benvanik** [comment]
out of curiosity, is this because codegen can't generate reasonable code for packs when fused? assuming the pack is a swizzle/permute I'd not expect it to be fundamentally so slow but could understand how it may choke current codegen

(just want to make sure we classify things as "never going to be good" vs "not currently good" when it comes to preventing fusion that should be profitable (less memory bandwidth, less serialization of the device, etc))

**Comment by dcaballe** [comment]
>  think the fix is to break matmul + generic + pack dispatch -> matmul + generic dispatch + pack dispatch.

Wondering if it would make more sense to do `matmul` + `generic + pack`. That should help amortize the cost of the pack op while still getting good performance

**Comment by hanhanW** [comment]
Codegen can generate reasonable code for pack when it is fused with reduction and elementwise ops, but not with matmul. The codegen strategy for matmul is complicated and it is not easy to make it work with pack ops.

I had an offline discussion with Benoit and I think there are two issues to fix:

1. I will partially undo Benoits's PR. Sop we can enable data-tiling for the case.
2. We need to update pack op fusion logic. I think we don't want `named_op + generic + pack` at all. It can be either (`named_op` and `generic + pack`) or (`named_op + generic` and `pack`).

I will try (1); we can revisit (2) after fixing the 10x slower regressions.

**Comment by benvanik** [comment]
that's just for non-data-tiling codegen using the current matmul strategy stuff, right?
(again, I'm trying to figure out what is TODOs/uninvested paths/etc vs what is truth - we're constantly fighting to reduce the number of dispatches and if this is just preventing fusion temporarily or in a path we don't currently care about that's fine but we don't want to disable fusion everywhere and consider this case-closed unless it really is)
