### ISSUE TITLE
User build issue: `undefined symbol: mlir::torch::registerTorchConversionPasses()`

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#15835]
Reported [here on Discord](https://discord.com/channels/689900678990135345/689900680009482386/1181890947655667763)

> When building IREE, I got an error:

```
[59/135] Linking CXX shared library lib/libIREECompiler.so
......
ld.lld: error: undefined symbol: mlir::torch::registerTorchPasses()
referenced by PluginRegistration.cpp:39 (iree/compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp:39)
>>>               ../compiler/plugins/input/Torch/torch-iree/CMakeFiles/torch-iree_registration.objects.dir/PluginRegistration.cpp.o:(mlir::iree_compiler::PluginSession<mlir::iree_compiler::(anonymous namespace)::TorchSession, mlir::iree_compiler::(anonymous namespace)::TorchOption
s, (mlir::iree_compiler::PluginActivationPolicy)1>::Registration::registerPasses()) in archive lib/libtorch-iree_registration.a

ld.lld: error: undefined symbol: mlir::torch::registerTorchConversionPasses()
>>> referenced by PluginRegistration.cpp:40 (iree/compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp:40)
>>>               ../compiler/plugins/input/Torch/torch-iree/CMakeFiles/torch-iree_registration.objects.dir/PluginRegistration.cpp.o:(mlir::iree_compiler::PluginSession<mlir::iree_compiler::(anonymous namespace)::TorchSession, mlir::iree_compiler::(anonymous namespace)::TorchOption
s, (mlir::iree_compiler::PluginActivationPolicy)1>::Registration::registerPasses()) in archive lib/libtorch-iree_registration.a

ld.lld: error: undefined symbol: mlir::torch::registerConversionPasses()
>>> referenced by PluginRegistration.cpp:41 (iree/compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp:41)
>>>               ../compiler/plugins/input/Torch/torch-iree/CMakeFiles/torch-iree_registration.objects.dir/PluginRegistration.cpp.o:(mlir::iree_compiler::PluginSession<mlir::iree_compiler::(anonymous namespace)::TorchSession, mlir::iree_compiler::(anonymous namespace)::TorchOption
s, (mlir::iree_compiler::PluginActivationPolicy)1>::Registration::registerPasses()) in archive lib/libtorch-iree_registration.a
```

Commands used:
```
git clone https://github.com/openxla/iree.git
cd iree
git submodule update --init

cmake -G Ninja -B ../iree-build/ -S . \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DIREE_ENABLE_ASSERTIONS=ON \
    -DIREE_ENABLE_SPLIT_DWARF=ON \
    -DIREE_ENABLE_THIN_ARCHIVES=ON \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DIREE_ENABLE_LLD=ON \
    -DCMAKE_C_COMPILER_LAUNCHER="ccache" \
    -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
    -DIREE_BUILD_PYTHON_BINDINGS=ON  \
    -DPython3_EXECUTABLE="$(which python3)"

cmake --build ../iree-build/
```

Tool versions:
> clang version: 14.0.0-1ubuntu1.1
OS: ubuntu 22.04.3 LTS
cmake version: 3.22.1
ccache version: 4.8.3
ninja version: 1.11.1
Ubuntu LLD 14.0.0 (compatible with GNU linkers)

**Comment by ScottTodd** [comment]
Those torch-mlir symbols are declared here: https://github.com/shark-infra/torch-mlir/blob/main/include/torch-mlir/Dialect/TorchConversion/Transforms/Passes.h and defined here: https://github.com/shark-infra/torch-mlir/blob/main/lib/Dialect/TorchConversion/Transforms/Passes.cpp.

They are used here:
https://github.com/openxla/iree/blob/611402e434cd10d2741deae2dcab9662bb4d94f0/compiler/plugins/input/Torch/torch-iree/CMakeLists.txt#L20-L23 https://github.com/openxla/iree/blob/611402e434cd10d2741deae2dcab9662bb4d94f0/compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp#L13-L16 https://github.com/openxla/iree/blob/611402e434cd10d2741deae2dcab9662bb4d94f0/compiler/plugins/input/Torch/torch-iree/PluginRegistration.cpp#L38-L41

That all seems correct...

**Comment by peymanbr** [comment]
This issue can be closed. I managed to build the reported target on an almost similar setup:
```
Clang: 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
OS: Ubuntu 22.04.1
cmake: 3.22.1
ccache: 4.5.1
ninja: 1.11.1.git.kitware.jobserver-1
Ubuntu LLD: 14.0.0
```
My guess is that the user encountered the build error because the contents of ccache were not properly invalidated. This propbably occurred in successive builds after rebasing and updating the LLVM submodules.

**Comment by ScottTodd** [comment]
Yeah, the build setup is fairly normal and well tested on CI. We've had similar issues where dependencies were missing, leaking to flaky builds based on the order that targets were built. If that is the case here, and not just some local build configuration issue, some sort of fix could help. We can close this since it isn't very actionable without consistent reproduction steps or more user reports though.
