### ISSUE TITLE
Integrating IREE with Android Studio: Seeking Assistance with File Selection

### ISSUE THREAD

**Issue by hiroto01230** [iree-org/iree#15981]
I'm trying to build IREE with C in Android Studio, but I'm encountering a character overflow error in the iree-populate code during the Git installation process.

 I've built IREE on my host machine but am unsure which files to move to Android Studio. 
I have checked the documentation and IREE samples, but it seems they only cover CMake tests on PC, and there are no provided examples for CMake working on Android Studio.
 My plan is to use PyTorch models on CPU for Android, and eventually support Vulkan, though it's not immediately necessary due to version issues. Could someone please advise me on the specific files needed for this integration?

**Comment by ScottTodd** [comment]
Were you able to resolve this? 

We had a sample app at https://github.com/not-jenni/iree-android-tflite-demo that used https://github.com/openxla/iree/tree/main/runtime/bindings/tflite/java, but that code is very stale (and was only tested a few times). 

In terms of source files needed, the 'runtime' directory (https://github.com/openxla/iree/tree/main/runtime) is typically what you would need for headers, though that directory does depend on third_party, build_tools, and perhaps a few other top level folders.

A working project or (ideally) template repo like https://github.com/iree-org/iree-template-runtime-cmake/ would be great to share in our docs if one existed. Contributions or shout-outs welcome there.
