### ISSUE TITLE
Missing some utility binaries in iree-dist tarball

### ISSUE THREAD

**Issue by hcindyl** [iree-org/iree#16026]
Most likely caused by the refactoring in https://github.com/openxla/iree/commit/3e0583f1449e2820dc990bc91d2fe1ae14157f80. Some of the utility binaries, such as `generate_embed_data` (used by baremetal flow to embed the IREE bytecode module), `llvm-link`, and `clang` (used by iree-ukernel-bitcode codegen) are missing since   https://github.com/openxla/iree/releases/tag/candidate-20231229.754
![68o5ZTTPvTVF3W2](https://github.com/openxla/iree/assets/19485875/f38dce75-8cbc-4432-a41d-a5b7f8093822)

**Comment by hcindyl** [comment]
@stellaraccident @lundong FYI

**Comment by stellaraccident** [comment]
> @stellaraccident @lundong FYI

I'm on vacation and can't help, but for now they can be added back. I was surprised we were distributing clang and llvm-link as they were strictly used for building the compiler.

If you look for how iree-tblgen is installed now, you can follow suit with these other tools (for the component and embed set to use). We may eventually want a different tarball for some of this but can have it be very large for now.

**Comment by stellaraccident** [comment]
(also, sorry. Didn't mean to break anyone but also these tarballs and install targets have been an incomplete dumping ground for a while and I figured it was easy enough to add things back in if needed now that it is organized)

**Comment by hcindyl** [comment]
Thanks for the pointers! I will try to add them back. I am surprised no crosscompile target caught the breakage -- the baremetal targets should complain the missing of `generate_embed_data`. 

There is no off-tree ukernel bitcode targets, so the latter two are harder to catch.

**Comment by stellaraccident** [comment]
I'd like to get these tarballs better supported. Doesn't have to be now, but for the python distributions, I added package test scripts that are installed with the package and can verify these kinds of things (and can be a place where we can leave some comments/context). We may want to do something similar for these. On the python side, we install and run the package tests in both presubmit and before marking a release as succeeded.

**Comment by hcindyl** [comment]
> I'd like to get these tarballs better supported. Doesn't have to be now, but for the python distributions, I added package test scripts that are installed with the package and can verify these kinds of things (and can be a place where we can leave some comments/context). We may want to do something similar for these. On the python side, we install and run the package tests in both presubmit and before marking a release as succeeded.

Good point. I realized yesterday that iree-dist tarball was not tested in CI. What we can do is to add a step in CI to build the iree-dist tarball and let all the cross-compile steps depending on it. Such a tarball should also be much smaller than the tarball that's currently used from `build-all`

**Comment by stellaraccident** [comment]
> > I'd like to get these tarballs better supported. Doesn't have to be now, but for the python distributions, I added package test scripts that are installed with the package and can verify these kinds of things (and can be a place where we can leave some comments/context). We may want to do something similar for these. On the python side, we install and run the package tests in both presubmit and before marking a release as succeeded.
> 
> Good point. I realized yesterday that iree-dist tarball was not tested in CI. What we can do is to add a step in CI to build the iree-dist tarball and let all the cross-compile steps depending on it. Such a tarball should also be much smaller than the tarball that's currently used from `build-all`

We can pick it up when I'm back. There are some more things I want to do to these to better support the C development flows.

We can also just have a normal ctest for this: it just needs to install-stripped the current build tree to a temp location and then run some checks.
