### ISSUE TITLE
[CPU][DT+UK] 20 mins to compile FP16 BERT on aarch64 with UK enabled

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#16042]
### What happened?

It takes 20 mins to compile FP16 BERT with input sequence length of 32 for Android with DT+UK. When compiling with only DT, it takes 5 seconds.

When compiling with the DT+UK but with an input length of 8, compilation takes 12 seconds.

### Steps to reproduce your issue

```
wget https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.23_1702848353/BERT_BASE_FP16_JAX_I32_SEQLEN32/stablehlo.mlirbc \
    -O /tmp/stablehlo.mlirbc

iree-compile /tmp/stablehlo.mlirbc \
    --iree-input-type=stablehlo \
    --iree-hal-target-backends=llvm-cpu \
    --iree-llvmcpu-link-embedded=true \
    --iree-input-demote-f64-to-f32=false \
    --iree-input-demote-i64-to-i32=false \
    --iree-llvmcpu-debug-symbols=false \
    --iree-vm-emit-polyglot-zip=false \
    --iree-opt-data-tiling \
    --iree-llvmcpu-enable-ukernels=all \
    --iree-llvmcpu-target-triple=aarch64-none-linux-android34 \
    --iree-llvmcpu-target-cpu-features=+v9a,+fullfp16,fp-armv8,+neon,+aes,+sha2,+crc,+lse,+rdm,+complxnum,+rcpc,+sha3,+sm4,+dotprod,+fp16fml,+dit,+flagm,+ssbs,+sb,+sve2-aes,+sve2-bitperm,+sve2-sha3,+sve2-sm4,+altnzcv,+fptoint,+bf16,+i8mm,+bti,+mte,+pauth,+perfmon,+predres,+spe,+ras \
    -o /tmp/module.vmfb
```
If we remove the `--iree-llvmcpu-target-cpu-features` flag, we see the same behavior.

### What component(s) does this issue relate to?

Compiler

### Version information

Release 20240103.759

**Comment by hanhanW** [comment]
The issue is that we don't have f16.f32.f16 mmt4d ukernels, and it falls back to codegen solution. However, we dropped lowering_config during decomposition. It generates huge vector shape, and it leads to bad codegen. The proper fix is to carry over the lowering_config in decomposition. We need to drop the batch tile size and set the new lowering_config on corresponding ops.
