### ISSUE TITLE
Frontend using linalg.transpose named op introduces huge regressions

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#16063]
We observed the [regressions](https://gist.github.com/iree-github-actions-bot/19cbd1474106905fa4a0695958363936) (for both number of dispatches and latency) when doing integrate in https://github.com/openxla/iree/pull/16055. The commit is reverted locally in IREE. We should fix the issue and drop the revert.

Leaving what I've found below. There could be other issues.

1. It somehow provides opportunities to hoist more const expr in IREE. This should not introduce regression, but it is weird to me.
2. It makes `RaiseSpecialOps` convert `transpose + matmul` to `matmul_transpose_b`. The backends are mostly focusing on matmul without transpose variants, so there are large regressions.
3. If we disable the conversion in (2), it generates below patterns in MobileBertFP32. There are opportunities to fuse elementwise (`%1196`) with following 4 transpose ops, but it looks not trivial. IR dump of this option can be found at [here](https://gist.githubusercontent.com/hanhanW/3a2659b02a4387e2691f22d5e4792c6e/raw/a319de8632825f1e9f62f0968b0d825b26778f14/log10).

```
    %1189 = flow.tensor.update %1182, %37[%c0, %c0] : tensor<384x384xf32> -> %37 as tensor<1536x384xf32>
    %1190 = flow.tensor.update %1184, %1189[%c384, %c0] : tensor<384x384xf32> -> %1189 as tensor<1536x384xf32>
    %1191 = flow.tensor.update %1186, %1190[%c768, %c0] : tensor<384x384xf32> -> %1190 as tensor<1536x384xf32>
    %1192 = flow.tensor.update %1188, %1191[%c1152, %c0] : tensor<384x384xf32> -> %1191 as tensor<1536x384xf32>
    %1193 = flow.tensor.reshape %1192 : tensor<1536x384xf32> -> tensor<4x384x384xf32>
    %1194 = flow.dispatch @main_dispatch_19::@main_dispatch_19_generic_4x384x384_f32(%1193, %5) : (tensor<4x384x384xf32>, tensor<384x384xf32>) -> tensor<4x384x384xf32>
    %1195 = flow.dispatch @main_dispatch_20::@main_dispatch_20_softmax_4x384x384xf32(%1194) : (tensor<4x384x384xf32>) -> tensor<4x384x384xf32>
    %1196 = flow.dispatch @main_dispatch_9::@main_dispatch_9_generic_384x4x32_f32(%1174, %cst_72) : (tensor<384x4x32xf32>, tensor<4x32xf32>) -> tensor<4x384x32xf32>
    %1197 = flow.dispatch @main_dispatch_22::@main_dispatch_22_transpose_32x384_f32(%1196) : (tensor<4x384x32xf32>) -> tensor<384x32xf32>
    %1198 = flow.dispatch @main_dispatch_23::@main_dispatch_23_matmul_384x32x384_f32(%1195, %1197) : (tensor<4x384x384xf32>, tensor<384x32xf32>) -> tensor<384x32xf32>
    %1199 = flow.dispatch @main_dispatch_24::@main_dispatch_24_transpose_32x384_f32(%1196) : (tensor<4x384x32xf32>) -> tensor<384x32xf32>
    %1200 = flow.dispatch @main_dispatch_25::@main_dispatch_25_matmul_384x32x384_f32(%1195, %1199) : (tensor<4x384x384xf32>, tensor<384x32xf32>) -> tensor<384x32xf32>
    %1201 = flow.dispatch @main_dispatch_26::@main_dispatch_26_transpose_32x384_f32(%1196) : (tensor<4x384x32xf32>) -> tensor<384x32xf32>
    %1202 = flow.dispatch @main_dispatch_27::@main_dispatch_27_matmul_384x32x384_f32(%1195, %1201) : (tensor<4x384x384xf32>, tensor<384x32xf32>) -> tensor<384x32xf32>
    %1203 = flow.dispatch @main_dispatch_28::@main_dispatch_28_transpose_32x384_f32(%1196) : (tensor<4x384x32xf32>) -> tensor<384x32xf32>
    %1204 = flow.dispatch @main_dispatch_29::@main_dispatch_29_matmul_384x32x384_f32(%1195, %1203) : (tensor<4x384x384xf32>, tensor<384x32xf32>) -> tensor<384x32xf32>
```

**Comment by MaheshRavishankar** [comment]
Thanks for the bug... I probably wont have time to look more till a day or so. Let me know if thats OK.

**Comment by hanhanW** [comment]
> Thanks for the bug... I probably wont have time to look more till a day or so. Let me know if thats OK.

I think it is okay. I just need to put this issue to LLVM integrate tracking issue, doing it now.
