### ISSUE TITLE
 RISC-V failed to build int8 MobileNetV2 with LLVM Integrate #16055

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#16061]
To repro:

```
iree-compile --output-format=vm-bytecode --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-target-triple=riscv32-pc-linux-gnu --iree-llvmcpu-target-cpu=generic-rv32 --iree-llvmcpu-target-abi=ilp32 --iree-llvmcpu-target-cpu-features=+m,+a,+f,+zvl512b,+zve32f --riscv-v-fixed-length-vector-lmul-max=8 --iree-vm-emit-polyglot-zip=true ~/mobilenet_v2_int8.mlir
```

It is broken by https://github.com/llvm/llvm-project/pull/76793

**Comment by hanhanW** [comment]
Error dump: https://gist.githubusercontent.com/hanhanW/c573ab5cfc5a066db07f580089258733/raw/5e07669fa516f3d9c8393f962d59629df0c6ebfb/out

**Comment by dcaballe** [comment]
Hey @rednoah91, could anybody from your side help with this?

```
iree-compile: /home/hanchung/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/LoopUnrollPass.cpp:659: std::optional<EstimatedUnrollCost> analyzeLoopUnrollCost(const llvm::Loop *, unsigned int, llvm::DominatorTree &, llvm::ScalarEvolution &, const SmallPtrSetImpl<const llvm::Value *> &, const llvm::TargetTransformInfo &, unsigned int, unsigned int): Assertion `UnrolledCost.isValid() && RolledDynamicCost.isValid() && "All instructions must have a valid cost, whether the " "loop is rolled or unrolled."' failed.
```

**Comment by hanhanW** [comment]
I talked to @rednoah91 today, and he can help take a look at this. @rednoah91 please let us know if someone is taking a look at this.

**Comment by hanhanW** [comment]
posting how to get mlir file here, I think you can download the file from one of CI jobs, e.g., `gcloud storage cp gs://iree-github-actions-presubmit-artifacts/7422301781/1/e2e-test-artifacts/iree_MobileNetV2_int8_tflite_.mlir ~/`

You can add `--iree-hal-dump-executable-sources-to=/tmp/dump` to dump dispatches; it might help narrowing it down to specific dispatch. Then you can use `iree-compile` with `--compile-mode=hal-executable` flag to generate the VMFB. Hopefully it could help narrow down the issue.

**Comment by rednoah91** [comment]
I've tried the ToT build (6ab1ed) but can not reproduce the error.

**Comment by hanhanW** [comment]
It seems to be fixed by some upstream changes. We can re-enable the model, I will prepare the PR
