### ISSUE TITLE
Need to bump tf-nightly to drop the revert in #16114 integrate

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#16173]
https://github.com/llvm/llvm-project/commit/af78e5daf0791135485dbd7972ffedb927727a6b changes the attribute type. We revert the commit locally to unblock the integrate PR. We will need to bump tf-nightly and torch-mlir to drop the revert.

**Comment by jpienaar** [comment]
https://github.com/openxla/iree/blob/main/integrations/tensorflow/README.md#updating-tensorflow-importers-in-ci for updating. Note: we may need to split this one if torch-mlir updates are needed in addition.

**Comment by hanhanW** [comment]
I think torch-mlir updates are need. That's why I had the change in very beginning. The fixes I had are https://github.com/openxla/iree/pull/16114/commits/3624f28853e989d18049196b0229ef09dad2470a and https://github.com/openxla/iree/pull/16114/commits/56ddaeb927b3a2d6acc14804dee3ba6f391eca1b

**Comment by jpienaar** [comment]
But torch-mlir is in a upstream repo, so process is first updating torch-mlir and then IREE?

**Comment by hanhanW** [comment]
> But torch-mlir is in a upstream repo, so process is first updating torch-mlir and then IREE?

Do you mean that we should bump torch-mlir to related llvm version, then IREE? If so, I already bumped the LLVM for torch-mlir repo; we just need to update IREE to pin on the commit.

**Comment by hanhanW** [comment]
It is done in https://github.com/llvm/torch-mlir/pull/2753

**Comment by hanhanW** [comment]
I could be wrong. I think what we need is following the doc to bump tf-nightly and cherry-pick the two commits.

**Comment by jpienaar** [comment]
Ah, sorry you meant bump the torch-mlir version in IREE, I had read update it along with IREE in one PR. SG.

**Comment by jpienaar** [comment]
For some reason I get in the image building

```
Could not find a version that satisfies the requirement tf-nightly==2.16.0.dev20240119 (from versions: 2.16.0.dev20231025, 2.16.0.dev20231026, 2.16.0.dev20231031, 2.16.0.dev20231101, 2.16.0.dev20231102, 2.16.0.dev20231103, 2.16.0.dev20231107, 2.16.0.dev20231108, 2.16.0.dev20231109, 2.16.0.dev20231110, 2.16.0.dev20231111, 2.16.0.dev20231112, 2.16.0.dev20231113, 2.16.0.dev20231114, 2.16.0.dev20231115, 2.16.0.dev20231116, 2.16.0.dev20231117, 2.16.0.dev20231118, 2.16.0.dev20231119, 2.16.0.dev20231120, 2.16.0.dev20231121, 2.16.0.dev20231122, 2.16.0.dev20231123, 2.16.0.dev20231124, 2.16.0.dev20231125, 2.16.0.dev20231126, 2.16.0.dev20231127, 2.16.0.dev20231128, 2.16.0.dev20231129, 2.16.0.dev20231130, 2.16.0.dev20231201, 2.16.0.dev20231202, 2.16.0.dev20231203, 2.16.0.dev20231204, 2.16.0.dev20231205, 2.16.0.dev20231207, 2.16.0.dev20231208, 2.16.0.dev20231209, 2.16.0.dev20231210, 2.16.0.dev20231211, 2.16.0.dev20231212, 2.16.0.dev20231213, 2.16.0.dev20231215, 2.16.0.dev20231216, 2.16.0.dev20231217, 2.16.0.dev20231218, 2.16.0.dev20231219, 2.16.0.dev20231220, 2.16.0.dev20231221, 2.16.0.dev20231222, 2.16.0.dev20231223, 2.16.0.dev20231224, 2.16.0.dev20231225, 2.16.0.dev20231226, 2.16.0.dev20231227, 2.16.0.dev20231228, 2.16.0.dev20231229, 2.16.0.dev20231230, 2.16.0.dev20231231, 2.16.0.dev20240101, 2.16.0.dev20240102, 2.16.0.dev20240103, 2.16.0.dev20240104, 2.16.0.dev20240105, 2.16.0.dev20240106, 2.16.0.dev20240107, 2.16.0.dev20240108, 2.16.0.dev20240109, 2.16.0.dev20240110)
```

with the 11th where the change was integrated. But installing that package locally worked, so some requirement differs between my system and the docker image.

**Comment by jpienaar** [comment]
Asked and apparently the latest couple of night lies haven't been uploaded due to size issues and some other refactoring. Enquiring about timeline for next full release.

**Comment by jpienaar** [comment]
It is due to a failure to upload a python 3.9 wheel. I'll wait a day or so to see if new nightly works.
