### ISSUE TITLE
`iree-mlir-lsp-server` does not work on `*.td` files

### ISSUE THREAD

**Issue by gglin001** [iree-org/iree#16209]
### What happened?

`iree-mlir-lsp-server` does not support symbol jumps in `*.td` files, and no log outputs at VSCode output panel

### Steps to reproduce your issue

1. build IREE, including cmake target `iree-mlir-lsp-server`
2. install MLIR plugin in VSCode, and set `"mlir.server_path": "ABS_PATH_TO/build/tools/iree-mlir-lsp-server",`
3. select one TD file, eg: `compiler/src/iree/compiler/Dialect/VM/IR/VMOps.td`
4. switch VSCode OUTPUT panel to `MLIR`
5. you cannot jump to a symbol in this TD file or include target, no(useful) log in the OUTPUT panel

### What component(s) does this issue relate to?

MLIR

### Version information

commit id
4267069dd70f356e094c5fcd6ec500deaf8c22ab

**Comment by ScottTodd** [comment]
Does the upstream/generic `mlir-lsp-server` do what you want?

https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/API/Internal/IREEMLIRLSPServerToolEntryPoint.cpp and https://github.com/llvm/llvm-project/blob/main/mlir/tools/mlir-lsp-server/mlir-lsp-server.cpp only differ in which dialects they register.

**Comment by gglin001** [comment]
> Does the upstream/generic mlir-lsp-server do what you want?

for the llvm-project and torch-mlir project, `*-mlir-lsp-server` works, see below imgs

<img width="744" alt="Screenshot 2024-01-26 at 09 03 10" src="https://github.com/openxla/iree/assets/13805221/bf3bf093-5cc1-4180-b909-0a5ab35d4783">

<img width="808" alt="Screenshot 2024-01-26 at 09 03 36" src="https://github.com/openxla/iree/assets/13805221/018d224f-b16a-47a9-8a7f-e2042697d4b3">

<img width="674" alt="Screenshot 2024-01-26 at 09 03 56" src="https://github.com/openxla/iree/assets/13805221/4f1ec7d3-035c-493d-95f0-29a13f28346f">


> only differ in which dialects they register.

yes, that's odd

**Comment by gglin001** [comment]
this is a config issue, `mlir.tablegen_compilation_databases` need include `tablegen_compile_commands.yml` from llvm-project
