### ISSUE TITLE
IREE compilation fails on some tflite models since bumping tf-nightly

### ISSUE THREAD

**Issue by lundong** [iree-org/iree#16251]
### What happened?

Since tf-nightly bumped to a recent version (https://github.com/openxla/iree/pull/16208), some tflite models have failed to be compiled via iree-compile. The error message is "failed to legalize operation 'tosa.variable.read'". 

It worked fine before the tf-nightly bump. Also, this issue only occurs to some models.

A sample failed model can be downloaded from:
https://github.com/google/lyra/blob/main/lyra/model_coeffs/soundstream_encoder.tflite

### Steps to reproduce your issue

1. Download the models from
https://github.com/google/lyra/blob/main/lyra/model_coeffs/soundstream_encoder.tflite

2. Build IREE

3. Import TFLite models
path/to/iree-import-tflite path/to/soundstream_encoder.tflite -o=/tmp/soundstream_encoder.mlir

4. Use iree-compile to compile TOSA MLIRs
path/to/iree-compile -iree-input-type=tosa -iree-hal-target-backends=llvm-cpu /tmp/soundstream_encoder.mlir

5. See errors
<unknown>:0: error: loc("streamable_model_46/encoder_0/resnet_0adepthwise_conv/concat/ReadVariableOp"): failed to legalize operation 'tosa.variable.read'
<unknown>:0: note: loc("streamable_model_46/encoder_0/resnet_0adepthwise_conv/concat/ReadVariableOp"): see current operation: %91 = "tosa.variable.read"() <{name = "encoder_0/resnet_0adepthwise_conv/states"}> : () -> tensor<1x2x1x64xf32>

### What component(s) does this issue relate to?

MLIR

### Version information

iree candidate-20240129.785

### Additional context

As the issue appears to be related to tf-nightly version, it's likely to be relevant to TOSA importer.
@jpienaar @NatashaKnk

**Comment by NatashaKnk** [comment]
From my understanding it's related to https://github.com/llvm/llvm-project/pull/66843 but I'm not entirely sure yet. Looking into it.

**Comment by NatashaKnk** [comment]
Should be fixed now, verified on the provided model. Let me know if there are any issues!
