### ISSUE TITLE
build error - "target requires changing an RPATH from the build tree"

### ISSUE THREAD

**Issue by alan-chen-dongsheng** [iree-org/iree#16289]
### What happened?

When I try to using vscode container to build iree by guide 
there is an error like: 
```
CMake Error at build_tools/cmake/iree_cc_binary.cmake:80 (add_executable):
  The install of the iree_base_internal_flags_demo target requires changing
  an RPATH from the build tree, but this is not supported with the Ninja
  generator unless on an ELF-based or XCOFF-based platform.  The
  CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set to avoid this relinking
  step.
Call Stack (most recent call first):
  runtime/src/iree/base/internal/CMakeLists.txt:166 (iree_cc_binary)

```

### Steps to reproduce your issue

1. fllow the guide https://github.com/openxla/iree/tree/main/.devcontainer
2. build with cmd:```sudo cmake -G Ninja -B ../iree-build/ -S /workspaces/iree \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DIREE_ENABLE_SPLIT_DWARF=ON \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DIREE_ENABLE_ASSERTIONS=ON \
    -DIREE_ENABLE_LLD=ON`
3. There will report an error:
```

CMake Error at build_tools/cmake/iree_cc_binary.cmake:80 (add_executable):
  The install of the iree_base_internal_synchronization_benchmark target
  requires changing an RPATH from the build tree, but this is not supported
  with the Ninja generator unless on an ELF-based or XCOFF-based platform.
  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set to avoid this
  relinking step.
Call Stack (most recent call first):
  build_tools/cmake/iree_cc_binary_benchmark.cmake:56 (iree_cc_binary)
  runtime/src/iree/base/internal/CMakeLists.txt:313 (iree_cc_binary_benchmark)
```

### What component(s) does this issue relate to?

MLIR

### Version information

Docker environment configured in the official warehouse

**Comment by alan-chen-dongsheng** [comment]
I switch to `makefile` try again.
```
sudo cmake -G Ninja -B ../iree-build/ -S /workspaces/iree \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DIREE_ENABLE_SPLIT_DWARF=ON \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DIREE_ENABLE_ASSERTIONS=ON \
    -DIREE_ENABLE_LLD=ON
```

I will feedback tommorow, good night 
<img width="945" alt="image" src="https://github.com/openxla/iree/assets/34329738/1cdf4ab1-557c-4c92-9315-d2b541625ca1">

**Comment by alan-chen-dongsheng** [comment]
failed with `Unix MakeFiles` too when build it. I'm not sure what problem maybe.
```
[ 11%] Building CXX object llvm-project/lib/TableGen/CMakeFiles/LLVMTableGen.dir/SetTheory.cpp.o
[ 11%] Building CXX object llvm-project/lib/TableGen/CMakeFiles/LLVMTableGen.dir/StringMatcher.cpp.o
[ 11%] Building CXX object llvm-project/lib/TableGen/CMakeFiles/LLVMTableGen.dir/TableGenBackend.cpp.o
[ 11%] Building CXX object llvm-project/lib/TableGen/CMakeFiles/LLVMTableGen.dir/TableGenBackendSkeleton.cpp.o
[ 11%] Building CXX object llvm-project/lib/TableGen/CMakeFiles/LLVMTableGen.dir/TGLexer.cpp.o
[ 11%] Building CXX object llvm-project/lib/TableGen/CMakeFiles/LLVMTableGen.dir/TGParser.cpp.o
[ 11%] Linking CXX static library ../libLLVMTableGen.a
[ 11%] Built target LLVMTableGen
[ 11%] Building CXX object llvm-project/tools/mlir/lib/Tools/mlir-tblgen/CMakeFiles/MLIRTblgenLib.dir/MlirTblgenMain.cpp.o
[ 11%] Linking CXX static library ../../../../../lib/libMLIRTblgenLib.a
[ 11%] Built target MLIRTblgenLib
[ 11%] Building CXX object tools/CMakeFiles/iree-tblgen.dir/iree-tblgen.cpp.o
[ 11%] Building CXX object tools/CMakeFiles/iree-tblgen.dir/__/compiler/src/iree/compiler/Dialect/VM/Tools/VMOpEncoderGen.cpp.o
[ 11%] Building CXX object tools/CMakeFiles/iree-tblgen.dir/__/compiler/src/iree/compiler/Dialect/VM/Tools/VMOpTableGen.cpp.o
[ 11%] Linking CXX executable iree-tblgen
[ 11%] Built target iree-tblgen
[ 11%] Generating iree_cuda/libdevice_embedded.h, iree_cuda/libdevice_embedded.c
Failed to open 'iree_cuda/libdevice_embedded.h' for write.
gmake[2]: *** [build_tools/third_party/cuda/CMakeFiles/iree_cuda_libdevice_embedded.objects.dir/build.make:75: build_tools/third_party/cuda/iree_cuda/libdevice_embedded.h] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:29905: build_tools/third_party/cuda/CMakeFiles/iree_cuda_libdevice_embedded.objects.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
```

**Comment by alan-chen-dongsheng** [comment]
- commit info:
```
commit 04d5849bcc6f8ca54a77c4e147ba0370bdae800f (HEAD -> main, tag: candidate-20240120.776)

```

**Comment by ScottTodd** [comment]
I'm suspicious of the `sudo cmake` in your initial configure command. That might be writing files under the root user account when you then later try to read/write/edit those files from a different user. Can you try a clean reconfigure without sudo?

**Comment by alan-chen-dongsheng** [comment]
Thank you for your reply. I used sudo because when I was configuring cmake, it prompted me that I had insufficient permissions to write to the file.
I deleted all the files and cloned the code again without using sudo, but I encountered the same problem.

**Comment by hamidelmaazouz** [comment]
> * commit info:
> 
> 
> ```
> commit 04d5849bcc6f8ca54a77c4e147ba0370bdae800f (HEAD -> main, tag: candidate-20240120.776)
> ```

Has this issue been solved ?

I am experiencing the same error on `release/19.x` oO

**Comment by hamidelmaazouz** [comment]
@sexjun could you share what was the resolution for this issue ?

**Comment by alan-chen-dongsheng** [comment]
Hi， @hamidelmaazouz  maybe you can try this script to build iree.
https://github.com/iree-org/iree/blob/main/build_tools/cmake/build_and_test_byo_llvm.sh

And I suggest
Pay attention to the construction of the CI, select the appropriate construction script, and extract the construction instruction from the script instead of obtained from the official website document.
https://github.com/iree-org/iree/blob/main/.github/workflows

**Comment by hamidelmaazouz** [comment]
Update:

Issue in my use case rose as I was trying to build LLVM 19 with an old Clang 14, I switched to a different more recent version (20git) and the issue went away. Not sure what happened there exactly
