### ISSUE TITLE
Option to disable -fPIC in bare metal targets

### ISSUE THREAD

**Issue by gmmyung** [iree-org/iree#16310]
### Request description

https://github.com/openxla/iree/blob/b2688322861cbf071955b1fc7682b85f1f9383b9/CMakeLists.txt#L581

The library has to be compiled without the `-fPIC` flag in my build configuration, but I have no way to disable this behavior.
Is this intentional? I would really appreciate it if there was an option to turn it off.

### What component(s) does this issue relate to?

Runtime

**Comment by stellaraccident** [comment]
We can definitely make that configurable. If you need it quickly, feel free to send a patch that introduces an option and sets the value to that.

**Comment by gmmyung** [comment]
I've submitted a pull request. Would you mind taking a look at it?
