### ISSUE TITLE
Configure number of threads

### ISSUE THREAD

**Issue by Theoo1997** [iree-org/iree#16325]
### Request description

Hi,
I would like to know if I could configure the number of threads. I am using a the simple embeddings project (AOT). The pass "mlir-disable-threading" disables multithreading?  Also the "iree-codegen-llvm-number-of-threads" can onfigure the number of threads?

**Comment by ScottTodd** [comment]
> The pass "mlir-disable-threading" disables multithreading?

That disables multithreading in the compiler, which is useful when debugging the compiler (e.g. so you can have debug logging that doesn't get intermixed across threads).

> Also the "iree-codegen-llvm-number-of-threads" can onfigure the number of threads?

FYI, that flag was renamed recently in https://github.com/openxla/iree/commit/c3518b210fd99ba914cd994ed83c42ca496e40c4 to `iree-llvmcpu-number-of-threads`. I'm not sure how that is supposed to work... maybe @MaheshRavishankar or @hanhanW could comment.

The usual way to control threads at runtime on CPU with flags is `--task_topology_group_count`, which is documented here: https://github.com/openxla/iree/blob/main/runtime/src/iree/task/api.c. In C code, you can also explicitly initialize a CPU device ("local-task") in whatever configuration you want.

**Comment by dcaballe** [comment]
> Also the "iree-codegen-llvm-number-of-threads" can onfigure the number of threads?

That flag is only providing some information to the distribution heuristics at compile time. It may impact the work each thread gets at runtime but it has been used mostly for experimentation and the outcome may not be the want expected as there are different factors involved in the computation of the workload for each thread.

**Comment by hanhanW** [comment]
What Diego said! If you are new to IREE, I'd suggest to only use `--task_topology_group_count` flag. The `--iree-llvmcpu-number-of-threads` flag is mostly for experiementations.

**Comment by Theoo1997** [comment]
Thanks a lot for you immediate response!! 

I am using the the static_library [sample](https://github.com/openxla/iree/tree/main/samples/static_library) and change it accordingly to run a Mobilenet model on host.  I tried the "task_topology_group_count". Just add the _IREE_FLAG(
    int32_t, task_topology_group_count, 0,..._ after the  #include. I sow that the execution time wasn't changed. As far I understand this example runs on a single thread (because of the [create_device_with_static_loader](https://github.com/openxla/iree/blob/d24fcc2e1a551d1855139069efd13a1e9c4aa265/samples/static_library/static_library_demo.c#L28)). To go from single threaded to multithreaded I need to do something like the Mnist [example](https://github.com/openxla/iree/blob/d24fcc2e1a551d1855139069efd13a1e9c4aa265/experimental/web/sample_static/device_multithreaded.c#L14)?

**Comment by ScottTodd** [comment]
Ah, the static library sample is an example of what I mentioned earlier

> In C code, you can also explicitly initialize a CPU device ("local-task") in whatever configuration you want.

The device creation code is here: https://github.com/openxla/iree/blob/6aa3a8b5ed69fe10186bb86628b8afca24cd5913/samples/static_library/static_library_demo.c#L52-L57

Yes, the mnist example code you linked has setup for a multithreaded device.

The `task_topology_group_count` command-line flag should work if you use `iree_task_topology_initialize_from_flags()` instead of 
```c
  iree_task_topology_initialize_from_group_count(
      /*group_count=*/4, &topology);
```
(or just use `iree_task_executors_create_from_flags()`, which also creates the executors)

Flags are flexible, but if you know the topology / desired thread-count on your system (either fully ahead of time or programmatically), then you can use your own logic explicitly.

**Comment by Theoo1997** [comment]
Thanks a lot you were very helpful. I am closing the issue.
