### ISSUE TITLE
Bug in consteval when defining global parameters

### ISSUE THREAD

**Issue by Eliasj42** [iree-org/iree#16338]
### What happened?

I'm getting the error
```
error: internal error: unsupported consteval jit function input (#stream.parameter.named<"model"::"params.model.decoder.embed_positions.weight"> : tensor<2050x1024xf32>)
  util.global private @_params.model.decoder.embed_positions.weight {noinline} = #stream.parameter.named<"model"::"params.model.decoder.embed_positions.weight"> : tensor<2050x1024xf32>
  ```
  when trying to compile opt-350m.  The file in question has a large number of global params defined in the same way to this one, but this is the only one that has this issue.
  
  https://gist.github.com/Eliasj42/a2ecadff14d99f330f7ff3af151a6362#file-facebook_opt_350-mlir-L22

### Steps to reproduce your issue

run `../iree-build/tools/iree-compile  --iree-hal-target-backends=vulkan --iree-vulkan-target-triple=rdna3-7900-linux facebook_opt_350m.mlir -o facebook_opt_350m.vmfb`  you can use the gist I linked earlier or download it here https://storage.googleapis.com/shark_tank/elias/facebook_opt_350m.mlir

### What component(s) does this issue relate to?

MLIR, Compiler

### Version information

I used the top of master iree build

**Comment by qedawkins** [comment]
Fixed by #16269
