### ISSUE TITLE
[CUDA Driver] Might get messy information for mutiple GPUs

### ISSUE THREAD

**Issue by Peter9606** [iree-org/iree#16343]
https://github.com/openxla/iree/blob/8c4c3e03ff4e7797eaf00e2682e63971096fabfd/runtime/src/iree/hal/drivers/cuda/cuda_driver.c#L181-L187

I encountered an issuse when there are mutiple GPUs of our own here, seems following fix could solve the problem in my case.
I'm not quite sure if it's same for NV for I have only one NV GPU.

```
*(buffer_ptr++) = '\0';
out_buffer_ptr = buffer_ptr; 
```

**Comment by ScottTodd** [comment]
> I encountered an issuse when there are mutiple GPUs of our own here

What issue in particular? A crash or error? What do you mean by "messy information"?

**Comment by benvanik** [comment]
I'm guessing you're trying to printf an iree_string_view_t from iree_hal_device_info_t - they are not NUL terminated and you need to use a format specifier with a length `printf("%.*s", (int)view.size, view.data);`
