### ISSUE TITLE
Integrate ZLUDA for AMD CUDA

### ISSUE THREAD

**Issue by GermanAizek** [iree-org/iree#16386]
### Request description

**Describe the feature**
@benvanik,
https://github.com/vosen/ZLUDA
it can give feature run CUDA program on amd video cards if cuda code is optimized, and speed up work on amd.

**Comment by stellaraccident** [comment]
IREE is unlikely to benefit from such an integration as neither the cuda kernels that iree produces with the cuda backend nor those produced by the rocm backend are generic kernels -- they use chip specific features as is typical of ml kernels. AMD gpus can already be targeted in an optimized way with hip/rocm or vulkan, and I don't think adding a third, abandoned mechanism (quoting the author) to the list will help.
