### ISSUE TITLE
Optimize `asan` CI job

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#16443]
This job is performing duplicate work and is one of the presubmit CI's largest bottlenecks.

Timing information from https://github.com/openxla/iree/pull/16441:

https://github.com/openxla/iree/actions/runs/7935113755/job/21667550415?pr=16441

Step | `IREE_BYTECODE_MODULE_ENABLE_ASAN` | Time taken
-- | -- | --
Configure | OFF | 50s
Build | OFF | 6m
Build test deps | OFF | 2m30s
Main ctest | OFF | 30s
llvm-external-projects tests | OFF | 20s
Configure | ON | 20s
Build | ON | 1m40s
Build test deps | ON | 2m40s
Build microbenchmark suites | ON | 20s
Main ctest | ON | 30s
llvm-external-projects tests | ON | 30s

[Discord discussion here](https://discord.com/channels/689900678990135345/689957613152239638/1208133315643703346) . Ideas from @benvanik :

> same exact compiler should be used to build the things, and same asan runtime should be used to run them, only difference is whether we pass a flag to iree-compile when building the test deps
only should have to rebuild test deps, nothing else
(and ideally, it shouldn't be a cmake flag that impacts each rule, but each test dep should have two artifacts and we should build one set or the other or both, then we configure once, build iree-test-deps iree-test-deps-with-asan)
so this whole run should be long-poled on building the compiler with asan on, but otherwise should be cheap
roughly 1-3mins longer than a normal build and test
(whatever the time to build test deps and run the tests is, but not the compiler)
we could also split the asan compiler/runtime into its own packages and build them concurrently with the other compiler, such that this just installs the asan compiler/runtime, builds test deps, and runs them
>
> whether we pass --iree-llvmcpu-sanitize=address or not when building a test dep shouldn't be a giant global flag, just one variant of compiler flags for a test dep we should be able to build with (like building for cpu/vulkan/etc)
it's just cpu, cpu w/ sanitizer, vulkan, metal, etc
(we're going to need such things as we go deeper too - vulkan/spirv version variants, etc)
we have to move away from having big "IF VULKAN ENABLED THEN BUILD ONE VULKAN TEST CONFIG"
and not having to reconfigure for each variant :P

**Comment by benvanik** [comment]
love the breakdown!
the only test deps that need to be rebuilt are the LLVM CPU ones - do we only run the LLVM CPU ones here or vmvx/vulkan/etc too? (if so, that'll cut things down even more)

**Comment by ScottTodd** [comment]
> love the breakdown! the only test deps that need to be rebuilt are the LLVM CPU ones - do we only run the LLVM CPU ones here or vmvx/vulkan/etc too? (if so, that'll cut things down even more)

`IREE_BUILD_ALL_CHECK_TEST_MODULES` is on (the default), so all the other ones are built too. It is useful to build them once (not twice), to ensure that those compilation pipelines are ASan-clean. Splitting the test definitions out and removing the top level `IREE_BYTECODE_MODULE_ENABLE_ASAN` option would let us keep that coverage without duplicating builds.

**Comment by benvanik** [comment]
agreed - we've cause ASAN bugs in the compiler like that compiling things so good to keep once but agree shouldn't have to do them again with the llvm-cpu-specific asan variant mode

**Comment by ScottTodd** [comment]
Sample run after refactoring: https://github.com/openxla/iree/actions/runs/8115687607/job/22184075017?pr=16452

Step | Time taken
-- | --
Configure | 1m10s
Build | 6m
Build test deps | 2m35s
Build microbenchmark suites | 20s
Main ctest | 27s
llvm-external-projects tests | 24s

Total: 18m14s before changes --> 11m52 after changes
