### ISSUE TITLE
GRAPH: Possible missing fusions of element-wise producer with reduction consumer

### ISSUE THREAD

**Issue by Max191** [iree-org/iree#16450]
The two dispatches in the following gist come from SDXL ([mlir file](https://storage.cloud.google.com/shark-public/ean/sdxl-turbine/SDXL1_0/BS1_len64/stable_diffusion_xl_base_1_0_64_unet_attn.mlir))

https://gist.github.com/Max191/49ef6fda457959cf4888897f4b0df8e7

We see a `dequant-like op -> element-wise op -> reduction -> element-wise op`. The indexing maps line up for all the ops, so I don't see any reason these can all get fused into a single dispatch. We should just need to fuse the `element-wise op -> reduction -> element-wise op`, and then the dequant-like op should clone into the dispatch region.

@MaheshRavishankar is there a reason these would not getting fused by default? The reduction is the only use of the producer element-wise op.

**Comment by benvanik** [comment]
(I noticed these too, thanks for extracting an example!)

**Comment by MaheshRavishankar** [comment]
> The two dispatches in the following gist come from SDXL ([mlir file](https://storage.cloud.google.com/shark-public/ean/sdxl-turbine/SDXL1_0/BS1_len64/stable_diffusion_xl_base_1_0_64_unet_attn.mlir))
> 
> https://gist.github.com/Max191/49ef6fda457959cf4888897f4b0df8e7
> 
> We see a `dequant-like op -> element-wise op -> reduction -> element-wise op`. The indexing maps line up for all the ops, so I don't see any reason these can all get fused into a single dispatch. We should just need to fuse the `element-wise op -> reduction -> element-wise op`, and then the dequant-like op should clone into the dispatch region.
> 
> @MaheshRavishankar is there a reason these would not getting fused by default? The reduction is the only use of the producer element-wise op.

I am not sure why the two elementwise operations in the first dispatch dont get fused. Thats strange. They should.

I think we dont fuse elementwise ops into reduction when reduction has more than one reduction dimension. There was an issue (I need to dig it up). But thats probably why...

**Comment by Max191** [comment]
@MaheshRavishankar what is the reason for this check?
https://github.com/openxla/iree/blob/b42e627e3761292676bbc6a405b7ef1829a8d53b/compiler/src/iree/compiler/Dialect/Flow/Transforms/FormDispatchRegions.cpp#L703-L705

This is the real thing blocking the fusion here, and it seems like it is very restrictive to me. Can we loosen this restriction somehow to allow more fusions like these?
