### ISSUE TITLE
Add a bisect tool using postsubmit pkgci artifacts

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#16556]
When diagnosing performance regressions it can be useful to run a bisect process to identify culprit commits. Git has a built in bisect tool: https://git-scm.com/docs/git-bisect, but bisecting across commits requires source builds that can be slow (particularly across LLVM commits). A full source build bisect with <10 steps can take a few hours if each build is 10-20 minutes long.

Postsubmit CI runs produce artifacts like the `linux_x86_64_release_packages` (68MB)  on https://github.com/openxla/iree/actions/runs/7978888274. We could bisect across commit ranges by downloading those release packages and running them. We could write a script that uses the GitHub CLI (https://cli.github.com/) to enumerate commits and postsubmit runs, download artifacts, and run a bisect test command (or allow manual marking of good/bad commits).

Nightly releases are also an option, especially when wanting to run on operating systems that pkgci does not currently produce artifacts for, but postsubmit CI runs should have artifacts for every commit with no gaps.

**Comment by stellaraccident** [comment]
Nice - this is basically the whole reason I set it up this way

**Comment by stellaraccident** [comment]
Partial approach here: https://github.com/openxla/iree/tree/main/experimental/regression_suite#setting-up-a-venv

**Comment by MacDue** [comment]
You may want to look into elfshaker too: https://github.com/elfshaker/elfshaker. We use this internally for quickly bisecting clang and GCC builds, and I believe it could work for IREE too.

For exampe, manyclangs (https://github.com/elfshaker/manyclangs) lets you download a few fairly small pack files (~few 100MB), then bisect through years of commits way quicker than you'd imagine using elfshaker + a small `git bisect` script.  I've bisected every commit between LLVM 14 to 15 in a few minutes with manyclangs.

**Comment by ScottTodd** [comment]
@saienduri added a script that fetches release artifacts here: https://github.com/nod-ai/SHARK-ModelDev/blob/main/ci-tools/latest-pkgci.py. That should make it easier to build such a bisect tool.

**Comment by ScottTodd** [comment]
Making progress on a bisect script that downloads and installs release artifacts corresponding to each git commit: https://github.com/ScottTodd/iree/tree/bisect-releases .

Still need to figure out a few details, mostly around reliable Python package installation. Having the main entry point be a Python script and having subtasks that need to `pip install` specific whl files is making things complicated. I probably need to rework how I'm using https://docs.python.org/3/library/venv.html somehow.
