### ISSUE TITLE
[CPU] i8mm i8*i8=i32 ukernel is slower than dotprod

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#16596]
### What happened?

On a simple matmul:

```
func.func @matmul(%lhs: tensor<197x768xi8>, %rhs: tensor<768x768xi8>, %acc: tensor<197x768xi32>) -> tensor<197x768xi32> {
  %result = linalg.matmul ins(%lhs, %rhs: tensor<197x768xi8>, tensor<768x768xi8>) outs(%acc: tensor<197x768xi32>) -> tensor<197x768xi32>
  return %result: tensor<197x768xi32>
}
```

The +dotprod ukernel performs faster than the +i8mm ukernel:

||i8mm latency (ms)|dotprod latency (ms)|
|-|-|-|
1 thread, no distribution|7.9|6.3
1 thread, distribution|10.3|6.1

||i8mm latency (ms)|dotprod latency (ms)|
|-|-|-|
5 threads, no distribution|21.8|19.7
5 threads, distribution|6.3|3.5

This is not expected since microbenchmarks show that i8mm performs better than dotprod:

```
-----------------------------------------------------------------------------------------------------------
Benchmark                                                 Time             CPU   Iterations UserCounters...
-----------------------------------------------------------------------------------------------------------
BM_mmt4d_s8s8s32_tile_1x8x4_dotprod/real_time         0.129 us        0.128 us      8388607 items_per_second=127.338G/s
BM_mmt4d_s8s8s32_tile_2x8x4_dotprod/real_time         0.164 us        0.163 us      8388607 items_per_second=200.269G/s
BM_mmt4d_s8s8s32_tile_4x8x4_dotprod/real_time         0.253 us        0.253 us      4194303 items_per_second=258.707G/s
BM_mmt4d_s8s8s32_tile_8x8x4_dotprod/real_time         0.363 us        0.362 us      2097151 items_per_second=361.478G/s
BM_mmt4d_s8s8s32_tile_1x8x8_i8mm/real_time            0.191 us        0.191 us      4194303 items_per_second=171.266G/s
BM_mmt4d_s8s8s32_tile_2x8x8_i8mm/real_time            0.182 us        0.182 us      4194303 items_per_second=359.516G/s
BM_mmt4d_s8s8s32_tile_4x8x8_i8mm/real_time            0.274 us        0.273 us      4194303 items_per_second=479.116G/s
BM_mmt4d_s8s8s32_tile_8x8x8_i8mm/real_time            0.452 us        0.451 us      2097151 items_per_second=579.566G/s
```

### Steps to reproduce your issue

1. Create matmul.mlir file with the contents below:

```
func.func @matmul(%lhs: tensor<197x768xi8>, %rhs: tensor<768x768xi8>, %acc: tensor<197x768xi32>) -> tensor<197x768xi32> {
  %result = linalg.matmul ins(%lhs, %rhs: tensor<197x768xi8>, tensor<768x768xi8>) outs(%acc: tensor<197x768xi32>) -> tensor<197x768xi32>
  return %result: tensor<197x768xi32>
}
```
2. Compile
```
INPUT_FILE=/tmp/matmul.mlir
ARM_CPU_FEATURE=dotprod
#ARM_CPU_FEATURE=i8mm

iree-compile "${INPUT_FILE}" --iree-hal-target-backends="llvm-cpu" --iree-input-type="tosa" --iree-llvmcpu-target-cpu-features="+${ARM_CPU_FEATURE}" --iree-llvmcpu-target-triple="aarch64-none-linux-android34" --iree-opt-data-tiling=true --iree-llvmcpu-enable-ukernels=all -o /tmp/matmul_${ARM_CPU_FEATURE}.vmfb
```
Add `--iree-llvmcpu-disable-distribution` to disable distribution.

3. Benchmark
```
ARM_CPU_FEATURE=dotprod
#ARM_CPU_FEATURE=i8mm

# On mobile device.
iree-benchmark-module --module=matmul_${ARM_CPU_FEATURE}.vmfb --device=local-task --function=matmul --input=197x768xi8=0 --input=768x768xi8=0 --input=197x768xi32=0 --task_topology_cpu_ids=0
```

### What component(s) does this issue relate to?

Compiler

### Version information

d7de68a33f

### Additional context

Related issue https://github.com/openxla/iree/issues/15399

**Comment by bjacob** [comment]
Interesting! Probably start with Tracy to see which dispatches take time, and then look at the asm code for these. Just Tracy Instrumentation (easy to set up) would be enough as you only need Tracy to point at the slow dispatch, dont necessarily need Tracy to zoom in down to asm level, can do that separately from Tracy.

**Comment by dcaballe** [comment]
I would also try with significantly smaller sizes (around 16/32?) to minimize any cache impact. We have a bunch of things in line to improve memory/cache behavior but we have to make sure what's going on to prioritize accordingly.

**Comment by bjacob** [comment]
But the weird thing here is it's *slower than dotprod*.  Most things like that seem like they should affect both equally, so whatever is at play here seems likely to be some kind of surprising detail, which is why I was suggesting heading straight to Tracy + disassembly.

**Comment by mariecwhite** [comment]
Tracy files can be downloaded here: https://storage.googleapis.com/iree-shared-files/mariewhite/tracies.zip

I profiled both the original matmul sizes and smaller sizes 16x32 * 32x32, disabling distribution and using 1 thread. Latencies below.

1 thread, no distribution | i8mm latency (ms) | dotprod latency (ms) |
-|-|-|
16x32 * 32x32 (small_matmul)|0.07|0.06
197x768 * 768x768 (matmul) |4.7|3.2

**Comment by bjacob** [comment]
great that you got the tracy traces! note, to set expectations --- I don't have time to dive myself into the level of detail here where I actually open the traces and try to think about them, this was merely a suggestion of what you could try --- let me know though if you need help understanding these traces. hopefully the 1.5x difference on the `197x768 * 768x768 (matmul)` single-thread case is big enough that that means that there has got to be something glaring in the traces.

**Comment by benvanik** [comment]
dotprod looks reasonable, the i8mm seems to break capstone though - it does at least show some weird swizzles/copies at the top which is odd to me given that this should be packed to avoid that
![image](https://github.com/openxla/iree/assets/75337/5eb587a9-f88e-47c0-81c1-59efb46c9a4b)

![image](https://github.com/openxla/iree/assets/75337/a15e0d9b-2275-4cc4-86c4-95c2d64be129)

**Comment by bjacob** [comment]
Yes i8mm requires capstone next branch, see our Tracy docs for that. But you can just dump executable intermediates instead. The swizzles with i8mm are expected, see i8mm ukernels source, they are fine because they are not in the innermost loop. (If you did see swizzles in the innermost loop, THAT would be unexpected bad codegen from clang). Need a working disasm of this func, plus a Tracy profile telling if the slowness really is in that func or elsewhere (Tracy instrumentation is enough here).

**Comment by mariecwhite** [comment]
Capstone at HEAD is not compatible with IREE's version of Tracy so had to find a commit that was compatible. Attached the trace ([matmul_i8mm_no_distribution.zip](https://github.com/openxla/iree/files/14454795/matmul_i8mm_no_distribution.zip)) and here is the screenshot:

![image](https://github.com/openxla/iree/assets/5143063/67dcd805-83da-441f-b866-8257d43e1e75)

For i8, `matmul_dispatch_3_mmt4d_25x96x96x8x8x8_i8xi8xi32` takes 33% of the runtime. For dotprod, `matmul_dispatch_3_mmt4d_25x96x192x8x8x4_i8xi8xi32` takes 21% of the runtime.

I'm not too familiar with how to read the disassembly but it looks like it's spending a lot of time in that `if (M0 == 1)` check ([here](https://github.com/openxla/iree/blob/03bc749f8617c87ab306df16d3c94d9ae0e414c4/runtime/src/iree/builtins/ukernel/arch/arm_64/mmt4d_arm_64_i8mm.c#L68)) and mispredicting, and it's in the inner loop. That's an easy fix. Do you see anything else that looks odd?

**Comment by bjacob** [comment]
Oh, interesting. The loop on M0 isn't being unrolled as it should be. I need to put kids to bed but can chat a bit later. If you open. The i8mm ukernel c file, spot that tiny loop on M0 around the vmmlaq, put a pragma unroll on it, you should get performance.

Regarding capstone and Tracy, sorry I forgot to mention, I had a patch for that as a Tracy pr, I'll link it when I'm at y computer.

**Comment by bjacob** [comment]
And the other loops on M0 around the accumulator loads and stores and swizzles, need that treatment too. That matters because not unrolling it effectively forced spillage here (the stp instructions after the zips) so the impact is large. Just pragma unroll all finite iteration count loops in that file (all loops except the main loop on K).

**Comment by bjacob** [comment]
Here the Tracy PR for capstone-next: https://github.com/wolfpld/tracy/pull/671

Regarding the pragma unrolls, that is a change that I knew I needed to make, I just didn't know that it would have an impact today, so now that I know that, I'll just whip up the PR.

**Comment by bjacob** [comment]
https://github.com/openxla/iree/pull/16626 should fix this. And has some details about what went wrong specifically with i8mm here, causing that specific one to miss unrolling: it comes down to a missing `static inline` on the implementation function.

**Comment by mariecwhite** [comment]
Good news, https://github.com/openxla/iree/pull/16626 takes the i8mm ukernel latency for `197x768 * 768x768` to 2.3ms (from 4.7ms).

mlir file|i8mm latency (ms)|dotprod latency (ms)
-|-|-|
197x768 * 768x768 (matmul)|	2.3|	3.2

Disassembly now looks like this:

![image](https://github.com/openxla/iree/assets/5143063/b640205a-108e-4179-bc98-6deea8caa1a9)

And tracy file: 
[matmul_i8mm_no_distribution_unrolled.zip](https://github.com/openxla/iree/files/14456097/matmul_i8mm_no_distribution_unrolled.zip)

**Comment by bjacob** [comment]
yes! that is what it should be.

**Comment by bjacob** [comment]
Note: i8mm should be nearly a 2x speedup over dotprod. That it is only a 3.2/2.3 == 1.4x speedup for an e2e matmul suggests that suboptimal tiling is hampering its memory/cache performance. Once that is fixed (which is part of the general discussion in #16410),  i8mm should get closer to 3.2/2 == 1.6 ms.

**Comment by bjacob** [comment]
(EDIT - this is fine actually, see at bottom of this comment) - There's still something (else) that's wonky about that asm.

It's subtracting 0x1800 == 6K from the pointer registers:

```asm
mov x16, #-0x1800
[...]
// within the loop
add x17, x10, x16
add x0, x14, x16
```

only to then apply an immediate offset of 0x1800 in the load-instructions to compensate that:

```asm
ldr q9, [x0, #0x1800]
// (and likewise the following 7 load instructions)
```

This seems silly; it's almost benign, but not quite: the two `add` instructions are part of the inner loop and collectively make it take ~ 1 extra cycle per loop iteration, which is probably a ~ 10% performance loss depending on the CPU, but particularly on a Cortex-X2 / Cortex-X3 that does 4 smmla instructions per cycle.

EDIT - this is actually fine. This `x16` is actually the loop counter: see how it is the operand to the `adds` instruction, the `s` suffix means set the condition-flags driving the loop's conditional jump. It's just counting in bytes left to be traversed until the end is reached. The 6K value comes from the dimensions of this dispatch, everything is so perfectly inlined that the static shape of this matmul propagates all the way to here. The M0/N0 width of this kernel being 8, the K-dimension of this matmul being 768,  8 * 768 == 6K of LHS/RHS data traversed by this ukernel inner loop.

And the reason why this probably isn't a 10% performance loss is that there are more than enough dual-issue slots, assuming an out-of-order core able to reorder this code a bit, these general-register additions are going to dual-issue fine with the NEON-register arithmetic. This code is perhaps not as friendly to an in-order Cortex-A510 but there, the much higher cost of the smmla arithmetic (only 1 per cycle, vs 2 or 4 on A710/X2) means that that dominates much more anyway.
