### ISSUE TITLE
ImportError: cannot import name '_runtime' from 'iree._runtime_libs' (unknown location)

### ISSUE THREAD

**Issue by muwys518** [iree-org/iree#16646]
### What happened?

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/roger.luo/workspace/test/iree/code/iree-build-base/runtime/bindings/python/iree/runtime/__init__.py", line 13, in <module>
    from . import _binding
  File "/home/roger.luo/workspace/test/iree/code/iree-build-base/runtime/bindings/python/iree/runtime/_binding.py", line 19, in <module>
    from .._runtime.libs import _runtime
ImportError: cannot import name '_runtime' from 'iree._runtime_libs' (unknown location)

### Steps to reproduce your issue

1. cmake -GNinja -B ../iree-build-base -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON -DCMAKE_C_COMPILER=/usr/bin/clang-9 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-9 -DCMAKE_INSTALL_PREFIX=../iree-build-base/install -DCMAKE_BUILD_TYPE=RelWithDebInfo -DIREE_BUILD_PYTHON_BINDINGS=ON -DPython3_EXECUTABLE="$(which python)" .
2. cmake --build ../iree-build-base --target install
3. source ../iree-build-base/.env && export PYTHONPATH
4. python -c "import iree.compiler"
5. python -c "import iree.runtime"
6. See error

### What component(s) does this issue relate to?

Python

### Version information

commit eda28bf01d10d13f86df9018cb1f35a2dcb1cadc (HEAD -> main, origin/main, origin/HEAD)
Author: Lei Zhang <antiagainst@gmail.com>
Date:   Sun Mar 3 17:37:23 2024 -0800

    [hip][rocm] Fix hipGetDeviceProperties usage after ROCm 6.0 (#16643)

    ROCm 6.0 changes the `hipDeviceProp_t` struct, so we would need the new
    `hipGetDevicePropertiesR0600()` API to query it--the existing
    `hipGetDeviceProperties()`l API won't work for our case with dynamic
    libraries.

    Related to https://github.com/ROCm/ROCm/issues/2728

**Comment by stellaraccident** [comment]
I'm not sure that the flag -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON

is going to work for a dev build like this as I think it sets up an rpath that does not match the organization of the build tree.

This can be verified by running `ldd` on the _runtime.*.so in the python path. If it shows that libraries were not found, that would be the problem. Note that when Python has an error loading a native library, it reports it as not found.

**Comment by muwys518** [comment]
> I'm not sure that the flag -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON
> 
> is going to work for a dev build like this as I think it sets up an rpath that does not match the organization of the build tree.
> 
> This can be verified by running `ldd` on the _runtime.*.so in the python path. If it shows that libraries were not found, that would be the problem. Note that when Python has an error loading a native library, it reports it as not found.


I used the following command, but the problem still persists：
 cmake -GNinja -B ../iree-build-base -DCMAKE_C_COMPILER=/usr/bin/clang-9 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-9 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DIREE_BUILD_PYTHON_BINDINGS=ON -DPython3_EXECUTABLE="$(which python)" .

I have any other step error?

**Comment by bailuan** [comment]
Is this error solved?

**Comment by bailuan** [comment]
This error occurs under conda virtual env, but it is fine under conda base env.

**Comment by muwys518** [comment]
> This error occurs under conda virtual env, but it is fine under conda base env.

I'm not sure，I have build python package to solve it.

**Comment by bailuan** [comment]
You mean that you use pip install ? That still didn't solve the issue.

**Comment by stellaraccident** [comment]
I don't have enough information to even speculate at the problem. The problem sounds environmental. I would need a docker image or equivalent information to reproduce.

Nine times out of ten this is due to an improper python setup, mismatched python versions or a basic inability for the os to load the shared library.

**Comment by muwys518** [comment]
> You mean that you use pip install ? That still didn't solve the issue.

I use ./build_tools/python_deploy/build_linux_packages.sh to build new version package then I use pip install the new version package in conda env, I can use  package continue, but still didn't solve the issue, You are right. I have no idea for this problem

**Comment by muwys518** [comment]
> I don't have enough information to even speculate at the problem. The problem sounds environmental. I would need a docker image or equivalent information to reproduce.
> 
> Nine times out of ten this is due to an improper python setup, mismatched python versions or a basic inability for the os to load the shared library.

It seems like it's an environmental issue.

**Comment by muwys518** [comment]
> This error occurs under conda virtual env, but it is fine under conda base env.

I have same problem in conda base env

**Comment by bailuan** [comment]
Though I didn't figure out why this happened, I strongly suggest stop using anaconda. I use pyvenv instead of conda, no error happened any more even under virtual envs.

**Comment by bailuan** [comment]
> > This error occurs under conda virtual env, but it is fine under conda base env.
> 
> I have same problem in conda base env

do not use conda, it is not a good choice, in my opinion.

**Comment by muwys518** [comment]
> Though I didn't figure out why this happened, I strongly suggest stop using anaconda. I use pyvenv instead of conda, no error happened any more even under virtual envs.

thanks， I‘ll try it

**Comment by muwys518** [comment]
> I don't have enough information to even speculate at the problem. The problem sounds environmental. I would need a docker image or equivalent information to reproduce.
> 
> Nine times out of ten this is due to an improper python setup, mismatched python versions or a basic inability for the os to load the shared library.

I think I have found the reason. The python environment for building the python package needs to be the same as the python environment for python -c. If there is a difference, there will be problems.

**Comment by muwys518** [comment]
> Though I didn't figure out why this happened, I strongly suggest stop using anaconda. I use pyvenv instead of conda, no error happened any more even under virtual envs.

I think I have found the reason. The python environment for building the python package needs to be the same as the python environment for python -c. If there is a difference, there will be problems.

**Comment by bailuan** [comment]
Maybe, but I have encountered several problem under conda, not only this one `_`

**Comment by muwys518** [comment]
> Maybe, but I have encountered several problem under conda, not only this one `_`

I have solved this problem, previously I was building in the container and referencing the python package outside the container. Now after I set the python interpreter inside the container and outside the container to be consistent, the problem has not occurred.

**Comment by muwys518** [comment]
> I don't have enough information to even speculate at the problem. The problem sounds environmental. I would need a docker image or equivalent information to reproduce.
> 
> Nine times out of ten this is due to an improper python setup, mismatched python versions or a basic inability for the os to load the shared library.

I have solved this problem, previously I was building in the container and referencing the python package outside the container. Now after I set the python interpreter inside the container and outside the container to be consistent, the problem has not occurred.
Thank you!
