### ISSUE TITLE
Test case failures in iree-run-module with signed/unsigned/signless types

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#16674]
Seeing a large number of ONNX tests failing like this:

```
EXEC @test_constantofshape_int_shape_zero
[FAILED] result[0]: metadata is 0xi32; expected that the view matches 0xsi32; expected that the view is equal to contents of a view of 0xsi32
  expected:
0xsi32=
  actual:
0xi32=

EXEC @test_constantofshape_int_zeros
[FAILED] result[0]: metadata is 10x6xi32; expected that the view matches 10x6xsi32; expected that the view is equal to contents of a view of 10x6xsi32
  expected:
10x6xsi32=[0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0]
  actual:
10x6xi32=[0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0][0 0 0 0 0 0]
```

Probably needs a fix to the expected output handling in `iree-run-module` somewhere

**Comment by ScottTodd** [comment]
I also ran into this here: https://github.com/openxla/iree/pull/15918#discussion_r1425956156

```mlir
// Buffer values can be read from binary files with `@some/file.bin`.
//   * numpy npy files from numpy.save or previous tooling output can be read to
//     provide 1+ values.
//   * Some data types may be converted (i32 -> si32 here)

// RUN: iree-compile --iree-hal-target-backends=vmvx %s -o %t.vmfb
//
// RUN: iree-run-module --device=local-sync --module=%t.vmfb --function=npy_round_trip \
// RUN:   --input="2xi32=11 12" --input="3xi32=1 2 3" --output=@%t.npy --output=+%t.npy
//
// RUN: iree-run-module --device=local-sync --module=%t.vmfb --function=npy_round_trip \
// RUN:   --input=@%t.npy | \
// RUN: FileCheck --check-prefix=INPUT-NPY_FILES %s

// INPUT-NPY_FILES-LABEL: EXEC @npy_round_trip
func.func @npy_round_trip(%arg0: tensor<2xi32>, %arg1: tensor<3xi32>) -> (tensor<2xi32>, tensor<3xi32>) {
  // INPUT-NPY_FILES: result[0]: hal.buffer_view
  // INPUT-NPY_FILES-NEXT: 2xsi32=11 12
  // INPUT-NPY_FILES: result[1]: hal.buffer_view
  // INPUT-NPY_FILES-NEXT: 3xsi32=1 2 3
  return %arg0, %arg1 : tensor<2xi32>, tensor<3xi32>
}
```

**Comment by PhaneeshB** [comment]
Moving the update from #16916, here

```
Stdout diagnostics:
EXEC @test_add_uint8

[FAILED] result[0]: metadata is 3x4x5xi8; expected that the view matches 3x4x5xui8; expected that the view is equal to contents of a view of 3x4x5xui8

expected:
3x4x5xui8=[[18 24 22 22 20][14 38 44 14 27][30 14 20 12 20][36 25 31 6 8]][[28 30 19 7 18][26 33 23 34 19][29 39 14 32 44][26 25 18 28 24]][[24 36 16 28 25][16 23 22 20 39][27 20 34 19 26][16 17 8 16 11]]
  actual:
3x4x5xi8=[[18 24 22 22 20][14 38 44 14 27][30 14 20 12 20][36 25 31 6 8]][[28 30 19 7 18][26 33 23 34 19][29 39 14 32 44][26 25 18 28 24]][[24 36 16 28 25][16 23 22 20 39][27 20 34 19 26][16 17 8 16 11]]

Compiled with: iree-compile model.mlir --iree-hal-target-backends=llvm-cpu -o model_cpu_llvm_sync_test.vmfb

Run with: iree-run-module --module=model_cpu_llvm_sync_test.vmfb --device=local-sync --flagfile=test_data_flags.txt
 ```
 MLIR :
 ```
 module {
  func.func @test_add_uint8(%arg0: !torch.vtensor<[3,4,5],ui8>, %arg1: !torch.vtensor<[3,4,5],ui8>) -> !torch.vtensor<[3,4,5],ui8> attributes {torch.onnx_meta.ir_version = 7 : si64, torch.onnx_meta.opset_version = 17 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
    %none = torch.constant.none
    %0 = torch.operator "onnx.Add"(%arg0, %arg1) : (!torch.vtensor<[3,4,5],ui8>, !torch.vtensor<[3,4,5],ui8>) -> !torch.vtensor<[3,4,5],ui8> 
    return %0 : !torch.vtensor<[3,4,5],ui8>
  }
}
 ```
 iree-compiler  and runtime versions : `20240326.843`

**Comment by PhaneeshB** [comment]
Looking at the mlir-after-all dump (attached)

Until `FuncConversion (torch-iree-func-conversion)` Pass
the result type is casted to ui8 and after the extracting the method the output type is recasted to i8 to return as a hal.buffer.view 

```
// -----// IR Dump BEFORE FuncConversion (torch-iree-func-conversion) //----- //
#executable_target_embedded_elf_x86_64_ = #hal.executable.target<"llvm-cpu", "embedded-elf-x86_64", {cpu = "generic", cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128", native_vector_size = 16 : i64, target_triple = "x86_64-unknown-unknown-eabi-elf"}>
#map = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
#device_target_llvm_cpu = #hal.device.target<"llvm-cpu", [#executable_target_embedded_elf_x86_64_]>
module attributes {hal.device.targets = [#device_target_llvm_cpu]} {
  ml_program.global private mutable @global_seed(dense<0> : tensor<i64>) : tensor<i64>
  func.func @test_add_uint8(%arg0: !torch.vtensor<[3,4,5],ui8>, %arg1: !torch.vtensor<[3,4,5],ui8>) -> !torch.vtensor<[3,4,5],ui8> attributes {torch.assume_strict_symbolic_shapes, torch.onnx_meta.ir_version = 7 : si64, torch.onnx_meta.opset_version = 17 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
    %0 = torch_c.to_builtin_tensor %arg0 : !torch.vtensor<[3,4,5],ui8> -> tensor<3x4x5xi8>
    %1 = torch_c.to_builtin_tensor %arg1 : !torch.vtensor<[3,4,5],ui8> -> tensor<3x4x5xi8>
    %2 = tensor.empty() : tensor<3x4x5xi8>
    %3 = linalg.generic {indexing_maps = [#map, #map, #map], iterator_types = ["parallel", "parallel", "parallel"]} ins(%0, %1 : tensor<3x4x5xi8>, tensor<3x4x5xi8>) outs(%2 : tensor<3x4x5xi8>) {
    ^bb0(%in: i8, %in_0: i8, %out: i8):
      %5 = arith.addi %in, %in_0 : i8
      linalg.yield %5 : i8
    } -> tensor<3x4x5xi8>
    %4 = torch_c.from_builtin_tensor %3 : tensor<3x4x5xi8> -> !torch.vtensor<[3,4,5],ui8>
    return %4 : !torch.vtensor<[3,4,5],ui8>
  }
}

// -----// IR Dump After FuncConversion (torch-iree-func-conversion) //----- //
#executable_target_embedded_elf_arm_64_ = #hal.executable.target<"llvm-cpu", "embedded-elf-arm_64", {cpu = "generic", cpu_features = "+reserve-x18", data_layout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128", native_vector_size = 16 : i64, target_triple = "arm64-unknown-unknown-eabi-elf"}>
#map = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
#device_target_llvm_cpu = #hal.device.target<"llvm-cpu", [#executable_target_embedded_elf_arm_64_]>
module attributes {hal.device.targets = [#device_target_llvm_cpu]} {
  ml_program.global private mutable @global_seed(dense<0> : tensor<i64>) : tensor<i64>
  util.func public @test_add_uint8$async(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view, %arg2: !hal.fence, %arg3: !hal.fence) -> !hal.buffer_view attributes {inlining_policy = #util.inline.never, iree.abi.model = "coarse-fences", iree.abi.stub} {
    %0 = hal.tensor.import wait(%arg2) => %arg0 : !hal.buffer_view -> tensor<3x4x5xi8>
    %1 = torch_c.from_builtin_tensor %0 : tensor<3x4x5xi8> -> !torch.vtensor<[3,4,5],ui8>
    %2 = hal.tensor.import wait(%arg2) => %arg1 : !hal.buffer_view -> tensor<3x4x5xi8>
    %3 = torch_c.from_builtin_tensor %2 : tensor<3x4x5xi8> -> !torch.vtensor<[3,4,5],ui8>
    %4 = torch_c.to_builtin_tensor %1 : !torch.vtensor<[3,4,5],ui8> -> tensor<3x4x5xi8>
    %5 = torch_c.to_builtin_tensor %3 : !torch.vtensor<[3,4,5],ui8> -> tensor<3x4x5xi8>
    %6 = tensor.empty() : tensor<3x4x5xi8>
    %7 = linalg.generic {indexing_maps = [#map, #map, #map], iterator_types = ["parallel", "parallel", "parallel"]} ins(%4, %5 : tensor<3x4x5xi8>, tensor<3x4x5xi8>) outs(%6 : tensor<3x4x5xi8>) {
    ^bb0(%in: i8, %in_0: i8, %out: i8):
      %12 = arith.addi %in, %in_0 : i8
      linalg.yield %12 : i8
    } -> tensor<3x4x5xi8>
    %8 = torch_c.from_builtin_tensor %7 : tensor<3x4x5xi8> -> !torch.vtensor<[3,4,5],ui8>
    %9 = torch_c.to_builtin_tensor %8 : !torch.vtensor<[3,4,5],ui8> -> tensor<3x4x5xi8>
    %10 = hal.tensor.barrier join(%9 : tensor<3x4x5xi8>) => %arg3 : !hal.fence
    %11 = hal.tensor.export %10 : tensor<3x4x5xi8> -> !hal.buffer_view
    util.return %11 : !hal.buffer_view
  }
  util.func public @test_add_uint8(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub} {
    %c-1_i32 = arith.constant -1 : i32
    %c0 = arith.constant 0 : index
    %device_0 = hal.devices.get %c0 : !hal.device
    %0 = util.null : !hal.fence
    %fence = hal.fence.create device(%device_0 : !hal.device) flags("None") : !hal.fence
    %1 = util.call @test_add_uint8$async(%arg0, %arg1, %0, %fence) : (!hal.buffer_view, !hal.buffer_view, !hal.fence, !hal.fence) -> !hal.buffer_view
    %status = hal.fence.await until([%fence]) timeout_millis(%c-1_i32) : i32
    util.return %1 : !hal.buffer_view
  }
}

```

[ir-after-all.mlir.txt](https://github.com/openxla/iree/files/14776906/ir-after-all.mlir.txt)

**Comment by ScottTodd** [comment]
I'd start by fixing the npy round tripping (e.g. in https://github.com/openxla/iree/blob/main/tools/test/iree-run-module-inputs.mlir). Can't fix the higher level programs if the low level tools are broken too.

Another thing we could do would be to allow ignoring some metadata when checking outputs, but that would just be a bandaid and not a robust fix.

**Comment by stellaraccident** [comment]
The internals of the compiler have always been "signless integers". These are neither signed nor unsigned. Higher level tooling cares about the distinction but low level tools like iree-run-module just do what they are told.

My personal opinion is that a check tool, when confronted with a module that returns signless values and having an expected value that is sign-carrying, is well within its rights to re-interpret the result with its expecting sign semantics.

**Comment by benvanik** [comment]
Agreed - internally we allow this signedness casting because it doesn't matter:
https://github.com/openxla/iree/blob/d884c5450ff89073d56f579ba3097a290d18b61b/runtime/src/iree/modules/hal/utils/buffer_diagnostics.c#L120-L129

Ideally bindings should at most be saying e.g. "I expect this to be ui32" and then comparing what it gets back to see if it's compatible (i32, si32, ui32, etc) instead of precisely trying to match what it gets back with enum equality. Outside of tests or really sloppy runners (of which we may be one in some cases :) there's not many realistic use cases where the invoker of a function has no idea what it's getting back or how to interpret it but _also_ cares enough to fail if it doesn't exactly match.

w.r.t. numpy files: we will never be able to round-trip things correctly as numpy can't represent all of the types we can. it's also developer tooling and I don't think we really care to try to make it a source of truth for tests as it'll never be sufficient for all the tests we need to write. e.g., can't support i4, bf16, f8, etc in numpy files or any fun blocked/packed formats and we'll have to store them as opaque byte arrays and then we're back at needing the same fuzzy matching/casting as above ("do you have enough bytes/the right shape and are the bytes correct" and ignoring everything else).

A good litmus test for whether a generic test runner is depending on things it shouldn't is whether it will fail if a buffer view is returned with an `IREE_HAL_ELEMENT_TYPE_OPAQUE_*` element type and/or `IREE_HAL_ENCODING_TYPE_OPAQUE`. It's legal for the compiler/runtime to return every buffer view like that (and we will on stateless programs once we have a way to mark which state is private to the program so that we can avoid packing/unpacking state args/results between invocations).

**Comment by ScottTodd** [comment]
https://github.com/nod-ai/SHARK-TestSuite/pull/146 proposed switching the comparison approach from using `iree-run-module ... --expected_output=` to using `iree-run-module ... --output=` and then loading the output into Python to use numpy comparison routines.

Looking at the C/C++ code in IREE, I think we can instead relax the metadata check here: https://github.com/openxla/iree/blob/05ff73f3b4298fb63f81f5038d33bda585165694/runtime/src/iree/tooling/buffer_view_matchers.c#L267-L273 , possibly gated behind a new flag defined here: https://github.com/openxla/iree/blob/05ff73f3b4298fb63f81f5038d33bda585165694/runtime/src/iree/tooling/comparison.cc#L21-L26 like
```c++
IREE_FLAG(
    bool, expected_allow_signedness_mismatches, true,
    "Allow mismatches between signless and signed types (e.g. si32 and i32)");
```

---

Another option would be switching from numpy reference output files to binary files

**Comment by benvanik** [comment]
binary files are going to be best because of numpy not supporting all types as then you can pass in the exact types you expect per output instead of having to round-trip through numpy.

**Comment by benvanik** [comment]
(the advantage of expected_output is that we can get reproducers that are easy to run/verify in debuggers/etc without having to use the test framework - if we dump files and then require the test runner to perform the match we'll make it harder to get standalone reproducers)

**Comment by ScottTodd** [comment]
> (the advantage of expected_output is that we can get reproducers that are easy to run/verify in debuggers/etc without having to use the test framework - if we dump files and then require the test runner to perform the match we'll make it harder to get standalone reproducers)

Yep! I gave similar feedback on https://github.com/nod-ai/SHARK-TestSuite/pull/146.

**Comment by ScottTodd** [comment]
> binary files are going to be best because of numpy not supporting all types as then you can pass in the exact types you expect per output instead of having to round-trip through numpy.

Sounds good. Switching test files from npy to bin would involve changing https://github.com/nod-ai/SHARK-TestSuite/blob/9464d503ddf37e658cf267254ac65a3d1f143344/iree_tests/onnx/import_tests.py#L132-L152 , possibly using code from https://github.com/nod-ai/SHARK-TestSuite/blob/9464d503ddf37e658cf267254ac65a3d1f143344/e2eshark/run.py#L255-L279. @PhaneeshB do you want to give that a try?

**Comment by PhaneeshB** [comment]
added changes here to keep using expected output with bin files to have finer control over output dtype
https://github.com/nod-ai/SHARK-TestSuite/pull/212
