### ISSUE TITLE
[LinalgExt] Add scale to linalg_ext.attention op

### ISSUE THREAD

**Issue by qedawkins** [iree-org/iree#16676]
The pytorch SDPA op specifies a scaling factor for the attention operation that is currently unsupported in the lowering to TMTensor because the corresponding LinalgExt op does not include an argument for the scale.

https://github.com/openxla/iree/blob/7782a414ea473c59f6d7a882cb510690ed666c79/compiler/src/iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td#L514

Additionally, the current default scale of 1.0 does not match the default specified by the pytorch op it lowers from:
https://github.com/llvm/torch-mlir/blob/933db87a07fb828b17b75f2f5f396a434f8f1a17/lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp#L1502
vs
https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html

The linalg_ext op needs to specify the scale based on the pytorch op, or the lowering to TMTensor the needs to handle the scale as a separate leading elementwise multiplication.

**Comment by Groverkss** [comment]
https://github.com/openxla/iree/pull/16679 Added scaling to linalg_ext op. The support on TMTensor side and torch-mlir side needs to be plumbed now.

**Comment by stellaraccident** [comment]
If you want to skip the tmtensor side, it will require a bit of rework, but you can direct lower this. There being a cutout to tmtensor there is legacy.

**Comment by qedawkins** [comment]
Closing as completed by #16679
