### ISSUE TITLE
Dumping expected results to .npy files does not roundtrip with --expected_output

### ISSUE THREAD

**Issue by qedawkins** [iree-org/iree#16686]
## Problem description + Reproducer
Simple elementwise add
```mlir
!tensor_t = tensor<4xf32>

func.func @forward(
    %A : !tensor_t, %B : !tensor_t) -> !tensor_t {
  %C = tensor.empty() : !tensor_t
  %0 = linalg.add ins(%A, %B : !tensor_t, !tensor_t)
                     outs(%C : !tensor_t) -> !tensor_t
  return %0 : !tensor_t
}
```
Compile + run and try to roundtrip the expected output with the same vmfb
```
iree-compile elementwise.mlir \
    --iree-llvmcpu-target-triple=x86_64-unknown-linux \
    --iree-hal-target-backends=llvm-cpu \
    -o /tmp/elementwise.vmfb

iree-run-module \
    --module=/tmp/elementwise.vmfb \
    --device=local-task \
    --function=forward \
    --input=4xf32=1.0 \
    --input=4xf32=2.0 \
    --output=@output.npy

iree-run-module \
    --module=/tmp/elementwise.vmfb \
    --device=local-task \
    --function=forward \
    --input=4xf32=1.0 \
    --input=4xf32=2.0 \
    --expected_output=4xf32=@output.npy
```

Produces the following failure to match
```
EXEC @forward
EXEC @forward
[FAILED] result[0]: element at index 0 (3) does not match the expected (2.23669E+08); expected that the view is equal to contents of a view of 4xf32
  expected:
4xf32=2.23669E+08 1.23875E-40 3.48335E-15 4.48986E+21
  actual:
4xf32=3 3 3 3
```

Using `.bin` files instead of `.npy` files works as expected.

**Comment by benvanik** [comment]
by saying `--expected_output=4xf32=file` you are saying that the file should be parsed as binary. Just use `--expected_output=@output.npy`.

**Comment by qedawkins** [comment]
ah, ok that worked

**Comment by qedawkins** [comment]
The way the help documentation for `--expected_output` works makes it seem like I'm supposed to pass the shape.
```
# An expected function output following the same format as `--input=`.
# When present the results of the invocation will be compared against
# these values and the tool will return non-zero if any differ. If the
# value of a particular output is not of interest provide `(ignored)`.
# --expected_output=...
```

And then the format for `--input` isn't very clear about this to me
```
# Raw binary files can be read to provide buffer contents:
#   2x2xi32=@some/file.bin
# Numpy npy files from numpy.save can be read to provide 1+ values:
#   @some.npy
```

but this issue solved so closing it, thanks!

**Comment by benvanik** [comment]
binary files need shapes/types, numpy files don't
comments here may be more informative and should probably be copied back into the help:
https://github.com/openxla/iree/blob/main/runtime/src/iree/tooling/function_io.h#L23-L46

**Comment by ScottTodd** [comment]
We also have this documentation page: https://iree.dev/developers/general/developer-overview/#iree-run-module

I focused on clarifying scalar/tensor types when I wrote that... should also talk about files (npy and binary)

**Comment by qedawkins** [comment]
yeah the reasoning for metadata makes sense. Copying back to the help would be nice.
