### ISSUE TITLE
"stat: ... File name too long" when building e2e test artifacts

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#16711]
To reproduce I just enabled `IREE_BUILD_E2E_TEST_ARTIFACTS` and did: `ninja iree-e2e-test-artifacts`.

Result:

```
ninja: error: stat(tests/e2e/test_artifacts/iree_tests_e2e_test_artifacts_iree-module-BertForMaskedLMTF_stablehlo___x86_64-cascadelake-linux_gnu-llvm_cpu__default-flags_dt-uk_compile-stats_): File name too long
```

**Comment by benvanik** [comment]
(probably need a platform/version/etc)

**Comment by bjacob** [comment]
```
~/iree-build uname -a
Linux hocher 6.5.0-25-generic #25-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 14:58:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
~/iree-build cmake --version
cmake version 3.27.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
~/iree-build ninja --version
1.11.1
```

**Comment by pzread** [comment]
The filename is long but its length 170 characters should still be under the Linux default limit? Can you check the length of the full path? Maybe the current working directory is deep

**Comment by bjacob** [comment]
Agree, this is why I don't understand! Neither my source nor my build directories are deep (and there are no symlinks either, so `realpath` still prints the same)
```
/home/benoit/iree
/home/benoit/iree-build
```

**Comment by bjacob** [comment]
AAh but I have an encrypted home directory. This is non-transparent in various ways, I wonder if that is one of them. Actually yes it is: https://wiki.archlinux.org/title/ECryptfs#Deficiencies . Sorry about the noise!  FYI @kuhar , I'm going to finally nuke that windows partition and go full-disk encrypted.

**Comment by pzread** [comment]
That's a very interesting finding!
