### ISSUE TITLE
Cleanup various verbose attention tests

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#16720]
We have a few attention tests that are essentially change detector:

https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/test/tile_and_decompose_attention.mlir
https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMGPU/test/attention.mlir

It's quite difficult to modify everytime we touch the transform script or other changes cause the IR change. We need to trim it down a bit. Typically I would do one relatively full tests to check more details, and with the rest being just check what the different parts are.

**Comment by benvanik** [comment]
yeah! <3 
(these have bit me before too)

**Comment by Groverkss** [comment]
These tests were nuked, and replaced by nicer ones, as we moved to the C++ attention pipeline.
