### ISSUE TITLE
HIP driver tests fail to compile

### ISSUE THREAD

**Issue by sogartar** [iree-org/iree#16768]
### What happened?

There are a bunch of tests that fail to compile with
```
FAILED: runtime/plugins/hal/drivers/hip/tests/stablehlo_ops/check_hip_stream_reduce.mlir_module.vmfb /home/nmeganat/boian/ws/iree/build/RelWithDebInfo/runtime/plugins/hal/drivers/hip/tests/stablehlo_ops/check_hip_stream_reduce.mlir_module.vmfb 
cd /home/nmeganat/boian/ws/iree/build/RelWithDebInfo/runtime/plugins/hal/drivers/hip/tests/stablehlo_ops && /home/nmeganat/boian/ws/iree/build/RelWithDebInfo/tools/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=rocm --iree-input-type=stablehlo --iree-rocm-link-bc=false --iree-rocm-target-chip= --iree-rocm-bc-dir= /home/nmeganat/boian/ws/iree/repo/tests/e2e/stablehlo_ops/reduce.mlir -o check_hip_stream_reduce.mlir_module.vmfb --iree-hal-executable-object-search-path=\"/home/nmeganat/boian/ws/iree/build/RelWithDebInfo\"
iree-compile: /home/nmeganat/boian/ws/iree/repo/third_party/llvm-project/llvm/include/llvm/MC/MCInstrInfo.h:64: const llvm::MCInstrDesc &llvm::MCInstrInfo::get(unsigned int) const: Assertion `Opcode < NumOpcodes && "Invalid opcode!"' failed.
Segmentation fault (core dumped)
```

### Steps to reproduce your issue

Build commands:
```
BUILD_TYPE=RelWithDebInfo

cmake \
  -G Ninja \
  -B "$IREE_BUILD_DIR" \
  -S "$IREE_SRC_DIR" \
  -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
  -DLLVM_ENABLE_ASSERTIONS=ON \
  -DIREE_ENABLE_ASSERTIONS=ON \
  -DIREE_ENABLE_LLD=ON \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DIREE_TARGET_BACKEND_ROCM=ON \
  -DIREE_TARGET_BACKEND_LLVM_CPU=ON \
  -DIREE_EXTERNAL_HAL_DRIVERS="hip;rocm"

cmake --build "$IREE_BUILD_DIR"
```

### What component(s) does this issue relate to?

Compiler

### Version information

8711c812455955f9dc252dba0d7943a7dba15cbe

### Additional context

The same build config, but in `Debug` did not fail.

**Comment by sogartar** [comment]
Somehow the first time when the conformance tests get generated in CMake, `IREE_ROCM_TARGET_CHIP` and `IREE_ROCM_BC_DIR` are empty.
Subsequent reconfigurations populate the correct value.

**Comment by sogartar** [comment]
The experimental [hip](https://github.com/openxla/iree/blob/8711c812455955f9dc252dba0d7943a7dba15cbe/experimental/hip/tests/stablehlo_ops/CMakeLists.txt#L14) driver uses stuff from the experimental [rocm](https://github.com/openxla/iree/blob/8711c812455955f9dc252dba0d7943a7dba15cbe/experimental/rocm/CMakeLists.txt#L15) driver.
On first configuration the cache variables where not defined yet.

**Comment by ScottTodd** [comment]
This looks obsolete. We have some of these tests building + running on CI now.
