### ISSUE TITLE
[hip] driver tests status

### ISSUE THREAD

**Issue by sogartar** [iree-org/iree#16770]
Since we don't have CI for the HIP runtime, I am posting here the test status. Lets keep track here until we get the CI up.

[summary.log](https://github.com/openxla/iree/files/14603137/summary.log)
 [LastTest.log](https://github.com/openxla/iree/files/14603026/LastTest.log)

CMake configure command:
```
BUILD_TYPE=Debug

cmake \
  -G Ninja \
  -B "$IREE_BUILD_DIR" \
  -S "$IREE_SRC_DIR" \
  -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
  -DLLVM_ENABLE_ASSERTIONS=ON \
  -DIREE_ENABLE_ASSERTIONS=ON \
  -DIREE_ENABLE_LLD=ON \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DIREE_TARGET_BACKEND_ROCM=ON \
  -DIREE_TARGET_BACKEND_LLVM_CPU=ON \
  -DIREE_EXTERNAL_HAL_DRIVERS="hip;rocm" \
  -DIREE_HIP_DRIVER_TARGET_CHIP=gfx940
```

This was tested against [HIP](https://github.com/nod-ai/TheRock/releases/tag/nightly-staging-20240313.26).

**Comment by ScottTodd** [comment]
We have tests for HIP now. Closing this stale issue.
