### ISSUE TITLE
Possible issue with allocations for custom dispatch use case

### ISSUE THREAD

**Issue by nirvedhmeshram** [iree-org/iree#16978]
I am seeing a correctness issue with calling the same custom dispatch  multiple times, I see a clear problem after `FuseDispatchBindingsPass`  ,  Here is a short gist
https://gist.github.com/nirvedhmeshram/ea15e4d5912af911282dc209da291ee2
The problem is the second dispatch is
```
      stream.cmd.dispatch @mlp_external_f32_f32_f32_i32_i32_i32_executable::@mlp_external_f32_f32_f32_i32_i32_i32_entry_point(%c0, %c0, %14, %10, %11, %11, %0, %6, %5, %6, %0, %6 : index, index, index, i32, i32, i32, index, index, index, index, index, index) {
        ro %arg5[%c0_2 for %15] : !stream.resource<transient>{%15},
        ro %arg3[%c0_2 for %8] : !stream.resource<external>{%8},
        wo %arg5[%c0_2 for %15] : !stream.resource<transient>{%15}
      }
```
Its reading and writing to the same buffer, which would be wrong for a matmul

Here is also the full dump for this
https://gist.github.com/nirvedhmeshram/f8b0c268447c41d9c65c7f8b48d2a618

Draft PR used to create this issue
https://github.com/openxla/iree/pull/16967

commands used to compile and run

```
iree-compile  --iree-preprocessing-pdl-spec-filename=$IREE_HOME/samples/custom_dispatch/cpu/mlp_plugin/mlp_linalg_spec.pdl.mlir $IREE_HOME/samples/custom_dispatch/cpu/mlp_plugin/mlp_linalg_two_matmul.mlir --mlir-print-ir-after-all --mlir-disable-threading -o mlp.vmfb

iree-run-module --device=local-sync --executable_plugin=$IREE_BUILD_DIR/samples/custom_dispatch/cpu/mlp_plugin/mlp_plugin.so --module=mlp.vmfb --function=mlp_invocation --input="8x8xf32=6" --input="8x8xf32=5"

**Comment by nirvedhmeshram** [comment]
It is worth noting though that the write buffer has an offset given to it
```
      %0 = hal.interface.constant.load[0] : i32
      %1 = hal.interface.constant.load[1] : i32
      %15 = arith.extui %0 : i32 to i64
      %16 = arith.extui %1 : i32 to i64
      %17 = arith.shli %16, %c32_i64 : i64
      %18 = arith.ori %15, %17 : i64
      %19 = arith.index_castui %18 {stream.alignment = 64 : index} : i64 to index
%47 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%19) : memref<?x?xf32>{%24, %44}
      %base_buffer_4, %offset_5, %sizes_6:2, %strides_7:2 = memref.extract_strided_metadata %47 : memref<?x?xf32> -> memref<f32>, index, index, index, index, index
      call @mlp_external_f32_f32_f32_i32_i32_i32(%base_buffer, %c0, %base_buffer_0, %c0, %base_buffer_4, %c0, %2, %3, %4) : (memref<f32>, index, memref<f32>, index, memref<f32>, index, i32, i32, i32) -> ()
      return
 ```
 However, at runtime I do notice that the second call, has same result and lhs buffer

**Comment by MaheshRavishankar** [comment]
> It is worth noting though that the write buffer has an offset given to it
> 
> ```
>       %0 = hal.interface.constant.load[0] : i32
>       %1 = hal.interface.constant.load[1] : i32
>       %15 = arith.extui %0 : i32 to i64
>       %16 = arith.extui %1 : i32 to i64
>       %17 = arith.shli %16, %c32_i64 : i64
>       %18 = arith.ori %15, %17 : i64
>       %19 = arith.index_castui %18 {stream.alignment = 64 : index} : i64 to index
> %47 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%19) : memref<?x?xf32>{%24, %44}
>       %base_buffer_4, %offset_5, %sizes_6:2, %strides_7:2 = memref.extract_strided_metadata %47 : memref<?x?xf32> -> memref<f32>, index, index, index, index, index
>       call @mlp_external_f32_f32_f32_i32_i32_i32(%base_buffer, %c0, %base_buffer_0, %c0, %base_buffer_4, %c0, %2, %3, %4) : (memref<f32>, index, memref<f32>, index, memref<f32>, index, i32, i32, i32) -> ()
>       return
> ```
> 
> However, at runtime I do notice that the second call, has same result and lhs buffer

Looking at the gist, this is before a `FuseDispatchBindings`

```
    %17 = stream.cmd.execute await(%16) => with(%4 as %arg2: !stream.resource<external>{%3}, %9 as %arg3: !stream.resource<external>{%8}, %result as %arg4: !stream.resource<external>{%13}, %result_0 as %arg5: !stream.resource<transient>{%15}) {
      stream.cmd.dispatch @mlp_external_f32_f32_f32_i32_i32_i32_executable::@mlp_external_f32_f32_f32_i32_i32_i32_entry_point(%10, %11, %12, %0, %1, %5, %6, %0, %6 : i32, i32, i32, index, index, index, index, index, index) {
        ro %arg2[%c0 for %3] : !stream.resource<external>{%3},
        ro %arg3[%c0 for %8] : !stream.resource<external>{%8},
        wo %arg5[%c0 for %13] : !stream.resource<transient>{%15}
      }
      stream.cmd.dispatch @mlp_external_f32_f32_f32_i32_i32_i32_executable::@mlp_external_f32_f32_f32_i32_i32_i32_entry_point(%10, %11, %11, %0, %6, %5, %6, %0, %6 : i32, i32, i32, index, index, index, index, index, index) {
        ro %arg5[%c0 for %13] : !stream.resource<transient>{%15},
        ro %arg3[%c0 for %8] : !stream.resource<external>{%8},
        wo %arg5[%14 for %13] : !stream.resource<transient>{%15}
      }
      stream.cmd.dispatch @mlp_invocation_dispatch_0::@mlp_invocation_dispatch_0_generic_DxD_f32[%0, %6](%0, %6 : index, index) {
        ro %arg5[%14 for %13] : !stream.resource<transient>{%15},
        wo %arg4[%c0 for %13] : !stream.resource<external>{%13}
      }
    } => !stream.timepoint
```

and this is after

```
    %17 = stream.cmd.execute await(%16) => with(%4 as %arg2: !stream.resource<external>{%3}, %9 as %arg3: !stream.resource<external>{%8}, %result as %arg4: !stream.resource<external>{%13}, %result_0 as %arg5: !stream.resource<transient>{%15}) {
      stream.cmd.dispatch @mlp_external_f32_f32_f32_i32_i32_i32_executable::@mlp_external_f32_f32_f32_i32_i32_i32_entry_point(%c0, %c0, %c0, %10, %11, %12, %0, %1, %5, %6, %0, %6 : index, index, index, i32, i32, i32, index, index, index, index, index, index) {
        ro %arg2[%c0_2 for %3] : !stream.resource<external>{%3},
        ro %arg3[%c0_2 for %8] : !stream.resource<external>{%8},
        wo %arg5[%c0_2 for %15] : !stream.resource<transient>{%15}
      }
      stream.cmd.dispatch @mlp_external_f32_f32_f32_i32_i32_i32_executable::@mlp_external_f32_f32_f32_i32_i32_i32_entry_point(%c0, %c0, %14, %10, %11, %11, %0, %6, %5, %6, %0, %6 : index, index, index, i32, i32, i32, index, index, index, index, index, index) {
        ro %arg5[%c0_2 for %15] : !stream.resource<transient>{%15},
        ro %arg3[%c0_2 for %8] : !stream.resource<external>{%8},
        wo %arg5[%c0_2 for %15] : !stream.resource<transient>{%15}
      }
      stream.cmd.dispatch @mlp_invocation_dispatch_0::@mlp_invocation_dispatch_0_generic_DxD_f32[%0, %6](%14, %c0, %0, %6 : index, index, index, index) {
        ro %arg5[%c0_2 for %15] : !stream.resource<transient>{%15},
        wo %arg4[%c0_2 for %13] : !stream.resource<external>{%13}
      }
    } => !stream.timepoint
```

So, not sure I am reading this right, but the offset becomes 0 for the write when it wasnt zero before... 

@nirvedhmeshram  can you try setting `--iree-scheduling-optimize-bindings=false` and try . At least that will unblock us for now.

In the plugin can you check that we are getting the offset we expect and that they are being used correctly in the plugin... but if I am reading the Stream IR correctly, the offset is being set to 0

**Comment by nirvedhmeshram** [comment]
>@nirvedhmeshram can you try setting --iree-scheduling-optimize-bindings=false and try . At least that will unblock us for now.

Yes that worked!

**Comment by benvanik** [comment]
This is working as intended - the offset is passed as %14 on the second dispatch and then that should be used as the offset in the `%3 = stream.binding.subspan %arg1[%arg3] : !stream.binding -> !flow.dispatch.tensor<writeonly:tensor<?x?xf32>>{%0, %1}` (%arg3).
I'm guessing something in your pipeline is ignoring that offset.

**Comment by nirvedhmeshram** [comment]
Thanks, @MaheshRavishankar based on what Ben is saying the mistake could possibly be in our llvm lowering (gist attached)? although I would be surprised this is the only case hitting it then.
https://gist.github.com/nirvedhmeshram/79a93d6252d9f66f9aa879e153bbcfae

I will keep investigating.

**Comment by daveliddell** [comment]
This workaround works for me also!

**Comment by MaheshRavishankar** [comment]
I think the issue is here https://github.com/openxla/iree/blob/086f3f9e38d751331e0e3141ab89501192e6e2aa/compiler/src/iree/compiler/Preprocessing/Common/ApplyPDLPatterns.cpp#L90 . What I need to pass is element offset. I think since I decoupled the element and the offset and this level assuming that the lowering to LLVM will take of converting it to element offset... but maybe its not happening. I need to look at the entire code to figure it out.

@nirvedhmeshram  this is something I have looked at before and will take some time for me to get back in cache and will end up flushing my current cache. Since the work around "works" for now, feel free to drop the issue to me... I will get to it next week after i flush somethings on my plate. (of course if yo want to fix it that will be deeply appreciated)

**Comment by nirvedhmeshram** [comment]
Just want to update her that removing the upstream folder on ExtractStridedMetadataOp fixed the issue, I am seeing that for my 8x8 case the expected result offset is 64 (elements) for the second call and that is what I am seeing at runtime. I will work on sending an upstream PR.

**Comment by jpienaar** [comment]
Is there a minimal example with the before and after folding showing it becomes incorrect? Especially to be able to motivate in standalone manner that the folder is wrong.

**Comment by MaheshRavishankar** [comment]
> Is there a minimal example with the before and after folding showing it becomes incorrect? Especially to be able to motivate in standalone manner that the folder is wrong.

https://github.com/llvm/llvm-project/pull/88043#issuecomment-2044175847

**Comment by nirvedhmeshram** [comment]
fixed in https://github.com/iree-org/iree/pull/16967
