### ISSUE TITLE
Run "iree-run-mlir" occurred error "Library not loaded: @rpath/libIREECompiler.dylib"

### ISSUE THREAD

**Issue by hyv5** [iree-org/iree#16986]
### What happened?

On Apple MacOS, if install iree to a custom path
`cmake --install build --prefix /path/to/iree`

and run a command like iree-run-mlir , The following error will occur
`dyld[15441]: Library not loaded: @rpath/libIREECompiler.dylib
  Referenced from: <469D1711-4D6B-3352-BF54-328C736796EC> /path/to/iree/bin/iree-run-mlir
  Reason: tried: '@loader_path:@loader_path/../lib/libIREECompiler.dylib' (no such file), '@loader_path:@loader_path/../lib/libIREECompiler.dylib' (no such file)`

### Steps to reproduce your issue

1.  On MacOS, clone and build the iree repo
2. cmake --install build --prefix /path/to/iree
3.  run `/path/to/iree/iree-run-mlir`

### What component(s) does this issue relate to?

Other

### Version information

HEAD

**Comment by ScottTodd** [comment]
Fixed by https://github.com/openxla/iree/pull/16987
