### ISSUE TITLE
[GPU] Partial Subgroup Reduction Codegen

### ISSUE THREAD

**Issue by kuhar** [iree-org/iree#17082]
This appears in attention lowering: we would like to do subgroup reduction but only within the 16 sets of adjacent threads across the subgroup with 64 thread.

The following lowering should be efficient on gfx9:
```
%a = gpu.shuffle %val, 64, 1 down // Rotate left by 1
%a_acc = arith.add %val, %a
%b = gpu.shuffle %a_cc, 64, 2 down // Rotate left by 2
%b_acc = arith.add %a_cc, %b
%set_base = arith.and %tid, ~(0x3)
%c = gpu.shuffle %b_acc, 64, %set_base idx // Broadcast from thread base thread
```

This can be implemented through a utility builder function like `warpReduction` in `GPUUtils.cpp`.

**Comment by kuhar** [comment]
@Groverkss @qedawkins

**Comment by antiagainst** [comment]
Is this still relevant with https://github.com/iree-org/iree/issues/18142?
