### ISSUE TITLE
[DT] Move encoding attributes and set/unset_encoding ops to a separate dialect

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#17191]
The EncodingAttr, SetEncodingOp, and UnSetEncodingOp were developed in LinalgExt because we wanted to upstream them to MLIR core. However, we need to iterate on encoding more because it also impact host code (e.g., how we allocate buffers for encoding). Since they are IREE specifics now, we should move them to Util dialect. So we will be in a better state in terms of code dependency. (E.g., stream don't need to depend on LinalgExt)

To be clear, this does not mean that we don't want to upstream them. We need more time to define proper interfaces and traits for encodings. I believe that the interfaces/traits could be upstreamed once we have them more stable.

(cc @benvanik that this is on our track.)

**Comment by benvanik** [comment]
I'm a bit hesitant about putting it in util - maybe an `encoding` dialect?
(util is meant for core programming language-like concepts, while encodings are something specific to tensors used in flow/stream)

**Comment by hanhanW** [comment]
> encodings are something specific to tensors used in flow/stream

Good point! Creating a `Encoding` dialect under https://github.com/iree-org/iree/tree/main/compiler/src/iree/compiler/Dialect sounds good to me.

**Comment by hanhanW** [comment]
The main goal of the issue is to remove the deps between LinalgExt and compiler/Utils. There are many other ops in LinalgExt, and we don't want to pollute other components that depend on compiler/Utils.

https://github.com/iree-org/iree/blob/1f2837cecfeda36cbe50f1de9d086bcc991f81c2/compiler/src/iree/compiler/Utils/BUILD.bazel#L52-L53

**Comment by bjacob** [comment]
https://github.com/iree-org/iree/pull/17277
