### ISSUE TITLE
PDLL isn't enabled during llvm_byo (installed llvm/mlir) builds

### ISSUE THREAD

**Issue by IanWood1** [iree-org/iree#17233]
#17144 adds support for pdll plugins but is disabled during builds that use out of tree llvm/mlir. As noted in the PR, `MLIRPDLLParser` is not installed by llvm. An upstream change to llvm is needed to be able to install all PDLL deps. 

Here is a potential fix:
- https://github.com/llvm/llvm-project/pull/90411

At this point, I'm not sure that would fully solve the issue. There might be some issues with mlir-tblgen's ODR violations.

**Comment by jpienaar** [comment]
Does this pass with the upstream PR? (it looks sensible, but didn't try)

**Comment by MaheshRavishankar** [comment]
Same here.. looks sensible to me to do that.

**Comment by IanWood1** [comment]
Okay, I did some testing because I was having problems even with an updated upstream. For some reason, byo_llvm is able to build and link successfully but then segfaults on some of the tests. These tests aren't related to PDLL at all either.

**Comment by ScottTodd** [comment]
> For some reason, byo_llvm is able to build and link successfully but then segfaults on some of the tests. These tests aren't related to PDLL at all either.

Got logs we can look at?

**Comment by IanWood1** [comment]
> > For some reason, byo_llvm is able to build and link successfully but then segfaults on some of the tests. These tests aren't related to PDLL at all either.
> 
> Got logs we can look at?

Yep https://gist.github.com/IanWood1/c2ea38035453b8a17b9d7c8b78fb9cd6

**Comment by MaheshRavishankar** [comment]
I think byo_llvm works in very limited use cases. I expect such things to happen on mismatched LLVM versions.
