### ISSUE TITLE
Update iree for nanobind 2

### ISSUE THREAD

**Issue by hawkinsp** [iree-org/iree#17496]
### What happened?

IREE doesn't build with nanobind 2.0, released today.

**Comment by stellaraccident** [comment]
Yeah, we just discovered that and pinned to the prior version this morning. I took a todo to upgrade it but it isn't going to happen today. Also a long weekend starts now.

**Comment by stellaraccident** [comment]
https://github.com/wjakob/nanobind/issues/597

**Comment by stellaraccident** [comment]
If CI passes with the 2.0 bump, I'll go ahead and land tonight.

**Comment by stellaraccident** [comment]
Note that folks are still having some issues depending on where they are sync'd to. If on a branch that does not include #17497, then downgrade via:

```
pip install --force-reinstall 'nanobind<2'
```

If after and having issues, upgrade (HEAD should work with older versions but CI doesn't test that / I only verified lightly):

```
pip uninstall nanobind
pip install -r runtime/bindings/python/iree/runtime/build_requirements.txt
```
