### ISSUE TITLE
The rocm links in the doc is outdated

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#17560]
See the `ROCm` and `Linux` link in https://iree.dev/guides/deployment-configurations/gpu-rocm/

They are https://rocm.docs.amd.com/en/latest/deploy/linux/quick_start.html and https://www.amd.com/en/graphics/servers-solutions-rocm which are all 404 errors.

**Comment by ScottTodd** [comment]
We had some ROCm doc updates in https://github.com/iree-org/iree/pull/17029 (cc @nithinsubbiah ). I wanted to make a pass through those docs myself, but I'm still waiting on a local dev machine so I can go through the steps personally.

**Comment by nithinsubbiah** [comment]
@ScottTodd I see that the docs have been updated, can we close this?

**Comment by ScottTodd** [comment]
Yep.
