### ISSUE TITLE
Upgrade Github runner to v2.317.0 before 2024-06-28

### ISSUE THREAD

**Issue by yuennancy** [iree-org/iree#17565]
The new runner version has been released: https://github.com/actions/runner/releases/tag/v2.317.0
Past issue:  [#17174](https://github.com/iree-org/iree/issues/17174)

**Comment by ScottTodd** [comment]
All presubmit and postsubmit runners are offline. Maybe this is needed now? The previous issue (https://github.com/iree-org/iree/issues/17174) updated to v2.316.0 but there was a v2.316.1 dot release shortly afterwards: https://github.com/actions/runner/releases

**Comment by ScottTodd** [comment]
Bump to v2.316.1 was completed in https://github.com/iree-org/iree/pull/17609 so runners are back online and running jobs. Discussion [here on Discord](https://discord.com/channels/689900678990135345/1166024193599615006/1248660019092914297).

v2.317.0 upgrade is planned for today too.

**Comment by yuennancy** [comment]
This has been pushed to canary.  Will promote to prod after a few days, next week.

**Comment by yuennancy** [comment]
Push to prod complete.
