### ISSUE TITLE
(Windows/Python) -- Latest windows wheels cannot import iree.compiler.ir.Context

### ISSUE THREAD

**Issue by monorimet** [iree-org/iree#17700]
### What happened?

if anyone knows why this might be happening please help:
```
  File "C:\V\SHARK-Turbine\models\turbine_models\custom_models\sd3_inference\sd3_text_encoders.py", line 13, in <module>
    from iree.compiler.ir import Context
  File "C:\V\SHARK\shark.venv\Lib\site-packages\iree\compiler\ir.py", line 5, in <module>
    from ._mlir_libs._mlir.ir import *
  File "C:\V\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\__init__.py", line 180, in <module>
    _site_initialize()
  File "C:\V\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\__init__.py", line 78, in _site_initialize
    from ._mlir import ir
    
ImportError: DLL load failed while importing _mlir: A dynamic link library (DLL) initialization routine failed.
```
this happens on IREE main with windows wheels, I suspect the builders (there were some changes to the windows 2022 images recently) but I don't know much more

i.e. `pip install iree-compiler iree-runtime --pre -f https://iree.dev/pip-release-links.html` and run:
```
python

> from iree.compiler.ir import Context
```
should reproduce the issue

### What component(s) does this issue relate to?

Python, Compiler

### Version information

iree-compiler-20240618.928 iree-runtime-20240618.928

Windows 11 Pro

### Additional context

Source build works. Started seeing this around monday of this week. (06/17/2024) roughly

**Comment by ScottTodd** [comment]
> Source build works. Started seeing this around monday of this week. (06/17/2024) roughly

If you can point to an exact release before/after, that would help. GitHub did update the runner image recently, breaking effectively all software built using msvc. That was partially fixed though.

**Comment by ScottTodd** [comment]
I can't repro on
* IREE compiler version 20240619.929 @ d792d2483a9d5d875a0f03b57c9d4f98e072c300
* Python 3.11.2
*
  ```
  Edition	Windows 10 Home
  Version	22H2
  Installed on	‎3/‎12/‎2021
  OS build	19045.4529
  Experience	Windows Feature Experience Pack 1000.19058.1000.0
  ```
  
Steps tried:
```
python -m venv .venv
.venv\Scripts\activate.bat
python -m pip install --find-links https://iree.dev/pip-release-links.html --upgrade iree-compiler iree-runtime
python -c "from iree.compiler.ir import Context"
```

Can you try from a fresh venv?

**Comment by stellaraccident** [comment]
Might be VC redistributable version or something. The bit about a doll init procedure points to something low level like that.

**Comment by ScottTodd** [comment]
There are some DLL-related issues and workarounds posted on https://github.com/actions/runner-images/issues/10004 that might provide some other clues.

We should probably switch our release builders to machines we have more control over the toolchain on, or have the release job explicitly install and configure MSVC. GitHub appears pretty committed to rolling forward with increasingly unstable and untested runner images :/

**Comment by snnn** [comment]
The runner image has nothing wrong. The problem is about how to distribute the built packages. 
@monorimet , please tell us if you were using conda. If yes, you need to check if you have installed the "vs2015_runtime" package. If yes,  you need to get a newer version from conda-forge.
```
 conda install conda-forge::vs2015_runtime
```
CPython(from python.org) does not have this issue. 
You also need to install the latest VC++ runtime from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170. The latest version was released a few weeks ago. If you didn't reinstall it recently, please do so.

**Comment by monorimet** [comment]
Not using conda, will blow away my venv and try again.

**Comment by ScottTodd** [comment]
When we build our releases for Linux, we use a Dockerfile (based on manylinux, https://github.com/pypa/manylinux, to work across multiple distros) with a pinned version of the clang compiler toolchain and other deps. For our Windows packages we inherit most of the deps from the runner: https://github.com/iree-org/iree/blob/199790292101bed6128c1db2e1bb1cacf2d6ab54/.github/workflows/build_package.yml#L119-L125 (the [`install_windows_deps.ps1`](https://github.com/iree-org/iree/blob/main/build_tools/python_deploy/install_windows_deps.ps1) script just installs a few specific python versions and some pip packages).

I'm thinking we could at least pin to a MSVC version to stabilize that part of our release process, or we could use a self-hosted runner (that would help with build times too).

**Comment by monorimet** [comment]
This was a weird fix (not really, just had a bit of trouble), I'll elaborate exactly what I did:

Note: Using VS Code / VS 2022

I first tried `deactivate`, `rm my_venv` and start fresh env. This did not solve the issue.

Then, I installed latest MSVC redist from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 and tried again. Still same issue.

Then, in vscode, I updated to a pre-release of the C/C++ extension pack, reinstalled Visual Studio 2022, and restarted my computer. Deleted venv and tried again.

Now it works! Must have been the VC redist, and I just needed to reboot a few things to get the VC redist synced up with my IDE.

**Comment by monorimet** [comment]
Closing this issue for now, as an update to my VC redist, and refreshing IDEs fixes the problem. Thanks @ScottTodd and @stellaraccident

**Comment by stellaraccident** [comment]
We need to switch to controlled windows runners for releases and then manage the installation. 

I don't like just leaving this as some magical dep was fixed, but tracking it down further won't actually move is towards the good fix state...
