### ISSUE TITLE
Update docker images base and base-arm64 and their dependencies

### ISSUE THREAD

**Issue by sogartar** [iree-org/iree#17715]
Can someone update the IREE docker images at `gcr.io/iree-oss/base`, `gcr.io/iree-oss/base-arm64` and the ones that depend on them, namely `nvidia`, `riscv` and `android`? I don't have permissions for that.

**Comment by ScottTodd** [comment]
Were the updates in https://github.com/iree-org/iree/pull/17661 and https://github.com/iree-org/iree/pull/17568 not recent enough?

Why do you want these images updated? (Anything new should be migrating to different images - please help with https://github.com/iree-org/iree/issues/15332 if this is important to you)

**Comment by sogartar** [comment]
> Were the updates in https://github.com/iree-org/iree/pull/17661 and https://github.com/iree-org/iree/pull/17568 not recent enough?
> @ScottTodd

They did not update `gcr.io/iree-oss/base` and `gcr.io/iree-oss/base-arm64`.

I want them for this PR #17433, which installs stuff in CI jobs post docker image generation that require sudo.

**Comment by ScottTodd** [comment]
Dockerfiles were moved to https://github.com/iree-org/base-docker-images. No extra permissions are needed to make changes and publish them now.
