### ISSUE TITLE
why torch-to-iree pass generate func named main$async automatically?

### ISSUE THREAD

**Issue by bailuan** [iree-org/iree#17776]
### What happened?

When I try to use iree-opt --torch-to-iree to transform ir from torch to linalg. I found my function named main becomes main$async automatically. What should I do if I just want a function named main but not a async function named main$async?

### What component(s) does this issue relate to?

MLIR

**Comment by ScottTodd** [comment]
If you _just_ want to convert from torch to linalg, use `torch-mlir-opt` from https://github.com/llvm/torch-mlir. IREE's use of torch-mlir is in service of IREE compilation and may introduce other dialects as needed for that purpose.

The `--torch-to-iree` pass should be creating _both_ a function named `main` _and_ a function named `main$async`. That's documented here: https://github.com/iree-org/iree/blob/main/compiler/plugins/input/Torch/InputConversion/FuncConversion.cpp and tested here: https://github.com/iree-org/iree/blob/main/compiler/plugins/input/Torch/InputConversion/test/func_conversion.mlir.

**Comment by bailuan** [comment]
THX, another question please, what should I do if I just want use python script to transform IR but not compile from source to use torch-mlir-opt?

**Comment by bailuan** [comment]
I have tried to conpile from source by using command line suggested: `cmake -GNinja -Bbuild \
  -DCMAKE_BUILD_TYPE=Release \
  -DPython3_FIND_VIRTUALENV=ONLY \
  -DLLVM_ENABLE_PROJECTS=mlir \
  -DLLVM_EXTERNAL_PROJECTS="torch-mlir" \
  -DLLVM_EXTERNAL_TORCH_MLIR_SOURCE_DIR="$PWD" \
  -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
  -DLLVM_TARGETS_TO_BUILD=host \
  externals/llvm-project/llvm`, but not find the torch-mlir-opt in build/bin/.

**Comment by ScottTodd** [comment]
> THX, another question please, what should I do if I just want use python script to transform IR but not compile from source to use torch-mlir-opt?

The IREE Python bindings expose some of the MLIR Python bindings (https://mlir.llvm.org/docs/Bindings/Python/) via `from iree.compiler import ir`. See https://iree.dev/reference/bindings/python/#installing-iree-packages for installation instructions. Upstream MLIR and torch-mlir also build some subset of the python bindings into packages.

> I have tried to conpile from source by using command line suggested: `cmake -GNinja -Bbuild \ -DCMAKE_BUILD_TYPE=Release \ -DPython3_FIND_VIRTUALENV=ONLY \ -DLLVM_ENABLE_PROJECTS=mlir \ -DLLVM_EXTERNAL_PROJECTS="torch-mlir" \ -DLLVM_EXTERNAL_TORCH_MLIR_SOURCE_DIR="$PWD" \ -DMLIR_ENABLE_BINDINGS_PYTHON=ON \ -DLLVM_TARGETS_TO_BUILD=host \ externals/llvm-project/llvm`, but not find the torch-mlir-opt in build/bin/.

Please direct torch-mlir support questions to torch-mlir. Did you build after configuring? See https://github.com/llvm/torch-mlir/blob/main/docs/development.md#build-commands

**Comment by bailuan** [comment]
ok, I will try this.
