### ISSUE TITLE
Update GCP GitHub Actions runners to use default runner group

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#17893]
We were using "self-hosted runner groups" (https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/managing-access-to-self-hosted-runners-using-groups) to organize our self-hosted runners. We just switched from the GitHub "enterprise" plan but back to the "free" tier, where runner groups are not available. All but the "Default" runner group has been disabled as a result. 

I manually moved self-hosted runners from the "presubmit" and "postsubmit" runner groups back to the "Default" group to keep them working, but the autoscaling / ephemeral GCP runners were added back to the disabled groups.

Looks like the groups are set in https://github.com/iree-org/iree/blob/main/build_tools/github_actions/runner/gcp/create_templates.sh and also used in https://github.com/iree-org/iree/blob/main/build_tools/github_actions/runner/config/register.sh.

We may want to keep the group labels, or we could just get rid of them entirely. Separate groups allow us to prevent presubmit jobs from starving postsubmit jobs and vice-versa, as well as limit which runners touch unsubmitted code.
* For context, here are example labels from a runner: `os-family=Linux self-hosted Linux X64 environment=prod runner-group=postsubmit trust=basic cpu-platform=Intel Cascade Lake machine-type=c2-standard-60 c2s601t zone=us-west1-a runner-version=2.317.0`
* Code integrity (not mixing minimally trusted code with fully trusted code) matters the most on release builds since we instruct users to download nightlies from github releases and promote releases from GitHub releases directly to pypi. The `build_package.yml` workflow recently switched from using self-hosted runners to using mostly github-hosted runners: https://github.com/iree-org/iree/blob/main/.github/workflows/build_package.yml . Self-hosted runners are still used there for linux-aarch64.

**Comment by yuennancy** [comment]
What's the ask? To change the group to Default in the scripts and keep the labels?

**Comment by ScottTodd** [comment]
Yeah, that's probably where I'd start.

As we rework CI jobs we might also want to get rid of the distinction between a presubmit runner and a postsubmit runner.

**Comment by ScottTodd** [comment]
I guess we could also keep the code unchanged and continue to use the "disabled" groups, assuming GitHub doesn't make them nonfunctional 🤔

**Comment by ScottTodd** [comment]
Most GCP runners are disabled now (see https://github.com/iree-org/iree/issues/18238). The runner groups are nearly empty (just ARM64 runners in there now)

**Comment by ScottTodd** [comment]
FYI: https://github.blog/changelog/2024-10-17-actions-runner-groups-now-available-for-organizations-on-free-plan/
