### ISSUE TITLE
[runtime][hip][cuda] Failures don't propagate to semaphores that need to be signaled

### ISSUE THREAD

**Issue by sogartar** [iree-org/iree#17962]
I noticed that in the HIP and CUDA drivers when an execution operation fails, the list of semaphores that are to be signaled on completion are not failed. This will then cause downstream semaphores to hang. They will be waiting on the not properly failed semaphore, which will never signal.
I am preparing a patch for this.

**Comment by sogartar** [comment]
@AWoloszyn, FYI.

**Comment by ScottTodd** [comment]
See also https://github.com/iree-org/iree/issues/17834#issuecomment-2218494783 and [this discussion on Discord](https://discord.com/channels/689900678990135345/689906000043573354/1260322908077686927) for how we might write CTS tests for failure signaling.

**Comment by sogartar** [comment]
#18095 fixes this. `iree-run-runtime` (the VM) would not give a good error message when a HAL fence await fails. It will not query the failed semaphore(s) for their errors and show them. At least we will not hang forever.
