### ISSUE TITLE
Land Horizontal contraction fusion changes into IREE main

### ISSUE THREAD

**Issue by MaheshRavishankar** [iree-org/iree#18009]
Following changes need to land in IREE

https://github.com/llvm/llvm-project/pull/98995
https://github.com/iree-org/iree/commit/fa5f5f4f02a59a9d97ba212b8e188014b484c673
https://github.com/iree-org/iree/commit/a184840225b76a62a5cecc18ebb18578da12bbaf
https://github.com/iree-org/iree/commit/d039e36008784434a4d512b28e9ce306ee56f20e

**Comment by hanhanW** [comment]
Will we turn it on by default?

**Comment by MaheshRavishankar** [comment]
Not at this time

**Comment by MaheshRavishankar** [comment]
This is landed in main.
