### ISSUE TITLE
pre-commit bazel_to_cmake check sometimes fails

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#18014]
### What happened?

See logs on https://github.com/iree-org/iree/actions/runs/10113405113/job/27969707119?pr=18010#step:4:73
```
Run bazel_to_cmake.py....................................................Failed
- hook id: bazel_to_cmake
- files were modified by this hook

Using repo root /home/runner/work/iree/iree
1 CMakeLists.txt files were updated, 7 were skipped, and 1[73](https://github.com/iree-org/iree/actions/runs/10113405113/job/27969707119?pr=18010#step:4:78) required no change.
Using repo root /home/runner/work/iree/iree
0 CMakeLists.txt files were updated, 14 were skipped, and 153 required no change.
Using repo root /home/runner/work/iree/iree
0 CMakeLists.txt files were updated, 14 were skipped, and 160 required no change.
Using repo root /home/runner/work/iree/iree
0 CMakeLists.txt files were updated, 19 were skipped, and 155 required no change.

Check for excessively long path lengths..............(no files to check)Skipped
Check Bazel file names...............................(no files to check)Skipped
Run generate_cmake_e2e_test_artifacts_suite.py...........................Passed
Run generate_cmake_e2e_model_tests.py....................................Passed
pre-commit hook(s) made changes.
If you are seeing this message in CI, reproduce locally with: `pre-commit run --all-files`.
To run `pre-commit` as part of git workflow, use `pre-commit install`.
All changes made by hooks:
diff --git a/tests/e2e/matmul/CMakeLists.txt b/tests/e2e/matmul/CMakeLists.txt
index 0556e75..5146d[74](https://github.com/iree-org/iree/actions/runs/10113405113/job/27969707119?pr=18010#step:4:79) 100644
--- a/tests/e2e/matmul/CMakeLists.txt
+++ b/tests/e2e/matmul/CMakeLists.txt
@@ -2252,289 +2252,3 @@ iree_generated_e2e_runner_test(
 )
 
 ### BAZEL_TO_CMAKE_PRESERVES_ALL_CONTENT_BELOW_THIS_LINE ###
-
-# To distinguish between CDNA(gfx9) and RDNA3(gfx11)
-if(IREE_HIP_TEST_TARGET_CHIP MATCHES "^gfx9")
-
-unset(IREE_HIP_TEST_COMPILER_FLAGS)
-list(APPEND IREE_HIP_TEST_COMPILER_FLAGS
-  "--iree-rocm-target-chip=${IREE_HIP_TEST_TARGET_CHIP}"
-)
```

### Steps to reproduce your issue

Not sure. Retrying the job works, so something is flaky. Maybe a race condition.

### What component(s) does this issue relate to?

Other

### Version information

https://github.com/iree-org/iree/commit/456d80c51930ccc03ce0488e98238e5e0a14b403

### Additional context

* bazel_to_cmake pre-commit code was changed in https://github.com/iree-org/iree/pull/17599
* pre-commit docs: https://pre-commit.com/
* pre-commit expects to run on individual files, but bazel_to_cmake works with both a `BUILD.bazel` file _and_ a `CMakeLists.txt` file

**Comment by ScottTodd** [comment]
Another failure: https://github.com/iree-org/iree/actions/runs/10114192081/job/27972273912?pr=17987

**Comment by benvanik** [comment]
I just noticed that and WTF'ed :P

**Comment by ScottTodd** [comment]
![image](https://media1.tenor.com/m/zrNT5Yi-FkIAAAAC/you-didnt-see-anything-penguins-of-madagascar.gif)

**Comment by ScottTodd** [comment]
Another report: https://github.com/iree-org/iree/issues/19365

I suspect there is a race condition since pre-commit checks are usually run in parallel across all files, modifying each file in-place as needed. For the bazel-to-cmake check, we had the option of always running it, or only running it when relevant files are changed... on each file: https://github.com/iree-org/iree/blob/939984cf4812d07feb962887cb15972432049f1a/.pre-commit-config.yaml#L86-L93 Since the CMake files can have extra text before and after the generated sections, editing a file while another script run is trying to read it could cause issues.

Race between when the CMake file is read: https://github.com/iree-org/iree/blob/939984cf4812d07feb962887cb15972432049f1a/build_tools/bazel_to_cmake/bazel_to_cmake.py#L270-L276 and when it is written again? https://github.com/iree-org/iree/blob/939984cf4812d07feb962887cb15972432049f1a/build_tools/bazel_to_cmake/bazel_to_cmake.py#L327-L332

Maybe we can run the check once for all modified BUILD.bazel files then once again for all modified CMakeLists.txt files, so there isn't a chance for the script to be run twice at the same time on the same pair of files 🤔

**Comment by ScottTodd** [comment]
Another (error prone) option would be to try dodging any race conditions by checking if the files are open before running the conversion process. Python can portably check if a file is open in the current process, and operating system-specific code can be used to check if a file is open by another process.

Maybe we can reproduce this bug by increasing the file sizes or adding some `sleep()` calls to slow down the code

**Comment by bjacob** [comment]
The race condition theory would mesh well with the finding in #19365 that the file gets truncated to exactly 16,384 bytes == 2^14. There's nothing at application level that would make that value significant, but it would be a typical manifestation of a race between OS-level things copying data by power-of-two sized chunks.

But I don't see how a race condition is possible within this Python function, which does a read and then a write. A race condition has to be between different threads, or processes.

I would look rather in the direction of a race between the output write of this Python code, and the subsequent read by the CI/lint script checking the results (e.g. executing `git diff` or some such).

**Comment by ScottTodd** [comment]
pre-commit is running bazel_to_cmake.py on all affected files, in parallel, just like it would run clang-format on C++ files. The difference here is that when clang-format runs on a .h file, it edits that single file in-place. When we run on a BUILD.bazel file we open both that file _and_ the CMakeLists.txt... but we also do the same when running on a CMakeLists.txt file, so two processes can both be trying to convert from the same BUILD.bazel to the same CMakeLists.txt.

**Comment by bjacob** [comment]
Oh i see.

**Comment by bjacob** [comment]
And these two `bazel_to_cmake.py` processes would actually be running in parallel?

**Comment by bjacob** [comment]
Sounds like we need to implement the standard pattern for atomically replacing a file's contents: write the new contents to a temporary file, then rename it to the destination path.

**Comment by ScottTodd** [comment]
Marking tentatively fixed.
