### ISSUE TITLE
[vulkan] Update default RDNA GPU subgroup size to 32

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#18037]
RDNA GPUs support two modes, wave32 and wave64. Right now in Vulkan we default to use wave64, following what `vulkaninfo` would report for RDNA GPUs, [except when we target matmul](https://github.com/iree-org/iree/blob/45323df861d2386073ff0d3aa3fdebad14e164b2/compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp#L909-L911). So that's a bit inconsistency. Further, when we targeting RDNA GPUs via HIP, the default is wave32. So another mismatch here. These differences causes quite some [special cases](https://github.com/iree-org/iree/blob/45323df861d2386073ff0d3aa3fdebad14e164b2/compiler/src/iree/compiler/Codegen/Dialect/GPU/IR/IREEGPUAttrs.td#L376-L379) in the compiler. 

We should consider changing the Vulkan side to use wave32 mode entirely to avoid all these inconsistencies and special cases. wave64 is more for graphics and we care more about compute. Fixing this involves also look at what tests would fail and update them.

**Comment by nithinsubbiah** [comment]
completed with https://github.com/iree-org/iree/pull/18207
