### ISSUE TITLE
Reduce verbosity of gcloud transfers in CI logs

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#18042]
In CI logs such as https://github.com/iree-org/iree/actions/runs/10164585273/job/28113039308 under `Downloading install dir archive` we have verbose logging of every little kilobyte that gets transferred. In the above log, that amounts to 67,000 lines or about 5 MB.

Apparently `gcloud` has command line flags such as `--verbosity` or perhaps `--quiet` to control these things. Is there a way that we can set them globally though rather than having to think about it at every place in the CI setup?

**Comment by ScottTodd** [comment]
I'm removing all those cloud transfers. The ones you linked don't exist as of https://github.com/iree-org/iree/commit/2bef72007dd975fa7469d2b1142378d037610981 :)

**Comment by ScottTodd** [comment]
Yeah the only job remaining that uses the "install" dir is `build_and_test_android`, and that uses the gcloud CLI instead of wget:
https://github.com/iree-org/iree/actions/runs/10165055203/job/28112516463#step:5:11
```
gcloud storage cp "${INSTALL_DIR_GCS_ARTIFACT}" "${INSTALL_DIR_ARCHIVE}"
Copying gs://iree-github-actions-postsubmit-artifacts/10165055203/1/install_dir.tar.zst to file://install_dir.tar.zst
  
....................

Average throughput: 933.8MiB/s
```
