### ISSUE TITLE
Bufferization issue with redundant allocation and copy (part 2)

### ISSUE THREAD

**Issue by yzhang93** [iree-org/iree#18075]
### What happened?

There seems to be some issue in comprehensive-bufferization that creates redundant data allocation and copy. 

Here, with the same lowering pipeline, matmul shape 64x64x64 has [redundant allocation and copies generated](https://gist.github.com/yzhang93/3f07bbb7f6de62e8bf9ed3b02dceb00d#file-gistfile1-txt-L253), while matmul shape 128x128x256 doesn't.

[IR dump for 64x64x64](https://gist.github.com/yzhang93/3f07bbb7f6de62e8bf9ed3b02dceb00d)
[IR dump for 128x128x256](https://gist.github.com/yzhang93/624b6e5126156be23b4c6f74cd811b39)

By comparing the IR, I think the difference might be that unpack results are written to shared_outs %7 for 64x64x64.

```
%8 = scf.forall (%arg0, %arg1) = (0, 0) to (64, 64) step (64, 64) shared_outs(%arg2 = %7) -> (tensor<64x64xi32>) {
    ...
    ...
    %unpack = tensor.unpack %18#2 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %7 : tensor<2x2x32x32xi32> -> tensor<64x64xi32>
    scf.forall.in_parallel {
      tensor.parallel_insert_slice %unpack into %arg2[%arg0, %arg1] [64, 64] [1, 1] : tensor<64x64xi32> into tensor<64x64xi32>
    }
  } {mapping = [#gpu.block<y>, #gpu.block<x>]}
```

While for 128x128x256, the unpack results are written to a extracted_slice.

```
%8 = scf.forall (%arg0, %arg1) = (0, 0) to (128, 128) step (64, 64) shared_outs(%arg2 = %7) -> (tensor<128x128xi32>) {
    %extracted_slice_7 = tensor.extract_slice %arg2[%arg0, %arg1] [64, 64] [1, 1] : tensor<128x128xi32> to tensor<64x64xi32>
    ...
    ...
    %unpack = tensor.unpack %19#2 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %extracted_slice_7 : tensor<2x2x32x32xi32> -> tensor<64x64xi32>
    scf.forall.in_parallel {
      tensor.parallel_insert_slice %unpack into %arg2[%arg0, %arg1] [64, 64] [1, 1] : tensor<64x64xi32> into tensor<128x128xi32>
    }
  } {mapping = [#gpu.block<y>, #gpu.block<x>]}
```

Another relevant issue was reported https://github.com/iree-org/iree/issues/17571.

CC: @MaheshRavishankar Could you help take a look and give some suggestions?

**Comment by yzhang93** [comment]
The above issue happened with matmul and elementwise fusion. I also looked at the IR for pure matmul 64x64x64, and there is no such problem, and the generated IR is as

```
%6 = scf.forall (%arg0, %arg1) = (0, 0) to (64, 64) step (64, 64) shared_outs(%arg2 = %5) -> (tensor<64x64xi32>) {
    %extracted_slice_6 = tensor.extract_slice %arg2[%arg0, %arg1] [64, 64] [1, 1] : tensor<64x64xi32> to tensor<64x64xi32>
    ...
    ...
    %unpack = tensor.unpack %14#1 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %extracted_slice_6 : tensor<2x2x32x32xi32> -> tensor<64x64xi32>
    scf.forall.in_parallel {
      tensor.parallel_insert_slice %unpack into %arg2[%arg0, %arg1] [64, 64] [1, 1] : tensor<64x64xi32> into tensor<64x64xi32>
    }
  } {mapping = [#gpu.block<y>, #gpu.block<x>]} 
```

**Comment by MaheshRavishankar** [comment]
Its a bug in bufferization. Looks like if there is no `extract_slice` of `%arg2` in the loop body (and it is used directly in the `tensor.parallel_insert_slice` it breaks some analysis in bufferization. I'd suggest just filing this issue on LLVM upstream and get input from Matthias on how to fix that.
To check that this is indeed a missed analysis in bufferization, just add a no-op `tensor.extract_slice` (so a `tensor.extract_slice %arg2[0, 0] [64, 64] [1, 1]` with the loop body of the `scf.forall` and check if it bufferizes correctly

**Comment by yzhang93** [comment]
> Its a bug in bufferization. Looks like if there is no `extract_slice` of `%arg2` in the loop body (and it is used directly in the `tensor.parallel_insert_slice` it breaks some analysis in bufferization. I'd suggest just filing this issue on LLVM upstream and get input from Matthias on how to fix that. To check that this is indeed a missed analysis in bufferization, just add a no-op `tensor.extract_slice` (so a `tensor.extract_slice %arg2[0, 0] [64, 64] [1, 1]` with the loop body of the `scf.forall` and check if it bufferizes correctly

I tried as suggested when the no-op `tensor.extract_slice` is added to the body of `scf.forall`, the IR after bufferization is correct without redundant allocations and copies. I have filed an issue upstream https://github.com/llvm/llvm-project/issues/101451.

**Comment by yzhang93** [comment]
@MaheshRavishankar Here is the dump after all https://gist.github.com/yzhang93/55dc45195b341af94e9f2bb316101b7c

**Comment by Abhishek-Varma** [comment]
Hi @yzhang93 - so I tried adding this trivial patch upstream https://github.com/llvm/llvm-project/pull/101755

Here is the e2e IR log with it : [e2e matmul + elemwise log after/before](https://gist.github.com/Abhishek-Varma/2db84354c0205fb63b77927a1c2e3bc9). I don't see the redundant copy with it anymore. Could you also confirm this at your end? (I can accordingly either modify the upstream patch or go ahead with merging it).

**Comment by yzhang93** [comment]
@Abhishek-Varma The IR log looks correct. Thanks for fixing the issue!

**Comment by Abhishek-Varma** [comment]
Closing as https://github.com/llvm/llvm-project/pull/101755 fixes this.
