### ISSUE TITLE
`arith.remsi` causes floating point exception on `llvm-cpu`

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#18085]
It appears there is a bug with lowering `arith.remsi` to `x86`. Not entirely certain where in the pipeline this goes wrong but it results in a floating point exception.

Repro IR:

```
module {
  util.func public @test_mod_mixed_sign_int32(%arg0: tensor<6xi32>, %arg1: tensor<6xi32>) -> tensor<6xi32> {
    %2 = tensor.empty() : tensor<6xi32>
    %3 = linalg.generic {indexing_maps = [affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>], iterator_types = ["parallel"]} ins(%arg0, %arg1 : tensor<6xi32>, tensor<6xi32>) outs(%2 : tensor<6xi32>) {
    ^bb0(%in: i32, %in_0: i32, %out: i32):
      %6 = arith.remsi %in, %in_0 : i32
      linalg.yield %6 : i32
    } -> tensor<6xi32>
    util.return %3 : tensor<6xi32>
  }
}
```

Command:
```
iree-compile model.mlir --iree-hal-target-backends=llvm-cpu | iree-run-module --module=- --input=6xi32=1111 --input=6xi32=1111
```

Result
```
EXEC @test_mod_mixed_sign_int32
Floating point exception (core dumped)
```

**Comment by MaheshRavishankar** [comment]
@lialan  could you please take a look

**Comment by lialan** [comment]
Will do shortly @MaheshRavishankar

**Comment by lialan** [comment]
Tentative analysis:
`%6 = arith.remsi %in, %in_0 : i32` is converted to `%11 = arith.remsi %9, %10 : vector<4xi32>` after vectorization, which later lowered to LLVM as `%41 = llvm.srem %38, %40  : vector<4xi32>`

`iree-run-module` failed with `[1]    38084 floating point exception (core dumped)` but the signal was actually `* thread #3, name = 'iree-worker-0', stop reason = signal SIGFPE: integer divide by zero`

Suspect codegen of `srem` with vector type is problematic. Investigating.

**Comment by lialan** [comment]
Instructions generated for a vector `llvm.srem` is as follows:
```
   0x7ffff7fb953d:      movss  0xc(%rax),%xmm4
   0x7ffff7fb9542:      shufps $0xe4,%xmm3,%xmm4
   0x7ffff7fb9546:      shufps $0x24,%xmm4,%xmm3
   0x7ffff7fb954a:      pshufd $0xff,%xmm2,%xmm4
   0x7ffff7fb954f:      movd   %xmm4,%eax
   0x7ffff7fb9553:      pshufd $0xff,%xmm3,%xmm4
   0x7ffff7fb9558:      movd   %xmm4,%ebx
   0x7ffff7fb955c:      cltd
=> 0x7ffff7fb955d:      idiv   %ebx
   0x7ffff7fb955f:      movd   %edx,%xmm4
...
...
```
the integer divide by zero is because the loaded values in `$ebx` is 0. 

checking up further, the first instruction shown here is trying to load from memory `0xc(%rax)`, however `%rax` is null at the point of signal:
```
(gdb) i r $rax
rax            0x0                 0
```

Suspect a mistake of loading wrong values.

**Comment by lialan** [comment]
disabling generic vectorization `iree-codegen-generic-vectorization` to avoid generating operations on `vector<4xi32>` will make the bug go away.

**Comment by hanhanW** [comment]
I feel that the issues are from masking. So we break the 6xi32 into two 4xi32 vectors, and the last one has to handle the corner case. It loads `[v_0, v_1, 0, 0]` for LHS and `[v_2, v_3, 0, 0]` for RHS, and the divisor becomes zeros which could lead to UB. I don't have a solution right now, I need to think about it.

**Comment by lialan** [comment]
@hanhanW Confirm it is the case:
```
  %28 = getelementptr i32, ptr %9, i64 %20, !dbg !81
  %29 = tail call <4 x i32> @llvm.masked.load.v4i32.p0(ptr %28, i32 4, <4 x i1> %25, <4 x i32> zeroinitializer), !dbg !81
  %30 = srem <4 x i32> %27, %29, !dbg !81
 ```
 
 where vectorization actually loads zero as divider due to mask being zero, and the `zeroinitializer`.
 
 To fix this, either pad values before hand, or do not allow vectorized part to go above boundary. 

To go with the option that do not access out of boundary, I assume we need to fix lowering of `linalg.generic` to `scf.for` and handle the residual part separately.

**Comment by lialan** [comment]
The fundamental issue is that: when doing masked load, have to guarantee the consumer of the loaded value is also masked. In this case, `llvm.srem` is not masked.

Well, maybe you can get away with most of that, but only not for `s/udiv` and `s/urem` operations. given we are not storing the masked values, simply avoid using `zeroinitializer` in the masked loads would suffice in such case:
```
%29 = tail call <4 x i32> @llvm.masked.load.v4i32.p0(ptr %28, i32 4, <4 x i1> %25, <4 x i32> <i32 1, i32 1, i32 1, i32 1>), !dbg !81

```

**Comment by lialan** [comment]
peeling works. Here is the generated IR:
```
  %3 = vector.load %0[%c0] : memref<6xi32>, vector<4xi32>
  %4 = vector.load %1[%c0] : memref<6xi32>, vector<4xi32>
  %5 = arith.remsi %3, %4 : vector<4xi32>
  vector.store %5, %2[%c0] : memref<6xi32>, vector<4xi32>
  %6 = vector.load %0[%c4] : memref<6xi32>, vector<2xi32>
  %7 = vector.load %1[%c4] : memref<6xi32>, vector<2xi32>
  %8 = arith.remsi %6, %7 : vector<2xi32>
  vector.store %8, %2[%c4] : memref<6xi32>, vector<2xi32>
```
A `vector<2xi32>` type is then expanded into scalar type operation before lowering to LLVM IR.

Option to add: `--iree-llvmcpu-vector-pproc-strategy=peel`

**Comment by lialan** [comment]
Patch in: https://github.com/iree-org/iree/pull/18146
