### ISSUE TITLE
How to get the name of an operator's result?

### ISSUE THREAD

**Issue by bailuan** [iree-org/iree#18091]
### Request description

I noticed in iree/third_party/llvm-project/mlir/lib/TableGen/Operator.cpp there is an api looks like:
`
StringRef Operator::getResultName(int index) const {
  DagInit *results = def.getValueAsDag("results");
  return results->getArgNameStr(index);
}`

why I can't use it, compiled error : " error: no member named 'getResultName' in 'mlir::Operation'"?

**Comment by benvanik** [comment]
Those are two different things.

**Comment by ScottTodd** [comment]
This is a question for upstream LLVM / MLIR. The "toy tutorial" may help introduce concepts: https://mlir.llvm.org/docs/Tutorials/Toy/ . Beyond that, I'd recommend using an editor with code completion / IntelliSense to see which objects/classes have which functions available.

**Comment by bailuan** [comment]
thanks, let me take a look.
