### ISSUE TITLE
Move dispatch region formation & preprocessing out of Flow

### ISSUE THREAD

**Issue by IanWood1** [iree-org/iree#18099]
>2. Create a new "compilation phase" named CreateDispatchesDefault(iree-create-dispatches-default) just like Global optimizations/Flow/Stream/HAL, etc. that is essentially the transformations in the addDispatchRegionCreationPasses. So move those passes out of Flow into that phase. There is also an additional advantage of being able compile-from/compile-to this phase to isolate whats happening there in more complex models.

From the comments of https://github.com/iree-org/iree/pull/18063

There are a few inflight changes that need to land before this takes place

- https://github.com/iree-org/iree/pull/18063
- https://github.com/iree-org/iree/pull/18069
- https://github.com/iree-org/iree/pull/17880
- ...more?

cc @benvanik @MaheshRavishankar

**Comment by hanhanW** [comment]
https://github.com/iree-org/iree/pull/18071 is a pure CPU changes, so you don't need to wait on it. Perhaps we put https://github.com/iree-org/iree/pull/17880 to the list.
