### ISSUE TITLE
`scf` operations can fail during `ScheduleExecution` due to captured dependencies not considered during topological sorting

### ISSUE THREAD

**Issue by polvalente** [iree-org/iree#18123]
### What happened?

I have a stablehlo module which compiles and runs correctly on OpenXLA, but when trying to compile with IREE, I get this error:

/Users/paulo.valente/Desktop/repro.mlir:95:13: error: operand #1 does not dominate this use
    %45:8 = stablehlo.while(%iterArg = %c, %iterArg_10 = %34, %iterArg_11 = %40, %iterArg_12 = %38, %iterArg_13 = %44, %iterArg_14 = %32, %iterArg_15 = %c_5, %iterArg_16 = %c_6) : tensor<ui32>, tensor<1xui32>, tensor<1xui32>, tensor<ui32>, tensor<ui32>, tensor<ui32>, tensor<4xui8>, tensor<4xui8>

I'm also attaching the module and complete error message as they seem relevant

### Steps to reproduce your issue

Run `iree-compile` with `--iree-hal-target-backends=llvm-cpu --iree-input-type=stablehlo_xla --iree-execution-model=async-internal`

### Version information

candidate-20240604.914 and candidate-20240804.975 both present this issue

### Additional context

error message: [error.txt](https://github.com/user-attachments/files/16514101/error.txt)
MLIR module: [repro_mlir.txt](https://github.com/user-attachments/files/16514104/repro_mlir.txt)

**Comment by rsuderman** [comment]
Okay I found the issue. When we insert the the stream timepoints we are not considering that an operation within an SCF operation may take a dependency on the operation. Therefore if the captured dependency occurs before the timepoint creation we get an out of order dep.

Going to need to dig further into how we can sort this out.

**Comment by rsuderman** [comment]
Looking deeper into it - the failure does not occur until after the canonicalization patterns run. Probably an issue with a StreamOps Canonicalization pattern.

**Comment by rsuderman** [comment]
@polvalente I have a patch that should fix the issue, feel free to patch it in to unblock yourself. Will hopefully land on head today / tomorrow.

https://github.com/iree-org/iree/pull/18131

**Comment by polvalente** [comment]
Thanks! This isn't really blocking me in the sense that I have a workaround in place to avoid that specific loop, but I'll keep an eye out for the changes!

**Comment by polvalente** [comment]
This fix got me past the error I was facing! Pulled one of the latest pre-releases and it worked perfectly. Thanks :)
