### ISSUE TITLE
[ONNX] Missing shape inference through torch_mlir.tools.import_onnx

### ISSUE THREAD

**Issue by jinchen62** [iree-org/iree#18153]
### What happened?

The ONNX model imported by `torch_mlir.tools.import_onnx` command is missing shapes like in https://github.com/llvm/torch-mlir/issues/3593. Using `onnx_importer` of python binding would have dynamic shape. So seems there is inconsistency for these two methods.

### Steps to reproduce your issue

The command I used:
`PYTHONPATH=path/to/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir python -m torch_mlir.tools.import_onnx model.onnx -o model_torch-onnx.mlir`

The python codes I used:
> shaped_model = onnx.shape_inference.infer_shapes(onnx_model, data_prop=True)
    context = Context()
    torch_d.register_dialect(context)
    model_info = onnx_importer.ModelInfo(shaped_model)
    imported_model = model_info.create_module(context=context)

### What component(s) does this issue relate to?

Frontends

### Version information

Build locally at commit 71f1e205a3df61e236cf10054798c53fcfe460c9

**Comment by jinchen62** [comment]
@ScottTodd Could you please take a look? cc: @zjgarvey

**Comment by ScottTodd** [comment]
Please include version information with bug reports. At least the `iree-compiler` package version, but `torch` and `onnx` versions (e.g. from `pip freeze`) could be useful too.

**Comment by jinchen62** [comment]
@ScottTodd I build iree and torch-mlir locally. IREE is at commit 71f1e205a3df61e236cf10054798c53fcfe460c9, torch-mlir is at 78d0fa8998c93514737f7075f4f2a3f4a9ff7b57. Actually am I supposed to file this issue on torch-mlir side?

**Comment by ScottTodd** [comment]
Possibly. Does `iree-import-onnx` produce the expected result? That tool/script is slightly diverged from `torch_mlir.tools.import_onnx`

**Comment by jinchen62** [comment]
@ScottTodd `iree-import-onnx` also produce the missing shape.

**Comment by jinchen62** [comment]
Setting opset-version as 21 fixes the issue.
