### ISSUE TITLE
Figure out magic flags to build LLVM/MLIR as installable and have our cmake use it

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#1819]
Right now we require an llvm checkout and directly reach into the submodule directory for include paths and tools. We should instead be able to support out-of-tree prebuilt LLVM installs.

Specifically, if we have an LLVM install directory with the appropriate headers, prebuilt shared libraries for ones that we depend on, and the tools we require (namely just mlir-tblgen, I believe) we should be able to use cmake's `find_dependency` if the local in-tree submodule is missing.

@stellaraccident has a discussion on the MLIR discourse here: https://llvm.discourse.group/t/separate-install-target-for-mlir/1005

Whatever that's doing is likely what we want as well. Most of this work is about fixing our cmake files to not assume the presence of in-tree LLVM and the specific structure of the third_party directory.

**Comment by stellaraccident** [comment]
Here's what I worked out for doing this: https://github.com/google/mlir-npcomp (instructions in the readme).

Specific helper scripts:

- https://github.com/google/mlir-npcomp/blob/master/tools/install_mlir.sh
- https://github.com/google/mlir-npcomp/blob/master/tools/cmake_configure.sh

There are two points of weirdness that I'm just adapting to right now and taking the hit:

- Lit does not get installed, so still need to reach into the build directory to find it.
- There is currently not an `install-mlir` target so I'm just using the `install` target, which pulls in a bunch of LLVM tools. The thread above is regarding whether we can resolve that.

In general, I've found the flow to be quite reasonable as-is, modulo the inefficiency of building too much. When I switched the linker to be lld vs the system linker, a lot of the overhead of building the extra LLVM tools was significantly reduced (still would be nice to not need them). FTR, here is how to do that: `export LDFLAGS=-fuse-ld=$(which ld.lld-$LLVM_VERSION)`

There is still something funny going on with warning flags.

**Comment by stellaraccident** [comment]
Note that #2187 makes progress on this but needs an upstream patch to land. Once it does, I'll update the docs. I'm using it locally...

**Comment by marbre** [comment]
With #2187 merged, what could be the next steps?

**Comment by marbre** [comment]
This is currently blocked by #2401, but is working before and is already documented, see https://google.github.io/iree/GetStarted/CMakeOptionsVariables#iree_mlir_dep_modestring.

**Comment by benvanik** [comment]
Closing as obsolete.
