### ISSUE TITLE
Failed to legalize operation 'stream.cmd.dispatch'

### ISSUE THREAD

**Issue by nirvedhmeshram** [iree-org/iree#18229]
For IR provided [here](https://gist.github.com/nirvedhmeshram/f350fa447fdf5cdcbff45ced0dd77e6c)

with
```
iree-compile uncased_transpose_repro.mlir --iree-hal-target-backends="rocm" --iree-rocm-target-chip=gfx942 -o dump.vmfb
```
OR
```
iree-compile uncased_transpose_repro.mlir --iree-hal-target-backends=llvm-cpu -o dump.vmfb
```
We get the following error
```
uncased_transpose_repro.mlir:92:11: error: failed to legalize operation 'stream.cmd.dispatch' that was explicitly marked illegal
    %88 = torch.operator "onnx.Transpose"(%87) {torch.onnx.perm = [0 : si64, 2 : si64, 1 : si64, 3 : si64]} : (!torch.vtensor<[?,?,?,?],f32>) -> !torch.vtensor<[?,?,?,?],f32> 
          ^
cased_MM.mlir:92:11: note: see current operation: "stream.cmd.dispatch"(%17, %18, %5, %6, %106, %108, %78, %80, %82, %84, <<UNKNOWN SSA VALUE>>, <<UNKNOWN SSA VALUE>>, %66, %42, %7, %7, %66, %42) <{entry_points = [@torch_jit$async_dispatch_10::@embedded_elf_x86_64::@torch_jit$async_dispatch_10_transpose_Dx12xDx64_f32], operandSegmentSizes = array<i32: 4, 6, 2, 2, 2, 2>, resource_accesses = [1 : i32, 2 : i32]}> : (index, index, index, index, i32, i32, i32, i32, i32, i32, !stream.resource<transient>, !stream.resource<external>, index, index, index, index, index, index) -> ()
```

**Comment by zjgarvey** [comment]
Here are three more reproducers without resource strings: <https://gist.github.com/zjgarvey/1bf521f50d3928596c2198bf734eb973>

An interesting thing to note:

The first IR provided "bert_cased_MatMul_repro.mlir" fails to compile for CPU, but does NOT fail to compile for Mi300x (rocm gfx942).

**Comment by nirvedhmeshram** [comment]
I believe the problem is that there is a  `flow.dispatch.tensor.load` during the `ConvertToHALPass`
Here is the suspected problem snippet
```
      hal.executable.export public @torch_jit$async_dispatch_10_transpose_Dx12xDx64_f32 ordinal(0) layout(#pipeline_layout7) attributes {hal.interface.bindings = [#hal.interface.binding<0, 0>, #hal.interface.binding<0, 1>], subgroup_size = 64 : index, workgroup_size = [128 : index, 1 : index, 1 : index]} {
      ^bb0(%arg0: !hal.device, %arg1: index, %arg2: index, %arg3: index, %arg4: index):
        %c12 = arith.constant 12 : index
        %c1 = arith.constant 1 : index
        %c0 = arith.constant 0 : index
        %c32_i64 = arith.constant 32 : i64
        %0 = hal.interface.constant.load layout(#pipeline_layout7) ordinal(0) : i32
        %1 = arith.extui %0 : i32 to i64
        %2 = hal.interface.constant.load layout(#pipeline_layout7) ordinal(1) : i32
        %3 = arith.extui %2 : i32 to i64
        %4 = arith.shli %3, %c32_i64 : i64
        %5 = arith.ori %1, %4 : i64
        %6 = arith.index_castui %5 : i64 to index
        %7 = hal.interface.binding.subspan layout(#pipeline_layout7) set(0) binding(0) alignment(64) offset(%6)
 flags("ReadOnly|Indirect") : !flow.dispatch.tensor<readonly:tensor<?x?x?x?xf32>>
{%arg1, %arg2, %arg3, %arg4}
        %8 = flow.dispatch.tensor.load %7, offsets = [0, 0, 0, 0], 
sizes = [%arg1, %arg2, %arg3, %arg4], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<?x?x?x?xf32>>{%arg1, %arg2, %arg3, %arg4} -> tensor<?x?x?x?xf32>
        %cast = tensor.cast %8 : tensor<?x?x?x?xf32> to tensor<?x?x12x64xf32>
        %dim = tensor.dim %cast, %c0 : tensor<?x?x12x64xf32>
        %dim_0 = tensor.dim %cast, %c1 : tensor<?x?x12x64xf32>
        hal.return %dim_0, %c12, %dim : index, index, index
      }
      builtin.module {
      // device code
      }
 ```
    
  Here is the full [dump-before-all](https://gist.github.com/nirvedhmeshram/c72d13bd4a3a3abffff818037243af41)

**Comment by nirvedhmeshram** [comment]
So we have narrowed down the issue to a `tensor.reshape` that is introduced at the `ConvertTorchToLinalg` pass that can actually be just a `tensor.expandshape` . 
```
  %from_elements_132 = tensor.from_elements %233, %234, %c768_i64_131 : tensor<3xi64>
  %reshape = tensor.reshape %cast_126(%from_elements_132) : (tensor<?x768xf32>, tensor<3xi64>) -> tensor<?x?x768xf32>
 ```
There are two fixes possible.
1. Change the lowering to generate the expandshape IR
2. Canonicalization at the flow level for `flow.dispatch.workgroups` ops like these
```
%29 = flow.tensor.reshape %28 : tensor<?x?x768xf32>{%0, %1} -> tensor<?x?x?x?xf32>{%0, %1, %c12, %c64}
%30 = flow.dispatch.workgroups[%0, %1, %c12, %c64](%29, %0, %1, %c12, %c64) : (tensor<?x?x?x?xf32>{%0, %1, %c12, %c64}, index, index, index, index) -> tensor<?x12x?x64xf32>{%0, %1} =
      (%arg3: !flow.dispatch.tensor<readonly:tensor<?x?x?x?xf32>>, %arg4: index, %arg5: index, %arg6: index, %arg7: index, %arg8: !flow.dispatch.tensor<writeonly:tensor<?x12x?x64xf32>>) {
    %34 = flow.dispatch.workload.ordinal %arg4, 0 : index
    %35 = flow.dispatch.workload.ordinal %arg5, 1 : index
    %36 = flow.dispatch.workload.ordinal %arg6, 2 : index
    %37 = flow.dispatch.workload.ordinal %arg7, 3 : index
    %38 = flow.dispatch.tie_shape %arg3 : !flow.dispatch.tensor<readonly:tensor<?x?x?x?xf32>>{%34, %35, %36, %37}
    %39 = flow.dispatch.tie_shape %arg8 : !flow.dispatch.tensor<writeonly:tensor<?x12x?x64xf32>>{%34, %35}
    %40 = flow.dispatch.tensor.load %38, offsets = [0, 0, 0, 0], sizes = [%34, %35, %36, %37], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<?x?x?x?xf32>>{%34, %35, %36, %37} -> tensor<?x?x?x?xf32>
    %41 = tensor.empty(%34, %35) : tensor<?x12x?x64xf32>
    %cast = tensor.cast %40 : tensor<?x?x?x?xf32> to tensor<?x?x12x64xf32>
    %42 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d2, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%cast : tensor<?x?x12x64xf32>) outs(%41 : tensor<?x12x?x64xf32>) {
    ^bb0(%in: f32, %out: f32):
      linalg.yield %in : f32
    } -> tensor<?x12x?x64xf32>
    flow.dispatch.tensor.store %42, %39, offsets = [0, 0, 0, 0], sizes = [%34, 12, %35, 64], strides = [1, 1, 1, 1] : tensor<?x12x?x64xf32> -> !flow.dispatch.tensor<writeonly:tensor<?x12x?x64xf32>>{%34, %35}
    flow.return
  }
  ```
  for 2. the idea will be that `%c12, %c64` are inlined and become part of the IR and are dropped as arguments to the ops
  
  We want to do both of these as they are good patterns to have, I will take 2. @MaheshRavishankar will assign 1. to another developer.

**Comment by benvanik** [comment]
Can you clarify what you mean by 2? If the shape is known to be static then that should be propagated at the tensor dialect level and never make it that far. Always prefer fixing it earlier in the process.

**Comment by MaheshRavishankar** [comment]
Actually thinking a bit more, there might be an option 3. Staying in `tensor.reshape` and doing this constant dim propagation is hard. But we can do it easily on `flow.tensor.reshape`.
But to be able to make sure the formed display is as we want, we will want to make the pass to convert tensor to flow [here](https://github.com/iree-org/iree/blob/main/compiler%2Fsrc%2Firee%2Fcompiler%2FDialect%2FFlow%2FTransforms%2FPasses.cpp#L297) run before conversion of region to workgroups.

**Comment by nirvedhmeshram** [comment]
That might be tricky becuase tensors in the inner computation are also getting converted e.g
```
  %18 = flow.dispatch.region -> (tensor<?x768xf32>{%16}) {
    %38 = affine.apply affine_map<()[s0, s1] -> (s0 * s1)>()[%0, %1]
    %39 = tensor.empty(%38) : tensor<?x768xf32>
    %40 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%collapsed : tensor<?xi64>) outs(%39 : tensor<?x768xf32>) {
    ^bb0(%in: i64, %out: f32):
      %41 = arith.index_cast %in : i64 to index
      %42 = linalg.index 1 : index
      %extracted = tensor.extract %cst_3[%41, %42] : tensor<30522x768xf32>
      linalg.yield %extracted : f32
    } -> tensor<?x768xf32>
    flow.return %40 : tensor<?x768xf32>
  }
  ```
  becomes
  ```
    %18 = flow.dispatch.region -> (tensor<?x768xf32>{%17}) {
    %41 = affine.apply affine_map<()[s0, s1] -> (s0 * s1)>()[%0, %1]
    %42 = tensor.empty(%41) : tensor<?x768xf32>
    %43 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%16 : tensor<?xi64>) outs(%42 : tensor<?x768xf32>) {
    ^bb0(%in: i64, %out: f32):
      %44 = arith.index_cast %in : i64 to index
      %45 = linalg.index 1 : index
      %46 = flow.tensor.load %cst_3[%44, %45] : tensor<30522x768xf32>
      linalg.yield %46 : f32
    } -> tensor<?x768xf32>
    flow.return %43 : tensor<?x768xf32>
  }
  ```
Edit: I see that the guard that should prevent this from happening just needs updating, I can do that.

**Comment by nirvedhmeshram** [comment]
> Actually thinking a bit more, there might be an option 3. Staying in `tensor.reshape` and doing this constant dim propagation is hard. But we can do it easily on `flow.tensor.reshape`. But to be able to make sure the formed display is as we want, we will want to make the pass to convert tensor to flow [here](https://github.com/iree-org/iree/blob/main/compiler%2Fsrc%2Firee%2Fcompiler%2FDialect%2FFlow%2FTransforms%2FPasses.cpp#L297) run before conversion of region to workgroups.

Can you elaborate what makes it hard at tensor.reshape that is easier at flow.tensor.reshape. I think that will answer Ben's question as well.

**Comment by qedawkins** [comment]
Can I be a fly on the wall and say that `tensor.reshape` is a terrible operation past a certain point. It is catering to unranked tensors by taking a tensor to describe the new shape, but this is pretty fundamentally incompatible with anything iree does for code generation.

We can just lower this sequence to a `flow.tensor.reshape` if need be somewhere near input conversion
```
  %from_elements_132 = tensor.from_elements %233, %234, %c768_i64_131 : tensor<3xi64>
  %reshape = tensor.reshape %cast_126(%from_elements_132) : (tensor<?x768xf32>, tensor<3xi64>) -> tensor<?x?x768xf32>
```

Also I'm pretty sure torch-mlir does fairly involved analysis to ensure every tensor ends up being ranked, so we should have no reason to ever even see a `tensor.reshape`, giving another option to just not create that op.

**Comment by benvanik** [comment]
Yeah, agreed - tensor.reshape is terrible, and the sooner we can get out of that and into flow.tensor.reshape the better!

**Comment by MaheshRavishankar** [comment]
> > Actually thinking a bit more, there might be an option 3. Staying in `tensor.reshape` and doing this constant dim propagation is hard. But we can do it easily on `flow.tensor.reshape`. But to be able to make sure the formed display is as we want, we will want to make the pass to convert tensor to flow [here](https://github.com/iree-org/iree/blob/main/compiler%2Fsrc%2Firee%2Fcompiler%2FDialect%2FFlow%2FTransforms%2FPasses.cpp#L297) run before conversion of region to workgroups.
> 
> Can you elaborate what makes it hard at tensor.reshape that is easier at flow.tensor.reshape. I think that will answer Ben's question as well.

If you look at the op definition of `tensor.reshape`, it take a source tensor and a tensor representing the new shape, and not a list of operands that represent the dynamic values of the new shape.  So instead of what it is today,
```
 %from_elements_132 = tensor.from_elements %233, %234, %c768_i64_131 : tensor<3xi64>
  %reshape = tensor.reshape %cast_126(%from_elements_132) : (tensor<?x768xf32>, tensor<3xi64>) -> tensor<?x?x768xf32>
```
if it were
```
  %reshape = tensor.reshape %cast_126 output_shape [%233, %234, %c768]  (tensor<?x768xf32>) -> tensor<?x?x?xf32>
```
you could canonicalize that to
```
  %reshape = tensor.reshape %cast_126 output_shape [%233, %234, 768]  (tensor<?x768xf32>) -> tensor<?x?x768xf32>
```

So in its current form `tensor.reshape` is a dud. 

But you can take take `flow.tensor.reshape`
```
%29 = flow.tensor.reshape %28 : tensor<?x?x768xf32>{%0, %1} -> tensor<?x?x?x?xf32>{%0, %1, %c12, %c64}
```
and canonicalize it to
```
%29 = flow.tensor.reshape %28 : tensor<?x?x768xf32>{%0, %1} -> tensor<?x?x12x64xf32>{%0, %1}
```

Re: when we should convert `tensor.reshape` to `flow.tensor.reshape`, dont have an opinion. All the tensor -> flow conversions happen in one pass, id rather keep it there. Would it be better for front end to not emit that to begin with, absolutely, but I think we should operate in a "if it comes in this way, we handle it, but if you want it to do better it needs to be lowered better".

**Comment by nirvedhmeshram** [comment]
just an update, I found that you dont want to always do the constant propagation as reshape may also be used as a cast (there is no flow.tensor.cast op) and in this case you may not want to propogate. see IR below
```
...
  %dim_11 = tensor.dim %32, %c0 : tensor<?x12x?x64xf32>
  %dim_12 = tensor.dim %32, %c2 : tensor<?x12x?x64xf32>
  %33 = flow.tensor.reshape %32 : tensor<?x12x?x64xf32>{%dim_11, %dim_12} -> tensor<?x?x?x?xf32>{%dim_11, %c12, %dim_12, %c64}
  %34 = hal.tensor.barrier join(%33 : tensor<?x?x?x?xf32>) => %arg2 : !hal.fence
  %dim_13 = tensor.dim %34, %c0 : tensor<?x?x?x?xf32>
  %dim_14 = tensor.dim %34, %c1 : tensor<?x?x?x?xf32>
  %dim_15 = tensor.dim %34, %c2 : tensor<?x?x?x?xf32>
  %dim_16 = tensor.dim %34, %c3 : tensor<?x?x?x?xf32>
  %35 = hal.tensor.export %34 : tensor<?x?x?x?xf32>{%dim_13, %dim_14, %dim_15, %dim_16} -> !hal.buffer_view
  util.return %35 : !hal.buffer_view
}
```
Here the propagation canonicalization causes a crash. 
So I am just going to have it as a pattern that i run after converting tensor.reshape to flow.tensor.reshape. We should not need it at other times.

**Comment by MaheshRavishankar** [comment]
> just an update, I found that you dont want to always do the constant propagation as reshape may also be used as a cast (there is no flow.tensor.cast op) and in this case you may not want to propogate. see IR below
> 
> ```
> ...
>   %dim_11 = tensor.dim %32, %c0 : tensor<?x12x?x64xf32>
>   %dim_12 = tensor.dim %32, %c2 : tensor<?x12x?x64xf32>
>   %33 = flow.tensor.reshape %32 : tensor<?x12x?x64xf32>{%dim_11, %dim_12} -> tensor<?x?x?x?xf32>{%dim_11, %c12, %dim_12, %c64}
>   %34 = hal.tensor.barrier join(%33 : tensor<?x?x?x?xf32>) => %arg2 : !hal.fence
>   %dim_13 = tensor.dim %34, %c0 : tensor<?x?x?x?xf32>
>   %dim_14 = tensor.dim %34, %c1 : tensor<?x?x?x?xf32>
>   %dim_15 = tensor.dim %34, %c2 : tensor<?x?x?x?xf32>
>   %dim_16 = tensor.dim %34, %c3 : tensor<?x?x?x?xf32>
>   %35 = hal.tensor.export %34 : tensor<?x?x?x?xf32>{%dim_13, %dim_14, %dim_15, %dim_16} -> !hal.buffer_view
>   util.return %35 : !hal.buffer_view
> }
> ```
> 
> Here the propagation canonicalization causes a crash. So I am just going to have it as a pattern that i run after converting tensor.reshape to flow.tensor.reshape. We should not need it at other times.

Can you share what the crash is... it should still be OK to propagate the constant here.

**Comment by MaheshRavishankar** [comment]
Cross linking https://github.com/llvm/torch-mlir/issues/3647 as related issues

**Comment by zjgarvey** [comment]
This only seemed to get the transpose reproducer to compile, but none of the other three reproducers are compiling with this patch (see <https://gist.github.com/zjgarvey/1bf521f50d3928596c2198bf734eb973>).

**Comment by nirvedhmeshram** [comment]
@zjgarvey with the recent gist https://gist.github.com/zjgarvey/1bf521f50d3928596c2198bf734eb973 is the failure 
```
 iree/compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/ArchiveWriter.cpp:390: std::optional<ZIPFileRef> mlir::iree_compiler::IREE::VM::appendZIPFileToStream(std::string, uint64_t, uint64_t, std::function<LogicalResult (llvm::raw_ostream &)>, llvm::raw_ostream &): Assertion `fileRef.totalLength == fileLength && "declared length mismatch"' failed.
 ```
 As mentioned in a previous [issue](https://github.com/iree-org/iree/issues/18195#issuecomment-2289063883) that is to do with the wrong way of elliding variables in the repros?

**Comment by nirvedhmeshram** [comment]
`distilgpt2_Add_repro` seems like a real (but different) failure, investigating that one...
```
<unknown>:0: error: failed to legalize unresolved materialization from ('i64') to 'index' that remained live after conversion
<unknown>:0: note: see current operation: %52 = "builtin.unrealized_conversion_cast"(%50) : (i64) -> index
../repro_mlirs/distilgpt2_Add_repro.mlir:1:1: error: conversion to vm.module failed
```

**Comment by zjgarvey** [comment]
> As mentioned in a previous issue that is to do with the wrong way of elliding variables in the repros?

yes

**Comment by nirvedhmeshram** [comment]
@zjgarvey I opened https://github.com/iree-org/iree/issues/18364 for the `distilgpt2_Add_repro` failure. I dont see the `Failed to legalize operation 'stream.cmd.dispatch')` anymore but if you do please let me know, if not feel free to close this issue.

**Comment by zjgarvey** [comment]
That's good. I'm getting the new error for rocm mentioned in the above link.

For llvm-cpu, I am still getting the `cmd.stream.dispatch` error for all four test cases besides the `transpose` one, so I'd like to keep this issue open for CPU.

**Comment by nirvedhmeshram** [comment]
That sounds good, I can revisit after #18364 as it is possible whatever we fix there might help with the CPU compilation too as it's a very similar problem.
