### ISSUE TITLE
jit global source initialization order invalid: global "__hoisted_i32" has no value

### ISSUE THREAD

**Issue by jinchen62** [iree-org/iree#18232]
### What happened?

> error: internal error: jit global source initialization order invalid: global "__hoisted_i32" has no value

Repro: 
https://gist.github.com/jinchen62/f546bb9ef88c769ba6bc13d135e2bd00

Command:
`iree-compile --iree-input-demote-i64-to-i32 --iree-hal-target-backends=llvm-cpu repro_onnx.mlir -o test.vmfb`

Commands I used when debugging:
- convert to linalg: `torch-mlir-opt -pass-pipeline='builtin.module(func.func(convert-torch-onnx-to-torch),torch-lower-to-backend-contract,func.func(cse,canonicalize),torch-backend-to-linalg-on-tensors-backend-pipeline)' repro_onnx.mlir -o repro_linalg.mlir`
- dump after HoistIntoGlobals: `iree-compile --iree-input-demote-i64-to-i32 --iree-hal-target-backends=llvm-cpu --mlir-print-ir-after=iree-util-hoist-into-globals repro_linalg.mlir -o repro.vmfb 2> dump_after_hoist.mlir`

### Version information

Build TOM locally

**Comment by jinchen62** [comment]
@qedawkins

**Comment by qedawkins** [comment]
So the issue is that HoistIntoGlobals is generating `index` type initializers like this
```
  util.global private @__hoisted_index_19 {stream.affinity.default = #hal.device.affinity<@__device_0>} : index
  util.initializer attributes {stream.affinity.default = #hal.device.affinity<@__device_0>} {
    %__hoisted_index_16 = util.global.load @__hoisted_index_16 : index
    %__hoisted_index_17 = util.global.load @__hoisted_index_17 : index
    %__hoisted_index_6 = util.global.load @__hoisted_index_6 : index
    %__hoisted_index_7 = util.global.load @__hoisted_index_7 : index
    %__hoisted_index_8 = util.global.load @__hoisted_index_8 : index
    %__hoisted_index_9 = util.global.load @__hoisted_index_9 : index
    %0 = affine.apply #map3()[%__hoisted_index_16, %__hoisted_index_17, %__hoisted_index_6, %__hoisted_index_7, %__hoisted_index_8, %__hoisted_index_9]
    util.global.store %0, @__hoisted_index_19 : index
    util.return
  }
```
which `__hoisted_i64` depends on
```
  util.global private @__hoisted_i64 {stream.affinity.default = #hal.device.affinity<@__device_0>} : i64
  util.initializer attributes {stream.affinity.default = #hal.device.affinity<@__device_0>} {
    %__hoisted_index_18 = util.global.load @__hoisted_index_18 : index
    %0 = arith.index_cast %__hoisted_index_18 : index to i64 
    %__hoisted_index_19 = util.global.load @__hoisted_index_19 : index
    %1 = arith.index_cast %__hoisted_index_19 : index to i64 
    %2 = arith.muli %0, %1 : i64
    util.global.store %2, @__hoisted_i64 : i64
    util.return
  }
```

So the initializer order is correct, but JitGlobals fails to evaluate the initializers `__hoisted_i64` depends on and as a result the pass fails. I am not sure whether index type globals is supported, though IIUC the max index bitwidth we support is 64 (?) so I think JitGlobals could support this. Either way the pass probably shouldn't fall over when an initializer fails to evaluate.

**Comment by jinchen62** [comment]
Close as https://github.com/iree-org/iree/pull/18303 is merged. Will open another issue for
```
error: 'util.initializer' op failed to inline into combined initializer
```
