### ISSUE TITLE
Bug with Dynamic dimensions in the case of `fuse Encoding ops into dispatch regions pass`.

### ISSUE THREAD

**Issue by pashu123** [iree-org/iree#18276]
### What happened?

after.mlir:13:10: error: operand #1 does not dominate this use
    %4 = flow.dispatch.region -> (tensor<?x8640x3200xf16>{%0}) {
         ^
after.mlir:13:10: note: see current operation:
%5:2 = "flow.dispatch.region"(%1, %7) <{operandSegmentSizes = array<i32: 2, 0>}> ({
  %24 = "tensor.empty"(%1) : (index) -> tensor<?x8640x3200xf16>
  %25 = "linalg.generic"(%4, %24) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
  ^bb0(%arg7: f16, %arg8: f16):
    "linalg.yield"(%arg7) : (f16) -> ()
  }) : (tensor<8640x3200xf16>, tensor<?x8640x3200xf16>) -> tensor<?x8640x3200xf16>
  %26 = "iree_encoding.set_encoding"(%25) : (tensor<?x8640x3200xf16>) -> tensor<?x8640x3200xf16, #iree_encoding.encoding<operand_index = 1 : index, op_type =  matmul, element_types = [f32, f16, f32], original_type = tensor<?x8640x3200xf16>, user_indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], round_dims_to = array<i64: 32, 32, 32>>>
  "flow.return"(%25, %26) : (tensor<?x8640x3200xf16>, tensor<?x8640x3200xf16, #iree_encoding.encoding<operand_index = 1 : index, op_type =  matmul, element_types = [f32, f16, f32], original_type = tensor<?x8640x3200xf16>, user_indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], round_dims_to = array<i64: 32, 32, 32>>>) -> ()
}, {
}) : (index, index) -> (tensor<?x8640x3200xf16>, tensor<?x8640x3200xf16, #iree_encoding.encoding<operand_index = 1 : index, op_type =  matmul, element_types = [f32, f16, f32], original_type = tensor<?x8640x3200xf16>, user_indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], round_dims_to = array<i64: 32, 32, 32>>>)
after.mlir:21:10: note: operand defined here (op in the same block)
    %5 = iree_encoding.set_encoding %4 : tensor<?x8640x3200xf16> -> tensor<?x8640x3200xf16, #iree_encoding.encoding<operand_index = 1 : index, op_type =  matmul, element_types = [f32, f16, f32], original_type = tensor<?x8640x3200xf16>, user_indexing_maps = [#map2, #map3, #map4], round_dims_to = array<i64: 32, 32, 32>>>

### Steps to reproduce your issue

`iree-opt --pass-pipeline="builtin.module(util.func(iree-flow-fuse-encoding-ops-into-dispatch-regions-pass))"  bug.mlir`

bug.mlir: https://gist.github.com/pashu123/e417e05bce68fe87094565c1eda0927d

### Additional context

https://github.com/Max191/iree/blob/data-tiling-fusion-prototype-new/compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp#L510,L541  Looking closely, the `dispatchOpNewResultsDynamicDims` is initialized and used without populating it with values.

**Comment by Max191** [comment]
Closing this because it has been fixed. The bug had not been merged yet, so I will update my PR.
