### ISSUE TITLE
[compile][rocm/gfx942] flux sampler fails to lower with batch size > 1 with dominance error

### ISSUE THREAD

**Issue by monorimet** [iree-org/iree#18308]
### What happened?

In the flux sampler model, with batch sizes greater than 1, we encounter the following error:
```
flux_sampler_attn_repro_fp16_bs4.mlir:64:11: error: operand #2 does not dominate this use
    %16 = torch.aten.neg %15 : !torch.vtensor<[4,4608,8],f64> -> !torch.vtensor<[4,4608,8],f64>
          ^
flux_sampler_attn_repro_fp16_bs4.mlir:64:11: note: operand defined here (op in the same block)
```
This is from an excerpt of the full model (positional embedding + double stream block).

The failure happens in EmplaceAllocationsPass (in stream dialect) -- this separates this case from other instances of the error I've seen browsing issues. I cannot compile to hal executables, otherwise I would post the failing dispatch by itself. A full print-ir-after-all is included below.

The given error points to IR that can be isolated by removing the double stream block, i.e., just the positional embedding. By itself, the positional embedding module (see `flux_sampler_pe_fp16_bs4.mlir` from reproducer instructions) compiles successfully.

Thus, one of two things is true:

1. the error is misleading
2. the error is correct but only occurs when the positional embedding is consumed by the double stream block -- I may be able to minimize on this further

### Steps to reproduce your issue

[flux_sampler_attn_repro_fp16_bs4.mlir](https://sharkpublic.blob.core.windows.net/sharkpublic/ean/flux-dev/flux_sampler_attn_repro_fp16_bs4.mlir)
[flux_sampler_pe_fp16_bs4.mlir](https://sharkpublic.blob.core.windows.net/sharkpublic/ean/flux-dev/flux_sampler_pe_fp16_bs4.mlir)
[attention_and_matmul_spec.mlir](https://raw.githubusercontent.com/iree-org/iree/main/build_tools/pkgci/external_test_suite/attention_and_matmul_spec.mlir)
Compile command:
```
iree-compile --iree-input-type=torch --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=rocm --mlir-print-debuginfo=false --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=rocm --iree-rocm-target-chip=gfx942 --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-global-opt-propagate-transposes=true --iree-opt-const-eval=false --iree-llvmgpu-enable-prefetch=true --iree-execution-model=async-external --iree-preprocessing-pass-pipeline='builtin.module(iree-preprocessing-transpose-convolution-pipeline, iree-preprocessing-pad-to-intrinsics)' --iree-codegen-transform-dialect-library=attention_and_matmul_spec.mlir --iree-codegen-llvmgpu-enable-transform-dialect-jit=false --iree-opt-outer-dim-concat=true flux_sampler_attn_repro_fp16_bs4.mlir
```
IR dump after all (fails at EmplaceAllocationsPass): [Azure](https://sharkpublic.blob.core.windows.net/sharkpublic/ean/flux-dev/flux_bs4_dump.txt)

### What component(s) does this issue relate to?

Compiler

### Version information

https://github.com/iree-org/iree/commit/10ba28dcf142f8b30217f24d7781130d581663c3

### Additional context

This may (or may not) be related to https://github.com/iree-org/iree/issues/18254

**Comment by nirvedhmeshram** [comment]
@benvanik any pointers on this, [here](https://gist.github.com/nirvedhmeshram/31923af94541a66c774b6616d37f7a9b) is the IR before the pass that I can see failing with
```
iree-opt --iree-stream-emplace-allocations emplacealloc_failure.mlir 
```
The error message is
```
../emplacealloc_failure.mlir:144:11: error: operand #2 does not dominate this use
  %40:2 = stream.async.dispatch on(#hal.device.affinity<@__device_0>) @main$async_dispatch_1::@main$async_dispatch_1_elementwise_4x4608x8_f32(%38[%c0 to %c110592 for %c110592], %16[%c0 to %c32 for %c32]) : (!stream.resource<*>{%c110592}, !stream.resource<*>{%c32}) -> (!stream.resource<*>{%c589824}, !stream.resource<*>{%c589824})
          ^
../emplacealloc_failure.mlir:144:11: note: see current operation: %114:2 = "stream.async.dispatch"(%110, %86, %114#1, %113, %18, %4, %20, %20, %14, %14, %21, %19, %18, %4, %22, %21, %18, %4, %19, %19, %20, %20) <{affinity = #hal.device.affinity<@__device_0>, entry_points = [@main$async_dispatch_1::@main$async_dispatch_1_elementwise_4x4608x8_f32], operandSegmentSizes = array<i32: 0, 4, 4, 4, 4, 4, 2>, tied_operands = [2 : index, 3 : index]}> : (!stream.resource<*>, !stream.resource<*>, !stream.resource<*>, !stream.resource<*>, index, index, index, index, index, index, index, index, index, index, index, index, index, index, index, index, index, index) -> (!stream.resource<*>, !stream.resource<*>)
../emplacealloc_failure.mlir:144:11: note: operand defined here (op in the same block)
```

**Comment by benvanik** [comment]
not sure - would need some investigation. emplace allocations is quite critical so if there's a case it's failing we need to fix it (instead of disabling it) - it failing to place a single case can cause memory consumption to double or worse (for example, if a dispatch ends up producing multiple results that are inserted into a 32GB kv cache and by not emplacing that kv cache is cloned 2 or 3 times)
