### ISSUE TITLE
`fetchRecurseSubmodules = false` for `third_party/torch-mlir`

### ISSUE THREAD

**Issue by makslevental** [iree-org/iree#18409]
### Request description

Would it be possible/acceptable to set `fetchRecurseSubmodules = false` (in `.gitmodules`) for `torch-mlir`? Reason: `third_party/torch-mlir/externals/llvm-project` is a whole 'nother checkout/clone of `llvm-project` and for people that don't use the `torch-mlir` frontend, it's a pretty expensive cost (both in CI and local dev). Obviously one can workaround it but it would be nice if it were opt-in rather than opt-out.

Also `shallow = true` for all the submodules is probably a good idea too (likewise in `torch-mlir` itself, so I'll open an issue there too).

**Comment by benvanik** [comment]
wow, that's bad - we should definitely fix that

**Comment by benvanik** [comment]
it also contains stablehlo

**Comment by makslevental** [comment]
> it also contains stablehlo

We should add `iree` there and complete the circle 😬

**Comment by makslevental** [comment]
FYI turns out you can actually do this even without the consent/cooperation of a submodule. Eg in [iree-amd-aie](https://github.com/nod-ai/iree-amd-aie/blob/main/.github/workflows/ci-linux.yml#L49) I did this

```
  git \
    -c submodule."third_party/torch-mlir".update=none \
    -c submodule."third_party/stablehlo".update=none \
    clone \
    --recursive \
    https://github.com/nod-ai/iree-amd-aie.git
```

and it works even though `third_party/torch-mlir` and `third_party/stablehlo` aren't directly our submodules (ie they're not in our `third_party` directory).

**Comment by stellaraccident** [comment]
I think no one up to now has needed to recurse submodules. If there's a way to make it better, yes please.

**Comment by ScottTodd** [comment]
> FYI turns out you can actually do this even without the consent/cooperation of a submodule. Eg in [iree-amd-aie](https://github.com/nod-ai/iree-amd-aie/blob/main/.github/workflows/ci-linux.yml#L49) I did this
> 
> ```
>   git \
>     -c submodule."third_party/torch-mlir".update=none \
>     -c submodule."third_party/stablehlo".update=none \
>     clone \
>     --recursive \
>     https://github.com/nod-ai/iree-amd-aie.git
> ```
> 
> and it works even though `third_party/torch-mlir` and `third_party/stablehlo` aren't directly our submodules (ie they're not in our `third_party` directory).

We recommend something similar in https://github.com/iree-org/iree-template-runtime-cmake (though it looks like I slipped a duplicate line in there during a merge conflict fix... oops, will fix)

When working on torch-mlir, I do find it useful to use IREE's torch-mlir submodule with recursive submodules. As long as that is still possible somehow then I'm also in favor of any quality of life improvements we can make for the majority of IREE users/developers.

**Comment by makslevental** [comment]
> We recommend something similar in https://github.com/iree-org/iree-template-runtime-cmake (though it looks like I slipped a duplicate line in there during a merge conflict fix... oops, will fix)

jeez I wish I knew about this this weekend while I was thrashing on it. Anyway with those `-c`s I'm happy-ish with the flow for iree-amd-aie so I'm gonna close this for now. Maybe revisit at a later date when I become unhappy again :)
