### ISSUE TITLE
[GPU] Codegen support for fused gather & attention

### ISSUE THREAD

**Issue by IanWood1** [iree-org/iree#18447]
f49c279cffb37e40c9f932036ca1e636a829bdfe on branch https://github.com/IanWood1/iree/tree/clone_gather implements cloning 'gather-like' ops (aka a `linalg.generic` that yields a `tensor.extract`). However, there needs to be codegen support to fully land this fusion. I have attached the executable sources below as well as the current error im getting from GPU codegen. Also, see the commit for the original IR used to generate the executable sources

Also, I tested IREE with this change locally and I surprisingly didn't get any failures. But, I'm sure this would probably cause codegen failures in other models that use gather-like ops.

### Executable Sources:
https://gist.github.com/IanWood1/d6fe3c9a92bc5407c1b73ea55593c698

### Error:
https://gist.github.com/IanWood1/cfe431d1f0e7dbe65f9e91ef5ae8fa4e

cc @MaheshRavishankar

**Comment by Groverkss** [comment]
Fixed by  https://github.com/iree-org/iree/pull/19209 (shows that it works)
