### ISSUE TITLE
mimalloc warning ubuntu 24.04

### ISSUE THREAD

**Issue by ziereis** [iree-org/iree#18472]
### What happened?

after upgrading to Ubuntu 24.04.1 i get the following warnings while compiling iree with clang version 18.1.3 :
```
mimalloc: warning: thread 0x7df4286006c0: unable to directly request hinted aligned OS memory (error: 0 (0x0), size: 0x40000000 bytes, alignment: 0x2000000, hint address: 0x20002000000)
```

### Steps to reproduce your issue

my compile commands:

cmake -G Ninja -B build/ -S . \
                                                  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
                                                  -DIREE_ENABLE_ASSERTIONS=ON \
                                                  -DIREE_ENABLE_SPLIT_DWARF=ON \
                                                  -DIREE_ENABLE_THIN_ARCHIVES=ON \
                                                  -DCMAKE_C_COMPILER=clang \
                                                  -DCMAKE_CXX_COMPILER=clang++ \
                                                  -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold" \
                                                  -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=mold" \
                                                  -DCMAKE_C_COMPILER_LAUNCHER=ccache  \
                                                  -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

### What component(s) does this issue relate to?

Other

### Version information

main b197555f57

**Comment by ScottTodd** [comment]
Interesting to see a warning from `mimalloc` when we don't directly use it... though we do have a patch that lets us use it (optionally): https://github.com/iree-org/iree/pull/16812

**Comment by benvanik** [comment]
It's unclear from the description what's emitting the warning - the compilation of some IREE compiler or runtime code, or the built IREE compiler during compilation, etc. If clang itself is exploding I'm not sure there's much we could do and you may want to check your environment.

**Comment by ziereis** [comment]
i didnt pay too much attention when the error occurs at first, but i checked again and i think its originating from my linker, so probably not iree related. Sorry ! :)

**Comment by kuhar** [comment]
Closing as it doesn't seem like anything actionable.

FWIW, I also use mold and haven't seen this warning.
