### ISSUE TITLE
[LinalgExt][Fusion] Fusion of attention + reshape on reduction dim causes lowering error

### ISSUE THREAD

**Issue by raikonenfnu** [iree-org/iree#18498]
### What happened?

During decode phase in sharktank paged LLM, there is a case where we expand shapes on one of attention's reduction dim/K2. When fused, this causes attention pipeline to break.  

We can see that the IR pre-fusion with expand shape [here](https://gist.github.com/raikonenfnu/431877638e495d5cd77fdc810326daf3)

post-fusion IR [here](https://gist.github.com/raikonenfnu/bdaa10e8600b07a7f95932716503abae)

We can see that dimension d5,d6 is used to represent K2 of attention dim. Which is problematic. 

### Steps to reproduce your issue

```bash
wget  gist.githubusercontent.com/raikonenfnu/8a346ac535849f8d5b083e01e9c5faf5/raw/ff800bc244d5bc74b9ffa6fd83e2d12bce2c88a9/padrepro.mlir

 ~/nod/iree-build-notrace/install/bin/iree-compile padrepro.mlir --iree-hal-target-backends=rocm --iree-hip-target=gfx942 -o paged_attn.vmfb

Expected output/error:
error: Unimplemented: > 1 k dims

From: https://github.com/iree-org/iree/blob/5a6521cac8f920650a7ea643a15d00ca955fcdff/compiler/src/iree/compiler/Codegen/Dialect/GPU/IR/IREEGPUAttrs.cpp#L1034-L1036
```

**Comment by Groverkss** [comment]
This is an easy fix, you can just assign batch dimensions to that addition dimension. I can fix it, but happy to let someone else also try fixing it.

**Comment by IanWood1** [comment]
Is the output in `post_fusion.mlir` invalid or does it just break the pipeline? Because I don't think its possible to fuse the transposes with the attention op without fusing the expand/collapse shapes

**Comment by raikonenfnu** [comment]
> This is an easy fix, you can just assign batch dimensions to that addition dimension. I can fix it, but happy to let someone else also try fixing it.

the additional dimension is a reduction dimension though, not sure if we can set it as a batch.

**Comment by raikonenfnu** [comment]
> Is the output in `post_fusion.mlir` invalid or does it just break the pipeline? Because I don't think its possible to fuse the transposes with the attention op without fusing the expand/collapse shapes

Yeah, it breaks the compilation pipeline if we fuse the expanded reduction dims. so my initial idea was to turn it off until we have support for it.

**Comment by Groverkss** [comment]
Me and Stanley talked offline and this should be a simple codegen change. We can just assign batch dimensions for the layout here: https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/Dialect/GPU/IR/IREEGPUAttrs.cpp#L1204

**Comment by raikonenfnu** [comment]
I have a wip that generates vmfb, was quite straight forward, but need to test e2e correctness. :)

**Comment by Groverkss** [comment]
Fixed by https://github.com/iree-org/iree/pull/18868
