### ISSUE TITLE
canonicalize dropping the `lowering_config` attached to an operation.

### ISSUE THREAD

**Issue by pashu123** [iree-org/iree#18697]
### What happened?

module_prefill_bs4$async_dispatch_20.mlir:9:7: error: not able to find the lowering config

      func.func @prefill_bs4$async_dispatch_20_pack_f16() {
      ^
module_prefill_bs4$async_dispatch_20.mlir:9:7: note: see current operation:

### Steps to reproduce your issue

**Input IR**: https://gist.github.com/pashu123/17e3f882b8ddee143c367a6743d918d5

Command: `iree-opt --canonicalize inp.mlir`

The output IR won't have the `lowering_config` attribute attached to the `tensor.pack` operation.

**Comment by hanhanW** [comment]
The fix is to add the attributes when we create a new tensor.pack op: https://github.com/llvm/llvm-project/blob/78089d5845d14bf61bdc06209c32f0fb34927c68/mlir/lib/Dialect/Tensor/IR/TensorOps.cpp#L4326-L4346

Or you can use in-place update like:

```
    rewriter.startOpModification(packOp);
    packOp.getSourceMutable().assign(source); // or .set(); I don't remember. :p
    packOp.getDestMutable().assign(dest);
    rewriter.finalizeOpModification(packOp);
```

**Comment by pashu123** [comment]
> The fix is to add the attributes when we create a new tensor.pack op: https://github.com/llvm/llvm-project/blob/78089d5845d14bf61bdc06209c32f0fb34927c68/mlir/lib/Dialect/Tensor/IR/TensorOps.cpp#L4326-L4346
> 
> Or you can use in-place update like:
> 
> ```
>     rewriter.startOpModification(packOp);
>     packOp.getSourceMutable().assign(source); // or .set(); I don't remember. :p
>     packOp.getDestMutable().assign(dest);
>     rewriter.finalizeOpModification(packOp);
> ```

Added the Patch here: https://github.com/llvm/llvm-project/pull/111261
