### ISSUE TITLE
Why is the size of the exported mnist_test.bin file 0 bytes?

### ISSUE THREAD

**Issue by hphyhl** [iree-org/iree#18787]
https://github.com/iree-org/iree/tree/f9fa934c649749b30fc4be05d9cef78eb043f0e9/samples/vision_inference

**Comment by IanWood1** [comment]
I tried it quickly and didn't have any issues. Maybe `cat` or `python3` failed (e.g. mnist_test.png was deleted or in wrong dir)?

**Comment by pyl3000** [comment]
Thank you. This problem has been solved.

**Comment by hphyhl** [comment]
> I tried it quickly and didn't have any issues. Maybe `cat` or `python3` failed (e.g. mnist_test.png was deleted or in wrong dir)?

Thank you. This problem has been solved.
