### ISSUE TITLE
failed to legalize operation 'hal.interface.constant.load'

### ISSUE THREAD

**Issue by pdhirajkumarprasad** [iree-org/iree#18845]
### What happened?

For the attached IR, seeing error as 

```
model.modified.mlir:780:12: error: failed to legalize operation 'hal.interface.constant.load'
    %203 = arith.index_cast %202 : i64 to index
           ^
model.modified.mlir:14:3: note: called from
```

command: 

```
iree-compile model.modified.mlir --iree-hal-target-backends=llvm-cpu -o compiled_model.vmfb --iree-llvmcpu-target-cpu=host
```

[model.modified.mlir.txt](https://github.com/user-attachments/files/17455304/model.modified.mlir.txt)

### What component(s) does this issue relate to?

Compiler

**Comment by ScottTodd** [comment]
This issue isn't actionable as-is. Please fill out the entire issue template, including version information.

For compiler errors, please also include context from `--mlir-print-ir-before-all` or similar, so developers can see which passes and IR led up to the failure.

Closing for now, feel free to re-open with more context.
