### ISSUE TITLE
Sharded toy-sized Llama fails compilation silently in conversion to stream

### ISSUE THREAD

**Issue by sogartar** [iree-org/iree#18878]
### What happened?

The model fails compilation in ConvertToStreamPass (iree-stream-conversion) without a meaning error reported.
Other iterations of the model did not fail like that.

### Steps to reproduce your issue

1. Download [sharded-toy-llama-convert-to-stream-failure.zip](https://github.com/user-attachments/files/17498959/sharded-toy-llama-convert-to-stream-failure.zip) and extract.
2. Run `compile.sh`.

### What component(s) does this issue relate to?

Compiler

### Version information

a400cde96289706512ac873591a9711c81edc244

**Comment by ScottTodd** [comment]
General tips: https://iree.dev/developers/debugging/model-development/

Maybe try print ir after all, attach a debugger, and/or enable asserts.

**Comment by dan-garvey** [comment]
https://gist.github.com/dan-garvey/f975db5df158fcbd46bfc58d70abb1f3

this is the ir after `iree-stream-conversion` fails

**Comment by dan-garvey** [comment]
It is failing here: https://github.com/iree-org/iree/blob/00104b551e1c2fc72e0f8f5b33bbfabfc25ee393/compiler/src/iree/compiler/Dialect/Stream/Transforms/ConvertToStream.cpp#L227

It is failing the affinity analysis

**Comment by benvanik** [comment]
I suspect you have invalid affinity annotations
(would be nice to print an error there - I thought the analysis would print something but I guess not - it's likely that the solver did not converge on a solution)

**Comment by benvanik** [comment]
`--debug-only=iree-util-explorer,iree-util-dfx` can help for the solver stuff, but `--iree-stream-annotate-input-affinities` and ensuring it matches what you think is the easiest.

**Comment by benvanik** [comment]
quick glance shows that you probably have bad annotations on `util.global private @__constant_tensor_` ops - they are all device 0 but are used on device 1.

(thanks for posting the IR @dan-garvey! a zip file with a shell script to run is unlikely to get triaged with a reasonable latency but I'll look at IR and error messages while cooking dinner :)

**Comment by dan-garvey** [comment]
[Solver] fixpoint iteration done after: 33/32 iterations

[Solver] finalized 1528 abstract elements
[Solver] fixed point iteration failed to converge

**Comment by dan-garvey** [comment]
probably coming from things like these in the original ir:

```
util.global private @__auto.constant_19_280_torch.float32 = dense_resource<__auto.constant_19_280_torch.float32> : tensor<19x280xf32>
util.global private @__auto.constant_19_280_torch.float32$1 = dense_resource<__auto.constant_19_280_torch.float32$1> : tensor<19x280xf32>
```

so non-weight constants not externalized by the python layer

**Comment by dan-garvey** [comment]
is the `$1` meant to be a kind of device annotation?

**Comment by sogartar** [comment]
@dan-garvey 
> so non-weight constants not externalized by the python layer

The rotary embedding layer for example constructs its table during initialization and it becomes a torch.nn.Module parameter, which gets embedded in the MLIR program.
