### ISSUE TITLE
Nix shell for building IREE 

### ISSUE THREAD

**Issue by bredamatt** [iree-org/iree#18914]
### Request description

Hi,

I am currently setting up a nix shell to build IREE with StableHLO support.
However, I am getting a weird error whilst running `cmake`, which doesn't reveal what goes wrong other than that the error is on `Makefile:166`. Because there is a reliance upon a generator with `CMakeLists.txt` in the IREE repo, I am having a hard time figuring out how I can back track this error.

### What component(s) does this issue relate to?

Compiler

### Additional context

AFAIK there is no documentation on reproducible / isolated builds of IREE with configurability atm. It would be very useful with a nix, or containerized version of IREE that can be used without having to change my local environment, which set me on the path towards building a `nix` shell with IREE in it.

I am happy to share what I have, if necessary.

There is simply too much that can go wrong with having to manually setup the environment, and this is slowing my productivity a lot.

**Comment by ScottTodd** [comment]
Which makefile are you running? The best supported build system we have is CMake (https://iree.dev/building-from-source/getting-started/)

We don't have many maintainers/contributors using Nix (https://nixos.org/ and https://github.com/NixOS/nix, right?), so we'd need to pick apart the questions here a bit to offer concrete advice.

If you see errors building LLVM targets like `LLVMDebugInfoCodeView`, that's _mostly_ outside of our direct control and might be better to debug with the upstream build system (e.g. https://llvm.org/docs/GettingStarted.html#getting-the-source-code-and-building-llvm).

**Comment by bredamatt** [comment]
Currently using cmake as seen from my snippet:

```
buildPhase = ''
      mkdir build && cd build
      
      export LLVM_DIR=${pkgs.llvmPackages_17.llvm.dev}/lib/cmake/llvm
      export MLIR_DIR=${pkgs.llvmPackages_17.mlir}/lib/cmake/mlir
      export CLANG_DIR=${pkgs.llvmPackages_17.clang}/lib/cmake/clang
      
      cmake -G Ninja -B build/ -S ../.. \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_C_COMPILER=${pkgs.llvmPackages_17.clang}/bin/clang \
        -DCMAKE_CXX_COMPILER=${pkgs.llvmPackages_17.clang}/bin/clang++ \
        -DLLVM_DIR=${pkgs.llvmPackages_17.llvm.dev}/lib/cmake/llvm \
        -DMLIR_DIR=${pkgs.llvmPackages_17.mlir}/lib/cmake/mlir \
        -DIREE_BUILD_PYTHON_BINDINGS=ON \
        -DIREE_TARGET_BACKEND_LLVM_CPU=ON \
        -DIREE_HAL_DRIVER_LOCAL_SYNC=ON \
        -DIREE_COMPILER_TRANSLATE_TO_STABLEHLO=ON \
        -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
        -DCMAKE_INSTALL_PREFIX=$out \
        ${platformSpecificCMakeOptions}
    '';

    installPhase = ''
      cd ..
      mkdir -p $out/{bin,lib,include}
      cat Makefile
      make VERBOSE=1 -j$(nproc) install
      cp -r install/* $out/
    '';
```

It is failing in the `buildPhase` at the moment and I don't see any errors associated with `LLVMDebugInfoCodeView`, but more an error without any particular information:

```
       > [ 14%] Linking CXX static library libspirv-cross-msl.a
       > cd /tmp/nix-build-iree-stablehlo.drv-2/source/build/third_party/spirv_cross && /nix/store/a7v65i1rs0jbdjq578pk9h689fif32sd-cmake-3.29.6/bin/cmake -P CMakeFiles/spirv-cross-msl.dir/cmake_clean_target.cmake
       > cd /tmp/nix-build-iree-stablehlo.drv-2/source/build/third_party/spirv_cross && /nix/store/a7v65i1rs0jbdjq578pk9h689fif32sd-cmake-3.29.6/bin/cmake -E cmake_link_script CMakeFiles/spirv-cross-msl.dir/link.txt --verbose=1
       > /nix/store/22a6p8311lg3z4ksrjbj018i7z3vgkva-clang-wrapper-16.0.6/bin/ar qc libspirv-cross-msl.a "CMakeFiles/spirv-cross-msl.dir/spirv_msl.cpp.o"
       > /nix/store/22a6p8311lg3z4ksrjbj018i7z3vgkva-clang-wrapper-16.0.6/bin/ranlib libspirv-cross-msl.a
       > make[2]: Leaving directory '/private/tmp/nix-build-iree-stablehlo.drv-2/source/build'
       > [ 14%] Built target spirv-cross-msl
       > make[1]: Leaving directory '/private/tmp/nix-build-iree-stablehlo.drv-2/source/build'
       > make: *** [Makefile:166: all] Error 2
       For full logs, run 'nix log /nix/store/3p9s9xgbv0g7c0198nj3hhmrgi51a8sg-iree-stablehlo.drv'.
```

could this be associated with my LLVM version?

**Comment by ScottTodd** [comment]
Do you need these options?

> -DLLVM_DIR=${pkgs.llvmPackages_17.llvm.dev}/lib/cmake/llvm \
>         -DMLIR_DIR=${pkgs.llvmPackages_17.mlir}/lib/cmake/mlir \

That looks like the "bring-your-own-llvm" path we support. Note that "support" there is brittle since LLVM is very complicated. Our standard way of building relies on the LLVM version that we keep in our `llvm-project` submodule at https://github.com/iree-org/iree/tree/main/third_party. See docs at https://github.com/iree-org/iree/tree/main/build_tools/llvm

Also not sure what this is?

> -DIREE_COMPILER_TRANSLATE_TO_STABLEHLO=ON \

**Comment by bredamatt** [comment]
Thanks for pointing these out! 

I thought:
> -DIREE_COMPILER_TRANSLATE_TO_STABLEHLO=ON

was the STABLEHLO option, but I see now in CMAKELists that it is:
> -DIREE_INPUT_STABLEHLO=ON

Thanks!

**Comment by bredamatt** [comment]
Btw, I am happy to open a PR if my nix-shell works.
