### ISSUE TITLE
[llama] Unfolded `tensor.extract_slice` after SetEncodingPass

### ISSUE THREAD

**Issue by IanWood1** [iree-org/iree#18956]
## Problem
Compiling llama 405b without data tiling explicitly disabled causes a bunch of `tensor.extract_slice` dispatches. Here is the difference in dispatch count:

| Data-Tiling Opt| Dispatch Count | Command (only differs in dt status) |
|--------------------|----------------|---------|
| Enabled (Default)           | 10,218         | `iree-compile llama405b_fp16.mlir --iree-hal-target-device=hip --iree-hip-target=gfx942 -o /dev/null --iree-scheduling-dump-statistics-file=dt-stats.csv --iree-scheduling-dump-statistics-format=csv` |
| Disabled           | 9,083          | `iree-compile llama405b_fp16.mlir --iree-hal-target-device=hip --iree-hip-target=gfx942 --iree-opt-data-tiling=false -o /dev/null --iree-scheduling-dump-statistics-file=no-dt-stats.csv --iree-scheduling-dump-statistics-format=csv` |

## Cause
This is because `SetEncodingPass` generates `unset_encoding` and `extract_slice` ops:
```mlir
%47 = iree_encoding.unset_encoding %46 : tensor<?x16384xf32, #iree_encoding.encoding<operand_index = 2 : index, op_type =  matmul, element_types = [f16, f16, f32], user_indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1)>], round_dims_to = array<i64: 32, 32, 32>>> -> tensor<?x16384xf32>

// IMPORTANT: %41 is equal to the dynamic dimension, making this a no-op
%extracted_slice_11 = tensor.extract_slice %47[0, 0] [%41, 16384] [1, 1] : tensor<?x16384xf32> to tensor<?x16384xf32>
```

## Minimum Repro:
1. Grab following MILR
```mlir
util.func public @main(%42 : tensor<?x16384xf16>, %43 : tensor<16384x16384xf16>, %45 : tensor<?x16384xf32>) -> (tensor<?x16384xf32>){
  %0 = tensor.empty() : tensor<4x32x64x128xf16>
  %46 = linalg.matmul_transpose_b ins(%42, %43 : tensor<?x16384xf16>, tensor<16384x16384xf16>) outs(%45 : tensor<?x16384xf32>) -> tensor<?x16384xf32>
  util.return %46  : tensor<?x16384xf32>
}
```
2. Run `iree-compile tmp.mlir  --iree-hal-target-device=hip --iree-hip-target=gfx942  -o /dev/null --mlir-print-ir-after=iree-dispatch-creation-clone-producers-into-dispatch-regions`. Or print after `SetEncodingPass` to see the IR generated
3. The `extract_slice` that gets created by `SetEncodingPass` never gets folded/canonicalized

-----

Hash 0bb6d92496c252c51f057fddd8e01826f2a1f241

cc @Max191 @hanhanW @MaheshRavishankar here's a repro from what I mentioned this morning. I'm not familiar with this pass, but max said the `extract_slice` might be left over from some old path.

**Comment by MaheshRavishankar** [comment]
At least we know we need to turn it off
