### ISSUE TITLE
Dynamic Matmul-Truncf Fusion

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#18976]
We are missing a fusion opportunity for matmul-truncf for dynamic tiled matmuls. See attached IR:

```
func.func @main(%arg0: tensor<?x128xf16>, %arg1: tensor<128x128xf16>) -> tensor<?x128xf16> {
  %c0 = arith.constant 0 : index
  %dim = tensor.dim %arg0, %c0 : tensor<?x128xf16>
  %0 = tensor.empty(%dim) : tensor<?x128xf32>
  %1 = linalg.matmul ins(%arg0, %arg1 : tensor<?x128xf16>, tensor<128x128xf16>) outs(%0 : tensor<?x128xf32>) -> tensor<?x128xf32>

  %2 = tensor.empty(%dim) : tensor<?x128xf16>
  %3 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%1 : tensor<?x128xf32>) outs(%2 : tensor<?x128xf16>) {
  ^bb0(%in: f32, %out: f16):
    %5324 = arith.truncf %in : f32 to f16
    linalg.yield %5324 : f16
  } -> tensor<?x128xf16>
  return %3 : tensor<?x128xf16>
}
```

**Comment by MaheshRavishankar** [comment]
eh... this should work. Hold on.

**Comment by MaheshRavishankar** [comment]
uh... this is the stupid data-tiling thing.

Add `--iree-opt-data-tiling=false`

**Comment by IanWood1** [comment]
> uh... this is the stupid data-tiling thing.
> 
> Add `--iree-opt-data-tiling=false`

related issue here https://github.com/iree-org/iree/issues/18956

**Comment by hanhanW** [comment]
I'll prioritize the fix. The plan is listed on discord: https://discord.com/channels/689900678990135345/1254843174111678555/1302016562974294127

**Comment by MaheshRavishankar** [comment]
> I'll prioritize the fix. The plan is listed on discord: https://discord.com/channels/689900678990135345/1254843174111678555/1302016562974294127

We have a WAR by just using `--iree-opt-data-tiling=false`, but your fix is a good QoL improvement!
