### ISSUE TITLE
Dynamic attention (decode)

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#18975]
We need a dynamic length flash attention that works with decode. This means a dynamic KV sequence length and length-1 decode sequence length.

[decode_dyn_attention.zip](https://github.com/user-attachments/files/17592076/decode_dyn_attention.zip)

**Comment by Groverkss** [comment]
Compiles with https://github.com/iree-org/iree/commit/c31583338a1d8cd099211d8980af7e2dd5791ce5
