### ISSUE TITLE
Address fusion dominance issue

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#18971]
Fusion can result in dominance issues due to out of order fusion with transfers. This can be observed in the following example.

[fusion_failure.zip](https://github.com/user-attachments/files/17591476/fusion_failure.zip)

**Comment by rsuderman** [comment]
Once fixed this optimization can be landed:
https://github.com/nod-ai/SHARK-Platform/pull/399

**Comment by MaheshRavishankar** [comment]
cc @IanWood1

**Comment by MaheshRavishankar** [comment]
What command line are using? I hit an error only in Stream
```
fusion_failure.mlir:3:3: error: 'stream.context.resolve' op failed to resolve affinity: only HAL device affinities are supported
  util.global private @__auto.token_embd.weight$1 {iree.abi.affinity = #hal.device.promise<@__device_1>} = #stream.parameter.named<"model"::"token_embd.weight"> : tensor<128256x4096xf16>
  ^
fusion_failure.mlir:3:3: note: see current operation: %15:2 = "stream.context.resolve"() <{affinity = #hal.device.promise<@__device_1>}> : () -> (!hal.device, i64)
fusion_failure.mlir:3:3: error: failed to legalize operation 'stream.parameter.load' that was explicitly marked illegal                                                                                                                       util.global private @__auto.token_embd.weight$1 {iree.abi.affinity = #hal.device.promise<@__device_1>} = #stream.parameter.named<"model"::"token_embd.weight"> : tensor<128256x4096xf16>
  ^
fusion_failure.mlir:3:3: note: see current operation: %15:6 = "stream.parameter.load"(%14, %14, %14, %14, %14, %13, %11, %10, %9, %9) <{affinity = #hal.device.promise<@__device_1>, operandSegmentSizes = array<i32: 5, 5, 0>, source_keys\ = ["token_embd.weight", "blk.0.attn_norm.weight", "blk.0.attn_q.weight.shard.1", "blk.0.attn_k.weight.shard.1", "blk.0.attn_v.weight.shard.1"], source_scope = "model"}> : (i64, i64, i64, i64, i64, index, index, index, index, index) ->\ (!stream.resource<constant>, !stream.resource<constant>, !stream.resource<constant>, !stream.resource<constant>, !stream.resource<constant>, !stream.timepoint)
```

**Comment by benvanik** [comment]
`#hal.device.promise` should not exist down in stream - there's a pass at the head of the pipeline that resolves those to `#hal.device.affinity`

**Comment by MaheshRavishankar** [comment]
I am just using `iree-compile` with usual flags. Anything else I need to add?

**Comment by MaheshRavishankar** [comment]
Also what I was asking is, I dont see any error at the fusion level.

**Comment by MaheshRavishankar** [comment]
I also tried with the extra flags that i usually use
```
    --iree-global-opt-propagate-transposes=true \
    --iree-opt-aggressively-propagate-transposes=true \
    --iree-opt-data-tiling=false \
    --iree-opt-aggressively-propagate-transposes=true \
    --iree-preprocessing-pass-pipeline="builtin.module(util.func(iree-preprocessing-generalize-linalg-matmul-experimental))"
```

and they seem to hit the same error.

**Comment by benvanik** [comment]
ah the reproducer has the promises but no devices defined - we'll have to make that better at the frontend level - running `--iree-hal-device-assignment-pipeline` is needed before dumping the reproducer when the frontend doesn't put any device information in the program. You could also pass `--iree-hal-target-device=__device_0=hip[0] --iree-hal-target-device=__device_1=hip[1]` to iree-compile with this input to specify them.

(the frontend is saying "someone promises to say what "__device_0" and "__device_1" are when they compile" so you have to say what they are, or the frontend has to bake out what it wants the devices to be explicitly - the former is better if exporting models that want to be tried on different device targets/different target settings and is preferred, but we should be including the device flags in issues with reproducers)

**Comment by rsuderman** [comment]
Ah this was generated post `--compile-to=input`. I assumed that we were all doing `--iree-hal-target-device=hip[0]` when doing full compilation.

**Comment by MaheshRavishankar** [comment]
Same error. This is my compilation line
```
iree-compile --mlir-print-local-scope --mlir-print-ir-after-all --mlir-print-ir-before-all --mlir-disable-threading --iree-hal-target-backends=rocm --iree-hip-target=gfx942 fusion_failure.mlir --ir\ee-global-opt-propagate-transposes=true --iree-opt-aggressively-propagate-transposes=true --iree-opt-data-tiling=false --iree-dispatch-creation-enable-aggressive-fusion '--iree-hal-target-device=hip[0]' '--iree-preprocessing-pass-pipel\ine=builtin.module(util.func(iree-preprocessing-generalize-linalg-matmul-experimental))'
```

**Comment by benvanik** [comment]
remove `--iree-hal-target-backends=rocm` (iree-hal-target-backends is deprecated and should not be used anymore)

this uses two devices and you have to explicitly specify them - if you only pass one device the other device won't be defined

**Comment by rsuderman** [comment]
Looks like this was since fixed at head.
