### ISSUE TITLE
Op uses negative memory exceeding 65536 byte limit

### ISSUE THREAD

**Issue by KyleHerndon** [iree-org/iree#19077]
### What happened?

When trying to compile a llama 8b fp8, I get the following error:
[fp8error.txt](https://github.com/user-attachments/files/17682931/fp8error.txt)

### Steps to reproduce your issue

I used the following command to compile:
```
../iree-build/tools/iree-compile ./fp8_kv.mlir   --iree-hal-target-device=hip[0] --iree-hal-target-device=hip[1] --iree-hal-target-device=hip[2] --iree-hal-target-device=hip[3] --iree-hal-target-device=hip[4] --iree-hal-target-device=hip[5] --iree-hal-target-device=hip[6] --iree-hal-target-device=hip[7]   --iree-hal-executable-debug-level=3 --iree-hip-target=gfx942 --iree-hal-force-indirect-command-buffers=true --iree-stream-resource-memory-model=discrete --iree-hip-legacy-sync=false   -o fp8.vmfb
```

### What component(s) does this issue relate to?

Compiler

### Version information

41ed8c04fdd42cc6990ec7714001bbdd2077531e

### Additional context

[MLIR](https://sharkpublic.blob.core.windows.net/sharkpublic/fp8_kv.mlir)

**Comment by pdhirajkumarprasad** [comment]
Attached is relatively smaller IR to reproduce the issue

[fp8_kv_small.mlir.txt](https://github.com/user-attachments/files/17706057/fp8_kv_small.mlir.txt)

**Comment by IanWood1** [comment]
Looks like another `bit-truncate -> gather` fusion issue, https://github.com/iree-org/iree/pull/18939 solves the issue but has some regressions for sdxl that need to get resolved

**Comment by dan-garvey** [comment]
@IanWood1 can you ping me when the fix lands?

**Comment by qedawkins** [comment]
negative memory is really silly though, I'm going to take a quick look at what codegen is doing.

**Comment by dan-garvey** [comment]
I think rob said its probably multiplying by a dynamic dimension somewhere

**Comment by qedawkins** [comment]
No looks like it really is just an enormous amount
```
%alloc = memref.alloc() : memref<4x131056x8x64x2xf16, #gpu.address_space<workgroup>>
```
I can fix this with a pattern to fuse gathers + elementwise ops. Another thing I'd like to try eventually is add a mechanism to raise gather indices to linalg operands after tiling (as with certain tile sizes the "gather" part will go away). This way we can resume tile + fuse. Then in cases where that's not possible we can lower to loops early and fuse through the `tensor.extract` (which is basically a 1-d slice).

For now I'll go for the simple solution though (which lets us keep the fusion too :) )
