### ISSUE TITLE
--iree-flow-export-benchmark-funcs fails on dynamic shapes

### ISSUE THREAD

**Issue by ziereis** [iree-org/iree#19134]
### What happened?

```
func.func @add_tensors(%arg0: tensor<?x10xf32>, %arg1: tensor<?x10xf32>) -> tensor<?x10xf32> {
  %c0 = arith.constant 0 : index
  %dim = tensor.dim %arg0, %c0 : tensor<?x10xf32>
  %init = tensor.empty(%dim) : tensor<?x10xf32>

  %result = linalg.generic {
    indexing_maps = [
      affine_map<(d0, d1) -> (d0, d1)>,
      affine_map<(d0, d1) -> (d0, d1)>,
      affine_map<(d0, d1) -> (d0, d1)>
    ],
    iterator_types = ["parallel", "parallel"]
  } ins(%arg0, %arg1 : tensor<?x10xf32>, tensor<?x10xf32>)
    outs(%init : tensor<?x10xf32>) {
    ^bb0(%a: f32, %b: f32, %c: f32):
      %sum = arith.addf %a, %b : f32
      linalg.yield %sum : f32
  } -> tensor<?x10xf32>

  return %result : tensor<?x10xf32>
}

```

results in:

```
add_dyn.mlir:1:1: error: unsupported buffer view import tensor type on <block argument> of type '!hal.buffer_view' at index: 0 used as 'tensor<?x10xf32>'
func.func @add_tensors(%arg0: tensor<?x10xf32>, %arg1: tensor<?x10xf32>) -> tensor<?x10xf32> {
```
[ir_dump.txt](https://github.com/user-attachments/files/17731187/ir_dump.txt)

### Steps to reproduce your issue

iree-compile --iree-flow-export-benchmark-funcs

**Comment by benvanik** [comment]
The pass cannot be used with dynamic shapes (and many other things). It's only intended for developers to make small microbenchmarks  of slices of IR and not for entire programs or all I/O conditions (or state, or parameters, or, ... etc). The benchmark tool can run most models by providing input or the preferred route is for the user to author a benchmark themselves.

Think of the pass like something that you'd run on a C program: if your C program is a single stateless function it may work, but if you take command line flags or external pointers as arguments there's not much the pass can make up that's meaningful.
