### ISSUE TITLE
Llama 3.1 8B fp16 TP8 sharded fails to compile for CPU and GPU

### ISSUE THREAD

**Issue by aviator19941** [iree-org/iree#19263]
### What happened?

When I try to compile the sharded Llama 3.1 8b fp16 [IR](https://gist.github.com/aviator19941/bab5886f53f2fd0b3b8458519148542c) for CPU or GPU:

I get this error for CPU:
https://gist.github.com/aviator19941/82bceb2624571d446da0964440790fde

and this error for GPU:
https://gist.github.com/aviator19941/89761b3bbb6ace5a6945de667e6d1e39

I tried to use these flags that were suggested to be used when compiling Llama as well:
`
--iree-dispatch-creation-enable-aggressive-fusion=true --iree-global-opt-propagate-transposes=true --iree-opt-aggressively-propagate-transposes=true --iree-opt-data-tiling=false --iree-preprocessing-pass-pipeline='builtin.module(util.func(iree-preprocessing-generalize-linalg-matmul-experimental))' --iree-hal-indirect-command-buffers=true --iree-stream-resource-memory-model=discrete --iree-hip-legacy-sync=false --iree-hal-memoization=true --iree-opt-strip-assertions
`

### Steps to reproduce your issue

1. wget the IR: https://gist.github.com/aviator19941/bab5886f53f2fd0b3b8458519148542c
2. Try to compile for CPU:
`
../iree-build-no-trace/tools/iree-compile 8b_f16_tp8_decomposed.mlir -o=8b_f16_tp8_decomposed_cpu.vmfb --iree-hal-target-device=llvm-cpu[0] --iree-hal-target-device=llvm-cpu[1] --iree-hal-target-device=llvm-cpu[2] --iree-hal-target-device=llvm-cpu[3] --iree-hal-target-device=llvm-cpu[4] --iree-hal-target-device=llvm-cpu[5] --iree-hal-target-device=llvm-cpu[6] --iree-hal-target-device=llvm-cpu[7]
`
3. CPU error: https://gist.github.com/aviator19941/82bceb2624571d446da0964440790fde
4. Try to compile for GPU:
`
../iree-build-no-trace/tools/iree-compile 8b_f16_tp8_decomposed.mlir --iree-hip-target=gfx942 -o=8b_f16_tp8_decomposed.vmfb --iree-hal-target-device=hip[0] --iree-hal-target-device=hip[1] --iree-hal-target-device=hip[2] --iree-hal-target-device=hip[3] --iree-hal-target-device=hip[4] --iree-hal-target-device=hip[5] --iree-hal-target-device=hip[6] --iree-hal-target-device=hip[7]
`
5. GPU error: https://gist.github.com/aviator19941/89761b3bbb6ace5a6945de667e6d1e39

### Version information

iree-base-compiler 3.1.0rc20241121

**Comment by sogartar** [comment]
About the CPU compilation error. I made a [fix](https://github.com/nod-ai/shark-ai/pull/576) when exporting for the unsharded case where we want no device affinities. This is a sharded variant. At a first glance argument and global parameter affinities look fine. It is probably something with the `flow.tensor.transfer` ops.

**Comment by nirvedhmeshram** [comment]
The GPU error is in an attention dispatch failing.  It is going down the `LLVMGPUDistribute` which is not the pipeline we want for it. [Here](https://gist.github.com/nirvedhmeshram/310ff2f613442196bd16044fecc770ba) is the Input IR for it.

You can run this with
```
iree-compile attention_dispatch.mlir --iree-hip-target=gfx942 -o=8b_f16_tp8_decomposed.vmfb --iree-hal-target-backends=rocm --compile-from=executable-sources --mlir-print-ir-after-all &> output.mlir
```

[Here](https://gist.github.com/nirvedhmeshram/ddfaa3872f741957c2f7dfb4b3d39808) is the full dump.

Looks like it has some dynamic shapes so I am guessing vector distribute bailed on it.

CC @raikonenfnu @Groverkss @kumardeepakamd

**Comment by aviator19941** [comment]
> The GPU error is in an attention dispatch failing. It is going down the `LLVMGPUDistribute` which is not the pipeline we want for it. [Here](https://gist.github.com/nirvedhmeshram/310ff2f613442196bd16044fecc770ba) is the Input IR for it.
> 
> You can run this with
> 
> ```
> iree-compile attention_dispatch.mlir --iree-hip-target=gfx942 -o=8b_f16_tp8_decomposed.vmfb --iree-hal-target-backends=rocm --compile-from=executable-sources --mlir-print-ir-after-all &> output.mlir
> ```
> 
> [Here](https://gist.github.com/nirvedhmeshram/ddfaa3872f741957c2f7dfb4b3d39808) is the full dump.
> 
> Looks like it has some dynamic shapes so I am guessing vector distribute bailed on it.
> 
> CC [@raikonenfnu](https://github.com/raikonenfnu) [@Groverkss](https://github.com/Groverkss) [@kumardeepakamd](https://github.com/kumardeepakamd)

I think @sogartar suggested we not compile with `--iree-hal-target-backends=rocm` since it is considered a legacy flag and will be removed in the future.

**Comment by nirvedhmeshram** [comment]
> > The GPU error is in an attention dispatch failing. It is going down the `LLVMGPUDistribute` which is not the pipeline we want for it. [Here](https://gist.github.com/nirvedhmeshram/310ff2f613442196bd16044fecc770ba) is the Input IR for it.
> > You can run this with
> > ```
> > iree-compile attention_dispatch.mlir --iree-hip-target=gfx942 -o=8b_f16_tp8_decomposed.vmfb --iree-hal-target-backends=rocm --compile-from=executable-sources --mlir-print-ir-after-all &> output.mlir
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [Here](https://gist.github.com/nirvedhmeshram/ddfaa3872f741957c2f7dfb4b3d39808) is the full dump.
> > Looks like it has some dynamic shapes so I am guessing vector distribute bailed on it.
> > CC [@raikonenfnu](https://github.com/raikonenfnu) [@Groverkss](https://github.com/Groverkss) [@kumardeepakamd](https://github.com/kumardeepakamd)
> 
> I think [@sogartar](https://github.com/sogartar) suggested we not compile with `--iree-hal-target-backends=rocm` since it is considered a legacy flag and will be removed in the future.

Yes I was just using that to be concise, you can use the new flags and get the same error too.

**Comment by Groverkss** [comment]
On the GPU side, this looks like it is coming because of inner unit dims for K2 dimension of attention. We could either collapse those unit dims to make it work, or I can send a patch tommorow to add support for multiple M/N dimension for intrinsic targetting.

**Comment by IanWood1** [comment]
> On the GPU side, this looks like it is coming because of inner unit dims for K2 dimension of attention. We could either collapse those unit dims to make it work, or I can send a patch tommorow to add support for multiple M/N dimension for intrinsic targetting.

@aviator19941 for some context, is this a regression or something that never worked?


Edit: I thought this might have to do with `tensor.concat` but instead it looks like we need to be able to canonicalize

```mlir
%expanded_8645 = tensor.expand_shape %28622 [[0, 1, 2], [3, 4]] output_shape [4, %21, 1, 1, 128]
	 : tensor<?x128xf16> into tensor<4x?x1x1x128xf16>
%collapsed_8653 = tensor.collapse_shape %expanded_8645 [[0], [1, 2, 3], [4]]
	 : tensor<4x?x1x1x128xf16> into tensor<4x?x128xf16>
```
to a single expand shape. `ComposeCollapseOfExpand` in `ReshapeOpsUtils.h` doesn't handle this case.

**Comment by kumardeepakamd** [comment]
This is a regression @IanWood1 . "I can send a patch tommorow to add support for multiple M/N dimension for intrinsic targetting" <- this seems ile rt thing to do.

**Comment by Groverkss** [comment]
https://github.com/iree-org/iree/pull/19336

This should fix it
