### ISSUE TITLE
Elementwise Op Fusion fails due to `complex` tensor operands

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#19288]
The following code snippet fails during elementwise op fusion. This is likely due to using `complex` operands. Compile command was a simple `iree-compile --iree-hal-target-backends=rocm --iree-hip-target=gfx1100`

https://gist.github.com/rsuderman/f693b0c9ea72a9914c41b33dbb54789e

This includes a `linalg_ext.scatter` to a `complex` destination formed from a tensor bitcast. Ultimately it should fuse into the prior block as well.

**Comment by IanWood1** [comment]
Upstream fix here https://github.com/llvm/llvm-project/pull/117667,

-----

In the short term, `--iree-opt-strip-assertions` should prevent the crash in most cases

**Comment by IanWood1** [comment]
Fixed with the most recent llvm integrate.
