### ISSUE TITLE
Can not execute from shark_turbine.aot import *

### ISSUE THREAD

**Issue by FlintWangacc** [iree-org/iree#19301]
### What happened?

```python
from shark_turbine.aot import *
```
produce
![Image](https://github.com/user-attachments/assets/91057a59-db5f-4f6f-b3c2-996b5a4897bc)

### Steps to reproduce your issue

1. build iree compiler
2. source ../iree-build/.env && export PYTHONPATH
3. pip install shark-turbine
4. from shark_turbine.aot import *

**Comment by ScottTodd** [comment]
The shark_turbine package (https://pypi.org/project/shark-turbine/) was replaced with the iree-turbine package (https://pypi.org/project/iree-turbine/).

Historical context: https://groups.google.com/g/iree-discuss/c/Bk58qwhaPEU/m/NwD90RwoAAAJ

Tracking issue for the migration: https://github.com/iree-org/iree-turbine/issues/28

We should probably push a new version of the shark-turbine package that issues a warning/error explaining the migration...
