### ISSUE TITLE
[CPU] Shortfin LLM Accuracy Degradation Followup

### ISSUE THREAD

**Issue by IanWood1** [iree-org/iree#19411]
### Background 
I'm creating this as a followup to https://github.com/nod-ai/shark-ai/issues/437 which was fixed with the revert here: https://github.com/iree-org/iree/pull/19070. I'm trying to re-land https://github.com/iree-org/iree/pull/19032, but It is still encountering some accuracy/correctness issues with Shark-AI's Shortfin LLM integration tests. 

### Current State
After investigation, I have determined that PR https://github.com/iree-org/iree/pull/19032 was not the root cause of the issue, but rather was exposing some sort of bug in CPU code-gen. This aligns with my expectation, as I find it hard to believe that PR https://github.com/iree-org/iree/pull/19032 would cause correctness issues without generating illegal MLIR.

I ran the offending commit against the shortfin LLM integration tests for both CPU and GPU (gfx1100). The correctness issue was only present when running on CPU giving an output of "6000000000000000" instead of the expected "6 7 8". NOTE: there has been some regression and GPU no longer works at all on iree main possibly related to https://github.com/iree-org/iree/issues/19347

### Minimal Reproduction
I have created an archive so that it is easier to follow along with my attempted reproduction steps [repro.tar.gz](https://github.com/user-attachments/files/18049941/repro.tar.gz). It contains: 
- `model.mlir` the exported model from shortfin integration tests
- Two vmfbs to compare with/without the commit
- Scripts to generate inputs, run the models, and compare outputs

However, you will need to get the GGUF file. If running the integration tests, there will be a symlink to it at  `/tmp/pytest-of-$USER/pytest-current/cpu_llm_server_test0/model.mlir`. I'm not sure if there is an easier way to get this since im not too familar with huggingface, you could also check 
```
$HOME/.cache/huggingface/hub/models--SlyEcho--open_llama_3b_v2_gguf/blobs/46978f4b19536f0d443ae75d2627fc4c15a8e1e85285f87b67710f8449633d63
```

#### Step 1: get weights
The provided scripts expect a symlink to it in the working directory with the name `sharktank-llama.gguf`

#### Step 2: compile models to vmfb (optional)
Generate vmfb for top of main (62903cc49f38e205fccf5e8a221a08e48abac345 at the time of writing)
```bash
git checkout 62903cc49f38e205fccf5e8a221a08e48abac345
<build iree-compile>
iree-compile --iree-hal-target-device=llvm-cpu --iree-llvmcpu-target-cpu=host model.mlir -o top-of-main.vmfb
```
Generate vmfb for reverted (bad) version 
```bash
git revert  be41632
<build iree-compile>## (note: there are conflicts, but they are only for pkgci and not the c++ source)
iree-compile --iree-hal-target-device=llvm-cpu --iree-llvmcpu-target-cpu=host model.mlir -o with-revert.vmfb
```

#### Step 3: generate data + run model + compare outputs
```bash
## Prefill
python gen-prefill.py && ./run-prefill.sh && python comp-prefill.py
## Decode
python gen-decode.py && ./run-decode.sh && python comp-decode.py
```
From the results, I found that the outputs of prefill and decode are exactly the same. I'm not sure how to diagnose this further or identify the root cause of the issue.

I'd appreciate any help investigating this issue further. A thank you to @renxida for assisting me.
cc @rsuderman @MaheshRavishankar

**Comment by MaheshRavishankar** [comment]
Awesome job following up and trying to narrow down errors. Tracking down such hard errors are absolutely worth it, so thanks for doing it!

There might be a couple of things to try. Try running the original CPU test with `-iree-opt-data-tiling=false` 
Case 1) Lets say the error stays with `--iree-opt-data-tiling=false`. In that case the CPU and the GPU paths should be creating the exact same dispatches. You should be able to compile with `--iree-flow-trace-dispatch-tensors` and compare the output between CPU and GPU for each dispatch (I just used a diff tool).
Case 2) Lets say the error goes away with `--iree-opt-data-tiling=false`. That is the harder case. There might be still ways to narrow down the error, but they require a lot of steps. We can get to that if this is needed.

> NOTE: there has been some regression and GPU no longer works at all on iree main possibly related to https://github.com/iree-org/iree/issues/19347

What was the last commit that you tried with GPU where this passed? If you have the setup already try with `--iree-codegen-block-dynamic-dimensions-of-contractions=false` and see if it gives the right results.

**Comment by IanWood1** [comment]
#### 1) Fixing GPU
 `--iree-codegen-block-dynamic-dimensions-of-contractions=false` didn't seem to fix the shortfin tests with GPU and neither did checking out iree at be41632fdca0ba6102d48a8cf7108fca67297056 (the commit reverting the one I'm trying to reland). Both times I got the same failures:
```
FAILED app_tests/integration_tests/llm/shortfin/cpu_llm_server_test.py::test_llm_server[model_test_dir0-write_config0-llm_server0] - app_tests.integration_tests.llm.utils.AccuracyValidationException: Expected '6wearwearwearwearwearwearwearwearwearwearwearwearwearwearwear' to start with '6 7 8'
FAILED app_tests/integration_tests/llm/shortfin/cpu_llm_server_test.py::test_llm_server[model_test_dir1-write_config1-llm_server1] - app_tests.integration_tests.llm.utils.AccuracyValidationException: Expected '6wearwearwearwearwear🏾wearwearwearwearwearwearwearwearasa' to start with '6 7 8'
```
It's possible a change to Shark-AI is making this go down a different path?


#### 2) CPU without DT
I tested with with the revert applied + `--iree-opt-data-tiling=false` and got the same incorrect output as before so I should be able to compare dispatches once I find a way to get accurate results from the GPU backend.

-----

Wouldn't diffing the output of `--iree-flow-trace-dispatch-tensors` be difficult because the KV cache is so large and would be dumped several times?

**Comment by MaheshRavishankar** [comment]
Yes... But I just used Beyond Compare. All you need is the first failing dispatch.

**Comment by IanWood1** [comment]
I compared CPU vs GPU and the first dispatch was the same as https://github.com/iree-org/iree/issues/19347 (except larger tensors).


I also compared CPU `--iree-llvmcpu-target-cpu=host` vs CPU without and found a multiresult/transpose/truncate dispatch was the first difference. This seems like it might be the culprit (since the commit was multi-use fusion related). Here's the a gist with the MLIR https://gist.github.com/IanWood1/a7bcd131b09ddcab167731bae1f74465. Also, note that the executable-source is for GPU but it is the same dispatch.

**Comment by MaheshRavishankar** [comment]
> I compared CPU vs GPU and the first dispatch was the same as [#19347](https://github.com/iree-org/iree/issues/19347) (except larger tensors).
> 
> I also compared CPU `--iree-llvmcpu-target-cpu=host` vs CPU without and found a multiresult/transpose/truncate dispatch was the first difference. This seems like it might be the culprit (since the commit was multi-use fusion related). Here's the a gist with the MLIR https://gist.github.com/IanWood1/a7bcd131b09ddcab167731bae1f74465. Also, note that the executable-source is for GPU but it is the same dispatch.

Nice! Might be a vectorization of transpose related issues. cc @pashu123  can you please help triage the issue.

**Comment by pashu123** [comment]
> > I compared CPU vs GPU and the first dispatch was the same as [#19347](https://github.com/iree-org/iree/issues/19347) (except larger tensors).
> > I also compared CPU `--iree-llvmcpu-target-cpu=host` vs CPU without and found a multiresult/transpose/truncate dispatch was the first difference. This seems like it might be the culprit (since the commit was multi-use fusion related). Here's the a gist with the MLIR https://gist.github.com/IanWood1/a7bcd131b09ddcab167731bae1f74465. Also, note that the executable-source is for GPU but it is the same dispatch.
> 
> Nice! Might be a vectorization of transpose related issues. cc [@pashu123](https://github.com/pashu123) can you please help triage the issue.

sure, let me take a look.

**Comment by pashu123** [comment]
I can reproduce the same! Looking into the dump.

**Comment by IanWood1** [comment]
@pashu123 Great! 
Thinking about this again, I'm not quite sure that this is the issue causing the test failure (but it it definitely worth tracking down). It was found after reverting and comparing with/without the cpu target info. I was unable to find a difference in output with/without the commit... and i'm not quite sure why. 

>The correctness issue was only present when running on CPU giving an output of "6000000000000000" instead of the expected "6 7 8".

Looking at the test output, both the "good" and "bad" runs return `6` for the first run of decode. It might be the case that the difference only occurs after running the first call to `decode`.

**Comment by IanWood1** [comment]
Okay I think I finally found the problem and @qedawkins 's PR https://github.com/iree-org/iree/pull/19389 seems to fix it.


The truncated 8b IR [here](https://gist.github.com/IanWood1/97e9d5141462021595e24e3141711386) allowed me to narrow the problem down to a single [failing dispatch](https://gist.github.com/IanWood1/0a258f8a8a4a090fbc9c2c77a0adf316). The truncated model returns the KV cache after the first write and only (thankfully) included a single dispatch that was modified by this PR. Using the commit from the linked PR alleviated the problem in my tests as well as shortfin integration tests.


I'm not sure why but the problem also completely went away when using `--iree-flow-trace-dispatch-tensors`.

**Comment by qedawkins** [comment]
Makes sense, tracing added another use to an unused tied value which caused stream to properly allocate memory for it.
