### ISSUE TITLE
Tracking issue for dropping the local revert of https://github.com/llvm/llvm-project/pull/116470

### ISSUE THREAD

**Issue by MaheshRavishankar** [iree-org/iree#19448]
The change to add 1:N `matchAndRewrite` method seems to have caused few failures in IREE. This is the tracking issue. 

First issue is related to `iree-stream-conversion` pass.

Repro : 
```
module attributes {stream.affinity.default = #hal.device.affinity<@__device_0>} {
  util.global private @__device_0 = #hal.device.target<"local", [#hal.executable.target<"llvm-cpu", "static", {cpu = "generic", cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-\i128:128-f80:128-n8:16:32:64-S128", link_embedded = false, link_static = true, native_vector_size = 16 : i64, static_library_output = "simple_mul_c_module.o", target_triple = "x86_64-unknown-linux-gnu"}>]> : \!hal.device
  flow.executable private @simple_mul_dispatch_0 {
    flow.executable.export public @simple_mul_dispatch_0_elementwise_4_f32 workgroups() -> (index, index, index) {
      %x, %y, %z = flow.dispatch.workgroup_count_from_slice
      flow.return %x, %y, %z : index, index, index
    }
    builtin.module {
      func.func @simple_mul_dispatch_0_elementwise_4_f32(%arg0: !flow.dispatch.tensor<readonly:tensor<4xf32>>, %arg1: !flow.dispatch.tensor<readonly:tensor<4xf32>>, %arg2: !flow.dispatch.tensor<writeonly:tens\or<4xf32>>) {
        %0 = flow.dispatch.tensor.load %arg0, offsets = [0], sizes = [4], strides = [1] : !flow.dispatch.tensor<readonly:tensor<4xf32>> -> tensor<4xf32>
        %1 = flow.dispatch.tensor.load %arg1, offsets = [0], sizes = [4], strides = [1] : !flow.dispatch.tensor<readonly:tensor<4xf32>> -> tensor<4xf32>
        %2 = tensor.empty() : tensor<4xf32>
        %3 = linalg.generic {indexing_maps = [affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>], iterator_types = ["parallel"]} ins(%0, %1 : tensor<4xf32>, tensor<4xf32>) outs(%2 :\ tensor<4xf32>) {
        ^bb0(%in: f32, %in_0: f32, %out: f32):
          %4 = arith.mulf %in, %in_0 : f32
          linalg.yield %4 : f32
        } -> tensor<4xf32>
        flow.dispatch.tensor.store %3, %arg2, offsets = [0], sizes = [4], strides = [1] : tensor<4xf32> -> !flow.dispatch.tensor<writeonly:tensor<4xf32>>
        return
      }
    }
  }
  util.func public @simple_mul(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub, iree.reflection = {iree.abi.declaration = "sync func @simple_mul(%input0: tensor\<4xf32>, %input1: tensor<4xf32>) -> (%output0: tensor<4xf32>)"}} {
    %0 = hal.tensor.import %arg0 "input0" : !hal.buffer_view -> tensor<4xf32>
    %1 = hal.tensor.import %arg1 "input1" : !hal.buffer_view -> tensor<4xf32>
    %2 = flow.dispatch @simple_mul_dispatch_0::@simple_mul_dispatch_0_elementwise_4_f32(%0, %1) : (tensor<4xf32>, tensor<4xf32>) -> tensor<4xf32>
    %3 = hal.tensor.export %2 "output0" : tensor<4xf32> -> !hal.buffer_view
    util.return %3 : !hal.buffer_view
  }
}
```

Repro command

```
iree-opt --iree-stream-conversion repro.mlir
```

It throws the following error

```
Trying to match "mlir::iree_compiler::(anonymous namespace)::ConvertDispatchOp"
LLVM ERROR: pattern 'mlir::iree_compiler::(anonymous namespace)::ConvertDispatchOp' does not support 1:N conversion
```

The pattern pointed to here https://github.com/iree-org/iree/blob/7177c29f9b2d9e255b63987f5dfff174ec2afc2f/compiler/src/iree/compiler/Dialect/Stream/Conversion/FlowToStream/Patterns.cpp#L715

That error is confusion since this is seems like a 1-1 replacement. One op (with N results) is replaced with another op (with N results). 

Recording from Discord steps from @matthias-springer  to fix issues

[12:23 AM]Matthias Springer: I would approach it as follows:
-  Look for does not support 1:N conversion in the test failures.
- For each pattern that does not support 1:N, replace the OpAdaptor of the matchAndRewrite with OneToNOpAdaptor. That's how you update 1:1 patterns to 1:N. When you call functions of the adaptor, you will now get ValueRange instead of Value. From there you have to continue on a case-by-case basis:
- Check if the ValueRange always contains a single Value. In that case you can probably put an assert and take the single value.
- If the ValueRange has more than one value, dump the all values and try to understand what the pattern is supposed to do with these values. (It's probably similar to what the addArgumentMaterialization callback was doing, followed by the pattern logic.) Update the patterns accordingly.
- The tests should now be passing.
- Cleanup: Delete all addArgumentMaterialization. Look for UnrealizedConversionCast in your code base. Ideally they should all be gone. (If not, you may be able to delete them. With 1:N conversion support in place, explicit usage of UnrealizedConversionCastOp should no longer be necessary in most cases.)

Going to start doing this now.

**Comment by MaheshRavishankar** [comment]
Took a bit of debugging, couple of things to note. The Stream conversion has a mismatch between the type converter and the operand converters. The operations convert `tensor<...>` to `stream.resource<*>` while the type converted seems to convert `tensor<...>` to `stream.resource<*>, index`. This is why operations like `ConvertToDispatchOp` conversions go down the 1:N conversion path cause dialect conversion sees that this is a 1:N conversion.

For example
```
util.func public @simple_mul(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub, iree.reflection = {iree.abi.declaration = "sync func @simple_mul(%input0: tensor\<4xf32>, %input1: tensor<4xf32>) -> (%output0: tensor<4xf32>)"}} {
    %0 = hal.tensor.import %arg0 "input0" : !hal.buffer_view -> tensor<4xf32>
    %1 = hal.tensor.import %arg1 "input1" : !hal.buffer_view -> tensor<4xf32>
    %2 = flow.dispatch @simple_mul_dispatch_0::@simple_mul_dispatch_0_elementwise_4_f32(%0, %1) : (tensor<4xf32>, tensor<4xf32>) -> tensor<4xf32>
    %3 = hal.tensor.export %2 "output0" : tensor<4xf32> -> !hal.buffer_view
    util.return %3 : !hal.buffer_view
  }
```

with the new change gets converted to

```
util.func public @simple_mul(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub, iree.reflection = {iree.abi.declaration = "sync func @simple_mul(%input0: tensor<4\xf32>, %input1: tensor<4xf32>) -> (%output0: tensor<4xf32>)"}} {
  %element_type_f32 = hal.element_type<f32> : i32
  %dense_row_major = hal.encoding_type<dense_row_major> : i32
  %c4 = arith.constant 4 : index
  hal.buffer_view.assert<%arg0 : !hal.buffer_view> message("input0") shape([%c4]) type(%element_type_f32) encoding(%dense_row_major)
  %0 = stream.tensor.sizeof on(#hal.device.affinity<@__device_0>) tensor<4xf32> : index
  %1 = stream.tensor.import on(#hal.device.affinity<@__device_0>) %arg0 : !hal.buffer_view -> tensor<4xf32> in !stream.resource<external>{%0}
  %2 = stream.async.transfer %1 : !stream.resource<external>{%0} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<*>{%0}
  %3:2 = builtin.unrealized_conversion_cast %2 : !stream.resource<*> to !stream.resource<*>, index
  %4 = hal.tensor.import %arg0 "input0" : !hal.buffer_view -> tensor<4xf32>
  %element_type_f32_0 = hal.element_type<f32> : i32
  %dense_row_major_1 = hal.encoding_type<dense_row_major> : i32
  %c4_2 = arith.constant 4 : index
  hal.buffer_view.assert<%arg1 : !hal.buffer_view> message("input1") shape([%c4_2]) type(%element_type_f32_0) encoding(%dense_row_major_1)
  %5 = stream.tensor.sizeof on(#hal.device.affinity<@__device_0>) tensor<4xf32> : index
  %6 = stream.tensor.import on(#hal.device.affinity<@__device_0>) %arg1 : !hal.buffer_view -> tensor<4xf32> in !stream.resource<external>{%5}
  %7 = stream.async.transfer %6 : !stream.resource<external>{%5} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<*>{%5}
  %8:2 = builtin.unrealized_conversion_cast %7 : !stream.resource<*> to !stream.resource<*>, index
  %9 = hal.tensor.import %arg1 "input1" : !hal.buffer_view -> tensor<4xf32>
  %c0 = arith.constant 0 : index
  %10 = stream.tensor.sizeof on(#hal.device.affinity<@__device_0>) tensor<4xf32> : index
  %11 = stream.async.dispatch on(#hal.device.affinity<@__device_0>) @simple_mul_dispatch_0::@simple_mul_dispatch_0_elementwise_4_f32(%2[%c0 to %0 for %0], %7[%c0 to %5 for %5]) : (!stream.resource<*>{%0}, !st\ream.resource<*>{%5}) -> !stream.resource<*>{%10}
  %12:2 = builtin.unrealized_conversion_cast %11 : !stream.resource<*> to !stream.resource<*>, index
  %13 = flow.dispatch @simple_mul_dispatch_0::@simple_mul_dispatch_0_elementwise_4_f32(%4, %9) : (tensor<4xf32>, tensor<4xf32>) -> tensor<4xf32>
  %14 = stream.resource.size %12#0 : !stream.resource<*>
  %15 = stream.async.transfer %12#0 : !stream.resource<*>{%14} from(#hal.device.affinity<@__device_0>) -> to(#hal.device.affinity<@__device_0>) !stream.resource<external>{%14}
  %16 = stream.tensor.export on(#hal.device.affinity<@__device_0>) %15 : tensor<4xf32> in !stream.resource<external>{%14} -> !hal.buffer_view
  %17 = hal.tensor.export %13 "output0" : tensor<4xf32> -> !hal.buffer_view
  util.return %17 : !hal.buffer_view
}
```

Notice the `builtin.conversion_cast` are being inserted to do what the `TypeConverter` sees as a mismatch. But in reality all the uses of the `builint.conversion_cast` dont want to use the 0-th result of the operation. Instead they want to use the operand of the operation. If I just extract the operand in the conversion pattern the pass works as expected.

Couple of strange things
1) The Stream conversion pattern and type converters need to agree. This is the reason for the mismatch
2) It is strange to me that the `OneToNOpAdaptor` is returning the results of the `builtin.unrealized_conversion_cast` instead of the operand directly, but maybe that makes sense.

cc @nithinsubbiah  and @matthias-springer

**Comment by matthias-springer** [comment]
The result IR is the final IR and not the output of `-debug`, right?

> But in reality all the uses of the builint.conversion_cast dont want to use the 0-th result of the operation. Instead they want to use the operand of the operation. 

This could be the result of folding two `unrealized_conversion_cast` ops.

Can run the dialect conversion with `ConversionConfig::buildMaterializations = false` and [`kDumpMaterializationKind = true`](https://github.com/llvm/llvm-project/pull/119532/files#diff-6d17755f82b46e25824f962e78609e94c540f26e129d74b65ecba6a266a71126R36)? This will skip materializations and instead put `unrealized_conversion_cast` ops with an attribute that indicates the type of materialization. That should make it easier to understand what's going on. (I would expect no argument materializations. These should all be gone.)
