### ISSUE TITLE
Rework function signature/descriptor API

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#1979]
`iree_vm_function_signature_t` was never fully implemented, and as such I've had to resort to hacks like passing around stack frame information in `iree_vm_function_t` for #1172. There's also multiple functions for getting reflection attributes and other random things that would be nice to clean up now that we have more usage info.

* [x] Remove `iree_vm_function_t` register info (move to signature?)
* [ ] ~~Make `iree_vm_function_signature_t` useful for validating I/O (register types, etc)~~
* [x] Combine `iree_vm_get_function_reflection_attr`, `iree_vm_function_reflection_attr`
* [ ] ~~Add more linkage types to avoid the need for function name-based queries (`__init`, `__deinit`, etc)~~
* [ ] ~~Add a compact list of init/deinit functions to avoid name lookups~~
* [x] Add linkage types for reflection public functions vs. just those exported (#1224)

Some of this may entail hiding the structures such that we can fully indirectify the storage of this information (for when pulling from flatbuffers/rdata/etc).

**Comment by lipracer** [comment]
@benvanik I'am very interested in this project. I think i can start with Combine Interfact. The first interface is like Get, second is like Query.Is it necessary to modify the parameters of first interface when combine?

**Comment by lipracer** [comment]
Thanks
