### ISSUE TITLE
Add documentation explaining IREE's build systems and options

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#2111]
Build system configurations are also part of the codebase. It would be nice to have docs for them too so folks can understand how things are wired up and make changes and tweak configurations.

**Comment by GMNGeoffrey** [comment]
Assigning to me because I should probably write some of this. That doesn't mean others shouldn't feel free to write some documentation :-)

**Comment by benvanik** [comment]
Part of #3843's goal is to remove as much build configuration as possible which should reduce the number of docs that need to be written. The vcpkg deployment project's goal is to get every user of IREE able to do so via vcpkg (or something like it, even if just cmake install into dirs). The only people that should need the docs for build tooling should then be IREE maintainers/contributors and that should make them much more targeted, ideally in-situ with the build configuration, and easier to keep in sync with the build system.

**Comment by ScottTodd** [comment]
https://github.com/iree-org/iree/pull/9046 added _some_ information about Bazel and CMake. We don't have anything for "so folks can understand how things are wired up and make changes and tweak configurations" at the moment though.

However, this issue is quite stale, so I'm going to close it.
