### ISSUE TITLE
Failed to properly clean up all refcounted objects in TF Python tests

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#2900]
https://github.com/google/iree/pull/2899 fixed an issue where we used to have two alive contexts for each test: one in `cls._tar_modules` (created via `setUpClass()`) and one in `self._tar_modules` (created via `setUp()`). It fixes by removing the `cls._tar_mdoules`. However, this disables module compilation sharing. But, simply switch to always use `cls._tar_modules` does not work as shown by #2897. This indicates deeper issues in Python layer regarding refcounted object clean up. It might due to Python garbage collection on Python classes (as shown by #2896), or there might be an issue in Python bindings not properly call C/C++ APIs to release objects.

**Comment by phoenix-meadowlark** [comment]
Recompilation is fixed by (an updated) #2897.

**Comment by benvanik** [comment]
Already fixed? @antiagainst @phoenix-meadowlark

**Comment by phoenix-meadowlark** [comment]
> Already fixed? @antiagainst @phoenix-meadowlark

Not fixed so much as worked around. We store the pre-compiled modules in `_global*` variables instead of on the test case class.

**Comment by benvanik** [comment]
Closing as obsolete.
