### ISSUE TITLE
Remove global dialect registration from MLIR usage

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#2958]
Copying an issue filed elsewhere by @joker-eph :

---

The global registration for MLIR Dialects has been deprecated and will be removed upstream "soon", IREE needs to adjust to this change and stop using the existing dialect registration.

1) For passes, you need to override the method:
```
    virtual void getDependentDialects(DialectRegistry &registry) const {}
```
and register on the provided registry any dialect that this pass can produce:
```
    registry.insert<DialectClass>();
```
Passes defined in TableGen can provide this list in the `dependentDialects` list field.

2) For dialects, on construction you can register dependent dialects using the
provided MLIRContext: `context.getOrLoadDialect<DialectName>()`
This is useful if a dialect may canonicalize or have interfaces involving
another dialect.

3) For loading IR, dialect that can be in the input file must be explicitly
registered with the context. `MlirOptMain()` is taking an explicit registry for
this purpose.

```
  mlir::DialectRegistry registry;
  registry.insert<mlir::StandardOpsDialect>();
  registry.insert<mlir::xyz123::XYZ123Dialect>();
  return failed(mlir::MlirOptMain(argc, argv, "XYZ123 Pass Driver", registry));
```

Only operations from these two dialects can be in the input file. To include all
of the dialects in MLIR Core, you can populate the registry this way:

```
  mlir::registerAllDialects(registry);
```

4) For `mlir-translate` callbacks, as well as frontend, Dialects can be loaded in
the context before emitting the IR: `context.loadDialect<ToyDialect>()`

**Comment by marbre** [comment]
FYI: This has been partially addressed by fa9dcf2, which allowed an LLVM submodule update.

**Comment by joker-eph** [comment]
` fa9dcf2` is the code I wrote to minimally not break IREE, but it was written *before* opening this ticket: this ticket is really about the incoming removal of the global registry upstream.

**Comment by marbre** [comment]
> ` fa9dcf2` is the code I wrote to minimally not break IREE, but it was written _before_ opening this ticket: this ticket is really about the incoming removal of the global registry upstream.

Thanks for your comment. I just wanted to reference this commit (which made it into main *after* the ticket was opened), to keep track of changes related to this issue. Indeed a lot more needs to be done :)

**Comment by benvanik** [comment]
#3092 says it removed obsolete global dialect registration.
