### ISSUE TITLE
Make iree-flow-trace-dispatch-tensors print more values controllable

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#3001]
Current work around is to modify the length of the buffer manually.

https://github.com/google/iree/blob/6bd3b1dc13236566d1f8ee651cd3ab9b03dd8a1d/iree/modules/hal/hal_module.cc#L432-L444

Eg, replace 4096 with `4096*1024`, and 1024 with `1024*1024`.

**Comment by hanhanW** [comment]
https://github.com/google/iree/pull/3508 makes the default element count to be maximal.

**Comment by benvanik** [comment]
At some point before the HAL module was converted to C the trace output got a compiler-controlled string key.
