### ISSUE TITLE
Bazel Android Support

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#3284]
Adding support to build for android with Bazel shouldn't be hard. We should set this up

https://docs.bazel.build/versions/master/android-ndk.html

**Comment by ScottTodd** [comment]
I'd rather we not do this unless it's actually requested by enough users, or if it makes development significantly easier in some way. 

Supporting another platform + build system combination otherwise seems like unnecessary complexity.

fyi @KoolJBlack (we've discussed this a bit recently)

**Comment by benvanik** [comment]
Closing as obsolete.
