### ISSUE TITLE
Add int128 atomic support to iree/base/atomics.h

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#3453]
Spotted on pulling changes from `main` into `google` when building for android_x86 and android_arm:
```
./third_party/iree/iree/base/atomics.h:156:17: error: __int128 is not supported on this target
typedef _Atomic __int128 iree_atomic_int128_t;
```

**Comment by benvanik** [comment]
Looks like we can check for the existence of __SIZEOF_INT128__ to conditionally enable this (for NDK) - may be other defines we can use. I'll wrap that in some IREE_HAS_INT128 macro and then if I use these 128-bit CAS ops I'll guard them with that.

**Comment by ScottTodd** [comment]
👍 
Here's what Abseil does:
https://github.com/abseil/abseil-cpp/blob/d1de75bf540f091b4dfc860713d556e578c0f158/absl/base/config.h#L269-L298
https://github.com/abseil/abseil-cpp/blob/master/absl/numeric/int128.h

**Comment by benvanik** [comment]
This may still be needed for an actually atomic iree_atomic_slist_t (ABA workaround), but not blocking as the current "atomic" slist just uses a slim lock.

**Comment by benvanik** [comment]
If @bjacob doesn't need this for `iree_atomic_slist_t` then it's not worth it.
