### ISSUE TITLE
Check in generated VM opcode table for compilerless builds

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#357]
The opcode table is currently generated by tblgen, which then makes LLVM a requirement to build the runtime: https://github.com/google/iree/blob/master/iree/compiler/Dialect/VM/Tools/VMOpTableGen.cpp#L53-L82

I'd really like to keep the runtime building without the LLVM dependency so it's easier to get going on weird platforms. One idea would be to check in the generated opcode table header and then add a script to update it (and a CI action to ensure it is updated if opcodes change).

**Comment by benvanik** [comment]
This will get easier when we build the compiler as an installation, as having the compiler for the host will include the generated header as part of it's include/ install.

**Comment by ScottTodd** [comment]
A script would still help here. What we have now is commented out and stale: https://github.com/google/iree/blob/c3ea7a879abfa86aa7c0994afba2b19d7354a459/iree/vm/BUILD#L204-L210

(`gentbl` no longer exists, see https://github.com/google/iree/commit/b0f67e653aae6e6c0cf7886734f5ef500ba2e73c)

**Comment by benvanik** [comment]
in the great bytecode reworking I'll likely remove the tablegen->runtime path and just respecify things - at some point when we start to stabilize the binary format we want it to be hard to change things :)

**Comment by ScottTodd** [comment]
SG. So.... how can I regenerate this now?

I'm not sure how to construct a command to invoke `iree-tblgen` :/

```
λ ..\iree-build\iree\tools\iree-tblgen.exe -gen-iree-vm-op-table-defs D:\dev\projects\iree\iree\compiler\Dialect\VM\IR\VMOps.td -I D:\dev\projects\iree\third_party\llvm-project\mlir\include\mlir\Interfaces
D:\dev\projects\iree\iree\compiler\Dialect\VM\IR\VMOps.td:10:9: error: Could not find include file 'mlir/Interfaces/CallInterfaces.td'
include "mlir/Interfaces/CallInterfaces.td"
        ^
```

**Comment by benvanik** [comment]
uncomment and change gentbl to whatever the replacement was is what I'd do

**Comment by GMNGeoffrey** [comment]
This should be tested and the update procedure should be documented (and ideally simple)

**Comment by benvanik** [comment]
Have been doing this by hand for a year or so. It's not worth any infra work at this point.
