### ISSUE TITLE
regression_training_test is failing in MaterializeConstantPoolBuffers

### ISSUE THREAD

**Issue by rybakov** [iree-org/iree#3752]
Model training is failing on regression model with sgd optimizer with error
```
assertion failed at third_party/iree/iree/compiler/Dialect/HAL/Transforms/MaterializeConstantPoolBuffers.cpp:284 in uint32_t mlir::iree_compiler::IREE::HAL::MaterializeConstantPoolBuffersPass::makePatternFromSplatValue(mlir::Attribute): elementAttr.getType().getIntOrFloatBitWidth() <= 32
```

How to reproduce:
```
bazel run integrations/tensorflow/e2e/keras/train:regression_training_test_manual -- --target_backends=iree_vmla --optimizer=sgd
```

It fails with other optimizers too, but it would be great to make sgd work first.

**Comment by ScottTodd** [comment]
Oleg, can you attach repro details that don't involve integrations/tensorflow? Geoffrey just added an issue template with instructions for that: https://github.com/google/iree/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

Ben (on Discord) also suggested that the error is having 64 bit integers, which we don't support (so don't use them :P)

**Comment by benvanik** [comment]
We can enable 64-bit integers in some places, but certain kinds of actions (like splatting non-zero 64-bit constants being done here) is a system-level limitation (there's no way to do an 8-byte fill in metal/vulkan/etc) that we'd need to work around by synthesizing executables instead. Something we will support, but if we can avoid that until after the burndown sprint I'd prefer it.

**Comment by ScottTodd** [comment]
Is this still an issue?

**Comment by GMNGeoffrey** [comment]
> Is this still an issue?

Yes :-D

**Comment by benvanik** [comment]
Closing as obsolete.
