### ISSUE TITLE
Extract `!quant.uniform` types and pack into tflite function signature for `TfLiteQuantizationParams`

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#3972]
The tflite importer some some quantization stuff and produces signatures like:
```mlir
func @QuantizeConv2D(
  tensor<1x224x224x3x!quant.uniform<u8:f32, 7.812500e-03:128>>
) -> tensor<1x112x112x32x!quant.uniform<u8:f32, 0.023528476789885875>>
```

It should be trivial during import to extract these into metadata we tag onto the `iree.reflection` attribute and then query them at runtime to satisfy `TfLiteTensorQuantizationParams` requests.

**Comment by benvanik** [comment]
I don't even know if this is a thing anymore or if we want to support it. Closing for now.

**Comment by stellaraccident** [comment]
That is an oddly specific title for what looks like a cat walked across the keyboard.
