### ISSUE TITLE
pyiree.rt.load_module should implicitly convert from bytes

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#4437]
Presently code like this is needed:

```
iree_module = ireert.load_module(ireert.VmModule.from_flatbuffer(binary), config=iree_config)
```

**Comment by alliemartens** [comment]
@stellaraccident Old issue alert! Still active?

**Comment by rsuderman** [comment]
I believe this is all set now. It has been a long time since I saw `str` vs `bytes` issues
