### ISSUE TITLE
iree-translate buries error messages under thousands of lines of IR

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#4561]
Running a python test recently, I noticed when it fails it seems to dump the entire module in generic asm format to stderr. This is a lot of output (thousands of lines) that overwhelms the user (and in my case, overflows their tmux buffer).

We should make this dump off by default, with an option to turn it on or send it to a file.

**Comment by phoenix-meadowlark** [comment]
I'm pretty sure the problem is `iree-translate`. I ran an `iree-translate` command and it dumped 7000 lines of unhelpful IR after two lines of error message.

**Comment by benvanik** [comment]
I suspect this may be chained emitError()'s (so multiple functions in the stack emit an error when something fails) where there's some top level one emitError()'ing on the entire module. Ideally we emit non-op errors at the high level ("compilation failed, whoops") and then only emit op errors on the actual ops that have issues.

**Comment by GMNGeoffrey** [comment]
> I'm pretty sure the problem is `iree-translate`. I ran an `iree-translate` command and it dumped 7000 lines of unhelpful IR after two lines of error message.

Yeah I also realized later yesterday that the iree-translate was doing the same thing

**Comment by benvanik** [comment]
I think iree-compile does something better here? Anything still actionable? And anyone who wants to do it?

**Comment by ScottTodd** [comment]
IIRC, this was fixed sufficiently with `--mlir-print-op-on-diagnostic=false`: https://github.com/iree-org/iree/blob/f1ec6e7c3284f2942aaa706fac68da43fd4b1f47/compiler/src/iree/compiler/API/python/iree/compiler/tools/core.py#L188-L192

https://mlir.llvm.org/docs/Diagnostics/#print-operation-on-diagnostic

> When a diagnostic is emitted on an operation, via `Operation::emitError/...`, the textual form of that operation is printed and attached as a note to the diagnostic. This option is useful for understanding the current form of an operation that may be invalid, especially when debugging verifier failures. An example output is shown below:
