### ISSUE TITLE
Add flexible configuration options to CMake for building/reusing tools

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#4662]
Relates to (and may resolve) https://github.com/google/iree/issues/4617

We have a few components like `iree_check_test` that require some tools to exist, but they don't necessarily need to (or can't, depending on the build configuration) build those tools themselves.

We currently use `-DIREE_HOST_BINARY_ROOT=$PWD/../build-host/install` and `CMAKE_CROSSCOMPILING` together with `iree_get_executable_path` as the main way to control what gets build or reused where:

https://github.com/google/iree/blob/8d74bfa28dd35203fba700aa1f1d88c200c848cd/build_tools/cmake/iree_macros.cmake#L115-L126

_<sub>separately, we can make that produce more helpful error messages if tools are missing</sub>_

However, this misses a few cases such as
* host runtime-only builds reusing the tools from a binary distribution
* Android builds excluding certain types of tests

Something like `IREE_USE_INSTALLED_HOST_TOOLS` was suggested on https://github.com/google/iree/pull/4627

**Comment by GMNGeoffrey** [comment]
I ran into this when trying to create a job that builds the IREE benchmarks (essentially import and compile some TFLite models). Currently they're built as part of the android build, which really doesn't make any sense and is not something I want to duplicate in the migration to GitHub actions. It appears that there's no way to build them using prebuilt host tools. You have to do a full host build.

**Comment by marbre** [comment]
> I ran into this when trying to create a job that builds the IREE benchmarks (essentially import and compile some TFLite models). Currently they're built as part of the android build, which really doesn't make any sense and is not something I want to duplicate in the migration to GitHub actions. It appears that there's no way to build them using prebuilt host tools. You have to do a full host build.

Can you elaborate which tools exactly where causing trouble and required a full host build?

**Comment by ScottTodd** [comment]
I think the change in https://github.com/iree-org/iree/commit/51893996b28d672e6ea56e6c4da7c86d8785059a was enough to enable this. I also audited our usage of `CMAKE_CROSSCOMPILING` and what we have today looks good (no unnecessary restrictions).

```diff
function(iree_get_executable_path OUTPUT_PATH_VAR EXECUTABLE)
-  if (NOT CMAKE_CROSSCOMPILING OR TARGET "${EXECUTABLE}")
+  if (NOT DEFINED IREE_HOST_BINARY_ROOT OR TARGET "${EXECUTABLE}")
```

we might want to rename or better document `IREE_HOST_BINARY_ROOT` to better convey "I want to use binary files / tools from this directory instead of building them from CMake targets" though.

I'll see if I can tweak https://github.com/iree-org/iree/blob/d9e6eb76a7c3818672fabe92e3993286b743a49f/.github/workflows/ci.yml#L513-L518 and https://github.com/iree-org/iree/blob/main/build_tools/cmake/build_benchmarks.sh to use that

**Comment by GMNGeoffrey** [comment]
I've also noticed that `IREE_HOST_BINARY_ROOT` actually has to point one directory *above* the root where IREE binaries are. It points to a directory containing a directory called "bin" that has the binaries. Basically it's an IREE install directory. I think we should probably name it based on that. Maybe `IREE_TOOLS_INSTALL`?
