### ISSUE TITLE
LLVM codegen is pulling in libc/libm (malloc, free, floorf) functions and shouldn't be

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#4717]
Here's where the flag is set:

https://github.com/google/iree/blob/af39f98403a30b85442130f25ceec5eb53e0c60d/iree/compiler/Dialect/HAL/Target/LLVM/internal/UnixLinkerTool.cpp#L127-L129

We punted on this back with https://github.com/google/iree/issues/2810 and now the flag is even leaking into our [Python documentation](https://github.com/google/iree/blob/main/bindings/python/pyiree/jax/README.md#ahead-of-time-compilation).

**Comment by ScottTodd** [comment]
In this zip file: [iree-llvmaot-linking.zip](https://github.com/google/iree/files/5922413/iree-llvmaot-linking.zip),
* `abs_ex_dispatch_0-staticcpp.so` uses the current code, with the flag
* `abs_ex_dispatch_0-nostaticcpp.so` omits the flag

Both were generated with

`iree-translate.exe -iree-mlir-to-vm-bytecode-module -iree-hal-target-backends=dylib-llvm-aot -iree-llvm-keep-linker-artifacts --iree-llvm-target-triple=aarch64-none-linux-android30 iree/tools/test/iree-run-module.mlir`
(then check the output to see where the linker artifacts went)

opening with https://cutter.re/ shows that both have some imports:
![image](https://user-images.githubusercontent.com/4010439/106828751-a6107000-663f-11eb-8b87-9586975e53cf.png)

<sub>Also see Discord discussions around [here](https://discord.com/channels/689900678990135345/689906000043573354/806674715586199592)</sub>

**Comment by ScottTodd** [comment]
The steps at https://google.github.io/iree/get-started/getting-started-android-cmake#dylib-llvm-aot-backend show how compile and run modules for Android using LLVM AOT. When I've tried that with `-static-libstdc++`, I get segfaults that can be symbolized with [ndk-stack](https://developer.android.com/ndk/guides/ndk-stack):

```
ndk-stack -sym iree-build-android\iree\tools -i crash_logs_from_logcat.txt
```

Sample symbolized crash:
```
********** Crash dump: **********
Build fingerprint: 'samsung/beyond1qlteue/beyond1q:10/QP1A.190711.020/G973U1UES4ETK1:user/release-keys'
#00 0x0000000000029088 /data/local/tmp/iree-run-module
std::__ndk1::basic_streambuf<char, std::__ndk1::char_traits<char> >::pubsync()
D:/dev/sdks/Android/ndk/android-ndk-r20b/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\streambuf:168:28
#01 0x0000000000028fe8 /data/local/tmp/iree-run-module
std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >::flush()
D:/dev/sdks/Android/ndk/android-ndk-r20b/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\ostream:948:36
#02 0x000000000020ca44 /data/local/tmp/iree-run-module
std::__ndk1::ios_base::Init::~Init()
/buildbot/src/googleplex-android/ndk-release-r20/external/libcxx/src\iostream.cpp:114:15
#03 0x00000000000ea21c /apex/com.android.runtime/lib64/bionic/libc.so (__cxa_finalize+344) (BuildId: d00c50b4798c95f2447d684ed3ea7dcb)
#04 0x00000000000e56a4 /apex/com.android.runtime/lib64/bionic/libc.so (exit+24) (BuildId: d00c50b4798c95f2447d684ed3ea7dcb)
#05 0x000000000007e89c /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+112) (BuildId: d00c50b4798c95f2447d684ed3ea7dcb)
```

**Comment by benvanik** [comment]
Somewhere in the linalg-on-tensors -> LLVM path we are getting mallocs:
```mlir
 %225 = llvm.call @malloc(%224) : (i64) -> !llvm.ptr<i8>
```

That's the root issue - malloc requires libc and shared linking, and the previous workaround was just to link in all of libc++. #4719 limits this to just libc (no more c++ global initializers and stuff!), but we still need to sever this dep: we can't have non-hermetic binaries.

**Comment by stellaraccident** [comment]
Also, we shouldn't have mallocs, but a malloc without a free seems worse?

**Comment by benvanik** [comment]
yep :P

**Comment by ScottTodd** [comment]
Checking the status here.

I'm testing https://github.com/google/iree/blob/main/iree/test/e2e/models/bert_encoder_unrolled_fake_weights.mlir.

When I flip these flags around: https://github.com/google/iree/blob/603b208f623e65eb48d8594c4ffc4218f36f41f5/iree/compiler/Dialect/HAL/Target/LLVM/internal/UnixLinkerTool.cpp#L96-L105

and compile for `-iree-llvm-target-triple=x86_64-linux-gnu` (on Windows)

I see `floorf` and `fmaf` undefined
```
ld.lld: error: undefined symbol: floorf
ld.lld: error: undefined symbol: fmaf
```

I actually am able to remove `--allow-undefined` from WASM linking (`-iree-hal-target-backends=wasm-llvm-aot`) though, thanks to https://github.com/google/iree/pull/5142: https://github.com/google/iree/blob/603b208f623e65eb48d8594c4ffc4218f36f41f5/iree/compiler/Dialect/HAL/Target/LLVM/internal/WasmLinkerTool.cpp#L93-L95

**Comment by benvanik** [comment]
(thanks for continuing to push on this)

**Comment by benvanik** [comment]
For the embedded ELF linker this is even more critical as we can't import any functions. The linker configuration is here:
https://github.com/google/iree/blob/96fd277e4424c8a195e4ab3b94a42a1824ae4322/iree/compiler/Dialect/HAL/Target/LLVM/internal/EmbeddedLinkerTool.cpp

**Comment by benvanik** [comment]
It looks like our options are:
1. statically link some libm variant
2. lower math to our own vector math/operations

I think I could wrangle 1 into working by taking newlib, openlibm, or musl and cross-compiling it to bitcode for some set of architectures and checking in the bitcode files.

That's a terrible mid/long-term option, though, especially if we care about performance as nothing in libm is fast. All those functions operate on scalars, have enough logic that they are never autovectorized, and often read/write the current system floating point rounding mode (which introduces a bunch of issues on its own) and set errno. _We do not want to be shipping things that call into libm, even when statically linked_.

Option 2 is the real way forward - we should be taking vector operations and lowering them to our own vector variants - we do this for some things already but our coverage is partial. I'd hoped that someone upstream in MLIR would have done this already (for their own sakes I'm really hoping the kernel codegen folks aren't also calling libm).

I'm not sure what the work difference is here between the two. It will take 1+ weeks to get option 1 working and will have a high maintenance burden because we check in per-arch binaries - and adding a new arch requires people to build/manage their own versions. If this is a short-term solution that we eventually cut that's probably ok (but an unfortunate time waste): it would at least unblock our cross-platform work. But if it's 1+ weeks to get proper lowerings for the 10-20 operations we support that seems like the better path given that we know we need to do that anyway.

@MaheshRavishankar / @asaadaldien what is your super rough estimate on 2? Do you know if this exists upstream somewhere that we could use, or if anyone is working on it? It feels like nice separable work (std/math -> vector) that maybe we could get help on?

Timing-wise we need to fix this issue ASAP - we can't do device multitargeting without it. I can take on option 1 if required (which it seems to be, and no one else is willing to touch this 😭), but want your eyes/planning on option 2 - the performance burden is more difficult to manage when we transparently call out to nasty scalar functions as we do today by calling out to a non-inlinable function for every vector element. If you're going to be doing CPU performance tuning the first thing you're going to want to do is not call out to libm as doing so will invalidate any measurements you make while trying to optimize work distribution as the work is off by 1000x. So even if I do 1 here and statically link in libm you're going to need to do this work anyway and will want to track that. Here I just want to make sure I won't be going down the 1 rabbit hole only for 2 to be done properly in a few weeks :)

I'll get started on a prototype for 1, but I'm hoping that you [looking at what we're doing today/will be doing with the static linking](https://sourceware.org/git/?p=newlib-cygwin.git;a=blob_plain;f=newlib/libm/mathfp/e_remainder.c;hb=refs/heads/master) will put some energy behind 2 :)

**Comment by MaheshRavishankar** [comment]
@benvanik responded on discord, and echoing that here. I am sorry that mot much progress has been made on this. This seems like we are taking libdevice approach and putting it on steroids. For libdevice in CUDA context, its a more constrained eco system (just the architectures NVIDIA supports). For different architectures, the burden here is probably much higher than having a priority list of functions that we want to burndown. To start with can we just list out the math functions we need. I think if we just dont link `libm`, see what fails and just add lowerings for them in the math dialect. In its own right its a valuable contribution to MLIR. It is not a blocker for anyone upstream, so it might actually just fall to us to deal with this).

**Comment by benvanik** [comment]
Agreed! And no worries - I've also not been pushing on this and hoping it would go away on its own, but like you say this seems to be another thing we are ahead of other upstream people on so we'll have to do it ourselves :(

We can see what's needed today by adding `-iree-llvm-link-embedded=true` - that'll build for our custom ELF loader that can't dynamically link against libm.so and you'll get compile-time link errors for anything not found ("undefined function floorf"). A triage of our current tests with that enabled dumped into a list is probably all we need for the initial burndown set. I don't suspect there are many things - the math dialect has 15 ops - just covering those may be easier than trying to figure out a subset only to find we need 14 of them and may as well just do them all :)

**Comment by asaadaldien** [comment]
@benvanik I ran `test/xla_ops` with `-iree-llvm-link-embedded=true` they all compile to vm modules but at fail with hal runtime:
```
iree/hal/local/elf/arch/x86_64.c:65: UNIMPLEMENTED; symbol-relative relocations not implemented; while invoking native function hal.executable.create; while calling import
```
how do we get the link time error ?

**Comment by benvanik** [comment]
Hmm that may still mean something is getting imported - `readelf -d` on the ELF should list the imports if any

**Comment by asaadaldien** [comment]
mmm, not seeing anything imported or I am not looking at the correct elf ?
```
$ readelf -h -d /tmp/floor_linked_llvm-874705.so
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x13e0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          3120 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         7
  Size of section headers:           64 (bytes)
  Number of section headers:         23
  Section header string table index: 21

Dynamic section at offset 0x730 contains 16 entries:
  Tag        Type                         Name/Value
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x0000000000000007 (RELA)               0x260
 0x0000000000000008 (RELASZ)             288 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          12
 0x0000000000000017 (JMPREL)             0x380
 0x0000000000000002 (PLTRELSZ)           24 (bytes)
 0x0000000000000003 (PLTGOT)             0x2830
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000006 (SYMTAB)             0x1c8
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0x230
 0x000000000000000a (STRSZ)              42 (bytes)
 0x0000000000000004 (HASH)               0x210
 0x0000000000000000 (NULL)               0x0
 ```

**Comment by benvanik** [comment]
attach elf and I can look? the GOT makes me think there's something

**Comment by benvanik** [comment]
looks like floorf is still getting imported
readelf -a:
```
Relocation section '.rela.plt' at offset 0x380 contains 1 entry:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000002848  000100000007 R_X86_64_JUMP_SLO 0000000000000000 floorf + 0

The decoding of unwind sections for machine type Advanced Micro Devices X86-64 is not currently supported.

Symbol table '.dynsym' contains 3 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND floorf
     2: 0000000000001670    16 FUNC    GLOBAL DEFAULT    7 iree_hal_executable_libra

Symbol table '.symtab' contains 4 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 0000000000002730     0 NOTYPE  LOCAL  HIDDEN    10 _DYNAMIC
     2: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND floorf
     3: 0000000000001670    16 FUNC    GLOBAL DEFAULT    7 iree_hal_executable_libra
```

the plt is what is throwing the error at runtime (it's trying to relocate relative to the imported floorf+0)

**Comment by benvanik** [comment]
A quick way to tell is that .dynsym should be 2 entries: 0 and the iree_hal_executable_library_query func.
We could check add a check during ELF loading that the table contains no imports so that we have a better error (it should be cheap enough to always do) - I'll try to do that this afternoon.

**Comment by asaadaldien** [comment]
Much better err ms :), thanks @benvanik. now I can see : 
```
iree/hal/local/elf/elf_module.c:481: UNAVAILABLE; ELF imports one or more symbols (trying 'floorf'); imports are not supported in the platform-agnostic loader; while invoking native function hal.executable.create; while calling import
iree/hal/local/elf/elf_module.c:481: UNAVAILABLE; ELF imports one or more symbols (trying 'fmodf'); imports are not supported in the platform-agnostic loader; while invoking native function hal.executable.create; while calling import
```

I will an LLVM pass that append `alwaysinline extern_weak` implementations of these functions to the Module so at link time we won't need external `libm`

**Comment by MaheshRavishankar** [comment]
Reopening this cause maybe this is not fully done. The part that is done is that the codegen itself doesnt insert calls to math library. 
The next step here was to flip the flag, `iree-llvm-link-embedded` to `true` by default. I was stuck on some bazel build issues (#6748 ) which @hcindyl fixed.
I am not sure what the remaining steps are.

**Comment by ScottTodd** [comment]
Sure, we can try flipping the flags now.

I noticed `floorf` and `fmaf` still appearing in a linked DLL for the [tflite_text_classification](https://colab.research.google.com/github/google/iree/blob/main/colab/tflite_text_classification.ipynb) model the other day:

![text_classification_linker_artifact_dependencies](https://user-images.githubusercontent.com/4010439/135298873-58d328d1-8281-476a-bab9-15bd82a18d4f.png)

is that expected?

**Comment by benvanik** [comment]
dlls are the system version and will have random things - the embedded linker is the one that needs all this (so you were looking at something generated with -iree-llvm-link-embedded=false)

**Comment by MaheshRavishankar** [comment]
Issue #7415 is currently a blocker to enable embedded link by default.

**Comment by ScottTodd** [comment]
Shall we call this fixed now?

There are still hacks on the system linker path that we could avoid if LLVM did not produce calls to libc/libm, but the embedded linker path is now the default and it uses our [`librt` solution](https://github.com/google/iree/tree/main/iree/compiler/Dialect/HAL/Target/LLVM/librt) for such calls.

https://github.com/google/iree/blob/981f48768a5a27baac818b8afa506abaf4ba75ad/iree/compiler/Dialect/HAL/Target/LLVM/internal/UnixLinkerTool.cpp#L78-L87

https://github.com/google/iree/blob/981f48768a5a27baac818b8afa506abaf4ba75ad/iree/compiler/Dialect/HAL/Target/LLVM/internal/EmbeddedLinkerTool.cpp#L107-L109

**Comment by benvanik** [comment]
![image](https://user-images.githubusercontent.com/75337/140092586-67eb37fe-9d66-41c7-aff8-a169b983810f.png)
Good job all - this was a tricky one!
If we don't have an issue for avoiding those scalar intrinsics we should - that'll be solely compiler-side work and maybe something purely upstream, so it'd be good to have a clear issue that we can share with people. At least now we aren't blocked on the embedded elf cases and can start on more multi-targeting/cross-compilation goodness!

**Comment by ScottTodd** [comment]
What would we like LLVM to emit instead of the scalar intrinsics? Vector operations? Here's some IR from the test I'm adding in https://github.com/google/iree/pull/7810: https://gist.github.com/ScottTodd/b7ca6277d8ef4ba4f6d2a6e726abb529 (with `tensor<f32>` changed to `tensor<3xf32>`)

**Comment by benvanik** [comment]
yeah - right now it'll run floor of 3xf32 as:
```c
for (int i = 0; i < 3; ++i) result[i] = floorf(input[i]);
```

which is:
```mlir
      ^bb3(%38: i64):  // 2 preds: ^bb2, ^bb4
        %39 = llvm.icmp "slt" %38, %33 : i64
        llvm.cond_br %39, ^bb4, ^bb5
      ^bb4:  // pred: ^bb3
        %40 = llvm.add %36, %38  : i64
        %41 = llvm.getelementptr %34[%40] : (!llvm.ptr<f32>, i64) -> !llvm.ptr<f32>
        %42 = llvm.load %41 : !llvm.ptr<f32>
        %43 = "llvm.intr.floor"(%42) : (f32) -> f32
        %44 = llvm.getelementptr %37[%40] : (!llvm.ptr<f32>, i64) -> !llvm.ptr<f32>
        llvm.store %43, %44 : !llvm.ptr<f32>
        %45 = llvm.add %38, %2  : i64
        llvm.br ^bb3(%45 : i64)
```

With the recent change to link in musl as bitcode it _may_ be possible for LLVM to inline the call to floor and then autovectorize it but I've never seen it do that (I think because the llvm.intr.floor gets turned into a call to floorf after the autovectorizer runs, but haven't verified that).

Note that even for an odd 3 elements it's almost always worth using proper vector instructions as the registers are likely coming from/going to other vector operations and using 3/4 SIMD lanes (in 128-bit vectors) would make that whole loop above 1 instruction + a masking operation. vroundss (single scalar) and vroundps (4 packed scalars) both execute in the same number of cycles for example.

**Comment by benvanik** [comment]
(this is really about orders of magnitude - 20 instructions -> 4 instructions, 160 bytes of instruction cache, RAM, and binary size consumption -> 16 bytes, 2+ branch predictor/etc reservations + extra hazard tracking -> 0, etc etc - all combine to yield outsized improvements to doing something better than a simple scalar for loop :)

**Comment by ScottTodd** [comment]
I'm going to close this for now, but we should still follow up on

> If we don't have an issue for avoiding those scalar intrinsics we should - that'll be solely compiler-side work and maybe something purely upstream, so it'd be good to have a clear issue that we can share with people.
