### ISSUE TITLE
Document canonical CMake options and make more robust

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#4739]
Just had a chance to bootstrap IREE on a fresh Linux environment with a bunch of python versions. Jotting down notes here to update docs.

```
cmake -G Ninja -B ../iree-build/ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DIREE_BUILD_XLA_COMPILER=ON -DIREE_BUILD_PYTHON_BINDINGS=ON -DPython3_EXECUTABLE=$(which python) -DPYTHON_EXECUTABLE=$(which python) .
```

Note that one of our dependencies appears to be using an old FindPython (might be flatcc) and one is using a new, so I included both Python3_EXECUTABLE and PYTHON_EXECUTABLE. I should triage more to discover what is going on here and warn if the situation appears awry. We seem to have lost the ability (on this machine) to not specify a python executable.

**Comment by ScottTodd** [comment]
Docs seem to cover this now: https://iree-org.github.io/iree/building-from-source/python-bindings-and-importers/#building-python-bindings . I think we can close this.
