### ISSUE TITLE
Make IREE dev assets installable

### ISSUE THREAD

**Issue by ewconnell** [iree-org/iree#4817]
I've been asked to work on Rust bindings for the IREE runtime api, and for now the work should be in a separate repository building against an "installed" build of IREE. 
I tried `cmake --install iree` after building, but it fails. Is this supposed to work or am I doing something incorrectly?

**Comment by stellaraccident** [comment]
The [CI installs](https://github.com/google/iree/blob/d369b7d5d9540268ddbc67c85ef6e15af6550d66/build_tools/github_actions/build_dist.py#L134) via the `install` or `install/strip` target: `cmake --build $BUILD_DIR --target install`

As we discussed, that currently does not install dev assets (headers/libraries) and should.

**Comment by GMNGeoffrey** [comment]
I think this would be a matter of adding the appropriate `install()` calls to `iree_cc_library`, yes? https://cmake.org/cmake/help/v3.13/command/install.html#installing-targets

**Comment by stellaraccident** [comment]
This is now available as of:
https://github.com/iree-org/iree-samples/tree/main/runtime-library

Also the compiler API should be compatible.
