### ISSUE TITLE
Finally remove `hal.ex.submit_and_wait`

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#5249]
Now that the HAL C API has stabilized it's possible to update the HAL dialect and remove this eyesore. This will allow for queuing multiple command buffers, asynchronous submission, and chaining of command buffers into a DAG.

I'll start by implementing and plumbing the new methods/ops and rewriting submit_and_wait to expand to them. This will let us continue to have a simple "just execute this" for handwriting/generating.

**Comment by ScottTodd** [comment]
Anything left to do for this particular issue, or did https://github.com/iree-org/iree/pull/9754 fix this?

**Comment by benvanik** [comment]
I think this part is done - the HAL C API doesn't yet have the right stuff but the op is gone and the compiler is doing the right thing 🥳
