### ISSUE TITLE
Add an `util.align` (or upstream) op for alignment math with folding/canonicalizations

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#5405]
Though not a critical hot path dynamic shapes - which then become dynamic sizes - can introduce a lot of IR performing alignment math of this form on byte offset and length calculations:
```c++
static inline uint64_t align(uint64_t value, uint64_t alignment) {
  return (value + (alignment - 1)) & ~(alignment - 1);
}
```

This leads to quite verbose IR and then lead to quite a few VM ops:
```mlir
%c-16 = constant -16 : index
%c15 = constant 15 : index
%0 = addi %arg1, %c15 : index
%1 = and %0, %c-16 : index
%2 = addi %1, %c15 : index
%3 = and %2, %c-16 : index
%4 = addi %arg2, %c15 : index
%5 = and %4, %c-16 : index
%6 = addi %3, %5 : index
%7 = addi %6, %c15 : index
%8 = and %7, %c-16 : index
%9 = addi %8, %c15 : index
%10 = and %9, %c-16 : index
```

Though it'd be fantastic to have something that could handle that as-is upstream it seems easier to support on a dedicated alignment op where a value produced by an align that is then fed into another align with a matching alignment would be able to elide the additional work. CSE does do at least some work here but without the semantics of the op it can't rearrange things enough to remove it all.

There may also be better bits of math than the above common technique that are more friendly to CSE/canonicalization we could explore.

**Comment by ScottTodd** [comment]
For reference when reproducing / iterating on this, the `packDynamic` test case in [pack_allocations.mlir](https://github.com/google/iree/blob/main/iree/compiler/Dialect/HAL/Transforms/test/pack_allocations.mlir) produces the IR in the original issue description: https://gist.github.com/ScottTodd/e13df0aebfffda10700357a1de2a41d2

Do we know of any larger programs/models in our set of samples that go down that path? I looked through a few I have output for and couldn't spot that pattern of IR.

**Comment by KoolJBlack** [comment]
@benvanik: Since #7583 added canonicalization for the previous TODO, can you elaborate on reach further into the IR and value-set analysis described in this  [TODO](https://github.com/google/iree/blob/7dc3d2a88ed3fda6c4571a76147a0b33e62795cd/iree/compiler/Dialect/Util/IR/UtilOpFolders.cpp#L315)?

**Comment by benvanik** [comment]
Done enough - future versions may want to use some of the upstream integer range analysis (but it may be too simple).
