### ISSUE TITLE
iree-run-mlir cannot execute MLIR from the TF integrations

### ISSUE THREAD

**Issue by phoenix-meadowlark** [iree-org/iree#5406]
The MLIR debug artifacts produced by the TensorFlow integrations are not consumable by `iree-run-mlir`. The error (checking) appears to have been added here: https://github.com/llvm/llvm-project/commit/109305e1046e68a26a99d3398434615ead1a8d2e.

```mlir
// Simplified version of iree_input.mlir from simple_arithmetic_test.py
module  {
  func @simple_mul(
      %arg0: tensor<4xf32> {tf._user_specified_name = "a"},
      %arg1: tensor<4xf32> {tf._user_specified_name = "b"}
    ) -> tensor<4xf32> attributes {
      iree.module.export,
      iree.reflection = {abi = "sip", abiv = 1 : i32, sip = "I12!S9!k0_0k1_1R3!_0"},
      tf._construction_context = "kEagerRuntime",
      tf._input_shapes = [#tf.shape<4>, #tf.shape<4>]} {  // The problematic attr.
    %0 = mhlo.multiply %arg0, %arg1 : tensor<4xf32>
    return %0 : tensor<4xf32>
  }
}
```

```sh
../iree-build/iree/tools/iree-run-mlir \
  -export-all \
  -iree-hal-target-backends=dylib-llvm-aot \
  -function-input="4xf32" \
  -function-input="4xf32" \
  /tmp/iree/modules/SimpleArithmeticModule/iree_input.mlir
```

```
loc("/tmp/iree/modules/SimpleArithmeticModule/iree_input.mlir split at line #1":2:324): error: 
#tf<"shape<4>"> : 'none' attribute created with unregistered dialect.
If this is intended, please call allowUnregisteredDialects() on the MLIRContext, or use -allow-unregistered-dialect with mlir-opt
```

`iree-run-mlir` doesn't allow using `-allow-unregistered-dialect`. 

This is being caused by the `tf._input_shapes` attribute. Deleting that appears to be a-ok, so we might want to strip it.

**Comment by benvanik** [comment]
We should be stripping that tf junk with https://github.com/google/iree/blob/main/integrations/tensorflow/iree_tf_compiler/TF/StripMetadata.cpp

is it possible the pipeline you are using to produce this is not running that somehow?

It is always run here:
https://github.com/google/iree/blob/402550bcbdd47ef96a599c3fdb5bbd071bbfb1a1/integrations/tensorflow/iree_tf_compiler/TF/Passes.cpp#L127-L128

**Comment by benvanik** [comment]
we also explicitly test that `tf._input_shapes` is removed, so I'm guessing the answer to my question is yes - but I'm not sure how:
https://github.com/google/iree/blob/000d64f50538ad381731263e81008e0f02cd5e8d/integrations/tensorflow/iree_tf_compiler/TF/test/strip_metadata.mlir#L11

**Comment by phoenix-meadowlark** [comment]
The arguments passed to `iree.compiler.tf.compile_module` are defined here
https://github.com/google/iree/blob/main/integrations/tensorflow/bindings/python/iree/tf/support/module_utils.py#L45-L89
and `iree_input.mlir` is requested here
https://github.com/google/iree/blob/main/integrations/tensorflow/bindings/python/iree/tf/support/module_utils.py#L77

Not sure how it could skip those passes...

**Comment by benvanik** [comment]
Me neither ;(
Stella may know when she's back.

**Comment by benvanik** [comment]
I suspect this has been fixed by the removal of SIP and tighter verification of the dialects present in the tensorflow tool outputs. Are you still hitting this @phoenix-meadowlark?

**Comment by phoenix-meadowlark** [comment]
I don't have my dev setup handy, but it might be worth creating a simple test that validates uses the bindings manually e2e:

- `iree.compiler.tf.compile_module`: `tf` --> `SavedModelV2` --> `mhlo`
- `iree.compiler.compile_asm`: `mhlo` --> `vmfb`
- `iree.runtime.maybe_this_changed`: `vmfb` --> executable func

**Comment by ScottTodd** [comment]
Sounds like the original issue here is fixed, but we should still expand our test coverage? Could fork that into a new issue...

**Comment by phoenix-meadowlark** [comment]
Should we close this now?
