### ISSUE TITLE
Lower vectors into VMVX.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#5549]
There's a few approaches we can take and we should experiment to see what we can get the IR to do.
The goal here is to end up with two types of work: big vectors and small vectors. I'm not sure how the current tiling infra does this.

Today we can (roughly) go to scalar level:
```mlir
scf.for %arg14 = %arg12p12 to %arg12p10p12x4 step %c4 {
  %16 = vmvx.buffer.load<%0 : !vmvx.buffer>[%arg14] : i32
  %17 = vmvx.buffer.load<%1 : !vmvx.buffer>[%arg14] : i32
  %18 = muli %16, %17 : i32
  vmvx.buffer.store<%2 : !vmvx.buffer>[%arg14], %18 : i32
}
```

Of course, that's a pretty bad way of doing this: we need 3 calls to one arithmetic op. One approach is to use smallish vectors here to amortize the call overhead:
```mlir
scf.for %arg14 = %arg12p12 to %arg12p10p12x4 step %c128 {
  %16 = vmvx.buffer.load<%0 : !vmvx.buffer>[%arg14] : vector<32xi32>
  %17 = vmvx.buffer.load<%1 : !vmvx.buffer>[%arg14] : vector<32xi32>
  %18 = muli %16, %17 : vector<32xi32>
  vmvx.buffer.store<%2 : !vmvx.buffer>[%arg14], %18 : vector<32xi32>
}
```
which we then can expand out to VM scalar registers:
```mlir
scf.for %arg14 = %arg12p12 to %arg12p10p12x4 step %c128 {
  %16#32 = vmvx.buffer.load.32<%0 : !vmvx.buffer>[%arg14] : i32
  %17#32 = vmvx.buffer.load.32<%1 : !vmvx.buffer>[%arg14] : i32
  %18 = muli %16#0, %17#0 : i32
  %19 = muli %16#1, %17#1 : i32
  %20 = muli %16#2, %17#2 : i32
  %21 = muli %16#3, %17#3 : i32
  %22 = muli %16#4, %17#4 : i32
  ...
  vmvx.buffer.store.32<%2 : !vmvx.buffer>[%arg14], %18, %19, .... : i32
}
```
We can vary the vector sizes here with tiling parameters to balance the ratio. The advantage of this approach is that it'll always work - there's no special vmvx ops required beyond the loads and we can add a strided variant if needed.

The other class of operations are ones we want to treat as external operations. These would operate directly on the `!vmvx.buffer`s without needing to load the values locally. Think of things like common elementwise ops and any of the larger vector/matrix operations modeled on the LLVM vector/matrix intrinsics. These are useful when we know that we'll have a high number of loads/stores relative to the work being performed and where we want to be able to have optimized implementations. These would look very similar to cooperative matrix in SPIR-V.

The above could be rewritten:
```mlir
scf.for %arg14 = %arg12p12 to %arg12p10p12x4 step %c4096 {
  vmvx.mul.si32 lhs(%0 : !vmvx.buffer>)[%arg14] rhs(%1 : !vmvx.buffer>)[%arg14] dst(%2: !vmvx.buffer>)[%arg14] length(%c1024)
}
```
This dramatically improves the code-size, runtime overhead, and lets us write a little SIMD implementation.

Since the tiling parameters differ between these two approaches while we need both we may have to perform the tiling multiple times - once to get to the coarse-level that we then match to the supported operations and then once again to get to the scalar-style small vectors and then once again to take care of anything remaining as simple scalar loops.

**Comment by benvanik** [comment]
April feels so far away now! Things changed with VMVX to simplify the approach and make it more reusable (it's possible to lower VMVX to non-IREE-VM backends like webassembly, etc). With respect to vectors this changed the problem from "how do we support `vector` in the IREE VM" (really involved) to "how do we turn `vector` into a 1D `memref` (or maybe some other `!vmvx.vector` type)" (something we may be able to lean on upstream bufferization support for, or at least write code that is nice and self-contained in a single pass vs touching a whole slice of the system) - or something like that.

The anchor requirement for the approach we choose is that we want to pass buffers and offsets to the library calls we have. For example:
```
vmvx.some_library_call_op %lhs_buffer, %lhs_offset, %rhs_buffer, %rhs_offset, %out_buffer, %out_offset, %length) :
    (!vm.buffer, index, !vm.buffer, index, !vm.buffer, index, index)
```
It could be in-place/etc too, whatever works for the op. The important thing is that we are passing in buffer references and offsets into them. This is in contrast to something like memref that would take a subview and such, as here we don't want to be creating additional buffer references or do any reference counting work in our inner loops.

So working backwards from there: if values are already in memrefs then this is relatively easy as we support converting `memref` -> `!vm.buffer`. For a lot of things that just do a `memref.subview` + scalar load/store this path is what's used today. The magic that enables this is [FlattenMemRefSubspanPass](https://github.com/google/iree/blob/a7986e1b6e0a50fad73dc5481faf8867d223f5f5/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp) which makes all memrefs 1D (so `memref<4x8xf32>` -> `memref<32xf32>`) giving us a foundation for memref+offset we need above.

When it comes to `vector`s we need to do something to get them into a form that we can lower to a `!vm.buffer` + offset. One approach would be to bufferize the vectors into memrefs and use the same `FlattenMemRefSubspanPass` to make them 1D and get the linear offsets. If the VMVX dialect ops took memrefs then this may slot in nicely - convert to vector ops, convert vector ops to VMVX ops on vectors, bufferize the vectors into memrefs, and then let the flattening happen for free with the existing tail of the pipeline. When lowering into the VM dialect then the 1D memref + linear offset become the `!vm.buffer` + offset we need.

This approach effectively treats vectors post-tiling (where they are all reasonably sized) as if they were machine registers in some register file, performs register allocation (similar to what the VM [RegisterAllocation](https://github.com/google/iree/blob/552d3f888e46f96c8227b1bd2e4600b85338237b/iree/compiler/Dialect/VM/Analysis/RegisterAllocation.h) does) to pack all the various vectors into the register file, and then allocas the register file. This would work well as each VMVX function already gets a [scratchpad/workgroup-local buffer](https://github.com/google/iree/blob/fcfa57bcf583cee1fbf520244a214db6cfbba5e0/iree/compiler/Dialect/HAL/Target/VMVX/test/smoketest.mlir#L51) passed in it can use as the register file. If whatever we did packed vectors into into a 1D memref that was alloca'd this would be really easy to wire up. Rough example:
```mlir
// load a 4x4 vector from %src_buffer at %linearized_offset (or whatever)
%13 = memref.subview %src_buffer[%linearized_offset] ... : memref<16xi8>
%16 = vector.transfer_read %13[%c0], %cst_0 : memref<16xi8, ...>, vector<4x4xi8>
// perform some vmvx op on the vector
vmvx.foo %16, ...

-> (bufferize vectors)

// allocate the virtual register file where all transient vectors are stored once (will be the local memory passed into the func)
%register_file = memref.alloca %total_size ... : memref<16384xi8>
...
// the vector became just a subview of the source of the read, with the read being turned into a copy from the source
%13 = memref.subview %src_buffer[%linearized_offset] ... : memref<16xi8>
%16 = memref.subview %register_file[%register_offset], ... : memref<4x4xi8, ...>
memref.copy %13, %16 : memref<4x4xi8>
vmvx.foo %16, ...

-> (flattening)

%register_file = memref.alloca %total_size ... : memref<16384xi8>
...
%13 = memref.subview %src_buffer[%linearized_offset] ... : memref<16xi8>
// flattening again to get 1D memrefs
%16 = memref.subview %register_file[%register_offset], ... : memref<16xi8, ...>
memref.copy %13, %16 : memref<16xi8>
vmvx.foo %16, ...

-> (memref optimizations)

// really hoping that memref optimizations could elide that unneeded copy :)
%13 = memref.subview %src_buffer[%linearized_offset] ... : memref<16xi8>
vmvx.foo %13, ...

-> (vm conversion)

// lowering to VM already handles taking the memref into a reference to the buffer + offset
%13 = %linearized_offset : index
vm.call @vmvx.foo(%src_buffer, %13, ...)

```

There are other approaches that may work too. For example, we could convert `vector` into a `!vmvx.vector` and a suite of load/store ops from memrefs (ala `vector.transfer_read`). The VMVX ops would then be specified to work on `!vmvx.vector` only and we can bufferize those. That's more boilerplate and more likely to drift as upstream changes to the vector dialect happen which is why I've shied away from it so far and tried to stick to 1D memrefs.

I'm sure there are more ideas too! I think the next step is probably taking the IR you have in #5819 and running the `FlattenMemRefSubspanPass` on it to see what that looks like as that would at allow focus on just the vectors and how they are represented. From that we could sketch up some example lowerings from 1D memref + vector operations to pure 1D memrefs or 1D memrefs + some custom type etc.

My instinct is that this will end up with not too much code and most of the time spent on fun IR design iteration to find something that is easy to work with and relatively stable in the face of codegen/linalg/vector/tiling/etc changes.

--

This was just a brain dump because what was in the issue was out of date - would love to chat more about approaches or experiment on discord :)

**Comment by anthonycanino1** [comment]
This is great information, and definitely helps me wrap my head around what we need to do a bit more. Let me dump what I currently have, then I can come back to your points above. I think I accidentally followed the memref + offset that takes advantage of the current pipline, where VMVX IR operates on memref directly :). 

--
Here is a rough sketch of a lowering that I have now (constants elided):

```mlir
// Starting
func @elem_add(%arg0 : tensor<8192xi32>, %arg1 : tensor<8192xi32>) -> tensor<8192xi32> attributes { iree.module.export } {               
  %0 = "mhlo.add"(%arg0, %arg1) : (tensor<8192xi32>, tensor<8192xi32>) -> tensor<8192xi32>                                               
  return %0 : tensor<8192xi32>                                                                                                         
}

// After tiling for vmvx (which does almost nothing at the moment) and a FlattenMemRefSubspan
func @elem_add_dispatch_0() {
  %0 = hal.interface.binding.subspan @io::@s0b0_ro_external[%c0] : memref<8192xi32>
  %1 = hal.interface.binding.subspan @io::@s0b1_ro_external[%c0] : memref<8192xi32>
  %2 = hal.interface.binding.subspan @io::@s0b2_xw_external[%c0] : memref<8192xi32>
  %workgroup_id_x = hal.interface.workgroup.id[0] : index
  %workgroup_count_x = hal.interface.workgroup.count[0] : index
  %3 = affine.apply affine_map<()[s0] -> (s0 * 128)>()[%workgroup_id_x]
  %4 = affine.apply affine_map<()[s0] -> (s0 * 128)>()[%workgroup_count_x]
  scf.for %arg0 = %3 to %c8192 step %4 {
    %5 = vector.transfer_read %0[%arg0], %c0_i32 {in_bounds = [true]} : memref<8192xi32>, vector<128xi32>
    %6 = vector.transfer_read %1[%arg0], %c0_i32 {in_bounds = [true]} : memref<8192xi32>, vector<128xi32>
    %7 = addi %5, %6 : vector<128xi32>
    vector.transfer_write %7, %2[%arg0] {in_bounds = [true]} : vector<128xi32>, memref<8192xi32>
  }
  return
}

// After VectorToVMVX 
func @elem_add_dispatch_0(%arg0: memref<?xi8>, %arg1: memref<?xi32>, %arg2: !iree.list<memref<?xi8>>, %arg3: index, %arg4: index, %arg5: index, %arg6: index, %arg7: index, %arg8: index, %arg9: index, %arg10: index, %arg11: index) {
  %0 = iree.list.get %arg2[%c0_0] : !iree.list<memref<?xi8>>
  %1 = unrealized_conversion_cast %0 : memref<?xi8> to memref<8192xi32>
  %2 = iree.list.get %arg2[%c1] : !iree.list<memref<?xi8>>
  %3 = unrealized_conversion_cast %2 : memref<?xi8> to memref<8192xi32>
  %4 = iree.list.get %arg2[%c2] : !iree.list<memref<?xi8>>
  %5 = unrealized_conversion_cast %4 : memref<?xi8> to memref<8192xi32>
  %6 = affine.apply affine_map<()[s0] -> (s0 * 128)>()[%arg3]
  %7 = affine.apply affine_map<()[s0] -> (s0 * 128)>()[%arg9]
  scf.for %arg12 = %6 to %c8192 step %7 {
    %c128 = constant 128 : index
    vmvx.add.si32 lhs(%1 : memref<8192xi32>) [%arg12] rhs(%3 : memref<8192xi32>) [%arg12] dst(%5 : memref<8192xi32>) [%arg12] length(%c128)
  }
  return
}

// After VMVX to VM
vm.import @vmvx.addsi32(%lhs_buffer : !vm.buffer, %lhs_offset : i32, %rhs_buffer : !vm.buffer, %rhs_offset : i32, %dst_buffer : !vm.buffer, %dst_offset : i32, %length : i32) attributes {sym_visibility = "private"}
vm.func @elem_add_dispatch_0(%arg0: !vm.buffer, %arg1: !vm.buffer, %arg2: !vm.list<!vm.buffer>, %arg3: i32, %arg4: i32, %arg5: i32, %arg6: i32, %arg7: i32, %arg8: i32, %arg9: i32, %arg10: i32, %arg11: i32) {
  %buffer = vm.list.get.ref %arg2, %zero : (!vm.list<!vm.buffer>, i32) -> !vm.buffer
  %buffer_0 = vm.list.get.ref %arg2, %c1 : (!vm.list<!vm.buffer>, i32) -> !vm.buffer
  %buffer_1 = vm.list.get.ref %arg2, %c2 : (!vm.list<!vm.buffer>, i32) -> !vm.buffer
  %0 = vm.mul.i32 %arg3, %c128 : i32
  %1 = vm.mul.i32 %arg9, %c128 : i32
  vm.br ^bb1(%0 : i32)
^bb1(%2: i32):  // 2 preds: ^bb0, ^bb2
  %slt = vm.cmp.lt.i32.s %2, %c8192 : i32
  vm.cond_br %slt, ^bb2, ^bb3
^bb2:  // pred: ^bb1
  vm.call @vmvx.addsi32(%buffer, %2, %buffer_0, %2, %buffer_1, %2, %c128) : (!vm.buffer, i32, !vm.buffer, i32, !vm.buffer, i32, i32) -> ()
  %3 = vm.add.i32 %2, %1 : i32
  vm.br ^bb1(%3 : i32)
^bb3:  // pred: ^bb1
  vm.return
}
```

So for the easy 1-d case above, FlattenMemRefSubspan gets the vector.transfer_read/write ops to an easy enough shape at which point I really just inline the memref and offset into `vmvx.addsi32`. After that, the rest of the pipeline seems to lower it to some usable `!vm.buffers` and offset. As it currently stands, I have a `vmvx.addsi32` intrinsic that grabs the `vm.buffer` and uses AVX2 to do some vectorized adds (tiny experiments showing about a 10x speedup).

After reading your writeup, I can see the step that I am skipping here is the bufferization of the vectors. Sure, I can inline the transfer read/write above, but I see that it will break very quickly (two addi ops in a row wont work etc). I'd say based on what I have now, taking the "vmvx on memref" approach looks like the way to go, with obvious work to be done on the bufferization part of it. 

--

I experimented with a slightly more complex mhlo add (`tensor<128x128xi32>`) that I knew would vectorize in the above pipeline:

```mlir
%7 = memref.subview %0[%arg0, %arg1] [128, 128] [1, 1] : memref<128x128xi32> to memref<128x128xi32, affine_map<(d0, d1)[s0] -> (d0 * 128 + s0 + d1)>>
%8 = memref.subview %1[%arg0, %arg1] [128, 128] [1, 1] : memref<128x128xi32> to memref<128x128xi32, affine_map<(d0, d1)[s0] -> (d0 * 128 + s0 + d1)>>
%9 = memref.subview %2[%arg0, %arg1] [128, 128] [1, 1] : memref<128x128xi32> to memref<128x128xi32, affine_map<(d0, d1)[s0] -> (d0 * 128 + s0 + d1)>>
%10 = vector.transfer_read %7[%c0, %c0], %c0_i32 {in_bounds = [true, true]} : memref<128x128xi32, affine_map<(d0, d1)[s0] -> (d0 * 128 + s0 + d1)>>, vector<128x128xi32>
%11 = vector.transfer_read %8[%c0, %c0], %c0_i32 {in_bounds = [true, true]} : memref<128x128xi32, affine_map<(d0, d1)[s0] -> (d0 * 128 + s0 + d1)>>, vector<128x128xi32>
%12 = addi %10, %11 : vector<128x128xi32>
vector.transfer_write %12, %9[%c0, %c0] {in_bounds = [true, true]} : vector<128x128xi32>, memref<128x128xi32, affine_map<(d0, d1)[s0] -> (d0 * 128 + s0 + d1)>>

// After FlattenMemRefSubspan with Error (interesting op)
// small_examples/elem_add2d.mlir:2:8: error: 'vector.transfer_read' op requires a permutation_map with result dims of the same rank as the vector type
%15 = "affine.apply"(%arg0, %2, %1) {map = affine_map<()[s0, s1, s2] -> (s0 * s1 + s2)>} : (index, index, index) -> index
%16 = "affine.apply"(%arg1, %3, %15) {map = affine_map<()[s0, s1, s2] -> (s0 * s1 + s2)>} : (index, index, index) -> index
%17 = "vector.transfer_read"(%4, %16, %0) {in_bounds = [true, true], operand_segment_sizes = dense<[1, 1, 1, 0]> : vector<4xi32>, permutation_map = affine_map<(d0) -> (d0)>} : (memref<?xi32>, index, i32) -> vector<128x128xi32>
```

So looks like FlattenMemRefSubspan has to be extended to also flatten out the vector (or maybe it's as simple as converting the vector type in this case).

Will try to catch you on discord today.

**Comment by benvanik** [comment]
Awesome - it's great that the inlining of the reads works well enough to prototype and it's a really good starting point for experimenting with what kind of ops/library calls would be useful while in parallel working toward the more interesting cases with multiple operations!

**Comment by MaheshRavishankar** [comment]
```// After tiling for vmvx (which does almost nothing at the moment) and a FlattenMemRefSubspan```
Can you expand a bit more on this. Most of the pipeline that is used for the VMVX lowering is same as what is used for CPU lowering. On CPU lowering you will get vectorization (at least for this case). It is explicitly disabled for VMVX because the VMVX backend cannot handle vectors.

```So looks like FlattenMemRefSubspan has to be extended to also flatten out the vector (or maybe it's as simple as converting the vector type in this case).
```

This would be great!

**Comment by anthonycanino1** [comment]
Thanks @MaheshRavishankar for pointing that out. I assume you are referring to the `LLVMCPUVectorization` pass? I completely missed that first time around, and instead grabbed a little code from the SPIRVTileAndVectorizeOneWorkgroup pass to get some tiling to happen. If so, I'm excited to plug into that instead.

**Comment by MaheshRavishankar** [comment]
This (https://github.com/google/iree/blob/10460ea350a0677820e0c15a51092b31192af0c8/iree/compiler/Dialect/Modules/VMVX/Transforms/Passes.cpp#L32) is the current VMVX lowering pipeline. It is already calling the same pipeline as the CPU to vectorize. You see there that it is explicitly setting `lowerToVectors` to `false`.  You should be able to get the vector code if you set it to `true` (which is the default value of that argument anyway).

**Comment by anthonycanino1** [comment]
So I tried that previously, (set lowerToVectors to true), and didn't see any vectorization on my machine. Tried again just now, and still nothing. Still have the `linalg.generic` op that performs the add. Perhaps I am missing something?

**Comment by MaheshRavishankar** [comment]
interesting. Ok, I'll take a look early next week.

**Comment by asaadaldien** [comment]
> So I tried that previously, (set lowerToVectors to true), and didn't see any vectorization on my machine. Tried again just now, and still nothing. Still have the `linalg.generic` op that performs the add. Perhaps I am missing something?

The current CPU lowering only vectorizes matmul and with a little modification to `LLVMCPUVectorization` pass we can enable vectorization for `linalg.generic`, but that will only work for cases where tile sizes are multiple of vector sizes.

However we are planning to deprecate this sometime in Q3 and enable the vector -> tensor `LLVMCPUVectorization` pass which will be the natural place to enable this.

**Comment by MaheshRavishankar** [comment]
Thanks Ahmed, had forgotten about the fact that for generic we still rely on LLVM vectorization. (didt actually get a chance to look at this on Friday)

**Comment by anthonycanino1** [comment]
I've been trying to pick that back up and have a little bit in place to experiment with the lowering discussed above and some ops. (Pretty sure the placeholder VMVX ops do not have enough information to do anything useful, but sketching it out for now) 

```mlir
func @elem_mul(%arg0 : tensor<512x512xi32>, %arg1 : tensor<512x512xi32>) -> tensor<512x512xi32> attributes { iree.module.export } {                                                                                                                                               
  %0 = "mhlo.dot"(%arg0, %arg1) : (tensor<512x512xi32>, tensor<512x512xi32>) -> tensor<512x512xi32>                                                                                                                                                                             
  return %0 : tensor<512x512xi32>                                                                                                                                                                                                                                               
}

// --> After LLVMCPUTileAndVectorizePass and FoldSubviewOps

scf.for %arg4 = %c0 to %c512 step %c64 {                                                                                                                                                                                                                                        
  scf.for %arg5 = %c0 to %c64 step %c16 {                                                                                                                                                                                                                                        
    %7 = affine.apply affine_map<(d0, d1) -> (d0 + d1)>(%arg5, %arg4)                                                                                                                                                                                                           
    %8 = affine.apply affine_map<(d0)[s0] -> (d0 + s0)>(%arg2)[%arg0]                                                                                                                                                                                                               
    %9 = vector.transfer_read %0[%8, %7], %c0_i32 {in_bounds = [true, true]} : memref<512x512xi32>, vector<16x16xi32>                                                                                                                                                           
    %10 = affine.apply affine_map<(d0)[s0] -> (d0 + s0)>(%arg3)[%arg1]                                                                                                                                                                                                          
    %11 = vector.transfer_read %1[%7, %10], %c0_i32 {in_bounds = [true, true]} : memref<512x512xi32>, vector<16x4xi32>                                                                                                                                                              
    %12 = vector.transfer_read %2[%8, %10], %c0_i32 {in_bounds = [true, true]} : memref<512x512xi32>, vector<16x4xi32>                                                                                                                                                          
    %13 = vector.contract {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d2, d1)>, affine_map<(d0, d1, d2) -> (d0, d1)>], iterator_types = ["parallel", "parallel", "reduction"], kind = #vector.kind<add>} %9, %11, %12 : vector<16x16xi32>, vector<16x4xi32> into vector<16x4xi32>                                                                                                                                                                                                                                           vector.transfer_write %13, %2[%8, %10] {in_bounds = [true, true]} : vector<16x4xi32>, memref<512x512xi32>                                                                                                                                                                   
  }                                                                                                                                                                                                                                                                             
} 

// --> After conversion to some VMVX ops

scf.for %arg4 = %c0 to %c512 step %c64 {                                                                                                                                                                                                                                        
  scf.for %arg5 = %c0 to %c64 step %c16 {                                                                                                                                                                                                                                           
    %7 = affine.apply affine_map<(d0, d1) -> (d0 + d1)>(%arg5, %arg4)                                                                                                                                                                                                               
    %8 = affine.apply affine_map<(d0)[s0] -> (d0 + s0)>(%arg2)[%arg0]                                                                                                                                                                                                               
    %9 = memref.alloca() : memref<256xi32>                                                                                                                                                                                                                                      
    vmvx.load_reg %0[%8, %7] %9 : memref<512x512xi32>, memref<256xi32>                                                                                                                                                                                                          
    %10 = affine.apply affine_map<(d0)[s0] -> (d0 + s0)>(%arg3)[%arg1]                                                                                                                                                                                                              
    %11 = memref.alloca() : memref<64xi32>                                                                                                                                                                                                                                      
    vmvx.load_reg %1[%7, %10] %11 : memref<512x512xi32>, memref<64xi32>                                                                                                                                                                                                             
    %12 = memref.alloca() : memref<64xi32>                                                                                                                                                                                                                                          
    vmvx.load_reg %2[%8, %10] %12 : memref<512x512xi32>, memref<64xi32>                                                                                                                                                                                                         
    %13 = vmvx.matmul lhs(%9 : memref<256xi32>) rhs(%11 : memref<64xi32>) fadd(%12 : memref<64xi32>) : memref<64xi32>                                                                                                                                                               
     vmvx.store %13, %2[%8, %10] : memref<512x512xi32>, memref<64xi32>                                                                                                                                                                                                             
  }                                                                                                                                                                                                                                                                             
}   

// --> After FlatenMemrefSubspan

scf.for %arg4 = %c0 to %c512 step %c64 {                                                                                                                                                                                                                                        
  scf.for %arg5 = %c0 to %c64 step %c16 {                                                                                                                                                                                                                                       
    %7 = memref.alloca() : memref<256xi32>                                                                                                                                                                                                                                      
    %8 = affine.apply affine_map<(d0, d1, d2)[s0] -> (d0 * 512 + d1 + d2 + s0 * 512)>(%arg2, %arg5, %arg4)[%arg0]                                                                                                                                                               
    vmvx.load_reg %0[%8] %7 : memref<?xi32>, memref<256xi32>                                                                                                                                                                                                                    
    %9 = memref.alloca() : memref<64xi32>                                                                                                                                                                                                                                       
    %10 = affine.apply affine_map<(d0, d1, d2)[s0] -> (d0 * 512 + d1 * 512 + d2 + s0)>(%arg5, %arg4, %arg3)[%arg1]                                                                                                                                                              
    vmvx.load_reg %1[%10] %9 : memref<?xi32>, memref<64xi32>                                                                                                                                                                                                                    
    %11 = memref.alloca() : memref<64xi32>                                                                                                                                                                                                                                      
    %12 = affine.apply affine_map<(d0, d1)[s0, s1] -> (d0 * 512 + d1 + s0 * 512 + s1)>(%arg2, %arg3)[%arg0, %arg1]                                                                                                                                                              
    vmvx.load_reg %2[%12] %11 : memref<?xi32>, memref<64xi32>                                                                                                                                                                                                                   
    %13 = vmvx.matmul lhs(%7 : memref<256xi32>) rhs(%9 : memref<64xi32>) fadd(%11 : memref<64xi32>) : memref<64xi32>                                                                                                                                                            
    %14 = affine.apply affine_map<(d0, d1)[s0, s1] -> (d0 * 512 + d1 + s0 * 512 + s1)>(%arg2, %arg3)[%arg0, %arg1]                                                                                                                                                              
    vmvx.store %13, %2[%14] : memref<?xi32>, memref<64xi32>                                                                                                                                                                                                                     
  }                                                                                                                                                                                                                                                                             
}
```

Here is what I ran into so far and will need some help with / discuss:

1. I am using `vmvx.load_reg` as a kind of temporary op to let me play around with memref flattening and replace a transfer_read which produces a vector with a load to a temporary membuf instead. From what I understand, `FlattenMemrefSubspan` cannot flatten a transfer_read/transfer_write if the result vector is a N-d vector.

3. From the previous point, the vector contraction would also need to be transformed because of the flattening. Perhaps this is where a temporary vmvx mapping op that acts as a place holder from the N-d vector ops to 1-d vmvx ops can get inserted.

3. I have to these vector -> vmvx conversions in the middle of the `buildVectorVMVXTransformPassPipeline` as opposed to the VMVX `ConversionPass` because of `FlattenMemrefSubspan` point above. 

4. I believe just allocating the memrefs like I am doing here won't lift them up into scratch space. That would have to happen as part of a bufferization that creates hal interface subspan buffers?

So, to continue on with the lowering above, which tries to go from N-d memref/vector, to VMVX ops that operate on 1-d memref, I think will have to more clearly flesh out how a bufferization / flattening would work here. Will try and chat on discord about it.

**Comment by benvanik** [comment]
VMVX has gone the microkernel route instead so this is no longer required.
