### ISSUE TITLE
Linux portability: Missing deps on `dl` for `threading` and `dynamic_library`

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#5702]
Some Linux systems need to link against `-ldl` explicitly for these two libraries in `iree/base/internal` (I've encountered this sporadically on weird systems but most recently on NVidia Jetson).

Just adding `-ldl` to the DEPS of both makes it work. The right answer is to wrap the in a generator expression which activates only on Linux. However, these files are bazel_to_cmake controlled. Should I just add this in the CMake specific section as a `target_link_libraries`? Bazel really lacks configurability and I don't care about making it work on the non mainline systems.

**Comment by GMNGeoffrey** [comment]
Ok this one I think this one is correctly assigned to me 😁

I recently ran into the same issue with a user report in httpss://github.com/google/llvm-bazel/issues/188. I never hit this because my system is one of the ones that automagically adds some of these linkopts for reasons that aren't really clear to me (if you happen to know more about why and what systems add linking to some libraries by default, a pointer would be appreciated 🙂)

So in that case we moved the linkopts to the library that's actually using those things. I *think* that's the right approach. I don't really see the benefit of only adding it to leaf binaries.

To finally actually answer your question, my assumptions stated, we should add it to linkopts on the cc_library in Bazel. I agree we care less about system coverage there, but that's not hard. But apparently we don't handle linkopts in bazel_to_cmake (https://github.com/google/iree/blob/9a7ff5eef7e66fd2d8f6409f4a713548c7297ef1/build_tools/bazel_to_cmake/bazel_to_cmake_converter.py#L340). That's silly because we have a linkopts argument to our cmake iree_cc_library (https://github.com/google/iree/blob/e56b4f7a2cd2eb12fa139026e26c0ea7feb0947f/build_tools/cmake/iree_cc_library.cmake#L31) and it's trivial to translate.

I can fix that (on Monday). Hopefully the bazel_to_cmake script is straightforward enough that you could do it before then if you want 😁

**Comment by stellaraccident** [comment]
I'm pretty sure we want it as a dep of those two libraries specifically: they are the ones actually using the symbols.

> I recently ran into the same issue with a user report in httpss://github.com/google/llvm-bazel/issues/188. I never hit this because my system is one of the ones that automagically adds some of these linkopts for reasons that aren't really clear to me (if you happen to know more about why and what systems add linking to some libraries by default, a pointer would be appreciated 🙂)

Happenstance would be my guess: as long as an `-ldl` shows up somewhere on the final link command line after the library that uses the symbol, it will be happy. This can be because some other system library or something is... something. So I don't actually know, but as with these things the answer is to do the right thing -- which is to add dependencies from libraries that use things.

> To finally actually answer your question, my assumptions stated, we should add it to linkopts on the cc_library in Bazel. I agree we care less about system coverage there, but that's not hard. But apparently we don't handle linkopts in bazel_to_cmake (

But `-ldl` should only be applied for Linux specifically. In CMake, this is a trivial generator expression.

**Comment by benvanik** [comment]
unconditionally putting `-ldl` in linkopts will break windows and bare metal
`IREE_DEFAULT_LINKOPTS` already exists and adds -ldl to all iree_cc_binary and iree_cc_library targets

are you building these individual libraries as shared objects or something weird and bazel-y? -ldl should only be required during linking, not when generating static libraries

**Comment by benvanik** [comment]
(that is to say, if you are seeing errors in linking iree_cc_binary/iree_cc_test targets then something deeper is broken, and if you are seeing errors linking your own binaries not using those macros then adding -ldl to any of our internal libraries won't help you)

**Comment by stellaraccident** [comment]
I am running `ninja` with no cmake options set except release mode.

**Comment by stellaraccident** [comment]
An example:

```
: && /usr/bin/c++ -O3 -DNDEBUG -ldl -lpthread iree/base/testing/CMakeFiles/iree_base_testing_dynamic_library_test.dir/dynamic_library_test.cc.o -o iree/base/testing/dynamic_library_test  iree/base/testing/libiree_base_testing_dynamic_library_test_library.a  iree/base/internal/libiree_base_internal_dynamic_library.a  iree/base/internal/libiree_base_internal_file_io.a  iree/testing/libiree_testing_gtest_main.a  iree/base/internal/libiree_base_internal_file_path.a  iree/base/internal/libiree_base_internal_threading.a  iree/base/internal/libiree_base_internal_synchronization.a  third_party/abseil-cpp/absl/types/libabsl_bad_optional_access.a  iree/base/internal/libiree_base_internal_status_internal.a  third_party/abseil-cpp/absl/strings/libabsl_strings.a  third_party/abseil-cpp/absl/strings/libabsl_strings_internal.a  third_party/abseil-cpp/absl/base/libabsl_base.a  third_party/abseil-cpp/absl/base/libabsl_spinlock_wait.a  -lrt  third_party/abseil-cpp/absl/numeric/libabsl_int128.a  third_party/abseil-cpp/absl/base/libabsl_throw_delegate.a  third_party/abseil-cpp/absl/base/libabsl_raw_logging_internal.a  third_party/abseil-cpp/absl/base/libabsl_log_severity.a  iree/base/libiree_base_logging.a  lib/libgmock.a  lib/libgtest.a  -pthread  iree/base/internal/libiree_base_internal_flags.a  iree/base/libiree_base_base.a && :
iree/base/internal/libiree_base_internal_dynamic_library.a(dynamic_library_posix.c.o): In function `iree_dynamic_library_load_from_file':
dynamic_library_posix.c:(.text+0x258): undefined reference to `dlopen'
dynamic_library_posix.c:(.text+0x328): undefined reference to `dlclose'
iree/base/internal/libiree_base_internal_dynamic_library.a(dynamic_library_posix.c.o): In function `iree_dynamic_library_load_from_files':
dynamic_library_posix.c:(.text+0x3a4): undefined reference to `dlopen'
dynamic_library_posix.c:(.text+0x480): undefined reference to `dlclose'
iree/base/internal/libiree_base_internal_dynamic_library.a(dynamic_library_posix.c.o): In function `iree_dynamic_library_load_from_memory':
dynamic_library_posix.c:(.text+0x578): undefined reference to `dlopen'
dynamic_library_posix.c:(.text+0x6f0): undefined reference to `dlclose'
iree/base/internal/libiree_base_internal_dynamic_library.a(dynamic_library_posix.c.o): In function `iree_dynamic_library_release':
dynamic_library_posix.c:(.text+0x75c): undefined reference to `dlclose'
iree/base/internal/libiree_base_internal_dynamic_library.a(dynamic_library_posix.c.o): In function `iree_dynamic_library_lookup_symbol':
dynamic_library_posix.c:(.text+0x7a4): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
```

**Comment by benvanik** [comment]
I see `-ldl` in that list. I'm not sure what to tell you :)

**Comment by stellaraccident** [comment]
I believe the issue is that the linkopts are the wrong place for this: they get added to the link command line first, which is not sufficient (should be after the library that introduces the symbol).

**Comment by benvanik** [comment]
Ah so this is a GCC thing. We need a bot building gcc stuff (same with #5703) - not great playing whackamole :(

**Comment by GMNGeoffrey** [comment]
(I'm on my phone drinking a beer in the sun, so all my responses should be suitably under weighted)

> I'm pretty sure we want it as a dep of those two libraries specifically: they are the ones actually using the symbols.

Agreed. That's what I was (trying to) say.

> But `-ldl` should only be applied for Linux specifically. In CMake, this is a trivial generator expression.

Yeah, sorry I should've said with a select against windows. Linux is default, which is what bazel_to_cmake uses.

Seems like Ben is on this. I forgot about default linkopts. But gcc sad ☹️

**Comment by stellaraccident** [comment]
I think the issue is actually the BFD linker, which on some platforms is configured to be more strict/less "latchy" on dynamic library depends (like `dl`). What I'm saying is the correct thing, but the other way happens to work some times (a lot of the time). I am pretty sure I can make this happen on LLVM on such systems as well... I've also seen it come and go when done wrong. We can label it GCC, but it is actually a Posix thing :)

Here is an example of what gets the link order right:

```
iree_cc_library(
  NAME
    threading
  HDRS
    "threading.h"
  SRCS
    "threading.c"
    "threading_darwin.c"
    "threading_impl.h"
    "threading_pthreads.c"
    "threading_win32.c"
  DEPS
    ::internal
    ::synchronization
    iree::base
    iree::base::core_headers
    iree::base::tracing
    $<$<PLATFORM_ID:Linux>:-ldl>
  PUBLIC
)
```

Alternatively, the following added at the end of the file has the same effect.

```
target_link_libraries(iree_base_internal_threading PUBLIC $<$<PLATFORM_ID:Linux>:-ldl>)
target_link_libraries(iree_base_internal_dynamic_library PUBLIC $<$<PLATFORM_ID:Linux>:-ldl>)
```

**Comment by stellaraccident** [comment]
Also +1 on build bot, and I think this one would be a good one to add: aarch64, pegged to old LTS release that we don't want to regress on, important embedded platform -- hits all of the weird (for Linux). I think I know how to dockerize it so that we can build/test it on regular build systems.

**Comment by benvanik** [comment]
What about moving the target_link_options below the target_link_libraries in iree_cc_binary.cmake? If it's just that we are putting them at the front then we can also put them at the back.

**Comment by stellaraccident** [comment]
It's not just the order of declaration in cmake. When the command line is computed, libraries are treated separately and a correct ordering is applied. Generally, the system is free to put all options at the beginning of the command line, regardless of how they are declared. 

So if wanting to handle this globally, `-ldl` needs to be a library that is added, not an option. This distinction is made in all systems I know of but they spell it differently and it causes a lot of confusion and head scratching because it can sometimes work the wrong way (ie. Autoconf, bazel and cmake all distinguish in this way).

**Comment by stellaraccident** [comment]
So really, this fragment of iree_copts.cmake isn't right:

```
iree_select_compiler_opts(IREE_DEFAULT_LINKOPTS
  ALL
    # TODO(benvanik): remove the ABSL usage here; we aren't abseil.
    "${ABSL_DEFAULT_LINKOPTS}"
  CLANG_OR_GCC
    # Required by all modern software, effectively:
    "-ldl"
    ${_IREE_PTHREADS_LINKOPTS}
    ${_IREE_LOGGING_LINKOPTS}
)
```

If wanting to do this globally, `-lpthread` and `-ldl` should be added to all binaries and tests via `target_links_libraries`, not `target_link_opts`.

Also, that "-ldl" should really be dependent on whether building for Linux, not whether compiling with GCC/Clang.

Geoffrey, it'd be great if you want to fix it, but I can work on this if needed since I'm pretty sure I know what is going on here. Would like to see it fixed properly.

**Comment by GMNGeoffrey** [comment]
Reading the documentation for `target_link_libraries` and `target_link_options`, I think Stella's right that we should be using the former for these. I think we should be specifying them as [plain library names](https://cmake.org/cmake/help/v3.13/command/target_link_libraries.html#:~:text=a%20plain%20library%20name%3A%20the%20generated%20link%20line%20will%20ask%20the%20linker%20to%20search%20for%20the%20library%20(e.g.%20foo%20becomes%20-lfoo%20or%20foo.lib)) though, no need to try to format it as a flag. Also agreed, that we're conditioning on the wrong thing there.

It's not clear to me whether the better thing to do is declare these on the libraries that use them or, as we're doing now, proclaim that it's 2021 and just please always add pthread. The former is a bit annoying to do, since they're link-time-only dependencies, so it's a bit hard to ensure they're declared on the correct libraries. If we care about each of our libraries properly declaring all their linktime dependencies, we could actually pretty easily add rules that link them into dummy binaries. I've in fact already done that internally with `iree_build_test` (which ensures that libraries get built by CI infra), which we could easily also bring to OSS. Not sure if that's useful. I suspect there will be some edge case where we deliberately have a library that doesn't have all its deps, but we could make it optional.

I'm happy to take a look at this on Monday, though I don't have a system to really test this on (unless you know of some docker container that makes this easy?)

**Comment by stellaraccident** [comment]
Sounds right generally.

In my mind, there are two classes of things here:

* `pthread` : Is part of the standard library, and if making the "it's 2021" debate, I can buy that. There are three options here:
  * Add a global *link opt* (only on Linux, non Android): `-pthread` and let the compiler frontend figure out out (the compiler has a special flag for this case)
  * Add a global *link library* (only on Linux, non Android): `pthread` (i.e. ensure that a `-lpthread` gets put on the compiler command line in the right place)
  * Add `$<$<PLATFORM_ID:Linux>:pthread>` to libraries that need it (if not ascribing to the "it's 2021" point.

* `dl` : This is just a library on the system and, ideally, should be added to `target_link_libraries` for things that actually use any of the `dl*` functions. In this way, it is the same as if you are using zlib stuff, you notate a dep on `z`. To keep things tidy, I generally prefer that this gets done on the library that is introducing the use vs globally. There will then be less surprises when depending on it from other projects.
  * Carve-outs in the CMake files to notate this seems fine:
    * `target_link_libraries(iree_base_internal_threading PUBLIC $<$<PLATFORM_ID:Linux>:dl>)`
    * `target_link_libraries(iree_base_internal_dynamic_library PUBLIC $<$<PLATFORM_ID:Linux>:dl>)`
  * Should be removed from `iree_copts.cmake`

As for testing, these things tend to be meta-stable even on systems that are more sensitive (I've carried this patch around for a while as the issue has come and gone on different linux systems). I usually prefer to look at actual command lines to verify:
  * Do a full build
  * Run `ninja iree_base_internal_dynamic_library_test -v`
  * Inspect the command line and make sure it is right

**Comment by stellaraccident** [comment]
I don't think this has been an issue for a long time (and I've seen the write deps for this).
