### ISSUE TITLE
Bert failing to compile with native ABI

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#5802]
Repro:

```
./iree/tools/iree-translate --iree-hal-target-backends=dylib-llvm-aot --mlir-elide-elementsattrs-if-larger=10 --iree-mlir-to-vm-bytecode-module --print-ir-after-all bertfloat.mlir.txt
```

[bertfloat.mlir.txt](https://github.com/google/iree/files/6444162/bertfloat.mlir.txt)

**Comment by stellaraccident** [comment]
Another simpler repro, possibly same root cause: 
[pytree_test.mlir.txt](https://github.com/google/iree/files/6444290/pytree_test.mlir.txt)

**Comment by stellaraccident** [comment]
With just the version that returns results of an arithmetic operation:

[reproducer__iree_vmla.mlir.txt](https://github.com/google/iree/files/6444400/reproducer__iree_vmla.mlir.txt)

**Comment by benvanik** [comment]
Likely fixed now (we have BERTs running).
