### ISSUE TITLE
Enable VMVX for tests previously covered by VMLA but not yet working with dynamic shapes.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#5897]
VMVX has the same limitations as Vulkan/SPIR-V codegen today (mostly due to #5822, but there may be some other hiding issues). This means that during replacement of VMLA->VMVX some tests had to be disabled. This issue is used to track them.

**Comment by alliemartens** [comment]
Hey @benvanik bumping this up again, still active?

**Comment by benvanik** [comment]
I think stella did this the other week as part of the VMVX work 🥳
