### ISSUE TITLE
Add a tool to enumerate vulkan devices and add test runner flags for selecting

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#61]
Right now the logic to select a Vulkan device for the test runners is too simplistic (it just takes the first). We should probably have two flags: a device name to match and an index. Also, it would be nice to have a tool to enumerate what the driver sees.

**Comment by benvanik** [comment]
#3937 allows us to expose multiple Vulkan drivers (swiftshader/nvidia native/etc), and then the existing driver device enumeration should allow for selecting specific devices within those. Just need some flags in the runners.

**Comment by benvanik** [comment]
This was added recently and `--list_devices`/`--dump_devices` (or the C APIs) can be used.
