### ISSUE TITLE
Forcing "opt+asserts" Bazel build makes configuring Bazel difficult

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#6140]
In our bazelrc, we set `-c opt` by default

https://github.com/google/iree/blob/02c7a8a8a7847fe20cd5b12fc4766e0ed03ac88d/build_tools/bazel/iree.bazelrc#L15

and then turn on asserts in a compiler specific fashion 

https://github.com/google/iree/blob/02c7a8a8a7847fe20cd5b12fc4766e0ed03ac88d/build_tools/bazel/iree.bazelrc#L64

These compiler-specific configs are added to configured.bazelrc so they are always used to select the compiler. This causes surprising behavior because now Bazel secretly doesn't do what you told it to do:

```shell
$ bazel build -c opt //foo
```

Still has asserts. To turn off asserts, you have to explicitly specify `--copt=-DNDEBUG`, as we do in our release configs:

https://github.com/google/iree/blob/02c7a8a8a7847fe20cd5b12fc4766e0ed03ac88d/build_tools/bazel/iree.bazelrc#L162

I think we should be far more conservative in what we set by default. This is similar to the discussion of default CMake build type. We can argue about what the default build type should have been for the tool, but having project specific configuration that doesn't compose nicely causes more harm than good IMO. Instead, I think we should provide configs that bundle sets of options we consider useful and then we can allow users to set those in their user.bazelrc depending on their preferences. People who want the current behavior can add `build --config=opt_asserts` to their user.bazelrc. I know, for instance, that Ben makes heavy use of a debugger and so prefers building in debug mode (though of course he's using CMake, so not directly applicable).

**Comment by stellaraccident** [comment]
I'm fine removing this carve out for the regular Iree tree, but I'll probably force it in the Tensorflow side. Ime, for that codebase, it is pure insanity and am untenable experience to build in anything but opt+asserts. But we don't need to refers everyone to that same mean.

**Comment by stellaraccident** [comment]
Feel free to back all of this out if it is hurting you (I don't use bazel except as a way to build Tensorflow). I may reciprocate with different defaults on the Tensorflow side if I find it to be a foot gun.

**Comment by ScottTodd** [comment]
Very old Bazel issue with some discussion about TensorFlow source builds. Closing as stale.
