### ISSUE TITLE
Set up a new sample repo for a TFLite demo app

### ISSUE THREAD

**Issue by not-jenni** [iree-org/iree#6148]
Following the conversation in https://github.com/google/iree/issues/3954, we should set up a separate repo for IREE samples.  At first, a TFLite demo app will probably live in not-jenni/iree-android-tflite-demo, but it in the long term should be moved to a formalized google/iree-samples repo that we can link to from the main repo

**Comment by not-jenni** [comment]
Repo available at https://github.com/not-jenni/iree-android-tflite-demo

**Comment by ScottTodd** [comment]
https://github.com/google/iree-samples now exists, we should move the TFLite demo app (and other similarly sized samples) there.

**Comment by jpienaar** [comment]
@not-jenni is the pending work here to move the example over? Is this demo app still working? (or should this be closed and new issue created once this is needed?)

**Comment by not-jenni** [comment]
I haven't tried running the app in in about a year, but I can make sure everything is still working and finish moving it to the iree-samples repo

**Comment by ScottTodd** [comment]
This issue is stale (no work has been done on TFLite demos or Android apps in a while), closing.
