### ISSUE TITLE
IREE TFLite Bindings AAR Generation and Distribution

### ISSUE THREAD

**Issue by KoolJBlack** [iree-org/iree#6198]
We need to bundle java and native tflite libraries into an AAR library and distribute for other apps/demos to reference. This is vital for building external demos with Gradle and (ideally) should not require most users to build all of IREE.

**Comment by alliemartens** [comment]
@KoolJBlack Old issue alert, is this still active? Can assign to someone and add a priority if so.

**Comment by KoolJBlack** [comment]
This is obsolete
