### ISSUE TITLE
Slim vision models should test with various dynamic shape variants

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#6356]
Ideally:
* dynamic batch size
* dynamic image size

This can be done in a patchy way by modifying `slim_vision_model_test.py` and none-ing out various shape dims:

```
    input_shape = list(get_input_shape())
    input_shape[0] = None
    self.m.build(input_shape)
```

**Comment by alliemartens** [comment]
@stellaraccident Old issue alert! Still active?

**Comment by alliemartens** [comment]
@stellaraccident Old issue alert! Still active?

**Comment by alliemartens** [comment]
@stellaraccident Old issue alert! Still active?

**Comment by jpienaar** [comment]
Closing as not current focus.
