### ISSUE TITLE
Introduce flow.tensor.cast for lowering `tensor.cast`

### ISSUE THREAD

**Issue by cathyzhyi** [iree-org/iree#6418]
Introduce a `flow.tensor.cast` that `tensor.cast` can be lowered to. Currently, `flow.tensor.reshape` is used in place of `flow.tensor.cast` to cast between different level of static type information. See `ConvertTensorCastPattern` in https://github.com/google/iree/pull/6407 as an example of such use.

**Comment by GMNGeoffrey** [comment]
Hey sorry I missed this. I'm the default assignee so that we can try not to miss issues from external folks (but obviously not perfect :grin:). I don't think I'm the best assignee for this one though. Can you talk to folks and get this prioritized appropriately?

**Comment by cathyzhyi** [comment]
@MaheshRavishankar Hey Mahesh, do you have any suggestions on who's the best assignee for this item?

**Comment by MaheshRavishankar** [comment]
Maybe Scott, Ben or me. How urgent is this?

**Comment by cathyzhyi** [comment]
I think it's not urgent as it's not blocking anything just to make things cleaner.
