### ISSUE TITLE
Skip building / testing / benchmarking commits that don't modify code

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#6587]
Discussed a bit on Discord [here](https://discord.com/channels/689900678990135345/689957613152239638/870024353721495672)

Start simple: add something like `change_requires_benchmarks.sh` that runs at the top of certain pipelines and exits if only markdown files, or files in `docs/` are changed.

**Comment by benvanik** [comment]
could have a `check_paths_changed.sh path0 path1` kind of script - that could then do the git diff/path checks, and each pipeline could just list what it cares about (`check_paths_changed.sh iree/ third_party/` or `check_paths_changed.sh docs/` or `check_paths_changed.sh bindings/tflite/` etc) - fewer scripts to manage, and things are easier to spot at a glance

(whenever we get around to moving the compiler from iree/compiler/ to compiler/ we'd be able to cleanly say "runtime code changes" vs "compiler code changes" too!)
