### ISSUE TITLE
Tracing builds on some linuxish systems sometimes broken?

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#6596]
Reported with clang 11 on linux with `-DIREE_ENABLE_RUNTIME_TRACING=ON`:
```
../iree/base/tracing.h:471:7: error: exception specification in declaration does not match previous declaration
void* operator new(size_t count) noexcept;
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/new:126:26: note: previous declaration is here
_GLIBCXX_NODISCARD void* operator new(std::size_t) _GLIBCXX_THROW (std::bad_alloc)
```

This looks like a legit error. Since different C++ libraries define new differently (sigh) we'll likely need multiple variants here:
https://github.com/google/iree/blob/552d3f888e46f96c8227b1bd2e4600b85338237b/iree/base/tracing.h#L471-L472

Can key these off of the library in use, and if unknown maybe just disable new/delete tracking.
I don't have an environment I can reproduce this in (or don't know how) - if anyone comes across this and knows how to make it happy everywhere that'd be great :)

**Comment by ScottTodd** [comment]
Is this still occurring? Has anyone else hit it? Maybe close as stale and re-open if needed?

**Comment by ScottTodd** [comment]
No updates since I asked if this was stale, closing.
