### ISSUE TITLE
Add linalg_ext ops lowering to VMVX pipeline

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#6601]
The lowering is missing in the pipeline. There was an error when adding ConvertLinalgExtToLoops pass to the pipeline. If we can add it to the pipeline, we will be able to run scatter/sort op on VMVX backend.

**Comment by alliemartens** [comment]
@hanhanW Please update this old issue and add priority if needed.

**Comment by hanhanW** [comment]
The tests have been enabled, closing the issue.
