### ISSUE TITLE
iree-translate : Few basic questions

### ISSUE THREAD

**Issue by uccoder-hk** [iree-org/iree#6705]
Hello,

I have few basic questions , requesting your help... 

1.  How to  decode the --entry_function name from .vmfb file which is required  for iree-run-module?
2. What is iree-translate command for converting .mlir to .vmfb for DyLib backend for android(Aarch64)?
 Any other change required while compiling iree-runtime for android to support DyLib other than mentioned in  https://google.github.io/iree/building-from-source/android (it has only vmvx backend example)?
 
 3. Similarly what needs to be done for Vulkan backend for android?

Thanks..

**Comment by ScottTodd** [comment]
1. Names come from frontends or your own specification. `serving_default` is a common one for TensorFlow models. You can run `iree-dump-module /path/to/file.vmfb` to get more information about a compiled module - look for something like this:
```json
  "exported_functions": [
    {
      "local_name": "serving_default",
      "signature": {
        "argument_types": [
          3,
          3,
          3
        ],
        "result_types": [
          3,
          3
        ],
        "calling_convention": "0rrr_rr"
      }
    },
    {
      "local_name": "__init",
      "signature": {
        "calling_convention": "0v_v"
      },
      "internal_ordinal": 1
    }
  ],
```

2-3. Check out https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_android_cmake.md#dylib-llvm-aot-backend and https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_android_cmake.md#vulkan-hal-backend. These specific configurations haven't been covered yet on our website.

**Comment by uccoder-hk** [comment]
> 1. Names come from frontends or your own specification. `serving_default` is a common one for TensorFlow models. You can run `iree-dump-module /path/to/file.vmfb` to get more information about a compiled module - look for something like this:
> 
> ```json
>   "exported_functions": [
>     {
>       "local_name": "serving_default",
>       "signature": {
>         "argument_types": [
>           3,
>           3,
>           3
>         ],
>         "result_types": [
>           3,
>           3
>         ],
>         "calling_convention": "0rrr_rr"
>       }
>     },
>     {
>       "local_name": "__init",
>       "signature": {
>         "calling_convention": "0v_v"
>       },
>       "internal_ordinal": 1
>     }
>   ],
> ```
> 
> 2-3. Check out https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_android_cmake.md#dylib-llvm-aot-backend and https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_android_cmake.md#vulkan-hal-backend. These specific configurations haven't been covered yet on our website.

Thanks..

2. I tried to experiment with the steps mentioned in this link ( -iree-hal-target-backends=dylib-llvm-aot 
  -iree-llvm-target-triple=aarch64-linux-android ). But Linking failed..
 Like mobilenet_v2_1.0_224.mlir:1:1: error:  failed to link executable and generate target dylib using linker toolchain /usr/bin/ld

**Comment by ScottTodd** [comment]
Do you have the `ANDROID_NDK` environment variable set?

**Comment by uccoder-hk** [comment]
> Do you have the `ANDROID_NDK` environment variable set?

yes..

**Comment by uccoder-hk** [comment]
From the same env, vmvx backend worked..

**Comment by benvanik** [comment]
vmvx will work because it doesn't require ld to link things. /usr/bin/ld should not be used for android and indicates you are going down a bad code path during linking. You'll need to paste the full logs as there may be more in there.

(for this kind of interactive debugging I recommend coming into the [discord](https://discord.gg/26P4xW4) - github issues aren't the best for realtime comms :)

**Comment by uccoder-hk** [comment]
> vmvx will work because it doesn't require ld to link things. /usr/bin/ld should not be used for android and indicates you are going down a bad code path during linking. You'll need to paste the full logs as there may be more in there.
> 
> (for this kind of interactive debugging I recommend coming into the [discord](https://discord.gg/26P4xW4) - github issues aren't the best for realtime comms :)

Sure I will try to post and connect on discord channel.. 
Meanwhile I will try share some logs & commands here.. It seems , it is not able to pick aarch64-linux-android toolchain though ANDROID_NDK is set.. 

Env,
export ANDROID_NDK=~/tools/android-ndk-r21e

IREE for both host & android is built by referring https://google.github.io/iree/building-from-source/android/

Command(Dylib) - FAILED:
iree/tools/iree-translate --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=dylib-llvm-aot --iree-input-type=tosa --iree-llvm-target-triple=aarch64-linux-android mobilenet_v2_1.0_224_float.mlir -o mobilenet_v2_1.0_224_float_dylib.vmfb

Please find the attached logs (Due to size limit, attached first half as parts)
[mobilenet_v2_1.0_224_float_dylib_translate_part1.log](https://github.com/google/iree/files/6960236/mobilenet_v2_1.0_224_float_dylib_translate_part1.log)
[mobilenet_v2_1.0_224_float_dylib_translate_part2.log](https://github.com/google/iree/files/6960243/mobilenet_v2_1.0_224_float_dylib_translate_part2.log)

**Comment by uccoder-hk** [comment]
Hello,

Any suggestion to the above issue based on the attached log?

**Comment by GMNGeoffrey** [comment]
Sorry you didn't get a response here. Both Ben and Scott were out of office. Just looking through the code (I'm not familiar with how this part works), I see

https://github.com/google/iree/blob/35fa381d3a625967ebac4097a951e2d5b97e3221/iree/compiler/Dialect/HAL/Target/LLVM/internal/AndroidLinkerTool.cpp#L71-L100

Given that you're *not* getting the error "ANDROID_NDK environment variable must be set" it seems like that isn't missing. One thing to double check https://github.com/google/iree/blob/35fa381d3a625967ebac4097a951e2d5b97e3221/iree/compiler/Dialect/HAL/Target/LLVM/LinkerTool.cpp#L109-L124 allows user override with `IREE_LLVMAOT_LINKER_PATH`. You don't have that env variable set, do you? Actually just noticed that it's mentioned in the [debugging notes](https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_android_cmake.md#host-configuration), so my spelunking revealed nothing new :-P

Then I would confirm that you're actually going down that path (breakpoint or good old printf debugging :-P) to help narrow down the problem

**Comment by ScottTodd** [comment]
Looks like this fell through the cracks, possibly without being resolved :/

I'm going to close as stale for now, but please reach out again if you have other questions.
