### ISSUE TITLE
failed to legalize operation 'std.uitofp' in VMVX backend

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#6995]
Observed the error when adding mhlo.rng_uniform end-to-end tests.

To repro:

```mlir
func @rng_uniform_2d() {
    %min = util.unfoldable_constant dense<-10.0> : tensor<f32>
    %max = util.unfoldable_constant dense<10.0> : tensor<f32>
    %shape = util.unfoldable_constant dense<[3, 3]>  : tensor<2xi32>
    %res = "mhlo.rng_uniform"(%min, %max, %shape) : (tensor<f32>, tensor<f32>, tensor<2xi32>) -> tensor<3x3xf32>
    check.expect_almost_eq_const(%res, dense<[
        [6.55154, -8.30982, -3.17117],
        [1.75741, 6.89606, -7.9653],
        [-3.03671, 2.10193, 7.24057]]> : tensor<3x3xf32>) : tensor<3x3xf32>
    return
}
```

**Comment by benvanik** [comment]
needs a conversion to CastUI32F32Op

**Comment by alliemartens** [comment]
@hanhanW Please update this old issue and add priority if needed.

**Comment by hanhanW** [comment]
The issue is that we have `arith.uitofp i32 -> f32` case. In this case, the check failed, so we're not able to lower it to vm dialect. I think it's reasonable to convert it to vm.uitofp if the src type is signless integer. WDYT?

https://github.com/iree-org/iree/pull/9727 fixes the issue.
