### ISSUE TITLE
Add monitoring to GCE VMs

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#7138]
It would be nice to have monitoring of our GCE VMs. Currently it's mostly just me poking around when something goes wrong. Like if we run out of disk space. Disk space monitoring requires installing monitoring agents https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/

**Comment by ScottTodd** [comment]
We're migrating to Azure (or maybe AWS). This old issue isn't worth keeping open.
