### ISSUE TITLE
Performance issues in running Bert inference on x86

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#7297]
I'm looking at performance issues in running bert inference on x86, using https://storage.googleapis.com/iree-model-artifacts/MobileNetV3Small-9c0042d19.tar.gz

This is the issue for tracking x86 performance in running Bert inference.

# Current status

| x86 1-thread | pixel 4 1-thread | x86 mult-thread | pixel 4 3-threads |
|--------------|-----------------|-----------------|------------------|
|      1200 ms   |          660 ms      |       228 ms         |            310 ms       |

# Couple issues

## Non-Performant generic op

The most critical dispatch is

```mlir
func @foo() -> tensor<1x4x384x384xf32> {
  %lhs = util.unfoldable_constant dense<2.0> : tensor<1x4x384x384xf32>
  %rhs = util.unfoldable_constant dense<1.0> : tensor<1x4x384x1xf32>
  %0 = chlo.broadcast_subtract %lhs, %rhs : (tensor<1x4x384x384xf32>, tensor<1x4x384x1xf32>) -> tensor<1x4x384x384xf32>
  %1 = "mhlo.exponential"(%0) : (tensor<1x4x384x384xf32>) -> tensor<1x4x384x384xf32>
  return %1 : tensor<1x4x384x384xf32>
}
```

On x86 single-threaded:

```
-------------------------------------------------------------------------------
Benchmark                                     Time             CPU   Iterations
-------------------------------------------------------------------------------
BM_foo/process_time/real_time              6.59 ms         6.59 ms          104
BM_foo/process_time/real_time              6.69 ms         6.69 ms          104
BM_foo/process_time/real_time              6.62 ms         6.62 ms          104
BM_foo/process_time/real_time              7.44 ms         7.44 ms          104
BM_foo/process_time/real_time              7.76 ms         7.76 ms          104
BM_foo/process_time/real_time              6.92 ms         6.92 ms          104
BM_foo/process_time/real_time_mean         7.00 ms         7.00 ms            6
BM_foo/process_time/real_time_median       6.81 ms         6.81 ms            6                                                                               BM_foo/process_time/real_time_stddev      0.484 ms        0.484 ms            6
BM_foo/process_time/real_time_cv           6.92 %          6.92 %             6
```

On Pixel 4 single-threaded:

```
-------------------------------------------------------------------------------
Benchmark                                     Time             CPU   Iterations
-------------------------------------------------------------------------------
BM_foo/process_time/real_time              2.20 ms         2.13 ms          302
BM_foo/process_time/real_time              2.18 ms         2.11 ms          302
BM_foo/process_time/real_time              2.19 ms         2.12 ms          302
BM_foo/process_time/real_time              2.20 ms         2.13 ms          302
BM_foo/process_time/real_time              2.27 ms         2.19 ms          302
BM_foo/process_time/real_time              2.15 ms         2.08 ms          302
BM_foo/process_time/real_time_mean         2.20 ms         2.13 ms            6
BM_foo/process_time/real_time_median       2.19 ms         2.12 ms            6
BM_foo/process_time/real_time_stddev      0.038 ms        0.037 ms            6
BM_foo/process_time/real_time_cv           1.74 %          1.73 %             6
```

The dispatch is called many times, so the total difference is around **180 ms**. (31 ms v.s. 213 ms)

## Non-Performant Matmul

The performance of x86 (single-threaded):

```
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
BM_dot_384x384x512/process_time/real_time       9.43 ms         9.43 ms           74
BM_dot_384x128x128/process_time/real_time      0.778 ms        0.778 ms          921
BM_dot_384x128x512/process_time/real_time       3.26 ms         3.26 ms          218
BM_dot_384x512x128/process_time/real_time       2.95 ms         2.95 ms          237
BM_dot_384x512x2/process_time/real_time        0.382 ms        0.382 ms         1815
BM_dot_384x384x32/process_time/real_time       0.574 ms        0.574 ms         1165
```

The performance of Pixel 4 (single-threaded):

```
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
BM_dot_384x384x512/process_time/real_time       2.78 ms         18.4 ms          234
BM_dot_384x128x128/process_time/real_time      0.512 ms         2.31 ms         1000
BM_dot_384x128x512/process_time/real_time       2.67 ms         14.9 ms          242
BM_dot_384x512x128/process_time/real_time       1.06 ms         6.58 ms          587
BM_dot_384x512x2/process_time/real_time        0.635 ms         2.75 ms         1111
BM_dot_384x384x32/process_time/real_time       0.253 ms         1.48 ms         2473
```

The dispatch_22 contains `dot_384x128x512` and a `linalg.generic` op, which is `176` ms on Pixel 4 and `221` ms on x86.

The dispatch_23 contains `dot_384x512x128` and a `linalg.generic` op, which is  `150` ms on Pixel 4 and `213` ms on x86.

CC @MaheshRavishankar @asaadaldien

**Comment by MaheshRavishankar** [comment]
> Dispatch 15 has better performance when enabling multi-threaded, so I think it's definitely a bad vector size issue. We are at good position with `iree-llvm-target-cpu-features=host`. The updated performance:
> 
> ## Matmul (single-threaded)
> ```
> ------------------------------------------------------------------------------------
> Benchmark                                          Time             CPU   Iterations
> ------------------------------------------------------------------------------------
> BM_dot_384x384x512/process_time/real_time       3.10 ms         3.11 ms          221
> BM_dot_384x128x128/process_time/real_time      0.230 ms        0.237 ms         3398
> BM_dot_384x128x512/process_time/real_time       1.00 ms         1.01 ms          706
> BM_dot_384x512x128/process_time/real_time      0.786 ms        0.795 ms          862
> BM_dot_384x512x2/process_time/real_time        0.284 ms        0.291 ms         1820
> BM_dot_384x384x32/process_time/real_time       0.200 ms        0.207 ms         3484
> ```
> 
> ## Dispatch 15 (single-threaded)
> ```
> ------------------------------------------------------------------------------------
> Benchmark                                          Time             CPU   Iterations
> ------------------------------------------------------------------------------------
> BM_serving_default/process_time/real_time        314 ms          314 ms            2
> ```
> 

This is still slow. The `generic` op is probably a reduction that isnt vectorized. This would be good to pursue.

> ## MobileBert Inference (single-threaded)
> ```
> -------------------------------------------------------------------------------------------
> Benchmark                                                 Time             CPU   Iterations
> -------------------------------------------------------------------------------------------
> BM_serving_default/process_time/real_time               310 ms          310 ms            2
> BM_serving_default/process_time/real_time               311 ms          311 ms            2
> BM_serving_default/process_time/real_time               306 ms          306 ms            2
> BM_serving_default/process_time/real_time               308 ms          308 ms            2
> BM_serving_default/process_time/real_time               306 ms          306 ms            2
> BM_serving_default/process_time/real_time               313 ms          313 ms            2
> BM_serving_default/process_time/real_time_mean          309 ms          309 ms            6
> BM_serving_default/process_time/real_time_median        309 ms          309 ms            6
> BM_serving_default/process_time/real_time_stddev       2.63 ms         2.63 ms            6
> BM_serving_default/process_time/real_time_cv           0.85 %          0.85 %             6
> ```
> 
> ## MobileBert Inference (multi-threaded)
> ```
> -------------------------------------------------------------------------------------------
> Benchmark                                                 Time             CPU   Iterations
> -------------------------------------------------------------------------------------------
> BM_serving_default/process_time/real_time              96.2 ms          607 ms            7
> BM_serving_default/process_time/real_time               103 ms          628 ms            7
> BM_serving_default/process_time/real_time              94.0 ms          597 ms            7
> BM_serving_default/process_time/real_time              95.8 ms          608 ms            7
> BM_serving_default/process_time/real_time              97.4 ms          617 ms            7
> BM_serving_default/process_time/real_time               142 ms          902 ms            7
> BM_serving_default/process_time/real_time_mean          105 ms          660 ms            6
> BM_serving_default/process_time/real_time_median       96.8 ms          613 ms            6
> BM_serving_default/process_time/real_time_stddev       18.4 ms          119 ms            6
> BM_serving_default/process_time/real_time_cv          17.57 %         18.04 %             6
> ```
> 
> For multi-threaded, there are 8 workers in total.
> 
> ![image](https://user-images.githubusercontent.com/6949191/136839031-1477330b-8d5e-4ac6-ab56-4d5424cda70c.png)
> 
> ## side note
> I think there are issues in default flags.
> 
> https://github.com/google/iree/blob/a85173143d7672d3d508ae38283964a08ed62e86/iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp#L88-L94
> 
> The `targetOptions` is using default host flags. However, the default value of `clTargetCPUFeatures` flag is empty string, which will overwrite the default configuration. I think they should be consistant, i.e., using `targetOptions.targetCPUFeatures` as default value. I'll send out a PR to fix default flag issues.

Actually I am fine with how the defaults are. The default flags for `clTargetCPUFeatures` ensures that we pick a vector size of `4` unless we are sure we want to run this on the host, in which case it results in the vector size of `16`. Given the host-device separation within IREE, this default makes the intent more explicit.
