### ISSUE TITLE
 no such package 'integrations/tensorflow/e2e'

### ISSUE THREAD

**Issue by chiachia36** [iree-org/iree#7422]
Hi,

I tried to run e2e test. ([Tensorflow e2e test](https://github.com/google/iree/tree/main/integrations/tensorflow/e2e))

I met some problems, when I ran the command `bazel run //integrations/tensorflow/e2e:conv_test_manual` in the section **Running Tests**.

Here is my error message.
```
ERROR: Skipping '//integrations/tensorflow/e2e:conv_test_manual': no such package 'integrations/tensorflow/e2e': Package is considered deleted due to --deleted_packages
WARNING: Target pattern parsing failed.
ERROR: no such package 'integrations/tensorflow/e2e': Package is considered deleted due to --deleted_packages
INFO: Elapsed time: 0.252s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```
Thanks!

**Comment by GMNGeoffrey** [comment]
There is a note at the top redirecting people, but maybe we should just delete that file, unless someone has the cycles to write a new one

**Comment by ScottTodd** [comment]
> I am curious about the usage of e2e. If I want to convert tensorflow model to mlir input and iree input, could you give me some reference?

See https://google.github.io/iree/ml-frameworks/tensorflow/ and https://github.com/google/iree/tree/main/colab

**Comment by chiachia36** [comment]
> 
> 
> Did you first follow https://google.github.io/iree/building-from-source/getting-started/ ?

Yes, I ran all steps and passed all test.

**Comment by GMNGeoffrey** [comment]
> Yes, I ran all steps and passed all test.

Alrighty, let's look into that failure then. What command are you running exactly? There are multiple things on that page. It looks like you're building the python bindings from source? That is always the most fiddly thing, in my experience. So first off, is that actually what you want to do? We have pip packages you can install, which will be much nicer if you're not trying to actually alter the bindings.
