### ISSUE TITLE
lit tests using certain tools are incredibly slow on Windows

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#7427]
Seems to be a recent regression, at least reproducible on my machine.

At some older commit (e.g. https://github.com/google/iree/commit/88e2aaee5), 

```
λ ctest -R iree/tools/test/iree-run-mlir.mlir.test --verbose

...

The following tests passed:
        iree/tools/test/iree-run-mlir.mlir.test

100% tests passed, 0 tests failed out of 1

Label Time Summary:
hostonly           =   3.31 sec*proc (1 test)
iree/tools/test    =   3.31 sec*proc (1 test)
```

At a recent commit (e.g. https://github.com/google/iree/commit/cde0270b2),

```
λ ctest -R iree/tools/test/iree-run-mlir.mlir.test --verbos

...

851: D:\dev\projects\iree\build_tools\cmake\run_test.ps1 : Test timed out after 120000 millis

...

0% tests passed, 1 tests failed out of 1

Label Time Summary:
hostonly           = 171.01 sec*proc (1 test)
iree/tools/test    = 171.01 sec*proc (1 test)

Total Test time (real) = 171.17 sec

The following tests FAILED:
        851 - iree/tools/test/iree-run-mlir.mlir.test (Failed)
```

running the tools outside of ctest is still fast

**Comment by GMNGeoffrey** [comment]
> is something scanning the entire working directory? like, does the lit runner grep across files or something for path fixups?

run_lit.sh used to do that, but I ripped that part out I thought. I don't speak ps1. Scott, you said this happened with both run_lit.sh and run_lit.ps1? Can you try running them directly, not under ctest but with the exact same command and working directory ctest uses?

**Comment by benvanik** [comment]
ETW time!
