### ISSUE TITLE
Do something better than silently disabling tests when PyYAML is not found

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#7454]
On #7449 , @GMNGeoffrey  [commented](https://github.com/google/iree/pull/7449#discussion_r735831671):

> I really don't like silently disabling tests (and yes, warnings in the long list of warnings that no one reads counts as silently). This sort of thing is how you discover that some tests were never getting run.

What can we do that would be better?  Provide PyYAML in third_party/ ? Just require PyYAML when building any tests at all (and then, offer an option to opt out of the tests that need it and still be able to build the rest of tests, just not as default behavior?)

**Comment by allieculp** [comment]
Sending to backlog due to the date of the issue - please reprioritize if needed.

**Comment by ScottTodd** [comment]
Only one test still uses PyYAML after https://github.com/iree-org/iree/pull/18262, and I've just left that test disabled on CI. Closing this.
