### ISSUE TITLE
Cannot materialize the result for `vm.const.ref.zero` in emitc

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#7487]
Hitting the issue when doing integration work.

https://source.cloud.google.com/results/invocations/8abe03c4-c49d-4674-baaf-5dbd121c2b53/targets/iree%2Fgcp_ubuntu%2Fcmake%2Flinux%2Fx86-swiftshader%2Fpresubmit/log

As discussed, disable the tests for now to unblock integrations.

**Comment by simon-camp** [comment]
#7565 fixes the compilation errors, but one test remains disabled as it fails at runtime.

**Comment by benvanik** [comment]
The referenced tests are enabled now in #5953. There's still quite a few `attributes {emitc.exclude}` that indicate there are other issues but not `vm.const.ref.zero`.
