### ISSUE TITLE
Support device side buffers for Python API

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#7638]
Any real integration via the Python API requires the ability to pass/return opaque device side buffers. This will require some design work.

**Comment by alliemartens** [comment]
@stellaraccident Still an active issue or no?

**Comment by alliemartens** [comment]
@stellaraccident Old issue alert! Is this still active?

**Comment by alliemartens** [comment]
@stellaraccident Old issue alert! Is this still active?

**Comment by stellaraccident** [comment]
Done as part of the DeviceArray work.
