### ISSUE TITLE
Encode i4 rodata in VM

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#7691]
When running the test case in https://github.com/google/iree/issues/7689, we're hitting a "failure to encode" error at https://github.com/google/iree/blob/727d793f354ae4b68a0a7ef6920ee0993fe050db/iree/compiler/Dialect/VM/Target/Bytecode/BytecodeEncoder.cpp#L363

**Comment by benvanik** [comment]
Closing for now until we've got a test case to work with. Please reopen if this is still important.
