### ISSUE TITLE
Add filters to trim down the benchmark permutations for pull requests

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#7792]
Landed commits and pull requests represent different workflows. We want to run all benchmark permutations for landed commits to understand the impact for all and guard against regressions. But for pull requests, aside from testing perf impact and guarding against perf regression early, we also want to have fast iterations. So it makes sense to reduce the amount of benchmark permutations we run there, esp. right now a full benchmark job run takes ~ 1 hour. Some concrete ideas:

* For both CPU and GPU, we can probably avoid running all benchmarks with default flags. Experimental flags covers effectively the same permutations and is where typically new feature developments come from.
* We can avoid running known slow IREE backends (like VMVX) for now. It's sort of verified by CPU dylib in general.
* For CPU, there are lots of permutations over big/little core and # of threads. Only running big/little core for 1/4 thread should suffice to test both single thread vs. multiple threads.
* We might still want to run all models though to avoid overfitting to specific models.
* ...

Now needs certainly still exists to run all benchmarks on pull requests, .e.g., if I'm working explicitly on a feature that touches stuff that are trimmed down in the above lists. So I think we might want to split the current `buildkite:benchmark` label into `buildkite:benchmark-full` vs. `buildkite:benchmark-reduced` to accommodate different needs. (It can effectively go further like `buildkite:benchmark-cpu`, `builidkite:benchmark-gpu`, etc., but we can take it step by step.)

**Comment by GMNGeoffrey** [comment]
This is something we want on CI as well (and I was planning to work on) to limit which builds are run. The benchmarking case is slightly different, but related

**Comment by antiagainst** [comment]
Yup. Basically a layered/hierarchical set of tests/benchmarks with different triggers (CMake targets, buildkite labels, etc.) to run.

**Comment by ScottTodd** [comment]
Stale issue - we have some filters now.
