### ISSUE TITLE
Error when running samples in integration/tensorflow/e2e

### ISSUE THREAD

**Issue by chiachia36** [iree-org/iree#7815]
Hi,
I want to check the whole process of an example.
I chose the example [matrix_ops_static_test.py](https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/matrix_ops_static_test.py) to run.
I ran it with command `python3.9 matrix_ops_static_test.py`.
Then, I got the file `tf_input.mlir` and `iree_input.mlir`.
I found that the operation in `tf_input.mlir` are in tf_executor dialect, so I tried to convert it to MHLO dialect before use it as the input of `iree-translate`.
Here is my command to convert the file.
`tf-opt -tf-executor-to-functional-conversion  /tmp/cache_bazel/MatrixOpsStaticModule/tf_input.mlir -o matrix-op/matrix_op_tf.mlir
`
I got the error message.
`/tmp/cache_bazel/MatrixOpsStaticModule/tf_input.mlir:3:392: error: #tf_type<"shape<64x32>"> : 'none' attribute created with unregistered dialect. If this is intended, please call allowUnregisteredDialects() on the MLIRContext, or use -allow-unregistered-dialect with mlir-opt`
So, I tried this command.
`mlir-opt -allow-unregistered-dialect /tmp/cache_bazel/MatrixOpsStaticModule/tf_input.mlir -o matrix-op/tf_executor_input.mlir`
Then, I still got other error meassage.
```
/tmp/cache_bazel/MatrixOpsStaticModule/tf_input.mlir:3:131: error: expected ')'
  func @__inference_basic_matmul_2310(%arg0: tensor<64x32xf32> {tf._user_specified_name = "lhs", tf_saved_model.index_path = [0]} loc(unknown), %arg1: tensor<32x16xf32> {tf._user_specified_name = "rhs", tf_saved_model.index_path = [1]} loc(unknown)) -> (tensor<64x16xf32> {tf_saved_model.index_path = []}) attributes {tf._construction_context = "kEagerRuntime", tf._input_shapes = [#tf_type.shape<64x32>, #tf_type.shape<32x16>], tf_saved_model.exported_names = ["basic_matmul"]} {
                                                                                                                                  ^
/tmp/cache_bazel/MatrixOpsStaticModule/tf_input.mlir:3:143: error: expected operation name in quotes
  func @__inference_basic_matmul_2310(%arg0: tensor<64x32xf32> {tf._user_specified_name = "lhs", tf_saved_model.index_path = [0]} loc(unknown), %arg1: tensor<32x16xf32> {tf._user_specified_name = "rhs", tf_saved_model.index_path = [1]} loc(unknown)) -> (tensor<64x16xf32> {tf_saved_model.index_path = []}) attributes {tf._construction_context = "kEagerRuntime", tf._input_shapes = [#tf_type.shape<64x32>, #tf_type.shape<32x16>], tf_saved_model.exported_names = ["basic_matmul"]} {
```
I want to ask that did I misunderstand the usage of the tool or other reason?

Thanks a lot!

**Comment by ScottTodd** [comment]
Yeah, there are several tools with similar names and slightly different capabilities. If you look at the output from running the python code, it should print which commands + flags are being run.

Here's a notebook for reference: https://colab.research.google.com/gist/ScottTodd/1e54ed2ed953fc4f79ac5b268eb216b2/iree-tf-tests-mlir-files.ipynb#scrollTo=mglvh6tKGgoI

```
I1112 16:43:17.433974 139627441915776 binaries.py:221] Invoke IREE Pipeline:
  /usr/local/lib/python3.7/dist-packages/iree/tools/tf/iree-import-tf /tmp/iree/modules/ControlFlowModule/tfmodule.saved_model --tf-import-type=savedmodel_v2 --tf-savedmodel-exported-names= --tf-savedmodel-tags= --mlir-print-debuginfo --save-temp-tf-input=/tmp/iree/modules/ControlFlowModule/tf_input.mlir --save-temp-mid-level-input=/tmp/iree/modules/ControlFlowModule/tf_mid_level_input.mlir --save-temp-iree-input=/tmp/iree/modules/ControlFlowModule/iree_input.mlir --pass-pipeline-crash-reproducer=/tmp/iree/modules/ControlFlowModule/reproducer__iree_llvmaot.mlir.import-tf
  /usr/local/lib/python3.7/dist-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib-llvm-aot -o=/tmp/iree/modules/ControlFlowModule/iree_llvmaot/compiled.vmfb --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/lib/python3.7/dist-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --pass-pipeline-crash-reproducer=/tmp/iree/modules/ControlFlowModule/reproducer__iree_llvmaot.mlir
[ RUN      ] ControlFlowTest.test_long_sequence
```

The first tool is `iree-import-tf`, which runs on a TensorFlow SavedModel and produces three .mlir files (`tf_input`, `tf_mid_level_input`, and `iree_input`). The next is `ireec`. If you want to fork off from Python, you can typically use the `iree_input.mlir` with `iree-translate -iree-input-type=mhlo ...`

`iree-import-tf` runs some IREE-specific passes on top of what `tf-opt` or `mlir-opt` would include, so it's safest to treat it as a black box, unless you need to work on that import flow itself.

---

Our docs at https://google.github.io/iree/ml-frameworks/tensorflow/ are a bit sparse, but they do generally recommend `iree-import-tf -o iree_input.mlir` -> `iree-translate`

**Comment by chiachia36** [comment]
Thanks for your reply.
Actually, I used `iree-input.mlir` directly before I used `tf-input.mlir`.
And I got the error message, so I thought I couldn't use it directly.
```
/tmp/cache_bazel/MatrixOpsStaticModule/iree_input.mlir:8:10: error: custom op 'hal.tensor.import' is unknown
    %0 = hal.tensor.import %arg0 : !hal.buffer_view -> tensor<64x32xf32> loc(#loc0)
```

Moreover, I also tried to use `iree-import-tf` to generate my own `.mlir` file for my model.
Here is the part of the model in my code.
```
class MyModel(Model):
  def __init__(self):
    super(MyModel, self).__init__()    
    # Define your layers here.
    input_shape = (1, 28, 28, 3)
    self.conv1 = Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=input_shape)
    self.flatten = Flatten()
    self.d1 = Dense(128, activation='relu')
    self.d2 = Dense(10, activation='softmax')

  def call(self, x):
    # Define your forward pass here,
    # using layers you previously defined (in __init__).
    x = self.conv1(x)
    x = self.flatten(x)
    x = self.d1(x)
    return self.d2(x)
```
However, I still got some error message.
```
<unknown>:0: note: loc(callsite(callsite(fused["Conv2D:", "my_model/conv2d/Conv2D@__inference__wrapped_model_22767"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_22942"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): see current operation: %14 = "mhlo.dynamic_conv"(%arg0, %13, %7) {batch_group_count = 1 : i64, dimension_numbers = #mhlo.conv<[b, 0, 1, f]x[0, 1, i, o]->[b, 0, 1, f]>, feature_group_count = 1 : i64, rhs_dilation = dense<1> : tensor<2xi64>, window_strides = dense<1> : tensor<2xi64>} : (tensor<?x28x28x1xf32>, tensor<3x3x1x32xf32>, tensor<4xi32>) -> tensor<?x26x26x32xf32>
Running iree-import-tf MHLO Import pass pipeline failed (see diagnostics)
```

Thanks for the trouble.

**Comment by benvanik** [comment]
one of your things is out of date - probably iree-translate (hal.tensor.import is new in the last week)

**Comment by chiachia36** [comment]
I will try to clone the newest version and run the steps  again. Thanks!

**Comment by ScottTodd** [comment]
This issue looks stale. Can you re-open or a file a new issue if you are still having trouble? Thanks!
