### ISSUE TITLE
python binding support multi-threading

### ISSUE THREAD

**Issue by arvin-chou** [iree-org/iree#7861]
I notice that bindings/python does not support multi-thread (there are no `thread-*` or `task_topology_group_count` alike function name)
could it support multi-thread control under python binding in the future?

**Comment by stellaraccident** [comment]
@benvanik is the flag based API here changing at all with the multi device work? If so, we want to adapt to what you are doing there.

**Comment by alliemartens** [comment]
@benvanik Checking on this older issue, still active with a priority or no?

**Comment by alliemartens** [comment]
@stellaraccident @benvanik Still active?

**Comment by stellaraccident** [comment]
There is an API for setting flags. That should be enough
