### ISSUE TITLE
iree_pydm/importer/intrinsics.py test failed after integrations

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#7879]
See log: https://source.cloud.google.com/results/invocations/ac2c4081-cd62-44c4-9bfe-8473774ccb97/targets/iree%2Fgcp_ubuntu%2Fcmake%2Flinux%2Fx86-swiftshader%2Fgoogle/log

**Comment by alliemartens** [comment]
@hanhanW Old issue alert! Is this still active?
