### ISSUE TITLE
Error running mhlo.dynamic_reshape

### ISSUE THREAD

**Issue by gnecula** [iree-org/iree#7888]
I am experimenting with dynamic shapes in JAX + IREE, and I am having trouble running a simple example of the form:
```
def f(x):   # x: f32[w, h] -> f32[w*h]
   return jnp.reshape(x, ((x.shape[0] * x.shape[1],))
```

See below the mhlo code that I generate.

I am using `mhlo.dynamic_reshape` with the second argument a `tensor<1xi32>`. I get an error that `'flow.tensor.reshape' op operand #3 must be index, but got 'i32'`. How do I convert a `tensor<1xi32>` to a ``tensor<1xindex>` (if the latter even makes sense). I tried "convert" and "bitcast_convert" and neither likes the result type to be a tensor of index.

Repro:
```
    from iree.compiler import compile_str

    CODE = """
module @jit_f.2  {
  func public @main(%arg0: tensor<?x?xf32> {mhlo.is_same_data_across_replicas} loc(unknown)) -> tensor<?xf32> {
    %0 = "mhlo.get_dimension_size"(%arg0) {dimension = 0 : i64} : (tensor<?x?xf32>) -> tensor<i32>
    %1 = "mhlo.get_dimension_size"(%arg0) {dimension = 1 : i64} : (tensor<?x?xf32>) -> tensor<i32>
    %2 = mhlo.multiply %0, %1 : tensor<i32>
    %3 = "mhlo.broadcast_in_dim"(%2) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<i32>) -> tensor<1xi32>
    %4 = "mhlo.concatenate"(%3) {dimension = 0 : i64} : (tensor<1xi32>) -> tensor<1xi32>
    %5 = "mhlo.dynamic_reshape"(%arg0, %4) : (tensor<?x?xf32>, tensor<1xi32>) -> tensor<?xf32>
    return %5 : tensor<?xf32>
  }
}
    """

    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```
Is there a better MHLO that I should generate for this purpose?

The error message:
```
>         raise CompilerToolError(process)
E         iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
E         Diagnostics:
E         <stdin>:9:10: error: 'flow.tensor.reshape' op operand #3 must be index, but got 'i32'
E             %5 = "mhlo.dynamic_reshape"(%arg0, %4) : (tensor<?x?xf32>, tensor<1xi32>) -> tensor<?xf32>
E                  ^
E         <stdin>:2:1: error: conversion from source -> vm failed
E         module @jit_f.2  {
E         ^
```

**Comment by benvanik** [comment]
We've only tested with `tensor<...index>` for dimensions - there would need to be some casts inserted if you are coming in with i32. If JAX generates that regularly we'll need to fix things to insert the casts somewhere - though it'd be ideal if `index` was returned from get_dimension_size.

**Comment by stellaraccident** [comment]
Yeah, this is one of the MHLO design bugs that I've long been wanting anyone to care about/fix. The other frontends did not make these mistakes. MHLO is only nominally really coherent for dynamic shapes.

With that said, we can see about yet another MHLO point fix for this.

**Comment by stellaraccident** [comment]
@rsuderman can you look at the lowering for dynamic reshape? It should be doing a type check for index and inserting an index_cast if not the right type.

**Comment by gnecula** [comment]
I can easily insert the cast myself, if somebody teaches me how to express that in MHLO. 

BTW, I prefer that `get_dimension_size` returns `i32` because we need to do arithmetic with those results.

**Comment by rsuderman** [comment]
This one needs some detensoring for get_dimension_size. I'll probably add a set of specialized lowerings that handle `mhlo.foo` operations on `tensor.from_elements` bypass the tensor and directly access the values.

**Comment by rsuderman** [comment]
Verified that with the new shape operations this compiles successfully. Closing.
