### ISSUE TITLE
mhlo.dynamic_broadcast_in_dim was explicitly marked illegal

### ISSUE THREAD

**Issue by gnecula** [iree-org/iree#7898]
This is in the context of JAX+IREE for dynamic shapes. The code below tries to broadcast `f32[w]` to `f32[w, w]`, but it fails with `failed to legalize operation 'mhlo.dynamic_broadcast_in_dim' that was explicitly marked illegal`.

Is the MHLO code that I am generating valid? Should I generate something else? 

Repro:
```
from iree.compiler import compile_str

CODE = """
module @jit_f.3  {
  func public @main(%arg0: tensor<?xf32> loc(unknown)) -> tensor<?x?xf32> {
    %0 = "mhlo.get_dimension_size"(%arg0) {dimension = 0 : i64} : (tensor<?xf32>) -> tensor<i32>
    %1 = "mhlo.broadcast_in_dim"(%0) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<i32>) -> tensor<1xi32>
    %2 = "mhlo.broadcast_in_dim"(%0) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<i32>) -> tensor<1xi32>
    %3 = "mhlo.concatenate"(%1, %2) {dimension = 0 : i64} : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32>
    %4 = "mhlo.dynamic_broadcast_in_dim"(%arg0, %3) {broadcast_dimensions = dense<1> : tensor<1xi64>} : (tensor<?xf32>, tensor<2xi32>) -> tensor<?x?xf32>
    return %4 : tensor<?x?xf32>
  }
}
"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

and the error:
```
$ python tests/iree_repro.py
Traceback (most recent call last):
  File "/Users/necula/Source/jax/tests/iree_repro.py", line 16, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/Users/necula/.pyenv/versions/jax39/lib/python3.9/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/Users/necula/.pyenv/versions/jax39/lib/python3.9/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:8:10: error: failed to legalize operation 'mhlo.dynamic_broadcast_in_dim' that was explicitly marked illegal
    %4 = "mhlo.dynamic_broadcast_in_dim"(%arg0, %3) {broadcast_dimensions = dense<1> : tensor<1xi64>} : (tensor<?xf32>, tensor<2xi32>) -> tensor<?x?xf32>
         ^
<stdin>:2:1: error: conversion from source -> vm failed
module @jit_f.3  {
^


Invoked with:
 ireec /Users/necula/.pyenv/versions/jax39/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/Users/necula/.pyenv/versions/jax39/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by gnecula** [comment]
Perhaps I should stop filing bugs if dynamic shapes is not really meant to be working yet. In that case, please just take a quick looks at these MHLO modules to see if they look reasonable.

**Comment by benvanik** [comment]
I think it'd be useful to split out what are MHLO issues vs what are IREE issues. MHLO itself will need to be made properly dynamic shape aware before we are able to do anything, and though I'm sure there are issues we have in IREE laying in wait it's difficult to triage when we can't trust that the frontend is correct. A lot of these are going to end up being things like broken canonicalizers/folders/lowerings into linalg. We need some better error messages to indicate this more clearly and route users to the right place (https://github.com/tensorflow/mlir-hlo) - I think that's being tracked in #7890 now.

**Comment by stellaraccident** [comment]
Yeah, I appreciate the attempts, but MHLO does need significant work for dynamic shapes, and the team that owns this does not think they will be able to look much at it until next year. Specifically, I think this op is on the list to delete outright or redesign.

There may still be IREE bugs in some of this, but both pytorch and TFLite use dynamic shape patgs pretty directly (and were designed right), which gives me some confidence to say that most of the issues here are with MHLO -- it has basically had the minimum amount of work done on it to support a small number of Tensorflow use cases, and you are hitting the bounds of it not having been owned and supported by anyone up until very recently.

I am interested in these things working and the bugs can help us make some incremental progress, but we also need the owners to take more of a holistic interest and turn that into progress.

**Comment by stellaraccident** [comment]
So, looking more at this (now that I'm out of bed):

```
CODE = """
module @jit_f.3  {
  func public @main(%arg0: tensor<?xf32> loc(unknown)) -> tensor<?x?xf32> {
    %0 = "mhlo.get_dimension_size"(%arg0) {dimension = 0 : i64} : (tensor<?xf32>) -> tensor<i32>
    %1 = "mhlo.broadcast_in_dim"(%0) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<i32>) -> tensor<1xi32>
    %2 = "mhlo.broadcast_in_dim"(%0) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<i32>) -> tensor<1xi32>
    %3 = "mhlo.concatenate"(%1, %2) {dimension = 0 : i64} : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32>
    %4 = "mhlo.dynamic_broadcast_in_dim"(%arg0, %3) {broadcast_dimensions = dense<1> : tensor<1xi64>} : (tensor<?xf32>, tensor<2xi32>) -> tensor<?x?xf32>
    return %4 : tensor<?x?xf32>
  }
}
"""
```

This would be a good example to bring up with the MHLO team. Basically, there is an ambiguity in the way that dynamic_broadcast_in_dim is defined in that the symbolic dimensions can either signify quantities or expansion (i.e. `1`). While it is possible to handle this generically, it carries some pretty high costs and is better avoided if possible. I'm yet to see a real case where the symbolic dimensions are intended to indicate expansion -- and in fact in this case, they do not.

The ambiguity makes it impossible to have a local lowering for dynamic_broadcast_in_dim, and choosing the correct lowering would need to be done with some analysis. There have been some half attempts at doing this, but in the past, I've rationalized such cases with more specificity at the layer above. Was this just you open coding this program, or was it produced by something that we could potentially look at?

**Comment by stellaraccident** [comment]
(if there is an actual use case for the full generality of dynamic_broadcast_in_dim, I am open to doing the work; however, to date, we've found that all real cases could be resolved with a more specifically designed op/lowering at the frontend, and when that can be done, it will produce the least surprising results -- note that in our other frontend work, we have not encountered a case for the fully generic dynamic_broadcast_in_dim style op).

**Comment by GMNGeoffrey** [comment]
It's on my TODO list to make it easier for users to do basic triage and direct their issues to the right place: https://github.com/google/iree/issues/7890. Can you see if this repros with the mlir-hlo legalize_to_linalg pass? If so, it's an upstream issue for them (at least. We could also have an IREE issue)

**Comment by gnecula** [comment]
> Was this just you open coding this program, or was it produced by something that we could potentially look at?

This was generated by JAX, as part of the lowering of the lax.broadcast_in_dim in an [experimental branch](https://github.com/gnecula/jax/blob/bc46c0192307281c54783dee4567b02bb39cd743/jax/_src/lax/lax.py#L2617). lax.broadcast_in_dim follows the [HLO BroadcastInDim](https://www.tensorflow.org/xla/operation_semantics#broadcastindim) semantics, except that the output shape is dynamic. The dynamism of the output shape is limited in the sense that it passed the JAX internal shape checking rules, which ensure that the output shape is compatible. See [here](https://github.com/google/jax/blob/18baa6e93bbb2b6b45fcb4de4509e092ea970d76/jax/_src/lax/lax.py#L2551). 

It is entirely reasonable that the lowering for lax.broadcast_in_dim can be more elaborate if mhlo.dynamic_broadcast_in_dim chooses to be more restrictive. Note that JAX uses the same shape checking rules for static and for dynamic broadcast.

**Comment by gnecula** [comment]
> Can you see if this repros with the mlir-hlo legalize_to_linalg pass?

Can you please point me to documentation for how to try this?

**Comment by GMNGeoffrey** [comment]
It's this repository: https://github.com/tensorflow/mlir-hlo/ and this pass https://github.com/tensorflow/tensorflow/blob/ebe9eceb95c393b307a7776808423eaa93c4dabd/tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/transforms/mhlo_passes.td#L65. So `mlir-hlo-opt --hlo-legalize-to-linalg` on your input

**Comment by gnecula** [comment]
Thank you. At this point I am going to sign off for a vacation, but I will pick this up when I return.

**Comment by stellaraccident** [comment]
Thanks for the issue reports - lot's of good stuff to dig into in 2022. Have a good holiday.

**Comment by stellaraccident** [comment]
So looking at the code:

```
  if not all(core.symbolic_equal_one_of_dim(operand.shape[i],
                                            [1, shape[broadcast_dimensions[i]]])
             for i in range(operand_ndim)):
    msg = (
        "broadcast_in_dim operand dimension sizes must either be 1, or be "
        "equal to their corresponding dimensions in the target broadcast "
        "shape; got operand of shape {}, target broadcast shape {}, "
        "broadcast_dimensions {} ")
```

In your experimental dynamic case, are you doing any analysis that is guaranteeing this relationship? Because, if so, getting that information into the dynamic version of the op is precisely what makes it non-ambiguous. Basically, someone needs to do that analysis, and if it falls out naturally from your frontend, then we want to capture it vs duplicating it in the compiler backend. Like I said, open to doing the work either way, but we've gotten a long way by asking the higher level question so far and seeing if the problems can go away more by construction.

**Comment by gnecula** [comment]
That conditional checks the condition. JAX internally does not use `?` for dynamic shapes, uses actual polynomials in terms of the dimension variables that are introduced at the top-level of the computation. So, it is able to check that two unknown shapes are the same. E.g., in `f32[w, w]` it will know that the shape is square. All this information is lost when lowering to MHLO, because I do not know how to encode it.

**Comment by GMNGeoffrey** [comment]
I think we can presume that this is an issue in upstream MHLO and close this. Please reopen if you identify this as an IREE issue.
