### ISSUE TITLE
Warn early on potential for running into windows path-length limit

### ISSUE THREAD

**Issue by oroppas** [iree-org/iree#7917]
**Describe the bug**

Building IREE out of source fails to generate *.pdb file.

```
[1/658] Building CXX object iree\compiler\Dialect\Stream\Conversion\StandardToStream\CMakeFil...er_Dialect_Stream_Conversion_StandardToStream_StandardToStream.dir\ConvertConstantOps.cpp.obj
FAILED: iree/compiler/Dialect/Stream/Conversion/StandardToStream/CMakeFiles/iree_compiler_Dialect_Stream_Conversion_StandardToStream_StandardToStream.dir/ConvertConstantOps.cpp.obj
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\cl.exe  /nologo /TP -DIREE_HAVE_EMITC_DIALECT -IC:\msys64\home\ryuta\packages\iree\iree\third_party\llvm-project\llvm\include -IC:\msys64\home\ryuta\packages\iree\build\third_party\llvm-project\llvm\include -IC:\msys64\home\ryuta\packages\iree\iree\third_party\llvm-project\mlir\include -IC:\msys64\home\ryuta\packages\iree\build\third_party\llvm-project\llvm\tools\mlir\include -IC:\msys64\home\ryuta\packages\iree\build\third_party\llvm-project\llvm\tools\mlir-hlo\include -IC:\msys64\home\ryuta\packages\iree\iree -IC:\msys64\home\ryuta\packages\iree\build /DWIN32 /D_WINDOWS /EHsc /Zi /O2 /Ob1 -MD /DWIN32_LEAN_AND_MEAN /DNOMINMAX /D_USE_MATH_DEFINES /D_CRT_SECURE_NO_WARNINGS /D_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES /GR- /bigobj /Zc:preprocessor /W3 /wd4200 /wd4018 /wd4146 /wd4244 /wd4267 /wd4005 /wd4065 /wd4141 /wd4624 /wd5105 -std:c++14 /showIncludes /Foiree\compiler\Dialect\Stream\Conversion\StandardToStream\CMakeFiles\iree_compiler_Dialect_Stream_Conversion_StandardToStream_StandardToStream.dir\ConvertConstantOps.cpp.obj /Fdiree\compiler\Dialect\Stream\Conversion\StandardToStream\CMakeFiles\iree_compiler_Dialect_Stream_Conversion_StandardToStream_StandardToStream.dir\iree_compiler_Dialect_Stream_Conversion_StandardToStream_StandardToStream.pdb /FS -c C:\msys64\home\ryuta\packages\iree\iree\iree\compiler\Dialect\Stream\Conversion\StandardToStream\ConvertConstantOps.cpp
C:\msys64\home\ryuta\packages\iree\iree\iree\compiler\Dialect\Stream\Conversion\StandardToStream\ConvertConstantOps.cpp: fatal error C1041: cannot open program database 'iree\compiler\Dialect\Stream\Conversion\StandardToStream\CMakeFiles\iree_compiler_Dialect_Stream_Conversion_StandardToStream_StandardToStream.dir\iree_compiler_Dialect_Stream_Conversion_StandardToStream_StandardToStream.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
```

**To Reproduce**

Clone the source. Copy and save the following configure and build script into, say `build.cmd`:

```
cmake ^
  -G Ninja ^
  -B build ^
  -S iree ^
  -DCMAKE_BUILD_TYPE=RelWithDebInfo ^
  -DIREE_ENABLE_ASSERTIONS=ON ^
  -DMLIR_ENABLE_BINDINGS_PYTHON=1 ^
  -DMLIR_ENABLE_SPIRV_CPU_RUNNER=1 ^
  -DMLIR_ENABLE_VULKAN_RUNNER=1 ^
  -DVulkan_INCLUDE_DIR="C:/VulkanSDK/1.2.198.1/Include" ^
  -DVulkan_LIBRARY="C:/VulkanSDK/1.2.198.1/Lib/vulkan-1.lib"

cmake --build build -- -j 1 -k 0
```

Run `build.cmd` in x64 Native Tools Command Prompt for VS 2022.

**Additional context**

I checked 

`iree\compiler\Dialect\Stream\Conversion\StandardToStream\CMakeFiles\iree_compiler_Dialect_Stream_Conversion_StandardToStream_StandardToStream.dir` under `build` directory, 

as the error message points

`fatal error C1041: cannot open program database 'iree\compiler\Dialect\Stream\Conversion\StandardToStream\CMakeFiles\iree_compiler_Dialect_Stream_Conversion_StandardToStream_StandardToStream.dir\iree_compiler_Dialect_Stream_Conversion_StandardToStream_StandardToStream.pdb'`

```
C:\msys64\home\ryuta\packages\iree>dir build\iree\compiler\Dialect\Stream\Conversion\StandardToStream\CMakeFiles\iree_compiler_Dialect_Stream_Conversion_StandardToStream_StandardToStream.dir\
 Volume in drive C is System
 Volume Serial Number is F63D-D612

 Directory of C:\msys64\home\ryuta\packages\iree\build\iree\compiler\Dialect\Stream\Conversion\StandardToStream\CMakeFiles\iree_compiler_Dialect_Stream_Conversion_StandardToStream_StandardToStream.dir

12/13/2021  05:28 PM    <DIR>          .
12/13/2021  05:28 PM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  694,542,868,480 bytes free
```

and the directory contain nothing.

**Comment by ScottTodd** [comment]
Looks like you're hitting the max path length on Windows (260 characters). This path component is 223 characters, which gets up to that limit when part of a full path: `iree\compiler\Dialect\Stream\Conversion\StandardToStream\CMakeFiles\iree_compiler_Dialect_Stream_Conversion_StandardToStream_StandardToStream.dir\iree_compiler_Dialect_Stream_Conversion_StandardToStream_StandardToStream.pdb`.

The (unfortunate) "fix" is to use a shorter root path like `C:\dev\projects\iree` instead of `C:\msys64\home\ryuta\packages\iree`. Last I checked, there wasn't a convenient way in CMake / MSVC / Windows to either automatically shorten paths or increase the maximum. We could also restructure the code paths for the few longest directories/files... again :/

**Comment by GMNGeoffrey** [comment]
Scott, is there a way we could give a better error message here?

**Comment by ScottTodd** [comment]
Last I checked... not really. The error is deep in CMake/MSVC, and what we're doing _should_ be fine. Any checks we add of our own would just be infrastructure complexity, similar to the git submodule init check.

**Comment by oroppas** [comment]
Hi Scott,

You're absolutely right. Shortening the root path fixed the issue.
It sounds like the best we can do is to document this limitation.

**Comment by oroppas** [comment]
I was naively thinking [enabling long paths](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later) will grant the immunity, but I guess I was wrong in this case.

**Comment by stellaraccident** [comment]
I suspect that all of the dev tools need to be recompiled/upgraded to opt in. I expect that visual studio is the biggest one, and i don't know if it is compatible yet. But also ninja and cmake.

What a mess. Since it breaks compatibility and requires an application change, I wish they'd just rev'd those apis and done some symbol magic to let binaries opt in with a simple setting... But no one asked me :)

**Comment by stellaraccident** [comment]
https://developercommunity.visualstudio.com/t/allow-building-running-and-debugging-a-net-applica/351628

Expected time to "critical mass": 5-10 years

**Comment by oroppas** [comment]
Hi Stella,

Thanks for the information. The situation is plain annoying at least...

@GMNGeoffrey, @ScottTodd,

Before I close this issue, I'd like to clarify the official solution.
(I'm guessing "use the short root path")

**Comment by ScottTodd** [comment]
This has a bit more concrete info: https://visualgdb.com/documentation/cmake/CMAKE_OBJECT_PATH_MAX/

I do get some warnings from CMake at configure time with good messages if _object files_ would spill over the max path length:

```
CMake Warning in iree/samples/simple_embedding/CMakeLists.txt:
  The object file directory

    D:/dev/scratch/some_really_long_path_for_testing_cmake/iree-build/iree/samples/simple_embedding/CMakeFiles/iree_samples_simple_embedding_simple_embedding_test_bytecode_module_dylib_x86_64_c.dir/./


  has 196 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file

    simple_embedding_test_bytecode_module_dylib_x86_64_c.c.obj

  cannot be safely placed under this directory.  The build may not work
  correctly.
```

Searching for "cmake max_path pdb" just points me back to our own issue, lol: https://github.com/google/iree/issues/490

Maybe there's a small window where pdb files spill over the limit but object files don't?

**Comment by ScottTodd** [comment]
I did also have a "troubleshooting" section in mind for the docs at https://google.github.io/iree/building-from-source/getting-started/:

https://github.com/google/iree/blob/993201d3d33e5bf170084f0fc8a8ceeab507e6be/docs/website/docs/building-from-source/getting-started.md#L129

I don't think "clone to a short path" is critical enough to go in the main instructions at the top of that page. If it was, we should push harder on keeping path lengths down so it isn't a problem in the first place. We're in an awkward middle spot where a few people have hit it, but not quite enough IMO. Because of that, I'm more inclined to note it at the bottom of the page, so it's at least documented _somewhere_. Other things like not updating git submodules when changing commits or using mismatching compiler and runtime versions could also go in such a troubleshooting / common issues section.

**Comment by stellaraccident** [comment]
We could just always recommend placing the build dir in Windows at the shortest possible path. This is what the ci does. I don't have a better idea: Microsoft should have fixed this decades ago, and even now, their own dev tools are lagging behind actually using the fix.

I'm not sure great is something to shoot for here. Pure pragmatics with something like that.

**Comment by ScottTodd** [comment]
Our old docs did call this out: https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_windows_cmake.md#clone 

> Tip:
    Clone to a short path like C:\projects\ to avoid issues with Windows maximum path lengths (260 characters).

I really don't want to spend characters talking about obscure OS/build system quirks on our getting started page though x_x

**Comment by benvanik** [comment]
agreed on not calling this out for everything; having a little cmake snippet seems easy enough though:
```
string(LENGTH ${CMAKE_SOURCE_DIR} _LENGTH)
if(WINDOWS AND _LENGTH GREATER_EQUAL 30)
  message(WARNING "path may be too long; see <some link>")
endif()
```

**Comment by GMNGeoffrey** [comment]
@oroppas want to send a patch for ^ :-)

Can stick it around here: https://github.com/google/iree/blob/35b9d4c937c68111008a16a38ef35f4d783bcb8e/CMakeLists.txt#L333

**Comment by ScottTodd** [comment]
It's not quite a fix for this, but we do now have a lint check for path length: https://github.com/iree-org/iree/pull/10367. I think I'll close this for now - CMake has some warnings and we'll try to keep path lengths short with that check. We _could_ still add a warning of our own, but I'm not convinced that would be accurate enough to be worth it.
