### ISSUE TITLE
Large performance regression in tosa conv ops after upstream merge.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#7954]
This merge commit caused a significant regression in tosa models with conv ops:
https://github.com/google/iree/commit/63a4724e168243a4697d654e90eb521a5e293bcf

![image](https://user-images.githubusercontent.com/75337/147305978-b19aae24-4091-471e-87f1-857c6706e7d5.png)

From looking at the IR before/after the merge it seems like conv2d handling changed to now not turn them into fully connected ops:
![image](https://user-images.githubusercontent.com/75337/147306024-20852106-b5b7-40d0-907f-edf55918e673.png)

Which then ends up as `linalg.conv_2d_nhwc_hwcf` instead of `linalg.matmul` like before.

I don't know enough to know what layer should be handling this - it feels like if there's such an extreme performance difference we'd want something at the linalg level to take the linalg conv op into matmuls instead of relying on that to happen at the frontend.

**Comment by MaheshRavishankar** [comment]
I think this was earlier happening as a canonicalization. Now it is not triggered with canonicalization but as a separate `createLinalgNamedOpConversion` pass. Looks like this conversion (intended or unintended) was triggered even later on. The use cases here need to be revisited. Doing this after dispatch region formation can result in stack allocations later on. For now they might be on balance still faster, cause convs are not vectorized but genms are. That will change soon though. Avoiding such conversion triggering much later in the pipeline would be better.

**Comment by stellaraccident** [comment]
Yeah, rolling back that canonicalization upstream was the right thing to do. This should happen early in the pipeline explicitly.

**Comment by rsuderman** [comment]
We should see the performance return to normal with splitting tosa-to-linalg-named-ops out of the normal tosa-to-linalg pass. I expect there was no constant propagation for the weight matrices used for tosa.conv -> tosa.matmul.

**Comment by stellaraccident** [comment]
For suspected constant prop issues, the generalized const eval stuff is at head and passing all tests, but disabled. Would be good to give it a spin. See flags: https://github.com/google/iree/blob/ebf3a6a25a5a86c5a68db0ee325d741c8bff4d26/iree/compiler/Translation/IREEVM.cpp#L86 (both of those need to be true for maximum effect)

**Comment by jpienaar** [comment]
Was this resolved post the split?

**Comment by rsuderman** [comment]
This should be resolved. We have a better layering / constant evaluation system so we won't make needless copies.
