### ISSUE TITLE
BERT LOAD4 becoming LOAD1 due to LLVM alignment issue

### ISSUE THREAD

**Issue by raikonenfnu** [iree-org/iree#8124]
For bert training model as seen [here](https://github.com/google/iree-samples/blob/main/ModelCompiler/nlp_models/bert_small_gen.py). We are facing perf issues with LOAD4s becoming LOAD1s later on in the llvm pipeline despite it being annotated in MLIR. 

Translate:
```bash
iree/tools/iree-translate --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=cuda -iree-cuda-llvm-target-arch=sm_70 -iree-hal-cuda-disable-loop-nounroll-wa ~/bert_model_training.mlir -o /tmp/bert_cuda.vmfb
```

Run:
```bash
/iree/tools/iree-benchmark-module --driver=cuda --function_input=1x512xi32=4 --function_input=1x512xi32=2 --function_input=1x512xi32=4 --function_input=1xi32=2 --entry_function=learn --module_file=/tmp/bert_cuda.vmfb
```

Artefacts:

0. [BERT Model in linalg mlir](https://storage.googleapis.com/iree-shared-files/nod-perf/stanley/models/bert_small_train_jan11.mlir)
1. [Print-after-all-dump](https://storage.googleapis.com/iree-shared-files/nod-perf/stanley/Reports/bert_cuda_dump.mlir)
2. [qdrep](https://console.cloud.google.com/storage/browser/_details/iree-shared-files/nod-perf/stanley/Reports/bert_cuda_jan14.qdrep;tab=live_object)
3. [kernelProfile.ncu-rep](https://console.cloud.google.com/storage/browser/_details/iree-shared-files/nod-perf/stanley/Reports/profile.ncu-rep;tab=live_object)
4. [dispatch45 llvmir](https://storage.googleapis.com/iree-shared-files/nod-perf/stanley/Reports/llvmir_sample___inference_learn_28700_dispatch_45.mlir)
5. [dispatch18 llvmir](https://storage.googleapis.com/iree-shared-files/nod-perf/stanley/Reports/llvmir_sample___inference_learn_28700_dispatch_18.mlir)

**Comment by ThomasRaoux** [comment]
Analyzed the problem. Few things were fixed in IREE however the main problem is that llvm alignment analysis is very limited as it won't recurse through phi nodes and has a recursion limit of 6.
I discussed this on llvm discourse but there isn't an obvious solution:
https://discourse.llvm.org/t/alignment-analysis/59617

I think the best solution would be to fix llvm and add a pass doing expensive alignment analysis that can be optionally enabled by some backend and enable it for NVPTX backend. This requires moving quite a few things around in llvm.

**Comment by raikonenfnu** [comment]
> Analyzed the problem. Few things were fixed in IREE however the main problem is that llvm alignment analysis is very limited as it won't recurse through phi nodes and has a recursion limit of 6. I discussed this on llvm discourse but there isn't an obvious solution: https://discourse.llvm.org/t/alignment-analysis/59617
> 
> I think the best solution would be to fix llvm and add a pass doing expensive alignment analysis that can be optionally enabled by some backend and enable it for NVPTX backend. This requires moving quite a few things around in llvm.

Sounds good, let me know how I can help/assist :)

**Comment by antiagainst** [comment]
Closing--no actions planned for now
