### ISSUE TITLE
Creating a new test suite in iree

### ISSUE THREAD

**Issue by ArunaKote** [iree-org/iree#8564]
want to create a test suite for testing a  pass where input is mlir file and output is binary file. Can I use test suite similar iree_bytecode_module,may i know what are steps to create new test suite in iree.

**Comment by ScottTodd** [comment]
See https://github.com/google/iree/blob/main/docs/developers/developing_iree/testing_guide.md#compiler-tests for an overview of testing the compiler.

To test a pass whose input is a .mlir file and whose output is a binary file, you may want a lit test running a translate tool (https://mlir.llvm.org/getting_started/Glossary/#translation) like `iree-translate`

For example: https://github.com/google/iree/blob/301091ac3cf4d2de7bda116547dde04c0571a70e/iree/compiler/Dialect/VM/Target/Bytecode/test/constant_encoding.mlir#L1-L8

Note the `-iree-vm-bytecode-module-output-format=flatbuffer-text` in that example so `FileCheck` has something to check. You could also just check for success or some console output like in https://github.com/google/iree/blob/301091ac3cf4d2de7bda116547dde04c0571a70e/iree/samples/vision/mnist_test.txt#L1-L3

**Comment by ArunaKote** [comment]
In file check there are different checks that is CHECK, CHECK-EMPTY,CHECK-COUNT,CHECK-NEXT,CHECK-SAME,CHECK-NOT,CHECK-DAG,CHECK-LABEL.May I know how the file check tool checks these in mlir files .

**Comment by ArunaKote** [comment]
In iree_lit_test_suite,for example if we add iree-run-mlir or iree-opt  in DATA section,what are the pass pipelines it will run?

**Comment by ScottTodd** [comment]
See https://mlir.llvm.org/getting_started/TestingGuide/ and https://llvm.org/docs/CommandGuide/FileCheck.html. Each `// RUN: ` specifies the command you want to run, including all flags like pass pipelines.

**Comment by ArunaKote** [comment]
How can we  check for success of output file generation in lit_test?

**Comment by ScottTodd** [comment]
> How can we check for success of output file generation in lit_test?

Lit checks the result code of what it runs, and you can check for files existing using bash in the run command, e.g.

```
// RUN: touch file.txt && test -f file.txt
```

**Comment by ScottTodd** [comment]
I think all questions were answered here, so closing the issue. Please re-open or reach out again if there's more you want help with.
