### ISSUE TITLE
Have better GEMM configurations for RISC-V targets

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#8568]
I recently found that we don't have good configurations when fixing long compilation time issue for RISC-V targets https://github.com/google/iree/issues/8431. In the past, we only had focus on Pixel 4. They were all used Pixel 4 configurations. For the time being, we have different strategies for different targets.

Now, we use x86 avx configuration, which is not the best for RISC-V targets. IMO, we can target some matmul shapes and set up better tiling sizes. E.g., we've been focusing on Bert matmul sizes for a while. The current configurations are set based on generally good performance for those shapes. The below shapes are what we care in the MiniLM Bert model.

```
    [1, 384, 384]
    [128, 384, 384]
    [128, 1536, 384]
    [128, 384, 1536]
```

We can start with benchmarking these GEMM shapes and set up more reasonable tiling sizes for RISC-V targets. There are other vector lowering strategies in Sandbox codegen driver based approach.

https://github.com/google/iree/blob/ae1c3a2d33bc20ac3aef4022dbc9bde7b185ff6c/iree/compiler/Codegen/Sandbox/Passes.td#L122-L175

Another aspect is to profile the model used in riscv CI (i.e., person_detect.tflite). There may be quantized matmul in the model (e.g., i8xi8->i32). I think we can still use the same shapes but with i32,i32->i32 types as a starter.

Once we have good performance for individual matmul ops, we can look into fusion cases (e.g., fill + matmul + generic ops). Fusion cases are the most common cases we'd like to address in IREE.

cc @MaheshRavishankar @hcindyl @dcaballe

**Comment by MaheshRavishankar** [comment]
> I recently found that we don't have good configurations when fixing long compilation time issue for RISC-V targets #8431. In the past, we only had focus on Pixel 4. They were all used Pixel 4 configurations. For the time being, we have different strategies for different targets.
> 
> Now, we use x86 avx configuration, which is not the best for RISC-V targets. IMO, we can target some matmul shapes and set up better tiling sizes. E.g., we've been focusing on Bert matmul sizes for a while. The current configurations are set based on generally good performance for those shapes. The below shapes are what we care in the MiniLM Bert model.
> 
> ```
>     [1, 384, 384]
>     [128, 384, 384]
>     [128, 1536, 384]
>     [128, 384, 1536]
> ```
> 
> We can start with benchmarking these GEMM shapes and set up more reasonable tiling sizes for RISC-V targets. There are other vector lowering strategies in Sandbox codegen driver based approach.
> 
> https://github.com/google/iree/blob/ae1c3a2d33bc20ac3aef4022dbc9bde7b185ff6c/iree/compiler/Codegen/Sandbox/Passes.td#L122-L175
> 
> Another aspect is to profile the model used in riscv CI (i.e., person_detect.tflite). There may be quantized matmul in the model (e.g., i8xi8->i32). I think we can still use the same shapes but with i32,i32->i32 types as a starter.
> 
> Once we have good performance for individual matmul ops, we can look into fusion cases (e.g., fill + matmul + generic ops). Fusion cases are the most common cases we'd like to address in IREE.
> 
> cc @MaheshRavishankar @hcindyl @dcaballe

Thanks Hanhan for bringing this up. Overall I think it makes sense to move in this direction. Though RISC-V eco system might be too diverse to have something nailed down in the compiler itself as general heuristic (I might be wrong).

I'd suggest start using the `iree_codegen.compilation_info` attributes to control the tile sizes etc. At least for prototyping ( + search) that would be an easier starting point.

**Comment by dcaballe** [comment]
https://github.com/iree-org/iree/pull/9870 provides a good baseline for both float and quantized GEMMs.
