### ISSUE TITLE
Fix issues with dialect conversion on linalg/arith/math ops for i64/f64 support.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#8745]
The i64->i32 and f64->f32 demotion passes can cause verification failures in ops that are strict in verifiers but lacking folders. One such example is an `arith.extsi` i32 -> i64 that gets converted to an i32 -> i32:
```
D:\Dev\iree/iree/test/e2e/models/unidirectional_lstm.mlir:62:9: error: 'arith.extsi' op operand type 'i32' and result type 'i32' are cast incompatible
```

In order to support the type promotion/demotion the dialects we are working with need to have sufficient folders for these operations such that we can safely convert the types without tripping the verifier.

Currently only MHLO is properly supported for promotion/demotion as its ops lack verifiers and we can perform conversion successfully. This does not help TOSA/non-TOSA torch/direct-to-linalg/etc though and requires additional MHLO-specific input options instead of more generic compiler options. MHLO must currently default to demotion as otherwise the generic pass in flow cannot work.

To reproduce the above failure disable the MHLO demotion and just use the lower-level flow demotion:
```
iree-opt \
  -iree-mhlo-demote-i64-to-i32=false \
  -iree-flow-demote-i64-to-i32=true \
  -iree-import-public \
  -iree-mhlo-input-transformation-pipeline \
  -iree-abi-transformation-pipeline \
  -iree-flow-transformation-pipeline \
  iree/test/e2e/models/unidirectional_lstm.mlir
```

Part of this issue is scoping out what possible folders are needed upstream, whether we have other cases that come from tosa/etc that we need to support, etc. Ideally when fixed we completely remove the `-iree-mhlo-demote-*` flags and rely on the `-iree-flow-demote-*` flags instead.

**Comment by benvanik** [comment]
Not sure what the best course of action is - hence this issue :(
It feels to me like something high level (higher than LLVM IR by a ways) should be fine with folding away no-ops - like if I wrote (indirectly via macros/inlined functions/etc) `static_cast<int32_t>(static_cast<int32_t>(a))` or something, but I don't have much control over the common dialects and we'll probably have to work around it.

One idea would be to have the demotion/promotion pass insert widening/narrowing ops instead of changing types, though then we'd have to guarantee that they all folded/canonicalized the types we are transitioning from and that feels like it may just be brittle in a different way. Open to suggestions. It's best if the input models used the most narrow types possible and it may just be the nature of this fixup approach that it's going to be brittle, but it'd be nice if it was as non-brittle as possible.

**Comment by jpienaar** [comment]
I don't think this can be handled generally/without knowledge of ops behavior. Consider an op with i64 result and i64 attribute, we can have one of 3 cases:

1. Attribute determines result type, so one has to change the attribute to match;
2. Attribute is independent of result type but required to be i64;
3. Attribute is independent of result type but can be any integer type;

In case 2 & 3 one can simply change return type, case 1 one has to change attribute type too and case 3 you are allowed to change it. Any pass that just changes return types may fail (for any dialect that has a constant op this is likely), any pass that always changes attributes may fail . So one would need to audit the op sets involved (or have trait/interface). Another alternative is to make it very specific (only per-dialect, or only per certain ops in the dialect targeting common behavior). This is slightly akin to shape refinement where one has to insert a case unless one knows the consumers's can be refined too, there one can always slap in casts without changing behavior, here a cast could change numerics and so isn't as much of a NOP.

**Comment by benvanik** [comment]
Agreed! For big changes like this I think this may need to be something that happens in tosa/mhlo/etc instead of something we can do generically when it comes to ABI and such - there's precision adjustment we can do on the lower dialects but in a more canonical way (inserting casts and letting fixed point iteration do stuff for us, like what stella has done with the various numeric optimization passes) but probably not via a big hammer like the current pass.

The equivalent is changing the size of `size_t` in C: for a whole program that really needs to happen in clang vs lower level in LLVM, though LLVM can still widen/narrow types in constrained cases where it knows the ranges and such.
