### ISSUE TITLE
Simplify how optional components are handled in Bazel and CMake

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#8761]
We have a few components that are optional for various reasons, including:

* compiler target backends (e.g. CUDA, Vulkan, Metal, ROCm, WebGPU) that require specific host build platforms or dependencies
* runtime HAL drivers that get registered in `iree_hal_register_all_available_drivers()` and may require specific dependencies
* EmitC output (see https://github.com/google/iree/pull/8593)

We're also considering making more components configurable, such as the torch-mlir integration and experimental parts of iree-dialects/.

The existing mechanisms for controlling which targets are defined and linked in as part of the build system are verbose and can vary from component to component, e.g.:

https://github.com/google/iree/blob/7d486be4a3f31a93014b95a49efa68562c3339b8/iree/compiler/Dialect/HAL/Target/CUDA/CMakeLists.txt#L9-L17

https://github.com/google/iree/blob/879f07684af55ca7948b64cc00db460167fd263c/iree/compiler/Dialect/VM/Target/C/CMakeLists.txt#L11-L24

Goals:

* Easy to understand CMake and Bazel code
* Easy to add new optional components, with a consistent style

Brainstorming:

* Wrap the "if not option, return" code in a macro, add a readable way to map from Bazel to CMake
* For conditional deps that use a `select()` in Bazel, create a helper function that translates from a readable dictionary to the equivalent Bazel `select()` and CMake list
* Registration system with hooks for adding compiler pipelines/passes?

**Comment by ScottTodd** [comment]
Another suggestion from https://github.com/google/iree/pull/8840:

> Not going to block it, but I really dislike having `#ifdef` in files. It is very easy to mess up.... It would be better if this could be refactored into files that either get compiled and linked or not. Might be hard to do in the present state though.

**Comment by ScottTodd** [comment]
I'm skeptical of adding syntactic sugar for
```cmake
if(CONDITION)
  return()
endif()
```
and I don't mind how `iree_cmake_extra_content` is set up.

I think our best chances at simplifying these configurations involve
* using consistent style for defining options in the root CMake file
* limiting the number of directories that branch on options. See this new directory for a good example: https://github.com/google/iree/blob/2814631ea27237908b930e655fc13967b62533ff/runtime/src/iree/hal/drivers/CMakeLists.txt#L112-L120

Remaining options that could use some polishing:
* `IREE_ENABLE_EMITC` -> `IREE_OUTPUT_FORMAT_C`, along with adding `IREE_OUTPUT_FORMAT_VM_BYTECODE`
* `IREE_BUILD_TORCH_MLIR_SUPPORT` -> `IREE_INPUT_DIALECT_TMTENSOR`, along with `IREE_INPUT_DIALECT_MHLO` and `IREE_INPUT_DIALECT_TOSA`

Thoughts?

**Comment by benvanik** [comment]
Agreed - I think most places the if->return is used could be flipped around like you mention. I really like being able to reason about a functioning project even if you `rm` entire directories you don't care about - it also means it's easier to drop in/overlay directories without needing to change a bunch of files.

I think the HAL drivers/ is probably a good model for where we can swing things - thinking specifically things like the compiler `HAL/Targets/` and `VM/Target/` (which should be renamed Targets/... whoops) directories. I'm thinking if we had a matching `IREE_EXTERNAL_HAL_TARGETS` variable (and such) we could even support out-of-tree targets/output formats just like we do for the runtime drivers. It has the benefit of more closely matching llvm's behavior there too, though not everything they do is great.

For things like samples/ we could change to only add-directory'ing manually and make the decisions in there - the `iree_add_all_subdirs` is the problem and we could easily move logic into there.

**Comment by ScottTodd** [comment]
I started to set up options for output formats:
```cmake
cmake_dependent_option(IREE_OUTPUT_FORMAT_BYTECODE "Enables the 'vm-bytecode' output format" ON ${IREE_BUILD_COMPILER} OFF)
cmake_dependent_option(IREE_OUTPUT_FORMAT_C "Enables the 'vm-c' output format, using MLIR EmitC" ON ${IREE_BUILD_COMPILER} OFF)
```

I don't really expect us to turn off the bytecode output format, but it would be nice to have it follow the same style as the C format output.  Unfortunately, ConstEval depends on the bytecode output format, so we'd have to make _that_ optional too, to have any possible configuration with the bytecode output format disabled.

**Comment by benvanik** [comment]
yeah bytecode is probably fine to always require as it's the reference impl - the things external to the project are more likely to be what we want to shut off (if broken/etc)

**Comment by ScottTodd** [comment]
I think this is in a pretty good state now. Our CMake files follow a few common styles and we print a nice message at configure time showing what is included in the build:
```
[cmake] -- IREE HAL drivers:
[cmake] --   - cuda
[cmake] --   - local-sync
[cmake] --   - local-task
[cmake] --   - vulkan
[cmake] -- IREE HAL local executable library loaders:
[cmake] --   - embedded-elf
[cmake] --   - system-library
[cmake] --   - vmvx-module
[cmake] -- IREE compiler input dialects:
[cmake] --   - MHLO
[cmake] --   - Torch MLIR
[cmake] --   - TOSA
[cmake] -- IREE compiler output formats:
[cmake] --   - C source module
[cmake] --   - VM Bytecode
[cmake] --   - VM MLIR Assembly
```
