### ISSUE TITLE
Inconsistent documentation for how to generate python packages

### ISSUE THREAD

**Issue by dan-garvey** [iree-org/iree#8766]
https://google.github.io/iree/building-from-source/python-bindings-and-importers/

https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_python.md

https://github.com/google/iree/tree/main/bindings/python

Each of the above offers ultimately different instructions on how to build and use the python bindings. The only one that is functionally correct is the first, assuming you need the iree.compiler bindings. I was able to generate a pip package/wheel/PYTHONPATH location with the other instructions, but not compiler. 

Happy to fix this myself but figured it may warrant a broader discussion on how to enable doc consistency, since maintaining three sets of instructions on how to build the python packages seems like a way to guarantee this happens again

<3

**Comment by stellaraccident** [comment]
When I do a clean build I search for "iree build from source" and follow the instructions (I'm weird: I wrote this stuff but typically follow docs versus use scripts), so I think I'm using the first link.

We should probably delete the second. For the third, we should delete instructions and details (maybe leave the readme to describe what is here but link to docs for how to build).

**Comment by ScottTodd** [comment]
https://github.com/google/iree/tree/main/docs/developers/get_started was a simple fork of older docs which https://github.com/google/iree/tree/main/docs/website/docs/building-from-source (the source for your first link) was created to replace. Pages like https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_linux_bazel.md are still occasionally useful (those pages can include more details that wouldn't make the cut for appearing on the website), but in general that folder has rotted over time.

**Comment by ScottTodd** [comment]
I think this is fixed now (still could use some refinement, but no more duplicated / inconsistent steps?)
