### ISSUE TITLE
Upgrade TF importer using fully upstreamed mechanisms to use ml_program

### ISSUE THREAD

**Issue by jpienaar** [iree-org/iree#8832]

**Comment by jpienaar** [comment]
Sorry clicked button by accident

**Comment by powderluv** [comment]
this is the only way we get functional Training graphs right now. torch-mlir is WIP and has OOM issues on IREE. JAX was still in flux for training graphs. No special love for this path but maybe worth keeping the lights on until we have one other framework that can reliably get training graphs for IREE to run.

**Comment by stellaraccident** [comment]
I think Jacques is going to look into using some pure upstream mechanism for this that doesn't need to involve iree. In any case, actually removing any functionality here is months away and depends on getting an alternative path and test suite brought up.

**Comment by jpienaar** [comment]
Indeed, I fat fingered creating this task while on mobile and before we could discuss it in the other thread. Let me rename.

**Comment by rsuderman** [comment]
In order to migrate TensorFlow importer MLProgram will need indirect read/store operatoins.

**Comment by jpienaar** [comment]
Good point, we can handle the case where there is only one VarHandle for now (I have a change to flip the pass to data flow). But you are correct it won't be complete. Do you know if we really use indirect for any of the models today vs it is really fixed once we've done the data flow analysis?

**Comment by benvanik** [comment]
We don't have indirect variables plumbed all the way through so today they must all be canonicalizing/folding into direct references before we hit the flow/stream layer in any model we can run. I think most of this happens in the util dialect - so we do support them at the input boundary at the least.

**Comment by jpienaar** [comment]
Cool, I'll update to version needed post data flow analysis pass deletion and can test.

**Comment by rsuderman** [comment]
Closing as the attached PR addressed this issue.
