### ISSUE TITLE
Shutdown deadlock in `iree_task_worker_deinitialize` -> `iree_notification_await` as the thread is already gone

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#8871]
This reproduces every ~1000 runs of `dylib` unit tests:
```
ctest -j20 -R iree/hal/dylib/cts/dylib --repeat-until-fail 1000 --output-on-failure
```

The test just hangs. Attaching GDB to it, I get [this stack](https://gist.github.com/bjacob/04bf9cd81f4ddf7786f4c0af0de3141c). According to GDB there is no other thread anymore (other than a TSan-internal thread) --- this is a single-threaded program at this point.

So `iree_task_worker_deinitialize` is awating a notification,

```
  if (worker->thread) {
    iree_notification_await(&worker->state_notification,
                            (iree_condition_fn_t)iree_task_worker_is_zombie,
                            worker, iree_infinite_timeout());
  }
```

but it will never come as there is no other thread left to send it.

**Comment by bjacob** [comment]
Note: the worker is already in zombie state. We just missed the notification.
```
(gdb) p worker->state
$3 = 3
```

**Comment by bjacob** [comment]
The `await` looks fine it itself, but in the surrounding code in `iree_task_worker_deinitialize`, something is missing to prevent the thread from exiting before we reach the `await`. See https://github.com/google/iree/pull/8872#issuecomment-1098230288

**Comment by benvanik** [comment]
(in other words - it's expected that calling in to await on a condition that is true is fine - so there's no harm if the worker exits before we await)

**Comment by bjacob** [comment]
I still don't see anything preventing this ordering of events:

1. The main thread reads the worker state  ([link](https://github.com/google/iree/blob/519815e4bcd51cf690ede07338d73d99241465b7/iree/base/internal/synchronization.c#L683), evaluating the `condition_fn` here that is `iree_task_worker_is_zombie`). That returns false, so the main thread will enter the wait.
2. The worker thread changes to zombie state [link](https://github.com/google/iree/blob/519815e4bcd51cf690ede07338d73d99241465b7/iree/task/worker.c#L376).
3. The worker thread posts the notification [link](https://github.com/google/iree/blob/519815e4bcd51cf690ede07338d73d99241465b7/iree/task/worker.c#L378)
4. The main thread enters the wait, as previously decided at step 1. It already missed the notification from step 3.

**Comment by benvanik** [comment]
yes, that's what I'm saying: that is _not_ the behavior of the futex implementation, but may be the behavior of the pthread implementation. It should be fixed.

**Comment by bjacob** [comment]
Sorry, I'm confused. In the previous comments, steps 2 and 3 link to `iree_notification_await`. I thought that was still in the code that's shared between futex / pthread implementations - the divergence seems to happen in `iree_notification_commit_wait`, which it does call.

**Comment by bjacob** [comment]
My concern (https://github.com/google/iree/issues/8871#issuecomment-1098276882) is what if the condition is **concurrently** made satisfied while `iree_notification_await` is running - so that the atomic store of worker state and the notification post (steps 2 and 3 above) both occur after `iree_notification_await` performed the atomic read of worker state (step 1) and before it committed the wait ?

**Comment by benvanik** [comment]
that's fine - that's precisely what iree_notification_t is meant for, see:
https://github.com/facebook/folly/blob/main/folly/experimental/EventCount.h#L34
https://github.com/concurrencykit/ck/blob/master/include/ck_ec.h#L31

the key being that it acquires a wait token, performs the check, and then commits the wait only if the wait token hasn't changed - if anything else comes in the wait token won't match and it'll abort the wait

https://github.com/concurrencykit/ck/blob/4463b74de4dd6314b9d90e18178e01fa57013fd7/include/ck_ec.h#L51-L64
->
```
*  1. On the producer side:
 *
 *    - Make changes to some shared data structure, without involving
 *	the event count at all.
 *    - After each change, call ck_ec_inc on the event count. The call
 *	acts as a write-write barrier, and wakes up any consumer blocked
 *	on the event count (waiting for new changes).
```
is our:
```c
  iree_atomic_store_int32(&worker->state, IREE_TASK_WORKER_STATE_ZOMBIE,
                          iree_memory_order_seq_cst);
  iree_notification_post(&worker->state_notification, IREE_ALL_WAITERS);
```

and 
```
 *  2. On the consumer side:
 *
 *    - Snapshot ck_ec_value of the event count. The call acts as a
 *	read barrier.
 *    - Read and process the shared data structure.
 *    - Wait for new changes by calling ck_ec_wait with the snapshot value.
```
is our:
```c
  while (true) {
    iree_wait_token_t wait_token = iree_notification_prepare_wait(notification);
    if (condition_fn(condition_arg)) {
      // Condition is now met; no need to wait on the futex.
      iree_notification_cancel_wait(notification);
      return true;
    } else {
      if (!iree_notification_commit_wait(notification, wait_token,
                                         deadline_ns)) {
        // Wait hit the deadline before we hit the condition.
        return false;
      }
    }
  }
```

**Comment by bjacob** [comment]
oooh i get it now! I'll fix the pthreads path. thanks for the explanation!

**Comment by benvanik** [comment]
I can take a whack at it too unless you'd like to get your hands dirty with it - I'm super appreciative of you finding these issues and don't mean to force the fixes onto you too :)

**Comment by bjacob** [comment]
I was taking a look --- how does this look? https://github.com/google/iree/pull/8876

**Comment by benvanik** [comment]
If that fixes the issue then that's awesome! I may rejigger the code to make it easier to follow (less mixing of atomics and mutex stuff) and that'd be a more confident NFC if you do this first :)

**Comment by bjacob** [comment]
it is looking ok in a ctest run with 1000 repeats and it certainly matches my understanding, now that i understand the above explanation, that it fixes a specific issue in the existing code (as explained in the comment added by that pr).

**Comment by bjacob** [comment]
wait, no indeed it was written hastily and incorrect. i am missing a really good way to test this code ---- i'll have to compensate with lots of care.

**Comment by benvanik** [comment]
Does this help make things easier to read? It has your fix for locking but may not work for the same reason you found:
https://github.com/google/iree/commit/d9521a7715adf37cca20989fb017aabc3765f4cd

**Comment by bjacob** [comment]
After all my #8876 was correct, my above comment https://github.com/google/iree/issues/8871#issuecomment-1098380562 was incorrect in calling it incorrect, and your https://github.com/google/iree/commit/d9521a7715adf37cca20989fb017aabc3765f4cd is correct too for the same reason, and yes it is clearer - i was also thinking while reading this code that it would help to decouple the different implementations in this way.

**Comment by benvanik** [comment]
cool - sent https://github.com/google/iree/pull/8877 - will see what the bots say!

**Comment by benvanik** [comment]
I believe we've quashed this now. Or, at least this specific one :P
