### ISSUE TITLE
Missing support for vectorizing quantized convolution ops

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#8905]
Follow up from https://github.com/google/iree/issues/8411, the quantized convolution ops are not vectorized. This introduces temp buffer allocation because types mismatch. We landed https://github.com/google/iree/pull/8526 to work it around. Ideally, we'd like to vectorize those operations as well.

We have a flow to vectorize convolution ops today, the missing part is -- adding a pattern to convert the quantized version into a normal version [like for matmul](https://github.com/google/iree/pull/8409) (or maybe extend the vectorization logic to directly account for the zero points if necessary).

It does not block quantized model exploration. We can prioritize this issue once quantized convolution-base models are in our tracking list. Just filing an issue for tracking it.

**Comment by pzread** [comment]
Unassigned myself as I don't have time recently to work on this P1 issue

**Comment by dcaballe** [comment]
Please, @vmurali coordinate with @rsuderman
