### ISSUE TITLE
unused-but-set-variable warning in emitc generated code

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#8954]
Not sure why this just started triggering, but emitc is generating code like:

```
uint8_t foo = 1;
```

with no references.

Would be better if it generated `(void)foo;` but the emitter isn't well structured to do that, so I am just adding a warning supression to the cc_binary (see static_library/CMakeLists.txt).

**Comment by simon-camp** [comment]
#8991 will prevent dead code from being emitted in some cases I found. But I wasn't able to reproduce the warnings locally, so I don't know if I missed something.

**Comment by marbre** [comment]
Is this fixed with #8991 merged?

**Comment by ScottTodd** [comment]
Possibly fixed? Closing for now.
