### ISSUE TITLE
Add CUDA dependency fetch to cmake.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#8971]
To get back to a state where we have CUDA enabled by default we can use the same technique the CI is using to fetch the CUDA deps directly and make cmake do that using its `file(DOWNLOAD)` command. This would avoid the need for 95% of users to touch CUDA deps at all, and for those with more customized setups (the CI which we want to use the copy in the docker image or people using their own locally installed toolkits) we can skip it.

We do similar cmake-time fetches of some dependencies such as spirv-tools/tint already:
https://github.com/google/iree/blob/main/build_tools/third_party/tint/CMakeLists.txt#L9

This is the CI script doing the downloading:
https://github.com/google/iree/blob/main/build_tools/docker/base/fetch_cuda_deps.sh

The issue there is that it's assuming bash/linux/etc; if we used the native cmake utils (`file(ARCHIVE_EXTRACT)`) we could avoid this so that it works on all platforms uniformly. Something like

`build_tools/third_party/cuda/CMakeLists.txt`:
```
# if cuda is not enabled in IREE then don't bother
if(NOT IREE_ENABLE_CUDA ...) return()

# allow CI/users to specify things explicitly
if(IREE_CUDA_DEPS_FLAG_THING) return()

# try to use the user's local install, if they have one
FindCUDAToolkit(...)
if(CUDAToolkit_FOUND) return()

# otherwise fetch each component
file(DOWNLOAD parse_redist.py)
add_custom_command(... "${PYTHON_EXECUTABLE} parse_redist.py ... cuda_nvcc")
add_custom_command(... "${PYTHON_EXECUTABLE} parse_redist.py ... cuda_cudart")
# and move the files we use to the build dir (or just leave them all there)
```

**Comment by stellaraccident** [comment]
I think this is now done and functioning as intended (see `build_tools/third_party/cuda`). On CMake, the necessary SDK parts are auto-downloaded, and on Bazel, flags/env vars are available to build against an SDK.
