### ISSUE TITLE
Refactor Bazel/CMake target names upstream so more can automatically line up

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#9031]
We have a list of mappings from Bazel target names to CMake target names in https://github.com/google/iree/blob/main/build_tools/bazel_to_cmake/bazel_to_cmake_targets.py. 

Where we can, we use automated rules like this to convert: https://github.com/google/iree/blob/5d4d17bc24456375a0f921faefe41a57ad1cdf87/build_tools/bazel_to_cmake/bazel_to_cmake_targets.py#L178-L183

However, a number of targets have names following different conventions in either Bazel or CMake, like these: https://github.com/google/iree/blob/5d4d17bc24456375a0f921faefe41a57ad1cdf87/build_tools/bazel_to_cmake/bazel_to_cmake_targets.py#L72-L78

If those were patched upstream to line up better, we could include less special cases in that python file and the CMake and Bazel files in our project (and other projects using MLIR) would be easier to understand.

**Comment by hanhanW** [comment]
This would be very nice for integrators. Sometimes there are errors in bazel build or new targets in BUILD. In any case, integrators have to understand the script implementation and fix it.

**Comment by stellaraccident** [comment]
+1 (but whoever does this, don't lose yourself -- the upstream bazel build files have a lot of sadness in them -- I've pulled myself back from a rage coding loop multiple times)

**Comment by Mogball** [comment]
@ScottTodd assign this to me please :)

**Comment by Mogball** [comment]
Some of the mappings are erroneous, e.g. `:DialectUtils` should be mapping to `MLIRDialectUtils`, not `""`. I've changed some of the bazel target names to be more consistent in https://reviews.llvm.org/D127459 but haven't changed CMake target names yet. In particular, I wonder what to do with the `*Dialect` suffix of bazel targets vs no suffix for CMake targets. 

Drop the suffix in bazel or add it in CMake? (Probably the latter).

**Comment by jpienaar** [comment]
Personally I'd add the the dialect in cmake/keep it in bazel. I'm guilty of some of those but I think this is more consistent (I have an internal change where I wrote a bzl megarule for the common case which would be funny to see if my opinion today matches my opinion when I wrote that couple of months ago before I got "distracted").

**Comment by Mogball** [comment]
I've made all the dialect targets line up: `MLIR*Dialect` in CMake. There are a few stragglers but I hope this is good enough for now.

**Comment by hanhanW** [comment]
Nice work! We're able to remove 7 rules with the change.

For more details, see https://github.com/google/iree/pull/9489/files#diff-91b6cbda515b254ffd03bacc6f16c7dd99f76e3a4b8828aa142dddcde7c45f92

**Comment by jpienaar** [comment]
And I think that was before https://github.com/llvm/llvm-project/commit/e16d13322b2617843511aebb29a502166824b07a , so the next round should have even less rules there.

**Comment by ScottTodd** [comment]
Mismatches between Bazel and CMake target names haven't seemed to cause issues for a while. Let's close this.
