### ISSUE TITLE
Document using Python with Asan

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#9067]
I think that general `*san` incantations should go in some kind of a debugging guide. In the absence of that, jotting down the one liner here for running Python scripts with asan (to be used when IREE is built with ASAN enabled):

```
alias asan_python="LD_PRELOAD=$(clang -print-file-name=libclang_rt.asan-x86_64.so) ASAN_OPTIONS=detect_leaks=0 python"
```

**Comment by stellaraccident** [comment]
(used for debugging #9033)

**Comment by stellaraccident** [comment]
Also should add `ASAN_OPTIONS=detect_leaks=0` because the Python interpreter leaks on exit.

**Comment by ScottTodd** [comment]
I think we can close this. We have some docs on Python + ASan here: https://iree.dev/developers/debugging/sanitizers/#linking-to-the-dynamic-asan-runtime
