### ISSUE TITLE
Need better vectorization for element-wise operation codegen

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#9093]
I think this is an issue we'd like to address at some point. There might be tiny dispatches (maybe because of bad tiling sizes?).

Without Tracy, I got 32 ms. With Tracy, I got 54 ms. Filing an issue for tracking it.

**Comment by hanhanW** [comment]
ah cool, seeing this. Flow level tiling sizes definitely go wrong. Some tiny dispatches are called 66k times.

![image](https://user-images.githubusercontent.com/6949191/167799145-4e23eab5-8fcd-4cf4-ac03-70136667218e.png)

**Comment by hanhanW** [comment]
dispatch_78 contains a single element-wise operation. Unfortunately, the sizes are prime numbers. We'd like to vectorize all the operations. They must be set to 1 if padding option is not available.

I'll work on a PR to properly pad and vectorize this kind of kernel.

```
%2 = linalg.generic {indexing_maps = [#map1], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} outs(%1 : tensor<1x257x257x21xf32>)
```

**Comment by MaheshRavishankar** [comment]
I think the decision is not to pad these right? Rather to use peeling when it is ready to use.

**Comment by hanhanW** [comment]
Yes, that's right. Let me update the title of the issue.

**Comment by hanhanW** [comment]
closing, this is a dup of https://github.com/iree-org/iree/issues/9660
