### ISSUE TITLE
Embed operation types in the dispatch name

### ISSUE THREAD

**Issue by okkwon** [iree-org/iree#9132]
Currently, the dispatch name is like "<model_name>_dispatch_<number", so it is difficult to see what the dispatch is doing. By embedding operation types in the name, we can easily see what's going on in the dispatch without looking into the dispatch code.

The feature may be enabled with a compiler option or for the non-release builds.

**Comment by ScottTodd** [comment]
Related to https://github.com/google/iree/issues/7211

**Comment by ScottTodd** [comment]
Closing this issue as a duplicate (seems pretty similar to the other issue linked above).
