### ISSUE TITLE
Properly translating non-library deps from iree_compiler_cc_library to CMake's iree_cc_library

### ISSUE THREAD

**Issue by pzread** [iree-org/iree#9146]
Currently we translate all `DEPS` from the bazel rule into `DEPENDS` of CMake's `iree_cc_library` rule. This causes the problem as DEPS can contain non-library deps from LLVM (non-linkable) and `DEPENDS` only accepts linkable libraries.

An example is in LLVM CMake we define tablegen files by `add_custom_target`. While it's okay to add those targets to `DEPS` in bazel, when we translate from bazel to CMake, those targets are added as `DEPENDS` and fail the build (CMake can't link those targets).

One solution is on the bazel side, we add another parameter to `iree_compiler_cc_library` for non-library deps. When translating to CMake, those special deps will be added to a new parameter of the CMake's `iree_cc_library` rule. `iree_cc_library` then can add those deps by `add_dependencies` instead of `target_link_libraries` so CMake won't try to link non-linkable targets.

**Comment by ScottTodd** [comment]
Oh, I had another idea: maybe we can check the type of dep (library vs custom target) in the CMake `iree_cc_library()` implementation, such as around here: https://github.com/google/iree/blob/ae05f3094f948cf310357da81ce6ac015e54bc56/build_tools/cmake/iree_cc_library.cmake#L218-L222

The type of dep would no longer be explicit, and that CMake function would get more complicated, but it would keep our BUILD and CMakeLists files simpler.

**Comment by stellaraccident** [comment]
That would make the cmake files order dependent, which would be not great.

It may be possible with some defer logic and/or generator expressions. But that would also be not great, imo

**Comment by ScottTodd** [comment]
Unless there is a specific build configuration or target that needs this sort of refactoring, I think we can close this as obsolete.
