### ISSUE TITLE
CUDA backend fails to compile miniLM when a transpose is fused

### ISSUE THREAD

**Issue by okkwon** [iree-org/iree#9240]
The work done in https://github.com/google/iree/pull/9103 enables a fusion of linalg with a generic op with a transpose. But when it is enabled, the cuda backend fails to compile.

How to reproduce:

1. Checkout https://github.com/nod-ai/transformer-benchmarks
2. Change `run_benchmark.sh` and modify it to run CUDA and IREE.
3. Change `run_iree()` in `benchmark.py` to add the following options.
`--iree-flow-normalize-input-indexing-map --iree-flow-fuse-transpose`
4. run `run_benchmark.sh`

This is the error message from Nod.
[fusion_error.txt](https://github.com/google/iree/files/8789606/fusion_error.txt)

**Comment by okkwon** [comment]
@ThomasRaoux can you take a look?

**Comment by okkwon** [comment]
This reduces the number of dispatches for miniLM from 271 to 247, so we expect performance improvement from the optimization.

**Comment by antiagainst** [comment]
Closing as obsolete--no actions planned for now
