### ISSUE TITLE
miniLM-Torch fails to run Vulkan due to failure in signless i64 casting to i32

### ISSUE THREAD

**Issue by raikonenfnu** [iree-org/iree#9245]
miniLM-Torch fails to run on Vulkan backend. 
It breaks during benchmark-module due to an assertion of value throwing out:

```bash
iree-build-latest/tools/iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-llvm-embedded-linker-path=/iree-build-latest/install/bin/lld --iree-mlir-to-vm-bytecode-module --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvm-target-cpu-features=host -iree-vulkan-target-triple=m1-moltenvk-macos --iree-flow-demote-i64-to-i32  -iree-flow-demote-f64-to-f32 --iree-vulkan-target-triple=ampere-rtx3080-linux --mlir-print-ir-after-all --mlir-print-ir-after-change -mlir-elide-elementsattrs-if-larger=4 minilm_torch.mlir -o /tmp/minilm_torch.vmfb 2> /tmp/minilm_pass.mlir

iree-benchmark-module --driver=vulkan --entry_function=forward --function_input=1x128xi64 --module_file=/tmp/minilm_torch.vmfb
I iree/runtime/src/iree/tools/utils/vm_util.cc:154] Creating driver and device for 'vulkan'...
2022-05-27T22:50:02+00:00
Running /nodclouddata/iree-build-host/tools/iree-benchmark-module
Run on (12 X 2200.15 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x6)
  L1 Instruction 32 KiB (x6)
  L2 Unified 1024 KiB (x6)
  L3 Unified 39424 KiB (x1)
Load Average: 1.20, 0.84, 0.38
<vm>:0: FAILED_PRECONDITION; mismatched size for broadcast;
[ 0] bytecode module.forward:3798 /home/minilm_torch.mlir:512:12
      at /home/minilm_torch.mlir:23:3
[1]    6864 abort (core dumped)
```

**For additional context:**
-[IR source](https://storage.googleapis.com/iree-shared-files/nod-perf/stanley/minilm_repro_vulkan/core-input.mlir)
-This bug also happens in cuda backend if I add the --iree-flow-demote-i64-to-i32 pass. (passes otherwise)
-This error do not happen if I do not add the --iree-flow-demote-i64-to-i32  on vulkan backend.(It does run and show gpu utility, but it throws off other Vulkan Validation Errors at the very start of the benchmark-module call).

**Hypothesis**
This leads me to believe that the error happens due to the pass, and specifically due to the casting failure for signless. Here is a sample of before and after the demotion.
Before:
<img width="605" alt="Screen Shot 2022-05-27 at 5 02 54 PM" src="https://user-images.githubusercontent.com/68087699/170814484-fd0c5a20-9512-4d99-8dd0-a19cf3d822ea.png">

After:
<img width="810" alt="Screen Shot 2022-05-27 at 5 02 38 PM" src="https://user-images.githubusercontent.com/68087699/170814487-0c9c22e0-d345-43b2-9215-4d99b5ccd91b.png">

It seems like that the problem is the demotion pass only looks at the Source Type(i64-signless) and Target Type (i32-signless). Hence it does not know how to cast the maximum value of int64 into int32(can be 2.1billion for signed and 4.2 billion for unsigned).

**Potential Solution**
I am thinking we should add op-aware casting to the demotion/promotion. a.k.a Pass should check if the parent op is a signed or unsigned Op and cast appropriately. If Op has not specified signedness, then cast default like how it is done right now.
Any suggestions on how to add this or other ideas to fix this is very welcomed! :)

**Comment by raikonenfnu** [comment]
**EDIT:**
-Started writing a pattern to add into `ConvertTypesPass` that target typeSenstivie cmpiOp. However, did find another pattern that we might need to add. 

<img width="481" alt="Screen Shot 2022-05-29 at 12 36 29 AM" src="https://user-images.githubusercontent.com/68087699/170857481-5cee20a5-d314-424c-865c-4040a1f3af28.png">

**Comment by raikonenfnu** [comment]
I was able to fix these issues with a pass that checks if an op is signed, if it is I will pre-demote it to the appropriate value while keeping the type to the sourceType. Then feed this into the demotion pass. Please let me know if this is the right place and way to fix? :)

https://github.com/raikonenfnu/iree/commit/22e21da996c61a36eb99b2b968c633128d2ae113

**Comment by antiagainst** [comment]
Great findings! Yes it's the operation itself decides the signedness interpretation of its operands---i32/i64 is just a bag of 32/64 bits. We need to be aware of this to decide how to demote them. Though instead of creating a new pass, I think we can directly enhance the current ConvertPrimitiveType pass to account for such cases. We have existing patterns to convert [`ConvertTypeSensitiveArithCastOp`](https://github.com/google/iree/blob/main/compiler/src/iree/compiler/Dialect/Util/Transforms/ConvertPrimitiveType.cpp#L219-L233), I think you can add something similar there by defining a template class and iterate over all constant operands and convert them.

**Comment by raikonenfnu** [comment]
Hey @antiagainst thanks for the input! I did have that in previous iteration and added the pattern to ConvertTypePass, but for some reason if I put the pattern there, the inputs that it receive would’ve been already demoted. I tried adding the new pattern at the very start and also tried putting the insert pattern as the very last pattern, but same issue persist. Any guidance on this would be appreciated :)

**Comment by antiagainst** [comment]
Yeah that's expected given this is using dialect conversion which involves type conversion. For such cases, ops convert from the top to the bottom---defining ops are converted before user ops. With the current implementation, we have the constant op already converted when looking at its user op. Though you are not forced to use the converted/demoted constant op (coming from `OpAdaptor`), you can entirely create new constant ops by looking at the original operand and demote that separately. Let me know if this makes sense.

**Comment by raikonenfnu** [comment]
I see, so we can create new constant op from the original operand and use that for the op instead(I think this is similar to how the patch I have is doing it). Would you happen to know how to obtain the original operand Value using the rewriter/OpConversion pattern within ConversionTypePass.

**Comment by raikonenfnu** [comment]
@antiagainst I have a new design for the patch that is a bit more conservative (i.e only target CmpIOp and SelectOp) and is part of ConvertPassType. Let me know what you think :)
https://github.com/google/iree/compare/main...raikonenfnu:UpDemote

**Comment by powderluv** [comment]
Is the recommendation here to make sure the we can map to i64 on the M1 and not worry about the demote ?

**Comment by antiagainst** [comment]
@powderluv: I think we should pursue all of these solutions (as Vulkan is really about supporting hardwares with different capabilities). 1) I've landed necessary fixes to make the model compile if i64 is natively supported. That should help M1. 2) I'll later add i64 emulation via i32. That should help all Vulkan targets not natively supporting i64. 3) @raikonenfnu's fix is good to have given I think it's a bugfix to the demotion passes. Keep all possibilities open and see which one gives you want you want. ;-P

**Comment by powderluv** [comment]
sounds good. I agree it is good to have this and also fix whatever needs fixing further upstream

**Comment by antiagainst** [comment]
closing as obsolete -- no actions planned now
