### ISSUE TITLE
Define targets in iree_bytecode_module

### ISSUE THREAD

**Issue by pzread** [iree-org/iree#9254]
Currently [`iree_bytecode_module`](https://github.com/google/iree/blob/fe7c4caddc5800a24fca73f495de7acb9e07e0db/build_tools/cmake/iree_bytecode_module.cmake#L36) doesn't define the targets for generating module (vmfb). Therefore whenever calling it to build the modules, we need to define the target by ourselves. For example:
https://github.com/google/iree/blob/fe7c4caddc5800a24fca73f495de7acb9e07e0db/build_tools/cmake/iree_benchmark_suite.cmake#L229-L234

It will be cleaner if we can define the proper targets for generating modules in `iree_bytecode_module`, similar to what it has done for C files:
 https://github.com/google/iree/blob/fe7c4caddc5800a24fca73f495de7acb9e07e0db/build_tools/cmake/iree_bytecode_module.cmake#L123-L128

**Comment by GMNGeoffrey** [comment]
I think there's an existing issue about iree_bytecode_module being bad

**Comment by bjacob** [comment]
when fixing this, please check existing call sites of `iree_bytecode_modules`. In my memory, at least two of them will be able to get simplified as they are currently defining the custom target themselves to make up for `iree_bytecode_module` not doing it.

**Comment by bjacob** [comment]
Thanks!!!
