### ISSUE TITLE
Support float16 NumPy outputs

### ISSUE THREAD

**Issue by hawkinsp** [iree-org/iree#9290]
Currently we get `ValueError: Unsupported VM Buffer -> numpy dtype mapping` for a float16 output.

**Comment by stellaraccident** [comment]
Thanks for the report. What type do you return in Jax for this? We can just match that (I don't think numpy has an f16 type?)

**Comment by benvanik** [comment]
looks like numpy.float16 'e'

**Comment by stellaraccident** [comment]
Thanks. My eyes must have blurred trying to correlate type tables with weird one char codes.
