### ISSUE TITLE
CUDA HAL needs to manage the active context.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#9301]
Though we create a CUcontext we don't set it properly and have inconsistent usage.
We need to be sure we are not invalidating global state by changing the context out from under hosting applications and also need to be sure we are setting our context whenever we are making CUDA calls that require it.

We allocate the context here:
https://github.com/google/iree/blob/16486e2d7c32bdaadf73bb940500d4356a51ebbb/runtime/src/iree/hal/cuda/cuda_device.c#L145
but do not use cuCtxPopCurrent before returning to the caller. If the calling application is using their own context this will break things, as well as leaving the stack unbalanced.

On the primary entry points into the CUDA HAL we need to put a cuCtxPushCurrent/cuCtxPopCurrent, such as around iree_hal_cuda_device_queue_submit and the allocator functions. The CUDA documentation will need to be checked to see which calls actually use the context but to be safe we could do it around any call tree that can reach a CUDA driver API call.

Wrapping around submit above should handle most of our uses at a coarse level (graph/deferred command buffer issuing), but in the case of inline execution we'll need to use persistent thread state. We can add a check to perform the push in iree_hal_cuda_stream_command_buffer_begin and pop in iree_hal_cuda_stream_command_buffer_end if the command buffer mode has the IREE_HAL_COMMAND_BUFFER_MODE_ALLOW_INLINE_EXECUTION bit set. There may be exceptional cases here where that can break (early-exiting midway through inline execution) but behavior isn't well-defined in those cases anyway.

* [ ] Pop context on creation to ensure a balanced stack
* [ ] Push/pop around HAL entry points (submit, etc)
* [ ] Push/pop around stream command buffer in inline execution mode
(+ probably others)

**Comment by powderluv** [comment]
we are using this patch locally in SHARK https://github.com/iree-org/iree/commit/49c983cf21ea633b161e423a0c2c27c0a0816847

**Comment by alliemartens** [comment]
@ThomasRaoux Hey Thomas, any updates here?

**Comment by FudanEMWLab** [comment]
Any update here? I hit similar issue when running iree-jax flow. 
```
import jax
import iree.compiler
import iree.runtime
import numpy as np

config = iree.runtime.system_api.Config("cuda")

x = np.array(7, dtype=np.int32)
y = np.array(8, dtype=np.int32)
def my_func(a, b):
    return a+b

xla_comp = jax.xla_computation(my_func)(x, y)
hlo_proto = xla_comp.as_serialized_hlo_module_proto()
bin = iree.compiler.tools.xla.compile_str(hlo_proto, target_backends=("cuda",), input_type="xla")
vm_module = iree.runtime.VmModule.from_flatbuffer(bin)
module = iree.runtime.load_vm_module(vm_module, config)
print(np.asarray(module["main"](x, y)))
```

**Comment by ThomasRaoux** [comment]
Sent a PR to fix the problem:
https://github.com/iree-org/iree/pull/9909
@powderluv can someone on Nod's side confirm that it solves your problem since I don't have a repo?
@FudanEMWLab could you also verify the fix on your side?

**Comment by FudanEMWLab** [comment]
@ThomasRaoux , ran my above python program with your PR but hit the same error.

**Comment by ThomasRaoux** [comment]
> @ThomasRaoux , rebuilt iree with your PR and ran my above python program, but hit the same error.

Could you give a bit more detail on what the error is? 
I’ll also try to reproduce on my side.

**Comment by ThomasRaoux** [comment]
> > > @ThomasRaoux , rebuilt iree with your PR and ran my above python program, but hit the same error.
> > 
> > 
> > Could you give a bit more detail on what the error is? I’ll also try to reproduce on my side.
> 
> ```
> (venv_local_iree_build) [jax_iree_experiment] > python notebook/test_cuda_as_iree_backend.py
> [debug]: iree_hal_cuda_device_create()
> [debug]:[iree/runtime/src/iree/hal/drivers/cuda/cuda_device.c]: cuCtxSetCurrent(context pointer: 0x0x32d0250)
> [debug]: iree_hal_cuda_device_destroy()
> [debug]: iree_hal_cuda_device_create()
> [debug]:[iree/runtime/src/iree/hal/drivers/cuda/cuda_device.c]: cuCtxSetCurrent(context pointer: 0x0x32d0250)
> [debug]:[/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/compiler/tools/xla.py][204]: ['/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile', '-', '--iree-input-type=xla', '--iree-vm-bytecode-module-output-format=flatbuffer-binary', '--iree-hal-target-backends=cuda', '--iree-llvm-embedded-linker-path=/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld', '--mlir-print-debuginfo', '--mlir-print-op-on-diagnostic=false']
> [debug]:[iree/runtime/src/iree/hal/drivers/cuda/stream_command_buffer.c]: (context pointer: 0x0x32d0250) before calling cuLaunchKernel
> Traceback (most recent call last):
>   File "/jax_iree_experiment/notebook/test_cuda_as_ireejax_backend.py", line 19, in <module>
>     print(np.asarray(module["main"](x, y)))
>   File "/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/runtime/function.py", line 129, in __call__
>     self._invoke(arg_list, ret_list)
>   File "/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/runtime/function.py", line 153, in _invoke
>     self._vm_context.invoke(self._vm_function, arg_list, ret_list)
> RuntimeError: Error invoking function: iree/runtime/src/iree/hal/drivers/cuda/stream_command_buffer.c:378: INTERNAL; CUDA driver error 'CUDA_ERROR_INVALID_HANDLE' (400): invalid resource handle; cuLaunchKernel; while invoking native function hal.ex.submit_and_wait; while calling import;
> [ 1]   native hal.ex.submit_and_wait:0 -
> [ 0] bytecode xla_computation_my_func_0.main:458 [unknown]
> [debug]: iree_hal_cuda_device_destroy()
> ```

Thanks for sharing, I wonder if the problem is really related to the context as it seems like we have the right context bound when doing the dispatch. Also I don’t see why another context would be created but I’m not an expert of jax. 
I’ll have to try to reproduce to understand what is going on here.

**Comment by FudanEMWLab** [comment]
> > > > @ThomasRaoux , rebuilt iree with your PR and ran my above python program, but hit the same error.
> > > 
> > > 
> > > Could you give a bit more detail on what the error is? I’ll also try to reproduce on my side.
> > 
> > 
> > ```
> > (venv_local_iree_build) [jax_iree_experiment] > python notebook/test_cuda_as_iree_backend.py
> > [debug]: iree_hal_cuda_device_create()
> > [debug]:[iree/runtime/src/iree/hal/drivers/cuda/cuda_device.c]: cuCtxSetCurrent(context pointer: 0x0x32d0250)
> > [debug]: iree_hal_cuda_device_destroy()
> > [debug]: iree_hal_cuda_device_create()
> > [debug]:[iree/runtime/src/iree/hal/drivers/cuda/cuda_device.c]: cuCtxSetCurrent(context pointer: 0x0x32d0250)
> > [debug]:[/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/compiler/tools/xla.py][204]: ['/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile', '-', '--iree-input-type=xla', '--iree-vm-bytecode-module-output-format=flatbuffer-binary', '--iree-hal-target-backends=cuda', '--iree-llvm-embedded-linker-path=/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld', '--mlir-print-debuginfo', '--mlir-print-op-on-diagnostic=false']
> > [debug]:[iree/runtime/src/iree/hal/drivers/cuda/stream_command_buffer.c]: (context pointer: 0x0x32d0250) before calling cuLaunchKernel
> > Traceback (most recent call last):
> >   File "/jax_iree_experiment/notebook/test_cuda_as_ireejax_backend.py", line 19, in <module>
> >     print(np.asarray(module["main"](x, y)))
> >   File "/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/runtime/function.py", line 129, in __call__
> >     self._invoke(arg_list, ret_list)
> >   File "/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/runtime/function.py", line 153, in _invoke
> >     self._vm_context.invoke(self._vm_function, arg_list, ret_list)
> > RuntimeError: Error invoking function: iree/runtime/src/iree/hal/drivers/cuda/stream_command_buffer.c:378: INTERNAL; CUDA driver error 'CUDA_ERROR_INVALID_HANDLE' (400): invalid resource handle; cuLaunchKernel; while invoking native function hal.ex.submit_and_wait; while calling import;
> > [ 1]   native hal.ex.submit_and_wait:0 -
> > [ 0] bytecode xla_computation_my_func_0.main:458 [unknown]
> > [debug]: iree_hal_cuda_device_destroy()
> > ```
> 
> Thanks for sharing, I wonder if the problem is really related to the context as it seems like we have the right context bound when doing the dispatch. Also I don’t see why another context would be created but I’m not an expert of jax. I’ll have to try to reproduce to understand what is going on here.

It's weird. I just cleaned and rebuilt IREE and then the test just passed. I repeated the build flow by undo/redo your patch and surely your patch works for my above test. (not sure why my first try failed). Thanks a lot.

**Comment by ThomasRaoux** [comment]
> > > > > @ThomasRaoux , rebuilt iree with your PR and ran my above python program, but hit the same error.
> > > > 
> > > > 
> > > > Could you give a bit more detail on what the error is? I’ll also try to reproduce on my side.
> > > 
> > > 
> > > ```
> > > (venv_local_iree_build) [jax_iree_experiment] > python notebook/test_cuda_as_iree_backend.py
> > > [debug]: iree_hal_cuda_device_create()
> > > [debug]:[iree/runtime/src/iree/hal/drivers/cuda/cuda_device.c]: cuCtxSetCurrent(context pointer: 0x0x32d0250)
> > > [debug]: iree_hal_cuda_device_destroy()
> > > [debug]: iree_hal_cuda_device_create()
> > > [debug]:[iree/runtime/src/iree/hal/drivers/cuda/cuda_device.c]: cuCtxSetCurrent(context pointer: 0x0x32d0250)
> > > [debug]:[/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/compiler/tools/xla.py][204]: ['/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile', '-', '--iree-input-type=xla', '--iree-vm-bytecode-module-output-format=flatbuffer-binary', '--iree-hal-target-backends=cuda', '--iree-llvm-embedded-linker-path=/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld', '--mlir-print-debuginfo', '--mlir-print-op-on-diagnostic=false']
> > > [debug]:[iree/runtime/src/iree/hal/drivers/cuda/stream_command_buffer.c]: (context pointer: 0x0x32d0250) before calling cuLaunchKernel
> > > Traceback (most recent call last):
> > >   File "/jax_iree_experiment/notebook/test_cuda_as_ireejax_backend.py", line 19, in <module>
> > >     print(np.asarray(module["main"](x, y)))
> > >   File "/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/runtime/function.py", line 129, in __call__
> > >     self._invoke(arg_list, ret_list)
> > >   File "/jax_iree_experiment/venv_local_iree_build/lib/python3.9/site-packages/iree/runtime/function.py", line 153, in _invoke
> > >     self._vm_context.invoke(self._vm_function, arg_list, ret_list)
> > > RuntimeError: Error invoking function: iree/runtime/src/iree/hal/drivers/cuda/stream_command_buffer.c:378: INTERNAL; CUDA driver error 'CUDA_ERROR_INVALID_HANDLE' (400): invalid resource handle; cuLaunchKernel; while invoking native function hal.ex.submit_and_wait; while calling import;
> > > [ 1]   native hal.ex.submit_and_wait:0 -
> > > [ 0] bytecode xla_computation_my_func_0.main:458 [unknown]
> > > [debug]: iree_hal_cuda_device_destroy()
> > > ```
> > 
> > 
> > Thanks for sharing, I wonder if the problem is really related to the context as it seems like we have the right context bound when doing the dispatch. Also I don’t see why another context would be created but I’m not an expert of jax. I’ll have to try to reproduce to understand what is going on here.
> 
> It's weird. I just cleaned and rebuilt IREE and then the test just passed. I repeated the build flow by undo/redo your patch and surely your patch works for my above test. (not sure why my first try failed). Thanks a lot.

Great, thanks for double checking. I'm closing this then.

**Comment by dan-garvey** [comment]
Can confirm from the nod perspective this resolved our issue too
