### ISSUE TITLE
Clean up the compiler API test binary.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#9302]
The [compile-mhlo-test-binary](https://github.com/google/iree/tree/main/compiler/src/iree/compiler/API/test) is ending up in the install/ directory. We should make sure we aren't building it unless required given its size/cost (maybe only with iree-test-deps), and should make sure it doesn't end up in the install/ directory (as it's a copy of a large binary).

It'd also be nice to rename it to make it a binary for all compiler API tests (which could have multiple .c files) so that in the future we don't add compile-tosa-test/etc binaries and add another 2GB to our build output.

**Comment by ScottTodd** [comment]
I came across similar issues working on https://github.com/iree-org/iree/pull/9474 and looking through the C API functions defined here: https://github.com/iree-org/iree/blob/636bc44f6d741da36667cf4c8f596f146150fa8f/compiler/src/iree/compiler/API/Compiler.h#L52-L87

I was thinking about generalizing blocks there to `ireeCompilerBuildImportPassPipeline(char* pipeline_name, ...)` so we wouldn't have an explicit function for every possible pipeline and could more easily swap optional / out of tree pipelines in.
