### ISSUE TITLE
Possible non-determinism in RewriteLinalgDestructiveUpdatesPass.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#9308]
On MSVC the test reliably fails with a transposed affine map symbol:
```
583: D:/Dev/iree/compiler/src/iree/compiler/Codegen/Common/test/rewrite_linalg_destructive_updates.mlir:122:15: error: CHECK-DAG: expected string not found in input
583: // CHECK-DAG: #[[MAP2:.+]] = affine_map<()[s0, s1, s2] -> (s0 * s1 + s2)>
583: <stdin>:39:1: note: possible intended match here
583: #map2 = affine_map<()[s0, s1, s2] -> (s1 * s0 + s2)>
```
(note expected `s0 * s1` vs actual `s1 * s0`)

In the past this has almost always indicated the use of an unsorted map or other data structure. IIRC there are ways of making LLVM randomize its maps that may help narrow it down (`EXPENSIVE_CHECKS` I think?).

**Comment by alliemartens** [comment]
@MaheshRavishankar Bumping this up as a slightly stale P1, please deprioritize or update as needed.

**Comment by MaheshRavishankar** [comment]
https://github.com/iree-org/iree/commit/7e54fe898a856eb74ba996f55e436edbdedaf9fa deletes the cultprit pass. So fixed.
