### ISSUE TITLE
Add MiniLM to the benchmark suite

### ISSUE THREAD

**Issue by pzread** [iree-org/iree#9318]
Add MiniLM model from https://github.com/google/iree-samples/blob/main/ModelCompiler/nlp_models/huggingface_MiniLM_run.py to the benchmark suite.

We want to benchmark it on x86_64 and CUDA.

**Comment by pzread** [comment]
Yes, I was just trying to avoid the TF->MLIR pass as all our current benchmarks are TFLite. It should be fine.

**Comment by pzread** [comment]
MiniLM is now benchmarking on x86 (#9547)

**Comment by alliemartens** [comment]
Hi Che-Yu, is this done?

**Comment by pzread** [comment]
We still need to add it to the CUDA benchmark pipeline.

**Comment by alliemartens** [comment]
@pzread Is there any update here?

**Comment by pzread** [comment]
#9791 will finish this task.

**Comment by alliemartens** [comment]
@pzread Any update here?

**Comment by pzread** [comment]
Still working on #9791 9791
