### ISSUE TITLE
Adapt LLVM-based CodeGen to opaque pointers

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#9319]
Upstream LLVM now enables opaque pointers by default with https://reviews.llvm.org/D126689. In integration https://github.com/google/iree/pull/9316 we explicitly set to disable opaque pointers to push forward. We need to drop the `context.setOpaquePointers(false);` changes introduced in #9316 and properly switch to opaque pointers.

**Comment by aeubanks** [comment]
Support for non-opaque pointers will be dropped after the next LLVM release, which will likely be in a month or two.
