### ISSUE TITLE
'Assertion failed: map.isProjectedPermutation( true)' while compiling tensorflow model using iree-compile.exe 

### ISSUE THREAD

**Issue by laxmansole** [iree-org/iree#9324]
**Describe the bug**
While compiling resnet50 tensorflow modelon windows using iree-compile.exe (model is imported into .mlir format using iree-import-tf  on WSL), I am getting the assertion `Assertion failed : map.isProjectedPermutation( true), file D:\iree\third_party\llvm-project\mlir\lib\IR\AffineMap.cpp, line 683`

**To Reproduce**
I am using following command to compile the model-
`iree-compile.exe \iree\samples\models\resnet50.mlir -iree-mlir-to-vm-bytecode-module -iree-hal-target-backends=dylib-llvm-aot --iree-input-type=mhlo  --iree-llvm-target-cpu=host -o resnet50_bytecode_module.vmfb` 

Note- I have a crash trace file but file size is exceeding 25MB

**Comment by ScottTodd** [comment]
Yay, a Windows user! A few of us on the team work primarily on Windows, despite some of its quirks :)

I suspect that your `iree-import-tf` and `iree-compile` are not compatible. At the moment, they need to be built very close to each other - we haven't yet stabilized the format between them. If you're using `iree-import-tf` from the python packages / releases and `iree-compile.exe` from a source build, you can look up what commit it was built at and use that with your build -- or just make sure that you are using the same release for both.

**Comment by ScottTodd** [comment]
Also to clarify "we haven't yet stabilized the format between them" - there are efforts underway in upstream LLVM/MLIR to add a ["ML program" dialect](https://discourse.llvm.org/t/rfc-introduce-ml-program-dialect-and-top-level-ops-proposal-v2/60907) and [config/metadata sections](https://discourse.llvm.org/t/rfc-adding-a-generalized-config-section-to-mlir-files/62867). Features like those will get us closer to stabilizing intermediate formats and adding versioning to detect when there are incompatibilities.

**Comment by laxmansole** [comment]
Thanks for the reply @ScottTodd. 
I wanted to note here that I can compile the same model on WSL and `iree-compile` is built from the sources on WSL. Also, I could use that model on windows to run the inference. So you can see I am using toolchain from WSL to build the model into `.vmfb` format and then use that on windows(I assume this is by design as there are no import tools available for windows).

**Comment by alliemartens** [comment]
Closing this issue for now, please re open if you encounter additional problems!
