### ISSUE TITLE
Confusing `iree-compile` and `tools/iree-compile` targets

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#9329]
I was wondering why `iree-compile` does not pick up the changes I made in the compiler, until I discovered the following in `build.ninja`:

```
build iree-compile: phony compiler/bindings/python/iree/compiler/_mlir_libs/iree-compile
build tools/iree-compile: CXX_EXECUTABLE_LINKER__iree-compile_Debug tools/CMakeFiles/iree-compile.dir/iree-compile-main.cc.o
```

So `iree-compile` is a phony target aliasing to python bindings, while all other iree binaries are phony targets aliasing to their `tools/` counterpart, e.g.:

```
build iree-benchmark-module: phony tools/iree-benchmark-module
build iree-dump-module: phony tools/iree-dump-module
```

This can be quite confusing. It's better to be consistent here.

**Comment by GMNGeoffrey** [comment]
@ScottTodd you were just messing with this, yes?

**Comment by ScottTodd** [comment]
> @ScottTodd you were just messing with this, yes?

No, I don't think so. I've reviewed some changes to the python bindings and how those targets are set up, but don't have any work planned in that area myself.

**Comment by GMNGeoffrey** [comment]
I thought this had to do with the cmake targets in tools

**Comment by GMNGeoffrey** [comment]
I now see

```
build iree-compile: phony tools/iree-compile
```

**Comment by antiagainst** [comment]
Hmm, I'm still seeing it as aliasing to `compiler/bindings/python/iree/compiler/_mlir_libs/iree-compile`. Have you enabled `IREE_BUILD_PYTHON_BINDINGS` when trying out?

**Comment by GMNGeoffrey** [comment]
Urgh, now. For that I'd have to remember how to build the python bindings. My cmake build dir is too old...

**Comment by GMNGeoffrey** [comment]
Oh, yup. When I build with the bindings enabled I see the same as you. Sorry about that. I'm not sure we really have a system for things that belong in *two* subprojects (infra and python bindings). Looks like some investigating of the Python bindings CMake configuration is required here.

**Comment by GMNGeoffrey** [comment]
A symptom of this (from @MaheshRavishankar):

> nasty build issue I ran into. If I have `IREE_BUILD_PYTHON_BINDINGS` on `iree-compile` in `tools/iree-compile` doesn't get updated.... Only `compiler/bindings/python/iree/compiler/_mlir_libs/iree-compile` gets updated. So I kept rebuilding `iree-compile` and kept having my changes not being picked up when I was using `tools/iree-compile`....

**Comment by GMNGeoffrey** [comment]
@stellaraccident could you take a look at addressing this? I think Lei has identified the root cause that is leading to the confusing behavior Mahesh is experiencing
