### ISSUE TITLE
Add verifiers to NVGPU ops

### ISSUE THREAD

**Issue by ThomasRaoux** [iree-org/iree#9395]
### Request description

The ops [mma.sync](https://github.com/llvm/llvm-project/blob/40f35cef894a4f899d1a0a31dd9600b9ce5e769b/mlir/include/mlir/Dialect/NVGPU/NVGPU.td#L82) and [ldmatrix](https://github.com/llvm/llvm-project/blob/40f35cef894a4f899d1a0a31dd9600b9ce5e769b/mlir/include/mlir/Dialect/NVGPU/NVGPU.td#L54) don't have a verifier. 
We should decide what makes sense to allow and add a verifier to make sure the type matches what the op should expect.

### What component(s) does this issue relate to?

MLIR

**Comment by ThomasRaoux** [comment]
[@manishucsd](https://github.com/manishucsd)

**Comment by manishucsd** [comment]
Patch targeting verifiers for `mma.sync` is in progress: https://reviews.llvm.org/D129400

**Comment by manishucsd** [comment]
Patch targeting verifiers for `ldmatrix` is in progress https://reviews.llvm.org/D129669
