### ISSUE TITLE
Increase time precision in the benchmark report

### ISSUE THREAD

**Issue by pzread** [iree-org/iree#9418]
### Request description

Currently we round our benchmark time (ms) to integer when reporting the benchmark results:
https://github.com/google/iree/blob/99097bed8a6999eae86a6f154e149b213bc745d4/build_tools/benchmarks/common/benchmark_definition.py#L435
This doesn't provide enough precision for x86 benchmarks, as they are usually fast and the improvement can be sub millisecond. 

### What component(s) does this issue relate to?

Other

**Comment by antiagainst** [comment]
+1. We could also consider changing the units for certain benchmarks. Right now they are all ms. Though that needs changes across the whole chain (`iree-benchmark-module`, Python collection scripts, presentation, etc.).
