### ISSUE TITLE
Investigate better measurement on dispatch binary sizes

### ISSUE THREAD

**Issue by pzread** [iree-org/iree#9436]
### Request description

To count the total size of dispatches in a module, currently we simply add up all dispatch binaries (from plolyglot). As the example in https://github.com/google/iree/pull/9227#discussion_r894579748, the raw size of the dynamic library might not provide enough granularity to the actual code size.

We might have similar issues on other formats of dispatches, such as SPIR-V flatbuffer.

### What component(s) does this issue relate to?

Other

**Comment by benvanik** [comment]
If you want precise sizes per dispatch region your best bet is to do an `--iree-hal-dump-executable-sources-to=` and then compile each using `iree-compile --compile-mode=hal-executable` - that'll spit out each file on its own without any linking/combining that we do in the normal pipelines. The tradeoff here is of course then that we aren't doing any linking/combining so it doesn't give you an accurate representation of the real size of the final output - we'll want to continue to track both.

**Comment by pzread** [comment]
I think we want to measure the total size of all dispatches (tracking individual size is hard as the number of dispatches is always changing). This issue is the paddings in the ELF section, which reduces the precision on the real code size. The code size might increase but still in the range of padding.

**Comment by bjacob** [comment]
In the past, I have come across situations where ther granularity of file size measurements was much larger than 4k. I seem to remember 64k for Android aarch64 builds of TFLite. I can dig up the ~ 3 year old data as needed (google internal). I never understood why the granularity was so high, but it was an empirical fact. I had a theory that it might be related to how relocations are implemented (and TFLite probably had lots more than we ever do in IREE runtime or module code).

Wanting a fine granularity metric does not imply wanting to act on tiny size changes. It's merely wanting to be able to tell tiny changes from larger changes. When the granularity is 64k, and a change makes us bump by 64k, all we know is the change was anywhere between 1 bytes and 128k minus 1 byte.

**Comment by benvanik** [comment]
The granularity is not 64K - we're generating the ELFs and it's 4K :)

**Comment by bjacob** [comment]
Is there a specific place in the embedded-elf linker code that controls that granularity? really curious!

**Comment by benvanik** [comment]
We don't set it and let the default of 4096 kick in:
https://code.woboq.org/llvm/lld/ELF/Target.h.html#lld::elf::TargetInfo::defaultCommonPageSize

(I'm not saying it's not useful to see the changes - just that _we can already do that with readelf/objdump_ and anything we were to build in addition to what we can already do is not going to make things easier)

**Comment by bjacob** [comment]
i guess i was wondering if something else than "page size" could contribute to the effective final file size granularity - after all, I doubt that page size was 64k when i observed 64k file size granularity across tflite android/aarch64 changes!

**Comment by benvanik** [comment]
I didn't pick those two constants at random :)

https://sourcegraph.com/github.com/llvm/llvm-project/-/blob/lld/ELF/Driver.cpp?L2678-2688
`// All important alignment decisions must use this value.`

**Comment by benvanik** [comment]
(if you saw 64K it was because someone override that value)

**Comment by benvanik** [comment]
Looks like toolchains do override it, and there's been some discussion about making it the default:
https://reviews.llvm.org/D77330

Our loader can align things in memory at any alignment we need and currently does the padding: https://github.com/google/iree/blob/857e15593718b74c15a104925bad1bab50fa7d9b/runtime/src/iree/hal/local/elf/elf_module.c#L244-L245
If the default does change we can override it (`-z max-page-size=4096`).

**Comment by benvanik** [comment]
Confirmed an aarch64 ELF is not padded - in fact, not even padded to 4096;
![image](https://user-images.githubusercontent.com/75337/173277835-7b50fe24-be97-4e73-bfd9-600f7d2738df.png)
Total size on disk is 3,968B.

**Comment by benvanik** [comment]
oh, that had debug info - stripped is 2,144B on disk:
![image](https://user-images.githubusercontent.com/75337/173278158-4110d131-0b3f-4415-8b79-31b4146fc571.png)
![image](https://user-images.githubusercontent.com/75337/173278184-696baf64-b5e0-4d93-95c9-36375f72d1b2.png)

Counting .text and .rodata is going to get you a pretty accurate code size number, and the rest of the total file size is relatively fixed (we only export a single symbol and we barely use relocations).

**Comment by pzread** [comment]
Back to the original topic, if the IREE ELF dispatch doesn't have padding between segments and the other non-code segments are fixed and relative small, then directly counting on the dispatch binary size seems not a bad idea to me. I measured the rodata + code vs. the binary size on mobilenetv3 x86 embedded ELF and the difference is only 2%. And as Ben said, small size changes will be buried in the noise. We can confirm the noise level after starting tracking the binary size.

I'm thinking if there is a way to track the bad IREE codegen (IREE generates bad LLVM IR) at the IR level, which suffers from less noise. For #8849, it looks like a histogram to count the vector sizes/types will help. And from my own experience, this can also track bad tiling config. @dcaballe WDYT?

**Comment by bjacob** [comment]
> Looks like toolchains do override it, and there's been some discussion about making it the default:
> https://reviews.llvm.org/D77330

Ha! OK, that clears it up. Thanks for digging this. Also relieved that "it wasn't just me" and 64k granularity was really a thing, and now I totally buy the rationale why IREE is not concerned :slightly_smiling_face:

**Comment by dcaballe** [comment]
> Although this probably won't happen soon, I'm thinking if there is a way to track the bad IREE codegen (IREE generates bad LLVM IR) at the IR level, which suffers from less noise. For #8849, it looks like a histogram to count the vector sizes/types might help. And from my experience, this can also track the bad tiling config. @dcaballe WDYT?

It would be hard. For #8849, the LLVM IR looks good until it's lowered to RISC-V machine instructions, which happens at the very end of the pipeline and it's target specific. It would be like inspecting assembly.

**Comment by pzread** [comment]
From the discussions above and the records in the past few months, it looks like using the size of each dispatch binary is okay at this moment. Close for now.
