### ISSUE TITLE
make e2e/xla tests `dot.mlir`, `dot_general.mlir` less expensive

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#9444]
These tests are relatively expensive, particularly with VMVX.

In #9435 we find that with the conjunction of VMVX and ThreadSanitizer, that becomes a real issue and requires at least increasing the timeout (which requires splitting them into separate CMake rules) and even so, the resulting coverage seems not worth the increase of TSan tests latency so we still decide to skip it under TSan (adding `notsan` tag).

Making these tests less expensive might be a simple matter of shrinking the matrix sizes involved, but some testcases there are specifically focusing on "large" shapes so there is presumably an original intent to get coverage specifically on such large shapes. Alternatively one might just skip these tests under VMVX.

**Comment by bjacob** [comment]
Change of course discussed in #9435 with @ScottTodd , @GMNGeoffrey : now trying to see if we can just do that right away.

What purpose is currently served by having (expensive) large shapes tested by xla/dot* tests?

There's no denying that many aspects of matmul implementation are prone to have bugs specific to large shapes. At some point in the past, these xla tests were presumably the only end-to-end matmul coverage that we had. But now that we have dedicated e2e/matmul tests, specifically testing such large shapes, it looks like there is no need anymore to test large shapes here?

Issues relating to large matmul shapes should be backend issues, orthogonal to frontends aspects such as XLA. The e2e/matmul tests should offer that backend coverage.

Some archaeology to find some people to CC to this discussion:
* the first introduction of large shapes here seems to be by @benvanik  in #336.
* the shapes were further widened by @MaheshRavishankar in #4772.

**Comment by ScottTodd** [comment]
Also see https://github.com/google/iree/pull/6661 from @ThomasRaoux . That touched `iree/test/e2e/cuda_specific/dot.mlir`, which I merged into `e2e/xla_ops/dot.mlir` in https://github.com/google/iree/pull/9151

**Comment by benvanik** [comment]
agreed!

**Comment by bjacob** [comment]
Fixed by https://github.com/iree-org/iree/pull/9435
