### ISSUE TITLE
Include CI build with latest compiler versions

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#9468]
We currently use the oldest supported version of clang in all our CI builds. This is to ensure that we do indeed support the versions we say we support. New versions of clang can have new warnings or ability to detect existing warnings, and additional nice features. We want to ensure we build with the newer compiler versions as well. We should have a CI build that builds with some recent (frequently updated) version of clang also. That could just be the latest release version, updated as needed, or we could get fancy and build it from source from our llvm-project submodule (personally, I think the former is probably fine). We could use a more updated clang in a totally separate build that is only for that purpose, or put an existing build to multiple purposes. Sanitizer builds seem like a good candidate for the latter. That way is cheaper resource-wise and one less build to deal with, but it also means that people might be confused by errors only in the asan build (for instance) that don't have anything to do with asan.

**Comment by powderluv** [comment]
I have couple VMs that track upstream llvm ppa and get the latest clang before I build.

They have a one line script we can use in a Dockerfile ``` 
bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" ```

**Comment by GMNGeoffrey** [comment]
I don't like non-deterministic docker files. They're a great way to make it impossible to update the version of one thing because it causes something else to change (has hit us multiple times before). Manually bumping for the latest stable clang doesn't seem very hard.

**Comment by GMNGeoffrey** [comment]
Fixed in #11185 and #11083
