### ISSUE TITLE
Release tooling has inconsistent treatment of package-suffix

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#9500]
In testing self-hosted runners, I launched the "build_release" workflow with a package suffix argument. It appears that much of the release tooling fails when such an argument is passed because it tries to glob for patterns that don't match the files created at https://github.com/google/iree/blob/23da926754/build_tools/python_deploy/build_linux_packages.sh#L135

First, package-suffix is assumed to start with a dash. I think we probably should not make such assumptions that comes from free-form user input. We should either not assume it, always prepend the dash ourselves, or validate that it is present.

Even with a dash, the filenames don't conform to what the glob expects because it somehow turns dashes into underscores and appends things after the suffix instead of before. Errors include:

> auditwheel: error: cannot access /wheelhouse/iree_runtime_instrumented*cp37-cp37m-linux_x86_64.whl. No such file

(https://github.com/google/iree/runs/6886630965)

> auditwheel: error: cannot access /wheelhouse/iree_compiler-*-cp37-cp37m-linux_x86_64.whl. No such file

(https://github.com/google/iree/runs/6885672332)

This is the contents of version_info.json
```
{
  "package-suffix": "-gcmn-testing-runners",
  "package-version": "0.1a1",
  "iree-revision": "efd24d6563891fd7b88f41204da4ab9752061051"
}
```

After building the releases, the actual contents of the bindist directory (which is mounted as `/wheelhouse` in the docker container) is:

> PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
> PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
> PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
> PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
> iree-dist-gcmn-testing-runners-0.1a1-linux-x86_64.tar.xz
> iree_compiler_gcmn_testing_runners-0.1a1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> iree_compiler_gcmn_testing_runners-0.1a1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> iree_compiler_gcmn_testing_runners-0.1a1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> iree_compiler_gcmn_testing_runners-0.1a1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> iree_runtime_gcmn_testing_runners-0.1a1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> iree_runtime_gcmn_testing_runners-0.1a1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> iree_runtime_gcmn_testing_runners-0.1a1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> iree_runtime_gcmn_testing_runners-0.1a1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> iree_runtime_gcmn_testing_runners_instrumented-0.1a1-cp37-cp37m-linux_x86_64.whl
> iree_tools_tf_gcmn_testing_runners-0.1a1-py3-none-linux_x86_64.whl
> iree_tools_tflite_gcmn_testing_runners-0.1a1-py3-none-linux_x86_64.whl
> iree_tools_xla_gcmn_testing_runners-0.1a1-py3-none-linux_x86_64.whl
> numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
> numpy-1.22.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> numpy-1.22.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> numpy-1.22.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

**Comment by ScottTodd** [comment]
Going to call this obsolete with https://iree.dev/developers/general/versioning-scheme/ now rolled out, using standardized version schemes (`X.Y.Z`, `X.Y.ZrcYYYYMMDD`, `X.Y.Z.dev0+01234`)

We do still have an option to explicitly set the package version or suffix in the workflow, but that is only lightly used: https://github.com/iree-org/iree/blob/c0fc41b2dd2370a33e88613941dfd0c5f68af5d2/.github/workflows/build_package.yml#L13-L39
