### ISSUE TITLE
[Vulkan-M1] Numerical issue with MiniLM-Torch Vulkan static

### ISSUE THREAD

**Issue by raikonenfnu** [iree-org/iree#9582]
### What happened?

Numeric issue:
```bash
E       assert True == False
E        +  where False = 
compare_tensors(tensor([[-0.0235, -0.0219]], grad_fn=<AddmmBackward0>), 
array([[8.790488e-38, 0.000000e+00]], dtype=float32))
```
Currently set as xfail

### Steps to reproduce your issue

On a nod VM image run:

```
git clone https://github.com/nod-ai/SHARK.git
PYTHON=python3.10 VENV_DIR=0617_venv IMPORTER=1 USE_IREE=1 ./setup_venv.sh 
source 0617_venv/bin/activate
python -m pytest tank/pytorch/MiniLM-L12-H384-uncased/MiniLM-L12-H384-uncased_pytorch_test.py::MiniLMModuleTest::test_module_static_vulkan
```

### What component(s) does this issue relate to?

Compiler

**Comment by antiagainst** [comment]
I'm not able to reproduce this numeric issue on my side. At the current tip (0e8d8370699912c6b51889e8f7e967690102402c) I'm seeing the result for ` tools/iree-run-module --device=vulkan --entry_function=forward --function_input=1x128xi64` as `1x2xf32=[-0.043285 0.0561848]`. With the fix (#9614) for i64 buffer aliasing issue, it's `1x2xf32=[-0.043285 0.0561848]`. They are not zeros anymore. Still different than the above expected results though. Did I use the correct input values?

**Comment by antiagainst** [comment]
I'm using Vulkan SDK 1.3.216.0 on my side.

**Comment by raikonenfnu** [comment]
I tested your branch with SHARK and the tests are passing, will close this issue once your patch goes in :)
