### ISSUE TITLE
FFT lowering needs to be adapted to the updated workload + workgroup count calculation mode

### ISSUE THREAD

**Issue by MaheshRavishankar** [iree-org/iree#9583]
PR #9552 makes the following changes to workload + workgroup count spec

1) The `workload` is now the same as the number of points in the iteration space of the operation, i.e.
		- The number of entries is same as the dimensionality of the iteration space (and not just 3 as it was previously)
		- The entries are ordered from "highest to lowest" (and not in x, y and z mode it was done previously)
		- The value for each dimension that is "parallel" is `ceilDiv(ub - lb, step)` instead of just `ub`.
	For now those dimension of the iteration space that are "reduction" are set to 1, but that doesnt need to happen either. Will be relaxed subsequently.

2) The backend generates the number of workgroups to use in the same manner as before, just adapted to the new workload representation

Its mostly an NFC change, but the `tests/e2e/xla_ops/fft.mlir` fails on SPIR-V. There seems to be some assumption in the tile size selection that conflicts with the above and needs to be addressed. The test is disabled in PR #9552 since the spir-v fft isnt load bearing at this point, but still needs to be adapted. This bug is to track the re-enabling of this test.

**Comment by MaheshRavishankar** [comment]
Confirmed that the issue is because PR #9552 changes the workload computation to `ceilDiv(ub - lb, step)` instead of just `ub`. Both SPIR-V and CUDA do the same thing in tile size selection. The number of parallel iterations should just be `ceilDiv(ub -lb, step)`. If it is indeed `ub` then this needs to be revisited.
For now my conclusion is that there is some assumption in the configuration selection that might have been wrong, and the change exposed it. So disabling the SPIR-V and CUDA FFT tests.

**Comment by antiagainst** [comment]
@hanhanW: You added FFT support and configuration to both CUDA and Vulkan. Would mind to take a look at this issue?

**Comment by hanhanW** [comment]
Yes, I'll help look into it!

**Comment by hanhanW** [comment]
This is the IR before RemoveSingleIterationLoopPass: https://gist.githubusercontent.com/hanhanW/6bb2252e8465ba8f97ee2a34ef2a8dd0/raw

The IR looks good to me. I might set configurations wrong... 

`#iree_codegen.translation_info<SPIRVDistribute workload_per_wg = [2]>, workgroup_size = [4 : index, 1 : index, 1 : index]} `

The workload per workgroup is 2, and there are total 4 workgroups. Are we able to delete the outermost loop in this case?

**Comment by MaheshRavishankar** [comment]
That pass is to be removed this quarter. Ill check if that helps fix this issue. Thanks for the traige

**Comment by ScottTodd** [comment]
Since WebGPU uses the SPIR-V backend in generating WGSL, this is also affecting the WebGPU compilation target:

`iree-compile --iree-hal-target-backends=webgpu --iree-input-type=mhlo tests/e2e/xla_ops/fft.mlir -o /dev/null`

```mlir
// -----// IR Dump Before ConvertToSPIRV (iree-convert-to-spirv) //----- //
module {
  func.func @_rfft_1d_dispatch_0_generic_32() {
    %cst = arith.constant dense<0> : vector<1xi32>
    %c0 = arith.constant 0 : index
    %cst_0 = arith.constant dense<true> : vector<1xi1>
    %cst_1 = arith.constant dense<0.000000e+00> : vector<1xf32>
    %cst_2 = arith.constant dense_resource<__elided__> : tensor<32xi32>
    %c32 = arith.constant 32 : index
    %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%c0) alignment(64) : memref<?xf32, #spirv.storage_class<StorageBuffer>>{%c32}
    %cast = memref.cast %0 : memref<?xf32, #spirv.storage_class<StorageBuffer>> to memref<32xf32, #spirv.storage_class<StorageBuffer>>
    %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) offset(%c0) alignment(64) : memref<?xf32, #spirv.storage_class<StorageBuffer>>{%c32}
    %workgroup_id_x = hal.interface.workgroup.id[0] : index
    %2 = gpu.thread_id  x
    %3 = arith.muli %workgroup_id_x, %c32 : index
    %4 = arith.addi %2, %3 : index
    %extracted = tensor.extract %cst_2[%4] : tensor<32xi32>
    %5 = vector.insert %extracted, %cst [0] : i32 into vector<1xi32>
    %6 = arith.index_cast %5 : vector<1xi32> to vector<1xindex>
    %7 = vector.gather %cast[%c0] [%6], %cst_0, %cst_1 : memref<32xf32, #spirv.storage_class<StorageBuffer>>, vector<1xindex>, vector<1xi1>, vector<1xf32> into vector<1xf32>
    %8 = vector.extract %7[0] : vector<1xf32>
    memref.store %8, %1[%2] : memref<?xf32, #spirv.storage_class<StorageBuffer>>
    return
  }
}

D:\dev\projects\iree/../iree-tmp/webgpu/tests_2022_10_25/\module__rfft_1d_dispatch_0.mlir:12:8: error: failed to legalize operation 'memref.cast'
        %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<readonly:32xf32>
       ^
```

(also not load bearing / blocking, but I'm just seeing which tests pass/fail as the compiler target comes online)
