### ISSUE TITLE
LLVM Integration broke SPIR-V round tests.

### ISSUE THREAD

**Issue by MaheshRavishankar** [iree-org/iree#9617]
The LLVM integration PR https://github.com/google/iree/pull/9610 broke the SPIRV tests for `round.mlir`. Seems related to https://github.com/google/iree-llvm-fork/commit/ce07b95610f7f8e70738790790a95e61a415e128 .

This bug is to track the re-enabling of these.

**Comment by rsuderman** [comment]
https://reviews.llvm.org/D129236 should fix the spirv issues
