### ISSUE TITLE
Build fails when path of the repository contains ".h" or ".inc"

### ISSUE THREAD

**Issue by hehaoqian** [iree-org/iree#9704]
### What happened?

When building the target "iree-run-module"

ld.lld: error: undefined symbol: flatcc_verify_error_string
>>> referenced by bytecode_module.c:253 (/mnt/data-1/data/haoqian.he/iree/runtime/src/iree/vm/bytecode_module.c:253)
>>>               bytecode_module.c.o:(iree_vm_bytecode_module_flatbuffer_verify) in archive runtime/src/iree/vm/libiree_vm_bytecode_module.a

ld.lld: error: undefined symbol: flatcc_verify_table_as_root
>>> referenced by bytecode_module_def_verifier.h:557 (runtime/src/iree/schemas/bytecode_module_def_verifier.h:557)
>>>               bytecode_module.c.o:(iree_vm_BytecodeModuleDef_verify_as_root) in archive runtime/src/iree/vm/libiree_vm_bytecode_module.a

### Steps to reproduce your issue

1. clone the iree repository to a directory whose path contains ".h",
for example "haoqian.he"

2. Follow IREE get started guide to build iree

### Version information

IREE Commit id = 664163e2d2a2dd6f5bffb40844bafcf3b116c270

### Additional context

I think the problem is

https://github.com/iree-org/iree/blob/664163e2d2a2dd6f5bffb40844bafcf3b116c270/build_tools/cmake/external_cc_library.cmake#L97

The regex should add a "$" sign to ensure ".h|.inc" only matches when they are at the end of the filename

Change to

```
if(${_SRC_FILE} MATCHES ".*\\.(h|inc)$") 
```

See Pull Request #9703

**Comment by jpienaar** [comment]
PR merged, is this issue addressed now?

**Comment by ScottTodd** [comment]
Yeah, looks like https://github.com/iree-org/iree/pull/9703 fixed this. Please reply or re-open the issue if not.
