### ISSUE TITLE
Numeric issue in LayoutLm on CPU

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#9716]
### What happened?

The output from IREE CPU and golden values mismatch.

### Steps to reproduce your issue

Download the artifacts from https://storage.googleapis.com/iree-shared-files/nod-perf/hanchung/layoutlm_repro.zip

```
$ iree-compile --iree-mlir-to-vm-bytecode-module --iree-input-type=mhlo --iree-hal-target-backends=dylib-llvm-aot --iree-llvm-target-triple=x86_64-linux-gnu --iree-llvm-target-cpu-features=host core-input.mlir -o /tmp/a.vmfb
$ iree-run-module --module_file=/tmp/a.vmfb --device=local-sync --entry_function=forward --function_input=@input1.npy --function_input=@input2.npy --print_max_element_count=1073741824
```

### What component(s) does this issue relate to?

Compiler

**Comment by hanhanW** [comment]
Coming from https://github.com/iree-org/iree/issues/9536#issuecomment-1166945952. The results are very different. E.g.,

```
Failed @ position 0 : -1.532623 v.s. 1.50368261
```

**Comment by alliemartens** [comment]
Sure! @powderluv FYI adding this bug to our hotlist.

**Comment by pzread** [comment]
@hanhanW Is 1.50368261 the correct value? I reran your sample on CascadeLake CPU and got the results which are very close to the `expected_out.txt`

I also ran the test https://github.com/nod-ai/SHARK/blob/main/tank/tf/hf_masked_lm/layoutlm-base-uncased_tf_test.py#L105 and it pass now.

**Comment by hanhanW** [comment]
Interesting... maybe it's fixed by other changes recently. I'll verify it again, thanks!

**Comment by hanhanW** [comment]
I verified that the numeric issues are gone. Sometimes it fails because of accuracy, but I think it's fine. Closing the issue.

@powderluv , the SHARK tests are not deterministic. The input data and expected output are changed between runs. Can we have deterministic tests in the integration tests? Otherwise, it's hard to verify if the issue is addressed.
