### ISSUE TITLE
vtune does not display source/assembly for IREE modules

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#9717]
### Request description

We're trying to get more low-level analysis using vtune. One of VTune examples shows that we're able to display total time at source/assembly level. E.g.,

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/6949191/177495583-79a8f0ea-82fb-4b3b-8e67-4d9b9db17296.png">

For IREE modules, the feature is not available in vtune. IREE loads the vmfb file at runtime, and the tool knows nothing about the file. Couple possible reasons:

1. We might need debug information enabled when compiling the LLVM module.
2. We have to make sure the dynamic code is resolved to symbolic name. Might need to use JIT API provided by VTune Profiler.

### What component(s) does this issue relate to?

Compiler, Other

**Comment by benvanik** [comment]
Use tracy instead if possible - it's already setup for this and shows most of the same top-level information. Vtune (and any vendor tool) will show more, but if you can get by without it using the path we support will be much easier for now.

**Comment by hanhanW** [comment]
Are they showed by default? I remembered that I saw asm stuff in your present, but could not do it on my local side. Do we have to apply some patches?

**Comment by ScottTodd** [comment]
Maybe try with `--iree-llvm-link-embedded=false`, to use the system linker instead of embedded ELF? That, along with `--iree-llvm-debug-symbols=true` (the default) has been enough for other tools to see source information.

**Comment by hanhanW** [comment]
I tried with `--iree-llvm-link-embedded=false` when using Tracy. With the flag, I do see the image mapping to `/tmp/iree_dylib...`. But I still can't get the asm view. Are we able to do it with Tracy? It would be very helpful because Tracy also collects some HW samples.

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/6949191/177739476-1a8d72a8-a62d-4bef-bcd5-9c03159c83dc.png">

(Tag @bjacob because he's also a Tracy user. Maybe I can get an answer from him.)

**Comment by bjacob** [comment]
Indeed, `--iree-llvm-link-embedded=false` is the first step. The symptom you're observing here --- you can see the symbols but still don't get the disasm --- typically means that you also need to rebuild the Tracy profiler UI (`iree-tracy-profiler`) with this "dirty hack" patch as explained here:
https://github.com/iree-org/iree/blob/main/docs/developers/developing_iree/profiling_with_tracy.md#patch-needed-for-androidarm

However, that patch as-is,
https://github.com/wolfpld/tracy/pull/383/files
 assumes that all instructions are 4-byte as is the case on ARM.  For x86, where instructions can have any number of bytes, you need to change
```
baseAddr -= 4;
```
into
```
baseAddr -= 1;
```
Please let me know if that works. It seems that we could just unconditionally make that change to that patch regardless of the architecture.

**Comment by hanhanW** [comment]
Thanks for the great input! I was not aware that there is a doc. It's much informative than the doc I've seen before. I'll give it a shot!

**Comment by hanhanW** [comment]
BIG thanks to @bjacob ! I followed the doc, and applied the patch (with `baseAddr -= 1;` version). It does work really nice to me on x86. I'm able to get source + assembly view for matmul microbenchmarks. (Some samples work and some samples do not work. The reason could be sample rate or something else.)

![image](https://user-images.githubusercontent.com/6949191/177937121-33282db0-8214-4d53-8d24-750da8ed484f.png)

The source code (at MLIR level) does not work for the e2e model. The symbol is unknown for some reasons. But I still can see good information at asm level.

![image](https://user-images.githubusercontent.com/6949191/177939954-f4515d45-5fa8-419e-9e8a-bb9aacc3f459.png)


> It seems that we could just unconditionally make that change to that patch regardless of the architecture.

Ideally we should map baseAddr to the place where IREE maps the module, and follow the symbol table structure to resolve it. Walking back from the `symAddr` correctly is not trivial. The `baseAddr -= 1` solution seems to be a reasonable workaround in this context.

Closing the issue since we're able to get the information by using Tracy.

**Comment by bjacob** [comment]
Woohoo!

I'll mention on the Tracy PR where the patch lives, that you found the ` baseAddr -= 1;` version useful on x86. It would still be very useful to understand the root problem there.

Too bad that you're not getting MLIR source view for the e2e model. i haven't run into that situation before. I guess that's what you would get if the module lacked debug information. As was mentioned above, you should get debug symbols since `iree-llvm-debug-symbols` is true by default (rather, `LLVMTargetOptions::debugSymbols` defaults to `true` and is only overriden if `iree-llvm-debug-symbols` is passed).

Can you try a few commands, like `file`, `readelf` or `dwarfdump` on the temporary `.so` file to see if it actually has debug symbols?

**Comment by hanhanW** [comment]
update -- I was not able to disasm some dispatches because capstone 4 is too old. I need capstone 5 for x86 development (e.g, to disasm vxorps ops). I'm able to do it and can update the doc for x86 part.

**Comment by bjacob** [comment]
Great! I was actually wondering if you would run into that. The doc mentions using capstone's `next` branch for some recent architecture but could use an update saying it's needed also on x86:
https://github.com/iree-org/iree/blob/main/docs/developers/developing_iree/profiling_with_tracy.md#do-you-need-capstone-next

**Comment by hanhanW** [comment]
Yeah, I saw the hint but was not aware of it. It just failed silently. Also, I'm actually surprised that the default version is still 4, not 5. The patch was checked into "next" branch two years ago. ;D

I'm going to spend some time on disappeared source view and make sure there are no other surprise..

**Comment by bjacob** [comment]
Possible fix: https://github.com/wolfpld/tracy/issues/384#issuecomment-1200399148

**Comment by antiagainst** [comment]
It has been a while since we updated Tracy. So let me give it a bump there to include this fix. :)

**Comment by antiagainst** [comment]
Uploaded https://github.com/iree-org/iree/pull/9977.
