### ISSUE TITLE
VM conversion of memref.alloca does not promote integer types

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#9778]
This:
```
%9 = memref.alloca() {alignment = 128 : i64} : memref<4xi1>
```

Is getting lowered to this:

```
%c1_3 = vm.const.i64 1
%buffer_4 = vm.buffer.alloc %c1_3 : !vm.buffer
```

The VM ConvertMemRefAllocaOp pattern is the culprit. It does not have size promotion logic to match load/store conversions. Adding this little patch gets all of these working:

```
    // TODO: Match this with load/store promotion logic.
    if (auto intType = type.getElementType().dyn_cast<IntegerType>()) {
      if (intType.getWidth() < 8) {
        intType = rewriter.getType<IntegerType>(8);
        type = type.cloneWith(type.getShape(), intType);
      }
    }
```

Not arguing we do it just like that. Ideally, I would like a utility that alloc/load/store call to appropriately widen their fundamental access type. And that should take care of sub-byte aligned buffers.

**Comment by benvanik** [comment]
you can use `IREE::Util::getRoundedElementByteWidth` - that does the right rounding and is what we use in other places

**Comment by stellaraccident** [comment]
We should probably fix load/store to round properly too vs just checking specific step-sizes of bit width.

**Comment by benvanik** [comment]
I'm still wiring it up but this should be fixed once we have util.buffer in-between memref and vm.buffer.

**Comment by benvanik** [comment]
(feel free to hack around if it's blocking you)
