### ISSUE TITLE
[spirv] Support reduction + elementwise op with dynamic shapes

### ISSUE THREAD

**Issue by okkwon** [iree-org/iree#9802]
### What happened?

When a reduction and an elementwise op with dynamic shapes are in a single dispatch, the vulkan fails to compile. The first pass that fails is PadDynamicAlloc.

### Steps to reproduce your issue

The input file is here: https://gist.github.com/okkwon/9d56fd368ab61aaec5bf5f18345fda6b

The command to reproduce is:

```
iree-compile iree_input.mlir --iree-input-type=xla --iree-flow-fuse-reduction-broadcast-elementwise --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan-spirv -o=compiled.vmfb
```

Here is the afterall dump: https://gist.github.com/okkwon/680b255bc70ce30777944eacc7ea4fc9

### What component(s) does this issue relate to?

Compiler

**Comment by antiagainst** [comment]
closing as obsolete -- no actions planned now
