### ISSUE TITLE
`computeBufferDescriptor` mutates IR before knowing whether the pattern application will succeed

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#9809]
Testcase:

```
func.func @foo(%arg0 : memref<1x?x8x4xi8>, %arg1 : memref<1x?x8x4xi8>, %arg2 : memref<1x1x8x8xi32>) {
  linalg.mmt4d ins(%arg0, %arg1 : memref<1x?x8x4xi8>, memref<1x?x8x4xi8>) outs(%arg2 : memref<1x1x8x8xi32>)
  func.return
}
```

Run:

```
tools/iree-opt --pass-pipeline="func.func(iree-vmvx-lower-linalg-microkernels, canonicalize, cse)" /tmp/a.mlir -debug
```

Result:
* `iree-opt` silently `exit(1)`
* With `-debug` one gets this message:

```
The pattern rewrite doesn't converge after scanning 10 times
```

The `-debug` output looks like this: https://gist.github.com/bjacob/b0b7aa66f17a96eac999c1e5b81cb4fe

That log shows creation of `arith.muli`.  Setting a breakpoint on `mlir::arith::MulIOp::build` I found that we were in the parts of `computeBufferDescriptor` that actually create integer add/mul ops to deal with strides, layouts etc.

But the callers of `computeBufferDescriptor` don't know yet that the pattern application will succeed so it seems too early to mutate IR?  And those IR mutations + pattern match failures seems to explain the above "doesn't converge" error ?

**Comment by bjacob** [comment]
@stellaraccident

**Comment by stellaraccident** [comment]
Yeah, was hoping you wouldn't hit that yet. I'm in the process of refactoring it -- and the right fix removes all of this in favor of upstream enhancements.

**Comment by stellaraccident** [comment]
I'm curious why it is failing, though. The cases where it is early exiting shouldn't be happening.

**Comment by alliemartens** [comment]
@stellaraccident Assigning this to you as a P1 since it looks in progress. If this is untrue please change!

**Comment by bjacob** [comment]
Confirming it's fixed now.
