### ISSUE TITLE
Allow to combine VMVX kernels and Codegen within the same module

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#9821]
Implement a way that we can generate modules containing both VMVX and Codegen dispatches and make it reasonably easy to express that "these few ops are to be compiled as calls to VMVX microkernels, everything else can go to codegen".

TBD: how is the routing to VMVX / to Codegen going to be expressed. In C++ compiler code? On the command line? In MLIR attributes?

Motivation: I would like to play with vmvx kernels for mmt4d. At the same time, I think that Codegen is great for much of the rest of the module, including within the matmuls, for the packing/unpacking code surrounding the mmt4d.

**Comment by bjacob** [comment]
@stellaraccident @benvanik @MaheshRavishankar @julianwa

**Comment by benvanik** [comment]
Slow down - this is not actually something we want.

**Comment by julianwa** [comment]
> Slow down - this is not actually something we want.
Which part? is "use mmt4d+vmvx for matmul, and codegen for everything else" an undesirable goal? or is it just our assumptions about how to get there that are off?

**Comment by MaheshRavishankar** [comment]
I understand Ben's concerns, but I think for evaluation purposes having something like this would be useful? It would also be the first foray into "hetergenous execution" where different dispatches execute on different "devices" (though both are effectively CPU). This will help get some initial numbers of how much benefit the micro kernels give over what is generated by CPU codegen path without using the inline assembly path (which also has its limitations) for some dispatches and not be thrown off by dispatches that are just elementwise operation not having a good VMVX implementation. There is a long tail of such operations that adding support for is very time consuming. This is definitely a shortcut, and for development purposes only, but is valuable even if there is no deployment story for it.

**Comment by benvanik** [comment]
Had some stuff typed but I think a meeting would be better.

You're right Mahesh that this is effectively heterogenous compute which is why this is really not a good exercise to be doing under the "move fast and break things" model: that's the most complex area of the stack and arguably least important.

I think there's a misunderstanding that'd be good to work through: we're talking about making hacky changes across the stack to support a deployment model we don't want/need in order to get numbers that are only indicative of the worst case performance in order to make investment plans for unrelated scenarios. I'm questioning the implied value being placed on this :)

**Comment by julianwa** [comment]
At a high-level, we're looking to understand whether VMVX can be used to accelerate @bjacob's work, making it easier for him to plug in the micro-kernels that we would like to use without painful manipulation of codegen to get things in the right form for the inline kernels.

We didn't mean to be too prescriptive about a solution. The goal was to ask: is there a way that we can glue these things together such that we can evaluate the hypothesis that VMVX can produce a great result? The hackiness was only proposed because we want to evaluate it as much as possible before deciding on level of investment. If it's a bad idea to start with, then we should have that discussion first. :) 

I'll find some time to chat.

**Comment by mattwalsh** [comment]
At first when I read VMVX summary, namely, 

> "a virtual ISA  extension to the IREE VM that exposes variable-length vector operations...std & vector dialect ops map to these vs. lowering to scalar loops" 

I deduced this was just a way to express a vector operation that remains a "logical" vector operation; almost a "lowering stop" to inhibit decomposing into a loop + scalar ops that would need to be re-assembled into vector operations later.  Seems to me the above doesn't necessarily imply heterogenous compute.

**Comment by julianwa** [comment]
> heterogenous compute

It's heterogenous in the sense that the execution would target separate IREE back-ends (separate HAL devices, etc), even though both would execute on the same physical CPU.

**Comment by benvanik** [comment]
Ok that's useful context - the good news is that these things are separable. It's much easier to use one or the other (pure VM or AOT) than the try to use both - trying to use both is all the same work as using either with additional hacks and non-transferrable results. I just synced with Benoit and he was thinking the pure AOT route but didn't realize what Stella has for the e2e is pure VM - and I didn't realize he didn't realize that and thought he was asking for the mixed case :P

We should still get together and have a high bandwidth conversation about next-steps - I think pure VM is going to be the least work and can start today while the pure AOT path is going to need some work from Mahesh or I to finish wiring up (but not a lot). Here's some background with code links we can point at and talk about:

> making it easier for him to plug in the micro-kernels that we would like to use without painful manipulation of codegen to get things in the right form.

VMVX is just a way to go from linalg to library calls and make those calls at runtime. That's it. You still need to write the compiler code to go from linalg to library calls and you still have to implement the library calls just as you would on the AOT path but you _also_ need to write VM goo (custom dialect ops, lowerings into the VM dialect, etc). It's strictly more work if you don't actually care about what the VM execution model gives you (versioning, portability, untrusted execution environments, etc). That said: it's done and working and strictly copy/paste to add new ops.

If you do, however, want to work on more compiler infra then the AOT path is nearly ready and once ready will be easier than the VMVX route in every way. It needs a bit of conversion goo and some cmake build scripts.

On the AOT path the `iree/builtins/` are designed to provide library calls to the compiler - you write C code and then have that linked in to the AOT codegen output - and the only codegen goo you need is a lowering from linalg->the builtin by way of an external function and a call to that function. You then get LTO and hermetic binaries that are seamlessly interleaved with other codegen generated output. It's the best way to get the smallest code size (as all paths not needed get stripped), fastest execution (as the compiler can track through to all call sites and inline/hoist/propagate), and easiest deployments (every model compiled can have a bespoke specialization of the kernels). See the diagram in the existing [`iree/builtins/device/` docs](https://github.com/iree-org/iree/blob/main/runtime/src/iree/builtins/device/README.md):
```
+------------+      +-------+      +-------------------------------+
| device_*.c | ---> | clang | ---> |+-------------------------------+
+------------+      +-------+      +| libdevice_[arch]_[variant].bc |
                                    +-------------------------------+
                                                  |||
                                                  vvv
      +------------+      +---------+      +================+
      | input.mlir | ---> | codegen | ---> | iree-compile   |
      +------------+      +---------+      +================+
                                                   |
                      +----------------------------+
                      v                            v
         +------------------------+   +----------------------------+
         | static library (.o/.a) |   | dynamic library (.so/.dll) |
         +------------------------+   +----------------------------+
```

Concretely all the LLVM codegen stuff needs to do is produce the equivalent of:
```c
extern void some_external_kernel(const void* lhs, const void* rhs, void* out, size_t count);
void dispatch() {
  << generated stuff >>
  some_external_kernel(...);
  << generated stuff >>
}
```

The only way this intersects with VMVX is that we should be sharing the implementation of these wherever possible: so the runtime links against `iree/builtins/vmvx/` or `iree/builtins/mmt4d/` or whatever and calls them from the VMVX module shim while the compiler pulls in the same code for linking into the AOT outputs. The builtin library can be compiled/tested/benchmarked standalone without touching either the runtime or compiler and an implementation in there is immediately available to VMVX with the same amount of goo as would make it available to AOT codegen plus some VM goo (linalg->vmvx op->call).

So:
```
+-----------+      +-------+      +------------------------------+
| mmt4d_*.c | ---> | clang | ---> |+------------------------------+
+-----------+      +-------+      +| libmmt4d_[arch]_[variant].bc |
  |                                +------------------------------+
  |                                               |||
  |                                               vvv
  |   +------------+      +---------+      +================+
  |   | input.mlir | ---> | codegen | ---> | iree-compile   |
  |   +------------+      +---------+      +================+
  |                                                |
  |                   +----------------------------+
  |                   v                            v
  |      +------------------------+   +----------------------------+
  |      | static library (.o/.a) |   | dynamic library (.so/.dll) |
  |      +------------------------+   +----------------------------+
  |
  | or:
  |
  |   +------------+      +------+      +================+
  |   | input.mlir | ---> | VMVX | ---> | iree-compile   |
  |   +------------+      +------+      +================+
  |                                             |
  |                                             v
  |                                    +------------------+
  |                                    |    module.vmfb   |
  |                                    +------------------+
  |                                             +
  |                                  +---------------------+
  +--------------------------------> | VMVX runtime module |
                                     +---------------------+
```

If what you want is an easy way to make calls to C code then this is that and it's a real production use case that is worth working on. I'm happy to help set this up - it's mostly copy/paste of the existing device builtins, copy/paste of the compiler goo to link the library, and then a few patterns. The end goal is that we have a library (or multiple) of kernels that are written in C and some patterns in the compiler that lower linalg into calls to those kernels.

The mechanics aren't complex. You'll note that VMVX is just doing bufferization and then converting the microkernels:
https://github.com/iree-org/iree/blob/7be9646d849e057a1b78f2d144d5daa9e9157ecf/compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp#L356
and on the AOT path you could have the same kind of pass after bufferization here:
https://github.com/iree-org/iree/blob/7be9646d849e057a1b78f2d144d5daa9e9157ecf/compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp#L325

Note also that this happens _before_ vectorization: it's just linalg on buffers same as VMVX, and the patterns are fairly mundane:
https://github.com/iree-org/iree/blob/7be9646d849e057a1b78f2d144d5daa9e9157ecf/compiler/src/iree/compiler/Codegen/VMVX/LowerLinalgMicrokernels.cpp#L753-L794

We could reuse the VMVX dialect and patterns for this - then in addition to the VMVX->VM lowering we'd have a VMVX->LLVM IR lowering that gets added somewhere in here: https://github.com/iree-org/iree/blob/7be9646d849e057a1b78f2d144d5daa9e9157ecf/compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp#L973-L986

Or we could just use extern calls - I think that'd be easier and require less boilerplate - you write the pattern to make a call and then write the C function and be done. Let the ConvertToLLVM pass lower the extern func.func and func.call to the llvm.func and llvm.call. The VMVX dialect gives us insulation against version changes that can happen when the runtime is deployed independently from the produced vmfbs and that's not a problem in the AOT world as the pattern in the compiler and the linked in library are always in sync so it's not really worth using unless it is easier. I haven't tracked upstream stuff and maybe there's already patterns that can be used for interoping LLVM IR and this kind of stuff.

So in the end we're just talking about making extern calls to common code, on one route we do that via VM calls and link the common code into the runtime and on the other we do that via LLVM calls and link the common code into the executable libraries.

(I hope to at some point make this mostly the same by removing the need for vm import lowering when trivial - you'd have an extern func.func and func.call and that'd end up as the vm.import and vm.call, meaning that the func->llvm lowering could source from the same input with no additional goo)

**Comment by stellaraccident** [comment]
Just chatted with Benoit and I think we are aligned. This is an experiment and we will control variables before going after complex/interleaved cases (and there are strong intuitions that it won't be required to go there). There are multiple ways this can go eventually, but we convinced ourselves that there are solutions to any needs there and we don't need to think about them right now.

We're going to divide and conquer with the VM/runtime based approach to start as that allows for quick iteration and we can easily assess our progress with traces. If we convince ourselves that is a good idea, then VMVX->LLVM (i.e. the AOT path) is mostly "just work" and can be estimated to produce some certain benefits based on the pre-cursor.

**Comment by alliemartens** [comment]
@stellaraccident @bjacob @julianwa Who is the appropriate assignee for this as a P1 item?

**Comment by julianwa** [comment]
I'm assigning to @bjacob until we know whether there's any work that needs to be done by others on this to support his prototyping.

**Comment by bjacob** [comment]
We can close this as an Issue. @stellaraccident and @benvanik have settled the matter above --- to summarize, what I was originally asking for here is not wanted. Other specific things discussed above are potentially wanted but could be split into their own more specific Issues.
