### ISSUE TITLE
Add EfficientNet-Lite0-quant and MobileBert-quant to RISC-V benchmarking infrastructure

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#9823]
### Request description

We are currently tracking the performance of the following benchmarks locally for RISC-V:

- MobileNetV1-float
- MobileBert-float
- DeepLabV3-float
- EfficientNet-Lite0-quant
- MobileBert-quant
- PersonDetect-quant

We should add EfficientNet-Lite0-quant and MobileBert-quant to our RISC-V benchmarking infrastructure.

### What component(s) does this issue relate to?

Compiler

**Comment by hcindyl** [comment]
We can add the run test to see they don't crash. However, the numerical value check may not be feasible until https://github.com/iree-org/iree/issues/9796 is addressed.

**Comment by hcindyl** [comment]
Also, "benchmarking infrastructure" currently doesn't support c API. Do we want to add the models to "presubmit" and "CI" or benchmark infrastructure?

**Comment by hcindyl** [comment]
> We can add the run test to see they don't crash. However, the numerical value check may not be feasible until #9796 is addressed.

This comment is meant for another issue. sorry.

**Comment by dcaballe** [comment]
Sorry, my bad. I copy-pasted the same tittle for both issues. This issue is only to track the the tests that should be added to the benchmarking infra. https://github.com/iree-org/iree/issues/9824 tracks the e2e/correctness testing.

**Comment by dcaballe** [comment]
Fixed by #10054. Thanks @hanhanW
