### ISSUE TITLE
Notifications for failed GitHub actions workflows

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#9857]
The way GitHub actions sends notifications is totally broken: https://github.com/github-community/community/discussions/18039

We need a way to notify the team (in particular, the build rotation and the commit author) when a postsubmit workflow fails. I've searched around, and the best thing I've found is https://github.com/dawidd6/action-send-mail. That requires a gmail login though. We are *not* going to put a google.com email password in GitHub (even in the repo secrets), so we need to come up with another way. Something like the [GMail API](https://developers.google.com/gmail/api/guides/sending) or a test gmail account with the aforementioned action. There may be other GitHub actions systems I missed as well. This probably involves consulting some internal folks on what the "right way" to do this is.

**Comment by GMNGeoffrey** [comment]
https://github.com/firebase/firebase-admin-node/tree/master/.github/actions/send-email should work. We'd need to make a [mailgun](https://www.mailgun.com/) account

**Comment by alliemartens** [comment]
@GMNGeoffrey we should add an assignee if this is truly P1. Thoughts?

**Comment by GMNGeoffrey** [comment]
Yeah it had an assignee till yesterday, but Bob is moving on to other things. Assigned myself
