### ISSUE TITLE
Track quantized models on x86 benchmarks

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#9871]
### Issue body

@dcaballe and I had a discussion and think that we also wanna track quantized models on x86 side. We have these 3 for RISC-V: 

- EfficientNet-Lite0-quant
- MobileBert-quant
- PersonDetect-quant

@pzread can you help add them to x86 benchmarks as well? Thanks!

**Comment by dcaballe** [comment]
Thanks, Hanhan! I'm tracking the performance of those three models locally. We are in the process (https://github.com/iree-org/iree/issues/9823) of adding EfficientNet and MobileBert to RISC-V benchmarks for code size and compile time tracking. It would be awesome if @pzread could help us with https://github.com/iree-org/iree/issues/9823 while working on this issue!

**Comment by alliemartens** [comment]
@pzread This looks like something we should mark as a P1 if you are going to actively work on it. Otherwise P2 - let me know!

**Comment by pzread** [comment]
Are these the quant models we want to add?

EfficientNet
https://pantheon.corp.google.com/storage/browser/_details/iree-model-artifacts/efficientnet_lite0_int8_2.tflite;tab=live_object?project=iree-oss

MobileBert
https://pantheon.corp.google.com/storage/browser/_details/iree-model-artifacts/mobilebert-baseline-tf2-quant.tflite;tab=live_object?project=iree-oss

PersonDetect
https://pantheon.corp.google.com/storage/browser/_details/iree-model-artifacts/person_detect.tflite;tab=live_object?project=iree-oss

**Comment by julianwa** [comment]
@hanhanW @dcaballe I'd like to make sure that adding models to the benchmark suite is relatively self-serve and doesn't become an ongoing responsibility for @pzread. Perhaps do this collaboratively and create documentation if there are non-obvious steps? Thanks!

**Comment by dcaballe** [comment]
> PersonDetect
> [pantheon.corp.google.com/storage/browser/_details/iree-model-artifacts/person_detect.tflite;tab=live_object?project=iree-oss](https://pantheon.corp.google.com/storage/browser/_details/iree-model-artifacts/person_detect.tflite;tab=live_object?project=iree-oss)

It's probably the same but I got it from here: https://github.com/tensorflow/tflite-micro/raw/aeac6f39e5c7475cea20c54e86d41e3a38312546/tensorflow/lite/micro/models/person_detect.tflite

> @hanhanW @dcaballe I'd like to make sure that adding models to the benchmark suite is relatively self-serve and doesn't become an ongoing responsibility for @pzread. Perhaps do this collaboratively and create documentation if there are non-obvious steps? Thanks!

That sounds good to me! Having a How-To would be great. The main unknown for me is how to compile and test this part of the infra. Is it just about adding the changes and running the buildkite bots on CI? Is there a way to test these changes locally?

**Comment by pzread** [comment]
For this kind of small changes, I usually just upload PR and test with Buildkite bots.

If you want to test locally, the docs are not completed. But https://github.com/iree-org/iree/tree/main/benchmarks documents how to build and run the benchmark suite.

For compilation statistics, we use this tool to generate the JSON report (after you build the benchmark suite) https://github.com/iree-org/iree/blob/main/build_tools/benchmarks/collect_compilation_statistics.py
