### ISSUE TITLE
iree-import-tf is crashing in several Colab notebooks

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#9925]
### What happened?

Several of our sample Colab notebooks are currently broken, with unsymbolized stack traces like
```
[2022-07-21T00:27:42Z] CompilerToolError: Error invoking IREE compiler tool iree-import-tf
[2022-07-21T00:27:42Z] Diagnostics:
[2022-07-21T00:27:42Z] TensorFlow crashed, please file a bug on https://github.com/tensorflow/tensorflow/issues with the trace below.
[2022-07-21T00:27:42Z] Stack dump:
[2022-07-21T00:27:42Z] 0.	Program arguments: /usr/src/github/iree/.notebook.venv/lib/python3.7/site-packages/iree/tools/tf/iree-import-tf /tmp/resaved_model --tf-import-type=savedmodel_v1 --tf-savedmodel-exported-names= --tf-savedmodel-tags=serve --mlir-print-debuginfo --save-temp-tf-input=/tmp/iree/colab_artifacts/mobilenet_v2_tf_input.mlir --save-temp-iree-input=/tmp/iree/colab_artifacts/mobilenet_v2_iree_input.mlir
[2022-07-21T00:27:42Z]  #0 0x0000000009e68891 (/usr/src/github/iree/.notebook.venv/lib/python3.7/site-packages/iree/tools/tf/iree-import-tf+0x9e68891)
[2022-07-21T00:27:42Z]  #1 0x0000000009e669a5 (/usr/src/github/iree/.notebook.venv/lib/python3.7/site-packages/iree/tools/tf/iree-import-tf+0x9e669a5)
```

This was first reported on the https://buildkite.com/iree/iree-samples/builds/416 nightly build (Wed 20th Jul at 5:13 PM, https://github.com/iree-org/iree/releases/tag/candidate-20220720.210).

Failing notebooks:
* [`variables_and_state.ipynb`](https://colab.research.google.com/github/iree-org/iree/blob/main/samples/variables_and_state/variables_and_state.ipynb)
* [`tensorflow_hub_import.ipynb`](https://colab.research.google.com/github/iree-org/iree/blob/main/samples/colab/tensorflow_hub_import.ipynb)

### Steps to reproduce your issue

This reproduces in both the nightly buildkite CI pipeline and when running the notebooks manually:

1. Open a notebook like [`variables_and_state.ipynb`](https://colab.research.google.com/github/iree-org/iree/blob/main/samples/variables_and_state/variables_and_state.ipynb)
2. Click `Runtime` -> `Run all`
3. Scroll to where `iree-import-tf` / `tfc.compile_module()` is run
4. See the error messages

### What component(s) does this issue relate to?

Frontends

### Version information

Started with https://github.com/iree-org/iree/releases/tag/candidate-20220720.210 . This could also be related to the TensorFlow version - Colab currently bundles 2.8.2 and we test with 2.8.0: https://github.com/iree-org/iree/blob/068b172e04e33b3d0d1b4c784f425ee759e2bfcb/build_tools/docker/samples/Dockerfile#L29

### Additional context

It's a bit surprising that notebooks failed in this way without anything else failing. We are likely missing some presubmit test coverage.

**Comment by ScottTodd** [comment]
`variables_and_state.ipynb` seems to be working in Colab now, even with TF downgraded from 2.8.2 to 2.8.0 (to match what we test with). That notebook is still failing on our CI though ([full logs here](https://gist.github.com/ScottTodd/cc557d23a7e640eb2d49c315ca51288d)).

`tensorflow_hub_import.ipynb` is failing on both Colab and our CI. The Colab error logs are like:

```
CompilerToolError: Error invoking IREE compiler tool iree-import-tf
Diagnostics:
<unknown>:0: error: could not lower resource op func.func
<unknown>:0: note: see current operation: "func.func"() ({
```
([full logs here](https://gist.github.com/ScottTodd/c5ba0f8bce9561d9e72cdc152b921eca))

**Comment by ScottTodd** [comment]
I confirmed that `tensorflow_hub_import,ipynb` actually broke between https://github.com/iree-org/iree/releases/tag/candidate-20220717.207 and https://github.com/iree-org/iree/releases/tag/candidate-20220718.208, which narrows that down to one IREE commit: https://github.com/iree-org/iree/pull/9812

**Comment by ScottTodd** [comment]
Ah, `variables_and_state.ipynb` is broken in Colab again... maybe it's flaky, or it was broken by a different release? I also tried updating the samples Docker image to use the version of TF that Colab includes (2.8.0 -> 2.8.2), but the notebook still fails locally.

This is tricky to debug. Probably time to distill some test cases (likely using TF variables, based on the logs that I've seen) and see if we can narrow down regressions + fixes that way.

**Comment by ScottTodd** [comment]
I built the TF importer from source and forked the program from [variables_and_state.ipynb](https://colab.research.google.com/github/iree-org/iree/blob/main/samples/variables_and_state/variables_and_state.ipynb) into https://github.com/iree-org/iree/blob/main/integrations/tensorflow/test/python/iree_tf_tests/uncategorized/simple_stateful_test.py

```python

class SimpleStatefulModule(tf.Module):

  def __init__(self):
    super().__init__()
    self.counter = tf.Variable(0.0)

  @tf.function(input_signature=[tf.TensorSpec([], tf.float32)])
  def inc_by(self, x):
    self.counter.assign(self.counter + x)

  @tf.function(input_signature=[])
  def get_state(self):
    return self.counter

  @tf.function(input_signature=[tf.TensorSpec([], tf.float32)])
  def set_state(self, x):
    self.counter.assign(x)

  @tf.function(input_signature=[])
  def reset_state(self):
    self.set_state(0.0)
```

error looks to be in `LowerGlobalTensors`:
```
<unknown>:0: note: Pipeline failed while executing [`mlir::iree_integrations::TF::(anonymous namespace)::LowerGlobalTensors` on 'builtin.module' operation]: reproducer generated at `/tmp/lit/iree_tf_tests/uncategorized/Output/llvmaot__simple_stateful.run.tmp/SimpleStatefulModule/reproducer__iree_llvmcpu.mlir.import-tf`
```

(here is that reproducer file: https://gist.github.com/ScottTodd/b7dc4862691640a11c1d09a51761269b)

This suggests https://github.com/iree-org/iree/pull/9804 could be a culprit (cc @jpienaar )

**Comment by jpienaar** [comment]
That seems likely, is there more of an error reported? E.g., I expect there to be an error from the pass reported before just failing.

**Comment by ScottTodd** [comment]
> That seems likely, is there more of an error reported? E.g., I expect there to be an error from the pass reported before just failing.

I don't see a clear error (it's also been a while since I've touched this part of the stack), but here are various logs I collected: https://gist.github.com/ScottTodd/5b314c9758e33e5f4fcb80d76a78b1a3

**Comment by jpienaar** [comment]
Mmm, compiling at head and using the above gist I get:

```sh
iree-tf-opt --iree-tf-saved-model-lower-global-tensors ir_before_crash.mlir
```

```mlir
module attributes {tf.versions = {bad_consumers = [], min_consumer = 12 : i32, producer = 987 : i32}, tf_saved_model.semantics} {
  ml_program.global private mutable @counter(dense<0.000000e+00> : tensor<f32>) : tensor<f32>
  func.func @__inference_get_state_120() -> (tensor<f32> {tf_saved_model.index_path = []}) attributes {tf._construction_context = "kEagerRuntime", tf._input_shapes = [#tf_type.shape<>], tf.signature.is_stateful, tf_saved_model.exported_names = ["get_state"]} {
    %0 = ml_program.global_load @counter : tensor<f32>
    return %0 : tensor<f32>
  }
  func.func @__inference_inc_by_190(%arg0: tensor<f32> {tf._user_specified_name = "x", tf_saved_model.index_path = [0]}) attributes {tf._construction_context = "kEagerRuntime", tf._input_shapes = [#tf_type.shape<>, #tf_type.shape<>], tf.signature.is_stateful, tf_saved_model.exported_names = ["inc_by"]} {
    %0 = ml_program.global_load @counter : tensor<f32>
    %1 = chlo.broadcast_add %0, %arg0 : (tensor<f32>, tensor<f32>) -> tensor<f32>
    ml_program.global_store @counter = %1 : tensor<f32>
    return
  }
  func.func @__inference_reset_state_300() attributes {tf._construction_context = "kEagerRuntime", tf._input_shapes = [#tf_type.shape<>], tf.signature.is_stateful, tf_saved_model.exported_names = ["reset_state"]} {
    %0 = mhlo.constant dense<0.000000e+00> : tensor<f32>
    ml_program.global_store @counter = %0 : tensor<f32>
    return
  }
  func.func @__sm_exported___inference_set_state_260(%arg0: tensor<f32> {tf._user_specified_name = "x", tf_saved_model.index_path = [0]}) attributes {tf._construction_context = "kEagerRuntime", tf._input_shapes = [#tf_type.shape<>, #tf_type.shape<>], tf.signature.is_stateful, tf_saved_model.exported_names = ["set_state"]} {
    ml_program.global_store @counter = %arg0 : tensor<f32>
    return
  }
}
```

(e.g., no error and pass completes).

**Comment by ScottTodd** [comment]
`iree-tf-opt --iree-tf-saved-model-lower-global-tensors ir_before_crash.mlir` also succeeds for me, while the full `iree-import-tf` or `tfc.compile_module()` runs both fail.

**Comment by jpienaar** [comment]
TSAN for the win as expected :) Now to figure out why (this pass is Module level pass)

**Comment by ScottTodd** [comment]
Verified these are fixed now. Thanks, @jpienaar !
https://buildkite.com/iree/iree-samples/builds/430 (one new failure is fixed in https://github.com/iree-org/iree/pull/9997, unrelated to the issue here)
