### ISSUE TITLE
Add e2e tests for reduction fusions

### ISSUE THREAD

**Issue by okkwon** [iree-org/iree#9938]
### Request description

It would be nice to have e2e tests for the reduction fusion. This would include softmax and normalization patterns. 

Iterate over all the benchmarks and extract out the patterns including dynamic shapes.

### What component(s) does this issue relate to?

Compiler

**Comment by alliemartens** [comment]
Hey @okkwon @MaheshRavishankar sounds like maybe a P2 'nice to have'? What do you think?

**Comment by alliemartens** [comment]
@okkwon @MaheshRavishankar Please help to give this a priority within codegen.

**Comment by alliemartens** [comment]
@okkwon @MaheshRavishankar Please help to give this a priority within codegen.

**Comment by okkwon** [comment]
I set the priority to 2. I am working on it.

**Comment by okkwon** [comment]
Done.
