### ISSUE TITLE
libzstd mis-detecting on MacOS Github Action runners

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#9955]
GitHub actions does install libzstd, but it is not universal so it detects from CMake and fails at build time.

For the moment, just deleting it in the runner. Need to come up with a better solution.

**Comment by alliemartens** [comment]
@GMNGeoffrey @julianwa @jpienaar Can you help triage?

**Comment by ScottTodd** [comment]
No longer seeing this issue.
