### ISSUE TITLE
Better define testing tools

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#9976]
Related to #9881, I'm noticing quite a few places where a CI build job needs an entire massive directory just so it can poke into it and get a single binary. Examples include getting the entire host build directory just for FileCheck in the RISCV64 build and checking out all submodules just for lit.py. We should better define the artifacts needed for testing and package them up for various builds. I think the best thing would be trying again for installable tests, but even if it's not that, we should be able to do a better job here.

**Comment by ScottTodd** [comment]
Stale issue, sort-of addressed by moving to package-based CI (https://github.com/iree-org/iree/issues/16203)
